### ISSUE TITLE
Rectangular Select

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1007]
### Description

Rectangular selection as per https://github.com/3drepo/3drepounity/issues/113

### Goals
- [x] Being able to perform rectangular select from the UI
- [x] Being able to start rectangular select the hold of the shift key

### Tasks
- [x] Update unityUtil to control rectangular select
- [x] with the nodes returned from unity, perform highlighting through it
- [x] Try to get it to work with the shift key
