### ISSUE TITLE
Bugs 2.11.4

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1011]
- [x] Cookies page empty
- [x] [Clash - previous revision of Target models set by default](https://github.com/3drepo/3drepo.io/issues/1011#issuecomment-395365041)
- [x] [Compare card - Change eye icons to tick box](https://github.com/3drepo/3drepo.io/issues/1011#issuecomment-395366483)
- [x] [Clash doesn't work after Diff](https://github.com/3drepo/3drepo.io/issues/1011#issuecomment-395376594)
- [x] [Can't export BCF in Sample Project](https://github.com/3drepo/3drepo.io/issues/1011#issuecomment-395415949)
- [x] [Use dd/mm/yyyy date format](https://github.com/3drepo/3drepo.io/issues/1011#issuecomment-395414769)

**Not coding bugs - we need a dump of a new sample project to fix**
- [Some groups are empty in Sample Project - Lego Federation](https://github.com/3drepo/3drepo.io/issues/1011#issuecomment-395414769)

**Can't reproduce**
- [Processing... message not displayed when uploading model](https://github.com/3drepo/3drepo.io/issues/1011#issuecomment-395428050)

**Comment by paloknapo** [comment]
Cookies page empty

![image](https://user-images.githubusercontent.com/760452/41090938-50f088d6-6a3d-11e8-973b-bb97051bffab.png)

**Comment by carmenfan** [comment]
this is a devOps problem, as the policies aren't stored in the code base. I've fixed this now.

**Comment by paloknapo** [comment]
Compare card - Change eye icons to tick box

![image](https://user-images.githubusercontent.com/760452/41093223-ac068d1a-6a42-11e8-81e9-9cc1dd78be26.png)

**Comment by paloknapo** [comment]
**Clash doesn't work after Diff**

1. open Lego Federation
2. go to Compare and Diff with default settings
3. finish Diff and go to Clash
4. leave only Architecture on in Base and Structure in Target
5. Clash - all goes red as Target shows the whole federation
6. finish Clash
7. Show All doesn't show Structure model

https://www.dropbox.com/s/zhk9iohc0iw66n7/Clash%20bug.mp4?dl=0

**Comment by paloknapo** [comment]
**Some groups are empty in Sample Project - Lego Federation**

![image](https://user-images.githubusercontent.com/760452/41101644-a01414fe-6a5c-11e8-88bf-2b9086895eaa.png)

**Comment by paloknapo** [comment]
**Can't export BCF in Sample Project **

{"message":"Group not found","status":404,"code":"GROUP_NOT_FOUND","value":50,"place":"GET /issues.bcfzip"}

**Comment by paloknapo** [comment]
**Issue content not displayed to a user with Viewer role**

![image](https://user-images.githubusercontent.com/760452/41103292-af3c152c-6a60-11e8-95cb-4174d1365873.png)
Also, this pops up in console when selecting model in Assign Permissions > Models/Federations
![image](https://user-images.githubusercontent.com/760452/41103427-07e898e4-6a61-11e8-9ffd-5d667f71b755.png)

**Comment by paloknapo** [comment]
**Processing... message not displayed when uploading model**

Displayed after refresh.
