### ISSUE TITLE
Saved Views issues

### ISSUE THREAD

**Issue by sergibot** [3drepo/3drepo.io#1043]
### Bug list
- [x] [SV doesn't show which plane is being Clipped (EDIT - unless Clip was in Y plane !?!)](https://github.com/3drepo/3drepo.io/issues/1043#issuecomment-399416492)
- [ ] [selection in card not adjusted upon creation](https://github.com/3drepo/3drepo.io/issues/1043#issuecomment-399441172)
- ~~[Enhancement: should Saved Views save isolation/hidden selection?](https://github.com/3drepo/3drepo.io/issues/1043#issuecomment-399458146)~~ Saving groups should be limited to groups/issues
- [x] [Back button remains after SV creation](https://github.com/3drepo/3drepo.io/issues/1043#issuecomment-399485827)
- [x] [Deleting a SV when editing name greys out create SV button](https://github.com/3drepo/3drepo.io/issues/1043#issuecomment-399494105) Resolved in #1052

**Comment by sergibot** [comment]
SV doesn't show which plane is being Clipped
### Description
Saved Views does store Clipping information but only shows the user the number (which isn't helpful information) - it doesn't show which plane is being Clipped (x/y/z buttons are all unticked), and the slider remains at the point it was at before the Saved View was accessed.

### Pictures of the problem
before any saved view selected
![image](https://user-images.githubusercontent.com/33570931/41775130-8c60a05c-761a-11e8-8a91-755d3eee2ece.png)
when first saved view selected (note that slider hasn't moved even though number has changed)
![image](https://user-images.githubusercontent.com/33570931/41775144-ac426568-761a-11e8-8079-53b46bd317e2.png)
second saved view
![image](https://user-images.githubusercontent.com/33570931/41775168-c731d4ee-761a-11e8-8420-e9981fdbe6b7.png)

**Comment by sergibot** [comment]
selection in card not adjusted upon creation
### Description
When a new Saved View is created, the View selected in the Views card remains what it was before the new View's creation - and the new View appears below such that the user is forced to scroll down to find it!
### GIF of the problem
![new saved view not selected upon creation](https://user-images.githubusercontent.com/33570931/41778852-e67303e8-7627-11e8-8b2d-8a8e9bb75b7f.gif)

**Comment by sergibot** [comment]
Enhancement: Saved Views save isolation/hidden selection?
### Description
Should Saved Views also save hidden/isolated models, exactly as Issues does?
Currently doesn't save this information - what if users start hiding objects from view instead of using the Clip tool, especially since the Selection Box (shift-clickdrag) makes this very easy?

**Comment by sergibot** [comment]
Back button remains after SV creation
### Description
After a Saved View is created, the button in the top left of the SV card should return to a camera icon, but doesn't until it is clicked
### Picture of the error
![image](https://user-images.githubusercontent.com/33570931/41785615-126b9b8c-763b-11e8-9171-30ae9a172b28.png)

**Comment by sergibot** [comment]
Deleting a SV when editing name greys out create SV button
### Description
The add view button becomes unusable if user deletes a view while editing that view's name. 
This is because add view button is greyed out when user starts editing a view's name, but isn't returned from greyed out state when that view is deleted - and so button is left in greyed out state (until the user opens and then _exits_ a different view's edit-name box).
### GIF of the problem
![edit dlt sv bug](https://user-images.githubusercontent.com/33570931/41786814-67dca234-763e-11e8-8c9c-8b90d591f72e.gif)

**Comment by carmenfan** [comment]
closing in favour of #1114 for the last remaining task
