### ISSUE TITLE
Additional HERE Map Tiles

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1057]
### Description
Additional HERE Map Tiles

### Goals
Add all the tiles!

### Tasks

- Normal Street Map
- [x] Terrain Map
- Satellite Map
- [x] Hybrid Map
- [x] Color-reduced Street Map
- [x] Color-reduced Transit Map
- [x] Truck Restrictions Map
- [x] Transparent Truck Restrictions Map
- [x] Fleet Vehicle Map (avail. through req.query)
- [x] Toll Zone Map
- [x] Hi-Res Map Tiles (avail. through req.query)
- [x] Foreign Language Support (avail. through req.query)
- [x] Support for Multiple Languages (avail. through req.query)
- [x] Mobile Optimization (avail. through req.query)
- [x] Map Tile Type Information
- ~~Map Tile Meta Data~~
- ~~Base64 Encoded Map Tile~~
- ~~Multiple Base64 Encoded Map Tiles~~
- ~~Copyright Information~~
- [x] Display Points of Interest
- [x] Filtering Points of Interest (avail. through req.query)
- [x] Point of Interest Categories (avail. through req.query)
