### ISSUE TITLE
Permissions bugs

### ISSUE THREAD

**Issue by sergibot** [3drepo/3drepo.io#1063]
### Permissions bug list
- [ ] [changing project permissions erases model permission sets](https://github.com/3drepo/3drepo.io/issues/1063#issuecomment-406328719)
- [ ] [box size refresh](https://github.com/3drepo/3drepo.io/issues/1063#issuecomment-406531331)
- [ ] [making user teamspace admin wipes model/fed permission settings BUT NOT project permission settings](https://github.com/3drepo/3drepo.io/issues/1063#issuecomment-406547615)
- [ ] [user listing methods absolutely random for project and models/fed permissions](https://github.com/3drepo/3drepo.io/issues/1063#issuecomment-406566381)
- [ ] [Permissions box bottom not aligned](https://github.com/3drepo/3drepo.io/issues/1063#issuecomment-406579286)
- [ ] [other teamspace admins get 500 internal error when edit permissions for fed](https://github.com/3drepo/3drepo.io/issues/1063#issuecomment-407018539)
- [ ] [why not put the tooltips on the Admin/Viewer/etc above, instead of on every single button?](https://github.com/3drepo/3drepo.io/issues/1063#issuecomment-407040696)
- [ ] [project and model names allowed to display too long in permission selection menus](https://github.com/3drepo/3drepo.io/issues/1063#issuecomment-407056702)
- [ ] [looks like as admin of someone else's teamspace a user can change the owner's permissions](https://github.com/3drepo/3drepo.io/issues/1063#issuecomment-407120679)

### Permissions bugs filed elsewhere on GitHub
- [long usernames push Permissions options out of alignment](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-395720543)
- [Assign Permissions page lets users attempt to grant permissions to projects they are not admins for](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-405315149) 
- [permissions - should viewers&commenters be able to see GIS info?](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-405952749)
- [permissions - should viewers&commenters be able to download the model they're viewing/commenting?](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-405953759)
- [federation collaborators see "permissions" option in fed option list](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-405969595)
- [Scroll bar appears when Assigning Permissions (models only, not feds)](https://github.com/3drepo/3drepo.io/issues/993#issuecomment-405290065)
- [Permissions options not very aligned with buttons](https://github.com/3drepo/3drepo.io/issues/993#issuecomment-405308241)
- [extra comma after list of submodels (in alert re federation permissions)](https://github.com/3drepo/3drepo.io/issues/993#issuecomment-405309416)

**Comment by sergibot** [comment]
changing project permissions erases model permission sets

### Description
If a user changes another user's project permissions, the individual model/fed permissions for that user are all reset to "unassigned"!
(I know because I changed testing12's project permissions and it just wiped all of the permissions I had set for testing12 in the models/fed permissions tab. The other account I was changing the permissions for, "testing23", was happily unaffected.)

### GIF of the problem 
![permissions erase when proj perm change](https://user-images.githubusercontent.com/33570931/42954398-80486a24-8b74-11e8-8535-ef57320bfe11.gif)
WALKTHROUGH:
here the permissions for the account "testing12" are changed...
0 - earlier I set testing12 to have admin permissions for project "onshapeformattesting"
1 - I give testing12 commenter permissions for model "house 3b" (in project "tests")
2 - I change testing12's project permissions for "onshapeformatting" to "unassigned"
3 - testing12's permissions for model "house 3b" in project "tests" has been changed to "unassigned"

**Comment by sergibot** [comment]
box size refresh

### Description
Just being OCD here - the permissions box resizes itself every time the user switches between permissions tabs. The number of users which the main user can grant permissions to will be the same for each tab, and this number is dictated by the number of users the main user has granted licences to...?

### GIF of the problem
![permissions box size unnec refresh](https://user-images.githubusercontent.com/33570931/42992671-0afc7caa-8c01-11e8-8a2a-3405e3229c15.gif)

**Comment by sergibot** [comment]
making user teamspace admin wipes model/fed permission settings BUT NOT project permission settings

### Description
When teamspace admin permission is granted to a user but then removed, the system remembers project permissions if they were open in the permissions menu during the process, but forgets all other permissions (and forgets project permissions if the options in the drop-down menus on the permissions tabs were at all changed).
This is a weird one...

### GIF of the problem
situation A - where project "tests" is left selected in the drop-down menus throughout the teamspace admin permissions granting and removal
![permissions diff memory after tspace admin onoff](https://user-images.githubusercontent.com/33570931/42995100-e91f9fa2-8c07-11e8-95a6-58988096fbe6.gif)
situation B - where the drop-down menus are changed away from models within project "tests" in the model/fed permissions section and this somehow allows the system to wipe the permissions for project "tests"
![perm tspace onoff 1](https://user-images.githubusercontent.com/33570931/42995664-522ec1f2-8c09-11e8-934d-6bdf1093b8e6.gif)

**Comment by sergibot** [comment]
user listing methods absolutely random for project and models/fed permissions

### Description
The order in which the users appear seems alphabetical sometimes, seems to distinguish admins from other permissions sometimes, seems to distinguish teamspace admins from only project admins sometimes, etc, on a seemingly entirely random basis. 

### Picture of the problem zone
![image](https://user-images.githubusercontent.com/33570931/42998897-b9713d72-8c13-11e8-81bc-2da0b637eaf4.png)

**Comment by sergibot** [comment]
Permissions box bottom not aligned

### Description
The bottoms of the bar on the left and the Permissions box are not in line. 

### Picture of the problem
![image](https://user-images.githubusercontent.com/33570931/43001235-74dcb958-8c1c-11e8-9a60-46a6eef4a366.png)

**Comment by sergibot** [comment]
other teamspace admins get 500 internal error when edit permissions for fed

### Description
If user A grants teamspace admin permission to user B, and if user B then clicks the Permissions option in the menu for a federation, they are directed to the Permissions page but get an internal error pop-up.

User B **is able to** edit the permissions for that federation, but cannot get to the correct permissions menu to do so via this Permissions option in the federation menu.

### GIF of the problem
![fed permissions 500error but works](https://user-images.githubusercontent.com/33570931/43072767-23f3a2d6-8e6f-11e8-99ca-ac9dd9188227.gif)

**Comment by sergibot** [comment]
ok that admins of teamspaces can't unadmin themselves but of projects can?

### Description
It is currently possible for a user with admin permissions for a project on a different user's teamspace to remove that permission (to de-admin themselves from that other user's project), but impossible for a user with admin permissions for a different user's teamspace to remove that teamspace-admin permission (to de-admin themselves from that other user's teamspace). This is just to raise this, in case it should be otherwise.

### Pictures of the problem
![image](https://user-images.githubusercontent.com/33570931/43088854-20bee112-8e9b-11e8-9165-5c6aba0a005d.png)
![image](https://user-images.githubusercontent.com/33570931/43088890-397b1342-8e9b-11e8-9261-1a26b18f3afd.png)

**Comment by sergibot** [comment]
looks like as admin of someone else's teamspace a user can change the owner's permissions

### Description
It appears to be possible - though thankfully it is not - for a user who has admin permissions for a different user's teamspace to change the permissions of the owner of that other teamspace. They cannot change their own permissions on models, but it appears like they can change the permissions of the owner. 

### GIF of the problem
![looks like other user admin can affect owner permissions](https://user-images.githubusercontent.com/33570931/43090116-6859b792-8e9e-11e8-88c9-6da42a9504be.gif)
(here the active user is "testing12" who has admin permissions for the teamspace of user "Sergi")

**Comment by carmenfan** [comment]
@sergibot 

It's probably worth testing the new User Management tab to see if any of these are still relevant.
