### ISSUE TITLE
SafetiBase

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1069]
### Description
SafetiBase is a risk register in 3D Repo developed as stand-alone feature. Integration with SharePoint on API level is possible. It allows user to create a geo-located Risk associated with objects in BIM model and more. 

Specification extends 3D Repo’s Issues schema which is aligned with BCF schema.

### Goals

Attribute | Optional | Description
-- | -- | --
Name (name) | No | User defined title of Risk
User (owner) | No | Automatically filled in username
Date (created) | No | Automatically filled in date created
ID (safetibase_id) | No | GUID generated by 3drepo.io (or pulled via API in case of integration with SharePoint)
Associate Activity (associated_activity) | Yes | List of default and user defined activities (as Issue Type)
Description (desc) | Yes | Risk description
Screenshot (viewpoint.screenshot) | No | Created by user with mark-up or automatically if not user specified
Owner (assigned_roles) | No | Assigned owner of Risk (as Issue Assign)
Category (category) | Yes | List of default and user defined categories (as Issue Type)
Risk Likelihood (likelihood) | Yes | List of default values (as Issue Priority)
Risk Consequence (consequence) | Yes | List of default values (as Issue Priority)
Level of Risk (level_of_risk) | Yes | Automatically set following Risk Assessment Matrix
Mitigation Status (mitigation_status) | Yes | List of default values (as Issue Status)
Mitigation (mitigation_desc) | Yes | Mitigation description
Pin (position, norm) | No | Pin placed by user. Type reflects Level of Risk

Associated Activity (default list, can be extended by user in project settings)
--
Cleaning and maintenance
Replacement
UNSET

Risk Likelihood, Risk Consequence, Level of Risk  (default list, can’t be changed by user)
--
Very Low
Low
Moderate
High
Very High
UNSET

Category (default list, can be extended by user in project settings)
--
Health - Material effect
Health - Mechanical effect
Safety Issue - Fall
Safety Issue - Trapped
Safety Issue - Event
Safety Issue - Handling
Safety Issue - Struck
Safety Issue - Public
Environmental Issue
Commercial Issue
Social Issue
Other Issue
UNKNOWN
UNSET

Mitigation Status (default list, can’t be changed by user)
--
Proposed
Approved
Accepted
UNSET

### Tasks
- [x] Finalise the schema
- [x] Finalise the UI
- [x] Backend endpoints
- [x] Implement frontend
- [x] Chat server
- [x] Refactor issue-screen-shot component out of issues
- [x] Refactor stringSearch out of risks (and others)
- ~~Integration with Sharepoint~~ move to v2 as still waiting for Sharepoint access
