### ISSUE TITLE
Minor Issues 2

### ISSUE THREAD

**Issue by sergibot** [3drepo/3drepo.io#1075]
### Description
The "[Minor Issues](https://github.com/3drepo/3drepo.io/issues/1014)" issue was getting a bit out of hand, so starting a new issue to make the list manageable.

### Bug List:
- [x] [Cancel button not responsive on Remove Licence](https://github.com/3drepo/3drepo.io/issues/1075#issuecomment-410653339)
- <del> [funky errors when input any of #./? into job creator](https://github.com/3drepo/3drepo.io/issues/1075#issuecomment-410764896) </del> created its own issue @ https://github.com/3drepo/3drepo.io/issues/1322
- [ ] [uploading .stl files gives delayed/no error](https://github.com/3drepo/3drepo.io/issues/1075#issuecomment-411107117)
- [ ] <del> [bottom portion of screen unclickable](https://github.com/3drepo/3drepo.io/issues/1075#issuecomment-412814053) </del> can't really fix this.
- [ ] [squished comment screenshots](https://github.com/3drepo/3drepo.io/issues/1075#issuecomment-413912139)
- [ ] [selecting in diff compare only selects in base not target](https://github.com/3drepo/3drepo.io/issues/1075#issuecomment-417689406)
- [x] [Login: with username and no password, hitting enter brings up "Missing or invalid arguments"](https://github.com/3drepo/3drepo.io/issues/1075#issuecomment-418134616)

**Comment by sergibot** [comment]
Cancel button not responsive on Remove Licence

### Description
Clicking the Cancel button doesn't do anything on the Remove Licence confirmation pop-up (only visible if the user whose licence is being removed has permissions on any models).
Clicking outside of the pop-up window closes the pop-up window successfully.

### GIF of the problem
![lic-remv-cancel notworking](https://user-images.githubusercontent.com/33570931/43710082-811cb554-9966-11e8-8c29-7ce10db4481e.gif)

**Comment by sergibot** [comment]
funky errors when input any of #./? into job creator

### Description
When a job is created with a # or a . or a / or a ? in the job name, the remove job button (red minus sign) doesn't work and brings up an error message pop-up. This error pop-up's contents gets interesting...
. # or ?    - the bold text in the pop-up says Model not found
/    - there is no bold text at all 
,./<>?\|    - no bold text at all
;'#:@~    - job not found
?|,./    - model not found
!?|,./    - job not found (and this result emerges for @?|,./ and {}?|,./ and ¬?|,./ etc)

Easy solution: limit what types of character job names can contain? E.g. pure alphabetical, or alphanumeric? 

### Pictures of the problem
![image](https://user-images.githubusercontent.com/33570931/43728314-a13b2a1a-999c-11e8-83f8-136ecf62b9c7.png)
![image](https://user-images.githubusercontent.com/33570931/43728325-abfa87ac-999c-11e8-8c71-ea5c5c8bb62f.png)
![image](https://user-images.githubusercontent.com/33570931/43728335-b450526a-999c-11e8-8f2e-1bd0a96eb062.png)

**Comment by sergibot** [comment]
uploading .stl files gives delayed/no error

### Description
Clicking add model, then selecting a .stl file and clicking upload does one of the following:
- closes the add model pop-up window but then either does nothing (adds no model) or adds the model name to the list but leaves it with no file content, as with model "h" in the first picture below.
- closes the pop-up and has "Uploading..." next to the model name, but never progressing from this "Uploading..." status.
- closes the pop-up and proceeds through the correct series of e.g. Uploading... Processing... statuses, but then ends these statuses with one last status "Import failed: Unknown error", shown in the second picture below.

### Pictures of the error
![image](https://user-images.githubusercontent.com/33570931/43787128-328323fe-9a62-11e8-8e74-a8de7d7c3276.png)

![image](https://user-images.githubusercontent.com/33570931/43786922-b8bf57a4-9a61-11e8-8428-d4c5870ac440.png)

**Comment by sergibot** [comment]
bottom portion of screen unclickable

### Description
Mouse clicks on the bottom part of the 3D Viewer have no effect. 
The relevant part is that very low bit of the screen that would be taken up by the bottom button bar (extent etc) if it were extended horizontally such that it took up that entire bottom section of the screen.
This may confuse users who are trying to click on an object in the model that is currently in that bottom section of the screen - they wouldn't be able to click on it until they adjusted the viewer (which is unintuitive).

The same also goes for the bits in between any open cards - any clicks on the gaps between open cards do not affect the model. This is less significant because the gaps are narrow and the purpose is kind of intuitive.

### GIF of the problem
![bottom bar part unclickable](https://user-images.githubusercontent.com/33570931/44084202-05417746-9fae-11e8-8ce3-0ae1c047f501.gif)

**Comment by sergibot** [comment]
squished comment screenshots
### Description
May just be because dev is slow, but something weird happens to issue screenshots and event history when a new screenshot-comment is added. The earlier screenshot comments squish vertically and so do events.

### GIF of the problem
![issues squished event history](https://user-images.githubusercontent.com/33570931/44276470-6c650800-a23f-11e8-8415-dd5c4cd7ab0d.gif)

**Comment by sergibot** [comment]
selecting in diff compare only selects in base not target
### Description
This means that users cannot use any of the isolate/hide tools to easily view the differences between a select few objects!
As shown below - if isolate is used on a selection of objects, the objects are indeed isolated in base, but target remains as before. 
(Also affects prod.)

### GIF of the problem
![diff selection only on base not target](https://user-images.githubusercontent.com/33570931/44919670-e7491b00-ad35-11e8-8083-8c9362fca526.gif)

**Comment by carmenfan** [comment]
Mostly N/A after migration.
