### ISSUE TITLE
Automatically save helicopter speed multiplier when it's changed

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1078]
### Description
Everytime the user changes the helicopter speed, save it as default for the next time the model is loaded

### Tasks

- [x] Add heli speed in model setting schema
- [x] Add a get/put API request to read/write helicopter speed
- [x] edit frontend to load helicopter speed
- [x] edit frontend to save helicopter speed
