### ISSUE TITLE
User Management: Users Tab

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1082]
### Description
Merging "Licenses & Jobs" view with "Assign Permissions (teamspaces tab)" view into "Users" tab.
https://sketch.cloud/s/mrZ88/all/3d-repo-monday/users

### Goals
- [x] Admins can manage members and their permissions from single view
- [x] Admins can add new members to teamspace
- [x] Admins can change job title
- [x] Admins can change permissions
- [x] Admins can remove members from teamspace

### Tasks
- [x] New application state: User Management
- [x] Users list component
- [x] FAB for adding new users
- [x] Information about licences in tab's footer
