### ISSUE TITLE
User Management: Jobs tab

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1083]
### Description
We want to refresh this view a little bit and move it to "User management" view as tab.
https://sketch.cloud/s/mrZ88/all/3d-repo-monday/jobs

### Goals
- [x] Admins can add new jobs to teamspace
- [x] Admins can change current color
- [x] Admins can choose new colors
- [x] Admins can filter jobs by name
- [x] Admins can sort jobs by name or color

### Tasks
- [x] Jobs list component
- [x] FAB for adding new jobs
- [x] Color picker component
