### ISSUE TITLE
User Management: Projects permissions

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1084]
### Description
"Assign Permissions" view for projects should be redesigned to can easily set permissions for specific or multiple users.
https://sketch.cloud/s/mrZ88/all/3d-repo-monday/projects_permissions

### Goals
- [x] Admins can change project, whose permissions should be modified
- [x] Admins can set permissions for single user
- [x] Admins can set permissions for multiple users
- [x] Admins can filter user permissions list by name

### Tasks
- [x] User permissions list component
- [x] Button linked to "Model and federations permissions" view
- [x] Footer with description
