### ISSUE TITLE
User Management: Model and federations permissions

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1085]
### Description
"Assign Permissions" view for models and federations should be redesigned to can easily set permissions for specific or multiple users.
https://sketch.cloud/s/mrZ88/all/3d-repo-monday/projects_models_permissions

### Goals
- [x] Admins can change project, whose permissions should be modified
- [x] Admins can set permissions for single model
- [x] Admins can set permissions for multiple model
- [x] Admins can set permissions for single user
- [x] Admins can set permissions for multiple users
- [x] Admins can filter user permissions list by name
- [x] Admins can filter models list by name
- [x] Admins can sort user permissions list by permission type or username
- [x] Admins can sort models list by model name

### Tasks
- [x] Models list component
- [x] Button linked to "Project permissions" view
- [x] Footer with description
