### ISSUE TITLE
Refactor notification.service 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1089]
### Description
Refactor notification.service to get rid of the duplicated subscription/unsubscription code and make it one simple class to be reuse.  

### Goals
- [x] Realtime collaboration should work the same way it does now but with cleaner code

### Tasks
- [x] Make a base class for subscribing to an event
- [x] Modify consumers of the notification service to use the new interface
- [x] Simplify events name
