### ISSUE TITLE
Here Maps Bugs/Concerns List

### ISSUE THREAD

**Issue by sergibot** [3drepo/3drepo.io#1097]
### List of Here Maps Bugs/Concerns :
- [ ] [~~sometimes a few map tiles load too far away??~~ (IF the model should be in metres but has been put in in mm)](https://github.com/3drepo/3drepo.io/issues/1097#issuecomment-412799227)
- [ ] [starting GIS doesn't load in right?](https://github.com/3drepo/3drepo.io/issues/1097#issuecomment-412807762)
- [ ] [Map options in GIS Card is even more squashed than before, in Firefox (fine in Chrome)](https://github.com/3drepo/3drepo.io/issues/1097#issuecomment-412876051)

**Comment by sergibot** [comment]
### Description
Occasionally a few tiles will load a little distance beyond the rest of the tiles.


### Picture of the problem
![image](https://user-images.githubusercontent.com/33570931/44081259-3523e8a2-9fa6-11e8-9fa4-72359b0f39d0.png)
(The above image was taken after I helicoptered up a while from a model that I GIS-located at 27 / 10)

**Comment by sergibot** [comment]
starting GIS doesn't load in right?
### Description
On at least some models, opening them and turning on GIS (without rotating them at all) doesn't bring as many tiles into view as it looks like it should?
And then rotating around the model also doesn't bring in enough tiles...
And zooming out of the model doesn't bring tiles in - until the viewpoint is rotated at all, which seems to trigger it. (I'm assuming this is how it is programmed?)

### GIF of the problem
![here maps error 3](https://user-images.githubusercontent.com/33570931/44082908-880c0b0e-9faa-11e8-8b1a-e8544f888073.gif)

**Comment by carmenfan** [comment]
The tile looks massive, is this model in m but with a mm setting? (check with measure tool)

**Comment by sergibot** [comment]
Map options in GIS Card is even more squashed than before, in Firefox (fine in Chrome)
### Description
The GIS Card looks fine in Chrome but hides most of the drop-down menu beneath the Card's header in Firefox. This used to be the case but I believe it is even more hidden now?
### Picture of the problem
![image](https://user-images.githubusercontent.com/33570931/44095263-46053a52-9fd0-11e8-8839-1e648b3ebed4.png)

**Comment by carmenfan** [comment]
Tab problem is fixed along with react migration

We can't really fix user error on units
