### ISSUE TITLE
Limiting character lengths on input

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1099]
NOTE: this is a recreation of #1079, which was hijacked for email/password validation!
Also note that #1079 still contains two sub-issues as Comments: 
-[Model creation allows symbols despite saying only underscore](https://github.com/3drepo/3drepo.io/issues/1079#issuecomment-411353559)
-[GIS Reference doesn't cap coordinates](https://github.com/3drepo/3drepo.io/issues/1079#issuecomment-412830092)

### Description
There are a number of places where if a user enters too much or too weird input into text boxes, the result may be ugly and/or broken. 
The first list here is a collated list of those instances from across the GitHub issues, for easier referencing. Related/similar issues are also included.
The second list here is of the places where user input is either not currently limited enough, or not limited immediately (e.g. where the user is only informed at the end of a creation process that the name they input was not allowed - where the creation box has closed and the user is made to fill out e.g. all of a model's details again).

### Bug List
- [ ] [funky errors when input any of #./? into job creator](https://github.com/3drepo/3drepo.io/issues/1075#issuecomment-410764896)
- [ ] [filter tool doesn't work with special chars or spaces](https://github.com/3drepo/3drepo.io/issues/1008#issuecomment-395083418)
- [ ] [long usernames push Permissions options out of alignment](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-395720543)
- [ ] [add model box gives NEITHER too-long rev name error prompt NOR same-name error prompt](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-395722249)
- [ ] [add project no samename error](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-399915907)
- [ ] [no word limit in Group Descriptions](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-405284111)
- [ ] <del> [Assign Permissions page lets users attempt to grant permissions to projects they are not admins for](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-405315149) </del> _ignore for now as we're revamping it_
- [ ] [no reason given when model settings unsaveable due to symbols in model code](https://github.com/3drepo/3drepo.io/issues/1014#issuecomment-407335809)
- [ ] [GIS Reference doesn't cap coordinates](https://github.com/3drepo/3drepo.io/issues/1079#issuecomment-412830092)

### List of user input areas to limit
(When testing whether there are limits on character type, I tested symbols, emojis, and ancient Greek lettering. Where there is a limit on character type, eg in model code, these are all prohibited; but when there is no limit these are all let through (fun fact, the ancient Greek lettering even appears with the ancient accents and breath marks - it is not modern Greek).)
- [ ] model creation: model name (currently claims it's more restrictive than it is, see below); revision description (no limit at all yet)
- [ ] model settings: model name (no limits at all, see effects in pics below)
- [ ] federation settings: federation name (as per model settings)
- [ ] project name? (currently no char type limit, even accepts emojis)
- [ ] model code (restricted fine, but in model settings the restrictions need declaring, currently no indication to user of char type limit)
- [ ] topic type (maybe? currently char limit length is 139 followed by a "..." which is maybe too long?)
- [ ] profile user's full name (not username): no limits at all here, can paste 2000pages (which predictably slows the whole browser page to a halt)
- [ ] job title: length (currently kind of limited at 1,011 characters - anything beyond that returns an error pop-up that doesn't give a reason)
- [ ] issue name, issue description, issue comments: no limits at all
- [ ] group name, group description, view name: no limits at all

### Pictures of input zones that want limiting
if changed in model settings, model name has no character limit at all (quantity or type - I was able to input 2000pages here) 
(model name has 120char and some symbol/language-type limit in "add model" box - doesn't allow emojis or anc greek) 
![image](https://user-images.githubusercontent.com/33570931/43831422-fb714e82-9afb-11e8-84ee-45d499607af5.png)
![image](https://user-images.githubusercontent.com/33570931/43831443-0d82b610-9afc-11e8-8756-25823e4d652d.png)
pic of model settings, where 139 char topic type has stretched the model settings box so far that scrolling is needed (however I guess it's still useful for anyone who wants to enter a long topic type? who would, though?)
![image](https://user-images.githubusercontent.com/33570931/43832734-4996c8e0-9b00-11e8-99ef-2578d9cad7e9.png)

**Comment by Charence** [comment]
I've noticed the following for model code:

1. Model code cannot be removed by saving a blank entry
2. Model code is limited to 5 characters

**Comment by Charence** [comment]
It seems model name doesn't have a character limit.

**Comment by carmenfan** [comment]
This is mostly N/A after react migration.
