### ISSUE TITLE
Advanced issue filter

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1117]
### Description
There will be a wider and more helpful range of options in order to search for an issue. 

Preview of what it should look like:

![image](https://user-images.githubusercontent.com/42032433/44406099-bb1de500-a552-11e8-8a13-252fea36b3a1.png)

### Goals
- [ ] You must be able to filter issues by priority, status , assigned, type and range of date. 
- [ ] The tags in the same category are considered to have an "or" criteria  relation. e. g. search by status 
        tags  "in progress" and "closed" at the same time should be read as "search issues that are in progress 
        or closed
- [ ] The tags across categories have an "and" relation between them. e. g. if you search by the status tag 
       "in progress" and the date range between 1/6/2018- 10/11/2018 should be read as "search issues 
        that are in progress AND that were created between the dates 1/6/2018 and 10/11/2018 "

### Tasks
- [x] Make the logic for filtering using certain tags as well as the search field following the logic described 
       in the goals
- [x] Add slide search bar component
- [x] Create a search dropdown component
- [x] Add priority search dropdown
- [x] Add status search dropdown
- [x] Add assigned search dropdown
- [x] Add date range search dropdown
- [x] Add tags selected component 
![image](https://user-images.githubusercontent.com/42032433/44407132-3f716780-a555-11e8-9ecd-f614cbfaa14d.png)
- [ ] Add remove tags
