### ISSUE TITLE
Forgot password 

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1119]
### Description

Allowing a user to reset password using their "username" or "email".

### Goals

- [x] User will be able to click forgot password link and reset password.
- [x] When resetting password the user will be able to enter username or password. 

### Tasks

- [x] Make forgot password form a single line of input.
- [x] Query database for username or email.
- [x] Update the user's record with correct reset token.

Suggested changes from pull request. 
When username is incorrect, the user is displayed an invalid username message, this could pose a security risk.
- [x] Remove username error validation for security purposes. 
- [x] Ask user to Confirm Password on password reset form.
- The user's reset link is still accessible even after resetting password, this could pose a security risk. 
- [x] Invalidate user's reset link by removing reset token after successful password reset.
- [x] Ensure disable button is only in an active state when the following
 - [x] Password is valid and passes the strength checker. 
 - [x] Password is not weak 
 - [x] Passwords are both the same 
- [x] Refactor code.

- [x] Found bug on password-change.component.ts, where value "result.feedback.suggestions" was returning an undefined value. 
![password-bug](https://user-images.githubusercontent.com/6556019/44539066-1be82180-a6fb-11e8-9db8-af16d70e548f.gif)

### Description
When a user clicks the forgot password link, they will have to enter their username or email.

### Steps to replicate
- Click on forgot password link on login page
- Enter username or email address, 
- Click 'Request Password Change' button.

### Steps to replicate for password reset.
- Enter password 
- Type password incorrectly (error message will appear)
- retype password (Tab away from input field, to remove error message.)
- Click 'Send password request'.
