### ISSUE TITLE
Logo change

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1121]
### Description

The 3D Repo site logo requires changing. 

### Goals

- [x] Change Logo
- [x] Test for responsive sizing on all breakpoints.

### Tasks

- [x] Find where current logo is stored.
- [x] Change logo
- [x] Test on mobile and browser to ensure logo sizes correctly.
Changes from pull request
- [x] Remove black logo
- [x] Upload White logo
