### ISSUE TITLE
View/Groups Filter Search

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1124]
### Description

Adding a search filter for the views and groups panel, this is a similar to issue #1117 .

### Goals

- [x] Click on a search icon on the Groups panel, to display a search input field.
- [x] The search input will allow the user to filter by description or name. 
- [x] The above feature will also be available on the "Views" panel.
- [x]  Remove the override all tab from the view tab as not required.

### Tasks

- [x] Add search filter icon and input field.
- [x] Implement search functionality.
- [x] Test input values againest search results.
- [x] Perform a search on search filters and return new groups set.
- [x] Filter out results set to only contain search matches
- [x] replace existing groups list with new search results list. 
- [ ] Re-factor code based on existing quality.
