### ISSUE TITLE
Migration: React setup

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1132]
It'll be initial step to migrate from AngularJS to ReactJS.
This issue includes React environment setup.

### Tasks
- [x] Add necessary React packages
- [x] Extend webpack configuration
- [x] Add new generators to plop
- [x] Redesign a files` structure to split AngularJS and React code
- [x] Rewrite one, small component to test extended environment and fix potentially bugs
