### ISSUE TITLE
View Hookup to Chat

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1134]
### Description

Add the ability to create , update or delete a view in the views panel and have those updates automatically reflect in another instance of the application. 

### Goals

- [ ] Ensure changes to view are updated across all version of application.
- [ ] Be able to add, delete or update a view.

### Tasks

- [x] Create event to hookup to Socket.io.
- [x] Test by adding a view. 
- [x] Test by creating a view.
- [x] Test by deleting a view.
