### ISSUE TITLE
Redirect to the correct page once you've logged in the app

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1149]
### Description
If you are logged off and you paste a specific page url (model for example) after you've logged in you are being redirect to the page you originally wanted

### Goals
- [x] Pasting a model-related url page should show the login page if you were logged off
- [x] After you've logged in you should be redirected to the original page you pasted or the home page if you are logging in from the root page

### Tasks
- [x] Study and understand how the heck does the state manager works
- [x] Make the redirect work(?)
