### ISSUE TITLE
Copy/Paste search from chips filter

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1155]
### Description
Users wants a way to save complex searches with chips filter. The idea is that you can copy the search criteria 

### Goals
- [x] users can copy the search criteria via a button that says "copy" in the chips filter
- [x] users can paste back the criteria in the search field and converted into chips

### Tasks
- [x] Integrate ngclipboard 
- [x] Handle copy event from ngclipboard and create a string with the criteria to get copied
- [x] Handle the paste event in the chip's input and create the chips
- [x] Clear the chip's input
- [x] Make it nice
