### ISSUE TITLE
Delete all filtered groups

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1158]
### Description

Delete All in groups currently deletes all groups; change functionality to only delete shown groups if filter applied

### Goals

- [x] Delete all should delete all groups if no filter applied
- [x] Delete all should not delete filtered out groups

### Tasks

- [x] Delete all filtered groups
- [x] Consider renaming "Delete All" button
