### ISSUE TITLE
Ensuring http://3drepo.io passes the accessibilty checker.

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1166]
### Description

In order to comply with HS2 compliance, the 3DRepo website must pass accessibility checkers, currently, there are many issues to be resolved, such as adding alt tags to images.

### Goals
- [ ] Ensure website http://3drepo.io passes the accessibility checker. 

### Tasks
- [x] Add alt tags to all images, discovered when running accessibility checker: https://achecker.ca/checker/index.php
Check the following pages pass then accessibility checker 
- [x] Homepage/StarterPage
- [x] Buttons Component on Homepage.
- [x] Right Panel 
- [x] Panel Component
- [x] Viewpoints Component
- [x] Groups Component 
- [x] Tree Component
- [x] Privacy
- [x] Terms
- [x] Cookies

The following pages that require testing are http://3drepo.org
- [x] Contact Page
- [x] Pricing Page

The last check to be performed will be when the edited files have been uploaded to the latest version, we can run the checks on the URL instead of copy and paste solution used to test all the files for accessibility errors.

- [ ] Test on live site

**Comment by niblux** [comment]
All pages have been checked and verified, currently all pages pass with "No known problems", whereas a few components pass with "No know problems" and "No potential problems".

I have attempted to resolve all potential problems as best i can , however some problems don't seem to be resolved by the suggested solution, may require further work.
