### ISSUE TITLE
Bugs dev.3drepo.io 2.17.1

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1167]
Bugs:
- <del>Federation is missing in Sample project when new account is created</del> _non reproducible_
- [x] [Empty screen appears when opening model](https://github.com/3drepo/3drepo.io/issues/1167#issuecomment-423927025)
- [x] [Isolated compound disappears when saving issue](https://github.com/3drepo/3drepo.io/issues/1167#issuecomment-424409819)
- [x] [Issues: Saved visibility status broken when switching between issues](https://github.com/3drepo/3drepo.io/issues/1167#issuecomment-424412410)
- [x] [Chat server doesn't update new issues or flag changes in list view](https://github.com/3drepo/3drepo.io/issues/1167#issuecomment-424415211)
- [x] [Exit to Teamspaces from 3D Viewer lags](https://github.com/3drepo/3drepo.io/issues/1167#issuecomment-424416187)
- [x] [Filter menu not updated when chips cleared individually from filter basket](https://github.com/3drepo/3drepo.io/issues/1167#issuecomment-424655704)

UI oddities:
- [x] [Filter chips not formatted correctly on Firefox](https://github.com/3drepo/3drepo.io/issues/1167#issuecomment-424656336)

Hot fix:
- [x] [Open links in new window](https://github.com/3drepo/3drepo.io/issues/1167#issuecomment-424721397)

**Comment by paloknapo** [comment]
**Empty screen appears when opening model**

I can't reliably replicate this but I noticed it few times:

1. open new tab so Unity is not running
2. open a model

![image](https://user-images.githubusercontent.com/760452/45946531-10816200-bfe9-11e8-981b-7d4434c62211.png)

**Comment by paloknapo** [comment]
**Isolated compound disappears when saving issue**

1. go to this model
https://dev.3drepo.io/pavol/160502e5-66fd-4cca-bbc4-84f6e1623aa7
2. filter W-05 in Tree card and zoom to the object
3. select glass only and isolate
4. create and save issue
5. issue is save but object disappears

**Comment by paloknapo** [comment]
**Issues: Saved visibility status broken when switching between issues**

1. go to this model
https://dev.3drepo.io/pavol/160502e5-66fd-4cca-bbc4-84f6e1623aa7
2. open Issues card
3. select issue no.23
4. select issue no.22
5. visibility status is not updated

**Comment by paloknapo** [comment]
**Chat server doesn't update new issues or flag changes in list view**

To fix enter and exit an issue or reload

**Comment by paloknapo** [comment]
**Exit to Teamspaces from 3D Viewer lags**

Some sort of a response would be nice when user clicks on the 3D Repo logo or Teamspaces in Account Menu.

**Comment by paloknapo** [comment]
**Filter menu not updated when chips cleared individually from filter basket**

![image](https://user-images.githubusercontent.com/760452/46072329-05aa0700-c17a-11e8-98f3-e2d030b71821.png)

1. filter by for example Status
2. clear chips individually by clicking on X
3. check menu

**Comment by paloknapo** [comment]
**Filter chips not formatted correctly on Firefox**

![image](https://user-images.githubusercontent.com/760452/46072514-7bae6e00-c17a-11e8-8f77-f534cdffef5d.png)

**Comment by paloknapo** [comment]
**Open links in new window**

Change default from open in new tab to open in new window. They probably changed memory limit per tab in the latest Chrome and 3D Repo crashes when user opens 2 models. It works fine in 2 or more separate windows. 

Firefox still works fine but most of our clients use Chrome. 

![image](https://user-images.githubusercontent.com/760452/46084192-00a97f80-c19b-11e8-8637-9c87f6c85dd5.png)

**Comment by carmenfan** [comment]
> **Open links in new window**
> 
> Change default from open in new tab to open in new window. They probably changed memory limit per tab in the latest Chrome and 3D Repo crashes when user opens 2 models. It works fine in 2 or more separate windows.
> 
> Firefox still works fine but most of our clients use Chrome.
> 
> ![image](https://user-images.githubusercontent.com/760452/46084192-00a97f80-c19b-11e8-8637-9c87f6c85dd5.png)

Doesn't look like it's possible, [see here](https://stackoverflow.com/questions/12939928/make-a-link-open-a-new-window-not-tab)

**Comment by paloknapo** [comment]
Got this again

**Comment by sanmont3drepo** [comment]
Next time you get this state try entering this in the console:
`angular.element(document.body).injector().get("StateManager").state.changing = false;`

If is still blank is a different thing. 


> **Got empty screen again**
> 
> I went to Profile, Billing, then User Management, changed colour of a job and then tried to open SKANSKA federation.
> 
> ![image](https://user-images.githubusercontent.com/760452/46335475-80ae6a00-c61f-11e8-9b7b-44e8ba62c266.png)
> 
> ![image](https://user-images.githubusercontent.com/760452/46335530-b05d7200-c61f-11e8-8bb9-115307fae22a.png)
