### ISSUE TITLE
SafetiBase Bugs on 35.177.161.205

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1173]
- [x] [Status icons mismatch](https://github.com/3drepo/3drepo.io/issues/1173#issuecomment-424651307)
- [x] [Back button triggers Print command](https://github.com/3drepo/3drepo.io/issues/1173#issuecomment-424652080)
- [x] [Filter Copy button doesn't work](https://github.com/3drepo/3drepo.io/issues/1173#issuecomment-424653858)
- [x] [Risk doesn't have its own URL](https://github.com/3drepo/3drepo.io/issues/1173#issuecomment-424660014)
- [x] [Can't drop pin on selected object](https://github.com/3drepo/3drepo.io/issues/1173#issuecomment-424660859)
- [x] [Difficulty updating flags](https://github.com/3drepo/3drepo.io/issues/1173#issuecomment-424662811)
- [x] [Show pins in menu works the other way](https://github.com/3drepo/3drepo.io/issues/1173#issuecomment-425081344)
- [x] [Saved visibility status broken when switching between risks](https://github.com/3drepo/3drepo.io/issues/1173#issuecomment-426548371)

UI oddity:
- [x] [Changing Risk Likelihood and Risk Consequence activates Submit button](https://github.com/3drepo/3drepo.io/issues/1173#issuecomment-426545258)

**Comment by paloknapo** [comment]
**Status icons mismatch**

![image](https://user-images.githubusercontent.com/760452/46071328-ac40d880-c177-11e8-9d78-654174fb8354.png)
currently UNSET, should be Accepted

![image](https://user-images.githubusercontent.com/760452/46071380-ca0e3d80-c177-11e8-986b-ec6d4803592d.png)
currently Accepted, should be UNSET

**Comment by paloknapo** [comment]
**Back button triggers Print command**

![image](https://user-images.githubusercontent.com/760452/46071625-59b3ec00-c178-11e8-8012-a06a3f828bb6.png)
It goes back to list view which is OK but additional opens new tab for print which is not OK

**Comment by paloknapo** [comment]
**Filter Copy button doesn't work**

![image](https://user-images.githubusercontent.com/760452/46072042-47867d80-c179-11e8-8323-de3bf5914f9f.png)

**Comment by paloknapo** [comment]
**Can't drop pin on selected object**

I can't drop pin on some selected objects. 

1. open this model
http://35.177.161.205/pavol/d6f913ad-1432-47c3-bc46-8f551869dce6
2. select "can't drop pin on selected" risk
3. create new risk and try dropping a pin on selected floor

**Comment by paloknapo** [comment]
**Difficulty updating flags**

Sometimes I have to change flag twice to update it. 

1. open risk
2. change for example Mitigation Status to Proposed and save
3. now change flag to Approved, flag doesn't change on the first click

**Comment by paloknapo** [comment]
**Show pins in menu works the other way**

![pins](https://user-images.githubusercontent.com/760452/46147551-a58c9100-c25d-11e8-983d-e03ad2c44bdf.gif)

**Comment by Charence** [comment]
Can't drop pin on selected object (https://github.com/3drepo/3drepo.io/issues/1173#issuecomment-424660859) seems to be a side effect of multi-select being active while trying to drop a pin.

**Comment by paloknapo** [comment]
**Changing Risk Likelihood and Risk Consequence activates Submit button **

Flags are saved, just the activated Submit button is bit confusing

**Comment by paloknapo** [comment]
**Saved visibility status broken when switching between issues**

Same as here:
https://github.com/3drepo/3drepo.io/issues/1167#issuecomment-424412410

To replicate, open this risk:
http://35.177.161.205/pavol/d6f913ad-1432-47c3-bc46-8f551869dce6/risks/abe68ae0-c174-11e8-b3e6-efdde9fe1d63
and then switch to this one:
http://35.177.161.205/pavol/d6f913ad-1432-47c3-bc46-8f551869dce6/risks/1d4299e0-c6e3-11e8-8c62-79b8fcde179e

**Comment by carmenfan** [comment]
> **Saved visibility status broken when switching between risks**
> 
> Same as here:
> [#1167 (comment)](https://github.com/3drepo/3drepo.io/issues/1167#issuecomment-424412410)
> 
> To replicate, open this risk:
> http://35.177.161.205/pavol/d6f913ad-1432-47c3-bc46-8f551869dce6/risks/abe68ae0-c174-11e8-b3e6-efdde9fe1d63
> and then switch to this one:
> http://35.177.161.205/pavol/d6f913ad-1432-47c3-bc46-8f551869dce6/risks/1d4299e0-c6e3-11e8-8c62-79b8fcde179e

@Charence this was fixed via this commit on the issues side: https://github.com/3drepo/3drepo.io/commit/413f41fe44be55f0018a64839bff8094742fc73f
