### ISSUE TITLE
Add DGN as one of the accepted file formats

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1180]
### Description
Add dgn as one of the accepted file formats on both back and front end.

### Goals
The user should be able to import file from .dgn format.

### Tasks
- [x] Add .dgn as an accepted format on the front end
- [x] Add .dgn as an accetped format on the backend
- [x] Add error codes belonging to .dgn
