### ISSUE TITLE
Migration: Teamspaces

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1183]
#### Description
This issue includes migration of Teamspaces view.

#### Goals
Migration of Teamspaces view to ReactJS.
Sketch: https://xd.adobe.com/view/9180ddc9-5807-4b95-6985-2f573e452411-e7b1/

#### Tasks
- [x] Component to display data in tree view
- [x] Component to add/edit project
- [x] Component to add/edit model
- [x] Component to add/edit federation
- [x] Component to upload files
- [x] Component to display revisions
- [x] Model settings route
- [x] Refactor and move old logic to new components
- [x] Expand teamspace tab height to almost full height 
- [x] Move plus button to top right 
- [x] On load, auto expand to own teamspace, showing all projects (collapsed)
- [x] Federation should list before models
- [x] Remove icons from model and federation list
- [x] When click on a project, auto expand models and federations
- [x] Auto collapse any expanded teamspace when another teamspace is expanded
- [x] Tooltip on the new hover menu buttons
- [x] Split new model and model upload
- [x] Model upload component - show model name, latest revision info and units
- [x] Enforce revision name as compulsory on model upload
- [x] New federation pop up utilises tick-boxes to select and add-remove from/to federation
- [x] Edit federation pop up is the same as new federation, just units drop-down is frozen 
- [x] Remove the disable on going into the viewer when a new revision is being uploaded
- [x] Move button to right hand side on pop up components
- [x] Teamspace, Federation folder, Model folder shouldn't have a hover menu/hamburger button, they should only have a + button permanently showing on their rows (note how + button is now aligned with the hamburger)
- [x] Project, individual model/federations should have a hover menu, with hamburger button acting as a show/hide 
- [x] Project rows should no longer have a + button on there (as it doesn't make any sense - since the user still needs to choose whether they want a model or federation)

**Comment by simplypixi** [comment]
@carmenfan Do you know already anything about changes in this view? Did Pavol prepare mockups?

**Comment by carmenfan** [comment]
We're literally having a meeting about this now, so hopefully we can send you the info by the end of the day!

**Comment by simplypixi** [comment]
@carmenfan Perfect! ;) In this case I'll start migration of Profile page.

**Comment by simplypixi** [comment]
@carmenfan 
We have some errors while adding models.

@dleszcz gets:
![screen shot 2018-10-23 at 08 38 29](https://user-images.githubusercontent.com/5683490/47341318-01053f80-d6a1-11e8-94a5-587d81b19a2c.png)

I think it's because of RabbitMQ. What should we do to run rabbit for the project? Do we have to meet some specific requirements or just run rabbit service?

**Comment by simplypixi** [comment]
> amqp://localhost:5672

**Comment by simplypixi** [comment]
Sorry, about that ^

**Comment by carmenfan** [comment]
@simplypixi 

If you take the config I pasted (and assuming you have a C:/sharedSpace folder, or change otherwise), and you have a rabbitmq instance running on your local computer, it should "work". Obviously without 3drepobouncer if you upload a model it won't actually process it. If you guys are working on windows machine I can potentially give you the binaries to run it. 

What is it that you're having a problem with?

**Comment by simplypixi** [comment]
> @simplypixi
> 
> If you take the config I pasted (and assuming you have a C:/sharedSpace folder, or change otherwise), and you have a rabbitmq instance running on your local computer, it should "work". Obviously without 3drepobouncer if you upload a model it won't actually process it. If you guys are working on windows machine I can potentially give you the binaries to run it.
> 
> What is it that you're having a problem with?

@carmenfan 
I made exactly these steps, but it didn't work. However, I just had a "brilliant" idea and I set up rabbit according to amqplib (library, which you use on backend side) instruction. We usually set up Rabbit in a little bit different way but... now it seems to work.

Thanks for the help and sorry for making troubles!
