### ISSUE TITLE
2.17.4 Bugs

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1187]
### Bugs
- [x] [Assign permissions error](https://github.com/3drepo/3drepo.io/issues/1187#issuecomment-427100780)
- [x] [Error when opening existing risk](https://github.com/3drepo/3drepo.io/issues/1187#issuecomment-427107387)
- [ ] [Filter date fields don't work in Firefox](https://github.com/3drepo/3drepo.io/issues/1187#issuecomment-427274604)
 

### Enhancements
- [x] [Changes to Mitigation Status](https://github.com/3drepo/3drepo.io/issues/1187#issuecomment-427074697)
- [x] [Changes to Associated Activity](https://github.com/3drepo/3drepo.io/issues/1187#issuecomment-427075789)

**Comment by Charence** [comment]
**Changes to Mitigation Status**

Can we make mitigation status -
Proposed 
Agreed - Fully Mitigated (Dissapears from list)
Agreed - Partial Mitigation (Stays in list) 
Rejected (stays in list)

**Comment by Charence** [comment]
**Changes to Associated Activity (TBC)**

also i think assocaited activty should be a text box not a drop down as it seems most instances link this to a names activity in the task schedule -- Andrew

**Comment by paloknapo** [comment]
**Assign permissions error**

I can reproduce for only one model (so far). My dev account has unlimited licences. 

![image](https://user-images.githubusercontent.com/760452/46491171-e1959800-c801-11e8-86a8-695e0158d335.png)

This is the problematic mode, I haven't found anything wrong with it:

https://dev.3drepo.io/pavol/cf13169c-5beb-4480-8713-424cd237b55d?page=teamspaces

**Comment by paloknapo** [comment]
**Error when opening existing risk**

User Laika0824 (no licences) in Firefox on Mac opened risk in pavol's model:

https://dev.3drepo.io/pavol/0281719c-cf2e-41c3-aa9b-74632599b07a/risks/07031a50-c7fc-11e8-bb9d-9b115e898136

![image](https://user-images.githubusercontent.com/760452/46492185-bc565900-c804-11e8-8e18-23e39f4b8df0.png)

**Comment by paloknapo** [comment]
**Filter date fields don't work in Firefox**

![image](https://user-images.githubusercontent.com/760452/46522289-442a7a80-c87a-11e8-8c40-cb0e2feff7cb.png)

**Comment by Charence** [comment]
@paloknapo For https://github.com/3drepo/3drepo.io/issues/1187#issuecomment-427107387 is it expected that the collaborator cannot edit the risk if they are not admin, risk owner, and not assigned? I guess the system shouldn't attempt to update the risk here.
