### ISSUE TITLE
detect i.dgn and throw file unsupported error

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1206]
### Description
We support dgn but not idgn. Apparently idgn's extensions are `.i.dgn`, so we need to treat it as special case and return file format not supported.

### Goals
- dgn files should pass
- idgn files should fail

### Tasks
- [x] Add i.dgn as a non-accepted format and run check to prevent uploading
- [ ] Ensure this is also applicable on the backend. 
- [x] Display the i.dgn file error "FILE NOT SUPPORTED"

**Comment by niblux** [comment]
@carmenfan if the i.dgn file cannot be uploaded via the frontend, but someone tried to bypass the check by renaming a file and changing it's extension.
Does this mean the file contents need to be read and checked on the backend ? 
Am i on the right track ?
