### ISSUE TITLE
[GridFS Migration] Change the way we read AssetBundleList

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1219]
### Description
With https://github.com/3drepo/3drepobouncer/issues/265, we need to change the way we read asset bundle list

Note: Requires update on bouncer + db migration ran on the database for consistency.

### Goals
- [x] Asset list api should still work for models
- [x] Asset list api should still work for federations

### Tasks
- [x] Change code to read from bson instead of gridFS
- [x] Make sure it still works for models
- [x] Make sure it still works for federations
- [x] Change tests
