### ISSUE TITLE
[GridFS Migration] Read files from S3

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1223]
### Description
Files such as trees, idmap will be moved to S3. We need to read it off a reference bson and send it back to the client from S3.

### Goals
- All file reads will still work
- quota should still read accurately

### Tasks
- [x] Setup nodeJS S3 driver
- [x] Read teamspace quota from reference bson 
- [x] Read json files from S3
  - [x] fullTree
  - [x] Unity mapping
  - [x] idMap
  - [x] idToMeshes
  - [x] treePath
  - [x] modelProperties
- [x] Read Asset bundles from S3
- [x] Read original files from S3
- [x] Remove gridFS methods
- [x] Delete models needs to clean up S3
- [x] Update sample project
- [x] Fix travis
