### ISSUE TITLE
Migration: Static Pages

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1226]
**Description**

Migration of static pages to ReactJS.

- Terms & Conditions
- Privacy
- Cookies

**Tasks**
- [x] Create React component to wrap static page files
- [x] Create HTML files from pug files
- [x] Declare routes
- [x] Install HTML Webpack loader
- [x] TS configuration for HTML files
