### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1230]
### Description

Auto generation of API documentation based on block comments in backend/router/*.js

### Goals

Auto generate API documentation. We will be using http://apidocjs.com/. All endpoints need to be listed and examples provided.

See existing docs for reference: https://3drepo.github.io/3drepo.io/

### Tasks

BASIC DOCS WITH PARAMS, REQUEST TYPES, AND BASIC DESCRIPTIONS
- [ ] Auto generate using build script (yarn?)
- [ ] README
- [x] Account permission
- [x] Auth
- [x] Config
- [x] Group
- [x] History
- [x] Invoice
- [x] Issue
- [x] Issue Analytic
- [x] Job
- [x] Maps
- [x] Meta
- [x] Model
- [x] Payment
- [x] Permission Template
- [x] Plan
- [x] Project
- [x] Risk
- [x] Subscriptions
- [x] Teamspace
- [x] Viewpoint

MORE DETAILED DOCS WITH EXAMPLES , ERRORS, DETAILED DESCRIPTION WHERE REQUIRED
- [ ] Auto generate using build script (yarn?)
- [ ] README
- [x] Account permission
- [x] Auth
- [x] Group
- [x] History
- [x] Invoice
- [x] Issue
- [ ] Issue Analytic
- [ ] Job
- [ ] Maps
- [ ] Meta
- [ ] Model
- [ ] Payment
- [ ] Permission Template
- [ ] Plan
- [ ] Project
- [ ] Risk
- [ ] Subscriptions
- [ ] Teamspace
- [ ] Viewpoint

- [ ] Proof Read (for typos, missing param types)
- [ ] Run through with Carmen or Charence any incorrect values, descriptions or types.

**Comment by carmenfan** [comment]
What we should do (as this will get large), is separate into 2 folders, `end points` and `functions`.

i.e. 
`routes/endpoint/<file>` -  should only have the routes registration and its comments in there
`routes/functions/<file>` - have functions that the files in `routes/endpoint` calls.
