### ISSUE TITLE
 Create "Download JSON" button for Isssues, Risks and Groups.

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1234]
### Description

Adding a button which will allow the user to download the JSON response sent back from server into a JSON file. This file will later be used to provide data using the PowerBI platform. 

### Goals

- [ ] The user should be able to click a button to download JSON
- [ ] The JSON file should download automatically. 
- [ ] The user should be able to perform the above tasks for Issues, Risks and Groups.

### Tasks

- [x] Add a new button to each Panel object (Panel Service)
- [x] Connect logic to download button 
- [x] Store JSON response
- [ ] Save to file
   - [x] Issues
   - [x] Risks
   - [ ] Groups
      - [ ] Link based on revision ?

**Comment by niblux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Download JSON button for issues, groups etc](https://trello.com/c/KjOjITyd/3-download-json-button-for-issues-groups-etc)
