### ISSUE TITLE
Clip tool revamp

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1242]
### Description
changes needed to support https://github.com/3drepo/3drepounity/issues/110

### Goals
- Expose new clip tool facilities similar to this https://xd.adobe.com/view/8a6b23f1-36b6-4419-5fe3-78a60d7ee17d-fc5a/

### Tasks
- [x] Create the buttons as needed
- [x] Wire buttons to unityUtils 
- [x] Implement state logic
- [x] remove old component code
- [x] Ensure it works from views/issues
