### ISSUE TITLE
Dev 2.19.2 Bugs

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1244]
BUGS
- <del> [No "check your email" screen after sending register form](https://github.com/3drepo/3drepo.io/issues/1244#issuecomment-440262026) </del>
- <del> [Sample Project doesn't work](https://github.com/3drepo/3drepo.io/issues/1244#issuecomment-440266160) </del>
- <del> [BCF import errors](https://github.com/3drepo/3drepo.io/issues/1244#issuecomment-441591876) </del>
- [x] [Doubling of Issues in card](https://github.com/3drepo/3drepo.io/issues/1244#issuecomment-441609701)
- [x] [Snackbar message keeps popping up](https://github.com/3drepo/3drepo.io/issues/1244#issuecomment-441616045)
- <del> [3D Diff & Clash broken](https://github.com/3drepo/3drepo.io/issues/1244#issuecomment-441619185) </del>
- [x] [New group appears multiple times](https://github.com/3drepo/3drepo.io/issues/1244#issuecomment-441661322)
- [x] New viewpoints generated via chat service is missing a thumbnail
-  <del> [URL doesn't update after log out](https://github.com/3drepo/3drepo.io/issues/1244#issuecomment-441665103) <del>
- [x] Clip box improvement from https://github.com/3drepo/3drepounity/issues/172

UI ODDITIES 
- <del> [Teamspace collapsed when coming back from viewer](https://github.com/3drepo/3drepo.io/issues/1244#issuecomment-440267528) </del>

**Comment by paloknapo** [comment]
**No "check your email" screen after sending register form**

I only see this:
![image](https://user-images.githubusercontent.com/760452/48774654-c227d100-ecc2-11e8-9941-b1882637ebc3.png)

**Comment by paloknapo** [comment]
**Sample Project doesn't work**

When opening any model in Sample Project, no model loads in viewer and this in console:
![image](https://user-images.githubusercontent.com/760452/48775348-b0dfc400-ecc4-11e8-8953-6e4b22b9266d.png)

**Comment by paloknapo** [comment]
**Teamspace collapsed when coming back from viewer**

Expanded teamspaces should be displayed when returning from model viewer. I think this was in requirements for Apptension.

**Comment by paloknapo** [comment]
**BCF import errors**

![image](https://user-images.githubusercontent.com/760452/49008402-a8c0d200-f165-11e8-81c8-6e880a763580.png)

1.export issues from federation
2.import to sub-model
3.imported issues fail to load

**Comment by paloknapo** [comment]
**Doubling of Issues in card**
![image](https://user-images.githubusercontent.com/760452/49011895-9e0b3a80-f16f-11e8-93ac-42b6687868a1.png)
1. open this federation
https://dev.3drepo.io/Laika2011/f2d18dfc-ee97-4b39-8cf2-60673ae7dc50
2. open any issue and go back to list view

**Comment by paloknapo** [comment]
**Permissions message pops up randomly**
![image](https://user-images.githubusercontent.com/760452/49012965-0dcef480-f173-11e8-8d8a-bfdbe5195aa8.png)
Snackbar pops up every time I open model or go back to Teamspaces after setting up permissions in User Management
1. change permissions for users in your teamspace
2. open any model or federation in your teamspace

**Comment by paloknapo** [comment]
**3D Diff broken**
![broken diff](https://user-images.githubusercontent.com/760452/49013570-24764b00-f175-11e8-87fd-1bbcc4596b0c.gif)
1. open model with different revisions, for example this one
https://dev.3drepo.io/Laika2011/de9c728e-fc3a-4ddd-a5e0-a2577a4c045a?page=teamspaces
2. open Compare/3D Diff and hit compare button
3. Diff loads revisions on top of each other, highlights everything green, target model is empty
4. both revisions stay in viewer after switching Diff off

**Comment by paloknapo** [comment]
**New group appears multiple times**
Looks like chat server is multiplying when new group is created by different user.
![image](https://user-images.githubusercontent.com/760452/49020812-38c44300-f189-11e8-94c3-b977c716cc29.png)

**Comment by paloknapo** [comment]
**URL doesn't update after log out**
![image](https://user-images.githubusercontent.com/760452/49021494-a6bd3a00-f18a-11e8-945c-96d9cae65964.png)
