### ISSUE TITLE
JSON file Download

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1254]
### Description
This is Issue is associated with the following Issues
#1252 and #1234 

This is a new issue improving the work done on the #1234 , the axis on the downloaded JSON file is incorrect and requires the values not to be mirrored.

Instead of [X, Y, Z] the axis is [Z,Y,Z].

Also when the user filters the Issues, groups or risks list the filtered results need to downloaded instead of the entire list. 

JSON file for issues contains mirrored XYZ Axis. 
"Position": [ X, Z, Y ]
X Values from JSON:
**3841
3819
-3835**
Y Values from JSON: 
**-3851
3828
3829**

Y values are mirrored

Easy fix with y = number * (-1)
x **3841**     y **3851**
x **3819**     y **-3828**
x **-3835**   y **-3829**

### Goals
- [ ] Fix X,Y,Z axis errors.
- [ ] Ensure Filtered results are download if applicable and not all results.

### Tasks

- [ ] A new Group panel
- [ ] List group component
- [ ] edit group component
- [ ] new API end point to remove groups
- [ ] New database schema for groups (present it here)

### Pictures/ Gifs of the error

Corrected Values
![dev pins](https://user-images.githubusercontent.com/19904513/49018536-935aa080-f183-11e8-8cd3-16e7174fa032.JPG)
![revit pins](https://user-images.githubusercontent.com/19904513/49018547-96ee2780-f183-11e8-8340-96d58313ea1d.JPG)
![json position](https://user-images.githubusercontent.com/19904513/49018550-99e91800-f183-11e8-9f8c-0273b1a557dd.JPG)
