### ISSUE TITLE
React Migration minor bugs

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1261]
### Bugs
- [x] [User details revert to the old one upon update](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-443741200)
- [ ] [Unable to see user list in project permission](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-443746560)
- [x] [Hover buttons needs hiding depending on user permissions](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-443756452)
- [x] [Teamspace menu should remember it's state when it comes back from the viewer](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-443759803)
- [x] [Inconsistent session state between browser tabs](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-444106946)
- [x] [Moving the login page back to top middle](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-444821547)
- [x] [Making Username/password only clear upon success](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-444822161)
- [x] [Firefox bugs](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-444822758)
- [x] [Terms&Conditions, Privacy, Cookies links lead to teamspace](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-444844618)
- [x] [Redirect to last url upon login](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-444846803)
- [x] [FireFox bug - Cannot see the arrow next to "Available"](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-444887682)
- [x] [Query string should disappear when you exist the issue](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-444900619)

**Comment by carmenfan** [comment]
**User details revert to the old one upon update**
When you update the user name, the value seems to revert to the old one upon save:
![before](https://user-images.githubusercontent.com/11945337/49381812-b7caf580-f70c-11e8-988a-778f1df94ead.gif)

**Comment by carmenfan** [comment]
**Unable to see user list on model permissions**

So far we only see this on @Charence 's laptop. [see here](https://github.com/3drepo/3drepo.io/pull/1224#issuecomment-441611487)

**Comment by carmenfan** [comment]
**Hover buttons needs hiding depending on user permissions**
At the moment, all users can see all buttons regardless of access rights. We need to hide the hover buttons if the user doesn't have sufficient permission.

![image](https://user-images.githubusercontent.com/11945337/49384198-67569680-f712-11e8-8f17-4fd77fea5a5a.png)
Green: Teamspace admin only
Orange: Project admin + Teamspace admin only
Blue: Collaborator + admins only

**Comment by carmenfan** [comment]
**Teamspace menu should remember it's state when it comes back from the viewer**
If possible (?) , whatever that was opened before entering the viewer should be shown again after
![before](https://user-images.githubusercontent.com/11945337/49384797-b4873800-f713-11e8-9393-993874b74153.gif)

**Comment by simplypixi** [comment]
@carmenfan @PavolKnapo 
> * [ ]  [User details revert to the old one upon update](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-443741200)
> * [ ]  [Hover buttons needs hiding depending on user permissions](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-443756452)

Ok!

> * [ ]  [Unable to see user list in project permission](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-443746560)

It's a very difficult bug. We have the same OS and browsers as charence and we don't have that issue. @Charence I have another idea. Could you try to run the app using Chrome in private mode? Maybe one of your browser's extensions is the source of the problem.

> * [ ]  [Teamspace menu should remember it's state when it comes back from the viewer](https://github.com/3drepo/3drepo.io/issues/1261#issuecomment-443759803)

To precise: Should the previous state be remembered always whether only when the user is coming back to teamspaces?

**Comment by carmenfan** [comment]
> To precise: Should the previous state be remembered always whether only when the user is coming back to teamspaces?
I believe that's ideal, if possible :)

**Comment by carmenfan** [comment]
**Inconsistent session state between browser tabs**

- If I log in on a browser tab, it should automatically log me in on other browser tabs
- If I logged out on one, it should log me out on both
- In the event if I manage to get into the log in tab when i'm already logged in, it should just redirect me instead of telling me i'm already logged in

![before](https://user-images.githubusercontent.com/11945337/49446391-04c1d100-f7cc-11e8-92eb-880a2ffd11d7.gif)

**Comment by simplypixi** [comment]
> **Inconsistent session state between browser tabs**
> 
> * If I log in on a browser tab, it should automatically log me in on other browser tabs
> * If I logged out on one, it should log me out on both
> * In the event if I manage to get into the log in tab when i'm already logged in, it should just redirect me instead of telling me i'm already logged in
> 
> ![before](https://user-images.githubusercontent.com/11945337/49446391-04c1d100-f7cc-11e8-92eb-880a2ffd11d7.gif)

**Comment by simplypixi** [comment]
> > To precise: Should the previous state be remembered always whether only when the user is coming back to teamspaces?
> 
> @simplypixi I believe that's ideal, if possible :)

@carmenfan I think is possible but currently, I can't do that without big effort. This is because of mixed routing and different source of data. After migration, the app will have only one "source of truth", so I think it's better to wait to this moment. For now, I can handle returning to the previous state after click the logo. What do you think about it?

**Comment by carmenfan** [comment]
@simplypixi  sure, whatever you feel is most appropriate

**Comment by carmenfan** [comment]
> 
> 
> > **Hover buttons needs hiding depending on user permissions**
> > At the moment, all users can see all buttons regardless of access rights. We need to hide the hover buttons if the user doesn't have sufficient permission.
> > ![image](https://user-images.githubusercontent.com/11945337/49384198-67569680-f712-11e8-8f17-4fd77fea5a5a.png)
> > Green: Teamspace admin only
> > Orange: Project admin + Teamspace admin only
> > Blue: Collaborator + admins only
> 
> @carmenfan I've added checking permissions using permission's flags returned by BE. Is it ok?

Yes

**Comment by carmenfan** [comment]
**Moving the login page back to top middle**

![image](https://user-images.githubusercontent.com/11945337/49577813-2a6fe700-f940-11e8-93eb-f4d256297198.png)


Can we move this back to top middle alignment? Sorry, I know we agreed to this, but Business guys changed their mind after testing the dev build :(

**Comment by carmenfan** [comment]
**Making Username/password only clear upon success**

![before](https://user-images.githubusercontent.com/11945337/49577927-7a4eae00-f940-11e8-8881-449787d87615.gif)
Can we make it so the username and password stays if the login failed? Pavol was saying that it is quite an inconvenience when the user got something wrong and just have to retype the password before, but now he has to type in the whole thing again.

**Comment by carmenfan** [comment]
**No scroll bar in firefox**

Teamspace page has no scrolling capability on firefox
![image](https://user-images.githubusercontent.com/11945337/49578081-c8fc4800-f940-11e8-9a9c-0192cb3e278e.png)

**Comment by carmenfan** [comment]
**Terms&Conditions, Privacy, Cookies links lead to teamspace**

All 3 links lead to:
/dashboard/teamspaces

@simplypixi  - is this because we need to merge static pages in ?

**Comment by carmenfan** [comment]
**Redirect to last url upon login**
We seems to have lost the redirect to the url upon login thing again :( . If I try to go to a viewer link withotu logging in, the app should redirect me back to that viewer link.
https://user-images.githubusercontent.com/11945337/49582508-36ae7100-f94d-11e8-9d00-efd7a59956d4.gif

**Comment by carmenfan** [comment]
**Query string should disappear when you exist the issue**
![before](https://user-images.githubusercontent.com/11945337/49592022-f3153080-f967-11e8-9968-97a55023cac3.gif)

**Comment by simplypixi** [comment]
> **Terms&Conditions, Privacy, Cookies links lead to teamspace**
> 
> All 3 links lead to:
> /dashboard/teamspaces
> 
> @simplypixi - is this because we need to merge static pages in ?

Nope, it should work :/

**Comment by simplypixi** [comment]
> **Moving the login page back to top middle**
> 
> ![image](https://user-images.githubusercontent.com/11945337/49577813-2a6fe700-f940-11e8-93eb-f4d256297198.png)
> 
> Can we move this back to top middle alignment? Sorry, I know we agreed to this, but Business guys changed their mind after testing the dev build :(

What about the rest?  E.g sign-up, password-change

**Comment by carmenfan** [comment]
> 
> 
> > **Moving the login page back to top middle**
> > ![image](https://user-images.githubusercontent.com/11945337/49577813-2a6fe700-f940-11e8-93eb-f4d256297198.png)
> > Can we move this back to top middle alignment? Sorry, I know we agreed to this, but Business guys changed their mind after testing the dev build :(
> 
> What about the rest? E.g sign-up, password-change

Yes everything top middle aligned please :)

**Comment by carmenfan** [comment]
> 
> 
> > **Terms&Conditions, Privacy, Cookies links lead to teamspace**
> > All 3 links lead to:
> > /dashboard/teamspaces
> > @simplypixi - is this because we need to merge static pages in ?
> 
> Nope, it should work :/
> 
> -- EDIT --
> Had the user active session? If yes, this behaviour is proper (I thought we've decided to redirect to teamspaces from static pages if user is logged)
> If not, this is a bug.

Seems to only happen if the user has an active session, but static pages needs to be shown as they are legal documents. It's things like Login/Register that needs to be redirected

**Comment by simplypixi** [comment]
> > > **Terms&Conditions, Privacy, Cookies links lead to teamspace**
> > > All 3 links lead to:
> > > /dashboard/teamspaces
> > > @simplypixi - is this because we need to merge static pages in ?
> > 
> > 
> > Nope, it should work :/
> > -- EDIT --
> > Had the user active session? If yes, this behaviour is proper (I thought we've decided to redirect to teamspaces from static pages if user is logged)
> > If not, this is a bug.
> 
> Seems to only happen if the user has an active session, but static pages needs to be shown as they are legal documents. It's things like Login/Register that needs to be redirected

Ok! ;)

**Comment by dleszcz** [comment]
> **Teamspace menu should remember it's state when it comes back from the viewer**
> If possible (?) , whatever that was opened before entering the viewer should be shown again after

Hi @carmenfan, 
1. Have you made any special steps to trigger this? Because I can't reproduce it.
2. Do you know anything more about the Charence's bug?

**Comment by carmenfan** [comment]
@dleszcz It's just as described. Are you saying that the Project listing goes to the right place for you upon ging back to it from the viewer?

I notice it's pretty inconsistent, even for entering into model setting. Notice how I went back to the right state going to a model in Andrew's teamspace, but not when I go to something from mine:
![before](https://user-images.githubusercontent.com/11945337/49725340-5bfbf180-fc63-11e8-9aee-3d28511b85b2.gif)

**Comment by carmenfan** [comment]
@dleszcz @simplypixi No update re Charence's bug. I'd say if these 2 issues are the only ones left then do as much as you feel is adequate for the teamspace state issue and make a PR for this. Charence is probably not going to have time to try things out any time soon (he's on holiday tomorrow until the new year)

**Comment by dleszcz** [comment]
> @dleszcz It's just as described. Are you saying that the Project listing goes to the right place for you upon ging back to it from the viewer?

Yes:)
> I notice it's pretty inconsistent, even for entering into model setting. Notice how I went back to the right state going to a model in Andrew's teamspace, but not when I go to something from mine:

This is interesting. Can I ask you for a notice how looks local storage and URL params when you're going:
- to model settings
- back from model settings
- to viewer
- back from viewer

This can help me diagnose the reason, because on my machine everything looks fine. 
And please make sure you are on a good branch and project is rebuilt - I know that this is unlikely but sometimes it happens.

**Comment by carmenfan** [comment]
@dleszcz I tested it on this branch, it seems to work so I guess it's fixed in this branch :)

On the other hand, I spot this:
![image](https://user-images.githubusercontent.com/11945337/49735814-3d582380-fc80-11e8-9e37-eb0223bb0499.png)

There's now a massive gap between the lower and the rest of the viewer 😟  See layout in staging:
![image](https://user-images.githubusercontent.com/11945337/49735919-83ad8280-fc80-11e8-8c94-fd32a3857946.png)

**Comment by dleszcz** [comment]
@carmenfan 
Fix pushed, Can you check it now?

**Comment by carmenfan** [comment]
@dleszcz  yup looks good now :)

If you think you're done then please feel free to make a PR

**Comment by carmenfan** [comment]
@dleszcz 
Sorry just noticed, the login page no longer shows a error message when my login credentials are incorrect:
![before](https://user-images.githubusercontent.com/11945337/49740565-6bdbfb80-fc8c-11e8-94d9-40ffad3f2593.gif)

**Comment by dleszcz** [comment]
@carmenfan I created PR. Your last request included.
