### ISSUE TITLE
Dev 2.19.3 Bugs

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1263]
### Bugs
- [x] [Issue back button opens file browser (state manager)](https://github.com/3drepo/3drepo.io/issues/1263#issuecomment-444170328)
- <del> [Login wrong page layout](https://github.com/3drepo/3drepo.io/issues/1263#issuecomment-444449717) </del> in #1261
- <del> Scrolling or page up/down in teamspaces doesn't work on Firefox </del> in #1261
- <del> [User management doesn't extend to page in Firefox](https://github.com/3drepo/3drepo.io/issues/1263#issuecomment-444458548) </del> in #1261
- [x] Sample Project isn't up to date
- [x] [New assigned issue doesn't update notification](https://github.com/3drepo/3drepo.io/issues/1263#issuecomment-444466772)
- <del> [Terms&Conditions, Privacy, Cookies links lead to teamspace](https://github.com/3drepo/3drepo.io/issues/1263#issuecomment-444546926) </del> in #1261
- [x] [Download JSON doesn't work on Firefox](https://github.com/3drepo/3drepo.io/issues/1263#issuecomment-444552850)
- <del> [Clicking login button clears fields](https://github.com/3drepo/3drepo.io/issues/1263#issuecomment-444805474) </del> in #1261
- [x] [Can't rename project](https://github.com/3drepo/3drepo.io/issues/1263#issuecomment-444842937)

**Comment by Charence** [comment]
**Issue back button opens file browser (state manager)**

![dec-04-2018 16-43-50](https://user-images.githubusercontent.com/1438332/49458159-2dee5b80-f7e4-11e8-8a16-d7ae2012614a.gif)

File browser shouldn't pop up

**Comment by paloknapo** [comment]
**Login wrong page layout**

![image](https://user-images.githubusercontent.com/760452/49509974-de10a280-f87e-11e8-8515-dd19aa177240.png)

**Comment by paloknapo** [comment]
**User management doesn't extend to page in Firefox**
![image](https://user-images.githubusercontent.com/760452/49511706-c982d900-f883-11e8-813c-308bf106fd34.png)

**Comment by paloknapo** [comment]
**New assigned issue doesn't update notification**

It works for existing issue but notification isn't updated when assigning new issues.
1. create new issue
2. assign to relevant job

**Comment by paloknapo** [comment]
**Terms&Conditions, Privacy, Cookies links lead to teamspace**

All 3 links lead to:
https://dev.3drepo.io/dashboard/teamspaces

**Comment by paloknapo** [comment]
**Dowload JSON doesn't wo**

**Comment by paloknapo** [comment]
**Download JSON doesn't work on Firefox**
No file is downloaded, no error in console

**Comment by paloknapo** [comment]
**Can't rename project**
I can't rename "P&P" project in Laika0512. It happens only with this project, any other works so far.
![image](https://user-images.githubusercontent.com/760452/49581866-3c0abc00-f94b-11e8-8ff3-b895cf460b37.png)

**Comment by carmenfan** [comment]
We seems to have lost the redirect to the url upon login thing again :( . If I try to go to a viewer link withotu logging in, the app should redirect me back to that viewer link.

![before](https://user-images.githubusercontent.com/11945337/49582508-36ae7100-f94d-11e8-9d00-efd7a59956d4.gif)
