### ISSUE TITLE
Migration: List item

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1264]
### Description
List item component for Issues/SafetiBase panel in the viewer

Design: https://xd.adobe.com/view/8a6b23f1-36b6-4419-5fe3-78a60d7ee17d-fc5a/

### Tasks
- [x] Generic component to show issue/risk item on the list
- [x] (Issues) Get rid of name prefix, only numbering
- [x] overdue - name & due date in red, light red background in list view
- [x] description in list view show 3 lines only & make layout more compact
