### ISSUE TITLE
Migration: Details

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1265]
### Description
Details collapsable component for Issues/SafetiBase panel in viewer.

Design: https://xd.adobe.com/view/8a6b23f1-36b6-4419-5fe3-78a60d7ee17d-fc5a/

### Tasks
- [x] edit description - edit icon on hover, edit in place, save with main save button
- [x] description length limit ~220 characters (4 lines)
- [x] edit jobs & types as last option in drop-down, preferably type new item in place
- [x] snackbars feedback when changing flag
