### ISSUE TITLE
Migration: Log

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1266]
### Description
Log component for Issues/SafetiBase panel in viewer
Design: https://xd.adobe.com/view/8a6b23f1-36b6-4419-5fe3-78a60d7ee17d-fc5a/

### Tasks
- [x] comments with tooltips (company & user data),  can be empty
- [x] system notifications
- [x] screenshots
- [x] screenshot element in log is always same size, image crop to ratio
- [x] add timestamp to status notifications and comments

**Comment by dleszcz** [comment]
@carmenfan Now I will implement only UI, so just tell me what log object properties are supposed to be displayed there?

**Comment by carmenfan** [comment]
@dleszcz @simplypixi
My thoughts are that I'll make an endpoint with this route:
`/:teamspace/:username`

Reason for teamspace being so we can filter out user access. And only disclose this information if the user requested is a member of the teamspace.

This will return the either an error (404, 400) or a json object:

````js
{
    "user" :, 
    "First name", 
    "last name" 
     "company" 
} 
````

Will have to confirm the exact naming of the field as I am out if the office right now. Company may be empty as its not a compulsory field upon registration. 

Let me know if you have any thoughts!

I can probably whip this up tomorrow, would you want me to put it on this branch or some other branch or make a separate issue?

**Comment by dleszcz** [comment]
@carmenfan 
We're thinking about it. When there are 100 comments, we will have to make 100 additional requests - it's not efficient. It would be better to add a user object to comment (when user have access?). Can it be done like this?

**Comment by carmenfan** [comment]
@dleszcz  I know Pavol mentioned this as an tooltip but I believe this isn't really a tooltip but more of a component that appears upon hover (and he wishes this to be applied across the whole application in the future.

it's more like the component that pops up when you hover on someone on gmail:
![before](https://user-images.githubusercontent.com/11945337/50213020-60678f00-0374-11e9-8d20-27b25a0e7c49.gif)


Which is why I believe is more suited for a dynamic approach than loading it along with the api request (which can be done, yes). And it should probably be outside of the log component. Let me know your thoughts :)

**Comment by simplypixi** [comment]
@carmenfan Everything is clear now ;)

**Comment by carmenfan** [comment]
@simplypixi ok :)

so do you want me to make this api here or another issue or a completely new issue?

**Comment by dleszcz** [comment]
@carmenfan our last question ;)

> My thoughts are that I'll make an endpoint with this route:
> `/:teamspace/members/:username`

Is the teamspace needed? User's data can be different per teamspace?

**Comment by carmenfan** [comment]
> @carmenfan our last question ;)
> 
> > My thoughts are that I'll make an endpoint with this route:
> > `/:teamspace/members/:username`
> 
> Is the teamspace needed? User's data can be different per teamspace?

It cannot, it's sent to check permissions. So the user can only get data of other users if they are both members of the same teamspace. To avoid someone signing up for a free account and trying to brute force his way to extract user data

Or at least that's the thinking anyway XD

**Comment by carmenfan** [comment]
@dleszcz 
should be working now!
![image](https://user-images.githubusercontent.com/11945337/50285817-3fc33600-0455-11e9-832f-9c5fe8ac8e63.png)

**Comment by dleszcz** [comment]
Thank you @carmenfan :)
