### ISSUE TITLE
Migration: New comment

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1271]
### Description
New comment component for Issues/SafetiBase panel in viewer.

Design: https://xd.adobe.com/view/8a6b23f1-36b6-4419-5fe3-78a60d7ee17d-fc5a/

### Tasks
- [x] comment length limit ~220 characters (4 lines)
- [x] expand comment box when long comment, comment max 4 lines (~220 characters)
- [x] snackbars feedback when sending comment
