### ISSUE TITLE
Migration: Issues

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1272]
### Description
Issues panel in viewer

Design: https://xd.adobe.com/view/8a6b23f1-36b6-4419-5fe3-78a60d7ee17d-fc5a/

### Tasks
- [x] show number of displayed issues in list view
- [x] description and comment length limit ~220 characters (4 lines)
- [x] details don’t scroll and can be collapsed, only log area scrolls
- [x] remember unsaved issue when close card
- [x] focus on filter field when clicked on magnifying glass icon

### Template layout
![image 1](https://user-images.githubusercontent.com/5683490/49567794-0ce65180-f92f-11e8-836e-fa5c6155827e.png)

**Comment by dleszcz** [comment]
Hello @camden-kid 
I'd like to make sure. Should we not display issues with status 'Closed'? 
But after filtering by "Status: Closed" all closed issues should appear on the list, right?

**Comment by carmenfan** [comment]
@dleszcz yes exactly :)

**Comment by carmenfan** [comment]
The revision you're requesting doesn't exist. Looking at the database there's only 1 entry for revision and the ID starts with `97e`, your endpoint is indicating a revision id of `a6f`.
![image](https://user-images.githubusercontent.com/11945337/52047055-1f03fb00-2540-11e9-991c-1b68b4dd8f5b.png)

This is probably because the data was corrupted to begin with. I suggest creating a new issue to add comment, or try a different model.
