### ISSUE TITLE
Migration: SafetiBase

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1273]
### Description
SafetiBase panel in viewer
Design: https://xd.adobe.com/view/8a6b23f1-36b6-4419-5fe3-78a60d7ee17d-fc5a/

### Tasks
- [x] show number of displayed issues in list view
- [x] description and comment length limit ~220 characters (4 lines)
- [x] details don’t scroll and can be collapsed, only log area scrolls
- [x] add comments and system notifications in log, just comment it out for now and we will hook it up with back-end at some point
- [x] give suggestions of existing when typing associated activity if possible
- [x] remember unsaved issue when close card
- [x] focus on filter field when clicked on magnifying glass icon

### Template layout
![image 1](https://user-images.githubusercontent.com/5683490/49567794-0ce65180-f92f-11e8-836e-fa5c6155827e.png)

**Comment by dleszcz** [comment]
![screenshot 2019-01-15 at 11 41 43](https://user-images.githubusercontent.com/17221890/51460690-77771380-1d5c-11e9-98cc-00f38ad2710e.png)

Hello @carmenfan @paloknapo 
We're wondering about creating consistent removal item mechanism in Views and Risks. 
Any thoughts?

**Comment by carmenfan** [comment]
@dleszcz Can we just get rid of the delete button? Our business guys thinks safetibase should be closer to issues and risks should not be able to delete them.
