### ISSUE TITLE
Style Print Page for Issues and Risks 

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1275]
### Description

The Print feature on Issues and Risks currently has no styles. It is now required to be styled as well add a couple of small additions to the functionality such as : 
- An image size toggle, this button will increase/decrease the risk/issue screenshot. 
- A show/hide toggle button for the issues log
- A "Print Button" which will display the standard (ctrl + p) print dialog box.
### Goals

The user will now be able to click a print button which will display the built in print dialog, where they will be able to print the page or save as a PDF. The current functionality remains the same in terms of the user being able to filter the issues/risks and have the same filtered output rendered as HTML.

### Tasks

- [x] Style Page to agreed design specification.
- [x] Add print button (display standard print dialog box)
- [x] Add Show/Hide button.
- [x] Add Image Increase/Decrease button.
- [x] Change button text dynamically when clicking.
- [x] Add All Dynamic Values from backend.
- [x] Test with different models.
- [x] Test and edit if required style settings for @media print.
- [x] Repeat the above for Risks Template. 

### Pictures/Screenshots

Link to Adobe Design
https://xd.adobe.com/view/8a6b23f1-36b6-4419-5fe3-78a60d7ee17d-fc5a/screen/9bd8e816-018f-4186-9abf-591ac1a0dba7/Print-report-1

Sample screenshots 
![renderstyle](https://user-images.githubusercontent.com/6556019/49513310-81b28080-f888-11e8-90ae-82000646a220.png)
![renderhtml](https://user-images.githubusercontent.com/6556019/49513311-81b28080-f888-11e8-8270-67d7eb8f12a5.png)
