### ISSUE TITLE
Bugs 2.19.5

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1283]
- [x] [Model reloads when clicking Issues back button](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446541934)
- [x] [Clearing notification filter in Issues reloads model](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446543767)
- [x] Query string not removed when we exist a risk
- <del>[Pin not created when importing BCF](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446570852) </del> _pins from BCF were never supported_
- [x] Occasionally issue strip is not coloured by job colours
- [x] [Collaborator can't create a risk](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446600754)
- [x] [No plane selected when clipping activated in Views](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446611398)
- [ ] [Top view impossible](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446619558)
- [x] [No menu buttons when new project created](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446642112)
- [x] [Incomplete on hover menu on freshly created model](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446645059)
- [x] [Can't paste to GIS settings fields in settings](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446654036)
- [x] [GIS settings field don't allow negative values](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446655259)
- [x] [Revision name exists even if model upload fails](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446710149)
- [x] [Model upload snackbar message vanishes too quickly](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446711960)

**Comment by paloknapo** [comment]
**Model reloads when clicking Issues back button**

1. open any issue ore create new one
2. click back button to go to list view

try on this one:
https://dev.3drepo.io/viewer/pavol/0fc81a60-a920-4de3-8fb6-180c2b56c507?issueId=10fa4a90-fdfa-11e8-bae2-f1e1199ff7de

**Comment by paloknapo** [comment]
**Clearing notification filter in Issues reloads model **

1. open model by clicking on notification
2. clear Issues filter 

![image](https://user-images.githubusercontent.com/760452/49864768-2558df00-fdfb-11e8-94de-c230091711cb.png)

**Comment by dleszcz** [comment]
> **Model reloads when clicking Issues back button**
> 
> 1. open any issue ore create new one
> 2. click back button to go to list view
> 
> try on this one:
> https://dev.3drepo.io/viewer/pavol/0fc81a60-a920-4de3-8fb6-180c2b56c507?issueId=10fa4a90-fdfa-11e8-bae2-f1e1199ff7de

@paloknapo @sanmont3drepo @carmenfan 
I will deal with it now

**Comment by paloknapo** [comment]
**Collaborator can't create a risk**

**Comment by paloknapo** [comment]
**No plane selected when clipping activated in Views**

1. go to saved view with clipping box
2. activate clipping
3. no plane is selected 
Try in this model, go to View 345 and activate clipping:
https://dev.3drepo.io/viewer/Laika0512/72be56fc-1b62-4c7a-b52d-63a7a8bc6fdc

**Comment by paloknapo** [comment]
**Top view impossible**

Models spins unexpectedly when trying to navigate to top view. It used to work in the old days of X3DOM, it also snapped to top view instead of going nuts. 

![project](https://user-images.githubusercontent.com/760452/49878401-65ca5400-fe1f-11e8-9f74-19d49ed5cdca.gif)

**Comment by paloknapo** [comment]
**No menu buttons when new project created**

Neither + buttons in empty models, federations nor on hover menu in project

![image](https://user-images.githubusercontent.com/760452/49882063-b2199200-fe27-11e8-9762-767a978c0bd5.png)

**Comment by paloknapo** [comment]
**Incomplete on hover menu on freshly created model**

Works after reload.

![project](https://user-images.githubusercontent.com/760452/49882597-daee5700-fe28-11e8-9e7b-bf50b613bbda.gif)

**Comment by jozefdobos** [comment]
> **Top view impossible**
> 
> Models spins unexpectedly when trying to navigate to top view. It used to work in the old days of X3DOM, it also snapped to top view instead of going nuts.
> 
> ![project](https://user-images.githubusercontent.com/760452/49878401-65ca5400-fe1f-11e8-9f74-19d49ed5cdca.gif)

This is known as Gimbal lock and our viewer exhibits it in both the helicopter and turntable modes. Sebastian should be able to help with this using quaternions.

**Comment by carmenfan** [comment]
@dleszcz @simplypixi Can you guys take a look at [this ](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446642112) and [this](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446645059) too?

**Comment by paloknapo** [comment]
**Revision name exists even if model upload fails**

1. try uploading model which is going to fail
2. name revision
3. upload
4. after failure try again with the same revision name
5. the same name is not allowed

![image](https://user-images.githubusercontent.com/760452/49893174-b7380a80-fe42-11e8-8015-d6229e352454.png)

**Comment by paloknapo** [comment]
**Model upload snackbar message vanishes too quickly**

Pleas set message displayed time to 5 seconds across the whole application 

![project](https://user-images.githubusercontent.com/760452/49893482-67a60e80-fe43-11e8-86a3-fdfaad12a335.gif)

**Comment by dleszcz** [comment]
> @dleszcz @simplypixi Can you guys take a look at [this ](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446642112) and [this](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446645059) too?

Yes, we can

**Comment by dleszcz** [comment]
@carmenfan 
According to [this one](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446881284)
For project case - this is because on creating project backend doesn't return the permissions in new project object.
For model case - I'll push the fix in a moment

**Comment by carmenfan** [comment]
> 
> 
> @carmenfan
> According to [this one](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446648860)
> For project case - this is because on creating project backend doesn't return the permissions in new project object.
> For model case - I'll push the fix in a moment

Thanks! I've added a change on project backend and it worked :)

**Comment by simplypixi** [comment]
> **Model reloads when clicking Issues back button**
> 
> 1. open any issue ore create new one
> 2. click back button to go to list view
> 
> try on this one:
> https://dev.3drepo.io/viewer/pavol/0fc81a60-a920-4de3-8fb6-180c2b56c507?issueId=10fa4a90-fdfa-11e8-bae2-f1e1199ff7de

Fixed ;)

**Comment by simplypixi** [comment]
> **Clearing notification filter in Issues reloads model**
> 
> 1. open model by clicking on notification
> 2. clear Issues filter
> 
> ![image](https://user-images.githubusercontent.com/760452/49864768-2558df00-fdfb-11e8-94de-c230091711cb.png)

And... fixed :)

**Comment by carmenfan** [comment]
>     * [ ]  [Can't paste to GIS settings fields in settings](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446654036)
> 
>     * [ ]  [GIS settings field don't allow negative values](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446655259)
>     * [ ]  [Model upload snackbar message vanishes too quickly](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446711960)

@dleszcz @simplypixi  Can you guys look into these ones please?

for the GIS input fields, there's 2 main problems:
    - You can't input negative numbers, not easily at least 
    - Pavol can't paste into these fields but he can on simple input boxes like model name on his browser. I can, with some effort 
They can just be normal input boxes with a validation check to make it go red if it's not a number. The up/down arrows are not really used realistically.

**Comment by simplypixi** [comment]
> > * [ ]  [Can't paste to GIS settings fields in settings](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446654036)
> > * [ ]   [GIS settings field don't allow negative values](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446655259)
> > * [ ]   [Model upload snackbar message vanishes too quickly](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446711960)
> 
> @dleszcz @simplypixi Can you guys look into these ones please?
> 
> for the GIS input fields, there's 2 main problems:
> 
> * You can't input negative numbers, not easily at least
> * Pavol can't paste into these fields but he can on simple input boxes like model name on his browser. I can, with some effort (like highlighting the number then paste)
> 
> They can just be normal input boxes with a validation check to make it go red if it's not a number. The up/down arrows are not really used realistically.

Should be fixed ;)

**Comment by carmenfan** [comment]
> 
> 
> > > * [ ]   [Can't paste to GIS settings fields in settings](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446654036)
> > > * [ ]    [GIS settings field don't allow negative values](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446655259)
> > > * [ ]    [Model upload snackbar message vanishes too quickly](https://github.com/3drepo/3drepo.io/issues/1283#issuecomment-446711960)
> > 
> > 
> > @dleszcz @simplypixi Can you guys look into these ones please?
> > for the GIS input fields, there's 2 main problems:
> > 
> > * You can't input negative numbers, not easily at least
> > * Pavol can't paste into these fields but he can on simple input boxes like model name on his browser. I can, with some effort (like highlighting the number then paste)
> > 
> > They can just be normal input boxes with a validation check to make it go red if it's not a number. The up/down arrows are not really used realistically.
> 
> Should be fixed ;)

Awesome! Thanks guys!
