### ISSUE TITLE
Migration: Issues / SafetiBase components

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1284]
**Description**
Summary task

**Tasks list**
- [x] [List item](https://github.com/3drepo/3drepo.io/issues/1264)
- [x] [Details](https://github.com/3drepo/3drepo.io/issues/1265)
- [x] [Log](https://github.com/3drepo/3drepo.io/issues/1266)
- [x] [Screenshot dialog](https://github.com/3drepo/3drepo.io/issues/1268)
- [x] [Filters](https://github.com/3drepo/3drepo.io/issues/1269)
- [x] [Menu](https://github.com/3drepo/3drepo.io/issues/1270)
- [x] [New comment](https://github.com/3drepo/3drepo.io/issues/1271)
