### ISSUE TITLE
Dev 2.19.6 Bugs

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1287]
- [x] [GIS settings not saved](https://github.com/3drepo/3drepo.io/issues/1287#issuecomment-447038020)
- [x] [Notifications mark as read/unread not working](https://github.com/3drepo/3drepo.io/issues/1287#issuecomment-447038816)
- [ ] [Clicking on notification reloads even if model is opened](https://github.com/3drepo/3drepo.io/issues/1287#issuecomment-447041625)
- [x] [Close Notifications drawer after Clear all command](https://github.com/3drepo/3drepo.io/issues/1287#issuecomment-447043659)

**Comment by paloknapo** [comment]
**GIS settings not saved**

1. type or paste any numberical values
2. hit save button and go to teamspaces
3. go back and check the settings

**Comment by paloknapo** [comment]
**Notifications mark as read/unread not working**

![project](https://user-images.githubusercontent.com/760452/49953723-a5b03a80-fef6-11e8-8992-77d713f04ab3.gif)

**Comment by paloknapo** [comment]
**Clicking on notification reloads even if model is opened**

Please add condition to only filter issues if user is already in the model.

![project](https://user-images.githubusercontent.com/760452/49954149-b614e500-fef7-11e8-8dee-b61614afa332.gif)

**Comment by paloknapo** [comment]
**Close Notifications drawer after Clear all command**

Empty notifications drawer should disappear after user clears all notifications
![project](https://user-images.githubusercontent.com/760452/49954503-83b7b780-fef8-11e8-98e9-0acb8dadbe06.gif)
