### ISSUE TITLE
Smart Groups

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1326]
### Description
Rule based filter support for groups

### Goals
- Metadata filter in groups
- Endpoint/param to return object IFC GUIDs

### Tasks
- [x] Extend group schema to support rules
- [x] Filter based on rule
- [x] Filter based on rules
- [x] AND/OR/NOT of filters
- ~Groups summary endpoint (similar to issues)~
- ~Full group endpoint (similar to issues)~
- [x] Return group in PUT response
- [x] Endpoint/param to return object IFC GUIDs (add as query string option)
- ~Endpoint to return available operators and params required~
- [x] Endpoint to return all metadata fields available
- [x] Regex operator
- [x] Sanitise string inputs for non-regex operations
- [ ] Frontend

**Comment by Charence** [comment]
@simplypixi @dleszcz 

Currently, the following operators are supported by the backend:

const ruleOperators = {
	"IS_EMPTY":	0,
	"IS_NOT_EMPTY":	0,
	"IS":		1,
	"CONTAINS":	1,
	"NOT_CONTAINS":	1,
	"EQUALS":	1,
	"NOT_EQUALS":	1,
	"GT":		1,
	"GTE":		1,
	"LT":		1,
	"LTE":		1,
	"IN_RANGE":	2,
	"NOT_IN_RANGE":	2
};

The _key_ is the operator name and _value_ is the multiple of number of parameters it expects. So EQUALS will expect 1 or more values and IN_RANGE will expect 2 or multiples of 2 (i.e. 4, 6, 8...) values.

Some sample groups:

1. "BWT_S_Stone Weight" less than 5

`{
    "_id" : LUUID("bc8c8010-1a49-11e9-ae99-574ec3c3147f"),
    "name" : "LT(5) BWT_S_Stone Weight",
    "description" : "",
    "author" : "charence",
    "updatedBy" : "charence",
    "updatedAt" : 1547724130605.0,
    "createdAt" : 1547723944945.0,
    "color" : [ 
        196, 
        229, 
        56
    ],
    "rules" : [ 
        {
            "field" : "BWT_S_Stone Weight",
            "operator" : "LT",
            "values" : [ 
                5
            ]
        }
    ],
    "objects" : [ 
        {
            "account" : "charence",
            "model" : "fbfebe94-cf01-4277-9661-a15167ff984b",
            "ifc_guids" : [ 
                "3X6JoeGVf6ju_B35xwBmPW"
            ]
        }
    ],
    "__v" : 0
}`

2. "BWT_S_Stone Weight" in range 5 - 10 (Note: ifc_guids in objects are ignored if rules exist)

`{
    "_id" : LUUID("cec19a40-1a49-11e9-ae99-574ec3c3147f"),
    "name" : "RANGE(5,10) BWT_S_Stone Weight",
    "description" : "",
    "author" : "charence",
    "updatedBy" : "charence",
    "updatedAt" : 1547725683647.0,
    "createdAt" : 1547723965042.0,
    "color" : [ 
        0, 
        148, 
        50
    ],
    "rules" : [ 
        {
            "field" : "BWT_S_Stone Weight",
            "operator" : "IN_RANGE",
            "values" : [ 
                5, 
                10
            ]
        }
    ],
    "objects" : [ 
        {
            "account" : "charence",
            "model" : "fbfebe94-cf01-4277-9661-a15167ff984b",
            "ifc_guids" : [ 
                "00V9WMvBD049jor5nwkjse", 
                "05D4BOSgv0jRMVQS9cmhiK", 
                "3yis_5Fz55vet3ryR1Q0lz"
            ]
        }
    ],
    "__v" : 0
}`

3. "BWT_S_Stone Weight" equals 10 or 30 or 50

`{
    "_id" : LUUID("1bc12ec0-1a4d-11e9-a592-8b227ab4a724"),
    "name" : "EQUALS(10, 30, 50) BWT_S_Stone Weight",
    "description" : "",
    "author" : "charence",
    "updatedBy" : "charence",
    "updatedAt" : ISODate("2019-01-17T11:43:27.600Z"),
    "createdAt" : ISODate("2019-01-17T11:43:27.600Z"),
    "color" : [ 
        234, 
        32, 
        39
    ],
    "rules" : [ 
        {
            "field" : "BWT_S_Stone Weight",
            "operator" : "EQUALS",
            "values" : [ 
                10, 30, 50
            ]
        }
    ],
    "objects" : [ 
        {
            "account" : "charence",
            "model" : "fbfebe94-cf01-4277-9661-a15167ff984b",
            "ifc_guids" : [ 
                "39BPrcs7n3Rwx2CGMCingu"
            ],
            "shared_ids" : []
        }
    ],
    "__v" : 0
}`

4. "BWT_S_Stone Weight" is not empty

`{
    "_id" : LUUID("bc8c8010-1a49-11e9-ae99-574ec3c3147f"),
    "name" : "IS_NOT_EMPTY() BWT_S_Stone Weight",
    "description" : "",
    "author" : "charence",
    "updatedBy" : "charence",
    "updatedAt" : 1547724130605.0,
    "createdAt" : 1547723944945.0,
    "color" : [ 
        196, 
        229, 
        56
    ],
    "rules" : [ 
        {
            "field" : "BWT_S_Stone Weight",
            "operator" : "IS_NOT_EMPTY",
            "values" : []
        }
    ],
    "objects" : [ 
        {
            "account" : "charence",
            "model" : "fbfebe94-cf01-4277-9661-a15167ff984b",
            "ifc_guids" : [ 
                "3X6JoeGVf6ju_B35xwBmPW"
            ]
        }
    ],
    "__v" : 0
}`

**Comment by simplypixi** [comment]
@Charence 
Which keys should I use to handle these operations?
![image](https://user-images.githubusercontent.com/5683490/53322714-819cac80-38dc-11e9-9346-67cf8f5310e2.png)

**Comment by Charence** [comment]
@simplypixi 
Let's use the following operators:

- exist = "EXISTS"
- does not exist = "NOT_EXISTS"
- is not = "IS_NOT"
- RegEx = "REGEX"

Yes, please add those two additional operators. Also, please change "smaller than" to "less than". The number operators list should be like this:

- equals
- does not equal
- greater than
- greater or equal to
- less than
- less or equal to
- in range
- not in range

Thanks!

**Comment by Charence** [comment]
@simplypixi I made a mistake in my last message! Please use these keys for the following operations:

- exist = "IS_NOT_EMPTY"
- does not exist = "IS_EMPTY"

**Comment by carmenfan** [comment]
obsolete. Replaced by #1387
