### ISSUE TITLE
Add api key support 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1339]
### Description
Add api key support for enabling the use of the api from a third party application without the need of  being logged in.

### Goals
- [x] Users can create an api key for personal use
- [ ] Users can regenerate or remove an api key
- [x] Appending the api key to a request will work as if the user is logged in

### Tasks
- [x] Add API key support in the backend for impersonate a user by appending the api-key as a query param 'key'
- [x] Add an endpoint to generate an api-key 
- [x] Add an enpoint to remove an api-key

- [x] In profile page add a field for viewing an api key
- [x] In profile page add button to generate an api key
