### ISSUE TITLE
v3.1.0 bugs list

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1342]
### Bugs
- [x] images doesn't show on risks report if there is a query string
- [x] Default near plane is too close, causing Z Fighting
- [x] Prominent link to 3drepo on issues/risk report
- [x] Do not load maps until the model is fully loaded.
- <del> [Wrong model loaded](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457178131) </del> _reverted views merge - this no longer happen_
- <del> [Unnecessary message when logging out](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457184099) </del> _This is most likely caused by loggin out whilst the front end is sending API requests_
- <del> [Can't add views](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457215895)</del> _reverted views merge - this no longer happen_
- [x] [Switching maps on throws error](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457225556)
- [x] [Issues multiplied if created by other user](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457536752)
- [x] [User's Job missing in Report](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457537545)
- <del> [BCF doesn't store visibility](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457542814) </del> _Delaying for next release_

**Comment by carmenfan** [comment]
**images doesn't show on risks report if there is a query string**

**Comment by paloknapo** [comment]
**Wrong model loaded**

Model/federation loads but progress bar stays on screen. When go back and try another model it doesn't load what I expected

**Comment by paloknapo** [comment]
**Unnecessary message when logging out**

![image](https://user-images.githubusercontent.com/760452/51679150-06429500-1fd6-11e9-850c-e79e7890cbef.png)

**Comment by paloknapo** [comment]
**Activating maps throws error**

1. open GIS card, set up and save
2. switch on map layer and this happens

![image](https://user-images.githubusercontent.com/760452/51686288-077cbd80-1fe8-11e9-9eb2-d85e5395627c.png)

**Comment by carmenfan** [comment]
> **Can't add views**
> 
> I'm in my own teamspace, add button is inactive and opening Views card throws this

@simplypixi 
Do you guys have time to take a look at this? It seems to only happen if the model has no views when you load the model.

**Comment by simplypixi** [comment]
> > **Can't add views**
> > I'm in my own teamspace, add button is inactive and opening Views card throws this
> 
> @simplypixi
> Do you guys have time to take a look at this? It seems to only happen if the model has no views when you load the model.

I'll check it tomorrow morning. I think I know where the problem is. ;)

**Comment by carmenfan** [comment]
@simplypixi 

I'm reverting the views PR from this release, the change on model component is causing [this bug](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457178131) 

So I think we shoudl give it a bit more testing/time . I'll create a separate issue for the bugs!

**Comment by paloknapo** [comment]
**Issues multiplied if created by other user**

This happens when collaborating. Issue created by user A is displayed 3 times in user's B card and vice versa. Happens in both Chrome and Firefox. 

Reload fixes the problem.

![image](https://user-images.githubusercontent.com/760452/51741924-1e76ea80-2090-11e9-8cec-1f4b34476d41.png)

**Comment by paloknapo** [comment]
**User's Job missing in Report**

![image](https://user-images.githubusercontent.com/760452/51742137-cab8d100-2090-11e9-8bd7-2cf71e8ed103.png)

**Comment by paloknapo** [comment]
**BCF doesn't store visibility**

1. in fedration A export issues with visibility 
2. create federation B with the same models
3. import BCF

![image](https://user-images.githubusercontent.com/760452/51743095-92ff5880-2093-11e9-943b-2dd2041e4d93.png)
