### ISSUE TITLE
Safetibase v2

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1359]
### Description
Additional logging functionality for risks

### Goals
- Can add comments to risks (similar to issues)
- Action history on risks (similar to issues)
- Level of risk and residual risk logging to document risk resolution

### Sketches
<img width="1189" alt="screenshot 2019-02-01 22 04 00" src="https://user-images.githubusercontent.com/1438332/52153143-c97b3b80-2670-11e9-8572-ebf2396d9b46.png">
<img width="455" alt="screenshot 2019-02-01 22 04 12" src="https://user-images.githubusercontent.com/1438332/52153148-ced88600-2670-11e9-8953-986b0187f4f4.png">
<img width="373" alt="screenshot 2019-02-01 22 04 37" src="https://user-images.githubusercontent.com/1438332/52153152-d304a380-2670-11e9-9a54-7ef3b64db659.png">
<img width="373" alt="screenshot 2019-02-01 22 04 42" src="https://user-images.githubusercontent.com/1438332/52153158-d566fd80-2670-11e9-8e5d-28773851b762.png">
<img width="374" alt="screenshot 2019-02-01 22 04 48" src="https://user-images.githubusercontent.com/1438332/52153164-d861ee00-2670-11e9-8d02-21a855eeb41d.png">
<img width="373" alt="screenshot 2019-02-01 22 04 54" src="https://user-images.githubusercontent.com/1438332/52153167-da2bb180-2670-11e9-8fee-96397d6d1043.png">

### Tasks
- [x] Comment support to risks
- [x] "action" comment support to risks
- [x] Special residual risk comment support
- [x] viewpoint -> viewpoints migration
- [x] BCF import/export should live in its own file.
- [x] Add "pin" field to comment to store pin position
- [x] There is a comment count in issue schema which basically equates to comments.length
- [x] Refactor issues backend
- [ ] Update tests
- [x] Frontend for comments (requires log list from Issues)
- [x] Frontend for actions (requires log list from Issues)
- [x] Frontend for displaying residual risks (requires log list from Issues)
- [x] Frontend for adding residual risks
- [x] Pretty print
