### ISSUE TITLE
Clear All Notifications on Panel Drawer 

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1362]
### Description

The Notifications panel drawer doesn't currently close the panel drawer when clicking the "Clear All" option. 

### Goals

- [x] Close panel drawer when clearing all notifications. 

### Tasks

- [x] Create action to close drawer 
- [x] Dispatch the above action when clicking the "Clear All" button.

### Steps to replicate
- Click on the 'Clear All' button.
- The panel drawer should close (as a requested feature, this is not a bug).

### Pictures/ Gifs of the error
![clearall](https://user-images.githubusercontent.com/6556019/52217271-04a78580-2890-11e9-993a-da7203395cc4.gif)
