### ISSUE TITLE
Change Icon and Link title in Viewer account

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1371]
### Description 

The Viewer account menu title and icon require updating.

### Goals

- [x] View a new title name "Support" and supporting icon. 

### Tasks

- [x] Change Icon in Viewer Menu.
- [x] Change menu item name from "User Manual" to "Support"
- [x] Change menu item href link.

### Pictures/ Gifs of the error
Current Icon 
![image](https://user-images.githubusercontent.com/6556019/52354315-158aff00-2a28-11e9-8ee9-35ec4ff8fecf.png)

New icon 
![image](https://user-images.githubusercontent.com/6556019/52354126-c3e27480-2a27-11e9-8e78-093cbce8320f.png)
