### ISSUE TITLE
Notify Issue owner when Issue Status is set to closed. 

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1375]
### Description

Currently when setting an Issue status to closed the user who created the Issue is not notified. This now requires a notification to be created whenever an Issue status is set to closed. 

The issue owner, as in the user who created the job requires a notification and any users who have been assigned the issues since the issue was created also need to be notified.  

### Goals

- [x] Notify User of an Issue Status being set to closed.
- [x] Allow the user to click the notification and be shown the relevant issue filtered out for that model. 

### Tasks

- [x] Acknowledge an Issue is being closed event.
- [x] Create a notification from event, with new type of notification. 
- [x] Display notification on front end. 
- [x] Test notification is notifying the correct user.
- [x] Add click event to show filtered issue. 
- [x] Test click event
- [x] Test notification is notifying all users who have been assigned the Issue.
- [x] Test entire Issue with different models and federations and users.
- [x] Write test cases
