### ISSUE TITLE
Dev bugs

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1391]
### Bugs
- [x] Sign up form clears the form even with an error #1381
- [x] Users should not be able to create project without a name #1379
- [x] User can revoke themselves from admin privileges via the api #1378
- [x] Job name needs to have character restrictions #1322
- [ ] yarn unity-util errors out #1389
 
### UI Oddities
- [x] [Extra scrollbars on login screen](https://github.com/3drepo/3drepo.io/issues/1391#issuecomment-466071674) #1395 (FAO: @simplypixi @dleszcz)
- [x] [No panel spacing when launched via pin](https://github.com/3drepo/3drepo.io/issues/1391#issuecomment-466072154) #1393 (FAO: @simplypixi @dleszcz)

**Comment by Charence** [comment]
**Login screen now has scrollbars appearing**

Caused by #1273 #1343 

![screenshot 2019-02-21 15 48 10](https://user-images.githubusercontent.com/1438332/53183588-80753200-35f3-11e9-8744-d602ba233d01.png)

**Comment by Charence** [comment]
**When Safetibase panel is opened via a risk pin and there is already the Issues panel open, the panel spacing is not there**

Caused by #1273 #1343 

![feb-21-2019 16-06-27](https://user-images.githubusercontent.com/1438332/53183639-9551c580-35f3-11e9-8381-dff6eb100a43.gif)

**Comment by carmenfan** [comment]
all done apart from #1389. @sanmont3drepo  is looking into it (and it has it's own issue) so I think we can close this one
