### ISSUE TITLE
Create HTML email template for Verification email

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1428]
### Description

A new email verification template needs to be created and used as the email sent to a user upon successful verification.  

### Goals

- [x] Create new email template, for user verification.

### Tasks

- [x] Create new email template.
- [x] Update link to template. 
- [x] Test verification email.

New User Verification email. 
![emailtemplate](https://user-images.githubusercontent.com/6556019/54612545-0ea4d280-4a51-11e9-9bf8-49f00fd85d52.png)
