### ISSUE TITLE
Migration: UI buttons

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1430]
### Subtasks
- [x] Creating toolbar component
- [x] Creating toolbar buttons (with tooltips)
- [x] Restyling of buttons on the left to make their behaviour similar to buttons from toolbar
- [x] Creating toolbar dropdown
- [x] Adding new viewer's constants: 
    - [x] navigationModes, 
    - [x] clippingModes,
- [x] Extending viewer's store of new values: 
    - [x] navigationMode, 
    - [x] helicopterSpeed, 
    - [x] focusMode, 
    - [x] clippingMode
- [x] Moving some of ViewerService method to the new viewer
- [x] Checking the icon in material/font awesome fonts
- [x] Migrate functions connected with buttons to actions:
    - [x] extent
    - [x] turntable
    - [x] show all
    - [x] hide
    - [x] isolate
    - [x] clip
    - [x] focus
    - [x] BIM
    - [x] Measure
- [x] Removing buttons on the right side
- [x] Removing old code

### Extras
- [x] transform bottom toolbar
- [x] put right buttons into new bottom toolbar.
- [x] remove text below button in favour of tooltip
- [x] use colour scheme from sketch
- [x] add button on top right to go back to teamspace
- [x] get rid of teamspace button in top right menu
- [x] button tool bar - when tool is active, highlight in orange/yellow colour.
- [x] dot on bottom of the button denotes it expands.
- [x] some buttons have submenu (Clip, Turntable)

Prototype:
https://xd.adobe.com/view/dbafde66-da15-4ead-5a67-7d7723e3d04b-ad9e/

Design specs:
https://xd.adobe.com/spec/7cbf178d-b7b1-4cfd-47f2-a1f3ff621111-0a8e/

**Comment by simplypixi** [comment]
@carmenfan 
We check your current code of bottom buttons and I found something like this:
![image](https://user-images.githubusercontent.com/5683490/54668299-db188580-4aee-11e9-9816-9a2891ecc677.png)

I suppose that the bottom buttons should close on background click, but... when I tried to do this, it didn't work. Should we fix this whether omit?

**Comment by carmenfan** [comment]
> @carmenfan
> We check your current code of bottom buttons and I found something like this:
> ![image](https://user-images.githubusercontent.com/5683490/54668299-db188580-4aee-11e9-9816-9a2891ecc677.png)
> 
> I suppose that the bottom buttons should close on background click, but... when I tried to do this, it didn't work. Should we fix this whether omit?

@simplypixi Please fix it 😆 

Can we make it so that it's just not "scene somewhere", but click pretty much anywhere? For e.g currently we can get into this state by clicking on navigation button then clip button:

![image](https://user-images.githubusercontent.com/11945337/54675855-4c5c3680-4af7-11e9-860e-f1acc68f7732.png)

It should collapse the menu if I click on another button

**Comment by dleszcz** [comment]
ok @carmenfan, we'll do it this way 👍
