### ISSUE TITLE
Migration: Metadata(BIM) card

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1431]
### Subtasks
- [x] Creating new BIM panel component (currently called "docs")
- [x] Adding tabs (All | Starred)
- [x] Adding list item (Star | Name | Value)
- [x] Adding filters to header (filtering by name or value)
- [x] Adding menu with single option to header (Clear starred)
- [x] Migrating rightPanel
- [x] Creating new module to handle BIM data and actions (migrating of docs service)
- [x] Binding the action to handler of model's click
- [x] Copying filters

### Extras
- [x] menu (option: Clear starred)
- [x] user can press on star - star turns yellow and available inn "starred" tab.
- [x] "favourites" will be saved in user profile - we will add API to edit/get this
- [x] when user unstar in starred tab, put a ~2sec delay to allow user to change their mind
- [x] add chip filter in meta tab. This is string only search, use metadata list from smart groups to give prompt for user.
- [x] Filter should work with both all and starred (name/value)
- [x] filter should look through both key and value for each entry
- [x] chips should work under OR logic i.e. list all results that matches any of the chips

Prototype:
https://xd.adobe.com/view/dbafde66-da15-4ead-5a67-7d7723e3d04b-ad9e/

Design specs:
https://xd.adobe.com/spec/7cbf178d-b7b1-4cfd-47f2-a1f3ff621111-0a8e/

**Comment by sanmont3drepo** [comment]
### API for starred metadata tags
`GET /starredMeta` : returns an array of strings with all the starred metadata tags

`POST /starredMeta`: appends a tag to the list of starred metadata tags. The body is a json with the format {tag : 'theTagToStar'}. If the tag was already starred it does nothing. 
returns 200 when successful, 
returns 400 if the json is not well formed

`DELETE /starredMeta`: deletes a tag from the list of starred metadata tags. The body is a json with the format {tag : 'theTagToRemove'}
returns 200 when successful, 
returns 400 if the json is not well formed

**Comment by simplypixi** [comment]
> starredMeta

@sanmont3drepo Will you be able to add `delete` for many `tags`?
I need to handle `Clear starred` option.
![image](https://user-images.githubusercontent.com/5683490/54992065-a27d1e00-4fbe-11e9-8dac-e1a8c3948c71.png)
And I would like to avoid deleting these records one by one.

**Comment by simplypixi** [comment]
@carmenfan Could we merge BIM and buttons? We have to change something in one place (opening of BIM panel) and we wouldn't like to duplicate the work. Also, it'll be easier for you to tests these changes on single branch. What do you think?

**Comment by carmenfan** [comment]
@simplypixi  yes that's fine

@sanmont3drepo maybe we should have a post request to allow the user to overwrite it with []?

**Comment by simplypixi** [comment]
> @simplypixi yes that's fine
> 
> @sanmont3drepo maybe we should have a post request to allow the user to overwrite it with []?

@sanmont3drepo  What's the status? :P

**Comment by sanmont3drepo** [comment]
> > @simplypixi yes that's fine
> > @sanmont3drepo maybe we should have a post request to allow the user to overwrite it with []?
> 
> @sanmont3drepo What's the status? :P
Added the endpoint

PUT /starredMeta: sets the list of starred metadata tags. The body is a json array of strings .
returns 200 when successful,
returns 400 if the json is not well formed
