### ISSUE TITLE
Migration: Compare

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1439]
### Subtasks
- [ ] Creating new compare component
- [ ] Creating tabs
- [ ] Creating Diff tab
  - [ ] Adding filters
  - [ ] Creating list item
  - [ ] Binding logic
- [ ] Add sort by name(Both)/sort by type(Clash only) in hamburger button.
- [ ] Creating Clash tab
  - [ ] Adding filters
  - [ ] Creating list item
  - [ ] Binding logic
- [ ] Handling permissions
- [ ] Adding slider to footer
- [ ] Moving Viewer-specific methods to migrated Viewer service
- [ ] Moving && refactoring logic from CompareService to new module
   - [ ] Creating redux state
   - [ ] Creating actions
- [ ] Moving && refactoring logic from RevisionsService to new api service
- [ ] Removing old files

### Extras

- [ ] Migrate existing compare card features
- [ ] 3D Diff should be the default tab to open
- [ ] Add search function to search model by name
- [ ] Change radio button to a slider with 3 options
- [ ] Add search filter to allow the user to search for models by name
- [ ] Add tick box to each model entry
- [ ] Add tick box next to search filter, which will select all models currently displayed

##### Diff mode
- [ ] It should list all models currently displayed (always only 1 entry for model, n entries for federation with n sub models)
- [ ] Revision displayed should be the currently loaded revision.
- [ ] When checked, the model listing shows a drop down menu containing existing revisions to compare against (this list should not have the currently loaded revision, by default, it should display the latest revision)
- [ ] When the user starts comparison, any unchecked models should be hidden from view, loading selected revisions as compare target.

##### Clash

- [ ] This feature should only be available for federation (Disable if it's just a model)
- [ ] When checked, a toggle button appears (BASE/TARGET)
- [ ] User clicks on the toggle button to choose if the model should be base/target
- [ ] Revision on model entry should be fixed as currently loaded revision if it is base.
- [ ] Drop down menu appears if it's chosen as target (with currently loaded revision available as an option)
- [ ] When the user starts comparison, hide all unchosen models. 
- [ ] If the target is:
   - [ ] A currently loaded revision -> there is a function in viewer Service to set a model as compare target (see current compare service for this logic)
   - [ ] A different revision -> hide currently loaded revision of the model, and load the selected revision.

Prototype and design spec links below:

https://xd.adobe.com/view/af7ebe9b-9bb8-43f4-723c-e8696c17c340-d94f/

**Comment by simplypixi** [comment]
`Add sort by name(Both)/sort by type(Clash only) in hamburger button.`
@paloknapo Can we move sorting options to menu in header? It'll be more consistent with the already migrated issues panel.
![image](https://user-images.githubusercontent.com/5683490/55382258-8250e000-5525-11e9-9241-26f6f5c6459a.png)

**Comment by dleszcz** [comment]
Hello @paloknapo, The search icon is a part of placeholder, or is separate? I mean, the icon should disappear when a user starts typing?

**Comment by paloknapo** [comment]
> `Add sort by name(Both)/sort by type(Clash only) in hamburger button.`
> @paloknapo Can we move sorting options to menu in header? It'll be more consistent with the already migrated issues panel.
> ![image](https://user-images.githubusercontent.com/5683490/55382258-8250e000-5525-11e9-9241-26f6f5c6459a.png)

@simplypixi Yes, good idea, let's move the menu button to the header.

**Comment by paloknapo** [comment]
> Hello @paloknapo, The search icon is a part of placeholder, or is separate? I mean, the icon should disappear when a user starts typing?

@dleszcz The icon is just a placeholder and disappears when user starts typing.

**Comment by dleszcz** [comment]
Hello @carmenfan ,

What do you think about some endpoint to fetch federation submodels with their revisions? 
Currently, we have to call:
- API get revisions method 
- Viewer getModelInfo function
for every submodel in a federation to prepare data for comparison.

When there are many models and their revisions, we will have to do many requests instead of one.
Let me know if we don't understand something in this case or there is another solution to do this 🤓

**Comment by carmenfan** [comment]
> When there are many models and their revisions, we will have to do many requests instead of one.
Let me know if we don't understand something in this case or there is another solution to do this 🤓

Sounds sensible! I'll look into it

**Comment by carmenfan** [comment]
@simplypixi @dleszcz 

I've added an api that gives you the name and revisions of submodels:
````js
router.get("/:model/revision/master/head/subModelRevisions", middlewares.hasReadAccessToModel, getSubModelRevisions);

router.get("/:model/revision/:revId/subModelRevisions", middlewares.hasReadAccessToModel, getSubModelRevisions);
````

Response returns you an json object where keys are subModel ids, with value being a json object with its name and the list of revisions for that submodel:
![image](https://user-images.githubusercontent.com/11945337/55639755-01fadb00-57c2-11e9-90ec-877114ede9bb.png)

I believe you only need to get the model Info to fetch the name. So this should make it so that you'll get all the info you need with one API request. If that's not the case, let me know.

**Comment by simplypixi** [comment]
> ```js
> /revision/master/head/subModelRevisions
> ```

Works like a charm ;)

**Comment by simplypixi** [comment]
@carmenfan I found a bug, probably. Did you add that on purpose? I mean, you passed more args than`diffToolSetAsComparator` requires. :D
![image](https://user-images.githubusercontent.com/5683490/55707570-30580080-59e4-11e9-800a-1e8c47f9a4b6.png)

**Comment by carmenfan** [comment]
Yes.. Copy and paste error. You can get rid of that 3rd argument!
