### ISSUE TITLE
Sort All 3D Repo UI Lists and add Search Functionality.

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1441]
### Description
A selection of lists on the front-end User Interface are currently not sorted in alphabetical order.

Furthermore the user does not have the ability to search for a list option, as in the list's are not searchable by keystroke. 

For example : if i type A on a job's list i would not be taken to any matching job titles such as "Architect". 

Any list's that have a logical order in place such as **Priority** "Low, Medium, High" or **Status** "Open, In Progress, For Approval, Closed" will not be altered.

### Goals
- [x] View any UI list in Alphabetical Order.
- [x] Use the keyboard to search by letter. 

### Tasks

- [x] Identify the UI list's that require sorting.
    * Check and note all list's that have a logical order.
- [x] Apply the sort to the lists. 
- [x] Add the search functionality. 
- [x] Test the search functionality. 
- [ ] Write a sorting unit test. 

### High Priority - Viewer lists. (Any list's found in the viewer)
- [x] Issues Card - Assign User list (This will be completed when, this branch and #1272 are both merged into staging as the logic is shared with Safetibase Job's List)
- [x] Issues Card - Types List  - (This has been done on #1272 )
- [x] Safetibase - Risk Owner 
- [x] Safetibase - Category 

### Medium Priority - Teamspace lists. 
- [x] Teamspace - New Model (Model Type)
- [x] Teamspace - Teamspace Selection NB: This needs to be checked if not already sorted.  

*The options below are the same lists but displayed in two different options, these still need to be checked and sorted if necessary.*
- [x] Teamspace Selection - found when clicking the large green plus icon.
- [x] Teamspace Selection - found when clicking the nested smaller plus icon on Model & Federations.

###  Low Priority - User Management
- [x] User management - Project List  

**NB** If any list contains an option such as "Unassigned" or "Other", these options must remain at the bottom of the lists.
