### ISSUE TITLE
Revamp forgot password template and improve wording.

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1450]
### Description

Update the current forgot your password template , sent to the user, as well as improve on the current wording.

### Goals

- [x] Create a new forgot password template.
- [x] Update existing text.

### Tasks

- [x] Update Forgot Password Template.
- [x] Review current wording (copy) and update.
- [ ] Add User account

**Comment by carmenfan** [comment]
don't forget to add user account on the email.
