### ISSUE TITLE
Create two new buttons for notifications "Mark all as read" and "Mark all as unread"

### ISSUE THREAD

**Issue by niblux** [3drepo/3drepo.io#1456]
### Description

Create two new buttons for the notifications panel, that allow the user to mark all as "Unread" and mark all as "Read".

### Goals

- [x] Mark all notifications as "Unread". 
- [x] Mark all notifications as "Read".

### Tasks

- [x] Add new buttons "Read" and "Unread".
- [x] Add logic to mark all notifications based on each state.
- [x] Test solution.
