### ISSUE TITLE
[GridFS Migration] Read files from file system

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1461]
### Description
Files such as trees, idmap will be moved to local file system. We need to read it off a reference bson and send it back to the client from file system.

### Goals
- All file reads will still work
- quota should still read accurately

### Tasks
- [x] Setup nodeJS filesystem driver
- [x] Read teamspace quota from reference bson 
- [x] Read json files from filesystem
  - [x] fullTree
  - [x] Unity mapping
  - [x] idMap
  - [x] idToMeshes
  - [x] treePath
  - [x] modelProperties
- [x] Read Asset bundles from filesystem
- [x] Read original files from filesystem
- [ ] Remove gridFS methods
- [x] Delete models needs to clean up filesystem
- [ ] Update sample project
- [x] Fix travis
