### ISSUE TITLE
Editable pins for risks and issues

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1462]
### Description
Pins should be able to be editable

### Goals
- [ ] The user can edit an issue, change the pin and  then save it
- [ ] The user can edit a risk, change the pin and  then save it

### Tasks
- [x] Update backend to be able to change the pin for an issue
- [x] Update backend to be able to change the pin for a risk
- [ ] Update frontend to be able to change the pin for an issue
- [ ] Update frontend to be able to change the pin for a risk
