### ISSUE TITLE
Migration: Tree

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1475]
#### Subtasks
- [x] New tree panel
- [x] Research about best data structure for big amount of nested data
- [x] Header menu (adding options with mocked actions)
- [x] Search
  - [x] Searching only by name
  - [ ] * Searching using web worker
- [x] List item
  - [x] [Federation] Model item should have icon button on the right side. It opens new tab with specific model
  - [x] List item should look like the item from the list on Teamspaces
  - [x] List item has many states: https://xd.adobe.com/view/d0570de5-983e-43f0-4270-bb01f45c0618-a666/screen/7e95c5f9-1490-49aa-b781-8359b9ece66e/Tree-states
- [x] Creating a nested list
  - [x] Rendering structure of nested items
  - [x] * First attempt with virtualization of the very long list
- [x] Moving tree service to redux module
  - [x] Adding base fields in redux store e.g selectedItem, visibleNodes etc.
  - [x] Migrating tree service functions
  - [x] Binding actions to UI elements
  - [x] Updating already migrated panels

#### Extras:
Sketches: https://xd.adobe.com/view/d0570de5-983e-43f0-4270-bb01f45c0618-a666/

**Comment by simplypixi** [comment]
@carmenfan We are wondering about the list of `subTrees`, which we get on the response of `fulltree.json` request. Is there any example model when the list is not empty?

**Comment by carmenfan** [comment]
@simplypixi if you open any federation they should have it

**Comment by dleszcz** [comment]
Hello @paloknapo ;) Can you share us sketch with specification?

**Comment by dleszcz** [comment]
@paloknapo What if there are a few highlighted ones? Every object should have a border? It may look like this:

![Screenshot 2019-04-18 at 15 17 11](https://user-images.githubusercontent.com/17221890/56363761-2fe21580-61ed-11e9-9e9a-077317e9bba0.png)
Any comments to this?^

Second thing: How many nestings can be in the tree? After some level, we will not be able to indent in the element of the tree :)

cc: @carmenfan

**Comment by carmenfan** [comment]
> Second thing: How many nestings can be in the tree? After some level, we will not be able to indent in the element of the tree :)

This is very much model dependant so we can't guarantee x amoutn of levels. I think we have to be prepared to support as many as necessary and just have a horizontal scroll bars if it goes too far.

**Comment by paloknapo** [comment]
> @paloknapo What if there are a few highlighted ones? Every object should have a border? It may look like this:
> 
> ![Screenshot 2019-04-18 at 15 17 11](https://user-images.githubusercontent.com/17221890/56363761-2fe21580-61ed-11e9-9e9a-077317e9bba0.png)
> Any comments to this?^
> 
> Second thing: How many nestings can be in the tree? After some level, we will not be able to indent in the element of the tree :)
> 
> cc: @carmenfan

@dleszcz Yes, render a frame for each selected frame in case of multiple selection.

Usually, there are 5 - 7 nesting levels in a typical BIM federation (see screenshot below), more than 10 is rare. In case you run out of space, item in list can have 2 lines and/or use horizontal scroll bar. 

![image](https://user-images.githubusercontent.com/760452/56364981-c4e21000-61e7-11e9-8873-ed3c3e8c89a2.png)

**Comment by carmenfan** [comment]
@dleszcz Sorry, disregard what pavol's just said.

We've had a talk about it and Pavol's updated the states info on the adobe link (same as the link from the top of the issue!)

In short:
- grey = highlighted, bordered = selected. 
- A highlighted object is always selected. 
- A selected hidden object should be bordered but not highlgihted.
- The buttons affect all selected objects
- Toggling visibility to toggle all selected objects. I.e. if I hit toggle on an hidden object, every selected object should be shown, and vice versa.
- Isolate should unhide any selected objects then perform isolate.

Please take a look and let us know if it makes sense. Happy to setup a call to talk about it if necessary.

**Comment by simplypixi** [comment]
@carmenfan @paloknapo Is this extra level necessary? Does it contain something different than model itself?
![image](https://user-images.githubusercontent.com/5683490/56561696-06880780-65a8-11e9-9a85-e5756e331e1c.png)

**Comment by carmenfan** [comment]
> @carmenfan @paloknapo Is this extra level necessary? Does it contain something different than model itself?
> ![image](https://user-images.githubusercontent.com/5683490/56561696-06880780-65a8-11e9-9a85-e5756e331e1c.png)



This came from the fulltree.json HTTP response. Basically federations are structured as it's own scene graph. And it looks something like this:
![image](https://user-images.githubusercontent.com/11945337/56576227-b6b53a80-65bf-11e9-9692-a98f1c265577.png)

So the extra node you see on the UI is the direct translation of the transformation node above the reference node. This is here so you can define a transformation where necessary... But in reality it's always an identity matrix.

So short answer is no, you don't need all that. But it will be quite a chore to change what the backend returns. So best way to "remove" this is to just contruct something on the UI if it is a federation and only use the sub model return values.

**Comment by dleszcz** [comment]
@paloknapo @carmenfan when all of the nodes are highlighted in "catalog/nodes group", then the catalog is also highlighted (with border and different colour)?

**Comment by simplypixi** [comment]
@carmenfan 
I'm currently rewriting `getNodesFromSharedIds` method from Tree service and I have some questions. What is the difference (or connection) between `shared_ids` and `shared_id`? What is the purpose of these fields?

**Comment by carmenfan** [comment]
> @carmenfan
> I'm currently rewriting `getNodesFromSharedIds` method from Tree service and I have some questions. What is the difference (or connection) between `shared_ids` and `shared_id`? What is the purpose of these fields?

every nodes in 3drepo has a unique ID and shared ID. uniqueID is unique across revision but shared_id isn't (e.g. let's say a door in a model, the first revision of the model the door will have the same shared ID as every other revision of the model, but with different unique IDs). So things like groups would be saved in shared IDs so the user can view the next version of the model and still get the right objects highlighted (whereas if we save it under unique ids, they will be unidentifiable)

> What is the difference (or connection) between `shared_ids` and `shared_id`
From the look of the code, object.shared_id this is legacy schema support for groups.

**Comment by simplypixi** [comment]
@carmenfan I'm wondering on idToMeshes map that you currently use in tree service. Is it this namespacing necessary?
I mean: 
![image](https://user-images.githubusercontent.com/5683490/57444337-36920480-7250-11e9-80af-162860d6b22f.png)
It'll be always the same teamspace, isn't it?

**Comment by carmenfan** [comment]
> @carmenfan I'm wondering on idToMeshes map that you currently use in tree service. Is it this namespacing necessary?
> I mean:
> ![image](https://user-images.githubusercontent.com/5683490/57444337-36920480-7250-11e9-80af-162860d6b22f.png)
> It'll be always the same teamspace, won't it?

It was originally designed in mind that you can make cross teamspace federations. Then we decided to restrict users from doing it. I would probably leave it as is unless there's a real need to get rid of it.

**Comment by simplypixi** [comment]
@carmenfan Could you describe a bit how the IFC works? I'm currently struggling with that. I checked hiding Ifc spaces on production and it seems to not work - maybe I'm doing this on the wrong model.

![image](https://user-images.githubusercontent.com/5683490/57676680-5bf28a00-7625-11e9-9a64-acaf49e70a50.png)

**Comment by simplypixi** [comment]
> @carmenfan Could you describe a bit how the IFC works? I'm currently struggling with that. I checked hiding Ifc spaces on production and it seems to not work - maybe I'm doing this on the wrong model.
> 
> ![image](https://user-images.githubusercontent.com/5683490/57676680-5bf28a00-7625-11e9-9a64-acaf49e70a50.png)

@carmenfan ^ friendly reminder :D

**Comment by carmenfan** [comment]
@simplypixi  sorry!

It does work on production, you just need to have a model that has IFC Spaces. (not all IFC models has them):
![2](https://user-images.githubusercontent.com/11945337/57763266-f243b000-76f8-11e9-98ee-2c6623e7de97.gif)


The way it works is that we want to hide IFC Spaces by default unless users specified. The list of hidden nodes is provided by the model properties API, where it gives you the list of IDs of objects that needs to be hidden by default:
![image](https://user-images.githubusercontent.com/11945337/57763363-215a2180-76f9-11e9-9d9d-6d68e7b51ca1.png)


If I remember correctly the Unity game is calling that and dealing with it. So this isn't an API  you need to call. Instead, the tree takes notes of what needs to be hidden by default by looking at the node properties:

![image](https://user-images.githubusercontent.com/11945337/57763490-5e261880-76f9-11e9-8f7d-aff50c256faf.png)


`toggleState` within the nodes tells you the starting state the node should start with. And if it is IFC Spaces (or in the future any other hidden by default nodes), they should come in with `invisible`.

Important to note that its parents comes in as `parentOfInvisible`, so you'd have to make sure the parent nodes reflect the hidden objects at initialisation.
