### ISSUE TITLE
Dev bugs 3.5.0 

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1490]
- [x] [Saving issue pin throws error](https://github.com/3drepo/3drepo.io/issues/1490#issuecomment-487947629)
- [x] [Pin updated message in report shows coordinates](https://github.com/3drepo/3drepo.io/issues/1490#issuecomment-487951807)
- [x] [Missing button in confirmation email](https://github.com/3drepo/3drepo.io/issues/1490#issuecomment-487961412)
- [x] [Pin is being add to a new issue if i edited a pin in an existing issue](https://github.com/3drepo/3drepo.io/issues/1490#issuecomment-488262542)
- [x] [Revive issue number](https://github.com/3drepo/3drepo.io/issues/1490#issuecomment-488262841)
- [x] Add "Sort by date" to Safetibase

**Comment by paloknapo** [comment]
**Saving issue pin throws error**
1. open existing issue which has no pin
2. add pin and save
3. edit pin
4. save - this error pops up

![image](https://user-images.githubusercontent.com/760452/56964077-5a6b9100-6b52-11e9-9b63-d2d473927d04.png)

**Comment by paloknapo** [comment]
**Pin updated message in report shows coordinates**
![image](https://user-images.githubusercontent.com/760452/56964917-01046180-6b54-11e9-8903-37ccb721ceaf.png)
It should show the same message as in the issue:
![image](https://user-images.githubusercontent.com/760452/56964967-15e0f500-6b54-11e9-96ed-24b636f460a9.png)

**Comment by paloknapo** [comment]
**Missing button in confirmation email**

![image](https://user-images.githubusercontent.com/760452/56966821-d1efef00-6b57-11e9-8d77-ab26397b36d9.png)

**Comment by carmenfan** [comment]
**Pin is being add to a new issue if i edited a pin in an existing issue**
- Open an existing issue, move and save a pin
- Create a new issue without adding a pin
- The new issue is saved with a pin, in the exact location of the moved pin of the existing issue.
![2](https://user-images.githubusercontent.com/11945337/57015685-0c1bc800-6c0e-11e9-888e-501e616245cb.gif)

**Comment by carmenfan** [comment]
**Revive issue number**
![image](https://user-images.githubusercontent.com/11945337/57015744-4f763680-6c0e-11e9-90a8-046135bb41d8.png)

- Issue needs to display their numbers
- Remove the automatically generated number on default issue name (i.e. it should be `Untitled Issue` instead of `Untitled Issue 4`)
