### ISSUE TITLE
Dev bugs 3.5.1

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1493]
- [x] [Error when issue is closed](https://github.com/3drepo/3drepo.io/issues/1493#issuecomment-489054457)
- [x] [Issues: take screenshot button doesn't work on Firefox](https://github.com/3drepo/3drepo.io/issues/1493#issuecomment-489057193)
- [x] [Issues: can't see all fields when creating issue in Firefox](https://github.com/3drepo/3drepo.io/issues/1493#issuecomment-489057828)
- [x] [Taking screenshot without comment doesn't save the correct view](https://github.com/3drepo/3drepo.io/issues/1493#issuecomment-489061542)
- [x] [Filtering in BIM card throws error](https://github.com/3drepo/3drepo.io/issues/1493#issuecomment-489082634)
- [x] [Issues: Create Report ignores filter and prints all issues](https://github.com/3drepo/3drepo.io/issues/1493#issuecomment-489143729)

**Comment by paloknapo** [comment]
**Error when issue is closed**

I got this error when I closed an issue. I can't replicate it but please have a look if it's something serious:
![image](https://user-images.githubusercontent.com/760452/57132532-c985f700-6d97-11e9-9e7b-c38bbd6593bc.png)

**Comment by paloknapo** [comment]
**Issues: take screenshot button doesn't work on Firefox**

![image](https://user-images.githubusercontent.com/760452/57133080-a0666600-6d99-11e9-8bb1-df10acc5baee.png)

**Comment by paloknapo** [comment]
**Issues: can't see all fields when creating issue in Firefox**

![image](https://user-images.githubusercontent.com/760452/57133214-0bb03800-6d9a-11e9-9a24-9b1bd87a2d39.png)

**Comment by paloknapo** [comment]
**Taking screenshot without comment doesn't save the correct view**

1. create or open issue
2. change view
3. take screenshot and submit without comment
4. screenshot with original view is saved instead of changed view

![01](https://user-images.githubusercontent.com/760452/57134003-8f6b2400-6d9c-11e9-9f5f-d30e756cfe0a.gif)

**Comment by sanmont3drepo** [comment]
> **Issues: take screenshot button doesn't work on Firefox**
> 
> ![image](https://user-images.githubusercontent.com/760452/57133080-a0666600-6d99-11e9-8bb1-df10acc5baee.png)

Im unaable to reproduce this one.

**Comment by paloknapo** [comment]
**Filtering in BIM card throws error**

1. activate too and select oobject
2. type search term in filter and hit enter

![image](https://user-images.githubusercontent.com/760452/57138025-7c128580-6da9-11e9-80d1-2df9fea89ae4.png)

**Comment by paloknapo** [comment]
**Issues: Create Report ignores filter and prints all issues**

If no filter, it prints also closed issues. It should print out only issues visible in the card.
