### ISSUE TITLE
Issues/Risk refactor to use partial issue update instead of replacing the whole issue/risk

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1496]
### Description
Instead of using post and replace the whole issue when changeing the issue from front end it should replace just part of the issue.

### Goals
- [x] Tests should pass
- [x] When updating any property in issues the request should be a patch with just that update of the property
- [x] When updating any property in risks the request should be a patch with just that update of the property

### Tasks
- [x] Update issues to use patch in the backend
- [x] Update frontend to use patch with issues
- [x] Update frontend to send only the field that's being updated
- [x] Fix the tests to use patch for updating the issue

- [x] Update risks to use patch in the backend
- [x] Update frontend to use patch with risks
- [x] Update frontend to send only the field that's being updated
- [x] Fix the tests to use patch for updating the risk
