### ISSUE TITLE
Dev bugs 3.5.2

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1497]
- [x] [Error when creating issue]()
- [x] [Collaborator can't change Priority, Status, Assign, Type flags](https://github.com/3drepo/3drepo.io/issues/1497#issuecomment-490128256)
- [x] [Add View button active for user with viewer permissions](https://github.com/3drepo/3drepo.io/issues/1497#issuecomment-490141093)
- [x] [Safetibase: Collaborator can't change Mitigation flags](https://github.com/3drepo/3drepo.io/issues/1497#issuecomment-490168006)
- [x] Add/edit pin should be available only if the user is the owner of the issue
- [x] Update the position should fail in the backend if you are not the owner of the issue 

UI oddities 

- [x] [This is very problematic and can’t be solved right now](https://github.com/3drepo/3drepo.io/issues/1497#issuecomment-490174767)

**Comment by paloknapo** [comment]
**Error when creating issue**

In federation, User with collaborator permissions on fed and viewer on sub-models gets this error when creating issue:

![image](https://user-images.githubusercontent.com/760452/57304487-5651ed00-70d7-11e9-9bc5-406f8f1a039a.png)

Also, Issue card disappears.

**Comment by paloknapo** [comment]
**Collaborator can't change Priority, Status, Assign, Type flags**

![image](https://user-images.githubusercontent.com/760452/57312134-dfbbec00-70e4-11e9-96f3-edf82a769774.png)

**Comment by paloknapo** [comment]
**Add View button active for user with viewer permissions**

![image](https://user-images.githubusercontent.com/760452/57314292-46430900-70e9-11e9-9b36-1558aa4112ca.png)

**Comment by paloknapo** [comment]
**Safetibase: Collaborator can't change Mitigation flags**

Risk is assigned to user's jog. User can change Mitigation Status but not Likelihood or Consequence.

![image](https://user-images.githubusercontent.com/760452/57318978-6a0b4c80-70f3-11e9-94d7-592eb2695beb.png)

**Comment by paloknapo** [comment]
**There is no limit on Issue or Risk name**

This should be at most 120 characters.

![image](https://user-images.githubusercontent.com/760452/57320053-e99a1b00-70f5-11e9-9577-9dd3d24879ca.png)
