### ISSUE TITLE
Issues and risks refactor: add  comments endpoints

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1498]
### Description
Add  comment enpoints to simplify backend and get a cleaner api

### Goals
- [x] Commenters/Collaborators/admins can create comments in issues
- [x] Viewers cannot create comments in issues
- [x] Commenters/Collaborators/admins can delete comments in issues
- [x] Viewers cannot delete comments in issues
- [ ] Commenters/Collaborators/admins can create comments in risks
- [ ] Viewers cannot create comments in issues
- [ ] Commenters/Collaborators/admins can delete comments in risks
- [ ] Viewers cannot delete comments in issues

### Tasks
- [x] Add a comments proper post endpoint to add comments in the issue
- [x] Update frontend to use the proper endpoint for creating comments in issues
- [x] Add a comments proper delete endpoint to delete the comment from the issue
- [x] Update frontend to use the proper endpoint for deleting comments in issues
- [x] Fix the tests to use the proper endpoint for adding comments in the issue
- [x] Fix the tests to use the proper endpoint for deleting comments from the issue

- [ ] Add a comments proper post endpoint to add comments in risks
- [ ] Update frontend to use the proper endpoint for creating comments in risks
- [ ] Add a comments proper delete endpoint to delete the comment from the risks
- [ ] Update frontend to use the proper endpoint for deleting comments in risks
- [ ] Fix the tests to use the proper endpoint for adding comments in the risks
- [ ] Fix the tests to use the proper endpoint for deleting comments from the risks
