### ISSUE TITLE
Risks refactor: add  comments endpoints

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1499]
### Description
Add  comment enpoints to simplify backend and get a cleaner api

### Goals
- [x] Commenters/Collaborators/admins can create comments in risks
- [x] Viewers cannot create comments in issues
- [x] Commenters/Collaborators/admins can delete comments in risks
- [x] Viewers cannot delete comments in issues

### Tasks
- [x] Add a comments proper post endpoint to add comments in the risks
- [x] Update frontend to use the proper endpoint for creating comments in risks
- [x] Add a comments proper delete endpoint to delete the comment from the risks
- [x] Update frontend to use the proper endpoint for deleting comments in risks
- [x] Fix the tests to use the proper endpoint for adding comments in the risks
- [x] Fix the tests to use the proper endpoint for deleting comments from the risks

**Comment by sanmont3drepo** [comment]
Merged this issue with #1498
