### ISSUE TITLE
Group upload notifications

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1511]
### Description
Group upload notifications to prevent notifications spamming.

### Goals
- [ ] Users will receive or update a notification each time a model has been uploaded
- [ ] If there was already a notification with that model at the moment f the new upload, the notification will be updated with the new version instead of creating a new notification

### Tasks
- [ ] Update the frontend to show the updated notification with the message "X revisions has been uploaded to model Y"
- [ ] Update backend to save the newrevisionid in an array in the notification.

**Comment by carmenfan** [comment]
Looks like this has been done ages ago and is in master already...
