### ISSUE TITLE
BCF 2.1 improvements

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1513]
### Description
Strictly adhere to BCF 2.1 schema as certain 3rd party software relies on markup order defined in schema

https://github.com/buildingSMART/BCF-XML/blob/master/Schemas/project.xsd

### Tasks

- [x] Update tests
- [x] Adhere to order specified by schema sequence
- [x] Save project info in project.bcfp
- [x] Remove extra whitespace from bcf.version
