### ISSUE TITLE
Hyperlinks in editable fields 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1530]
### Description
Add the ability to have hyperlinks in editable fields in issues and risks

### Goals
- [x] Users can change view/edit mode in editable fields
- [x] When a editable field is in view mode hyperlinks are clickable

### Tasks
- [x] Add a new view/edit field component
- [x] Add a hover edit button in the view/edit field component that allows to change it to an editable field

**Comment by sanmont3drepo** [comment]
I would need to review this with @paloknapo
