### ISSUE TITLE
Migration: Top level components and the rest of services

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1539]
### Tasks

- [x] Removing Account [(PR)](https://github.com/3drepo/3drepo.io/pull/1564) 
- [x] Chat
- [x] Removing cookies [(PR)](https://github.com/3drepo/3drepo.io/pull/1564) 
- [x] Removing privacy [(PR)](https://github.com/3drepo/3drepo.io/pull/1564) 
- [x] Removing terms [(PR)](https://github.com/3drepo/3drepo.io/pull/1564) 
- [x] Removing entry
- [x] Removing height-setter
- [x] Removing old icons [(PR)](https://github.com/3drepo/3drepo.io/pull/1564) 
- [x] Revisions [(PR)](https://github.com/3drepo/3drepo.io/pull/1587) 
~~Using the library to setting proper hide of panels~~ (flexbox)
- [x] Analytic service [(PR)](https://github.com/3drepo/3drepo.io/pull/1564) 
- [x] Removing event service [(PR)](https://github.com/3drepo/3drepo.io/pull/1571)
~~Auth service~~ (will be migrated at the end)
- [x] Migrating the rest of dialog service  [(PR)](https://github.com/3drepo/3drepo.io/pull/1587) 
- [x] Removing API [(PR)](https://github.com/3drepo/3drepo.io/pull/1576)
~~Removing ClientConfigService~~ (will be migrated at the end)
- [x] Removing state managera
- [x] Removing Template service [(PR)](https://github.com/3drepo/3drepo.io/pull/1564) 
- [x] Removing Angular Theme config [(PR)](https://github.com/3drepo/3drepo.io/pull/1564) 
- [x] Removing panel service (in progress)
- [x] Service workera
- [x] Home (in progress)
- [x] Payment
- [x] Viewer (in progress)
- [x] Creating new module (or connecting the react-router with the store) to instant access for current teamspace, modelId, revisionId and query params. (in progress)
- [ ] Moving current App component logic (related to user sessions) to new Auth component (in progress)
- [x] Removing old libraries
- [ ] * Migration to CRA (boilerplate) 

### Issues
#1558 Migration: Removing old files
