### ISSUE TITLE
API Documentation update

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1543]
### Description
Complete the API documentation ; add request body parameters, examples and permissions needed.

### Goals
- add request body parameters
- add examples

### Tasks
- [x] accountPermission.js - cw
- [x] auth.js - cw
~- [ ] config.js - cw~
- [x] group.js - cw
- [x] history.js - cw
~- [ ] invoice.js~
- [x] issue.js - sm
~- [ ] issueAnalytic.js~ 
- [x] job.js - cw
- [x] maps.js - cw
- [x] meta.js - sm
- [x] model.js - sm
~- [ ] notification.js~
~- [ ] payment.js~
- [x] permissionTemplate.js - cw
~- [ ] plan.js~
- [x] project.js - sm
- [x] risk.js - cw
- [x] subscriptions.js - sm
- [x] teamspace.js - sm
- [x] user.js - sm
- [x] viewpoint.js - cw
