### ISSUE TITLE
Attach resource

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1544]
### Description

Adding the Groups feature into 3D Repo, allowing the user to create/edit/delete groups

### Goals

- [ ] Collaborators/admins can create groups
- [ ] viewers cannot create groups
- [ ] clicking on a group highlights the group objects in viewer

### Tasks

- [ ] A new Group panel
- [ ] List group component
- [ ] edit group component
- [ ] new API end point to remove groups
- [ ] New database schema for groups (present it here)

### Description
Highlighting objects on a federation node that would highlight multiple sub models is not functioning.

### Steps to replicate
- click on the root node of a federated tree
- The entire model should be highlighted, but only one of the models was highlighted.

### Bugs
- [ ] Bug 1 
- [ ] Bug 2 
- [ ] Bug 3 
 
### UI Oddities
- [ ] Weird UI 1 
- [ ] Weird UI 2 
- [ ] Weird UI 3 

https://xd.adobe.com/view/b485f5c3-1d06-4858-7439-a1f2ad1c4a5d-c2b4/
