### ISSUE TITLE
Dev bugs 3.9.1

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1582]
**UI oddities**

- [ ] [Delay when deleting views](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-503542543)
- [x] [Spacing in groups card](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-503542861)
- ~[Card height incorrect when reopened](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-503544666)~ Wait for completion of frontend migration
- [ ] [No user feedback when issues/risks being saved](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-504069965)

**Comment by Charence** [comment]
**Delay when deleting views**

Sometimes, there's a message informing the user that a view is being deleted, but sometimes it doesn't appear. In addition, there's a delay when deleting views and the user can still interact with the buttons.

![Jun-19-2019 14-23-05](https://user-images.githubusercontent.com/1438332/59766052-a4920880-929f-11e9-95ee-8c85a01162da.gif)

**Comment by Charence** [comment]
**Spacing in groups card**

The first line in groups card and separating line with shadow seem to overlap slightly.

<img width="394" alt="Screenshot 2019-06-19 14 25 00" src="https://user-images.githubusercontent.com/1438332/59766176-e28f2c80-929f-11e9-913f-9be001b8cb04.png">

**Comment by Charence** [comment]
**Card height incorrect when reopened**

![Jun-19-2019 14-31-11](https://user-images.githubusercontent.com/1438332/59766503-a01a1f80-92a0-11e9-8a9c-d35f9863b1ad.gif)

**Comment by Charence** [comment]
**No user feedback when issues/risks being saved**

![Jun-20-2019 17-20-30](https://user-images.githubusercontent.com/1438332/59860897-15a8ed00-9380-11e9-9ef5-b4b50f5c8599.gif)
