### ISSUE TITLE
Create docker files for docker based installations

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#1583]
### Description

Create appropriate docker configuration files to assist in dockerised deployments.

### Goals

- [x] Dockerfile - base docker image creation
- [x] .dockerignore - reduce the size of the images
- [x] docker-compose.yml - Create a working stack of 3drepo.io / mongodb / rabbitmq
- [x] docker friendly configuration file - confd and etcd based template created
- [ ] update .gitignore for elasticbeanstalk configuration

### Tasks

- [x] Dockerfile for 3drepo.io
- [x] Dockerfile for rabbitmq
- [x] Dockerfile for mongodb
- [x] config.js for docker
- [x] .gitignore
- [x] .dockerignore

**Comment by keifgwinn** [comment]
This work is complete, but currently maintained in a separate private repo. We should decide if we wish to bring over the dockerfile for 3drepo.io for the project for future ease of use and we can maintain the production images separately.

**Comment by keifgwinn** [comment]
this is now completed
