### ISSUE TITLE
Dev bugs 3.9.1

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1592]
- ~Compare card doesn't expand to show full list of models~ Wait for completion of frontend migration
- [x] [Allow selection of current revision in 3D Diff](https://github.com/3drepo/3drepo.io/issues/1592#issuecomment-506286248)

**UI oddities**

- [ ] [Delay when deleting views](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-503542543)
- [x] [Spacing in groups card](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-503542861)
- ~[Card height incorrect when reopened](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-503544666)~ Wait for completion of frontend migration
- [ ] [No user feedback when issues/risks being saved](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-504069965)

**Comment by paloknapo** [comment]
**Compare card doesn't expand to show full list of models**

When you open compare card it doesn't show full list, selecting and deselecting all does the job but it's not ideal.

![01](https://user-images.githubusercontent.com/760452/60258142-737f8c80-98cc-11e9-8872-f5248273ea78.gif)

**Comment by paloknapo** [comment]
**Allow selection of current revision in 3D Diff**

Diffing current revision with itself will produce no result but this is useful to set context for other diffed models.

![image](https://user-images.githubusercontent.com/760452/60258407-00c2e100-98cd-11e9-84b3-da2f57dda808.png)

**Comment by carmenfan** [comment]
> **Compare card doesn't expand to show full list of models**
> 
> When you open compare card it doesn't show full list, selecting and deselecting all does the job but it's not ideal.
> 
> ![01](https://user-images.githubusercontent.com/760452/60258142-737f8c80-98cc-11e9-8872-f5248273ea78.gif)
> 
> Try here:
> https://dev.3drepo.io/viewer/pavol/3bbb646b-b2e6-4d3a-9fd0-5eb4ebd6e471

@dleszcz @simplypixi  can you guys have a look at this one?

**Comment by simplypixi** [comment]
> > **Compare card doesn't expand to show full list of models**
> > When you open compare card it doesn't show full list, selecting and deselecting all does the job but it's not ideal.
> > ![01](https://user-images.githubusercontent.com/760452/60258142-737f8c80-98cc-11e9-8872-f5248273ea78.gif)
> > Try here:
> > https://dev.3drepo.io/viewer/pavol/3bbb646b-b2e6-4d3a-9fd0-5eb4ebd6e471
> 
> @dleszcz @simplypixi can you guys have a look at this one?

@carmenfan @paloknapo Could we wait with fixing this? We'll spend some time fixing height calculatio, but then we'll have to remove that code. xd Currently (on model/viewer migration branch) we got rid of height-setting code. Now we uses native solution (flexbox) and it works pretty good (and fast).

**Comment by carmenfan** [comment]
> > > **Compare card doesn't expand to show full list of models**
> > > When you open compare card it doesn't show full list, selecting and deselecting all does the job but it's not ideal.
> > > ![01](https://user-images.githubusercontent.com/760452/60258142-737f8c80-98cc-11e9-8872-f5248273ea78.gif)
> > > Try here:
> > > https://dev.3drepo.io/viewer/pavol/3bbb646b-b2e6-4d3a-9fd0-5eb4ebd6e471
> > 
> > 
> > @dleszcz @simplypixi can you guys have a look at this one?
> 
> @carmenfan @paloknapo Could we wait with fixing this? We'll spend some time fixing height calculatio, but then we'll have to remove that code. xd Currently (on model/viewer migration branch) we got rid of height-setting code. Now we uses native solution (flexbox) and it works pretty good (and fast).

ok Sure.

Can you guys take a quick look at the other ones too? I think they're all pretty much UI problems

**Comment by simplypixi** [comment]
> > > > **Compare card doesn't expand to show full list of models**
> > > > When you open compare card it doesn't show full list, selecting and deselecting all does the job but it's not ideal.
> > > > ![01](https://user-images.githubusercontent.com/760452/60258142-737f8c80-98cc-11e9-8872-f5248273ea78.gif)
> > > > Try here:
> > > > https://dev.3drepo.io/viewer/pavol/3bbb646b-b2e6-4d3a-9fd0-5eb4ebd6e471
> > > 
> > > 
> > > @dleszcz @simplypixi can you guys have a look at this one?
> > 
> > 
> > @carmenfan @paloknapo Could we wait with fixing this? We'll spend some time fixing height calculatio, but then we'll have to remove that code. xd Currently (on model/viewer migration branch) we got rid of height-setting code. Now we uses native solution (flexbox) and it works pretty good (and fast).
> 
> ok Sure.
> 
> Can you guys take a quick look at the other ones too? I think they're all pretty much UI problems

Sure ;)

**Comment by carmenfan** [comment]
> > > > > **Compare card doesn't expand to show full list of models**
> > > > > When you open compare card it doesn't show full list, selecting and deselecting all does the job but it's not ideal.
> > > > > ![01](https://user-images.githubusercontent.com/760452/60258142-737f8c80-98cc-11e9-8872-f5248273ea78.gif)
> > > > > Try here:
> > > > > https://dev.3drepo.io/viewer/pavol/3bbb646b-b2e6-4d3a-9fd0-5eb4ebd6e471
> > > > 
> > > > 
> > > > @dleszcz @simplypixi can you guys have a look at this one?
> > > 
> > > 
> > > @carmenfan @paloknapo Could we wait with fixing this? We'll spend some time fixing height calculatio, but then we'll have to remove that code. xd Currently (on model/viewer migration branch) we got rid of height-setting code. Now we uses native solution (flexbox) and it works pretty good (and fast).
> > 
> > 
> > ok Sure.
> > Can you guys take a quick look at the other ones too? I think they're all pretty much UI problems
> 
> Sure ;)
> @carmenfan What about priority? Is it more important than Tree/Model/Viewer migration?
> Let me know and then I'll switch the context. :)

I'd say
- Tree
- This
- other Migration

**Comment by dleszcz** [comment]
> * [ ]  [No user feedback when issues/risks being saved](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-504069965)

@Charence @paloknapo 
We cannot reproduce this bug. It was tested on staging?

**Comment by dleszcz** [comment]
> * [ ]  [Delay when deleting views](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-503542543)
> Sometimes, there's a message informing the user that a view is being deleted, but sometimes it doesn't appear.

Do you mean snackbar message in the bottom right corner?

**Comment by Charence** [comment]
> > * [ ]   [Delay when deleting views](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-503542543)
> >   Sometimes, there's a message informing the user that a view is being deleted, but sometimes it doesn't appear.
> 
> @Charence @paloknapo
> Do you mean snackbar message in the bottom right corner?

I mean the user can click on edit or delete multiple times after deleting a view because the item doesn't disappear immediately and the buttons aren't disabled.

**Comment by Charence** [comment]
> > * [ ]   [No user feedback when issues/risks being saved](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-504069965)
> 
> @Charence @paloknapo
> We cannot reproduce this bug. It was tested on staging?

I actually noticed it on master as well. It seems to be more noticeable on a bad internet connection. When save is pressed for a new issue/risk, the button is not disabled.

**Comment by simplypixi** [comment]
> > > * [ ]    [Delay when deleting views](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-503542543)
> > >   Sometimes, there's a message informing the user that a view is being deleted, but sometimes it doesn't appear.
> > 
> > 
> > @Charence @paloknapo
> > Do you mean snackbar message in the bottom right corner?
> 
> I mean the user can click on edit or delete multiple times after deleting a view because the item doesn't disappear immediately and the buttons aren't disabled.

👌 
Fixed ;)

**Comment by simplypixi** [comment]
> > > * [ ]    [No user feedback when issues/risks being saved](https://github.com/3drepo/3drepo.io/issues/1582#issuecomment-504069965)
> > 
> > 
> > @Charence @paloknapo
> > We cannot reproduce this bug. It was tested on staging?
> 
> I actually noticed it on master as well. It seems to be more noticeable on a bad internet connection. When save is pressed for a new issue/risk, the button is not disabled.

Fixed ;)
