### ISSUE TITLE
3.9.3 bugs list

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1605]
### Bugs
- [x] [Pins doesn't appear if it's the issue is added via notification (also the case for modifying a pin)](https://github.com/3drepo/3drepo.io/issues/1605#issuecomment-509190347)
- [x] [Notifications updates not received if the user created the issue and did not reopen it](https://github.com/3drepo/3drepo.io/issues/1605#issuecomment-509191401)
- [x] [The cross to delete someone elses' comment is there if the comment has a screenshot](https://github.com/3drepo/3drepo.io/issues/1605#issuecomment-509192694)
- [x] Get it to auto-open links on resources
 - <del> [Can't upload resource](https://github.com/3drepo/3drepo.io/issues/1605#issuecomment-509255317) </del> config problem
- [x] [No Description in Issues list preview.](https://github.com/3drepo/3drepo.io/issues/1605#issuecomment-510015243)

**Comment by carmenfan** [comment]
**Pins doesn't appear if it's the issue is added via notification (also the case for modifying a pin)**
- open the same model with 2 different accounts
- create a new issue with pin (or modify an existing issue with a pin)
- a new issue appears in the browser of the other account, but pin is not visible 
![2](https://user-images.githubusercontent.com/11945337/60807310-38f3da80-a17d-11e9-9818-dd479f0b2ea2.gif)

**Comment by carmenfan** [comment]
**Notifications updates not received if the user created the issue and did not reopen it**
Let's say there's 2 users in 2 different browser, A and B
- A creates an issue and stays on that page
- B opens this issue and comment on it
- A does not see the comment updates unless he exits to issues lists and re-enter the issue

**Comment by carmenfan** [comment]
**The cross to delete someone elses' comment is there if the comment has a screenshot**
Let's say there's 2 users in 2 different browser, A and B
- both A and B opens the same issue
- A comments on it with a screen shot
- B can see the updated comment with a cross, but if he clicks on it , it says "not authorised".

B shouldn't see the X in the first place

**Comment by paloknapo** [comment]
**Can't upload resource**

1. hit attach resource button and select files
2. OK
3. upload starts but just before finish it throws this error
![image](https://user-images.githubusercontent.com/760452/60819225-1ff82300-a197-11e9-9613-d5f9cec2be14.png)
![image](https://user-images.githubusercontent.com/760452/60819246-25ee0400-a197-11e9-80d0-20ff454cc2ff.png)

Try here:
https://dev.3drepo.io/viewer/pavol/d6f913ad-1432-47c3-bc46-8f551869dce6?issueId=6536a9e0-a18e-11e9-98fb-ef8c0732510c

**Comment by BDavydov** [comment]
**No Description in Issues list preview.** 

Applies to existing and new issues. 

- Open issue cart
- Click on the issue to open
- Description present in the issue
![Issue Description](https://user-images.githubusercontent.com/19904513/60964124-7174ef00-a30a-11e9-837f-4ad119fdf430.gif)

**Comment by BDavydov** [comment]
**Issue Cart not updating its size after log review.**

- Open issue cart and open an issue
- Collapse the issue to review the log history
- Expand the issue information again
![Issue Log](https://user-images.githubusercontent.com/19904513/60965168-12fd4000-a30d-11e9-99ca-e088b8c79153.gif)
