### ISSUE TITLE
Teamspaces: Grid view

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1608]
### Tasks

- [x] Teamspaces
  - [x] Reimplementing teamspaces structure
  - [x] Searchnig
  - [x] Sorting
  - [x] Updating project item design
  - [x] Updateing teamspace item deign
- [x] New model/federation card component
- [x] Starred models/federations
  - [x] Storing the data
  - [x] Adding tabs (model/federations, starred)
- [x] Model upload dialog
- [x] Revisions dialog

### Design notes

Model name 120 chars limit - abbreviate if doesn't fit 2 lines and show full name on tooltip

Model code 50 chars limit - scale to font fit 
Suitability code 10 chars limit (mostly no longer than 5)

Clicking the card opens model/federation 
Upload and all other commands are accessible from menu 
on hover menu is gone

### Other notes

Teamspace view:
* Instead of list layout, change it to grid layout
* Add profile picture and name for teamspace info
* Each fed/model becomes a card instead taking up a row
* Each card should also show all the model code and the latest suitability code (we'll change the api to give it with the model list)
* Federation has different background to differentiate them
* On hover is gone, clicking on card opens the model/federation, all commands are available from the menu
* Add share link to menu - it copies URL to model/federation and shows message
* Starred tab, show only star components in the grid view
* Can star across teamspaces
* Starred should be stored like meta starred -> API to follow
* Star should work like meta, has 3 seconds delay to remove and shows undo icon
* Sort commands to sort models/fed by name or modified
* Search button to be able to search teamspaces, project, fed/model
* Menu to be able to narrow search 
* Ability to search model code/suitability code

Revisions listing:
* Add file type + suitability code to entry
* Ability to make revision active or void - API to follow to support this
* Set as latest essentially set any later revisions void
* We'll add to the GET API to have a query string to be able to see void revisions or not

Model upload:
* Suitability code when uploading a new revision (not compulsory)  

Design:
https://xd.adobe.com/view/9214502d-304d-4de6-67fb-68d7e2e241e3-e425/

**Comment by simplypixi** [comment]
@carmenfan @sanmont3drepo From which branch should we start? Staging or model/viewer migration branch (the lastest react features)? I think it depends on your priorities, so let us know. ;)

**Comment by carmenfan** [comment]
i think this should be based of your migration branch

**Comment by dleszcz** [comment]
> Model code 50 chars limit - scale to font fit

@carmenfan on model settings, we have **5** chars limit, so I'm guessing this 50 is a mistake?

We will need these pieces of information about model/federation:
- model code
- suitability code
- last update
(currently returned data on the screenshot below)
![Screenshot 2019-07-17 at 14 42 28](https://user-images.githubusercontent.com/17221890/61376396-69d0bf80-a8a1-11e9-9cd5-20e62ee0483a.png)

Also, we will need some backend to:
- making void
- making active
- starred models/federations

Let us know when it's ready. So far we will be mocking data :)

**Comment by carmenfan** [comment]
> > Model code 50 chars limit - scale to font fit
> 
> @carmenfan on model settings, we have **5** chars limit, so I'm guessing this 50 is a mistake?
> 
no, Pavol wanted it longer. 50 is intentional

> We will need these pieces of information about model/federation:
> 
> * model code
> * suitability code
> * last update
>   (currently returned data on the screenshot below)
>   ![Screenshot 2019-07-17 at 14 42 28](https://user-images.githubusercontent.com/17221890/61376396-69d0bf80-a8a1-11e9-9cd5-20e62ee0483a.png)
> 

Forget about suitability code for now. It takes a lot more backend changes to support what pavol envisioned...

> Also, we will need some backend to:
> 
> * making void
> * making active
> * starred models/federations
> 
> Let us know when it's ready. So far we will be mocking data :)

ok. We are moving offices again... 😆 so I don't think it'll happen until next week

**Comment by carmenfan** [comment]
> We will need these pieces of information about model/federation:
> 
> * model code
> * suitability code
> * last update
>   (currently returned data on the screenshot below)

@dleszcz 

Model code added. 
Suitability code is dropped as discussed.
last update is basically the timestamp.
![image](https://user-images.githubusercontent.com/11945337/61640399-24433680-ac95-11e9-9a0a-b441db56c490.png)

**Comment by carmenfan** [comment]
Set a revision to void (to set a revision as active, send `void: false`):
![image](https://user-images.githubusercontent.com/11945337/61647349-0f6e9f00-aca5-11e9-8e81-6eb5942d0c12.png)


Get revisions by default does not list the void revisions, add `showVoid` as a query string to see the void revisions:
![image](https://user-images.githubusercontent.com/11945337/61647267-e6e6a500-aca4-11e9-8790-17f521c15515.png)

**Comment by carmenfan** [comment]
starred models api:

````js
/**
 * @api {get} /starredModels Gets the starred models for the logged user
 * @apiName GetStarredModels
 * @apiGroup User
 * */
router.get("/starredModels", middlewares.loggedIn, getStarredModels, onSuccess);

/**
 * @api {post} /starredModels Adds a starred models for the logged user
 * @apiName StarModels
 * @apiGroup User
 *
 * @apiParam  {String} tag The tag to be starred
 * @apiParamExample {json} Input
 *    {
 *      "teamspace": "user1",
 *      "model": "c7d9184a-83d3-4ef0-975c-ba2ced888e79"
 *    }
 *
 * @apiSuccessExample {json} Success
 *    HTTP/1.1 200 OK
 *	  {}
 *
 * @apiError 400 BadRequest The request was malformed
 * */
router.post("/starredModels", middlewares.loggedIn, appendStarredModels, onSuccess);

/**
 * @api {put} /starredModels Sets the whole starred models for the logged user
 * @apiName SetStarredModels
 * @apiGroup User
 *
 * @apiParam  [String]  An array of models to be starred
 * @apiParamExample {json} Input
 *    {
 *     	"user1": ["c7d9184a-83d3-4ef0-975c-ba2ced888e79"],
 *     	"user2": ["4d17e126-8238-432d-a421-93819373e21a", "0411e74a-0661-48f9-bf4f-8eabe4a673a0"]
 * 	  }
 *
 * @apiSuccessExample {json} Success
 *    HTTP/1.1 200 OK
 *	  {}
 *
 * @apiError 400 BadRequest The request was malformed
 * */
router.put("/starredModels", middlewares.loggedIn, replaceStarredModels, onSuccess);

/**
 * @api {delete} /starredModels removes a starred models for the logged user if the tag exists
 * @apiName UnstarModels
 * @apiGroup User
 *
 * @apiParam  {String} tag The tag to be starred
 * @apiParamExample {json} Input
 *    {
 *      "teamspace": "user1",
 *      "model": "c7d9184a-83d3-4ef0-975c-ba2ced888e79"
 *    }
 *
 * @apiSuccessExample {json} Success
 *    HTTP/1.1 200 OK
 *	  {}
 *
 * @apiError 400 BadRequest The request was malformed
 * */
router.delete("/starredModels", middlewares.loggedIn, deleteStarredModels, onSuccess);
````


I believe this is all. Let me know if I missed something. I'll probably make a few more commits for travis!
