### ISSUE TITLE
Risks and Issues refactor: move out common logic to another file (update)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1621]
### Description
In order to have a more readable code a refactor of issues and risks should take place in the backend.

### Tasks
- [x] Move out update common logic to new "Tickets" model
- [x] Refactor issue to use tickets model while keeping its own distinct logic
- [x] Refactor risk to use tickets model while keeping its own distinct logic
