### ISSUE TITLE
Unity Caching and Unity Update

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1641]
### Description
Update Unity to 2018.4.x and investigate on cache policies

### Goals
- [x] Working webassembly version of the unity game engine
- [ ] Unity Caching working on demand
- [ ] Cache policy for things like tree

### Tasks
- [ ] Update code to support unity API changes in https://github.com/3drepo/3drepounity/issues/222
- [ ] Add new cache properties in viewer settings
- [ ] add cache policy settings on the backend
