### ISSUE TITLE
3.11.3 - bug list

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1682]
### Bugs
- [x] [Cannot turn off model caching](https://github.com/3drepo/3drepo.io/issues/1682#issuecomment-527852172)
- [x] [Add warning message when a user turn on caching](https://github.com/3drepo/3drepo.io/issues/1682#issuecomment-527852489)
- [x] [Viewer settings needs to be stored on a user by user basis](https://github.com/3drepo/3drepo.io/issues/1682#issuecomment-527876198)

**Comment by carmenfan** [comment]
**Cannot turn off model caching**
Turn it off - log off and log back in -> it's turned on again.

**Comment by carmenfan** [comment]
**Add warning message when a user turn on caching**
WARNING - This feature will save model data to your browsers cache. If you are using a shared computer, be sure to clear the cache before logging out

**Comment by carmenfan** [comment]
**Viewer settings needs to be stored on a user by user basis**

Currently all users are sharing the same settings
