### ISSUE TITLE
Screenshot paint

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1683]
**Description**
Drawing on screenshots in the viewer.

**Tasks**

- [x] Removing the old code
- [x] Install & configure library (https://github.com/konvajs/react-konva)
- [x] Add toolbar component
- [x] Change colour feature
- [x] Change width of line
- [x] Implement drawing mode
- [x] Implement shape mode & custom shapes
- [x] Implement text mode
- [x] Implement earsing mode
- [x] Implement undo/redo feature
- [x] Implement clear all feature
- [x] Save screenshot
- [x] Cancel screenshot

**Comment by carmenfan** [comment]
@dleszcz can you do this base on staging? It'd be good if we can reduce the amount of features being stuck behind the tree 😆

**Comment by dleszcz** [comment]
> @dleszcz can you do this base on staging? It'd be good if we can reduce the amount of features being stuck behind the tree 😆

Sure ;)
