### ISSUE TITLE
Invite users into teamspace by email

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1723]
### Description
At the moment, users can only invite other users into their teamspace. If the person they wish to invite does not have a 3drepo account, they will have to wait for the users to get one before they can invite them.

We want to change it so if the user tries to add an unrecognised email into their teamspace, the system then:
- Send an email to the person saying xxx has invited you to join 3D Repo 
- Once the teamspace owner has sent out an invitation, one of the license should be reserved for the invitee.
- The teamspace owner should be able to revoke the reserved license should they change their mind.
- The teamspace owner should be notified once the person has signed up (& activated) their account.
- Upon registration, the user should automatically become a user within that teamspace (unless the invitation has been revoked.)

### Tasks
- Get Business team to design an email template
- Figure out the necessary change in the database to track placeholder licenses (ghost user account that becomes live when someone registers with the same email address?)
- implement the feature

### Mockup
https://marvelapp.com/d272287/screen/62984136

### Frontend tasks
- [ ] Create new module: invitations (?)
- [x] Add "sent invitation" suggestion if user doesn't exist (https://marvelapp.com/d272287/screen/62985222)
- [x] Add invitation "button" in new user popup
- [x] Create invitations modal (https://marvelapp.com/d272287/screen/62984236)
  - [x] Display invitations list
  - [x] Handle removing invitation
  - [x] Display "Add" button and handle logic
- [x] Create new/edit invitation modal
  - [x] Add email field (should be pre-populated with whatever user typed in the previous UI)
  - [x] Add job field
  - [x] Add "teamspace admin" checkbox
  - [x] Handle adding project/model permissions (should be hidden if "teamspace admin" is checked)
    - [x] Add project dropdown
    - [x] Add "project admin" checkbox
    - [x] Create new permissions table component to handle projects/models permissions from single user perspective
    - [x] Hide permissions table if "project admin" is checked
    - [x] Footer should be sticky, content should be scrollable
  - [x] Handle saving logic (send request to the BE and show snackbar on success)
- [x] Add information about pending invitations to the footer

**Comment by simplypixi** [comment]
@carmenfan @sanmont3drepo When can we expect those changes will be merged with staging?
We need those changes and small dialog changes (eg. showing multiple dialogs at the same time) from "Kanban Board branch" to implement the invitation feature properly. ;)

**Comment by carmenfan** [comment]
I think you can just do the work on this branch. As it's difficult to test these changes without the UI and these changes has no use without the UI implemented.

For Kanban I'll put it up on our dev server for the business guys to have another play to see if they have any more feedback

**Comment by simplypixi** [comment]
@sanmont3drepo Is it necessary to use projects' names instead of their ids?

**Comment by sanmont3drepo** [comment]
> @sanmont3drepo Is it necessary to use projects' names instead of their ids? Is any specific reason to do that this way?
The reason is just legacy to be honest, everywhere is using project names. But we are changing it to use ids

**Comment by simplypixi** [comment]
@carmenfan @sanmont3drepo FE part is ready ;)

**Comment by sanmont3drepo** [comment]
> @carmenfan @sanmont3drepo FE part is ready ;)

Mariusz have you changed the FE to use project ids instead of project names?

**Comment by carmenfan** [comment]
@sanmont3drepo  I haven't migrated their database yet 

@simplypixi  the API has changed to address projects with project ID. It will probably break your backend code however due to the database needs to be migrated. I will do this soon.

**Comment by carmenfan** [comment]
@sanmont3drepo @simplypixi database migrated.

**Comment by simplypixi** [comment]
@carmenfan @sanmont3drepo Updated ;)

**Comment by carmenfan** [comment]
@simplypixi thanks!

@sanmont3drepo Can you make a PR once @BDavydov has given you an email template?

**Comment by sanmont3drepo** [comment]
> @simplypixi thanks!
> 
> @sanmont3drepo Can you make a PR once @BDavydov has given you an email template?

sure!
