### ISSUE TITLE
v3.15.2 bug list

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1767]
### Bugs
- <del> Sometimes federation message is stuck in queue even though it has completed </del> _This is not a bug with the code, it's because staging and dev are sharing a queue_

- [x] [Scroll bar and component size doesn't scale properly on tree search](https://github.com/3drepo/3drepo.io/issues/1767#issuecomment-548447451)
- [x] [Metadata not found error when the node has no metadata](https://github.com/3drepo/3drepo.io/issues/1767#issuecomment-548454985)
- [x] [Add tooltip on tree nodes to show the full name](https://github.com/3drepo/3drepo.io/issues/1767#issuecomment-548456031)
- <del> [Federation isn't being produced](https://github.com/3drepo/3drepo.io/issues/1767#issuecomment-548745526)</del> _bouncer was down_
- [ ] [Grid view bugs](https://github.com/3drepo/3drepo.io/issues/1767#issuecomment-548836189)
- [ ] [Can not filter Teamspaces using Model Type/Code](https://github.com/3drepo/3drepo.io/issues/1767#issuecomment-549282658)

**Comment by BDavydov** [comment]
Problem with the model tree filtering

**Description**
When you filter a model tree and it contains a limited set of results (2-5 items) shrinks in size

**How to recreate**
- Open a tree window of any model
- Start searching for a specific model element (preferably there are few of them in a model)
![Model Tree](https://user-images.githubusercontent.com/19904513/67964275-ea6cbf00-fbf7-11e9-91d0-400273d38dd5.gif)

**Comment by carmenfan** [comment]
**Metadata not found error when the node has no metadata.**

**Comment by carmenfan** [comment]
**Add tooltip on tree nodes to show the full name**

**Comment by BDavydov** [comment]
Can't fetch a full tree when opening a new Federation

**Description** 
When you create a new federation & then open it, the error message comes up. Works for IFC & NWC files

**How to Recreate**
- Create a new Federation
- Open it and receive the error code
![Can't fetch a full tree](https://user-images.githubusercontent.com/19904513/68019865-c7dcb380-fc94-11e9-8a6c-b8d67cbd0fac.jpg)

**Comment by BDavydov** [comment]
> Can't fetch a full tree when opening a new Federation
> 
> **Description**
> When you create a new federation & then open it, the error message comes up. Works for IFC & NWC files
> 
> **How to Recreate**
> 
> * Create a new Federation
> * Open it and receive the error code
>   ![Can't fetch a full tree](https://user-images.githubusercontent.com/19904513/68019865-c7dcb380-fc94-11e9-8a6c-b8d67cbd0fac.jpg)

The same happens to the Issues List, even though there are no issues in the new federation.
![Risks](https://user-images.githubusercontent.com/19904513/68020071-49ccdc80-fc95-11e9-8988-b1970049db30.jpg)

**Comment by carmenfan** [comment]
**Grid view bugs:**
- [ ] You shouldn't be able to upload or edit a federation whilst there's a version being processed
- [ ] Revisions should get incremented once a model has been imported
- [ ] timpstamp should be updated once a model has been imported

**Comment by BDavydov** [comment]
Can not filter Teamspaces using Model Type/Code

**Description**
When I click on the model type ie. Architectural or Structural, my teamspace or any other is not filtered accordingly. The same happens to the Model Code.

**How to recreate:**
- Log in to 3drepo
- In Teamspaces activate Search/Filter option
- Choose your model type as a filter chip
![Model Type Filter](https://user-images.githubusercontent.com/19904513/68112186-b8ee3f00-fee8-11e9-8b34-0cf1999be2f8.gif)
