### ISSUE TITLE
v4.0 bugs

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1777]
- [x] [For some models you can't show an object again after hiding.](https://github.com/3drepo/3drepo.io/issues/1777#issuecomment-549783832)
- [x] [Group returning 404 on some federations](https://github.com/3drepo/3drepo.io/issues/1777#issuecomment-549804748)
- [x] [Helicopter speed change return 404](https://github.com/3drepo/3drepo.io/issues/1777#issuecomment-549804989)

**Comment by carmenfan** [comment]
**For some models you can't show an object again after hiding.**

try this: 
- load https://dev.3drepo.io/viewer/carmen/648e6010-fca0-11e9-b0b4-7dccb0ec4ff4
- hide any object
- show it again - nothing happens.

**Comment by carmenfan** [comment]
**Group returning 404 on some federations**
Get groups request return with 404 error if:
- The model is a federation
- at least one of the submodel has no revisions
- the federation has a smart group

**Comment by carmenfan** [comment]
**Helicopter speed change return 404**
- Change navigation mode to helicopter
- increase/decrease/reset speed would return with a 404 error
