### ISSUE TITLE
Invitations UI

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1790]
#### Mockup
https://marvelapp.com/d272287/screen/62984136

#### Tasks
- [ ] Create new module: invitations (?)
- [x] Add "sent invitation" suggestion if user doesn't exist (https://marvelapp.com/d272287/screen/62985222)
- [x] Add invitation "button" in new user popup
- [ ] Create invitations modal (https://marvelapp.com/d272287/screen/62984236)
  - [ ] Display invitations list
  - [ ] Handle removing invitation
  - [ ] Display "Add" button and handle logic
- [ ] Create new/edit invitation modal
  - [ ] Add email field (should be pre-populated with whatever user typed in the previous UI)
  - [ ] Add job field
  - [ ] Add "teamspace admin" checkbox
  - [ ] Handle adding project/model permissions (should be hidden if "teamspace admin" is checked)
    - [ ] Add project dropdown
    - [ ] Add "project admin" checkbox
    - [ ] Create new permissions table component to handle projects/models permissions from single user perspective
    - [ ] Hide permissions table if "project admin" is checked
    - [ ] Footer should be sticky, content should be scrollable
  - [ ] Handle saving logic (send request to the BE and show snackbar on success)
- [ ] Add information about pending invitations to the footer
