### ISSUE TITLE
Bugs with Issues functionality in Kanban Board & Model Viewer

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1808]
### Bugs
- [x] [Can't Udpdate Issues](https://github.com/3drepo/3drepo.io/issues/1808#issuecomment-558703451)
- [x] [Issue Title in Mozilla Firefox](https://github.com/3drepo/3drepo.io/issues/1808#issuecomment-558710862)
- [x] [Issue cards become large when changing topic](https://github.com/3drepo/3drepo.io/issues/1808#issuecomment-559023746)
- [x] [Bigger popup for issue details](https://github.com/3drepo/3drepo.io/issues/1808#issuecomment-559461645)

**Comment by BDavydov** [comment]
### Description
Even though I am the creator of an issue, I can't change Priority, Status, Assign, Type, Due Date

### Steps to replicate
- Open a Kanban board
- Create a new issue for any project
- Re-open the issue you have created and try to change the fields

### Pictures of the error
![image](https://user-images.githubusercontent.com/19904513/69651333-d2a62080-1067-11ea-8d54-223591b26dad.png)

**Comment by BDavydov** [comment]
### Description
This issue is applicable to Mozilla Firefox.
Issue title is overlapping the information. When writing a long issue title, not all text is visible. 

### Steps to replicate
- Open Mozilla Firefox browser
- Log in to 3D Repo & open Kanban Board 
- Create a new issue and write a long string of characters
- Save the issue and open it again. 

### Pictures of the error
![image](https://user-images.githubusercontent.com/19904513/69652093-046bb700-1069-11ea-9201-0a190a9171f9.png)
![Issue Title](https://user-images.githubusercontent.com/19904513/69652903-447f6980-106a-11ea-98ba-09131f36f039.gif)

**Comment by carmenfan** [comment]
@simplypixi can you take a look at these?

**Comment by simplypixi** [comment]
@carmenfan Yeah, sure ;)

**Comment by BDavydov** [comment]
### Description
This issue is applicable to Mozilla Firefox.
Issue cards jumping around the screen when changing the topic to group them. 

### Steps to replicate
- Open Mozilla Firefox browser
- Log in to 3D Repo & open Kanban Board 
- Start changing the Group by field

### Pictures of the error
![Sorting Issues in Kanban Board](https://user-images.githubusercontent.com/19904513/69714218-ed2ad900-10fd-11ea-8e4f-409504ba67a7.gif)

**Comment by carmenfan** [comment]
**Bigger popup for issue details**
![image](https://user-images.githubusercontent.com/11945337/69803480-2e8db800-11d4-11ea-8101-439b616c2213.png)
There's quite a bit of unnecessary scrolling going on as we are not utilising the entire height of the screen for the pop up, can we make this component longer?

**Comment by m1chalkubiak** [comment]
> ### Description
> This issue is applicable to Mozilla Firefox.
> Issue title is overlapping the information. When writing a long issue title, not all text is visible.

@BDavydov @carmenfan 
I'm still working on the writing of title in FF, this bug is very weird.

**Comment by m1chalkubiak** [comment]
Hi  @BDavydov @carmenfan 
I manage to fix all the issues. After long debugging I discovered that The problem with text input on FF was caused by updating the placeholder during writing.
[PR 1819](https://github.com/3drepo/3drepo.io/pull/1819)
