### ISSUE TITLE
Frontend tests

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1817]
### Description
Add frontend testing to ensure a basic level of stability when deploying 

### Goals
- [x] Test should run before deploying
- [x] Sign in test when entering correct credentials
- [ ] Sign in test when entering incorrect credentials

### Tasks
- [ ] Add frontend test runner
- [ ] Run tests in travis
- [ ] Add sign in test when entering correct  credentials
- [ ] Sign in test when entering incorrect credentials
