### ISSUE TITLE
Add option to set transparency for groups colour override

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1820]
### Description
Allow users to set an optional transparency setting, which will be applied on groups override

See https://marvelapp.com/80ef7f5/screen/64222126 for mock up

### Tasks
- [x] Add unity-utils functions to change objects transparency value (Carmen)
- [x] Add transparency value into groups data schema (should be separate to colour, as it is optional)
- [x] Add set transparency UI to colour picker (should only be visible for groups for now). Default setting when enabled should be set to 100% (opaque)
- [x] If possible, it'd be nice to show the colour swatch being affected by the transparency value

**Comment by carmenfan** [comment]
Unity updated: 06fb7173376e8fa1f124920ef429c3f503d0f92b
