### ISSUE TITLE
4.1.3 Bug List 

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1846]
- [x] Groups UI save button state is incorrect
- [x] [SafetiBase risk status icon missing](https://github.com/3drepo/3drepo.io/issues/1846#issuecomment-567596801)
- [x] [Transparent obejcts become Opaque](https://github.com/3drepo/3drepo.io/issues/1846#issuecomment-567907876)
- [x] [Not all elements follow the Opacity setting](https://github.com/3drepo/3drepo.io/issues/1846#issuecomment-567911434)
- <del> [Revisions List](https://github.com/3drepo/3drepo.io/issues/1846#issuecomment-567856408) </del>not fixing this release  https://github.com/3drepo/3drepo.io/issues/1797

**Comment by carmenfan** [comment]
**Groups UI:**
- [ ] Save button shouldn't be enabled by default, it should only be enabled when someone changed something
- [ ] If the Group is saved without any objects, the save button is forever disabled
- [ ] If you go into a group and edited the highlighting -> save. The button is disabled and you cannot edit objects again until you refresh

**Comment by Charence** [comment]
**Didn't the risk card used to have a status icon?**

![Screenshot 2019-12-19 17 55 56](https://user-images.githubusercontent.com/1438332/71197181-f6384180-2288-11ea-87ba-4b56d6701224.png)

It should have a status icon that changes colour and symbol.

Issues has its own set of icons and colours in this position.

**Comment by BDavydov** [comment]
### Description
Revisions count does not correlate with the revisions list.

### Steps to replicate
- Create a new model
- Upload first model Revisions
- Click on the model revisions to see the list

### Pictures/ Gifs of the error
![Revisions Bug](https://user-images.githubusercontent.com/19904513/71244580-bf0a7480-230a-11ea-98a6-8092737e37aa.jpg)
![Revisions Bug - 2](https://user-images.githubusercontent.com/19904513/71244581-c03ba180-230a-11ea-9d08-d046ffcba236.jpg)
![Revisions Bug - 3](https://user-images.githubusercontent.com/19904513/71244584-c16cce80-230a-11ea-8c52-942db058bef8.jpg)
![Revisions Bug - 4](https://user-images.githubusercontent.com/19904513/71244586-c29dfb80-230a-11ea-986c-4588890883bc.jpg)

**Comment by BDavydov** [comment]
### Description
Lego House does not load but exists in the tree.

### Steps to replicate
- Create a new account
- Open lego house federation
- click on model elements in the tree to see them
### Pictures/ Gifs of the error

![Lego Federation](https://user-images.githubusercontent.com/19904513/71249652-9a67ca00-2315-11ea-837b-a3c7fde3626b.jpg)
![Lego Federation 2](https://user-images.githubusercontent.com/19904513/71249656-9d62ba80-2315-11ea-9428-7e860173981a.jpg)
![Lego Federation 3](https://user-images.githubusercontent.com/19904513/71249661-9f2c7e00-2315-11ea-8de6-0bfb9b22ffb0.jpg)

**Comment by BDavydov** [comment]
### Description
Groups Opacity seems to change when overriding already transparent objects. When you assign a colour to the group, elements that contain transparent objects are set to opaque

### Steps to replicate
- Open a model or Federation
- Create a smart group and search for elements that contain transparency
- Assign colour and save
- Override group colour

### Pictures/ Gifs of the error
![Opacity](https://user-images.githubusercontent.com/19904513/71254603-65627400-2323-11ea-87f6-3bb8bfd22a5d.gif)

**Comment by BDavydov** [comment]
### Description
Opacity setting does not apply to all of the model elements inside a group.

### Steps to replicate
- Open a model or Federation
- Create a smart group
- Assign colour and save
- Set the opacity to less than 50%
- Override group colour

### Pictures/ Gifs of the error

![Transparency](https://user-images.githubusercontent.com/19904513/71255390-b4a9a400-2325-11ea-9ddb-0e023323f5c5.gif)
![Groups 1](https://user-images.githubusercontent.com/19904513/71255407-bb381b80-2325-11ea-82d7-0f166e361ef4.jpg)
![Groups 2](https://user-images.githubusercontent.com/19904513/71255409-bd9a7580-2325-11ea-8cf4-116e75d40eca.jpg)
