### ISSUE TITLE
4.1.3 Bug List 2

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1853]
- [x] [Sub Project Issues do not open in Federations](https://github.com/3drepo/3drepo.io/issues/1853#issuecomment-572537572)
- <del>[Issues can be saved without a title] (https://github.com/3drepo/3drepo.io/issues/1853#issuecomment-572540798)</del> N/A
- <del> [New Models/Projects get a grey list from user management icon click](https://github.com/3drepo/3drepo.io/issues/1853#issuecomment-572544984) </del> moving this to a separate issue: https://github.com/3drepo/3drepo.io/issues/1856
- [x] [Issue filter by Type](https://github.com/3drepo/3drepo.io/issues/1853#issuecomment-572613738)
- [x] [Can not change colour in the markup tool](https://github.com/3drepo/3drepo.io/issues/1853#issuecomment-573062389)
- [x] [Issues & SafetiBase Pins visibility toggle disappears from the menu](https://github.com/3drepo/3drepo.io/issues/1853#issuecomment-573704436)

**Comment by BDavydov** [comment]
### Description
Sub-model Issues load in federations but you can not open them

### Steps to replicate
- Create some models (example Model A & B)
- Add Issues to individual models (to Model A or B)
- Federate Models (Model A & B)
- Load Sub-model issues
- Click on sub-model issue and try opening them

### Pictures/ Gifs of the error
![Sub Model Issues](https://user-images.githubusercontent.com/19904513/72067348-665f4380-32da-11ea-9d69-f383fee85b58.gif)

**Comment by BDavydov** [comment]
### Description
You can create an issue and not give it a title. 
'This field is required' message only comes up when you click on the title

### Steps to replicate
- Open a model/federation
- Start creating a new issue
- Update any field or add a screenshot
- Save the issue without updating the title

### Pictures/ Gifs of the error
![Untitled Issue](https://user-images.githubusercontent.com/19904513/72067863-b985c600-32db-11ea-8801-268594a53e70.gif)

**Comment by BDavydov** [comment]
### Description
New Models or Projects do not open the relevant page in User permissions. 
When you click on the user permissions tab for existing projects or models, it shows the relevant information. Any new model or Project give blank grey page.

### Steps to replicate
- Create a new project
- Create a few models in that project
- Click on the User Permission Icon
- Get a grey list of contents
- Click on the User permissions icon of an existing model/project
- Receive a list of information in User Management

### Pictures/ Gifs of the error
![Project   Model Permissions](https://user-images.githubusercontent.com/19904513/72068675-80e6ec00-32dd-11ea-9c9f-2567f9535db5.gif)

**Comment by BDavydov** [comment]
### Description
Filtering Issues by Type generates a chip stat says 'Undefined' 
It is still filtering the list, but users do not know what they filter for.

### Steps to replicate
- Open a model or Federation that contains some issues
- Activate search Icon
- Start Filtering by Type

### Pictures/ Gifs of the error
![Issue Filtering by Type](https://user-images.githubusercontent.com/19904513/72080697-1fcb1280-32f5-11ea-8097-c27280cec2ae.gif)

**Comment by BDavydov** [comment]
### Description
Can not change colour in the markup tool after changing it once already.

### Steps to replicate
- Log in to 3D Repo and open a model
- Create an issue
- In the issue create a markup of the screenshot
- Create a first random shape and commit it
- Change colour for the first time and create a second random shape
- Try changing colour again ( for the 2nd time) 
- Either error message will pop up or you will not be able to save the colour selection

### Pictures/ Gifs of the error
![Change Colour](https://user-images.githubusercontent.com/19904513/72161142-7731b700-33b7-11ea-9da5-c3ed71b2a461.gif)

**Comment by BDavydov** [comment]
### Description
Clicking on 'Show Pins' makes this option disappear completely. The same thing is happening with SafetiBase Pins

### Steps to replicate
- Log in to 3drepo.io and open any model
- Create a few issues with pins (if none exist)
- Open the issues option menu
- Click on 'Show Pins' 
- It disappears completely

### Pictures/ Gifs of the error
![Issue Pins visibility](https://user-images.githubusercontent.com/19904513/72265902-320ac080-3615-11ea-87e9-9e425af959a4.gif)
