### ISSUE TITLE
Block simultaneous login

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1866]
### Description
Block simultaneous login

### Goals
- Block simultaneous login for the same user when accessing through a browser
- Allow simultaneous login for desktop/mobile client
- Use chat to notify unseated session that they have logged in elsewhere

### Tasks
- [x] Identify login session source (web or other)
- [x] Invalidate older web sessions for user
- [x] Establish chat channel for session based on session ID
- [x] Notify user their session has been terminated
