### ISSUE TITLE
v4.3.1 bug list

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1869]
### Bugs
- [x] [BIM Data only comes up on second click](https://github.com/3drepo/3drepo.io/issues/1869#issuecomment-578714918)
- [x] [BIM Card Remains Open](https://github.com/3drepo/3drepo.io/issues/1869#issuecomment-578716554)
- [x] [BIM Card White Space](https://github.com/3drepo/3drepo.io/issues/1869#issuecomment-578718277)
- [x] [Show Coordinates does not work](https://github.com/3drepo/3drepo.io/issues/1869#issuecomment-579175984)
- [x] [Measurement feature brings up BIM Card](https://github.com/3drepo/3drepo.io/issues/1869#issuecomment-579176028)

**Comment by BDavydov** [comment]
### Description
BIM Cart only opens when you click on the element twice or every 2nd mouse click.
 
### Steps to replicate
- Open a model in dev.3drepo.io
- Activate BIM Cart
- Click on a model element and click again to show BIM Data.

### Pictures/ Gifs of the error
![BIM Cart](https://user-images.githubusercontent.com/19904513/73172512-19ada200-40fb-11ea-9916-161aa00dfdf7.gif)

**Comment by BDavydov** [comment]
### Description
BIM Cart remains open when you load a new/different model after leaving the previous model by clicking on the teamspace icon and using the BIM Cart at the same time.
 
### Steps to replicate
- Open a model in dev.3drepo.io
- Activate BIM Cart
- Click on the model element to bring up the data
- Click on the Teamspaces Icon in the Top Right corner
- Load a new/different model
- BIM Cart remains open, even though it's not activated in the toolbar

### Pictures/ Gifs of the error
![BIM Cart Open](https://user-images.githubusercontent.com/19904513/73173208-c3416300-40fc-11ea-8ac6-6804bd7d5605.gif)

**Comment by BDavydov** [comment]
### Description
BIM Card white space
 
### Steps to replicate
- Open a model in dev.3drepo.io
- Activate BIM Card
- Click on the model element to bring up the data
- If the element contains little amount of data, there is a lot of white space

### Pictures/ Gifs of the error
![BIM Cart White Space](https://user-images.githubusercontent.com/19904513/73173553-86c23700-40fd-11ea-9577-bc73ee075a9a.gif)

**Comment by carmenfan** [comment]
### Description
Show coordinates does not work
 
### Steps to replicate
- Open a model in dev.3drepo.io
- Activate 'Show Coordinates' in the toolbar
- Click anywhere on a model

### Pictures/ Gifs of the error
![Tool Bar Coordinates](https://user-images.githubusercontent.com/19904513/73253207-f85cbc80-41b3-11ea-8b9e-5bd8d16cff5b.gif)

**Comment by carmenfan** [comment]
### Description
Clicking on measurement option brings up the BIM Card.
 
### Steps to replicate
- Open a model in dev.3drepo.io
- Activate 'Measurement' feature from a toolbar
- Click again to deactivate it
- Click again to hide BIM Card and activate the measurement feature alone

### Pictures/ Gifs of the error
![Tool Bar Measurement](https://user-images.githubusercontent.com/19904513/73253500-905aa600-41b4-11ea-98f8-efa98717492a.gif)
