### ISSUE TITLE
stop sending/storing empty objects on comment post

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1897]
When we send a comment with no viewpoint/screenshot we're currently sending this:

![image](https://user-images.githubusercontent.com/11945337/74346138-05c69900-4da7-11ea-90da-f0afcb910c52.png)

Which results in the database storing this:
![image](https://user-images.githubusercontent.com/11945337/74346201-1f67e080-4da7-11ea-80dd-211bcc9d023c.png)

**Tasks:**
- [ ] Front end:  Don't send viewpoint/empty string screenshot when it's N/A
- [ ] Back end: If the front end sends this, don't store it. (as we don't always have control of the api requests incoming.. it's good to add this in even if former is done)
- [ ] This also applies to the issue's viewpoint, it's storing `""` as screenshot. We probably need a viewpoint entry as we assume viewpoint[0] to be issue's... but we can omit the screenshot for sure.

**Comment by carmenfan** [comment]
N/A with V5
