### ISSUE TITLE
v4.3.3 bug list

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1915]
### Bugs
- [x] [No tooltip information for preset views](https://github.com/3drepo/3drepo.io/issues/1915#issuecomment-591352270)
- [x] [GIS Maps set up comes up with an error message](https://github.com/3drepo/3drepo.io/issues/1915#issuecomment-591355269)
- [x] [Clipping plane generated from clicking an issue isn't updating the clip tool on tool bar](https://github.com/3drepo/3drepo.io/issues/1915#issuecomment-591357363)
- [x] [(Decimal) on latitude but not longitude on GIS tab](https://github.com/3drepo/3drepo.io/issues/1915#issuecomment-591359312)
- [x] [GIS visibility doesn't reset when you change model](https://github.com/3drepo/3drepo.io/issues/1915#issuecomment-591360592)
- [x] Remove architectural rendering from visual settings
- [x] Risk report is broken (#1919)

**Comment by BDavydov** [comment]
### Description
Preset views do not contain tooltip info when you hover over it with a mouse pointer
Ideally, it should indicate what view it is ie. Top, Bottom, Left, Right, Front & Back.

### Steps to replicate
- Open any model in 3D Repo
- Open Views Card
- Hover over preset view (any)

### Pictures/ Gifs of the error
![Preset Views](https://user-images.githubusercontent.com/19904513/75335866-16d0d900-5882-11ea-82ed-cc84308dee0d.jpg)

**Comment by BDavydov** [comment]
### Description
GIS Maps come up with an error message when complete initial set up.

### Steps to replicate
- Open any model in 3D Repo
- Open GIS Card
- Provide coordinates info
- Save coordinates
- Activate map by clicking in the eye icon

### Pictures/ Gifs of the error
![GIS Maps](https://user-images.githubusercontent.com/19904513/75336393-fbb29900-5882-11ea-80a4-83e7697f4018.gif)

**Comment by carmenfan** [comment]
Clipping plane generated from clicking an issue isn't updating the clip tool on tool bar:
![image](https://user-images.githubusercontent.com/11945337/75336771-9ca15400-5883-11ea-9710-37fd83a7ea37.png)


This should say 6 and clicking on it should just enable the tool instead of having to choose and reset the clipping planes.

**Comment by carmenfan** [comment]
`(Decimal)` on latitude but not longitude on GIS tab

![image](https://user-images.githubusercontent.com/11945337/75337091-3cf77880-5884-11ea-83a3-3acddaf7c4d8.png)

**Comment by carmenfan** [comment]
GIS visibility doesn't reset when you change model

- Open GIS and turn on maps on a model
- go to another model, GIS tab shows maps is enabled still

![image](https://user-images.githubusercontent.com/11945337/75337315-a8414a80-5884-11ea-9c62-3d21f77f17f4.png)
