### ISSUE TITLE
Merging the static viewer and the viewer service

### ISSUE THREAD

**Issue by m1chalkubiak** [3drepo/3drepo.io#1916]
### Description
Getting rid of currently separated into two large classes viewers, which largely overlap each other, by merging them into one.

### Goals
- [ ] Viewer should still work properly, in the same way that it was before merging
- [x]  ~~Render viewer's canvas only on the viewer page (if it will be possible)~~

### Tasks
- [x] Rid of two large viewer classes
   - [x] Separate the methods responsible only for controlling Unity to another class (in the future it probably would be possible to get rid of this class)
- [x] Remove all duplicate methods
- [x] Re-organize code by grouping methods by features
- [x] Remove all unnecessary (this will clear up during debugging and testing) classes added into the global scope.
   - [x]  ~~UnityUtils~~
   - [x] Pin
      - [x] Additionally remove old duplicated Pin class
   - [x] Viewer
      - [x] Remove old Viewers
- [x] ~~Move viewer canvas to viewer page route~~
   - [x] ~~Handle of properly destroying of Viewer class instance when leaving the route~~.

**Comment by carmenfan** [comment]
@m1chalkubiak 

>  Render viewer's canvas only on the viewer page (if it will be possible)

I don't think we want to do this. The problem is the viewer takes a long time to instantiate, so we kind of want it to be hanging around if the user has initialised it before. So unless you can not render the canvas and preserve the game, I think it's a no go.

>  Remove all unnecessary (this will clear up during debugging and testing) classes added into the global scope.
 UnityUtils

We still need this in the global scope for external applications

**Comment by m1chalkubiak** [comment]
@carmenfan 
> > Render viewer's canvas only on the viewer page (if it will be possible)
> 
> I don't think we want to do this. The problem is the viewer takes a long time to instantiate, so we kind of want it to be hanging around if the user has initialised it before. So unless you can not render the canvas and preserve the game, I think it's a no go.

I didn't test it for now, but I can imagine that if this will significantly extend waiting time for the user, then we shouldn't do it at all. This was something that I wanted to test at the very end of this refactor.

> > Remove all unnecessary (this will clear up during debugging and testing) classes added into the global scope.
> > UnityUtils
> 
> We still need this in the global scope for external applications

I suspected it might be this way, in that case, I will stop at the current point - so only removing the Viewer and the Pin class from the global scope.

Currently, I am in the process of checking all existing functionalities and comparing them with the previous version. It is quite time-consuming, but it seems to me that I'm approaching the end.
I believe that by Wednesday I should have this branch in a condition suitable for testing.

**Comment by m1chalkubiak** [comment]
Hi @carmenfan 
I tested all the cases that I am aware of and it seems to me that the current version is suitable for testing now. I'm sure, there are some functionalities which I forgot (or I'm just not aware of). That's why I would like to ask You to test this refactor and if you notice any inconsistencies, please let me know.

**Comment by carmenfan** [comment]
@m1chalkubiak  can you make a PR first, it'll probably make sense to take a look at what you've changed and test it at the same time

**Comment by m1chalkubiak** [comment]
Of course @carmenfan , I just created PR and fixed all conflicts:
https://github.com/3drepo/3drepo.io/pull/1925
