### ISSUE TITLE
stop storing screenshots in base64 within a bson in the database

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1917]
We're currently storing screenshots in issues/issue comments embedded into the bson object as base64 binary.

As bson has a size limit of 16MB, this will become problematic if users starts uploading HQ images or if the amount of comments within the issue gets very long.

We should store them externally via whatever file storage the server is configured to connect to (fs, s3, gridfs etc?)

**Comment by sanmont3drepo** [comment]
### Tasks
- [ ] When creating an issue the viewpoints screenshots should be saved in a external ref
- [ ] When creating a risk the viewpoints screenshots should be saved in a external ref
- [ ] When showing the screenshot it should access the external ref in the new ones and the old ones should work as they do now
- [ ] When deleting a screenshot it should delete the new ones using the external ref and the old ones should work as they do now 
- [ ] Check what happens on update
