### ISSUE TITLE
4.5.1 bug list

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1966]
### Bugs
- [x] [Background colour for comments is inconsistent](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-610336958)
- [x] [Pins missing if you go into the model after looking at kanban](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-610874884)
- [x] [Lines should only appear below the name if it's in editing mode](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-610879496)
- [x] [The save/cancel button should appear as soon as it enters edit mode](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-610880013)
- [x] [CoordView is showing even though it's suppose to be disabled](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-610889735)
- [x] [Existing text not clearing in edit mode](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-610894832)
- [x] [Measure colour selector missing previously used options.](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-610907819)
- [x] [X Y Z should align](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-610949811)
- [x] [Polygon area tool not clearing](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-611009953)
- [x] [Measurements don't always match](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-611016762)
- [x] [We can no longer save views with the default name](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-611641597)
- [x] [Limit Measurement name to 15 characters per line](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613301405)
- [x] [Rearrange selected total](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613309131)
- [x] [Save the new name when you hit Enter](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613320259)
- [x] [UI oddities when creating issues/risks](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613325683)
- [x] [Issue Title and Description are not operating properly](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613330066)
- [x] [Length Measurements are showing XZY values instead of XYZ](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613334619)
- [x] [Change teamspace setting update to a patch instead of put](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613476597)
- [x] [We're still using the RISK_CATEOGORIES constant in places](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613517405)
- [x] [Remove selectTopicType and its usage fro model selection](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613531383)
- [x] [Measuring large areas gives an error](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613654863)
- [x] [Objects ghost effect](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613941613)
- [x] [Action + Button does not work & Compare card does not load](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614005839)
- [x] [Updating risk category is updating everything else](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614075017)
- [x] [Measurement Banners floating in random locations](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614256502)
- [x] [Deleting incomplete custom surface area measurement gives an error message](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614509707)
- [x] [Point measurement stays active after deactivating it. Can't spin around the model when measuring point locations](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614569621)
- [x] [No tooltip description for measurement types](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614571892)
- [x] [Model Tree element name spacing](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614628731)
- [x] [Groups Colour override is still active when you open the same model again](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614638533)
- [x] [3D Diff the same model revision gives you a Red Model](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614644030)
- [x] [3D Diff shows you unselected models](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614653696)
- [x] [3D Diff / Instant Clash deactivates when you keep them running but close and open the Compare Card](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614658325)
- [x] [Smart Groups background isn't stretched all the way to the bottom](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614722927)
- [x] [Closed Issue reappears in the list, but remains as closed](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614815344)
- [x] [Images uploaded via Kanban board change camera position to far far far away from the model](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614872634)
- [x] [Measurement Tool shows XZY. must be as **XYZ**](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614877117)
- [x] [Point measurement feature becomes inactive when you click in space and not on the model mesh](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-614881334)

**Comment by carmenfan** [comment]
**Background colour for comments is inconsistent**
This area should be grey:
![image](https://user-images.githubusercontent.com/11945337/78664719-7c29d800-78cc-11ea-8aae-047f2b862468.png)
There is a white strip if there is a comment:
![image](https://user-images.githubusercontent.com/11945337/78664782-9b286a00-78cc-11ea-8687-eab7671f9442.png)
This area should be grey:
![image](https://user-images.githubusercontent.com/11945337/78664826-b1362a80-78cc-11ea-959f-812c11d5e134.png)


@m1chalkubiak  can you take a look at this? I think this is caused by this fix: https://github.com/3drepo/3drepo.io/issues/1938#issuecomment-601683334

**Comment by m1chalkubiak** [comment]
Hi @carmenfan 

> @m1chalkubiak can you take a look at this? I think this is caused by this fix: #1938 (comment)

You are right I'm trying to figure out it right now.

**Comment by carmenfan** [comment]
**Pins missing if you go into the model after looking at kanban**
- Go to the kanban board and view a model (let's call this `model A`)
- Exit kanban board and view `model A` in the viewer - the issue pins are missing.

**Comment by carmenfan** [comment]
**Lines should only appear below the name if it's in editing mode**

![image](https://user-images.githubusercontent.com/11945337/78773940-d9389300-798b-11ea-9386-36b73e02b084.png)

**Comment by carmenfan** [comment]
**The save/cancel button should appear as soon as it enters edit mode**
They currently only appears when the text has changed
![1](https://user-images.githubusercontent.com/11945337/78774111-156bf380-798c-11ea-9959-1a5ef900fcf6.gif)

**Comment by carmenfan** [comment]
**CoordView is showing even though it's suppose to be disabled**
It needs to be turned on unity and rebuild (CF: I'll do this)

**Comment by anorrie** [comment]
**When editing measurement name the existing text should be automatically cleared when entering edit mode**

**Comment by anorrie** [comment]
**Measure colour selector missing previously used options.** 
In measure card the colour selector should have previously used options like in the colour selector for Jobs. This only needs to be remembered in the session.

**Comment by carmenfan** [comment]
**X Y Z should align**
the X Y Z labels should algin, but the numbers should stay where they are. (i.e. the units should also align. In other words you can think of this as 2 columns, the labels aligns vertically, and the data aligns to the right.
![image](https://user-images.githubusercontent.com/11945337/78787657-98984400-79a2-11ea-93cb-ae654b7b0d92.png)

**Comment by m1chalkubiak** [comment]
Hi @carmenfan 
> Lines should only appear below the name if it's in editing mode

Just to be clear we changed this behavior in purpose in ISSUE 1847 - SafetiBase v3
https://github.com/3drepo/3drepo.io/issues/1847#issuecomment-581864641
And in my comment above the linked one, I was asking should we change it to all places where this component is used. I understand, that now we would like this component to display differently in some places?

> The save/cancel button should appear as soon as it enters edit mode
They currently only appears when the text has changed

> Existing text not clearing in edit mode
When editing measurement name the existing text should be automatically cleared when entering edit mode

For both of the above, I would like to ask If this change should be made all around application, so in all places where this component is used?

**Comment by carmenfan** [comment]
> Just to be clear we changed this behavior in purpose in ISSUE 1847 - SafetiBase v3
#1847 (comment)
And in my comment above the linked one, I was asking should we change it to all places where this component is used. I understand, that now we would like this component to display differently in some places?

Ah yes sorry, I didn't realise we'd reuse this component for the measuring labels, Measuring labels shouldn't have a line below it, but issue/risks properties should. I hope this makes sense!

> For both of the above, I would like to ask If this change should be made all around application, so in all places where this component is used?

Yes (as far as I'm aware, if there's a case where it seems strange to do, please let me know and we should review).  But clearing the text, it would be ideal if we can set the existing name as default text, so it still displays but you just right over it, like we have with the description field with the `(no description)` here:
![1](https://user-images.githubusercontent.com/11945337/78791660-13b02900-79a8-11ea-8a94-d6df1488cd77.gif)

**Comment by m1chalkubiak** [comment]
> > Just to be clear we changed this behavior in purpose in ISSUE 1847 - SafetiBase v3
> > #1847 (comment)
> > And in my comment above the linked one, I was asking should we change it to all places where this component is used. I understand, that now we would like this component to display differently in some places?
> 
> Ah yes sorry, I didn't realise we'd reuse this component for the measuring labels, Measuring labels shouldn't have a line below it, but issue/risks properties should. I hope this makes sense!

No worries, from what I have checked this component is also used in edit view on group panel, should it have a line there or not?

> > For both of the above, I would like to ask If this change should be made all around application, so in all places where this component is used?
> 
> Yes (as far as I'm aware, if there's a case where it seems strange to do, please let me know and we should review). But instead of clearing the text, it would be ideal if we can set the existing name as default text, so it still displays but you just right over it, like we have with the description field with the `(no description)` here:
> ![1](https://user-images.githubusercontent.com/11945337/78791660-13b02900-79a8-11ea-8a94-d6df1488cd77.gif)

I have big doubts about this change. The main threat I see is the fact that we will not be able to edit previously entered text. It seems to me that this is not experience witch users would expect. Mostly I'm thinking about long descriptions in risk panel.
However, for measurements panel where we have some "random" names, it makes sense in my opinion.

**Comment by carmenfan** [comment]
> No worries, from what I have checked this component is also used in edit view on group panel, should it have a line there or not?

If you mean the description part yes, that should have a line underneath

> I have big doubts about this change. The main threat I see is the fact that we will not be able to edit previously entered text. It seems to me that this is not experience witch users would expect. Mostly I'm thinking about long descriptions in risk panel.
However, for measurements panel where we have some "random" names, it makes sense in my opinion.

@m1chalkubiak 
Alternatively, can we start the editing mode with the text highlighted? then the user can just type to overwrite it, or click where appropriate to edit?

**Comment by m1chalkubiak** [comment]
@carmenfan 
> If you mean the description part yes, that should have a line underneath

Yes, its used in for description field.

> @m1chalkubiak
> Alternatively, can we start the editing mode with the text highlighted? then the user can just type to overwrite it, or click where appropriate to edit?

Yes, in my opinion, it sounds like a good idea. I will add this behavior, then we could check if it works as expected.

**Comment by anorrie** [comment]
**Polygon Area Tool Not Clearing** 
If you start an area measure and do not commit, after leaving the tool and re-entering the old unfinished shape will appear. 
Steps to recreate. 
1) Start polygon area tool 
2) click a number of points 
3) DO NOT double click to commit 
4) exit the polygon area tool 
5) shape will disappear 
6) re-enter tool 
7) start drawing 
8) old unfinished shape will appear

**Comment by m1chalkubiak** [comment]
> **Polygon Area Tool Not Clearing**
> If you start an area measure and do not commit, after leaving the tool and re-entering the old unfinished shape will appear.

@carmenfan I think that we would need to have some additional method to tell Unity (from frontend) that we cancel creating of the area measurement

**Comment by carmenfan** [comment]
> > **Polygon Area Tool Not Clearing**
> > If you start an area measure and do not commit, after leaving the tool and re-entering the old unfinished shape will appear.
> 
> @carmenfan I think that we would need to have some additional method to tell Unity (from frontend) that we cancel creating of the area measurement

don't worry about that one, i'll just fix it in unity. it should clear the cache when the tool changes/turned off

**Comment by anorrie** [comment]
**Measurements don't always match**
Occasionally, measurement readings on the label and in the card do not match...

![measure](https://user-images.githubusercontent.com/41000373/78800728-ac987180-79b3-11ea-9d48-4e3968e20d92.PNG)

**Comment by carmenfan** [comment]
> **Measurements don't always match**
> Occasionally, measurement readings on the label and in the card do not match...
> 
> ![measure](https://user-images.githubusercontent.com/41000373/78800728-ac987180-79b3-11ea-9d48-4e3968e20d92.PNG)

@m1chalkubiak  i think this is a rounding method difference, I will fix this as well in Unity (so it sends rounded numbers back to the front end)

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak i think this is a rounding method difference, I will fix this as well in Unity (so it sends rounded numbers back to the front end)

@carmenfan I'm not sure if this will cover all the cases, rounding is also done when user change the units from panel menu, then we don't get any update from Unity, so on the frontend I need to re-calcualate values manually.

Therefore, I believe we should be consistent on both sides with rounding numbers in the same way.
However, if it's only happening in the case of "m" units, I probably know what can cause wrong rounding.

@anorrie I would be grateful if You could repeat this measurement with the newest version of the code, as I wasn't ably to find myself a case were rounding was done incorrectly.

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak
> Alternatively, can we start the editing mode with the text highlighted? then the user can just type to overwrite it, or click where appropriate to edit?

@carmenfan I just pushed change of this behavior, so now in all places where we are using this component, it will be the same. Just for reminding those places are: Risk/Issues descriptions, Group descriptions and measurements names.

**Comment by carmenfan** [comment]
> Therefore, I believe we should be consistent on both sides with rounding numbers in the same way.
> However, if it's only happening in the case of "m" units, I probably know what can cause wrong rounding.

You're right. But we'll still tweak the numbers in unity first to the nearest mm, as that's the level of accuracy we support. so rounding should never be a problem for mm units

**Comment by carmenfan** [comment]
> > Therefore, I believe we should be consistent on both sides with rounding numbers in the same way.
> > However, if it's only happening in the case of "m" units, I probably know what can cause wrong rounding.
> 
> You're right. But we'll still tweak the numbers in unity first to the nearest mm, as that's the level of accuracy we support. so rounding should never be a problem for mm units

@m1chalkubiak  just had a look, seems like it's already is doing this by default. So no changes needed on the unity side

**Comment by carmenfan** [comment]
We can no longer save views with the default name

- add a view in the views card
- hit save without changing the name
- instead of saving it with the default name (e.g. View 3), it tries to save it without a name and thus the server is returning an error.

![1](https://user-images.githubusercontent.com/11945337/78921457-d70a2d80-7a8c-11ea-80d2-1bcde0f7e9ae.gif)


We should also change the backend so it returns invalid arguments instead of a 500.... (I'll change the backend)

**Comment by m1chalkubiak** [comment]
@carmenfan 
I manage to solve issue with missing pins after visiting kanban board which took me most of the day yesterday to debug this.

I was also re-thinking case with saving default values and as a very quick fix I added condition that if the value didn't change we just exiting the edit mode (exactly like pressing the cancel button). 
Because, if we haven't made any changes, saving the same value again probably isn't needed at all.
I hope this makes sense.

**Comment by BDavydov** [comment]
**Limit the measurement name to about 15 characters per line**

When you create a name and the measurement distance is long, both can get too close together.
Can we drop to the next line after let's say 15 characters? This way we would avoid the name getting too close in line with the measurement.

![image](https://user-images.githubusercontent.com/19904513/79202795-08d71780-7e32-11ea-98b5-42927b72af59.png)

**Comment by BDavydov** [comment]
**Could we ditch the current Total Length arrangement?**

Shift 'Selected total' to the right and make use of the white space to the right of the measurement.

![Measurement Length Total](https://user-images.githubusercontent.com/19904513/79203888-98c99100-7e33-11ea-89a0-aa80111c5de6.gif)
![Total Length](https://user-images.githubusercontent.com/19904513/79204426-72582580-7e34-11ea-8948-24a646739666.jpg)
![Total Length collapsed](https://user-images.githubusercontent.com/19904513/79204438-7421e900-7e34-11ea-87b4-99a8cdab4254.jpg)

**Comment by carmenfan** [comment]
> I was also re-thinking case with saving default values and as a very quick fix I added condition that if the value didn't change we just exiting the edit mode (exactly like pressing the cancel button).
> Because, if we haven't made any changes, saving the same value again probably isn't needed at all.
> I hope this makes sense.

@m1chalkubiak if you're talking about the viewpoint saving bug mentioned here then it won't work, as it hasn't been saved yet.

**Comment by BDavydov** [comment]
**Save the name when you hit Enter button**

Currently, you have to click on the save icon in order to save the new name of any measurement.
Can we do it similarly to views, where you can write the name and hit Enter to submit it? 
![image](https://user-images.githubusercontent.com/19904513/79206743-b13baa80-7e37-11ea-9ec8-e11e509ec409.png)

**Comment by BDavydov** [comment]
**Description**
SafetiBase Comment Option buttons show up and remain there until you save the issue. I have to manually delete Untitled Issue in the SafetiBase Issue name. Could we make it behave in similar way as Issues do?

**Steps to replicate**
- Open any model
- Open SafetiBase Card
- Create a new Issue
- The description line will contain delete and save icons
- Clear all button does not respond
- Once you've saved the issue and open it again Description is back to normal

![image](https://user-images.githubusercontent.com/19904513/79207245-5d7d9100-7e38-11ea-8dc0-365c6a05f6f0.png)
![image](https://user-images.githubusercontent.com/19904513/79207767-0a580e00-7e39-11ea-890b-dbb0a219954b.png)

**Comment by BDavydov** [comment]
**Description**

Similarly to SafetiBase when I create a new Issue I have to manually delete the Untitled Issue and Description contains 'Clear' & 'Delete' options which are inactive. Create a new issue and open it again to edit the Description field. Clear all button does not work.

**Steps to Replicate:**
- Open any model
- Open the Issue Card and create a new Issue
- Manually delete the Issue title in order to write a new one 
- Description contains options icons but they do not respond on click
- Open the newly created issue to edit the description field
- Click on the description edit button
- Description clear all button X does not work
![image](https://user-images.githubusercontent.com/19904513/79208799-74bd7e00-7e3a-11ea-8303-6491f604caa1.png)

**Comment by BDavydov** [comment]
Can we show **XYZ** for measurements as per settings? Currently, it is showing **X Z Y**

![image](https://user-images.githubusercontent.com/19904513/79209689-ab47c880-7e3b-11ea-8878-6bbfc099f5c7.png)
![image](https://user-images.githubusercontent.com/19904513/79209700-aedb4f80-7e3b-11ea-9884-de3b1bfdbca9.png)

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak if you're talking about the viewpoint saving bug mentioned here then it won't work, as it hasn't been saved yet.

Sorry @carmenfan mistakenly assumed that they were using the same textfield component that was changed, but it appears that its not the case. So, I wrote additional logic that sends default name if none were added during creating of new viewpoint. However, I wasn't able to find a version of an application on which it would work differently. I back to version 4.4.1 from over a month ago and it was acting the same.

**Comment by carmenfan** [comment]
> > @m1chalkubiak if you're talking about the viewpoint saving bug mentioned here then it won't work, as it hasn't been saved yet.
> 
> Sorry @carmenfan mistakenly assumed that they were using the same textfield component that was changed, but it appears that its not the case. So, I wrote additional logic that sends default name if none were added during creating of new viewpoint. However, I wasn't able to find a version of an application on which it would work differently. I back to version 4.4.1 from over a month ago and it was acting the same.

Yes I happened to test that since I was looking around simlar looking components to see if they work. Not sure when it started breaking!

Just tried, it working well, thanks!


I noticed you checked off https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613325683 but it doesn't automatically highlight the title when you go into new issue/risk. Can we change that as well? 
![image](https://user-images.githubusercontent.com/11945337/79229088-60897900-7e5a-11ea-86ae-d3b17ad4a255.png)

**Comment by m1chalkubiak** [comment]
> I noticed you checked off [#1966 (comment)](https://github.com/3drepo/3drepo.io/issues/1966#issuecomment-613325683) but it doesn't automatically highlight the title when you go into new issue/risk. Can we change that as well?

Ohh I see, it was about the second part - `Edit buttons shouldn't appear when the user is creating a new issue/risk` I will check right away if can we automatically highlight the default title, as You suggested.

**Comment by carmenfan** [comment]
**Change teamspace setting update to a patch instead of put**

At the moment we expect a put http request for teamspace setting update when it should be a patch

(I'll work on this)

**Comment by carmenfan** [comment]
We're still using the RISK_CATEOGORIES constant in places

for e.g. Kanban board filter
![image](https://user-images.githubusercontent.com/11945337/79244241-92a4d600-7e6e-11ea-889c-62d280c0dd83.png)

RISK_CATEOGORIES  should be completely gone and replaced with the dynamic one from API

**Comment by carmenfan** [comment]
@m1chalkubiak we still have a selectTopicType in the model selector and it seems like the kanban board is using this. This should be wired to the selector from teamspace right? We need to remove that one and make sure everything comes from the teamspace selector.

I'm also seeing a mismatch between the topic type on kanban filter vs the topic types in teamspace setting. (looks like it's a default list)

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak we still have a selectTopicType in the model selector and it seems like the kanban board is using this. This should be wired to the selector from teamspace right? We need to remove that one and make sure everything comes from the teamspace selector.
> 
> I'm also seeing a mismatch between the topic type on kanban filter vs the topic types in teamspace setting. (looks like it's a default list)

@carmenfan You're right, the board has been omitted from this refactor. So from tomorrow morning, I will start looking at what exactly needs to be changed there to work with dynamic data from API.

**Comment by BDavydov** [comment]
**Description**
Custom area measurement gives an error message when surface is large

**Steps to replicate:**

- Open this [model](dev.3drepo.io/viewer/Bogdan_D/7582583e-52d5-4d76-a693-f4b8bb9da0e9) in 3D Repo
- Open measurement Card
- Activate surface area measurement
- Click on some of the large roof slabs
- Calculation starts then error message appears

![image](https://user-images.githubusercontent.com/19904513/79268832-50da5680-7e93-11ea-9944-1eadcb1962db.png)

**Comment by BDavydov** [comment]
**Description**
Selected objects get a ghost effect when rotating or panning around the model. This is not the issue for the same model on Prod.

Steps to Replicate:
- Open a big federation on dev
- Select any model element
- Start rotating or panning around

**Currently on DEV:**
![Object Ghost Effect](https://user-images.githubusercontent.com/19904513/79324510-a51f1e00-7f07-11ea-9495-454dd69c257f.gif)

**Currently on PROD:**
![Object No Ghost Effect](https://user-images.githubusercontent.com/19904513/79324533-ab14ff00-7f07-11ea-97d8-ea9cdd19f342.gif)

**Comment by BDavydov** [comment]
**Description**
Action Buttons don't work for any of the features in the model viewer (Issues, SafetiBase, Groups & Views) & Compare Card does not load

**Steps to replicate:**
- Open the [Residential Block Federation](https://dev.3drepo.io/viewer/Bogdan_D/0c1aa250-7ef9-11ea-9a0c-675b6f4f3816)
- Open Issue/SafetiBase/Groups or Views Card
- Click on the Green + Button
- Nothing Happens

![Action Button not responding](https://user-images.githubusercontent.com/19904513/79336791-39937b80-7f1c-11ea-8113-f782bf53a6e0.gif)

**Comment by m1chalkubiak** [comment]
> **Description**
> Action Buttons don't work for any of the features in the model viewer (Issues, SafetiBase, Groups & Views) & Compare Card does not load

@BDavydov  Quick guess, can You check what is visible in Teamspace Settings page of this model? Unfortunately, I don't have access to this model by my account.

**Comment by carmenfan** [comment]
> > **Description**
> > Action Buttons don't work for any of the features in the model viewer (Issues, SafetiBase, Groups & Views) & Compare Card does not load
> 
> @BDavydov Quick guess, can You check what is visible in Teamspace Settings page of this model? Unfortunately, I don't have access to this model by my account.

@m1chalkubiak  I have acces, I'll take a look first

**Comment by carmenfan** [comment]
> > > **Description**
> > > Action Buttons don't work for any of the features in the model viewer (Issues, SafetiBase, Groups & Views) & Compare Card does not load
> > 
> > 
> > @BDavydov Quick guess, can You check what is visible in Teamspace Settings page of this model? Unfortunately, I don't have access to this model by my account.
> 
> @m1chalkubiak I have acces, I'll take a look first

@m1chalkubiak 
in Issues saga we're still using the model selector for topic types, as this is a new model the model API doesn't return the topic type list anymore (we haven't ran the script to remove the old ones yet, but the new ones doesn't generate anymore). So what you're doing right now should fix this. Though I don't think we can assume topic_type must have a length of at least 1, so i'm going to add in some checks.

Compare card problem is a separate problem, I haven't gotten to the bottom of it yet but it looks like it's a backend problem.

**Comment by carmenfan** [comment]
**Updating risk category is updating everything else**

1. create a risk
2. change the risk category from blank to something
3. you can see the comment log is populated with a lot of actoins...

![1](https://user-images.githubusercontent.com/11945337/79349478-28ec0100-7f2e-11ea-938a-b21c88904b6e.gif)
Looks like this is a back end bug as the front end is only sending 1 value

**Comment by sanmont3drepo** [comment]
> **Updating risk category is updating everything else**
> 
> 1. create a risk
> 2. change the risk category from blank to something
> 3. you can see the comment log is populated with a lot of actoins...
> 
> ![1](https://user-images.githubusercontent.com/11945337/79349478-28ec0100-7f2e-11ea-938a-b21c88904b6e.gif)
> Looks like this is a back end bug as the front end is only sending 1 value

done (it was a problem in the frontend when evaluating the values that changed in the form)

**Comment by BDavydov** [comment]
**Description** 
Measurement banners appear to be floating randomly in the model as you move to other model areas. 
There is no measurement taken, but the banner appears there.

**Steps to replicate**
- Open any model in 3D Repo
- Start measuring distance and areas in your model
- Create a few measurements min 6/7 in different locations
- Start navigation to other model areas (Preset Views) or pan around

![Measurement Banner 1](https://user-images.githubusercontent.com/19904513/79383643-6caa2f00-7f5d-11ea-8eb9-6fc96bf03987.gif)

![Measurement Banner 2](https://user-images.githubusercontent.com/19904513/79383865-d4607a00-7f5d-11ea-87b5-6b976329c003.gif)

**Comment by BDavydov** [comment]
**Description**
Error message comes up when you are deleting the incomplete custom surface area measurement.

**Steps to replicate:**
- Load any model in 3D Repo
- Open the Measurement Card
- Start measuring the custom surface area
- Do not finish measuring yet but click on the measurement card
- Open the Measurement card again
- Incomplete surface area measurement banner appears
- Delete this measurement by clicking X on the banner
- Error message appears


![image](https://user-images.githubusercontent.com/19904513/79435086-24275b80-7fc7-11ea-8278-4e3e998b7c14.png)

**Comment by BDavydov** [comment]
**Description**
Point Measurement option does not allow you to spin around without placing a new pin. 
When you click on the point measurement place a few pins. Click on the point icon to deactivate it, When you click on the model another point icon appears even though the feature is no longer active.

**Steps to replicate**
- Open any 3D Model
- Open Measurement Card
- Activate Point measurement
- Place a few measurement points
- Try spinning around the model (points get added)
- Click on the point measurement icon to deactivate it
- Click anywhere on the model and point icon appears again, even though it's no longer active

![Point Measurement](https://user-images.githubusercontent.com/19904513/79447088-3b6e4500-7fd7-11ea-8538-882829770f90.gif)

**Comment by BDavydov** [comment]
**Description** 
No tooltip description for measurement types. Should be like preset views on hover and include the following: Point, Point to Point, Ray cast, Minimum Distance, Surface Area, Custom Area

![image](https://user-images.githubusercontent.com/19904513/79447399-b59ec980-7fd7-11ea-898c-5b92a58177d6.png)

**Comment by BDavydov** [comment]
Model Tree contains unnecessary spacing between the expand icon and item name. Shift the object names closed to the +/- button as per prod version.

**Dev**
![image](https://user-images.githubusercontent.com/19904513/79457428-1e8e3d80-7fe8-11ea-81e5-5c9b4447010a.png)

**Prod**
![image](https://user-images.githubusercontent.com/19904513/79457460-29e16900-7fe8-11ea-9794-ee5bc2b6ed76.png)

**Comment by BDavydov** [comment]
**Description**
Group colour override icon remains active. When you apply colour override to a group and go back to teamspaces without deactivating it is still active when you open the same model again. Sometimes Group colour shows up, sometimes it doesn't. Group colour override button remains active(as in applied) even though there is no colour override applied atm.

**Steps to replicate**
- Open any model/federation in 3D Repo
- Open Groups Card
- Create a group with any model element you like
- Save the new group and go back to the groups' card
- Click on the newly created group and apply the colour override
- Click on the (Back to teamspaces) button
- Open the same model again
- Open groups card
- Click on the group you have created recently
- Notice that colour override button is still active

**Step 1**
![Groups colour override 1](https://user-images.githubusercontent.com/19904513/79458803-42528300-7fea-11ea-959a-73cb02bda10a.gif)

**Step 2**
![Groups colour override 2](https://user-images.githubusercontent.com/19904513/79459239-e6d4c500-7fea-11ea-9c26-c6e480b49211.gif)

**Comment by BDavydov** [comment]
**Description**
When run 3D Diff between the same model revisions it highlights everything in Red. It should be all great as per no Changes schema.

![image](https://user-images.githubusercontent.com/19904513/79460147-4f707180-7fec-11ea-9d1e-b47b7422db17.png)

**Comment by BDavydov** [comment]
**Description**
3D Diff shows another model that wasn't selected from the list of models.
I am running diff on Structure, but Furniture model shows up all green.

**Steps to recreate**
- Open dev.3drepo.io
- Open [this model](https://dev.3drepo.io/viewer/Bogdan_D/e776a090-7fb9-11ea-bf68-2139b927bbac)
- Open Compare Card
- Select 3D Diff
- Choose any model and run the comparison

![3D Diff 2 Models](https://user-images.githubusercontent.com/19904513/79461909-b68f2580-7fee-11ea-90f3-f05578c12183.gif)

**Comment by BDavydov** [comment]
**Description**
When you activate Instant Clash or 3D Diff and close the compare card but keep the function running, it deactivates as soon as you open the Compare card again.

**Steps to replicate:**
- Open any Federation in 3D Repo
- Open compare card and select any models you would like to 3D Diff or InstantClash
- Activate the Diff or Instant Clash feature
- Close the Compare Card, but keep the features running
- Open the Compare Card again. 
- Comparison checks deactivate themselves, without any user input

![Instant Clash Deactivates](https://user-images.githubusercontent.com/19904513/79462727-d115ce80-7fef-11ea-899f-a06abc2d4e43.gif)

**Comment by carmenfan** [comment]
@BDavydov  this sounds like @1958 with @sanmont3drepo  is looking at?

**Comment by BDavydov** [comment]
@carmenfan Yes. I have shared the information with Santiago. Instant Clash and 3D Diff seems to throw additional models in comparison checks.

**Comment by carmenfan** [comment]
ok. @sanmont3drepo  please either fix it here or reopen #1958 remove it from the list from this. Whichever is easier.

There's no point logging the same bug twice

**Comment by BDavydov** [comment]
Smart Groups background (grey) colour doesn't go all the way to the bottom of the card.

![image](https://user-images.githubusercontent.com/19904513/79474998-083fac00-7fff-11ea-9c97-4608c083e048.png)

**Comment by BDavydov** [comment]
**Description**
When you reopen a previously closed issue it reappears in the list. However, if you close an issue and someone reopens it before you have refreshed the web page the issue reappears in the list but says 'Issue Closed'. 

**Steps to recreate:**
- Open any model in 3D Repo using account A
- Open the Issues Card with several issues and keep it active
- Using Another account (Account B) open the same issues list in another web browser
- Using Account B close some of the issues
- Account A will notice the change as 'This issue is now closed' 
- Using Account B reopen the issue you have recently closed
- Account A will notice it reappearing in the list, but it still says 'This issue is now closed'

![Closed Issue Bug](https://user-images.githubusercontent.com/19904513/79491658-b145d100-8016-11ea-823b-460f70adbd24.gif)

**Comment by BDavydov** [comment]
**Description**
I have open an issue in Kanban Board and uploaded an image as a comment. Later I have loaded the 3D Model and open the same issue in the viewer. When I click on the comment images created in the viewer I simply change my camera position. However, when I click on the image uploaded via a Kanban board, my camera changes position to somewhere far far far far far far far away! Extent button shows me the model.

Steps to recreate:
- Open [THIS MODEL](https://dev.3drepo.io/viewer/Bogdan_D/e776a090-7fb9-11ea-bf68-2139b927bbac)
- Open issues card and click on the **6 Bench Height** Issue
- Open it and scroll down to the comments
- Click on the first image with a comment, camera position changes
- Then click on the later image comment
- Uploaded comment image expands
- When you close the 'Screenshot' window you notice the Grey Screen
- You are far away from your model
- Click on the extent button and you are back to where you belong! 

![Uploaded Comment Issue](https://user-images.githubusercontent.com/19904513/79502481-93349c80-8027-11ea-8f4c-3a52bb2b31d0.gif)

**Comment by BDavydov** [comment]
**Description**
When you use the point measurement tool it displays incorrect XYZ coordinates. 
It should be *XYZ*, by we show it as *XZY*

**What you see in 3D Repo**
![image](https://user-images.githubusercontent.com/19904513/79503160-98deb200-8028-11ea-86bf-5ffad489a9c1.png)

**Alternative 3D Modelling/Review Tools**
![image](https://user-images.githubusercontent.com/19904513/79503278-c62b6000-8028-11ea-959d-54da26c26c2f.png)
![image](https://user-images.githubusercontent.com/19904513/79503413-04c11a80-8029-11ea-914c-f2849db5b9d9.png)

**Comment by BDavydov** [comment]
**Description**
When you activate the point measurement feature and click on the mesh you get a point icon. If you click somewhere in model space that is not a mesh, it automatically deactivates itself. It should remain active like all the other measurement features when you click in space and not the mesh.

**Note**
Placing an issue pin keeps the function active even if you click somewhere in space and then on the model mesh again.
