### ISSUE TITLE
4.5.2 bugs list

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#1988]
### Bugs
- [x] [Attaching image comments to Risks on Kanban unreliable ](https://github.com/3drepo/3drepo.io/issues/1988#issuecomment-617279724)
- [x] [Project permissions does not automatically open the users list](https://github.com/3drepo/3drepo.io/issues/1988#issuecomment-617613623)
- [x] [Kanban board throws an error code 'Not Authorized' to a user with Project Admin Rights](https://github.com/3drepo/3drepo.io/issues/1988#issuecomment-617619297)
- [ ] [Measurement Tool position accuracy](https://github.com/3drepo/3drepo.io/issues/1988#issuecomment-618395601)

**The following has been deemed non release critical and now has their own separate issues:**

<details>

-  [Kanban Board Issues don't show section cuts when you click on 'View on Model'](https://github.com/3drepo/3drepo.io/issues/1988#issuecomment-617662644)
- [Manual Group Type is missing the underline in the Description Field](https://github.com/3drepo/3drepo.io/issues/1988#issuecomment-617761746)
- [Groups Colour Picker not responding correctly](https://github.com/3drepo/3drepo.io/issues/1988#issuecomment-617771389)
- [Groups Name and Description can be hidden by clicking on an invisible button](https://github.com/3drepo/3drepo.io/issues/1988#issuecomment-617774972)
- [Smart Groups remove value button disables Value Restrictions and Activates Add/update button](https://github.com/3drepo/3drepo.io/issues/1988#issuecomment-617807751)

</details>

**Comment by mosment3DRepo** [comment]
### Attaching image comments to Risks on Kanban unreliable

### Description
When you attach an image to a comment it frequently does not load the image into the comment window after hitting 'Save' on the mark-up dialog

### Steps to replicate
- Kandban Board
- Create new or edit existing risk
- Add image to comment window
- As per gif below:
   - 1st attempt: plain image upload - unsuccesful
   - 2nd attempt: plain image upload - unsuccesful
   - 3rd attempt: doodle + image upload - succesful
   - 4th attempt: plain image upload - succesful
   - 5th attempt: plain image upload - unsuccesful


### Pictures/ Gifs of the error
![](https://raw.githubusercontent.com/mosment3DRepo/images/master/imagecomment.gif)

**Comment by BDavydov** [comment]
**Description**
Project permission button takes you to the User management page. A user would expect to see a list of users for this project, but the list is empty. This is because the project drop-down list doesn't automatically contain project selection. 

**Steps to replicate:**
- Log in to 3D Repo (dev)
- Go to the Models & Federations page
- For any of your projects click on the Permissions tab
- You will be redirected to User Management
- The drop-down list doesn't contain project selection

![Project User Permissions](https://user-images.githubusercontent.com/19904513/79955192-55e06c80-8476-11ea-96d2-7748eb4d0370.gif)

**Comment by BDavydov** [comment]
**Description**
I was added to a teamspace and decide to open a Kanban board. When I click on the Federation's Kanban board icon I get an Error Code 'Not Authorized' however I have admin right to this project and can updated issues.

**Steps to Replicate:**
- Create an alternative account (Account A)
- Using your personal account add Account A to one of your projects
- Give them Project Admin rights
- Log in to 3D Repo using Account A
- From the list of projects in other teamspaces click on the Kanban board
- Get an error message
- Carry on using the Kanban board as normal

![Kanban Permissions](https://user-images.githubusercontent.com/19904513/79956366-f71bf280-8477-11ea-8164-07e178adcb59.gif)

**Comment by BDavydov** [comment]
**Description**
Opening Issue in the viewer from Kanban board doesn't show section cuts.
When you look at an issue in the Kanban board click on the 'View in Model' Icon. Once you are redirected to a model viewer you will navigate to an Issue's viewpoint. The issue contains a section cut, which does not appear if you open it from Kanban Board.

**Steps to Replicate**
- Create an issue with a section cut
- Go to the Kanban board an open the same issue
- Click on the 'View on Model' button
- Once the viewer loads you will navigate to the Issue's viewpoint
- Section cut is missing
- Come out of the issue and open it again to see the section cut

![View Issue in Model](https://user-images.githubusercontent.com/19904513/79965088-82e74c00-8483-11ea-8f11-20ae4cbd7298.gif)

**Comment by BDavydov** [comment]
**Description**
The manual Groups Description field is missing the underline when writing text. Should be similar to
 the description field in Issues. 

**Steps to replicate**
- Open any 3D Model
- Open the Groups Card
- Click on the Green + button to create a new group
- In the group, description click on the field to fill out (Mast be a manual group type)

![Groups Description](https://user-images.githubusercontent.com/19904513/79984234-cac89c00-84a0-11ea-9e72-fcbbe2b55363.gif)

**Comment by BDavydov** [comment]
**Description** 
Groups Colour Range square tile does not respond to the colour spectrum selection. Only updates when you select a new colour from the spectrum chart and click on the square tile after. 

**Steps to replicate**
- Open any 3D Model
- Start Creating a new group
- Click on the Colour picker
- Change the colour from the spectrum bar
- Click on the square tile to then get an update on the colour density variants

![Group Colours](https://user-images.githubusercontent.com/19904513/79986122-770b8200-84a3-11ea-8cc8-e18aec17a890.gif)

**Comment by BDavydov** [comment]
**Description**
Groups contain an invisible hide button (similar to the one that hides the issue description and shows comments only). User can click on it accidentally and hide the Group information. You can unhide it again if you find the expand button ( may take a few clicks). 

![Group description hide button](https://user-images.githubusercontent.com/19904513/79986736-6dcee500-84a4-11ea-88fd-112a124be057.gif)

**Comment by BDavydov** [comment]
**Description**
In smart groups by default the Value field is required unless the operation is a wildcard (Exists). Therefore, Add button stays grey, until a user provides the value. You can activate add button without providing the mandatory value field by pressing on the 'Remove Value' button -
This applies to an existing or new filter. 

**Steps to Replicate**
- Open 3D Model
- Open the Groups Card
- Start Creating a new group and select 'Smart Group' from the group's type
- Fill out the Field section
- Select Operation (such as contains)
- Click on the Remove value - button
- See the mandatory value field disappear.
- Add button now becomes active
- 'Add value' + button is now greyed out, so you can't add any values again :(

![smart groups rule logic](https://user-images.githubusercontent.com/19904513/79992847-f1400480-84ab-11ea-9f08-1c39aec587e6.gif)

![Smart Groups Add value bug](https://user-images.githubusercontent.com/19904513/79993323-8ba04800-84ac-11ea-9962-2bcbfe45808e.gif)

**Comment by BDavydov** [comment]
> **Description**
> I was added to a teamspace and decide to open a Kanban board. When I click on the Federation's Kanban board icon I get an Error Code 'Not Authorized' however I have admin right to this project and can updated issues.
> 
> **Steps to Replicate:**
> 
> * Create an alternative account (Account A)
> * Using your personal account add Account A to one of your projects
> * Give them Project Admin rights
> * Log in to 3D Repo using Account A
> * From the list of projects in other teamspaces click on the Kanban board
> * Get an error message
> * Carry on using the Kanban board as normal
> 
> **Edit by CF : I think this due to kanban board calling ts settings and it has the wrong permissions control? We also need to call `/:ts/mitigations/criteria` to get the real list of risk categories**
> 
> **Edit 2: ts setting permission is fixed in #1963. It'll be merged in when travis test passed. Check after that. But we should still use risk categories from the other endpoint.**
> 
> ![Kanban Permissions](https://user-images.githubusercontent.com/19904513/79956366-f71bf280-8477-11ea-8164-07e178adcb59.gif)

@carmenfan The same error message appears when you open a 3D Model. I have been given Project Admin Rights. After clicking on OK, I can carry on reviewing issues.
![image](https://user-images.githubusercontent.com/19904513/80006626-0bcea980-84bd-11ea-8785-a43717d185d5.png)

**Comment by carmenfan** [comment]
> > **Description**
> > I was added to a teamspace and decide to open a Kanban board. When I click on the Federation's Kanban board icon I get an Error Code 'Not Authorized' however I have admin right to this project and can updated issues.
> > **Steps to Replicate:**
> > 
> > * Create an alternative account (Account A)
> > * Using your personal account add Account A to one of your projects
> > * Give them Project Admin rights
> > * Log in to 3D Repo using Account A
> > * From the list of projects in other teamspaces click on the Kanban board
> > * Get an error message
> > * Carry on using the Kanban board as normal
> > 
> > **Edit by CF : I think this due to kanban board calling ts settings and it has the wrong permissions control? We also need to call `/:ts/mitigations/criteria` to get the real list of risk categories**
> > **Edit 2: ts setting permission is fixed in #1963. It'll be merged in when travis test passed. Check after that. But we should still use risk categories from the other endpoint.**
> > ![Kanban Permissions](https://user-images.githubusercontent.com/19904513/79956366-f71bf280-8477-11ea-8164-07e178adcb59.gif)
> 
> @carmenfan The same error message appears when you open a 3D Model. I have been given Project Admin Rights. After clicking on OK, I can carry on reviewing issues.
> ![image](https://user-images.githubusercontent.com/19904513/80006626-0bcea980-84bd-11ea-8785-a43717d185d5.png)

yep, same problem. ts setting permission isn't set right. @Charence  fixed it

**Comment by mosment3DRepo** [comment]
**Description**
Measurement tool no correctly visualising seleciton location, appears to be out consistently. Same issue occurs in Pins. Most obvious example is in [This Residential Model](https://dev.3drepo.io/viewer/Bogdan_D/02b274c0-2271-11ea-8625-4351ad484b5b.)

**Steps to Replicate:**
 
* Open Point to Point Measurement Tool
* Snap to edge of element
* Complete measurement and review points

**Comment by carmenfan** [comment]
> **Description**
> Measurement tool no correctly visualising seleciton location, appears to be out consistently. Same issue occurs in Pins. Most obvious example is in [This Residential Model](https://dev.3drepo.io/viewer/Bogdan_D/02b274c0-2271-11ea-8625-4351ad484b5b.)
> 
> **Steps to Replicate:**
> 
> * Open Point to Point Measurement Tool
> * Snap to edge of element
> * Complete measurement and review points

Moving this to #1998 as a separate bug
