### ISSUE TITLE
Add plane border settings to visual setttings

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2036]
requires https://github.com/3drepo/3drepounity/issues/268

### Description
Add plane border settings such as colour and width so users can have the ability to customize the look to their personal preferences.

### Tasks
- [x] Add to unityutil SetPlaneBorderWidth
- [x] Add to unityutil SetPlaneBorderColor
- [x] Add the item plane border width in visual settings dialog
- [x] Add the item plane border colour in visual settings dialog
