### ISSUE TITLE
Emails template

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2044]
### Description
Add emails templates and separate html into reusable parts

### Tasks
- [x] Separate template code into reusable parts
- [x] Implement new  invitation email template
- [ ] Implement new  verification email template
- [ ] Implement new password reset email template
- [ ] Implemant welcome email template

**Comment by carmenfan** [comment]
I think this got abandoned - code will be re-written in v5 as well.
