### ISSUE TITLE
4.7.1 bug list

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2058]
### Bugs
- [x] [Error if user tries to open the viewer on firefox](https://github.com/3drepo/3drepo.io/issues/2058#issuecomment-635456375)
- [x] [NO_FILE_FOUND error if you try to export to BCF with a broken screenshot reference](https://github.com/3drepo/3drepo.io/issues/2058#issuecomment-638218742)
- [x] [Ticket.clean code doesn't clean viewpoints properly if it is in the old schema.](https://github.com/3drepo/3drepo.io/issues/2058#issuecomment-638302314)
- [x] [fileshare refs are being stored with \ instead of / if the user is running from a windows machine](https://github.com/3drepo/3drepo.io/issues/2058#issuecomment-638327255)
- [x] [Incorrect label on kanban for risks](https://github.com/3drepo/3drepo.io/issues/2058#issuecomment-639537745)
- [x] [Model/Federation Name missing occasionally when you click go back to teamspace](https://github.com/3drepo/3drepo.io/issues/2058#issuecomment-639561569)
- [x] [Dismiss button throws an error code when measuring surface area](https://github.com/3drepo/3drepo.io/issues/2058#issuecomment-640522978)
- [x] [Model/Federation permissions icon doesn't open permissions list](https://github.com/3drepo/3drepo.io/issues/2058#issuecomment-640717340)
- [x] [Compare card shows Model IDs instead of Revision Names](https://github.com/3drepo/3drepo.io/issues/2058#issuecomment-641138808)
- [x] [Can't update issue status in Kanban Board. Works when you drag and drop the card](https://github.com/3drepo/3drepo.io/issues/2058#issuecomment-641185226)

**Comment by carmenfan** [comment]
**Error if user tries to open the viewer on firefox**
- Launching the viewer on firefox results in this:
![image](https://user-images.githubusercontent.com/11945337/83168060-d7c45500-a108-11ea-8d2a-0d8dfed1df31.png)

As with the unity 2019 upgrade, we're now using webassmebly, this seems to be related to this:
https://github.com/emscripten-core/emscripten/issues/5559#issuecomment-328542101

**Comment by carmenfan** [comment]
`NO_FILE_FOUND` error if you try to export to BCF with a broken screenshot reference
This is failing because nodeJS couldn't find the data for a screenshot:
http://api1.example.org/api/carmen/6cb7debf-3b10-4941-87b3-2b6dc531f1b6/issues.bcfzip?numbers=1,2,3,4

**Comment by carmenfan** [comment]
Ticket.clean code doesn't clean viewpoints properly if it is in the old schema.

A risk that is coming out of the toy project is found to be sending raw data of the screenshot. This is due to the viewpoint is placed in the `viewpoint` field instead of `viewpoints` array, and the clean logic completely ignores this.
![image](https://user-images.githubusercontent.com/11945337/83661387-f79ec180-a5bd-11ea-955b-f1a15d9bfb18.png)
![image](https://user-images.githubusercontent.com/11945337/83661397-fe2d3900-a5bd-11ea-9659-37f8a025a7eb.png)


API call can be tested here: http://api1.example.org/api/vnozdrenkov/1fb5aef0-950f-11ea-a767-0bc782383c6a/risks

**Comment by carmenfan** [comment]
**fileshare refs are being stored with `\` instead of `/` if the user is running from a windows machine**

This causes the linux based backends to fail to find the file even though it is there

**Comment by carmenfan** [comment]
**Incorrect label on kanban for risks**

This should say `Unmitigated`:
![image](https://user-images.githubusercontent.com/11945337/83889255-d2878b80-a742-11ea-8351-22dc3181f444.png)

**Comment by BDavydov** [comment]
Federation/Model Name disappears when you go back to the Teamsapce. I can't guarantee that it only happens when you set up GIS information, but it happened to me 3 times, whilst doing exactly that.

**Steps to replicate:**
- Open any model or create a new federation that contains no GIS Set up
- Open the GIS Card and set up your maps settings
- Activate the map tiles then deactivate them
- Go back to the teamspace, discover that the name is missing

![image](https://user-images.githubusercontent.com/19904513/83894004-a40caf00-a748-11ea-9c92-bd59ccf76f7e.png)

**Comment by BDavydov** [comment]
When you measure Surface Area and click the Dismiss button, an error code appears.

**Steps to replicate:**
- [Open this model](https://dev.3drepo.io/viewer/Bogdan_D/03c4a630-a4d5-11ea-90bd-db80072a6c88)
- Open measurements card
- Activate Surface Area
- Try measuring a complex mesh (curved roof/ railing)
- When calculating results click on the Dismiss button
- _Error Uncaught SyntaxError: Unexpected token N in JSON at position 1825 occured at line 8_
- User needs to refresh the browser tab

![Min Distance Dismiss Error Code](https://user-images.githubusercontent.com/19904513/84021425-7740dd80-a97c-11ea-98f9-56202cdd3372.jpg)

**Comment by BDavydov** [comment]
Permissions Icon doesn't work on some models/federations. Click on this icon for model federations or single models. Some work fine and show the users and permissions list, however, [this model](dev.3drepo.io/viewer/Bogdan_D/6aaddf10-2271-11ea-9278-29654c85f83d) doesn't work.

**Steps to replicate**
- Open dev.3drepo.io
- Click on the Users Icon for [this model](dev.3drepo.io/viewer/Bogdan_D/6aaddf10-2271-11ea-9278-29654c85f83d)
- User Management page comes up, but it's empty

![image](https://user-images.githubusercontent.com/19904513/84052602-b5ec8d00-a9a8-11ea-8a5e-0a3101c639ea.png)
![image](https://user-images.githubusercontent.com/19904513/84052626-bd139b00-a9a8-11ea-8b9c-4ee33f3b5991.png)
**What I expect to see**
![image](https://user-images.githubusercontent.com/19904513/84052713-d4528880-a9a8-11ea-8f46-7817be08eff4.png)

**Comment by BDavydov** [comment]
Compare Card shows me model IDs instead of the model revision's names.

**Steps to replicate**
- Open dev.3drepo.io
- Open any model/federation for instant clash
- Open the Compare Card

![image](https://user-images.githubusercontent.com/19904513/84127720-86389600-aa37-11ea-92c7-842799ce40ea.png)
![image](https://user-images.githubusercontent.com/19904513/84127738-8a64b380-aa37-11ea-92ca-c1f411b4f527.png)

**Comment by BDavydov** [comment]
Using Kanban Board, commenter/collaborator can update issue status by dragging and dropping issue card. However, the filed is greyed out when they open the Issue Card.

**Steps to replicate**
- Login to dev.3drepo.io
- Open Issues Kanban board for any model
- Drag and drop issue card to change its status
- Open the issue card to change the status
- Fields are greyed out even though it's assigned to you and you are a commenter/collaborator

![Strange Permissions](https://user-images.githubusercontent.com/19904513/84135045-61492080-aa41-11ea-9aa0-3a1320056d9f.gif)
