### ISSUE TITLE
Orthographic viewpoint support

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2066]
### Description
We want to add support for orthographic camera.

Note that similar work is happening in the issues plugin. To make that work, we have added a field `orthographicSize` to the viewpoint schema. This should match up nicely with both [Unity camera](https://docs.unity3d.com/ScriptReference/Camera-orthographicSize.html) and [BCF schema](https://github.com/BuildingSMART/BCF-XML/tree/master/Documentation#orthogonalcamera-optional)

Currently we have `type` parameter within the viewpoint schema that takes in `orthographic` or `perspective`. We can assume the lack of type to be perspective for backwards compatibility sake. 

### Goals
The user should be able to :
- Toggle between orthographic/perspective camera view while they are navigating
- If the viewpoint the user clicked to change to is of a different camera type as what they are currently using, the viewer should automatically change to the same type as the view to ensure the user sees exactly what was intended

### Tasks
In Unity:
- [x] Implement functions to toggle camera between perspective and orthographic
- [x] Check the current type and output fields accordingly when user request current viewpoint data
- [x] When user sets current viewpoint, check camera type and adjust accordingly

In 3drepo.io:
- [x] Add functionality to toggle between orthographic/perspective 
- [x] Ensure type parameter and zoom factor is saved into the database if it exists (I think this works already)
- [x] Ensure these values are being provided if available on a GET request   (I think this works already)
- [x] Ensure we are saving orthographic viewpoints properly on BCF exports
- [x] Ensure we're preserving `ViewToWorldScale` in BCF imports
- [x] Add tests
