### ISSUE TITLE
Presenter mode MVP

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2068]
### Description
Allow a user to establish a session, where other users can connect to, and share what they are
seeing with other users

### Goals
- [x] As a presenter I want to initiate a view sharing session
- [x] As an attendee I want to join an existing session
- [x] As an attendee I want to occasionally resume control of navigation
- [x] As a presenter I want sync my camera view with my attendees

### Tasks
- [x] Create an endpoint to start a sharing session
- [x] Implement ui to start a sharing session
- [x] Create a message type for the chat with the sharing session id 
- [x] Create an endpoint to stream the camera position
- [x] Implement ui to  join a sharing session
- [x] Subscribe to the camera position streaming and set unity to the streamed viewpoints
- [x] Implement ui to unjoin a sharing session

**Comment by carmenfan** [comment]
bug in presenter mode:
![image](https://user-images.githubusercontent.com/11945337/92600014-ea6f2e00-f2a2-11ea-84a4-b519c70e114b.png)


we should reset the state somehow if the user was logged out and re-logged in as the UI state resets
