### ISSUE TITLE
Add new Notifications for references within comments

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2070]
### Description
This is an extension to #2026

- When a user is tagged in a comment, it should create a notification for the user to say `xxx has tagged you in a comment`
- When a user tagged another issue within the same model, it should create a system message on the tagged issue saying `xxx has referenced this issue in #<issue number>` And the issue number should be clickable to go to that issue

### Goals
- [x] For each user reference, we should create a notification for users who are being referred.
- [x] For each issue being referenced, we should create a system comment which states `xyz referenced this issue in #yy`

### Tasks
- [x] Parse comments and determine if we should create a notification for a specific user
- [x] Parse comments and determine if we should be creating a system comment on another issue
- [x] Ensure UI understands and dispaly the user referenced notification properly
- [x] Ensure UI understands and display the issue reference properly
- [x] add test for parse comment and add notification for user tagging
- [x] add test for checking that quotes are not generating notifications when user tagging
- [x] add test for parse comment and add new system message for issue referencing
- [x] add test for checking that quotes are not generating system messages when referencing an issue
