### ISSUE TITLE
Issues/Risks UI update

### ISSUE THREAD

**Issue by m1chalkubiak** [3drepo/3drepo.io#2087]
### Description
Update UI of Issues and Risks panels, allowing the user to update images/viewpoints and clone whole ticket details.

### Tasks

**FRONTEND:**
 Existing issues:
- [x] Tab format like risk 
- [x] Move description/Screenshots to the top of the properties tab (like risk)
- [x] Slight revamp on attachments UI - notice new styling of button + message when there's no attachments 
- [x] Add void status -> auto hide on issue list like closed issues
- [x] Update viewpoint -> click -> ask if they want to add a new screenshot -> save
- [x] Edit Image -> split option (attach image/screenshot) -> ask if they want to update viewpoint -> save
- [x] edit image/update viewpoint -> if user doesn't have permissions (admin/owner's job only), it should be disabled with tooltip saying they do not have enough permissions to do this.
- [x] Add attach image as an option on commenting
- [x] button to clone issue -> copy all properties and populate it on new issue panel   

New Issues:
- [x] Similar formatting to existing issues
- [x] Add Image button
- [x] Removed the attach screenshot button at the footer
- [x] Once the user uploaded an image "Add Image" should become "Edit Image"
- [x] Add void status in status selection

Existing Risk:
- [x] Change risk icon (on menu also risk level icon) to be the same as the pin (svg can be found here)
- [x] Add image and update viewpoint added
- [x] revamp attachments
- [x] Add "void" as one of the treatment status
- [x] Update suggestion button to the same look and feel as the add image/viewpoint button
- [x] Also add the clone button for Risk

New Risk:
- [x] Similar to new Issues 

**BACKEND:**
 -  [x] Allow editing of screenshot/viewpoints on existing issues/risks endpoints

**Comment by m1chalkubiak** [comment]
@carmenfan 
Everything is almost finished, I need bit more time to work cloning tasks I should push it out tonight / tomorrow morning. I will also add a more detailed summary with additional questions.

**Comment by m1chalkubiak** [comment]
@carmenfan 
I would like to start with the fact that this is not 100% done mainly because I had less time for it than I expected, last week we were improving new comments. Therefore, I had less time for this task than we estimated. However, due to the fact that I will be on vacation for a week, I did not want to leave you with anything. That is why I would like to emphasize that there are places in the code that I would like to refactor yet and I am aware that this code may have some errors. I will take care of all this after returning from vacation.

I added cloning functionality but I have one problem with it, namely, I can't send the previous image to a new task. It seems to me that the problem is that existing tasks have an image saved as URLs (from the task id), while with normal creation of new tasks we send base64 and then the backend sends us the correct URL after creating a new task.
So I'm not sure if I should create base64 images from them, or is it something you can handle on the backend side.
Additionally, I picking which fields I'm copying during cloning, so there is a probability that I missed something.

I probably focused too much on how the new buttons look like on mockups, which is why both the clone button, suggestion, and new buttons under the image have slightly different styles. Probably this is something we would like to level up. Let me know what you think about it.

Of course, image updates and viewpoint don't work. The backend returns 400 currently, but I do it analogously to how the pin position is updating. So I think I'm sending it correctly.

> * Add void status -> auto hide on issue list like closed issues

Question regarding void status on risks:
Should void status should auto hide ticket on list? Rejected status don’t do that currently.

> * edit image/update viewpoint -> if user doesn't have permissions (admin/owner's job only), it should be disabled with tooltip saying they do not have enough permissions to do this.

The buttons should be disabled, but I didn't manage to add the appropriate tooltips.

I hope you will be satisfied overall and see you in a week.

**Comment by carmenfan** [comment]
@m1chalkubiak Thanks for the detailed explanation and working till late for this! I'll take a look soon and let you know if I have any feedback!

You are right viewpoint/screenshot update is not functional right now, we need https://github.com/3drepo/3drepo.io/pull/2069 in staging. @Charence can you look into finishing it off when you're back?

**Comment by carmenfan** [comment]
@m1chalkubiak 

#2069 is now merged in, so if you pull the latest off staging you should be able to edit screenshots/viewpoints.

Some things I found:
- [ ] there's now a quota warning message showing until it's been processed if I try to add resource (Not sure if you actually changed anything there, but I don't think I've seen it before), if it takes time to process we need to make sure we put a loading message in there instead of showing the error message :
![1](https://user-images.githubusercontent.com/11945337/85599595-901be500-b644-11ea-852d-d091d6945d53.gif)

**Comment by m1chalkubiak** [comment]
Hi @carmenfan , apologies for not giving any updates for a couple of days. I had a problem with updating of image on existing task, and now I think that there are some additional things that I need to ask You regarding this endpoint functionality. 

- After sending a request to update the issue, should we get an updated issue in response, currently we get the old one and I wonder if this is a bug?

- I'm not sure but I think that from the front-end perspective there are a few redundant fields here as well. For example viewpoint.screenshotSmall for issues / risks, we are not using it anywhere.

- I have not yet dive deeper into this topic but it seems to me that system logs with the image and viewpoint update aren't properly handled. Is this something that also requires additional work on the frontend side?

- Currently, the biggest challenge that I'm facing is the correct handling of cloning actions on the kanban board view. The problem is that we currently don't have any support for changing the styling dialog from the state manager perspective. I refer to the dialog in which the form is located, it just looks bad. I have an idea for this, but it will take a day or two to write it in a different way.

> * Styling goes weird when i click on edit pin:

I tried on different browsers, but I can't reproduce it, can you give me more details in what environment it happens?

**Comment by carmenfan** [comment]
@m1chalkubiak  sorry for the late reply!

> Hi @carmenfan , apologies for not giving any updates for a couple of days. I had a problem with updating of image on existing task, and now I think that there are some additional things that I need to ask You regarding this endpoint functionality.
> 
> * After sending a request to update the issue, should we get an updated issue in response, currently we get the old one and I wonder if this is a bug?

It should return you the updated issue, is this not the case in general or specifically for this viewpoint/screenshot change?

> * I'm not sure but I think that from the front-end perspective there are a few redundant fields here as well. For example viewpoint.screenshotSmall for issues / risks, we are not using it anywhere.

screenshotSmall is a deprecated field. Front end is not expected to use it.

> * I have not yet dive deeper into this topic but it seems to me that system logs with the image and viewpoint update aren't properly handled. Is this something that also requires additional work on the frontend side?

When the viewpoint/screenshot has changed, the front end is expected to just say something like "xxx has modified the viewpoint" or "xxx has updated the image" - a bit like pins.

> * Currently, the biggest challenge that I'm facing is the correct handling of cloning actions on the kanban board view. The problem is that we currently don't have any support for changing the styling dialog from the state manager perspective. I refer to the dialog in which the form is located, it just looks bad. I have an idea for this, but it will take a day or two to write it in a different way.

ok

> > * Styling goes weird when i click on edit pin:
> 
> I tried on different browsers, but I can't reproduce it, can you give me more details in what environment it happens?

I'm now seeing it without on hover even: 
![image](https://user-images.githubusercontent.com/11945337/87137492-e4ee6b00-c294-11ea-978c-7dd27855f0f1.png)

Seems to happen as soon as I have a screenshot/image on there. (Perhaps the introduction of the scroll bar is causing it?)

I'm on win 10 latest version on chrome, and I built the app with yarn build if that makes any difference!

**Comment by m1chalkubiak** [comment]
@carmenfan 
> > * After sending a request to update the issue, should we get an updated issue in response, currently we get the old one and I wonder if this is a bug?
> 
> It should return you the updated issue, is this not the case in general or specifically for this viewpoint/screenshot change?

So, when we are changing fields like status, priority, desc, position (which is pin position, from what I understand) etc. as a response we get ticker object with updated fields, but when we are sending updates for viewpoint / screenshot related fields aren't updated in the response object. It seems to me that if I start updating other fields, after a while, I will also receive the updated viewpoint and screenshot fields in the response, so it looks like something asynchronous is happening that we are not waiting for.

However, there is also the `thumbnail` field which contains a path for thumbnail of the ticket, which is used in listing view of all tasks. This field does not appear to be updated at all.

> > * I have not yet dive deeper into this topic but it seems to me that system logs with the image and viewpoint update aren't properly handled. Is this something that also requires additional work on the frontend side?
> 
> When the viewpoint/screenshot has changed, the front end is expected to just say something like "xxx has modified the viewpoint" or "xxx has updated the image" - a bit like pins.

Ok, I'll deal with it then.

> > > * Styling goes weird when i click on edit pin:
> > 
> > 
> > I tried on different browsers, but I can't reproduce it, can you give me more details in what environment it happens?
> 
> I'm now seeing it without on hover even:
> ![image](https://user-images.githubusercontent.com/11945337/87137492-e4ee6b00-c294-11ea-978c-7dd27855f0f1.png)
> 
> Seems to happen as soon as I have a screenshot/image on there. (Perhaps the introduction of the scroll bar is causing it?)
> 
> I'm on win 10 latest version on chrome, and I built the app with yarn build if that makes any difference!

You are right it is about the operating system, I did not notice the specific scrolls that are displayed on windows. We will probably have to narrow the buttons / distances between them slightly between them so that they display properly in this case.

**Comment by carmenfan** [comment]
>So, when we are changing fields like status, priority, desc, position (which is pin position, from what I understand) etc. as a response we get ticker object with updated fields, but when we are sending updates for viewpoint / screenshot related fields aren't updated in the response object. It seems to me that if I start updating other fields, after a while, I will also receive the updated viewpoint and screenshot fields in the response, so it looks like something asynchronous is happening that we are not waiting for.
>
>However, there is also the thumbnail field which contains a path for thumbnail of the ticket, which is used in listing view of all tasks. This field does not appear to be updated at all.

@Charence  can you look into this? I think we can just fix it on this branch.

>You are right it is about the operating system, I did not notice the specific scrolls that are displayed on windows. We will probably have to narrow the buttons / distances between them slightly between them so that they display properly in this case.

@m1chalkubiak  I think we can definitely narrow the space between the button as the gap looks quite wide atm! :)

**Comment by Charence** [comment]
> > So, when we are changing fields like status, priority, desc, position (which is pin position, from what I understand) etc. as a response we get ticker object with updated fields, but when we are sending updates for viewpoint / screenshot related fields aren't updated in the response object. It seems to me that if I start updating other fields, after a while, I will also receive the updated viewpoint and screenshot fields in the response, so it looks like something asynchronous is happening that we are not waiting for.
> > However, there is also the thumbnail field which contains a path for thumbnail of the ticket, which is used in listing view of all tasks. This field does not appear to be updated at all.
> 
> @Charence can you look into this? I think we can just fix it on this branch.

@m1chalkubiak I have pushed an update that I believe fixes the issue/risk response. The URLs for screenshot and thumbnail are expected to remain the same since the new image will be available at the same URL. Does this cause a problem?

**Comment by m1chalkubiak** [comment]
Thanks for the latest fixes @Charence . The updates seem to work correctly now.
I have reviewed the overall changes in this branch, made a few minor improvements and it seems to me that now everything should work properly. Will, you have time to review this feature again @carmenfan ?

**Comment by carmenfan** [comment]
@m1chalkubiak  if everything's done then please raise a PR :)
