### ISSUE TITLE
Standardise viewpoints in views/issues/risks

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2093]
### Description

Standardise viewpoints in views/issues/risks

### Goals

- Viewpoints in views/issues/risks should have the same properties
- Backwards compatibility should be retained for now (deprecated parts should be marked)

### Tasks

- [ ] Update viewpoint to match tickets
- [ ] Update/add tests (mark tests for deprecated formats)
- [ ] DB migration script
