### ISSUE TITLE
There's no validation checks for model settings update

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2115]
### Description
Model settings endpoint is not performing any validation checks on the object being sent from the front end. It needs to make sure it can only update values we allow the user to update, and that they are of the right type.

**Tasks:**
- [ ] Add whitelist to only allow users to update values we allow them to update (Note: Units is not something we allow the user to update)
- [ ] Add type checking to ensure the user is entering a value with the right type
- [ ] Ensure units is a value we currently support. (i.e. `m, mm` etc)

**Comment by carmenfan** [comment]
N/A with V5
