### ISSUE TITLE
Support colour overrides in viewpoints

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2116]
### Description
Support colour overrides in viewpoints for issues, risks, views and comments

### Goals
- [x] Creating a view saves the viewpoint with the colour override

### Tasks
- [x] In frontend get the current override state and send that data to backend the viewpoint that is being created
- [x] In backend create a group with the colour override value
- [x] In frontend when selecting the viewpoint show the colour override

**Comment by carmenfan** [comment]
This is merged into #2093
