### ISSUE TITLE
Compare Card & Transparent Groups

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2129]
- [ ] [3D Diff - group colour override with transparency highlights objects red](https://github.com/3drepo/3drepo.io/issues/2129#issuecomment-671486725)
- [ ] [Instant Clash - When you apply a group colour override (with transparency) another model loads](https://github.com/3drepo/3drepo.io/issues/2129#issuecomment-671488759)
- [ ] [Instant Clash - When you apply colour override to a group that has transparency it disappears](https://github.com/3drepo/3drepo.io/issues/2129#issuecomment-671490870)

**Comment by BDavydov** [comment]
**Description**
When you activate 3D Diff, you can apply the colour override to groups. If a group contains transparency, objects will inherit it, however, they become Red (deletion).

**Steps to replicate**
- Open any 3D Model with at least 2 Revisions
- Create a group that contains multiple elements
- Add Transparency to that group
- Open compare card and activate 3D Diff
- Select the group you have created (with transparency) and apply colour override

**Screenshot**
![3D Diff Transparent Group](https://user-images.githubusercontent.com/19904513/89811898-3bbabf00-db37-11ea-8286-7d72a6b39a5a.gif)

**Comment by BDavydov** [comment]
**Description**
When you activate Instant Clash you can isolate results by selecting some groups and Isolating them in view. If you apply colour override to a group isolated in view, it will load another model. The group that you have applied the colour override, contains transparency also. 

**Steps to replicate**
- Open any model federation
- Create a smart group for Model A & Model B
- Apply transparency to a group from Model B
- Open Compare Card and select instant clash
- Select model A & B and activate Instant Clash
- Select 2 groups that you have created earlier and Isolate them
- Select a group that contains transparency & apply colour override

**Screenshot**
![Instant Clash Transparent Group 1](https://user-images.githubusercontent.com/19904513/89812298-cef3f480-db37-11ea-91dc-e1064c2a5d85.gif)

**Comment by BDavydov** [comment]
**Description**
When you run instant clash and use smart groups to isolate results, the group that contains transparent objects will disappear if you apply colour override to it. 

**Steps to replicate**
- Create 2 groups (Group A & B) & include transparency in Group A
- Run instant Clash and apply colour overrides to Group A & B
- Isolate Groups A & B
- Notice how the Group A (with transparency) disappears

**Screenshot**
![Instant Clash Transparent Group 2](https://user-images.githubusercontent.com/19904513/89812656-62c5c080-db38-11ea-98df-0230c0fa7cad.gif)

**Comment by carmenfan** [comment]
This should be fixed in 4.9.1

Reopen if you still see it.
