### ISSUE TITLE
update viewpoints api docs

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2163]
### Tasks
- [x] Update views apidocs
- [x] Update issues apidocs
- [x] Update risks apidocs
