### ISSUE TITLE
Synchro v2

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2169]
❗  denotes it is depended on by another task

Mockup: https://marvelapp.com/prototype/2554ejj6

### Hourly increment support & schema changes
- [x] Make front end work with modified schema (currently white screening) ❗ (Santiago)
- [x] Modify logic to deduce current activity from the activity list ❗ (Santiago)
- [x] Add option to support steps in x hours
- [x] Change Date display to date/time 
- [x] Change Date picker to Date/time picker _[something like this?](https://material-ui.com/components/pickers/#date-amp-time-pickers)_

### Import changes
- [x] New revision page UI revamp (michal)
- [x] Add checkbox for option to import transformations if it is a spm file (michal)
- [x] API endpoint to understand flag and pass it to the queue ❗  (carmen)
- [x] Bouncer to ignore transformations in frames if flag set to false (https://github.com/3drepo/3drepobouncer/issues/382) ❗  (carmen)

### Activity List
- [x] Bouncer to export activity list as a json https://github.com/3drepo/3drepobouncer/issues/374 ❗ 
- [x] Remove current activity from frame data json https://github.com/3drepo/3drepobouncer/issues/374 ❗ 
- [x] Add endpoint to support list of activities ❗ (Charence)
- [x] Add endpoint to fetch activity details ❗ (Charence)
- [x] Right hand panel to display activity list + metadata (michal)
- [x] Support search in activity list (michal)
- [x] Add toggle to toggle right hand panel on/off (michal)
- [x] Implement a sequence action to change the date of the currently displayed frame ❗  (Santiago) : its `SequencesActions.setSelectedFrame(date)`
- [x] Ability to click on a date in activity metadata to change the date of current sequence (michal)

### Issues/Risks support
- [x] modify endpoint to support storing sequence start/end date in risks/issues
- [x] Ability to click on the date to go to the particular date in sequence card
- [x] When sequence is running, hide pins of issues/risks that contains a start/end date if the current date is not within those 2 dates
- [x] Add chip filter/sort for sequence start dates

### Animations support
- [x] Supermesh changes for animations support https://github.com/3drepo/3drepobouncer/issues/379 (carmen)
- [x] (Unity) add api to alter transform of a mesh  (carmen) https://github.com/3drepo/3drepounity/issues/303
- [x] (Unity) error out if the mesh isn't of it's own supermesh.  (carmen) https://github.com/3drepo/3drepounity/issues/303
- [x] Add bridging API in UnityUtils to call this move Mesh function  (see https://github.com/3drepo/3drepo.io/commit/076965769f1453e6d63dc633a01c92688b12ffee#diff-8ff416ab308f7376de7ffd20b7ca6482)
- [x] Move mesh accordingly when the frame state requires for it.

### Additional improvements
- [x] When you open the sequence tab, don't automatically show all objects. Only change the state of the objects when the user enters into a sequence
- [x] Other bouncer changes https://github.com/3drepo/3drepobouncer/issues/380
- [x] Add support for extra error codes

**Comment by carmenfan** [comment]
@m1chalkubiak 

Mode upload endpoint updated, it now takes in [an optional parameter](https://github.com/3drepo/3drepo.io/commit/8e99f2b8fd792b00219dfa0054e8cdec1b651f88#diff-32d7081d865007104d9d621ec5425bd0R1338) `importAnimations` as part of the payload

**Comment by m1chalkubiak** [comment]
Hi @carmenfan 
I've been working on the activity list panel for a while, but the version of code that I based on was probably slightly outdated as it contained some hardcoded response from what I understand. Today when I wanted to make the final updates I pulled the newest changes and all `activities` endpoints stopped working form me. Can You take a look at this? I using ones provides by Charence couple of days ago.
I've been trying with both models `oldSchema` and `newSchema` but I still getting `404`.

**Comment by carmenfan** [comment]
> Hi @carmenfan
> I've been working on the activity list panel for a while, but the version of code that I based on was probably slightly outdated as it contained some hardcoded response from what I understand. Today when I wanted to make the final updates I pulled the newest changes and all `activities` endpoints stopped working form me. Can You take a look at this? I using ones provides by Charence couple of days ago.
> I've been trying with both models `oldSchema` and `newSchema` but I still getting `404`.

Can you try now (with newSchema)? 

We've renamed the .tasks collections to .activities so this is most likely why

**Comment by m1chalkubiak** [comment]
@carmenfan 
Unfortunately, I see no change.
I'm using `newSchema` model,
I restarted my local BE, clear cache on the browser. I even went back to a few commits to check if any of my changes broke anything, but the request to this endpoint, which happens after selecting a sequence throws the same error all the time.

**Comment by Charence** [comment]
@m1chalkubiak I've made one more change on the DB. Please try again.

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak I've made one more change on the DB. Please try again.

Thanks @Charence now endpoints seems to work well.

@carmenfan From what I can see, something is wrong right now with the left sequences panel - in its case, no activity is displayed at the moment. There is probably something minor to correct there on FE side. With this and a few other things that I know still need to improve, I should be able to deliver it somewhere by the middle of the day tomorrow. 
If anything else will raise my doubts, I will let you know.

**Comment by sanmont3drepo** [comment]
> > @m1chalkubiak I've made one more change on the DB. Please try again.
> 
> Thanks @Charence now endpoints seems to work well.
> 
> @carmenfan From what I can see, something is wrong right now with the left sequences panel - in its case, no activity is displayed at the moment. There is probably something minor to correct there on FE side. With this and a few other things that I know still need to improve, I should be able to deliver it somewhere by the middle of the day tomorrow.
> If anything else will raise my doubts, I will let you know.
Do you mean this panel?
![image](https://user-images.githubusercontent.com/42032433/93902105-7ea3b100-fcf7-11ea-8bc6-89edeeb35780.png)
it seems to be working.
Maybe you are using a broken model?
does the GET api call for activities for your model works?
http://{yourlocalurl}/api/{teamSpace}/{model}/revision/master/head/sequences/{sequenceId}/activities

**Comment by sanmont3drepo** [comment]
@m1chalkubiak it seems that you added redundant functions in activities sagas

If you take a look the call is already there in fetchTasksDefinitions in sequence sagas.
here:
https://github.com/3drepo/3drepo.io/blob/257d7aea2d5f6aeac7a24d7f1407ab49005d5843/frontend/modules/sequences/sequences.sagas.ts#L56

if you need to get the information about those activities there are also selectors, here:
https://github.com/3drepo/3drepo.io/blob/257d7aea2d5f6aeac7a24d7f1407ab49005d5843/frontend/modules/sequences/sequences.selectors.ts#L283

if you need the data to be presented in another way add a selector using this selector as a source of data:
https://github.com/3drepo/3drepo.io/blob/257d7aea2d5f6aeac7a24d7f1407ab49005d5843/frontend/modules/sequences/sequences.selectors.ts#L64

**Comment by m1chalkubiak** [comment]
@sanmont3drepo 
 > Do you mean this panel?
> ![image](https://user-images.githubusercontent.com/42032433/93902105-7ea3b100-fcf7-11ea-8bc6-89edeeb35780.png)
> it seems to be working.

For me it looks like this:
<img width="332" alt="Zrzut ekranu 2020-09-23 o 10 53 51" src="https://user-images.githubusercontent.com/24941866/93990468-6c735280-fd8b-11ea-8484-866a90efed35.png">

> Maybe you are using a broken model?
> does the GET api call for activities for your model works?
> http://{yourlocalurl}/api/{teamSpace}/{model}/revision/master/head/sequences/{sequenceId}/activities

Yes, API call for activities works, so it is hard for me to say if it is broken or not.
<img width="543" alt="Zrzut ekranu 2020-09-23 o 10 53 43" src="https://user-images.githubusercontent.com/24941866/93990628-a47a9580-fd8b-11ea-84b8-bd5c754878f0.png">

**Comment by carmenfan** [comment]
@m1chalkubiak we figured out the problem. The data I uploaded was before a date fix (the dates are stored in seconds instead of ms)

I'm going to upload a new revision of the model manually with the fixed data, will let you know when done

**Comment by m1chalkubiak** [comment]
@carmenfan when can the model update be expected? Unfortunately, I still don't see any change on my side.

**Comment by carmenfan** [comment]
@m1chalkubiak sorry, I have limited upload bandwidth at home so uploading a 3d model takes a while... (and because it takes a while I got distracted with other tasks as well 😆 )

Should be all ready now, let me know if there's any problem

**Comment by Charence** [comment]
@sanmont3drepo Sending `null` will now delete the `sequence_start`/`sequence_end`.

**Comment by m1chalkubiak** [comment]
> Should be all ready now, let me know if there's any problem

@carmenfan 
Sadly now the model isn't loading at all, stops at 0%.
And call for /activities throws 404 error (again ?)

**Comment by carmenfan** [comment]
@m1chalkubiak how about now?

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak how about now?

@carmenfan The model is loading properly but call for /activities still throws 404.

**Comment by Charence** [comment]
@m1chalkubiak I've made a change on the BE. Could you please try again and let me know if it fixes the problem?

**Comment by m1chalkubiak** [comment]
Yes, it seems to me that the model is working well now. Thank You so much @carmenfan and @Charence for helping me. I will make the missing improvements and let you know when this feature is ready for your feedback.

**Comment by m1chalkubiak** [comment]
Hi @carmenfan 
I think that all assigned to me subtasks are covered.
There is one thing where I would need your decision, it is about searching in the activity panel. We agreed on a simple string search, and this is what I implemented, but I filter and render nested elements in a specific way. I assumed that when looking for a specific activity, we might really want to find all the sub-activities that belong to it.
So, for example, the results of the search would look like this:
<img width="370" alt="Zrzut ekranu 2020-09-30 o 10 06 16" src="https://user-images.githubusercontent.com/24941866/94659492-a8b32f80-0304-11eb-92fc-2756ee924281.png">
But if you wanted this to work exactly like in the Tree panel, i.e. a flat list of only activities that match the name to be searched, I can change it right away.

**Comment by BDavydov** [comment]
### Description
A new user invitation containing more than 2 projects does not work. You can invite new users to 1 or 2 projects, no more.

### Steps to replicate
- Go to User Management
- Click on the Green Plus button
- Click on the 'Invite to 3D Repo'
- Specify an email address
- Select a job
- In the projects menu select a project and define user permissions
- Repeat the above step so you have 3 projects minimum
- Click Invite
- Invalid Model ID Error pops - up

### Pictures/ Gifs of the error
![Invitation](https://user-images.githubusercontent.com/19904513/98976285-1612cc80-250f-11eb-80e0-4db5364f80d9.gif)

**Comment by BDavydov** [comment]
### Description
Selection boxes do not work in the Projects' permissions tab.

### Steps to replicate
- Go to User Management
- Click on the Projects Tab
- Select a project
- Click on the Selection Boxes (individual users)
- Click on the Select All selection box
- No response from both of the steps above

### Pictures/ Gifs of the error
![Project Permissions Selection box](https://user-images.githubusercontent.com/19904513/98976861-c84a9400-250f-11eb-9d2f-cb088a9f8180.gif)
