### ISSUE TITLE
Investigate Elastic APM

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2198]
### Description
This is to start Testing Elastic APM

### Goals

- [x] Application logs presented in Elastic
- [x] Runtime statistics collected from docker images
- [x] Exceptions traceable

### Tasks

- [x] Get the APM module installed
- [x]  Learn how to configure it

**Comment by carmenfan** [comment]
@keifgwinn instead of making it all fully integrated with the live 3drepo.io feed at the very start, it might be good to start smaller/isolated and do it in https://github.com/3drepo/3drepo.io/tree/master/scripts/reporting/statsGen

This is the script that gets run to generate the monthly report for stats., so hooking that up and sending the data to elastic is probably a good start (also the type of data we know for sure the business guys need)

**Comment by Charence** [comment]
A nice to have would be a message to remind the user to set the environment variable before this line in `genStats`:

`const ELASTIC_CLOUD_AUTH = process.env.ELASTIC_CLOUD_AUTH.split(":")`
