### ISSUE TITLE
Walkme: Add unique ids to frontend elements to be able to id them in walkme

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2236]
### Description
Add ids as described in  https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Support/Walkthrough?preview=3D+Repo+Element+Naming+Requirement.pptx

### Tasks
The following elements should have a unique id.

In the viewer:
- [x] Each button on the left bar.
- [x] Each card
- [x] Each card with opened details
- [x] Each 'add-new' button in each card
- [x] 'save' button in groups
- [x] 'add comment' buttons in issues and risks
- [x] The div that contains all the add measurements in measurements
- [x] 'save' button when creating a new issue/risk
- [x] 'save' button in views
- [x] Each button  on the top right
- [x] The entire bottom toolbar

In the dashboard:
- [x] Each teamspace in models & federations
- [x] Each project for each teamspace
- [x] Each model area for each project

**Comment by sanmont3drepo** [comment]
![image](https://user-images.githubusercontent.com/42032433/95216565-816fcd00-07f2-11eb-976d-5ff92c65d83e.png)
![image](https://user-images.githubusercontent.com/42032433/95216604-8c2a6200-07f2-11eb-95f5-bd3e93c3b06a.png)
![image](https://user-images.githubusercontent.com/42032433/95216624-94829d00-07f2-11eb-9b88-dbf2ef58d643.png)
