### ISSUE TITLE
Rules for Metadata

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2243]
### Description

Use rule queries from groups to query metadata

### Tasks

- [x] Refactor rules out of groups
- [x] Refactor rules to helper/rules
- [x] Refactor metadata out of helper/model
- [x] Add tests for federation smart group
- [x] Add tests for meta filters with rules
- [x] Get list of mesh ID based on smart rules
- [x] Add tests for filter all metadata with rules
- [x] All metadata filter based on smart rules
- [x] Remove mongoose dep?
- [ ] Clean up
