### ISSUE TITLE
Group Card changes

### ISSUE THREAD

**Issue by m1chalkubiak** [3drepo/3drepo.io#2263]
### Description
Improving the user experience regarding the use of the group panel

### Goals
- [x] User can see which Groups currently have their colour overrides applied
- [x] Allow user to switch the colour overrides and isolate without requiring of focusing on card first  

### Tasks
- [x] Disable actions hiding for group card
- [x] Move remove group action inside group details
