### ISSUE TITLE
Investigate Intercom

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2268]
### Description

Investigate Intercom integration

### Goals
- [x] Intercom client starts
- [x] Intercom client can populate logged in customer data

### Tasks

- [x] Add intercom configuration settings
- [x] Add intercom header
- [x] Populate intercom API with logged in session information

**Comment by carmenfan** [comment]
merged into #2340  as part of the hotfix
