### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2296]
### Description
A list of small UI improvements to be attended to TBD

- [ ] [_Last Updated_ field in the group's card is inconsistent](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224487)
- [x] [Long view names should have a full name presented on hover (like with the model tree elements)](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224563)
- [x] [Peculiar behaviour discovered when editing federations right after the model name change](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224663)
- [ ] [Edit measurement's name icon is poorly positioned](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224858)
- [x] [Federation Name Limit is now showing up as a warning message](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224978)
- [x] [Model Name limit message is confusing](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728225108)
- [x] [The CV is eclipsing the treatment file name when it is too long](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-732206803)
- [x] [Autosuggestions positioning issue during filtering list](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-733039102)
- [x] [Add a character limit for Job titles](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-732247270)
- [x] [Add options menu with base options in Views Card](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-733044366)
- [x] [Auto-populated revision name should truncate to the max character length](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-739870509)
- [x] [Limit Job role character length to 50](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-739973466)
- [x] [Increase revision name limit to 50 on the UI](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-739973466)
- [ ] [Increase revision name limit to 50 on the backend/API](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-739973466)
- [x] [Ticket Screenshot update during an edition of pin cause disappearing of an edited pin (both Risks & Issues).](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-733689500)
- [x] [Fix styling of the tabs on issues card](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-733766046)
- [x] [Reset viewerGUI state after leaving model](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-735797649)

**Comment by mosment3DRepo** [comment]
### Description
_Last Updated_ field in the Groups Card is insistent with the rest of the card layout. Font size is different and too big. Make it smaller as other fields of information so that it sits in one line.

### Steps to replicate
- Open any model
- Open the Groups Card
- Click on the Green button to start creating a group
- Notice the last updated field is too large

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/98984064-96d6c600-2519-11eb-9103-c96f506b29c1.png)

**Comment by mosment3DRepo** [comment]
### Description
Views are allowed to have a name with 37 characters maximum. Unfortunately, only 30 characters are visible, 
the rest is presented as ...
Ideally, it should display a full name on hover. Otherwise, users may potentially miss out on useful bits of information if these views follow strict naming strategy. 

### Steps to replicate
- Open any model
- Open the Views Card
- Create a view with the name containing 37 characters (max allowed)
- Save the view
- Not all of the view name is visible

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/98984809-9ab71800-251a-11eb-987c-29662dd4b18c.png)

**Comment by mosment3DRepo** [comment]
### Description
You can change a model name at any time. However, should that model be part of a federation, then you're going get confused when you go to edit that federation next. As you can see the new model name now exists in the list of available models, at the same time the old name exists in the list of federated models. This is confusing, and therefore a user may add a new model accidentally, without realising that the previous name already exists in the list & wasn't updated. This can be fixed by refreshing the web page. Sadly, that will not be the first thing a user will do as they will rush to our support team in frustration, especially if the list of models in the federation is long. How can you best address this issue? 

### Steps to replicate
- Log in to 3D Repo
- Head over to any project that contains several models and a federation
- Make sure the model you are about to change the name of is federated
- Now, change the model's name
- Click on the edit button (for any federation where it resides)

### Pictures/ Gifs of the error
![Renaming a model](https://user-images.githubusercontent.com/19904513/98987524-326a3580-251e-11eb-9e8d-f167fb877e18.gif)

**Comment by mosment3DRepo** [comment]
### Description
Edit measurement's name icon is not aligned with text.

### Steps to replicate
- Open any model
- Open the measurements card
- Take a Length or an Area measurement
- Notice how the Edit Name icon has shifted up & hidden by the UI

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/98988082-0602e900-251f-11eb-9deb-e1352b2fde59.png)

**Comment by mosment3DRepo** [comment]
### Description
The federation name is limited to 120 Characters as per Model Name. However, there is no warning message to say that. Some users copy & paste information, then don't understand why it doesn't save.

### Steps to replicate
- Log in to 3D Repo
- Create any federation and start typing the name
- Even though everything else is done accordingly, you can't save it.
- There is no warning message to say that the Name is too long (120 characters max)

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/98989125-8fff8180-2520-11eb-80ee-26e5c9fdd182.png)

**Comment by mosment3DRepo** [comment]
### Description
Model Name limit is confusing. Should just say _Model Name is limited to 120 characters_ 
instead of _modelName must be at most 120 characters_ 

### Steps to replicate
- Log in to 3D Repo
- Start creating a new model container
- Give it a name that is more than 120 characters
- Notice the warning message

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/98989522-2633a780-2521-11eb-9843-40350dcd77a2.png)

**Comment by BDavydov** [comment]
### Description
Currently, you can delete your last comment in Issues/Risks. This works fine if you make a mistake and remove the comment in session. Unfortunately, this action discredits the audit trail functionality of our issues/risks when you are able to delete comments 2/3/4 or 5 months after posting it.

### Steps to replicate
- Open any Issue/Risk in 3D Repo
- Post a comment
- Open the same Issue/Risk a day or a month later
- Click on the X button to delete your last comment
- None will ever know 😈

### Pictures/ Gifs of the error
Today is 23/11/2020
![image](https://user-images.githubusercontent.com/19904513/99964497-436f3e00-2d8b-11eb-8ca7-bb1a9b5ecebc.png)

**Comment by carmenfan** [comment]
The CV is eclipsing the treatment file name when it is too long 
![Uploading image.png…]()

**Comment by BDavydov** [comment]
### Description
There is no character limit for Job titles. Users can fill in all sorts of things

### Steps to replicate
- Open the User Management page
- Open the Jobs Tab
- Create a new Job with a really long title

### Pictures/ Gifs of the error

![image](https://user-images.githubusercontent.com/19904513/99983479-cef4c900-2da3-11eb-821a-171bafc293f4.png)

![image](https://user-images.githubusercontent.com/19904513/99983497-d320e680-2da3-11eb-9a13-ce246f1f47d8.png)

**Comment by carmenfan** [comment]
> ### Description
> Currently, you can delete your last comment in Issues/Risks. This works fine if you make a mistake and remove the comment in session. Unfortunately, this action discredits the audit trail functionality of our issues/risks when you are able to delete comments 2/3/4 or 5 months after posting it.
> 
> ### Steps to replicate
> * Open any Issue/Risk in 3D Repo
> * Post a comment
> * Open the same Issue/Risk a day or a month later
> * Click on the X button to delete your last comment
> * None will ever know 😈
> 
> ### Pictures/ Gifs of the error
> Today is 23/11/2020
> ![image](https://user-images.githubusercontent.com/19904513/99964497-436f3e00-2d8b-11eb-8ca7-bb1a9b5ecebc.png)

@3drepo/product-team this is less of a UI thing more of a scope definition. The original scope was that the user can delete the latest comment. if we want to change to "the user can delete the comment only if it's the latest comment & less than X days old" then... that works too, but I don't think there's any change on the UI side for this

**Comment by BDavydov** [comment]
### Description
When I use the Risks Kanban Board, I have difficulties selecting my options from the input drop-down list. If it contains several options, it's presented as a drop-down list (fine). When I start filtering the list, it slowly disappears and matching fields appear randomly on their own.

### Steps to replicate
- Open any of my models on DEV
- Start creating a SafetiBase Risk
- Select any input that contains a drop-down list
- Filter that list for a specific entry
- That's where the fun begins

### Pictures/ Gifs of the error
![SafetiBase Input List](https://user-images.githubusercontent.com/19904513/100112994-c49c0300-2e67-11eb-8fb3-e67f702f6ec1.gif)

**Comment by BDavydov** [comment]
### Description
It would be great if our Views Card an options menu as per other feature cards. Ideally, it should include at least the following:
- Delete All
- Sort By Name

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/100114003-d9c56180-2e68-11eb-8df3-92118e378040.png)

**Comment by BDavydov** [comment]
### Description
When I create a SafetiBase Risk and save it, I might suddenly decide to add a pin. If I add a pin after saving the risk, it's visible. However, if I then decide to update a screenshot, the Pin icon disappears until I close the Risk.

### Steps to replicate
- Open any model in 3drepo.io
- Create a SafetiBase Risk (no need to fill anything out)
- Now add a pin to the newly created Risk
- Update the Screenshot accordingly
- The pin icon disappears until you close the risk.

### Pictures/ Gifs of the error
![SafetiBase Icon Disappears](https://user-images.githubusercontent.com/19904513/100230274-6a5d7980-2f1d-11eb-91a2-f0af8ec0e5b8.gif)

**Comment by BDavydov** [comment]
### Description
Issues Card contains multiple tabs now and not all of them are readable. It's hard to tell what it is, and that you can click on it. 
Users unfamiliar with the UI won't understand what on earth is ATTACHM. Bring the text closer, there is no need for so much spacing in between or make the card wider. I can see the model anyway, but missing out on making the most of the UI.

### Steps to replicate
- Open any model in 3drepo.io
- Open the Issues Card
- Start Creating an Issue
- Notice the tab spread

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/100245891-7141b780-2f30-11eb-8615-c1f27321274d.png) ![image](https://user-images.githubusercontent.com/19904513/100245917-79015c00-2f30-11eb-9e68-93f0b024a1b9.png)

**Comment by BDavydov** [comment]
I open a model then switch to a helicopter mode. If I go back to my teamspace and open another model, it says that I am still using a helicopter navigation mode, but it's actually a Turntable Mode. So, I have to switch to a turntable, then to a helicopter again to make it work.

### Steps to replicate
- Open any model in staging.dev.3drepo.io
- Switch to a Helicopter mode
- Go back to your teamspace
- Open another model
- Start Navigating
- Notice that it's Turntable mode, but it says Helicopter

### Pictures/ Gifs of the error

![Navigation Modes](https://user-images.githubusercontent.com/19904513/100617815-edfada00-3312-11eb-9cf1-b090cf84ce4f.gif)

**Comment by m1chalkubiak** [comment]
> * - [ ] [_Last Updated_ field in the group's card is inconsistent](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224487)

@mosment3DRepo Can you please confirm that it still occurs and if so give me more details on what system, browser (+ version) on which it is reproducible?
I checked on my local machine on Chrome (Wersja 87.0.4280.67) and Firefox (83.0), it looks fine on my side.
<img width="398" alt="Zrzut ekranu 2020-12-2 o 11 11 55" src="https://user-images.githubusercontent.com/24941866/100859301-5c64a700-348f-11eb-8485-05f486c49284.png">

**Comment by m1chalkubiak** [comment]
> * [Edit measurement's name icon is poorly positioned](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224858)

@mosment3DRepo Similar to the case https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-737134762
I'm unable to reproduce it, if that still occurs, please give me more details on what system, browser (+ version) on which I can reproduce it.
<img width="433" alt="Zrzut ekranu 2020-12-3 o 12 48 29" src="https://user-images.githubusercontent.com/24941866/101015504-d10b1480-3567-11eb-8d17-a0b3c6a979b0.png">

**Comment by m1chalkubiak** [comment]
> The CV is eclipsing the treatment file name when it is too long

https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-732206803

@carmenfan Can You Please, upload the attached image one more time? Or point me to which part of the application You are referring to?

**Comment by mosment3DRepo** [comment]
@BDavydov could you take a look at Michaels comments

**Comment by m1chalkubiak** [comment]
> ### Description
> There is no character limit for Job titles. Users can fill in all sorts of things
> 
> ### Steps to replicate
> * Open the User Management page
> * Open the Jobs Tab
> * Create a new Job with a really long title

Hi @BDavydov is there any decision on what character limit should be implemented? 
I believe that real Job titles can be quite long, so it might be safer to show only a limited part of the name in the UI elements You referring to. In addition, we could also handle this long Job title case on the User management site, currently, only a part of such a title in the table will be visible - here we could add a tooltip and style it correctly.

**Comment by carmenfan** [comment]
> > The CV is eclipsing the treatment file name when it is too long
> 
> [#2296 (comment)](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-732206803)
> 
> @carmenfan Can You Please, upload the attached image one more time? Or point me to which part of the application You are referring to?

@m1chalkubiak sorry!
![image](https://user-images.githubusercontent.com/11945337/101032064-b178e980-3571-11eb-9895-147478442d1a.png)


It's the mitigation file, if you upload a csv that has a very long name, this happens

**Comment by m1chalkubiak** [comment]
> > > The CV is eclipsing the treatment file name when it is too long
> > 
> > 
> > [#2296 (comment)](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-732206803)
> > @carmenfan Can You Please, upload the attached image one more time? Or point me to which part of the application You are referring to?
> 
> @m1chalkubiak sorry!
> ![image](https://user-images.githubusercontent.com/11945337/101032064-b178e980-3571-11eb-9895-147478442d1a.png)
> 
> It's the mitigation file, if you upload a csv that has a very long name, this happens

No worries  @carmenfan 
As in a couple of other places in the app, I added an ellipsis and a tooltip, I believe it is the safest solution and most consistent with the rest of the app UI.
 
<img width="476" alt="Zrzut ekranu 2020-12-3 o 15 33 36" src="https://user-images.githubusercontent.com/24941866/101042414-767cb300-357d-11eb-827a-0968cca9a335.png">

**Comment by BDavydov** [comment]
> > ### Description
> > There is no character limit for Job titles. Users can fill in all sorts of things
> > ### Steps to replicate
> > 
> > * Open the User Management page
> > * Open the Jobs Tab
> > * Create a new Job with a really long title
> 
> Hi @BDavydov is there any decision on what character limit should be implemented?
> I believe that real Job titles can be quite long, so it might be safer to show only a limited part of the name in the UI elements You referring to. In addition, we could also handle this long Job title case on the User management site, currently, only a part of such a title in the table will be visible - here we could add a tooltip and style it correctly.

@m1chalkubiak It would be great if we could maybe stop the long name as ... in the Jobs section. Make it a tooltip on hover as with many long strings in 3D Repo. It also looks odd in the issues card, so should probably be shortened as well with a tooltip if possible? Notice that the Kanban board looks messed up with the Long Job Title.
![image](https://user-images.githubusercontent.com/19904513/101340337-7cbda880-3877-11eb-90d3-2f174ff06335.png)

**Comment by m1chalkubiak** [comment]
Hi @BDavydov  Just to be clear what do You exactly mean by "in the Jobs section"?
Are You referring to Jobs section on User management site?
If so, the length of the string that can fit here depends on the width of the screen, but assuming some standard width, we can assume that 22 characters would fit here.
Is this the limit we would like to implement?
<img width="455" alt="2020-12-7 o 12 32 40" src="https://user-images.githubusercontent.com/24941866/101346109-62d89180-3888-11eb-8719-6702f20c15d7.png">

While in most cases displaying a tooltip with an extended version of the string works well, here we are talking about a property that appears in many select lists or other tooltips. Also in the case of Kanban board, as this entire module uses an external library, the customization options are partially limited. However, I will try to do my best to add them here.

**Comment by carmenfan** [comment]
@m1chalkubiak 

I think we should just limit the job character length to a sensible number that we are sure we can display on all the places we display job name

**Comment by carmenfan** [comment]
Auto-populated revision name should truncate to the max character length.

At the moment if you upload a model with a file name that has more than 20 characters, it'll just populate it with the error message automatically popping up:
![image](https://user-images.githubusercontent.com/11945337/101347890-a4fed480-3882-11eb-89c4-cb7e64068969.png)

We should truncate the string to 20 characters instead.

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak
> 
> I think we should just limit the job character length to a sensible number that we are sure we can display on all the places we display job name

@carmenfan As for the technical side of displaying it, I think these 22 characters are a pretty safe limit. However, I have doubts from the business point of view whether it will not limit application users the freedom of adding more extensive positions.

**Comment by mosment3DRepo** [comment]
@m1chalkubiak following a conversation with Carmen can we do the following

- limit input of Job title to 50 chars
- increase limit of revision name to 50 chars

In most instances this should negatively affect UI, but in case where it does please truncate the middle of the text in both cases

**Comment by m1chalkubiak** [comment]
> ### Description
> It would be great if our Views Card an options menu as per other feature cards. Ideally, it should include at least the following:
> 
> * Delete All
> * Sort By Name
> 
> ### Pictures/ Gifs of the error
> ![image](https://user-images.githubusercontent.com/19904513/100114003-d9c56180-2e68-11eb-8df3-92118e378040.png)

Hi @BDavydov 
I looked at this yesterday and it seems to me that the only challenge here is the `Delete All` option, as long as we have this option in two other panels, it has support in the form of an appropriate endpoint in the case of the group panel and the appropriate method in UnityUtil in the case of measurement panel. As for the viewpoints, I only have an endpoint for removing a single entry. Of course, theoretically, I could run this in a loop for each viewpoint on the list, but I think we will all agree that this is not the way we would like to solve such a problem.
In view of the above, I would suggest moving this particular point to a separate issue and dealing with it later.

If you agree with this, I would create an issue and add the changes that I have done so far.

**Comment by mosment3DRepo** [comment]
@m1chalkubiak agreed, lets ignore the Delete All option for now

**Comment by m1chalkubiak** [comment]
@BDavydov @mosment3DRepo In regards to two items from the bug list, I added comments about the problem with reproducing the reported problems. Could you please take a look at this and let me know if the bugs still exist and possibly provide more details so I can recreate them?
https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-737134762
https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-737901235

**Comment by mosment3DRepo** [comment]
@m1chalkubiak I'm happy to leave those 2 if they are unable to be replicated. It would imply that they are edge cases

**Comment by m1chalkubiak** [comment]
Sure @mosment3DRepo 

> * [ ]  [Increase revision name limit to 50 on the backend/API](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-739973466)

@carmenfan  What do we do with this one? It would require the help of someone from you. If this change on the BE side would be added, we could then create a PR, as I believe everything else seems to be covered.

**Comment by carmenfan** [comment]
> Sure @mosment3DRepo
> 
> > * [ ]   [Increase revision name limit to 50 on the backend/API](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-739973466)
> 
> @carmenfan What do we do with this one? It would require the help of someone from you. If this change on the BE side would be added, we could then create a PR, as I believe everything else seems to be covered.

@m1chalkubiak can you just tweak the number quickly? it's in `backend/models/history.js`:
![image](https://user-images.githubusercontent.com/11945337/102095098-08f14200-3e1b-11eb-92d1-b291e1ad3493.png)
