### ISSUE TITLE
Support for updating and deleting model in Chat Events

### ISSUE THREAD

**Issue by m1chalkubiak** [3drepo/3drepo.io#2343]
### Description

Adding ChatEvents for updating and deleting models.
It should be based on `ChatEvent.newModel` as this is how event about creating a new model is handled right now

### Goals

- [ ] [FE] Teamspace is updated as soon as the event about updating the model contained in it arrives
- [ ] [FE] Teamspace is updated as soon as the event about deleting the model contained in it arrives

### Tasks

- [ ] [BE] Events about updating of the model is send by ChatEvent
- [ ] [BE] Events about deleting of the model is send by ChatEvent

**Comment by carmenfan** [comment]
Closing as v5 would revamp the whole thing
