### ISSUE TITLE
4D UI Tweaks (Work In Progress - Do not delete)

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2348]
Based on initial public feedback of the 4D Sequence feature there is some initial UI tweaks

### Tasks

- [ ] When loading the next frame, do not replace the activity list with the loading icon
- [ ] Add options to allow playback by activity sequence
- [ ] Include 4D playback data in model cache
- [ ] Remove "Unnamed Sequence" from Sequence card
- [ ] Change default calendar date behaviour
