### ISSUE TITLE
Upgrade material-ui

### ISSUE THREAD

**Issue by m1chalkubiak** [3drepo/3drepo.io#2362]
### Description
Upgrade version of material-ui library to the 4.x.x 

### Tasks
- [x] Support for forwardRef in all needed components
  - [x] `textField.component` refactor 
- [x] Update material-ui to latest version
- [x] Use Fab component instead of Button with "fab" variant
- [x] Adjust styles on login & sign-up pages
- [x] Review dashboard pages
  - [x] Align displaying of select list
  - [x] Align displaying of Tabs
  - [x] Incorrect background color during editing ticket title
  - [x] Checkboxes in User management page stopped working
  - [x] Broken styles in profile/user menu
- [x] Review model viewer components
  - [x] Expandable details in panels stopped working
  - [x] Fix react devtools warnings
  - [ ] Use new `@material-ui/pickers` instead of deprecated `material-ui-pickers`

**Comment by m1chalkubiak** [comment]
Hi @carmenfan, I would like to inform You, that I near finishing work on this issue, the last main thing that left is the non-working expandable functionality in issues and risks panels. It looks that with the new version of `material-ui` it needs to be implemented slightly differently, therefore I started refactoring it.

During working on this issue I discover that we are using a different deprecated package - `material-ui-pickers`, it throws some additional errors in the console with the new version of `material-ui`, however, it seems to work currently for now. Therefore, I would suggest moving updating (or in fact changing this library) to another issue.
