### ISSUE TITLE
Remove Mongoose - invoice

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2379]
### Description

Adding the Groups feature into 3D Repo, allowing the user to create/edit/delete groups

### Goals
- [x] Remove mongose for invoice

### Tasks
- [x] Remove mongose for invoice
- [x] update test for invoice
- [x] add new tests if necessary
