### ISSUE TITLE
Improve health checking and graceful termination in Kubernetes environment

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2380]
### Description
Adding some endpoints to establish if the system is ready for requests will improve behaviour under kubernetes and ensure requests aren't routed to containers that aren't ready yet.

We should also receive the Kubernetes shutdown and termination commands more gracefully.

https://github.com/CloudNativeJS/cloud-health-connect 

### Goals 

Add the following endpoints for the ability of kubernetes to self monitor.
- [ ] /live
- [ ] /ready
- [ ] /health

### Tasks

- [ ] evaluate https://github.com/CloudNativeJS/cloud-health-connect
- [ ] add the endpoints
- [ ] ensure clean stop on SIGINT

**Comment by keifgwinn** [comment]
cloud-health-connect seems abandoned at the moment, https://github.com/gajus/lightship is another possibility.

**Comment by keifgwinn** [comment]
https://github.com/godaddy/terminus is another option
