### ISSUE TITLE
3D Repo New User > Intercom API request

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2393]
### Description
When a new user is added to 3D Repo, rather than send an email with the details we want to push the data to intercom, where the customer success team can better manage customer specific campaigns

### Goals

- [x] Create a new user entry on Intercom database after a Sign Up (via API)
- [x] Stop sending 3D Repo new user email currently sent sales@3drepo.org
- [x] Stop sending the 'Welcome to 3D Repo' email to users (this will be handled by intercom)

### Tasks

TBD by dev team

### Related Resources

[Intercom Contact creation API docs](https://developers.intercom.com/intercom-api-reference/reference#create-contact
)

JSON body of request:
> { 
"role": "user", 
"external_id": "Username", 
"email": "example@3drepo.com", 
"name": "Jane Doe", 
"signed_up_at": 1571069751,
"custom_attributes": { 
    "company": “3D Repo”, 
    "subscribed": true
    } 
}

For access token please speak to @BDavydov 

Coda doc: [More context on Coda](https://coda.io/d/3D-Repo-Features_d5c0Qp25r6f/API-Automations_su2D8#_luyId)

**Comment by carmenfan** [comment]
@mosment3DRepo @keifgwinn does dev run on the same intercom account?

Just thinking if we need to have a flag to not send this if it's not production, otherwise it may start tainting the contacts there

**Comment by keifgwinn** [comment]
Yes, we only have one intercom account and it's set for that at the moment.
It's possible to have dev intercom set ups under the account as well I saw,
but I've not investigated that properly

**Comment by keifgwinn** [comment]
https://www.intercom.com/help/en/articles/188-create-a-test-workspace-in-intercom

**Comment by BDavydov** [comment]
@carmenfan On Intercom you can review user's **Recent page views** however, for every entry, it contains the following: https://www.3drepo.io/dashboard/teamspaces I know that personally, I have visited a number of pages such as user management and several models.
![image](https://user-images.githubusercontent.com/19904513/106435895-58430e80-646b-11eb-802f-0892a4c15915.png)
When I got in touch with their support team to understand how the system works and what may be an issue I got the following answer: 
**1.**
_First of all, is your website a Single Page App (SPA)?
If your website is a single page application SPA - characterized by very few page refreshes (i.e. content is swapped out on the client-side but no page refresh happens) and lots of asynchronous JavaScript - you'll need to integrate Intercom in a slightly different way. Including the intercom, JavaScript library file in your HTML head element and making a few extra JS calls will allow you to do this.
Check out the documentation on how to [integrate Intercom in an SPA](https://www.intercom.com/help/en/articles/170-integrate-intercom-in-a-single-page-app) for complete details._ 

**2.**
_For some extra content, with an SPA you'll need to make sure you're only installing the Messenger using that method, and if you wanted to track the different URLs someone has been on, you'll need to call the update method every time.
The update call is limited to 10 times per user/per page without getting throttled! If you do exceed that, you'll be allowed to call ('Update') once in 30 minutes. It's worth mentioning too that a page refresh or reload will reset this. This discourages folks from bombarding us with Intercom('update'); calls needlessly. We recommend instead updating only in places where there is a user data change sent to Intercom that could trigger an Auto Message._

Would you be able to assist me with this?

**Comment by carmenfan** [comment]
> Would you be able to assist me with this?

We are a single page app. I guess @sanmont3drepo  can look into calling the intercom update when we change the routes. But it does sound like we'd exceed the 10 times per page if we just blindly do this So you might want to pick and choose.

**Comment by sanmont3drepo** [comment]
The intercom  config properties for the backend has been changed and grouped under intercom here:

https://github.com/3drepo/3drepo.io/blob/e283cdef426f453bb06eda048ff79a616beddbe2/config/config_sample.js#L122-L126
