### ISSUE TITLE
Synchro v3 - Front end enhancements

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2401]
### Description
A series of (mostly) front end changes on the Synchro feature.

### Goals
Click on the links to see the details:
- [x] [Play sequence in frame intervals](https://github.com/3drepo/3drepo.io/issues/2401#issuecomment-762338273)
- [x] [Move the loading icon to somewhere else](https://github.com/3drepo/3drepo.io/issues/2401#issuecomment-762340709)
- [x] [Ability to rename a sequence](https://github.com/3drepo/3drepo.io/issues/2401#issuecomment-762379088)
- [x] [Modify Date Picker defaults](https://github.com/3drepo/3drepo.io/issues/2401#issuecomment-762389501)
- [x] [Cache state data in indexeddb](https://github.com/3drepo/3drepo.io/issues/2401#issuecomment-762387035)
- [x] [Add a legend](https://github.com/3drepo/3drepo.io/issues/2401#issuecomment-762748315)

### Tasks
- [x] Use new @material-ui/pickers instead of deprecated material-ui-pickers
### Related Resources
Coda doc: https://coda.io/d/3D-Repo-Features_d5c0Qp25r6f/4D-v3_suIVb#Synchro-4D-v3_tud5j

**Comment by carmenfan** [comment]
### Play Sequence in frame intervals

#### Description
At the moment, the user can only play/skip in time intervals (hours, days, months, year). We want to add support to add frame intervals, so the user can see changes within the sequence without the constraint.

#### Task:
- [ ] Add `frame(s)` as one of the available drop down options on `Step interval`
![image](https://user-images.githubusercontent.com/11945337/104937700-fd5ae300-59a5-11eb-87b0-3b56e134f183.png)
- [ ] When Step interval is set to `frame(s)`:
    - [ ]  the prev/next button should go to the date of the previous/next frame.
    - [ ] If the sequence is playing, it should jump to the next available frame on every tick.

**Comment by carmenfan** [comment]
### Move the loading icon to somewhere else

#### Description
When the card is waiting on current state information, currently we do not show the activity list, as that is being occupied by the loading icon. The activity list is already ready to be displayed.

#### Task
Move the loading icon to the left of the `Full Activity List` toggle and show the current list of activities whilst we are waiting for the state
![image](https://user-images.githubusercontent.com/11945337/104938367-e4066680-59a6-11eb-9937-b0aaacbcc431.png)

**Comment by carmenfan** [comment]
### Ability to rename a sequence
#### Description
Sequences coming from Synchro tends to be unnamed, allow the user to modify the name of the Sequence in the UI to better describe what the sequence is trying to show.

#### Task
**Frontend:**
    - Add the Sequence name onto the Sequence details panel 
    - If the user is collaborator or above, allow the user to edit the name: (similar input boxes as issues/risks description)
![image](https://user-images.githubusercontent.com/11945337/104945784-1d43d400-59b1-11eb-9d4c-29376018bf8f.png)


**Backend:**
    - Add route to allow renaming a sequence

**Comment by carmenfan** [comment]
### Cache state data in indexeddb

#### Description
In 3D Repo, we have an option in the viewer settings to cache 3D Models. If enabled, this will store asset bundles in indexeddb, this is handled within the Unity game.
![image](https://user-images.githubusercontent.com/11945337/104946615-46b12f80-59b2-11eb-8814-bed6e70cb985.png)

As frame state information can also get large and they never change, we would like to also store these files in indexeddb if this option is enabled in the settings.

There may be more things we would like to store in the future, so it would be good if the interaction with index db is generic and created as a service that is utilised by the sequence operations.

#### Task
- [ ] Create a data caching service on the front end
- [ ] If `Model Caching` is enabled:
    - [ ] Store a copy of frame state in indexeddb every time we fetch a frame state from the API.
    - [ ] If there is a local copy of framestate, take it from indexeddb instead of fetching the data.

#### Naming Considerations
For the assetbundle, we store them as `<teamspace.modelID_bundleID.unity3d>`. So maybe we should do something similar here.

**Comment by carmenfan** [comment]
### Modify Date Picker defaults

#### Description
In Risks/Issues, there is a sequencing tab to describe whether the issue /risk is only valid within a certain timeframe within a sequence. If those fields are currently empty, it will default to the current date/time:
![image](https://user-images.githubusercontent.com/11945337/104947571-dc998a00-59b3-11eb-843b-0441547a7673.png)

Considering the sequence could've happened in the past/future, the currently real life date isn't very helpful. We would like to change the defaults to reflect closer to what the sequence timeframe is.

#### Task:
- If there is currently an active sequence loaded in the sequence tab, and:
    - the sequence start date is empty

**Comment by carmenfan** [comment]
### Add a legend
Allow user to configure a legend for the sequence they're currently viewing. If the user is of collaborator or above, they should be able to edit/remove/add entries on the legend. The colour blotch should be 

NOTE: more UI information will be added later
![image](https://user-images.githubusercontent.com/11945337/105021087-0bf5d880-5a40-11eb-8316-768edc7fb0e5.png)

**Comment by carmenfan** [comment]
@m1chalkubiak  sequence name update API is updated in this branch: https://github.com/3drepo/3drepo.io/issues/2431

**Comment by m1chalkubiak** [comment]
> ### Move the loading icon to somewhere else
> #### Description
> When the card is waiting on current state information, currently we do not show the activity list, as that is being occupied by the loading icon. The activity list is already ready to be displayed.
> 
> #### Task
> Move the loading icon to the left of the `Full Activity List` toggle and show the current list of activities whilst we are waiting for the state

Hi @carmenfan 
As it was discussed at the meeting, I tried to fit an additional loader somewhere, I added another switch to make it clearer how this interface can finally look like.
<img width="365" alt="Zrzut ekranu 2021-02-4 o 09 59 37" src="https://user-images.githubusercontent.com/24941866/106869450-3dbd9f00-66d0-11eb-8feb-44e3e2f1ed0d.png">

Please let me know what you think about it.

**Comment by m1chalkubiak** [comment]
@carmenfan From what I understand, work on the API for the legend functionality is not ready yet, so I would like to propose an additional task that we could do as part of this issue. I wrote about it while updating the `material-ui` library. There is some deprecated package that we are using - `material-ui-pickers`.  We could replace it with the currently suggested `@material-ui/pickers`, of course, in this case, the sequence panel would not be the only place affected by these changes, therefore I leave the decision to You.

**Comment by carmenfan** [comment]
> <img alt="Zrzut ekranu 2021-02-4 o 09 59 37" width="365" src="https://user-images.githubusercontent.com/24941866/106869450-3dbd9f00-66d0-11eb-8feb-44e3e2f1ed0d.png">
> 
> Please let me know what you think about it.

@m1chalkubiak 
I think that looks fine, taggin @mosment3DRepo incase he has anything to add.



> @carmenfan From what I understand, work on the API for the legend functionality is not ready yet, so I would like to propose an additional task that we could do as part of this issue. I wrote about it while updating the `material-ui` library. There is some deprecated package that we are using - `material-ui-pickers`. We could replace it with the currently suggested `@material-ui/pickers`, of course, in this case, the sequence panel would not be the only place affected by these changes, therefore I leave the decision to You.

@m1chalkubiak  sure, i think that makes sense

**Comment by mosment3DRepo** [comment]
Looks good @m1chalkubiak 

@carmenfan can we have the legend API be linked to the model rather than the revision to avoid people having to redo it each time they upload a revision

**Comment by carmenfan** [comment]
> @carmenfan can we have the legend API be linked to the model rather than the revision to avoid people having to redo it each time they upload a revision

As discussed  in chat we'll leave this as is as it is pegged against a particular sequence which may be revision agnostic. Instead we'll have a default legend for model.

@m1chalkubiak I've commited the routes for legends in #2431. there's a GET and a PUT. After a discussion with Matt, we also want to be able to set a default legend for sequences (similar to default viewpoint), but I've ran out of time to do this, and will do it later and update you with the scope. I will also add api documentation at a later stage... 😆 

GET example: 
![image](https://user-images.githubusercontent.com/11945337/106914527-01ecfe80-66fd-11eb-8303-52ade8e0d54a.png)

NOTE: if the sequence doesn't have a legend it will return `{}`. (it will automatically return you the default legend when the logic is there)

PUT example:
![image](https://user-images.githubusercontent.com/11945337/106914875-5abc9700-66fd-11eb-9aba-edc9be9cc3e2.png)


Any questions let me know!

**Comment by carmenfan** [comment]
@m1chalkubiak all done now.

**Default Legend**
Model settings endpoint now understands `defaultLegend`, to set a legend as the default legend of the model, just do an update on model settings with the sequence ID:
````json
{
    "defaultLegend": "b3c02824-84e6-45cd-9ede-774d55afe402"
}
````

There's also an endpoint to delete a legend (this is equivalent to resetting it to default) https://github.com/3drepo/3drepo.io/blob/4eddd99dc2e9905b880309de146bcb61319272e7/backend/routes/sequence.js#L349


If we can add a hamburger button to this panel and put the new functionalities in there that would be great (rough illustration):
![image](https://user-images.githubusercontent.com/11945337/107625138-c948aa00-6c53-11eb-9b70-56e56c3c1627.png)



**Panel height**
For the panel height, can we make it by default ~30% of the screen height, scrollable, and resizable?

**Comment by carmenfan** [comment]
@m1chalkubiak  found a bug with the legend:

![fds](https://user-images.githubusercontent.com/11945337/110147859-0e37aa80-7dd4-11eb-8035-06cfb98db379.gif)

If I try to alter the colour prior to saving the entry, it disappears.

Also the random colour it's generating when you add a new entry, can we set alpha to 1 by default? As you can see on the gif here, sometimes it looks like opacity can be 0

**Comment by mosment3DRepo** [comment]
Can we reduce the padding on the rows, similar to the image below. It would make it a bit clearer to display > 5 records in the window.

![image](https://user-images.githubusercontent.com/62879582/116056217-7177e780-a675-11eb-8c8a-f08670a3348e.png)

**Comment by carmenfan** [comment]
> Can we reduce the padding on the rows, similar to the image below. It would make it a bit clearer to display > 5 records in the window.
> 
> ![image](https://user-images.githubusercontent.com/62879582/116056217-7177e780-a675-11eb-8c8a-f08670a3348e.png)

moving this to #2440 since this is closed and #2440 is touching similar code
