### ISSUE TITLE
Add API support to rename a sequence, and sequence legend

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2431]
### Description
This is a supporting issue for the front end work done in #2401.
Splitting it up as we are about to do more backend work in synchro (which will build on this), so it might be better to have this separate to avoid issue dependencies.

### Goals
- [x] Be able to change the name of a sequence
- [x] Be able to add a legend for the sequence
- [x] Be able to fetch a legend for the sequence
- [x] Be able to alter the legend for the sequence
- [x] Be able to delete the legend for the sequence
- [x] Be able to set a legend as default

### Tasks
- [x] Add route to allow renaming a sequence
- [x] ensure character limit is respected
- [x] ensure permission restriction is respected
- [x] Endpoint to add/remove/get legend
- [x] model settings endpoint update to take in a default legend
- [x] add tests
    - [x] getting a legend where a sequence does not have one should return an empty legend (no default legend)
    - [x] getting a legend where a sequence has one should succeed
    - [x] setting a default legend should succeed
    - [x] getting a legend where the sequence does not have one should return the default legend
    - [x] removing the default legend should succeed
    - [x] getting a legend with an invalid sequence id should fail
    - [x] permissions check on read/write
- [x] API docs
