### ISSUE TITLE
4.13.0 Bug List

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2434]
### Bugs
- [x] [White page triggered by pasting criteria in search box](https://github.com/3drepo/3drepo.io/issues/2434#issuecomment-771816492)
- [x] [Updating a smart group throws status 400 ](https://github.com/3drepo/3drepo.io/issues/2434#issuecomment-772653404)
- [x] [Metadata search does not query numbers correctly](https://github.com/3drepo/3drepo.io/issues/2434#issuecomment-769147874)
- [x] [Cannot change avatar](https://github.com/3drepo/3drepo.io/issues/2434#issuecomment-769711900)
- [x] Only allow email search in user search
- [ ] [Isolate Button doesn't work](https://github.com/3drepo/3drepo.io/issues/2434#issuecomment-774976752)
- [ ] [Hiding an element stop other element selection](https://github.com/3drepo/3drepo.io/issues/2434#issuecomment-774977443)
- [ ] [View naming oddity](https://github.com/3drepo/3drepo.io/issues/2434#issuecomment-774979133)

**Comment by mosment3DRepo** [comment]
### Description
Metadata search does not query numbers correctly.

When the value is a number the API call for highlighting and the Copy Groups Logic button should use "EQUALS" instead of "IS"

### Steps to replicate
- Open any model
- In the BIM Card select a number value and hit the target icon to select similar elements
- Notice that the API call is using the "IS" argument and therefore returns a null
- No additional elements are highlighted

### Expected Behaviour
- Copy Group Logic button should use the EQUALS logic in the copied JSON object when the value is a number
- Select Similar Elements button should use the EQUALS logic in the API request when the value is a number

**Comment by Charence** [comment]
**Cannot change user avatar**

Problem: backend/routes/auth still using Mongoose function `user.save()`

**Comment by sanmont3drepo** [comment]
When a criteria copied from the BIM card is pasted in the search filter a white page error is triggered.

![whitepage](https://user-images.githubusercontent.com/42032433/106638483-d262b880-657b-11eb-9a3b-87a79262a339.gif)

**Comment by sanmont3drepo** [comment]
Updating a smart group using a number value triggers a 400 error

![image](https://user-images.githubusercontent.com/42032433/106779805-431ed900-663f-11eb-835b-127dd0d7e0a0.png)

**Comment by carmenfan** [comment]
Tagging this one in here.

Restrict user search from partial username search to full email search only

**Comment by mosment3DRepo** [comment]
### Isolate Button doesn't work

Highlighting elements and picking he isolate button from the toolbar does nothing

Same is true for Isolate when using the isolate groups button in the Groups card

### GIF

![Isolate](https://user-images.githubusercontent.com/62879582/107195710-9ac79680-69e9-11eb-87a8-2289499894e0.gif)

**Comment by mosment3DRepo** [comment]
### Hiding an element stop other element selection

If you select an element and hide it, it seems you can no longer select other elements in the model

### GIF

![Select](https://user-images.githubusercontent.com/62879582/107195821-c185cd00-69e9-11eb-9e37-a181bed1880a.gif)

**Comment by mosment3DRepo** [comment]
### View naming oddity

When naming a view, if you use the same first letter as an  existing View name, it will loose focus on the text box

### Steps

1. Name a view "Hello"
2. Create another view
3. Type the letter "H"
4. Notice the previous view "Hello" is now selected
5.  In some instances the camera moves to the previous view too

### GIF

![ViewName](https://user-images.githubusercontent.com/62879582/107196160-2b05db80-69ea-11eb-8892-73f3c7830818.gif)

**Comment by carmenfan** [comment]
@mosment3DRepo I'm going to move moving those issues to a separate issue as this branch has been merged

**Comment by BDavydov** [comment]
**Remove User window contains semicolon characters around the action buttons**

Try and remove a user from your teamspace. In the pop-up window you will notice the odd characters highlighted below:
![image](https://user-images.githubusercontent.com/19904513/107523893-1e7db080-6bad-11eb-92e3-149501d5259b.png)
