### ISSUE TITLE
3D Markup for issues/risks

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2439]
## Description
![image](https://user-images.githubusercontent.com/11945337/106634254-86157980-6577-11eb-8e4c-f901fb828f3f.png)
The ability to add measuring tool like shapes (lines, polygons) to issues and risks. Note: Volumes are not part of this task.

The idea is for them to behave like pins:
- By default, they should be visible when pins are visible, unlike overrides/highlights/visibility
- They should have their own toggle on/off option
- A single issue/risk can have multiple shapes 
- The shape tool should be reusing the same logic as measuring tool, it should essentially be the same, apart from it does not have the measurement label.

## Goals
- [x] User should be able to create/remove shapes when create a new issue
- [x] User should be able to create/remove shapes when editing an issue
- [ ] By default, the shapes should show if it satisfies the same condition to show its pin
- [ ] The User should be able to show/hide shapes by a toggle button in the risks/issues menu

## Specification details
<details>
    <summary> Specification Details</summary>

## UI Design 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/11945337/108068887-98ed7b00-705a-11eb-8021-11b85bd1cf3b.png)

## Technical specification
- This is associated with the issue, not the viewpoint, thus should live on the issue root like pin
- Complex shapes may end up with a lot of vertices, to avoid clogging up the issue storage, we should consider putting this in a separate collection (referencing the issue)
- This needs to be returned in issuesList api call.

#### Currently:
- React tells unity to enable measurement tool in a certain mode (point to point, raycast, surface area, polygonal etc
![image](https://user-images.githubusercontent.com/11945337/106644175-a991f180-6582-11eb-83be-2b8d484ab7ee.png)
- When a measurement has been established, unity go ahead and displays it 
- Unity then calls the callback method to tell react what it has measured, with the following schema:
````c#
        protected class Measurement
        {
            public string uuid;
            public Vector3[] positions;
            public float value;
            public Color color;
            public MeasurementType type;
        }
````
- UnityUtils also has API to remove a measurement referencing it's uuid.
- There is no way to tell Unity to add a measurement.

##### What needs to be done:
- We need to refactor the measuring tool to be able to draw shapes displaying the measurement part (probably split it out into a generic base class? and a measuring tool is a special version of this?). These needs to be distinguishable from the measuring tool measurements and should not display the labels when they are instantiated
- The callback function called by Unity to notify react should distinguish between proper measurements and these measurements.
- measuring calls should not affect the generic drawings (e.g. disable snapping, clear all measurements, enable/disable measuring, show XYZ)
- Support adding a non measuring tool measurements drawing from React to Unity through UnityUtils.

### Backend changes
- issue create/edit should support the user passing in a shape with payload as follows (or similar):
````js
{
    _id : LUUID("454ca060-32f8-11eb-acc7-17c494897eae"),
    shapes: [
        {
            position: [array of floats],
            color: string,
            type: 0 or 1,
            value
        }
     ]
}
````
- backend should process the shapes and store them outside of the issue json. This should be oblivious to the user and the endpoint should always piece it back into the issue result 
- ensure issuesList.json returns the shapes array

#### DB Schema
In issue and risks, add an extra root level key:
````js
// In <model id>.[issues|risks]
{
    _id : LUUID("454ca060-32f8-11eb-acc7-17c494897eae"),
    shapes: [/*uuid to shape*/]
}
//in <model id>.[issues|risks].shapes
{
    _id: uuid
    issue_id: uuid
    positions: [float]
    color: string //#aaaaaa
    type: int //0 for Distance, 1 for area
}
````
</details>

## Tasks
- [x] Isolate measurements list component
- [x] Add shapes tab
- [x] Show list of shapes in shape tab
- [x] Show add line and area buttons in shape tab
- [x] Add backend support for fetching shapes ?
- [x] Add backend support for adding shapes
- [x] Add backend tests for adding shapes
- [ ] Add backend support for removing shapes
- [ ] Add backend tests for removing shapes
- [ ] Add backend support for editing shapes (color, name)
- [ ] Add backend tests for editing shapes
- [ ] Add fetch shape support in frontend (risks)
- [ ] Add save shape support in frontend (risks)
- [ ] Add remove shape support in frontend (risks)
- [ ] Add edit shape support in frontend (risks)
- [ ] Add show and hide all shapes in menu in frontend (risks)
- [ ] Add sequence show/hide shapes criteria as with pins (risks)
- [ ] Apply all changes to issues also 

## Related Resources
https://coda.io/d/3D-Repo-Features_d5c0Qp25r6f/4D-v3_suIVb#_luK_K

**Comment by sebjf** [comment]
Hi @carmenfan, responding to your message on Teams :) ... 

The MeasureTool is currently made up of the MeasureTool component itself, and a number of subcomponents. The MeasureTool component handles all the UI and the toolbar, and the subcomponents actually implement the measurement modes. The MeasureTool component turns the subcomponents on and off as required.

The subcomponents receive UI through the MeasureTool component, then use the physics and viewer APIs to take the measurements, displaying them through different types of Gizmos.

When a measurement is started, a subcomponent instantiates a new Gizmo (Prefab) and keeps a reference to it, allowing the instance to be updated as the measurement changes (e.g. as the point-to-point endpoint is moved around). When the measurement is complete, the subcomponents drop the reference, leaving the gizmo in the scene graph.

The gizmos/prefabs are built from a number of components, and handle both the 2D and 3D drawing themselves. The one thing they don't do is handle any UI (apart from the delete button); i.e. they cannot update themselves.

Below is an image showing the top level GameObject of a PolygonGizmo, which is used to display a surface (by the MeasurePolyArea and MeasureSurfaceArea subcomponents).

![image](https://user-images.githubusercontent.com/5058369/106876841-1070f100-66d0-11eb-98e5-21c1d9cd8d39.png)

There are two types of gizmo: Distance and Polygon (under Assets/Measure/Prefabs). They have a few loose dependencies on the MeasureTool itself:

1. They keep a reference to the MeasureTool instance, but only to get the colour and display units
2. They both have a method, Commit(), which they expect to be called when they are 'finalised'. This moves them under the Measurements GameObject where they will sit until deleted, and issues the MeasurementAlert through the ExternCaller. 
3. They handle their own deletion, and this currently includes a call to ExternCaller::MeasurementRemoved().
4. They both subclass from the type MeasurementGizmo, though this is a very small class that effectively just holds the measurement Guid and name.

The reason the Commit() method is put in the Gizmos is simply to avoid duplicating the same code in each subcomponent.

We could repurpose the gizmos by breaking the dependencies by, for example,

1. Having the subcomponents initialise the Gizmos via a method in the MeasureTool component
2. Have the colour set up externally on instantiation
3. Create a new interface to provide display units that can be implemented by the MeasureTool and set on the Gizmo on instantiation
4. Add Events to the Commit and Delete methods to move the ExternCaller calls elsewhere.

One other thing the Gizmos don't do is save their state; they expect the MeasureTool to re-create them.
