### ISSUE TITLE
Custom sequences via the API (1) - Create Sequences

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2440]
## Description
Introduce the ability to add a sequence based on viewpoint schema via API. These sequences will be custom sequences that will be different to the Synchro sequences and are editable/removable. Instead of having states, they will utilise the viewpoint schema and animation transformations will not be supported.

## Goals
- [x] The user will be able to create a custom sequence for via the API.
- [x] The user will be able to remove a custom sequence via the API
- [x] The user will be able to edit a custom sequence via the API.
- [x] The user will be able to view sequences appropriate for the revision specified
- [x] Synchro sequences stay read only - the user should not be able to edit/remove a synchro sequence (other than changing the  sequence name, supported from #2431
- [x] The front end should be showing and interacting with customs the same way as synchro sequences

## Specification

<details>

### Backend
We need to add the following endpoints:
- HTTP POST to add a sequence
- HTTP DELETE to remove a sequence
- HTTP GET to fetch a specific sequence

We need to modify an existing endpoint:
- HTTP PATCH to edit a sequence
- HTTP GET to get a list of sequences

##### Make revision association optional
Unlike synchro sequences, these sequences may not necessary be pegged against a particular revision. (esp the ones who are associated with smart groups.) We want to make sure that revision Id is only stored if the user specified it in their data.

We should move all sequence endpoints to be ` /:teamspace/:modelId/sequences` instead of  `/:teamspace/:modelId/revision/[master/head|:revisionId]/sequences`.

In the GET request, allow the user to provide a query string. ie.:

`HTTP GET /:teamspace/:modelId/sequences?revId=:revId`

This should return all the timeless sequences, and any sequences that matches `revId`.

If no query string is provided, it should return every single sequence regardless of revision.

##### Make sequence list API return a summary instead
At the moment, the sequence list api `/:teamspace/:modelId/revision/[master/head|:revisionId]/sequences` returns the full document of the sequence. As it is likely that we will get more than 1 sequence per revision with this change. Similar to risk/issues, we want to make the sequence list api return a summary (everything apart from the frame details), and create a separate API to return the sequence details given a sequence Id

#### Add a sequence
Proposed route: `HTTP POST /:teamspace/:modelId/sequences`
payload:
````js
{
    name: string
    revId: string //optional
    frames: [
        {
             dateTime: number //timestamp
             viewpoint: {} or viewpointId: string //takes in a viewpoint like issues/risks, or an existing viewpointId.
        }
    ]
}
````
- Viewpoint data should be processed just like issues/risks, where highlighted objects etc are moved into a group instead.
- if the user submits a `viewpointId`, take a copy of the viewpoint data instead of taking the link (so if the viewpoint got removed, the sequence is intact.
- `INVALID_ARGUMENTS` if any of the viewpoints contain a transformation.
- `_id` should be automatically generated by the backend
- `rev_id` should only be stored if it's provided, if it is provided, ensure it is a valid revision
- `customSequence` set to true for all sequences created this way.

#### Editing a sequence
- There is already an API done in #2431 to support editing a sequence. Currently it only supports a `name` change, we should change it so that it also support updating the `frames` property.
- `SEQUENCE_READ_ONLY` if the user is trying to update a sequence where `customSequence` is not set to true.
- frames data should be processed in a similar manner to POST request.

#### Deleting a sequence
Proposed route: `HTTP DELETE /:teamspace/:modelId/sequences/sequenceId`
- this should clean up any group Ids that are only associated with the sequence

### Frontend
- For these sequences, viewpoint is replacing states, so the front end needs to be modified to understand it and processing them accordingly.

</details> 

## Tasks

- [x] Create sequence
  - [x] tests
- [x] Remove sequence
  - [x] tests
- [x] Edit sequence
  - [x] tests
- [x] Get sequence(s)
  - [x] tests
  - [x] backend
    - [x] deprecate old endpoints that require revision
  - [x] frontend
    - [x] use new GET endpoint
- [x] List sequences to retrieve summary only
  - [x] update tests
- [x] Synchro sequences read only
  - [x] tests
  - [x] backend
  - [x] frontend
- [x] Check frontend sequence interaction

## DB migration
See [PR](https://github.com/3drepo/3drepo.io/pull/2537#issue-595790494)

## Related Resources
https://coda.io/d/3D-Repo-Features_d5c0Qp25r6f/4D-v3_suIVb#_luYkt

**Comment by mosment3DRepo** [comment]
@carmenfan after testing another use case today I found that the "viewpointId" described isn't accepted and instead the key that is accepted is "viewId"
