### ISSUE TITLE
Custom sequences via the API (2) - Create Activities

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2441]
## Description
Following on from #2440 , once a custom sequence exists, the user should be able to add/edit activities within this sequence

## Goals
- [x] Be able to add activities to a sequence
- [x] Be able to edit an existing activity
- [x] Be able to remove an activity

## Specifications
<details>

### Activity Schema
The current activity schema is designed around the assumption that it's write once, read only after. Which may be difficult to replicate for this purpose. It consists of 2 different dataset:
1. Activity list - a json file stored as a blob that serves as a cache to the front end to display the activity list as a tree structure (note: this example does not have sub tasks, but it is possible)
![image](https://user-images.githubusercontent.com/11945337/106790559-a6166d00-664b-11eb-9e3d-8c20633caed4.png) 
2. Activities - Each activity is a separate entry within the database, consist of metadata, and resources it the activity is associated with: 
![image](https://user-images.githubusercontent.com/11945337/106790311-47e98a00-664b-11eb-9c04-b4c7fc1014cb.png)

keeping up with 2. is simple, as it is just a write to the database. But as 1 is just a blob file, writing it every time there's been an edit to any activity can be exhausting (especially the usually will most likely make multiple edits before a activity list read request is made.) So my proposal is that:
- When we create/update activity in a sequence, we remove the existing blob file for the activity list without generating a new one
- When there is a request to get the activity list, 
    - if blob file exists for this sequence, return the activity list
    - otherwise, generate it on the fly base on the activities within the database, store the newly generated data as a blob file

### Other things to note:
- activities should be removed if there is a request to remove the whole sequence
- Sequence imported from synchro (i.e. `customSequence` is not set to true) should remain read only and the user should not be able to add/edit/remove activities within them

#### To add an activity:
Proposed route: `HTTP POST /:teamspace/:modelId/:sequences/:sequenceId/activities`
Payload:
````js
{
    name: string
    startDate: timestamp
    endDate: timestamp
    resources: object //see "Activities Schema change for details
    parents; []  //array of parent activity ids. can be undefined. I think in our use case this will always be 1 or nothing.
    data: [
        //other metadata for this activity
       {
            key: string
            value: <dataType>
       }
    ]
}
````

- `startDate` and `endDate` doesn't exist in the current schema, but we should store it as we need to generate the activityList on the fly. Convert to ISO Date.
- `_id` should be generated by the backend (uuid)
- add a `sequence_id` property when stored in the database, so we can remove these activities if the user wishes to remove the sequence.
- User should not be allowed to do this action if the associated sequence does not have `customSequence` set to true.

#### To edit an activity
Proposed route: `HTTP PUT  /:teamspace/:modelId/:sequences/:sequenceId/activities/:activityId`
- See POST request, essentially the same.
- should throw error if `activityId` not found.

#### To delete an activity
Proposed route: `HTTP DELETE /:teamspace/:modelId/:sequences/:sequenceId/activities/:activityId`

##### Metadata key/value change
Notice the schema of activities has been changed from `data : { key: value }` to `data: [ {key: keyString, value: value}]`. This makes the keys indexable to future proof for any queries we may want to do. 

##### Resource array change
We want resource array to work more like groups. so instead of taking in an array of shared Ids, we'll allow rules in replacement of `shared_ids`. i.e. the resource array should either be

storing a list of shared_ids:
````js
{
  resources: {
    shared_ids: [array]
  }
  //...
}
````
or rules:
````js
{
  resources: {
    rules: [...] //Same schema as group
  }
}
````

This will require work on the following:
1. A db migration script to modify existing activities
2. bouncer changes so future synchro imports also follows the same schema
3. front end modification to understand this schema

</details>

## Tasks
- [x] Create activity in model
- [x] Add a create activity test 
- [x] Edit activity in model
- [x] Edit activity test 
- [x] Remove activity  in model
- [x] Remove activity test
- [x] Generate file from activities table
- [x] Modify get activities to generate a file and save it if none is there or to return the already available file
- [x] Add tests on get activities taking in consideration the deletion of the activities file when updated
- [x] Create migration script for the new schema 
- [x] Fill in apidocs

## Related Resources
https://coda.io/d/3D-Repo-Features_d5c0Qp25r6f/4D-v3_suIVb#_luYkt

**Comment by sanmont3drepo** [comment]
### Schema  changes
- **_parents_: []string** changed to  **_parent_: string**
