### ISSUE TITLE
Bug List 4.13.1

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2447]
### Bugs
- [x] [Isolate Button doesn't work](https://github.com/3drepo/3drepo.io/issues/2434#issuecomment-774976752)
- [x] [Hide an element stop other element selection](https://github.com/3drepo/3drepo.io/issues/2434#issuecomment-774977443)
- [x] [View naming oddity](https://github.com/3drepo/3drepo.io/issues/2434#issuecomment-774979133)
