### ISSUE TITLE
4.13.2 bug list

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2455]
### Bugs
- [x] [Total saved meshes should not be saved within the database](https://github.com/3drepo/3drepo.io/issues/2455#issuecomment-775886167)
- [x] [Handle missing teamspaces](https://github.com/3drepo/3drepo.io/issues/2455#issuecomment-775894974)
- [x] [Treatment suggestions get white screen](https://github.com/3drepo/3drepo.io/issues/2443)

**Comment by carmenfan** [comment]
**Normal groups with IFC guids are returning empty object arrays instead of shared_ids**

Toy project imports have groups entry like the following:
![image](https://user-images.githubusercontent.com/11945337/107359343-798ba680-6acc-11eb-80de-65f9010e027a.png)


It looks like it's not being doing the IFC conversion correctly and is returning with this: 
![image](https://user-images.githubusercontent.com/11945337/107359441-958f4800-6acc-11eb-952f-45196042866f.png)


NOTE: can we also add a test for groups with IFC guids are returning correctly?

**Comment by carmenfan** [comment]
**Rectangular select is selecting some random object that is not instead the selection area**

Notice how an object within the building is being highlighted
![fds](https://user-images.githubusercontent.com/11945337/107360333-ae4c2d80-6acd-11eb-8f0b-a4c191c99172.gif)

**Comment by carmenfan** [comment]
**Total saved meshes should not be saved within the database**

When you save a group, it's currently saving some front end values with it:
![image](https://user-images.githubusercontent.com/11945337/107360552-03883f00-6ace-11eb-8500-55e0d2224b22.png)

**Comment by Charence** [comment]
**Error handling for deleted teamspaces**

![Screenshot 2021-02-09 at 12 07 08](https://user-images.githubusercontent.com/1438332/107362210-6084f480-6ad0-11eb-9ded-139d0eb776d8.png)
