### ISSUE TITLE
M6 Pen Test - Rate Limiting

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2460]
### Description

This is to test nginx based rate limiting, no actual IO code changing but best to get up a separate issue on the test lab.

### Goals

- [x] mitigate DDos with max connections
- [x] one client has a max requests per second
- [ ] rate limit a client if a large number of errors start occurring

### Tasks

- [x] test nginx.ingress.kubernetes.io/limit-connections
- [x] test limit-rps
- [x] test limit-rpm
- [ ] work out if possible with opensource nginx or requires commercial.

**Comment by keifgwinn** [comment]
rate limiting in place and under testing
