### ISSUE TITLE
4.13.3 Bug List

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2462]
### Bugs
- [x] [Clicking on Issues Comments does not open the proper Viewpoint](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-777551536) (CF)
- [x] [Erroneous dialog when you try to save an issue](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-777610194) (S)
- [x] [Issues & Risks not updated on chat server if card is closed](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-778098735) (C)
- [x] [Presenter Mode viewer cannot place pins or highlight objects](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-778100314) 
- [x] [Bim card selection is on multi select mode by default](https://github.com/3drepo/3drepo.io/issues/2470)(CF)
- [x] Update Kanban board subscriptions on model change
- [x] [Location input field can be picked from the drop-down options but doesn't save or show after clicking on the Save button.](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-778294886)

### UI Oddities
- [x] [ Remove User window contains semicolon characters around the action buttons](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-776754552) (S)
- [x] [Previous View mode is still active](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-776784840) (C)
- [x] [Card symbol oddity](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-776788564) (S)
- [x] [Create Report Endpoint broken for Issues & Risks](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-776837687) (C)
- [x] [Orthographic view loads as perspective](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-776922829) (C)
- [x] [Compare Card text comes out of the box & Updated toggle UI??](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-776941221) (S)
- [x] [Instant Clash feature is enabled when you have a target model only](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-777408990) (S)
- [x] [Presenter Mode support article URL link needs updating](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-777480740) (C)
- [x] [Presenter mode issue and risk save button doesn't disable](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-778102061)

### Others
- [x] [Remove automatic folder deletion code upon import success](https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-779299603)

**Comment by mosment3DRepo** [comment]
**Remove User window contains semicolon characters around the action buttons**

Try and remove a user from your teamspace. In the pop-up window you will notice the odd characters highlighted below:
![image](https://user-images.githubusercontent.com/19904513/107523893-1e7db080-6bad-11eb-92e3-149501d5259b.png)

**Comment by BDavydov** [comment]
**Previous View mode is still active**
It says Perspective but shows Orthographic

Steps to replicate:

- Open any model and change the view mode to Orthographic
- Click on the back to Teamspaces icon (top right)
- Open another/the same model
- View mode looks like orthographic, but it says perspective in the toolbar

**GIF**
![View Mode](https://user-images.githubusercontent.com/19904513/107530314-a961a980-6bb3-11eb-9dc6-abbd736df353.gif)

**Comment by miadibe** [comment]
**GIS Card** 
Strange UI white rectangle when opening GIS card near 'Settings'. Appears for all map tiles styles. Disappears when clicking once then going back. 
![Bug02](https://user-images.githubusercontent.com/56918163/107530664-02c9d880-6bb4-11eb-899e-48cf24812d21.gif)

**Comment by mosment3DRepo** [comment]
**Create Report Endpoint broken for Issues & Risks**

Creating a report for either issues or risks leads to a Mongo Error

**Steps**
1. Create a risk
2. Run report

![image](https://user-images.githubusercontent.com/62879582/107539775-35c49a00-6bbd-11eb-942d-2367d2fe8a83.png)

**Comment by BDavydov** [comment]
**Orthographic view loads as perspective**

Steps to replicate:

- Create & save a view using the orthographic mode
- Open 3D Repo in another tab
- In the new tab load the same model with a newly created view (orthographic)
- The perspective mode is ON. In the Views Card click on the same view once again (updates to orthographic)

**GIF**
![Orthographic view](https://user-images.githubusercontent.com/19904513/107555208-cbb4f080-6bce-11eb-96af-01697adaa987.gif)

**Comment by BDavydov** [comment]
WIP

**Compare Card text comes out of the box & Updated toggle UI??**

![Compare Card](https://user-images.githubusercontent.com/19904513/107558625-eb4e1800-6bd2-11eb-95e5-8008ba05b429.png)

@mosment3DRepo is this UI update?

**Comment by carmenfan** [comment]
@BDavydov This is most likely due to us upgrading material UI. A lot of the formatting went out of whack and had to be tweaked manually one by one. (this is the same deal with the random ; in the pop ups)

**Comment by BDavydov** [comment]
**Instant Clash feature is enabled when you have a target model only**

Users shouldn't be able to activate the Instant Clash feature until both Base & Target models selected.
Currently, you can activate them by selection just target models. Next questions from users would be "Why there are no clashes & what's the difference between Target & Base". 

**GIF**
![Instant Clash](https://user-images.githubusercontent.com/19904513/107635107-84783f80-6c62-11eb-9d57-191b2a7067b7.gif)

**Comment by BDavydov** [comment]
**Presenter Mode support article URL link needs updating**

Since we have a new help centre for 3drepo.io users. We need to update the link for _Read more..._ in the presenter mode window.
This is the link it must have: https://help.3drepo.com/en/articles/4894459-presenter-mode

![image](https://user-images.githubusercontent.com/19904513/107646376-cd83c000-6c71-11eb-99d6-27ca1a801eb2.png)

**Comment by BDavydov** [comment]
**Presenter Mode doesn't work. It says "The Presentation does not exist"**

Presentation code: **BTuLk**
![image](https://user-images.githubusercontent.com/19904513/107647643-48010f80-6c73-11eb-8de0-4cc9488010bc.png)

Copy & Paste it to another web-browser (different User) get the following error:
![Presenter Mode](https://user-images.githubusercontent.com/19904513/107647767-6d8e1900-6c73-11eb-8988-3c3b0f2c9572.gif)

**Comment by miadibe** [comment]
**Clicking on Issues Comments does not open the proper Viewpoint**
1. Camera does not update to the correct angle or view when clicking on a markup as comment. Seems to incrementally rotate to the right on each click. 
2. Clicking on markups created in the Revit plugin (via image upload) make the model disappear from the viewer in 3D Repo

**GIF**
https://user-images.githubusercontent.com/56918163/107654478-9d8cea80-6c7a-11eb-9790-b0bf873a20da.mp4

**Comment by carmenfan** [comment]
@miadibe  clicking on the screenshot doesn't move the viewpoint, you gotta click on the comment (@mosment3DRepo fell into the same expectation a while back, see his issue here..)

The pin moving thing should've been fixed though when I fixed that issue though.... 😢

**Comment by carmenfan** [comment]
@miadibe 

> Clicking on markups created in the Revit plugin (via image upload) make the model disappear from the viewer in 3D Repo (see end of GIF)

Can we get a link to the model?

**Comment by miadibe** [comment]
> @miadibe
> 
> > Clicking on markups created in the Revit plugin (via image upload) make the model disappear from the viewer in 3D Repo (see end of GIF)
> 
> Can we get a link to the model?

https://www.dropbox.com/s/10ws2qubdbrvdfw/House%20with%20textures-Revit%202020.rvt?dl=0

**Comment by carmenfan** [comment]
> > @miadibe
> > > Clicking on markups created in the Revit plugin (via image upload) make the model disappear from the viewer in 3D Repo (see end of GIF)
> > 
> > 
> > Can we get a link to the model?
> 
> https://www.dropbox.com/s/10ws2qubdbrvdfw/House%20with%20textures-Revit%202020.rvt?dl=0

I mean a 3drepo link... 😆

**Comment by miadibe** [comment]
**Revit Issues Viewer: Any issue created in 3D Repo (with or without an added screenshot) opens on Revit with ENORMOUS line weights. Forces Revit to crash if not flicking the _Thin Lines_ button to disable lineweight**
We do not want the unrealistically thick lines exported/imported

**GIF**
GIF 1
![ezgif com-gif-maker (12)](https://user-images.githubusercontent.com/56918163/107657862-7be13280-6c7d-11eb-8449-2c5e0b028d64.gif)
GIF 2
![ezgif com-gif-maker (13)](https://user-images.githubusercontent.com/56918163/107658135-bd71dd80-6c7d-11eb-9f4d-3df89a0554f7.gif)

**Comment by miadibe** [comment]
> > > @miadibe
> > > > Clicking on markups created in the Revit plugin (via image upload) make the model disappear from the viewer in 3D Repo (see end of GIF)
> > > 
> > > 
> > > Can we get a link to the model?
> > 
> > 
> > https://www.dropbox.com/s/10ws2qubdbrvdfw/House%20with%20textures-Revit%202020.rvt?dl=0
> 
> I mean a 3drepo link... 😆

https://staging.dev.3drepo.io/viewer/mia_dibe/1fec4df0-6ba8-11eb-acb5-f1237edef157 :D

**Comment by miadibe** [comment]
**Navisworks Plugin**
After having Navisworks open for a while, icons disappear from the main ribbon.

**GIF**
![navisbug](https://user-images.githubusercontent.com/56918163/107659873-8d2b3e80-6c7f-11eb-9268-d07504bfb691.gif)

**Comment by BDavydov** [comment]
> **WIP**
> 
> **UNABLE TO RECREATE IT ATM**
> 
> **Presenter Mode doesn't work. It says "The Presentation does not exist"**
 
Unable to recreate this ATM. Seems to be working fine. Maybe it was a one-off issue

**Comment by BDavydov** [comment]
### Description

Open any model and start a presenter mode session. As a presenter, you can create issues. When you click Save Issue you get a warning message saying that "This will end the session for all users. Continue?". In reality, it doesn't end the session, but it's confusing and unexpected. This pop-up window appears when you Save Issues, Go Back to the list of Issues and Open an existing Issue.

- This is happening in: staging

### Steps to replicate
- Open any model
- Start a presenter mode session
- Open Issues Card
- Create a new Issue
- Click on the Save button (warning comes up)
- Go back to the list of issues (warning comes up)
- Open another issue (warning comes up)

### Current Behaviour
- Warning message comes up

### Expected Behaviour
- Shouldn't happen and allow users to communicate live & create issues without a problem

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/107664174-0c227600-6c84-11eb-83b2-3ac7a8de7a4c.png)
![image](https://user-images.githubusercontent.com/19904513/107664188-104e9380-6c84-11eb-9cd4-566d70f87e6c.png)

**Comment by miadibe** [comment]
**Model appears to import some white 2D lines of the Revit Section box in 3D Repo. This is only seen in some viewpoints when clicking on some issues.**
- Previously we couldn't see the white section cut in 3D Repo
- Are we importing this? If so, this is not consistent with the other viewpoints: some contain these lines while others don't.
- Discrepancy works for both issues created on Revit and in 3D Repo. (Issues No. 2 & 5 don't have the white section lines)

**Steps to replicate**
- Apply a section box to a model on Revit and push it to 3D Repo via plugin Publish with a 3D view called 3D Repo that contains the Section Box. 
- Create some issues in Revit and in 3D Repo and compare. 
Link to model: https://staging.dev.3drepo.io/viewer/mia_dibe/1fec4df0-6ba8-11eb-acb5-f1237edef157

**GIF**
![ezgif com-gif-maker (14)](https://user-images.githubusercontent.com/56918163/107666403-64f30e00-6c86-11eb-83a2-47c77e38b289.gif)

**Comment by carmenfan** [comment]
> **Navisworks Plugin**
> After having Navisworks open for a while, icons disappear from the main ribbon. But clicking on each and using them works fine.
> 
> **GIF**
> ![navisbug](https://user-images.githubusercontent.com/56918163/107659873-8d2b3e80-6c7f-11eb-9268-d07504bfb691.gif)

Moving this to plugins repo: https://github.com/3drepo/3drepoPlugin/issues/214

**Comment by miadibe** [comment]
**Revit Plugin, Issues Viewer: User cannot open comment screenshots created from Revit but can open comment screenshots created in 3D Repo **
Loading button but nothing happens

**GIF**
![ezgif com-gif-maker (15)](https://user-images.githubusercontent.com/56918163/107670322-87872600-6c8a-11eb-9589-3724c8a884fa.gif)

**Comment by mosment3DRepo** [comment]
### Issues & Risks not updated on chat server if card is closed

When an issue is raised or edited by one user, the other users only see the creation/edit live if they have the issues card open. If not it is missing until the page is refreshed

### Steps to replicate
- Open the same model with 2 users
- Both users open the issues card
- User 1 create an issue
- Notice user 2 can see issue
- User 2 close issues card
- User 1 create another new issue
- User 2 open issue card back up
- Notice User 2 cannot see issue

### Current Behaviour
- Chat server not updating

### Expected Behaviour
- All updates should be visible in all sessions regardless of what cards are open

### Pictures/ Gifs of the error
![Chatnotworking](https://user-images.githubusercontent.com/62879582/107754423-5ace1f80-6d19-11eb-86c6-ae7066a6f66f.gif)

**Comment by mosment3DRepo** [comment]
### Presenter Mode viewer cannot place pins or highlight objects

When joining a presented session the viewer cannot place pins or highlight objects when raising issues/risks

### Steps to replicate
- User 1 create presenter session
- User 2 join session
- User 2 create issue
- User 2 attempt to place pin
- User 2 attempt to select objects

### Current Behaviour
- No pin can be placed or objects selected

### Expected Behaviour
- All models should be highlighted

### Pictures/ Gifs of the error
![PinPlacement](https://user-images.githubusercontent.com/62879582/107754684-bd272000-6d19-11eb-8427-c36615798617.gif)

**Comment by mosment3DRepo** [comment]
### Presenter mode issue and risk save button doesn't disable
In presenter mode the Issue save button is not disabled immediately following an issue creation. This means that the user does not get a clear indication the issue has saved. If they click the issue save button again they get an error

### Steps to replicate
- Open a model and host a presenter session
- Raise an issue
- Save issue
- Notice the save button is still active
- Click the save button
- See error

### Current Behaviour
- Issue save button still active after saving

### Expected Behaviour
- Issue save button should be disabled unless changes are made to the issue, at which point it should become active again

### Pictures/ Gifs of the error
![Presentersave](https://user-images.githubusercontent.com/62879582/107755030-332b8700-6d1a-11eb-9a40-70622de0b722.gif)

**Comment by sanmont3drepo** [comment]
> **WIP**
> 
> **UNABLE TO RECREATE IT ATM**
> 
> **Presenter Mode doesn't work. It says "The Presentation does not exist"**
> 
> Presentation code: **BTuLk**
> ![image](https://user-images.githubusercontent.com/19904513/107647643-48010f80-6c73-11eb-8de0-4cc9488010bc.png)
> 
> Copy & Paste it to another web-browser (different User) get the following error:
> ![Presenter Mode](https://user-images.githubusercontent.com/19904513/107647767-6d8e1900-6c73-11eb-8988-3c3b0f2c9572.gif)

If you see the url bar its a completely different model

**Comment by miadibe** [comment]
### SafetiBase Create new Risk
Location input field can be picked from the drop-down options but doesn't save or show after clicking on the Save button. 

### Steps to replicate
Open a model
Open the SafetiBase Card
Create new risk
Fill in the information and pick an option from the available drop-down in the 'Location' field
Save the risk
Notice how 'Location' is still empty after the risk is created

### Current Behaviour
Location field empty after saving new risk
### Expected Behaviour
Whatever the user chose from the drop-down list under 'Location' should remain after saving the new created risk

### GIF of the error
![ezgif com-gif-maker (19)](https://user-images.githubusercontent.com/56918163/107793911-bc5cb100-6d4e-11eb-89f3-186735bc1edb.gif)

**Comment by carmenfan** [comment]
**Remove automatic folder deletion code upon import success**

Not a bug. Just sneaking this one in since it's a tiny task. @keifgwinn  will setup some automatic clean up on the efs queue folders, so we will remove the not very reliable file removal code from io that is triggering once a model has been uploaded

**Comment by sanmont3drepo** [comment]
> ### Presenter mode issue and risk save button doesn't disable
> In presenter mode the Issue save button is not disabled immediately following an issue creation. This means that the user does not get a clear indication the issue has saved. If they click the issue save button again they get an error
> 
> ### Steps to replicate
> * Open a model and host a presenter session
> * Raise an issue
> * Save issue
> * Notice the save button is still active
> * Click the save button
> * See error
> 
> ### Current Behaviour
> * Issue save button still active after saving
> 
> ### Expected Behaviour
> * Issue save button should be disabled unless changes are made to the issue, at which point it should become active again
> 
> ### Pictures/ Gifs of the error
> ![Presentersave](https://user-images.githubusercontent.com/62879582/107755030-332b8700-6d1a-11eb-9a40-70622de0b722.gif)

Couldnt reproduce it after I've fixed the problem with the wrong dialog when saving an issue https://github.com/3drepo/3drepo.io/issues/2462#issuecomment-777610194
