### ISSUE TITLE
Pentest M7 - wildcard certificates

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2468]
### Description

An issue raised on the pen test report was the use of wildcard SSL certificates on the platform.

We don't need wildcard when we can automatically register named certificates that match the config file.

### Goals
- [x] specify every name in use on the configuration

### Tasks
- [x] update helm chart ingress options
- [x] update azure pipeline
