### ISSUE TITLE
4.13.4 Bugs List

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2474]
**Bugs**

**UI Oddities**

- [x]  [Previous View mode is still active](https://github.com/3drepo/3drepo.io/issues/2474#issuecomment-780492387)
- [x] [New User search field contains Username suggestion](https://github.com/3drepo/3drepo.io/issues/2474#issuecomment-780527357)
- [x] [Verified users are now set with inactive: null instead of getting rid of the property](https://github.com/3drepo/3drepo.io/issues/2474#issuecomment-780632119)
- [x] [Opening Perspective view after Orthographic](https://github.com/3drepo/3drepo.io/issues/2474#issuecomment-780740961)
- [x] [Update helm version](https://github.com/3drepo/3drepo.io/issues/2474#issuecomment-781297847)
- [ ] Add an api to see optional flags that are flagged on the teamspace

**Comment by BDavydov** [comment]
**Previous View mode is still active**

It says Perspective but shows Orthographic

Steps to replicate:

- Open any model and change the view mode to Orthographic
- Click on the back to Teamspaces icon (top right)
- Open another/the same model
- View mode looks like orthographic, but it says perspective in the toolbar

**GIF**
![View Mode](https://user-images.githubusercontent.com/19904513/107530314-a961a980-6bb3-11eb-9dc6-abbd736df353.gif)

**Comment by BDavydov** [comment]
**Zoom extent view automatically when switching view modes**

When a user switches between Perspective or Orthographic mode it changes camera mode, thus resulting in either very zoomed-in view of the model or empty model space. Often a user is required to press the extent button. (90% of users get lost and don't realise that there is such function)

**Expected behaviour:**

For a much easier method of switching between view modes, activate that function automatically. 

- User clicks on the view mode
- View mode changes
- Extent function is triggered automatically without pressing on the icon
- View mode changes & user can see their model.

**GIF**
![view mode extent](https://user-images.githubusercontent.com/19904513/108199329-c0a11980-7114-11eb-834f-9405a0ee788b.gif)

**Comment by carmenfan** [comment]
> **Previous View mode is still active**
> 
> It says Perspective but shows Orthographic
> 
> Steps to replicate:
> 
> * Open any model and change the view mode to Orthographic
> * Click on the back to Teamspaces icon (top right)
> * Open another/the same model
> * View mode looks like orthographic, but it says perspective in the toolbar
> 
> **GIF**
> ![View Mode](https://user-images.githubusercontent.com/19904513/107530314-a961a980-6bb3-11eb-9dc6-abbd736df353.gif)

This only happens on models with default viewpoints, unity is only changing projection mode if it is defined, and perspective viewpoints don't always have the projection mode defined (esp the old ones).

Fixing this in unity issue https://github.com/3drepo/3drepounity/issues/347

**Comment by BDavydov** [comment]
**New User search field contains Username suggestion**

As of our latest security update, we no longer support user search by their username, it's a full email address only.
Please remove the **Username** and leave **Email address** only.
![image](https://user-images.githubusercontent.com/19904513/108205233-abc88400-711c-11eb-924f-c091d21d7580.png)

**Comment by carmenfan** [comment]
> **New User search field contains Username suggestion**
> 
> As of our latest security update, we no longer support user search by their username, it's a full email address only.
> Please remove the **Username** and leave **Email address** only.
> ![image](https://user-images.githubusercontent.com/19904513/108205233-abc88400-711c-11eb-924f-c091d21d7580.png)

The auto lookup is email only, but if you know someone's username you can still type it in. I don't think we should be changing this? @mosment3DRepo

**Comment by BDavydov** [comment]
> 
> The auto lookup is email only, but if you know someone's username you can still type it in. I don't think we should be changing this? @mosment3DRepo

I see, thanks. You can actually add someone by their user name. It's just that when I use email address it comes up with the drop-down menu. That wasn't the case for a username, so I assumed it doesn't work.
@carmenfan @mosment3DRepo
![image](https://user-images.githubusercontent.com/19904513/108206964-0367ef00-711f-11eb-888a-289cece07d07.png)
![image](https://user-images.githubusercontent.com/19904513/108207015-12e73800-711f-11eb-876b-bc70092ddce4.png)

**Comment by carmenfan** [comment]
> > The auto lookup is email only, but if you know someone's username you can still type it in. I don't think we should be changing this? @mosment3DRepo
> 
> I see, thanks. You can actually add someone by their user name. It's just that when I use email address it comes up with the drop-down menu. That wasn't the case for a username, so I assumed it doesn't work.
> @carmenfan @mosment3DRepo
> ![image](https://user-images.githubusercontent.com/19904513/108206964-0367ef00-711f-11eb-888a-289cece07d07.png)
> ![image](https://user-images.githubusercontent.com/19904513/108207015-12e73800-711f-11eb-876b-bc70092ddce4.png)

After chat with @mosment3DRepo , I've changed it so it also searches for the full username, so it should prompt you if you got it right.

Also added a 1s delay on trigger the search to avoid catching users that match a substring of the username

**Comment by carmenfan** [comment]
Verified users are now set with `inactive: null` instead of getting rid of the property

This breaks things like user search as we look for `{$exists: false}`, and null field is considered to exist

**Comment by BDavydov** [comment]
**Smart Groups Field drop-down menu**

If you accidentally/deliberately press on the Filters chip, it will update the Field value. However, the original drop-down menu is still there. Should just disappear, no?
![Smart Groups](https://user-images.githubusercontent.com/19904513/108242416-cd3d6600-7144-11eb-8a1e-81e435fc7e11.gif)

**Comment by BDavydov** [comment]
**Opening Perspective view form a teamspace doesn't work**

@carmenfan I am guessing it's similar behaviour to [this issue?](https://github.com/3drepo/3drepo.io/issues/2474#issuecomment-780507458)

Steps to replicate:
- Click on the Load model with... icon
- Select a saved view (Perthographic)
- Go back to Teamspaces
- Click on the Load model with... icon again
- Select a saved view (Perspective)

Notice how the view mode remains orthographic, even though you're loading a saved view with a Perspective view mode.

![Saved Views](https://user-images.githubusercontent.com/19904513/108247101-2065e780-714a-11eb-836c-24671cebd6ea.gif)

**Comment by carmenfan** [comment]
@BDavydov  this is exactly the same problem. it doesn't matter whether you're going through saved view or you have a default view. it goes through the same logic.

Ortho/perspective works fine if you're going into models without default views.

**Comment by BDavydov** [comment]
**Confusing logic for tree Search & Isolate**
Just want to make sure that the current logic we have is what it is supposed to do?
I got confused when the tree card did not isolate elements selected because I already have an isolated element in the viewer.

Steps to replicate:
- Open any federation
- Open the Tree Card
- Isolate a single element from the tree
- Search for similar elements in the tree
- Go to the options menu and click "Select All"
- In the same menu click on the "Isolate Selected" 
- Nothing happens

**GIF**

![Tree Isolation](https://user-images.githubusercontent.com/19904513/108333418-d4a65300-71c8-11eb-91e0-360eb763fcae.gif)

**Comment by carmenfan** [comment]
> **Confusing logic for tree Search & Isolate**
> Just want to make sure that the current logic we have is what it is supposed to do?
> I got confused when the tree card did not isolate elements selected because I already have an isolated element in the viewer.
> 
> Steps to replicate:
> 
> * Open any federation
> * Open the Tree Card
> * Isolate a single element from the tree
> * Search for similar elements in the tree
> * Go to the options menu and click "Select All"
> * In the same menu click on the "Isolate Selected"
> * Nothing happens
> 
> **GIF**
> 
> ![Tree Isolation](https://user-images.githubusercontent.com/19904513/108333418-d4a65300-71c8-11eb-91e0-360eb763fcae.gif)

Well the label says `isolate selected. Under 3drepo logic it's impossible to select elements that are hidden (just like when you're selecting from a tree, it ignores hidden elements) Unselected objects would not have been isolated so yes that would make sense.

**Comment by carmenfan** [comment]
> **Smart Groups Field drop-down menu**
> 
> If you accidentally/deliberately press on the Filters chip, it will update the Field value. However, the original drop-down menu is still there. Should just disappear, no?
> ![Smart Groups](https://user-images.githubusercontent.com/19904513/108242416-cd3d6600-7144-11eb-8a1e-81e435fc7e11.gif)

Moved this to its own separate issue(https://github.com/3drepo/3drepo.io/issues/2479) as this is reproducible in production and not mission critical.

**Comment by Charence** [comment]
Need to update helm version to 0.9.5 for azp deployment

**Comment by mosment3DRepo** [comment]
> **New User search field contains Username suggestion**
> 
> As of our latest security update, we no longer support user search by their username, it's a full email address only.
> Please remove the **Username** and leave **Email address** only.
> ![image](https://user-images.githubusercontent.com/19904513/108205233-abc88400-711c-11eb-924f-c091d21d7580.png)

@carmenfan username suggestion appears to be back on staging:

![image](https://user-images.githubusercontent.com/62879582/108531576-be82ba80-72ce-11eb-8f98-74444362ab9a.png)

**Comment by carmenfan** [comment]
> > **New User search field contains Username suggestion**
> > As of our latest security update, we no longer support user search by their username, it's a full email address only.
> > Please remove the **Username** and leave **Email address** only.
> > ![image](https://user-images.githubusercontent.com/19904513/108205233-abc88400-711c-11eb-924f-c091d21d7580.png)
> 
> @carmenfan username suggestion appears to be back on staging:
> 
> ![image](https://user-images.githubusercontent.com/62879582/108531576-be82ba80-72ce-11eb-8f98-74444362ab9a.png)

That's not suppose to be possible... 😢
