### ISSUE TITLE
Triger Zoom extent automatically when switching view modes

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2475]
### Description

When a user switches between Perspective or Orthographic mode it changes camera mode, thus resulting in either very zoomed-in view of the model or empty model space. Often a user is required to press the extent button. (90% of users get lost and don't realise that there is such function)

### Goals

For a much easier method of switching between view modes:
- [ ] Activate Extent function automatically
- [ ] Users can switch between modes without getting lost

### Tasks

- [ ] Triger Extent function automatically

### Related Resources

**Current Behaviour**
![view mode extent](https://user-images.githubusercontent.com/19904513/108199329-c0a11980-7114-11eb-834f-9405a0ee788b.gif)

###  @sanmont3drepo  edit
After changing camera types call the action from Home button in the toolbar
<img width="123" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/fb6beb3e-6cd6-4706-a11d-d0547305a29f">

**Comment by mosment3DRepo** [comment]
@carmenfan do we have a zoom extents function in UnityUtils? Because the current "Extents" function isn't really that, it's just return home

@BDavydov I think if there is no zoom extents function it might be annoying to have it reset the camera angle as well as the zoom

**Comment by carmenfan** [comment]
@mosment3DRepo functionality is in there inside unity game, but it's not really exposed (We only expose it as zoom to object, which we could technically use to get the same effect by passing all the objects, but it's quite excessive and much easier to just expose a zoom to bounding box function for it to call)

Or we could just code it inside unity to force a camera reset when we change view modes without needing react to do anything (in which case it would also effect embedded viewer, which is probably what we want anyway.)

**Comment by AsiteZane** [comment]
This is still an issue. Had it recently at the Sisk demo. Moved to "to discuss" as it may require a button/change to interface.

**Comment by AsiteZane** [comment]
Not proposing as a quick fix but certainly not a priority at this stage. Will need some consideration of how Sebastian could do this in due course - likely resolved by thinking about how the steps work in Orth view.

To go into scoping so it is redrafted to a proper ticket rather than a "quick fix" for zoom extents.

**Comment by AsiteZane** [comment]
@carmenfan - need to discuss a quick fix instead of scoping. Could we not repurpose the SetViewpoint command with type: orthographic using the default home view straight after the 'UseOrthographicProjection' command (i.e. when you click the orthoview icon).

Pointless having it on the nav bar if it doesn't work but also not worth exhausted unity efforts on this if it can be a quick fix.

**Comment by AsiteZane** [comment]
Discussion with Carmen, to call "resetcamera" when changing between perspective and orthographic. To release for 5.12, not a hotfix.
