### ISSUE TITLE
Add 'Chunking' to 3D Repo model upload

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2489]
### Description

Currently 3D Repo does not appear to support file 'chunking', This means that on integration platforms such as Microsoft Power Automate (also know as Logic Apps on Azure) any files >50MB fail as the platform uploads files in 50MB chunks. With chunking files up to 1GB can be supported on these platforms

Currently when chunking is attempted the response from the API is "The multipart content body cannot be null."

### Goals

- [x] Allow files to be uploaded >50MB on Microsoft Power Automate
- [ ] Better connect with Projectwise and Asite, who also have connectors on these platforms

### Tasks

Currently envisage 3 API endpoints to be required to handle this MS Logic App specific uploading.

1. We tell the server that we plan on starting an upload and we pass through the information that a regular 3drepo.io upload needs such as tag and description. We get a `corID` back in the response and we'll use this to keep track of which upload it is for the POST/PATCH requests from the logic app.
2. This is the upload initiation POST request mentioned in the Logic App documentation. A POST is sent with information about the size of the upload in the header. In response, you'll get a `Location`, which is the API for uploading the subsequent file chunks, and a desired chunk size. **NB: I believe Logic Apps should be handling this next chunk upload step automatically**
3. This last step should hopefully happen automatically. It is a PATCH for uploading individual model chunks. The response of each PATCH confirms the byte range uploaded and the desired chunk size for the next upload.

1) **`/:teamspace/:model/upload/ms-chunking`**
- [x] Initiate upload session with server and obtain Correlation ID (corID) to keep track of upload
- [x] Tests

Example:
```
POST /:teamspace/:model/upload/ms-chunking

body: {
  filename,
  tag,
  desc,
  importAnimation
}

response: {
  corID: <correlation ID for upload>
}

```

2) **`/:teamspace/:model/upload/ms-chunking/:corID`**
- [x] Upload request POST endpoint with an empty message in body. Request header includes: `x-ms-transfer-mode` and `x-ms-content-length`
  - [x] verify that `x-ms-transfer-mode` is `chunked`; we're not expecting anything other than `chunked` so it will throw an `INVALID_ARGUMENTS` error if this header is not as expected
  - [x] verify that `x-ms-content-length` is in the header and is a number, otherwise throw `INVALID_ARGUMENTS`
  - ~we (maybe) need to store this expected content length so we can recognise when we have received all expected chunks~
  - [x] need to calculate upload chunk size and know max chunk size for Logic Apps
  - [x] Respond with URL location for PATCH messages
  - [x] Tests

Example:
```
POST /:teamspace/:model/upload/ms-chunking/:corID

header: {
  x-ms-transfer-mode: "chunked",
  x-ms-content-length: 4096
}

response: {
  x-ms-chunk-size: 1024,
  Location: "https://<domain>/api/<teamspace>/<model>/upload/ms-chunking/<corID>"
}
```

3) **`/:teamspace/:model/upload/ms-chunking/:corID`**
- [x] Chunk file upload PATCH endpoint
  - [x] Saving of uploaded chunk ~(similar to existing multer file upload?)~
    - current implementation saves to `cn_queue.upload_dir`, which is the same as the existing multipart file upload
    - alternatively, it could be held in memory, but I think we might not want to do this due to the file sizes, especially if there's more than 1 upload
  - [x] Concatenate uploaded chunks
    - if we assume chunks are sequential (as stated in docs) then we can join files as they are uploaded
  - [x] Record/save the `Content-Range` uploaded
    - `Content-Range` is in the format `bytes=<start byte>-<end_byte>/<total bytes>`, e.g. `bytes=0-1023/10100`
    - so potentially if we assume chunks are uploaded sequentially (according to documentation it is), we could maybe get away with just checking if the current chunk is the last one based on the `end_byte + 1 = total_bytes`
  - [x] When all expected chunks received, continue with same post file upload processing as normal `upload` endpoint
  - [x] Tests

Example:
```
PATCH /:teamspace/:model/upload/ms-chunking/:corID

header: {
  file: <file chunk>,
  Content-Range: "bytes=0-1023/4096",
  Content-Type: <file type>,
  Content-Length: 1024
}

response: {
  Range: "bytes=0-1023",
  x-ms-chunk-size: 1024
}
```

### Related Resources

[Azure documentation on chunking](https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-handle-large-messages)

[HTTP specification relating to chunking](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.6.1)

**Comment by carmenfan** [comment]
Ok I did a bit of digging, and everything, including the nodejs codebase, just tells me nodejs enables chunking by default anyway, so it confuses the hell out of me.

And since it's a post request chunking should be initiated by the request header anyway (you're trying to send a file over in chunks not the server trying to send you something in chunks). Then tried a postman request with Transfer-Encoding: `chunked`  and it uploaded my model fine.

Reading further on that Azure documentation, It says this:
https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-handle-large-messages#upload-content-in-chunks

Which suggest it needs some very specific handshake to process chunking? this may mean we have to have an endpoint specifically for logic app for this

**Comment by mosment3DRepo** [comment]
How big was the model you tried?

**Comment by carmenfan** [comment]
> How big was the model you tried?

tiny, but it's irrelevant, I'm changing the transfer encoding so if it works it should work.

From the azure documentation it looks more like they don't actually support chunking as per the http protocol (at least for the situation when you want to send a file to an endpoint), they're implementing their own chunking by POST/PATCH requests.

I'm not 100% sure though, @Charence can dig deeper when he looks into this.

**Comment by Charence** [comment]
@mosment3DRepo Please point the demo logic app to https://issue-2489.dev.3drepo.io/
