### ISSUE TITLE
Update helm chart to latest

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2510]
### Description

Update helm chart to latest

### Goals

These are the things updated in this chart

- [x] updated config.js for correctly handling Terms
- [x] updated ingress for pentest
- [x] updated config for customLogins
- [x] updated config for legals

### Tasks

- [x] update helm chart to 0.10.6
