### ISSUE TITLE
2D lines milestone 4

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2536]
3drepo.io build for https://github.com/3drepo/3drepounity/issues/350

Also need extra work on:
- [ ] Enabling snap for pins
- [ ] check navigation is still sane (esp helicopter)
- [ ] function name changes for snapping enable/disable
