### ISSUE TITLE
add index on issue's createdAt

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2540]
### Description
the script to gen stats is running really slowly and getting memory overload. For now I have serialised it to make it run even more slowly, but does not run out of memory.

The slowness i believe is to do with mongo taking a long time to return the query on issues due to issue's createdAt timestamp is not indexed. If we can index this at model creation then it should make things run a lot faster.

### Goals
- [ ] when a user creats a model, index the issues collection (and risk too i guess!) by createdAt.
- [ ] we'd also want to add indices on existing models

### Tasks
- [ ] Index the issues collection at the point of creating the model
- [ ] create a script to loop through all existing models and generate indices on them.

**Comment by carmenfan** [comment]
also, we can probably let mongo do the grouping via an aggregate pipeline: https://docs.mongodb.com/manual/reference/operator/aggregation/month/

**Comment by carmenfan** [comment]
Won't fix, Issue is a dying feature
