### ISSUE TITLE
Add API to return Texture Maps

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#2571]
### Description
Add an API to return a texture by UID to support [textured SRCs for Unreal](https://github.com/3drepo/3drepoUnreal/issues/31)

### Goals
- [x] A new API (e.g. :model/textures/:uid) will return a texture map.
- [x] The API will support HTTP, returning a binary stream with the correct mime type
- [x] The API will work with the Unreal WebRequestManager.

### Tasks
- [x] Add a new route for the API
- [x] Add a new helper class similar to mesh
- [x] Ensure different texture types are supported correctly

### Related Resources
The API should return textures for any textured model. Minimal working textured models for development are available here: https://www.dropbox.com/sh/m3206ivyefukuz9/AADXiuDz8D3gOGyGzBwKduH6a?dl=0
