### ISSUE TITLE
Azure Pipeline Values Override on a Branch

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2573]
### Description

Occasionally we want to override the default values in the Azure pipelines in order to support custom bouncers or other such features. We want to be able to add additional -set commands to the helm package based on the branch.

### Goals

- [x] Defaults can be overridden on a per branch basis.
- [x] Some way to ensure that these don't always make their way up to staging, could require a review of pull requests. https://github.com/3drepo/3drepo.io/pull/2576

### Tasks

- [x] Work out how to add commands
- [x] Test
- [x] Discussion around pull requests

**Comment by keifgwinn** [comment]
https://github.com/3drepo/3drepo.io/pull/2576 covers ensuring it doesn't make changes further up the tree

**Comment by carmenfan** [comment]
@keifgwinn  this can close?

**Comment by keifgwinn** [comment]
Yes

--
Keif
