### ISSUE TITLE
Version 4.15.1 Issues List

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2612]
- <del> [Username starting with a number shows a warning message](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842134123) UI Oddity
- <del> [New accounts show 2GB Storage available, when it should be 100MB](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842229023)</del> - this is a devops config
- <del> [Some Teamspaces don't display profile pictures](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842239237) UI Oddity
- <del> [No indication as to how many characters are allowed in the model code field](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842371638) UI Oddity
- <del> [Long Model names are overlapping when creating/editing federations](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842388353) UI Oddity
- <del> [Long Model names are not visible in the revisions/model upload window](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842397056) UI Oddity
- <del> [Clip box behaviour with linear asset models & 2D Sheets/Drawings](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842417562)
- [x] [Issue forgets the camera position after the screenshot update. Only works after Ctrl + R](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842450730)
- <del> [PDF Report is missing screenshots and contains lines of code](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842587997)
- <del> [Unlimited Description Length for new Issues in Kanban Board](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842601685) UI Oddity
- <del> [Long attachment names break the comments layout](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842626917) UI Oddity
- <del> [Adding an image to the SafetiBase Risk messes up the drop-down input list](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842633009) UI Oddity
- [x] [Quoted images don't appear in SafetiBase comments](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842639776) UI Oddity
- <del> [Zoom In & Out doesn't work with a middle mouse button pressed](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-843276815) UI Oddity
- [x] [Activity List Search not working after one character](https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-844823375)

**Comment by BDavydov** [comment]
**Description**
New users can add numbers to their Usernames. Even though you can add numbers, they can't start Username with a number. We need to update our warning message if there is a limitation on our side.

**Steps to replicate:**

- Head over to the [Sign Up Page](https://staging.dev.3drepo.io/sign-up)
- Type in a Username containing numbers _(Works fine)_
- Type in a Username starting with a number _(Warning message)_ 

**Current Behaviour:**
- Warning Message

**Expected Behaviour:**
- Warning message to disappear
- Explain that a Username can't start with a number

**Pictures of the Error:**
![image](https://user-images.githubusercontent.com/19904513/118458779-fc875300-b6f2-11eb-9cda-cfcfd66b03b5.png)
![image](https://user-images.githubusercontent.com/19904513/118458812-0446f780-b6f3-11eb-8275-62d3b83e7937.png)

**Comment by BDavydov** [comment]
**Description**
The Billing page contains information for the space available. Currently, a new account displays 2GB, when I believe it should be 100MB as per our Free Account licensing.

**Steps to replicate:**

- Sign Up for a New Account on [Staging](https://staging.dev.3drepo.io/sign-up)
- Log into your new account
- Head over to the Billing Page

**Current Behaviour:**
- 2GB Storage available
- 
**Expected Behaviour:**
- 100MB Storage available

**Pictures of the Error:**
![image](https://user-images.githubusercontent.com/19904513/118478173-79bcc300-b707-11eb-8b2e-1a7bd4d62a24.png)

**Comment by carmenfan** [comment]
> **Description**
> The Billing page contains information for the space available. Currently, a new account displays 2GB, when I believe it should be 100MB as per our Free Account licensing.
> 
> **Steps to replicate:**
> 
> * Sign Up for a New Account on [Staging](https://staging.dev.3drepo.io/sign-up)
> * Log into your new account
> * Head over to the Billing Page
> 
> **Current Behaviour:**
> 
> * 2GB Storage available
> 
> **Expected Behaviour:**
> 
> * 100MB Storage available
> 
> **Pictures of the Error:**
> ![image](https://user-images.githubusercontent.com/19904513/118478173-79bcc300-b707-11eb-8b2e-1a7bd4d62a24.png)

this could be because we hiked the quota for basic account on dev... @keifgwinn  is that the case? what's the number on the config?

**Comment by BDavydov** [comment]
**Description**
I've been added to a teamspace and I can't see that Teamspace's profile picture.

**Steps to replicate:**

- Ask me to add you to Bodan_D Teamspace
- Refresh the Models & Federations window

**Current Behaviour:**
- Teamspace appears in the list, but not the profile picture

**Expected Behaviour:**
- See the profile picture of the teamspace

**Pictures of the Error:**
![image](https://user-images.githubusercontent.com/19904513/118479926-83dfc100-b709-11eb-8fe7-05c86499f9f1.png)

**Comment by BDavydov** [comment]
**Description**
There is no clear indication as to how many characters you are allowed in the Model Code field. It illustrates that it's limited to alphanumeric values, but then at some point the same warning comes up, even though you are using alpha numeric values only.
**Steps to replicate:**
- Head over to Staging
- Click on Add Model in any of the projects/teamspace
- Give it a name, units & type
- Start typing model code

**Current Behaviour:**
- No indication as to how many characters the model code is limited to

**Expected Behaviour:**
- Notify me when I exceed the character limit as per model name & tell me how much I am allowed to have

**Pictures of the Error:**
![image](https://user-images.githubusercontent.com/19904513/118505528-679d4d80-b724-11eb-82c2-9e069668bf48.png)

**Comment by BDavydov** [comment]
**Description**
Really long model names don't fit in the list of available or federated models.

**Steps to replicate:**
- Create a couple of models with really long names 80-120 characters
- Start creating a new federation

**Current Behaviour:**
- Model Names are overlapping

**Expected Behaviour:**
- Push the model names apart so that you can read them, instead they're fixed because of the selection boxes.

**Pictures of the Error:**
![image](https://user-images.githubusercontent.com/19904513/118508964-8e10b800-b727-11eb-9dd1-14111dd6446c.png)

**Comment by BDavydov** [comment]
**Description**
Long Model names don't fit in the model name bar

**Steps to replicate:**
- Create a model with a really long name 80-120 characters
- Click on the new model container to upload a model revision

**Current Behaviour:**
- Model Names are broken into 3 line text ( only the middle line is visible)

**Expected Behaviour:**
- Make the mode text go **Really long name...** if we want to keep the blue bar consistent size

**Pictures of the Error:**
![image](https://user-images.githubusercontent.com/19904513/118510690-1774ba00-b729-11eb-80f0-0b62cb153056.png)

**Comment by miadibe** [comment]
**Description**
Issues with Section box when Clip plane is activated. 

**Steps to replicate**
- Click on Clip button to activate Section box 
- Choose either Single clip or Box clip (both lead to the same issues)
- Zoom in/out of the model 
- Drag any clip plane 

**Current Behaviour**
- Issue 1: [Section box extent when activating Clip](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Section%20box%20extent%20on%20Clip%20activation.mp4?role=work) Clip box appears to already cut through the model (part of the model is blue) even if it doesn't
- Issue 2: [Disappearing section box](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Section%20box%20on%20clip%20plane%20move.mp4?role=work). Section box starts as a box but disappears when dragging/adjusting any clip plane to the model. 
- Issue 3: [Clip plane section cut on zoom](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Clip%20Plane%20Section%20cut%20on%20Zoom.mp4?role=work). Zooming in/out of the model with the mouse appears to gradually cut the model even without dragging clip planes. 

**Expected Behaviour**
- Clip box should not initially cut through the model (blue cutting objects) when first activated
- Clip box starts as a box around model and _remains_ a box (does not disappear) when dragging/adjusting any clip plane to the model
- Clip box should not cut through the model (blue cut) when zooming in/out of the model with mouse, only when dragging/adjusting specific clip planes

**Comment by carmenfan** [comment]
> **Description**
> Issues with Section box when Clip plane is activated.
> 
> **Steps to replicate**
> 
> * Click on Clip button to activate Section box
> * Choose either Single clip or Box clip (both lead to the same issues)
> * Zoom in/out of the model
> * Drag any clip plane
> 
> **Current Behaviour**
> 
> * Issue 1: [Section box extent when activating Clip](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Section%20box%20extent%20on%20Clip%20activation.mp4?role=work) Clip box appears to already cut through the model (part of the model is blue) even if it doesn't
> * Issue 2: [Disappearing section box](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Section%20box%20on%20clip%20plane%20move.mp4?role=work). Section box starts as a box but disappears when dragging/adjusting any clip plane to the model.
> * Issue 3: [Clip plane section cut on zoom](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Clip%20Plane%20Section%20cut%20on%20Zoom.mp4?role=work). Zooming in/out of the model with the mouse appears to gradually cut the model even without dragging clip planes.
> 
> **Expected Behaviour**
> 
> * Clip box should not initially cut through the model (blue cutting objects) when first activated
> * Clip box starts as a box around model and _remains_ a box (does not disappear) when dragging/adjusting any clip plane to the model
> * Clip box should not cut through the model (blue cut) when zooming in/out of the model with mouse, only when dragging/adjusting specific clip planes

You're testing with 2D Sheets, clipping on the 3rd dimension. They probably have a height of 0 as they are all flat.....

We can't expect a volumetric clipping plane to work in the axis that has no length. I feel like this is not a case we should consider right now it is pretty niche (since we can only import 2D from assimp/dgn? We should either disable clip plane on 2D sheet mode, or code in some logic to ignore the flattened dimension. (much easier to just do the former, unless there's really merit in clipping a sheet)

tagging @mosment3DRepo for considerations

**Comment by miadibe** [comment]
> > **Description**
> > Issues with Section box when Clip plane is activated.
> > **Steps to replicate**
> > 
> > * Click on Clip button to activate Section box
> > * Choose either Single clip or Box clip (both lead to the same issues)
> > * Zoom in/out of the model
> > * Drag any clip plane
> > 
> > **Current Behaviour**
> > 
> > * Issue 1: [Section box extent when activating Clip](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Section%20box%20extent%20on%20Clip%20activation.mp4?role=work) Clip box appears to already cut through the model (part of the model is blue) even if it doesn't
> > * Issue 2: [Disappearing section box](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Section%20box%20on%20clip%20plane%20move.mp4?role=work). Section box starts as a box but disappears when dragging/adjusting any clip plane to the model.
> > * Issue 3: [Clip plane section cut on zoom](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Clip%20Plane%20Section%20cut%20on%20Zoom.mp4?role=work). Zooming in/out of the model with the mouse appears to gradually cut the model even without dragging clip planes.
> > 
> > **Expected Behaviour**
> > 
> > * Clip box should not initially cut through the model (blue cutting objects) when first activated
> > * Clip box starts as a box around model and _remains_ a box (does not disappear) when dragging/adjusting any clip plane to the model
> > * Clip box should not cut through the model (blue cut) when zooming in/out of the model with mouse, only when dragging/adjusting specific clip planes
> 
> You're testing with 2D Sheets, clipping on the 3rd dimension. They probably have a height of 0 as they are all flat.....
> 
> We can't expect a volumetric clipping plane to work in the axis that has no length. I feel like this is not a case we should consider right now it is pretty niche (as of this release, we can only import 2D from assimp/dgn) We should either disable clip plane on 2D sheet mode, or code in some logic to ignore the flattened dimension. (much easier to just do the former, unless there's really merit in clipping a sheet)
> 
> tagging @mosment3DRepo for considerations

You'll find that it's not a 2D sheet though it has 2D lines. It has 3D Revit elements and in elevation no height of 0, but yes it is a long and linear model. 
![coast](https://user-images.githubusercontent.com/56918163/118516815-91f40880-b72e-11eb-9076-e15bde9a8a08.JPG)

**Comment by BDavydov** [comment]
**Description**
Updating the Issue screenshot without changing the camera position seems to make it look like it has lost camera position. It only works again when you do the hard refresh **Ctrl + R**

**Steps to replicate:**
- Create an Issue
- Go back to the issues list
- Open the last issue again
- Update its screenshot without updating the camera position
- Go back to the issues list & navigate away
- Click on the updated issue
- Camera does not change

**Current Behaviour:**
- Camera does not change after updating the issue screenshot in the session
- Only works when you do a **Ctrl + R**

**Expected Behaviour:**
- Go back to the original camera position if you reopen the same issue (after updating the screenshot

**Pictures of the Error:**
[Video](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Updating%20Issue%20Screenshot.mp4)

**Comment by BDavydov** [comment]
**Description**
PDF Report is broken. Contains a list of viewpoint updates + Issue Screenshots are missing.

**Steps to replicate:**
- Open any model on staging
- Create several issues
- Update a viewpoint for one of them
- Click on the options icon in the Issues Card
- Select Create PDF

**Current Behaviour:**
- The PDF report is a mess

**Expected Behaviour:**
- Not see the lines of code describing the viewpoint updates
- Contain Issue Screenshots

**Pictures of the Error:**
![image](https://user-images.githubusercontent.com/19904513/118548008-aeee0300-b751-11eb-9a35-ff706f2b3da5.png)

**Comment by BDavydov** [comment]
**Description**
New Issue in Kanban board doesn't show me a warning message for exceeding the 660 characters limit. As a result, I can write a novel, but when I click save, only half of it appears there.

**Steps to replicate:**
- Open the Kanban board
- Start Creating a new Issue
- Give it a really lone description 660+ characters
- Click on the Save button

**Current Behaviour:**
- Allows you to copy & paste the entire Wikipedia, but only shows a little after you save the issue

**Expected Behaviour:**
- Throw a character limit warning message as in the model viewer

**Pictures of the Error:**
[Video of the Error](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Long%20Description%20in%20Kanban%20Issue.mp4)


![image](https://user-images.githubusercontent.com/19904513/118550684-e27e5c80-b754-11eb-9b91-77a26ff6cfd7.png)

**Comment by BDavydov** [comment]
**Description**
No Character limit on Issue & Risk Attachments. Resulting in a broken comments section if you quote a resource with a very long name.

**Steps to replicate:**
- Open any model
- Create a new Issue/Risk
- Click on the Attachments tab
- Add a resource and give a really long title 300+ characters
- Now quote the resources in the comments section
- Add a new comment

**Current Behaviour:**
- Weird looking comments section

**Expected Behaviour:**
- Show a little bit of the title with ... or display a tooltip on hover

**Pictures of the Error:**
![image](https://user-images.githubusercontent.com/19904513/118554375-4571f280-b759-11eb-926c-f7447ba3c61e.png)

**Comment by BDavydov** [comment]
**Description**
SafetiBase input selection lists don't move with the card. It works as expected until I upload an image, then they're stuck in the middle of a screen.

**Steps to replicate:**
- Open [this Risks Kanban Board](https://staging.dev.3drepo.io/dashboard/board/risks/Bogdan_D/Q&A/691db810-97cc-11eb-b0d4-297881185407)
- Start Creating a new Risk
- Add a risk image
- Start selecting risk fields

**Current Behaviour:**
- Drop-down list is detached from the input field

**Expected Behaviour:**
- As it does when there is no Risk screenshot/image

**Pictures of the Error:**
Without an Image
![image](https://user-images.githubusercontent.com/19904513/118555074-22940e00-b75a-11eb-943f-ce105a8402d0.png)

With an Image
![image](https://user-images.githubusercontent.com/19904513/118555128-33dd1a80-b75a-11eb-99af-554b8e0d366b.png)

**Comment by BDavydov** [comment]
**Description**
Quoted images in SafetiBase comments do not display in both Model Viewer & Kanban Board

**Steps to replicate:**
- Open any model and create a Risk
- Add a comment to that risk with an image
- Quote the previous comment (including the image)
- Submit your quoted comment

**Current Behaviour:**
- Quoted comment image doesn't appear as per Issues

**Expected Behaviour:**
- See the quoted image as per Issues

**Pictures of the Error:**
Kanban Board
![image](https://user-images.githubusercontent.com/19904513/118556625-03967b80-b75c-11eb-8f9c-c8448e79b3ca.png)

Model Viewer
![image](https://user-images.githubusercontent.com/19904513/118556789-304a9300-b75c-11eb-8f56-4931d8cf4f29.png)

**Comment by keifgwinn** [comment]
> this could be because we hiked the quota for basic account on dev... @keifgwinn is that the case? what's the number on the config?

https://github.com/3drepo/DevOps/blob/31c03288c0f81e34505a2c9e9d5faae9bf8e2eb5/helm/3drepo-io/templates/configmap-config.yaml#L49

yes, dev has a higher quota now, but this will also get out to prod so we should update this to 100mb

**Comment by carmenfan** [comment]
> > this could be because we hiked the quota for basic account on dev... @keifgwinn is that the case? what's the number on the config?
> 
> https://github.com/3drepo/DevOps/blob/31c03288c0f81e34505a2c9e9d5faae9bf8e2eb5/helm/3drepo-io/templates/configmap-config.yaml#L49
> 
> yes, dev has a higher quota now, but this will also get out to prod so we should update this to 100mb

Ok i'll create a devops ticket!

**Comment by BDavydov** [comment]
**Description**
Updated turntable model navigation method is missing support for the middle mouse press zoom

**Steps to replicate:**
- Open any model
- Press on the middle mouse button
- Now drag your mouse Up & Down

**Current Behaviour:**
- Nothing is happening

**Expected Behaviour:**
- Expected the mouse to perform Zoom In & Out

**Pictures of the Error:**
![image](https://user-images.githubusercontent.com/19904513/118681043-2a55c000-b7f7-11eb-968c-005bb3135f86.png)

**Comment by carmenfan** [comment]
> **Description**
> Updated turntable model navigation method is missing support for the middle mouse press zoom
> 
> **Steps to replicate:**
> 
> * Open any model
> * Press on the middle mouse button
> * Now drag your mouse Up & Down
> 
> **Current Behaviour:**
> 
> * Nothing is happening
> 
> **Expected Behaviour:**
> 
> * Expected the mouse to perform Zoom In & Out
> 
> **Pictures of the Error:**
> ![image](https://user-images.githubusercontent.com/19904513/118681043-2a55c000-b7f7-11eb-968c-005bb3135f86.png)

@BDavydov works for me:
![sequence running](https://user-images.githubusercontent.com/11945337/118788693-f082c900-b88b-11eb-946e-d8ea4abb869e.gif)

Considering all we did was change the mouse button mapping if it's broken for a particular model it would be broken on prod for the same model.

**Comment by BDavydov** [comment]
@carmenfan the mouse button Zoom In & Out seems to not work for this particular model [Terminal](https://staging.dev.3drepo.io/viewer/Bogdan_D/1a94cf40-56cc-4491-8d49-c17f082f052a). Really odd :/

**Comment by carmenfan** [comment]
> @carmenfan the mouse button Zoom In & Out seems to not work for this particular model [Terminal](https://staging.dev.3drepo.io/viewer/Bogdan_D/1a94cf40-56cc-4491-8d49-c17f082f052a). Really odd :/

if it also doesn't work on right click button in production then we didn't introduce any bug... 😆 It'd be useful to find out.

**Comment by mosment3DRepo** [comment]
### Description
Activity List Search not working after one character

### Steps to replicate:

- Open [this model](https://staging.dev.3drepo.io/viewer/mosment3ddev/a207c830-b8c1-11eb-9d54-8d644d6ccdc2) or any 4D model
- Open the 4D Sequence
- Open the Full Activity List
- Review the activities then search for a term you know exists in the activity list eg. Excavation
- Notice the list is only filtered after the first character is typed, then it displays no results

### GIF

![Activity Search](https://user-images.githubusercontent.com/62879582/118940096-487f0580-b948-11eb-9e5e-cf2d83ace733.gif)

**Comment by mosment3DRepo** [comment]
QA v1 completed
