### ISSUE TITLE
Update helm chart to support https://github.com/3drepo/DevOps/issues/203

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2615]
### Description

I need to bump the helm chart used in DevOps to 0.10.14 to support configurable basic subscription settings.

### Goals

- [x] basic subscription configuration configurable.

### Tasks

- [x] Update helm chart
- [x] Updated deployment code
