### ISSUE TITLE
Category support in the BIM card

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2629]
### Description
At the moment we store the category information as a prefix to the metadata label, with `::` as the delimiter.

E.g. 
    `Classification::Source` is a metadata value for `Source`, that belongs in the `Classification category`

This results in metadata looking like a mess and hard for users to make sense of it. e.g. Bim card of a certain object in 3drepo
![image](https://user-images.githubusercontent.com/11945337/119841866-18ae9f80-befe-11eb-813b-d45512bce5ee.png)

When the same data presented in a different software:
![image](https://user-images.githubusercontent.com/11945337/119841766-02084880-befe-11eb-924e-c6ebcd828d3d.png)

### Goals
- [ ] **Introduce category grouping in the BIM data card.**
Key value needs to be looped through and split by the delimiter `::`, any keys that has the same categories should be grouped together for view. Note that the keys could nested categories, i.e. `1::2::3::key_a` should be placed inside category `1`, with a subcategory `2`, which has a sub category `3`. This would not be in the same grouping as `3::key_b`

The end result should look a bit like the measuring card:
![image](https://user-images.githubusercontent.com/11945337/119852826-8ca17580-bf07-11eb-9682-5e832c349881.png)

Note:
- we should collapse all categories by default
- Add a button on the `...` button to allow collapse all

- [ ] **Ensure filtering still works**
Filtering behaviour should be similar to filtering activity list:
    - if it matches a category, the entire category (plus children) should show
    - if it matches a sub category, the parent category + the sub category should show (but not the siblings unless they are also  matches)
    - If a metadata label matches, it should show the parent ancestor categories, but not the sibling metadata (unless they are also matches)
- [ ] **Ensure favourites still work**
    - If I favourited a metadata label of a certain category, it should show it on the favourite tab.
    - It should not show on the favourite tab if it matches the label , but under a different category.
- [ ] **Ensure Copy group filter button still work**
    - The copy group filter button should copy exactly what we get right now (i.e. with the original string value with categories.)
- [ ] **Select Element... button still work**
    - Select element with the same value should trigger a API request that sends the same payload as right now (i.e. with original string value with categories)

### Tasks
To be filled out by the developer
