### ISSUE TITLE
Element Colour Override not consistent across Views and Issues

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#2637]
<details>
<summary> Expand to see original post </summary>

### Description
Transparency and colour overrides with Smart Groups do not come through consistently when clicking on Issues and Views that contain these overrides. The camera position updates correctly but the overrides fail to save. This is happening in prod.io. Does it require a hotfix? @mosment3DRepo 

### Steps to replicate
- Open this model: [https://www.3drepo.io/viewer/PowerBIVisual/1099fb90-b329-11eb-87e0-f722fb2ce12b](url) 
- Create a view with colour override (you can use the Smart groups that are already created) and save it
- Create an issue that has a view with colour override and save it with the view as a screenshot
- Refresh the browser page and toggle between different views and issues in the list to see how colour and transparency overrides behave

### Current Behaviour
- **Issue no 1:** Clicking anywhere in space on the model viewer resets view and removes overrides 
- **Issue no 2:** Toggle between different views in the Views list: camera position updates but some coloured elements come through while others don't, 
- **Issue no 3:** Click on different issues in the Issues list and open them: camera position updates but some elements overrides are missing
- **Issue no 4:** Click on different views with colour overrides. Some elements are highlighted in yellow even if view doesn't contain a specific selection. 

### Expected Behaviour
1. Clicking anywhere in space should retain whatever colour/transparency overrides is set for the opened view and not make them disappear
2. Clicking on any Issue or View in the lists should retain all colour/transparency overrides
3. Clicking on any View with overrides should not select and highlight elements in yellow

### Pictures/ Gifs of the error
[https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos/Element%20colour%20overrides%201.mp4?role=work](url)
[https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Videos?preview=Element+colour+overrides+2.mp4](url)

</details>

**Bug list:**
- [ ] [Colour override's alpha values are cleared if you toggle between 2 views](https://github.com/3drepo/3drepo.io/issues/2637#issuecomment-856785906)
- [ ] [When you click on an issue, it's fetching the groups information but not applying it](https://github.com/3drepo/3drepo.io/issues/2637#issuecomment-856829804)
- [ ] [Similar colour override problems in views](https://github.com/3drepo/3drepo.io/issues/2637#issuecomment-856839773)
- [ ] [Colour overrides doesn't go away when you navigate outside of the issue](https://github.com/3drepo/3drepo.io/issues/2637#issuecomment-856843967)
- [ ] [Only one of the colour overrides are being applied when I have 3](https://github.com/3drepo/3drepo.io/issues/2637#issuecomment-856847853)
- [ ] [We may want to add a spinning wheel icon when the groups are loading?](https://github.com/3drepo/3drepo.io/issues/2637#issuecomment-856854767)

**Comment by carmenfan** [comment]
> Issue no 1: Clicking anywhere in space on the model viewer resets view and removes overrides

@miadibe from what I can tell, it doesn't. it resets highlights:
![aa](https://user-images.githubusercontent.com/11945337/121007310-cb49f200-c789-11eb-9bb6-bea9ff493c73.gif)

> Issue no 2: Toggle between different views in the Views list: camera position updates but some coloured elements come through while others don't,

I can't reproduce this

> Issue no 3: Click on different issues in the Issues list and open them: camera position updates but some elements overrides are missing

nor this.

> Issue no 4: Click on different views with colour overrides. Some elements are highlighted in yellow even if view doesn't contain a specific selection.

Highlights are stored as yellow in issues/risks. (I'm not sure if views ever preserved the colours, but probably not as we use the same functions) If we want this changed, this is a feature request.


Can you share the model?

**Comment by carmenfan** [comment]
**Colour override's alpha values are cleared if you toggle between 2 views that has the same colour overrides, if the view was updated in that particular session**

- Create 2 issues with that has with a colour override imposed on the same set of  semi transparent objects
![aa](https://user-images.githubusercontent.com/11945337/121196720-9eb8d780-c868-11eb-81be-13b692a7041a.gif)
- refresh the session.
- On one of the 2 issue, edit the viewpoint without actually changing anything (essentially re-save the same viewpoint)
![aa](https://user-images.githubusercontent.com/11945337/121196854-babc7900-c868-11eb-9b08-b77eb0a94a48.gif)
- on issue list, toggle between the 2 issues

**Current Behaviour**
The alpha values seems to reset to the original value on the issue that was updated in that current session
![aa](https://user-images.githubusercontent.com/11945337/121196986-d7f14780-c868-11eb-8168-05566bc61c43.gif)


**Expected Behaviour**
The alpha value should remain the override value

**Comment by carmenfan** [comment]
**When you click on an issue, it's fetching the groups information but not applying it**

1. click on an issue with colour overrides

**Current Behaviour**
You can see from the network tab that it has fetched the groups, but it's not displaying them. It displays them when you click on the issue again.

![aa](https://user-images.githubusercontent.com/11945337/121206274-3cfc6b80-c870-11eb-8645-cb39d927b12e.gif)


**Expected Behaviour**
It should display them as soon as it has arrived

**Comment by carmenfan** [comment]
**Similar colour override problems in views**

https://github.com/3drepo/3drepo.io/issues/2637#issuecomment-856829804 and https://github.com/3drepo/3drepo.io/issues/2637#issuecomment-856785906 are also happening in views

**Comment by carmenfan** [comment]
**Colour overrides doesn't go away when you navigate outside of the issue**

1. create an issue with multiple colour overrides, like this one has 3: 
![image](https://user-images.githubusercontent.com/11945337/121207058-e3487100-c870-11eb-8805-df149a61a39d.png)
2. refresh the page while you're in issue details

**Current behaviour**
When I leave issue details, only one of the colour overrides reset (notice the teal and dark green overrides are there regardless of which issue i click)

**Comment by carmenfan** [comment]
**Only one of the colour overrides are being applied when I have 3**

Using the same issue as https://github.com/3drepo/3drepo.io/issues/2637#issuecomment-856843967

ignoring the [first click problem](https://github.com/3drepo/3drepo.io/issues/2637#issuecomment-856829804), notice how only 1 of the colour overrides show up:
![aa](https://user-images.githubusercontent.com/11945337/121209858-1d1a7700-c873-11eb-9886-6a8e0cec3917.gif)

**Comment by carmenfan** [comment]
**We may want to add a spinning wheel icon when the groups are loading?**

May worth adding a spinning wheel icon on the lists to indicate to the user that the groups are loading when they click on issues/risks/views, so if the group is taking a while to come back, it doesn't look like it's broken.

Def a nice to have, let me know if it's gonna be a lot of effort.
