### ISSUE TITLE
Update node version to 14.0.0

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2639]
### Description
Update node version to 14.0.0 for being up to date.

### Goals
- [x] Update node version to 14.0.0 

### Tasks
- [x] Update node version
- [x] Udate packages that are needed to be updated for 14.0
- [x] Make sure everything works on backend
- [x] Make sure everything works on frontend

**Comment by keifgwinn** [comment]
I thought we were going to Node v14 @carmenfan  ?

**Comment by carmenfan** [comment]
current is v16, if we are upgrading we may as well go all the way to the latest to make it last longer...

Would it be a problem?

**Comment by carmenfan** [comment]
@keifgwinn @sanmont3drepo actually it's not adviced to use Current...

`Production applications should only use Active LTS or Maintenance LTS releases.`

So yea, we should probably use v14

**Comment by keifgwinn** [comment]
It's frustrating as 16 will be LTS from 2021-10-26 so we could do it again in November to take advantage of longest period.

**Comment by carmenfan** [comment]
We could postpone it.. 😆

**Comment by keifgwinn** [comment]
We're out of support on NodeJS 10 now, so your call.

**Comment by carmenfan** [comment]
let's just upgrade to v14... it's good for another 2 years anyway.

that would be inline with 3D Send which will make life a bit easier
