### ISSUE TITLE
Add PixelStreaming Viewer Support to UnityUtil

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#2662]
### Description
The UnityUtil class is used to initialise a Unity viewer. This should be updated to allow initialising an Unreal PixelStreaming viewer instead.

The implementation of the PixelStreaming viewer will be in a separate file, delivered from the signalling server that is used to make the connection to a PixelStreaming process. It is assumed that this source will be loaded before the command to UnityUtil is given.

### Goals
- [x] The existing UnityUtil API is supported
- [x] When the viewer is set to Unreal, a PixelStreaming instance is established that operates as Unity does

### Tasks
- [x] Implement a method to initialise a PixelStreaming [viewer](https://github.com/3drepo/3drepoUnreal/issues/68)

### Related Resources
Unreal Issue: https://github.com/3drepo/3drepoUnreal/issues/40
Viewer Issue: https://github.com/3drepo/3drepoUnreal/issues/68
PlanBase Issue: https://github.com/3drepo/PlanBase/issues/9

**Comment by sebjf** [comment]
Hi @carmenfan,

For the UnityUtil API, I have added `loadUnreal` so there are now two functions, `loadUnity` and `loadUnreal`. `loadUnity` takes a URI where the Unity static files are found. `loadUnreal` needs the address of the matchmaking server.

Since the arguments to these are slightly different, do you want me to add general `setViewer`/`loadViewer` methods, or just assume the application (e.g. PlanBase) will call the appropriate load method with its specific arguments?

**Comment by carmenfan** [comment]
@sebjf It's quite difficult to imagine without the full story. So do what you think it's best and I can take a look at code review 😆

**Comment by carmenfan** [comment]
same as #2650
