### ISSUE TITLE
Optional logging as JSON messages without formatting

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2685]
### Description

It would be useful to have the config option to output logging as json for easier parsing by other systems

### Goals

- [x] JSON logging optional

### Tasks

- [x] A new config option
- [x] switch on the logger
