### ISSUE TITLE
Revamping - Restructure folders 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2686]
### Description
The objectives of revamping of 3drepo.io are multiple; provide with a more usable visually appealing experience for the user and to lay the groundwork for making 3drepo easier to develop. In order to do this folder restructuring and a new framework with additional design rules are to be provided.  

### Goals
- [x] Restructuring of folders

### Tasks
- [x] Move folders around 
- [x] Upgrade packages
- [x] Update webpack config to build  the new folder structure
- [x] Update webpack config to add aliases for folders to provide cleaner imports

### Related Resources
Dashboard scoping:
https://docs.google.com/document/d/1Kla4KIoo6Naw092LuZz-AKSz5kmKU1j9Zi3uY8bQBBQ/edit?usp=sharing

**Comment by carmenfan** [comment]
@sanmont3drepo  can we also add a new linter for the v5 folder and alter the command to run old linter on v4 and new linter on v5?
