### ISSUE TITLE
Revamping - New framework

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2688]
### Description
The goal of the new framework is to provide a more developer friendly way of coding the frontend. This issue depends on #2686. 

### Goals
- [x] Have a new framework for integrating react and redux using hooks in a maner that is easier to use
- [x] Have to separate lint options for v4 and v5
- [x] Have a new testing framework for sagas
- [x] Have a new route /v5 for the new dashboard with a dummy page

### Tasks
- [x] Add service files for wrapping selectors to provide an easier redux integration
- [x] Add service files for wrapping actions to provide an easier redux integration
- [x] Add sagas testing  package
- [x] Update webpack config to support the new saga tests. Because we are testing the typescript source code, we need to write the tests in typescript and transpile them
- [x] Modify package.json to add a test sagas script
- [x] Add a saga testing example
- [x] Add a dummy layout page for v5
- [x] Add a route that shows the dummy layout
- [x] Add a command to package json to run linter for v4 and v5

### Related Resources
Dashboard scoping:
https://docs.google.com/document/d/1Kla4KIoo6Naw092LuZz-AKSz5kmKU1j9Zi3uY8bQBBQ/edit?usp=sharing
