### ISSUE TITLE
Revamping - Containers page

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2689]
### Description
The new containers page is being though as a replacement for models. That means provide the functionality of listing all the models (with each of the revisions) of a project, have a filtering system where you can filter containers by name,  upload new models and delete old containers. It should also provide a way of navigating to other resources like issues/risks/enter the model, etc. As this is the first revamped page it provides the groundwork for the rest of the dashboard pages.

### Goals
- [ ] User should be able to see list all the containers 
- [ ] Users should be able to filter out these containers
- [ ] Users should be able to sort the containers by container name, container code, category and last updated
- [ ] Users should be able to create new containers
- [ ] Users should be able to upload to containers
- [ ] When clicking a row in the list of containers more details are shown; if the container is empty an upload button is shown if its not a list of revisions are shown.
- [ ] To the right of the row an ellipsis menu button is shown that displays the options 'Load model in 3d viewer', 'Upload new revision', 'View issues', 'View risks', 'View revisions', 'Download' , 'Permissions', 'Share', 'Settings',  'Delete'

### Tasks
- [ ]  set up a route for /v5/{teamspace}/{projectid}
- [ ] Create template for a row using the controls for rows 
- [ ] Set up the filtering system using selectors
- [ ] Create popup for new container
- [ ] Create popup for upload file
- [ ] Create blank state page

### Related Resources
MockUp : 

No containers for the project:
https://www.figma.com/proto/jEWzypoRCqj64bMiE2UosN/Teamspace-designs?node-id=1%3A36&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=46%3A37

Container list with details showning an empty container and the ellipsis menu showing:
https://www.figma.com/proto/jEWzypoRCqj64bMiE2UosN/Teamspace-designs?node-id=148%3A1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=46%3A37

Container list with details showing in a container with multiple revisions:
https://www.figma.com/proto/jEWzypoRCqj64bMiE2UosN/Teamspace-designs?node-id=65%3A2098&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=46%3A37

Creating a new container popup form:
https://www.figma.com/proto/jEWzypoRCqj64bMiE2UosN/Teamspace-designs?node-id=151%3A303&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=46%3A37

Stages of uploading a model to a container:
https://www.figma.com/proto/jEWzypoRCqj64bMiE2UosN/Teamspace-designs?node-id=90%3A68&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=46%3A37

https://www.figma.com/proto/jEWzypoRCqj64bMiE2UosN/Teamspace-designs?node-id=140%3A65&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=46%3A37

https://www.figma.com/proto/jEWzypoRCqj64bMiE2UosN/Teamspace-designs?node-id=140%3A399&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=46%3A37

https://www.figma.com/proto/jEWzypoRCqj64bMiE2UosN/Teamspace-designs?node-id=95%3A1243&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=46%3A37

**Comment by carmenfan** [comment]
TODO:

- make clear on the hamburger button menus - what should be implemented, what should be ignored (or just go to an endpoint?)
- ask george re feedback (are we using toast? how should it be visualised etc)
