### ISSUE TITLE
Revamping  - Basic layout page  

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2690]
### Description
Create the basic layout page.  This is the basic layout that will be shown when accessing  /v5 pages. The specific page content and teamspace/project/ (on the left) select tab (on the right) will be dependant on the route the user is in.

### Goals
- [ ] Apply new design
- [ ] Users can select the current project  using the top left  and that will create a redirection
- [ ] Users can change the tab on the right and that will create a redirection
- [ ] Mockup buttons for notifications and user profile will be shown on the top right (although the icon of the profile will show the correct user avatar)

### Tasks
- [ ] Create routes for /v5/{teamspace}/{projectid}/federations  and /v5/{teamspace}/{projectid}/containers
- [ ] Create the tabs component that will redirect to these two routes
- [ ] Create the breadcrumb component 
- [ ] Create api for fetching basic teamspaces information . /api/teamspaces Will return the teamspaces/projects of the loggedin user
- [ ] Create saga/redux conterpart for storing the teamspaces information
- [ ] Set the general layout following the design

### Related Resources
![basic layout](https://user-images.githubusercontent.com/42032433/125653672-c5cafa4d-1a88-44d5-8bf3-c053d4946cc1.png)

https://www.figma.com/file/jEWzypoRCqj64bMiE2UosN/Teamspace-designs?node-id=0%3A1

**Comment by carmenfan** [comment]
@carmenfan  just thinking about the endpoints

> Create routes for /v5/{teamspace}/{projectid}/federations and /v5/{teamspace}/{projectid}/containers

If we consider the breadcrumb will also give the multi tier effect, i'm just wondering if we should make this more distinct.

E.g. imagine when we've done the full implementation, we have 3 tiers of breadcrumbs:
1. teamspace
2. teamspace/project
3. teamspace/project/federation

I think naturally we want to reflect this on the route? i.e. if I'm on the settings tab on teamspace, under the suggestion above, we probably want something like this:
````
/v5/{teamspace}/settings
/v5/{teamspace}/{project_id}/settings
/v5/{teamspace}/{project_id}/{fed_id}/settings
````

which implies settings and projects are in the same category of selection, when it isn't. I think it may be helpful to have a more clear separation between the routes and tabs.

A few  possibilities comes to mind:
**1. either make tabs query strings, i.e** 
````
/v5/{teamspace}?t=settings
/v5/{teamspace}/{project_id}?t=settings
/v5/{teamspace}/{project_id}/{fed_id}?t=settings
````
We may have a lot in query strings though, since we probably want to identify pop ups states within tabs as query strings

**2a. super explicit about everything with prefixes**
````
/v5/ts/{teamspace}/t/settings
/v5/ts/{teamspace}/p/{project_id}/t/settings
/v5/ts/{teamspace}/p/{project_id}/f/{fed_id}/t/settings
````
**2b. only prefix tab entry with /t/ (so we know when breadcrumb stopped?)** 
````
/v5/{teamspace}/t/settings
/v5/{teamspace}/{project_id}/t/settings
/v5/{teamspace}/{project_id}/{fed_id}/t/settings
````
**3 use delimiter for tabs**
````
/v5/{teamspace}_settings
/v5/{teamspace}/{project_id}_settings
/v5/{teamspace}/{project_id}/{fed_id}_settings
````

This inspiration is taken from facebook: 
![image](https://user-images.githubusercontent.com/11945337/126184656-475058d6-1a9c-4882-8dea-a9b6540d10d0.png)

If we go for this we may want to use a different delimiter as the user could easier have _ in their teamspace names


Tbh I'm not 100% with any of the options. Let me know what you think

**Comment by carmenfan** [comment]
Might be worthwhile to split this into 2 issues -> one for the basic layout (dummy everything), then one for navigation
