### ISSUE TITLE
3drepo io v4.17.0 (Release Candidate) QA

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2691]
### UI Oddities
- [x] ~~[Spacing on elements in Risk Card inconsistent](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-880521001)~~ (caused by https://github.com/3drepo/3drepo.io/pull/2646)
- [x] [Underline in Issues & Risk cards is inconsistent](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-880700259)
- [x] [Comment expand button missing from Issue & Risks](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-881405081)
- [x] [Smart Group filters can't be modified](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885063132)
- [x] [White screen after revision link](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-883337026) (carmen)
- [x] [SPM import error](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-884873958) - devops issue. to be dealt with on https://github.com/3drepo/DevOps/issues/235
- [x] [Can't update SafetiBase Viewpoint without taking a new model screenshot](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885047344) (Charence)
- [x] [Retain risk viewpoint on screenshot update](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885060223) (Charence)
- [x] Retain risk screenshot on viewpoint update (Charence)
- [x] [BCF import/export fail](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-884957232)
- [x]  [Empty "Assign" field when creating a new issue](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885535011)(Carmen)
- [x] API key auth session should not check referer (Charence)
- [x] [Investigate "Filter with this operation is already used" in groups](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-887460033) (Charence)

**Comment by mosment3DRepo** [comment]
### Spacing on elements in Risk Card inconsistent

The margin or padding (or something else) has increased in this release, making the Risk card longer and harder to use

### Steps to Replicate

Compare Staging Risk card to Prod risk card

### Screenshot

![padding issue](https://user-images.githubusercontent.com/62879582/125759652-41395a4e-b06f-42e8-a806-f5f86198e83a.png)

**Comment by miadibe** [comment]
### Underline in Risk card inconsistent
Issues Card: Underline doesn't exist in Staging
Risks Card: Inconsistency where some Risk fields have the underline and others don't.

### Steps to Replicate
Compare Staging Risk card to Prod risk card.

### Screenshot
![risks ui](https://user-images.githubusercontent.com/56918163/125796837-0817d58d-fcfb-457a-9336-f18ea289880d.png)
![issues ui](https://user-images.githubusercontent.com/56918163/125796853-8a95b2f6-b207-4cc1-b60d-1250c44c2766.png)

**Comment by ChristosTsiotsias** [comment]
@sanmont3drepo  In the first comment I think the margin is caused cause SUMMARY_HEIGHT in previewDetails.styles.ts was increased from 70 to 78. Do you wanna have a look at this or shall I do it 😄  ?

**Comment by mosment3DRepo** [comment]
### Comment expand button missing from Issue & Risks

The 'expand comment' button has dissapeared, but the comment still expands if the area is clicked

![image](https://user-images.githubusercontent.com/62879582/125946186-a559366f-ce74-4a6f-9442-b3671a400bec.png)

**Comment by BDavydov** [comment]
**Description**

New sign-ups on staging.dev.3drepo.io get a 2GB storage Quota. I believe that by default our users must get 100MB maximum?

**Steps to replicate:**
- Head over to staging.dev.3drepo.io
- Sign Up for a new account
- Log in to your newly created account and open the Billing Page

**Screenshots**
![image](https://user-images.githubusercontent.com/19904513/126182368-164f526a-21bb-40f7-ba42-e3e9d38f61af.png)

**Comment by keifgwinn** [comment]
> New sign-ups on staging.dev.3drepo.io get a 2GB storage Quota. I believe that by default our users must get 100MB maximum?
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/19904513/126182368-164f526a-21bb-40f7-ba42-e3e9d38f61af.png)

This is just a config thing to make it easier when using dev. 

Dev is set to use   

APP_SUBSCRIPTIONS_BASIC_COLLABORATORS: "5"
APP_SUBSCRIPTIONS_BASIC_DATA: "2048"

Prod is set to use 100mb

**Comment by carmenfan** [comment]
> > New sign-ups on staging.dev.3drepo.io get a 2GB storage Quota. I believe that by default our users must get 100MB maximum?
> > **Screenshots**
> > ![image](https://user-images.githubusercontent.com/19904513/126182368-164f526a-21bb-40f7-ba42-e3e9d38f61af.png)
> 
> This is just a config thing to make it easier when using dev.
> 
> Dev is set to use
> 
> APP_SUBSCRIPTIONS_BASIC_COLLABORATORS: "5"
> APP_SUBSCRIPTIONS_BASIC_DATA: "2048"
> 
> Prod is set to use 100mb

Also we've had the same conversion last QA https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842229023

Either you guys keep a mental note of this, or we can switch it back down to 100MB (of course this does mean everytime you setup a new account and need more quota you'd need to ping one of us). Let's not bring it up every QA cycle 😆

**Comment by BDavydov** [comment]
**Description**
When I am creating a new user invitation I can decide which models/federations to share. If I select all of the models at once and then decide to remove one or more of them I get a warning message. It seems as though it registers the original selection and if I unassign the model it throws an error.

**Steps to replicate:**
- Log in to staging
- Head over to the User Management page
- Create a new user invitation
- Select a project and batch select all models as a viewer
- Now make one of the models as unassigned
- Click Send invitation

**Images/GIFs**
![User Invtire permissions](https://user-images.githubusercontent.com/19904513/126299644-b6cbdca2-4ee7-4d64-adce-873a4d625c19.gif)

**Comment by BDavydov** [comment]
**Description**
When you open the model revisions window there is an option to load a specific model revision. When I click on the icon, I get a white screen, but it should start loading the model viewer with the model revision selected.

**Steps to replicate:**
- Log in to staging
- Click on the revisions icon
- Click on the open revision icon

**Images/GIFs**
![Model Revision](https://user-images.githubusercontent.com/19904513/126320531-56a05a09-31f8-4345-ae16-788077deddea.gif)

**Comment by BDavydov** [comment]
**Description**
When you open the model/federation settings menu there is an option to change the name. The only issue is that there is no character limit (120 characters) that appears when you first create your model container. As a result, you can have a really long name.

**Steps to replicate:**
- Log in to staging
- Click on the model/federation settings icon
- Change the name to a really long value > 120 characters
- Click save

**Images/GIFs**
![Model Settings Name](https://user-images.githubusercontent.com/19904513/126321559-b0a3f88d-b36d-42c9-82cd-4766ae708cee.gif)

**Comment by BDavydov** [comment]
**Description**
The .SPM model exported from Synchro is failing to process on staging.dev.3drepo.io. Right after the upload, you get an error message **_Import failed: Unknown error_** The same file works absolutely fine on Prod.

**Steps to replicate:**
- Log in to staging.dev.3drepo.io
- Create a model container
- Upload this [SPM Model](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/3D%20Models/Synchro/20201019%20Clinic_S%20-%20M%20Osment%20Demo%20-%20With%20Landscape%20v6.spm)
- Include the option **Import transformations**

**Images/GIFs**
![image](https://user-images.githubusercontent.com/19904513/126639109-31d42af7-4353-459a-b92e-dadd5acad453.png)

**Comment by carmenfan** [comment]
@keifgwinn something wrong with the staging setup, with the packaging script i believe it should be trying to find the plugins there? should be a folder called plugins within the packaged folder
![image](https://user-images.githubusercontent.com/11945337/126639892-4e58713f-b7a1-45b5-89b4-cf224d3d1dd0.png)

**Comment by BDavydov** [comment]
**Description**
I can export the BCF from any model/federation. When I try and upload it to another model/federation it shows an error message.

**Steps to replicate:**
- Login to staging.dev.3drepo.io
- Open any federation that contains issues
- Download/Export BCF (issues)
- Create another copy of the federation
- Upload BCF and wait
- Error message appears and no issues imported

**Images/GIFs**
![image](https://user-images.githubusercontent.com/19904513/126656029-4371be5e-e351-4c08-89a6-c04ae924e02e.png)

**Comment by BDavydov** [comment]
**Description**
Relly strange behaviour in the markup tool. After I draw any shape, such as a line, arrow or square, I can move them around. After moving around I get an option to change their size. When I pull on the corners, it changes the overall shape size before I do anything. 

**Steps to replicate:**
- Create an Issue
- Add a model markup to the issue
- When you draw a line, move it around
- Select the corner of the line to drag (make bigger or smaller)
- Line jitters and changes size on its own

**Images/GIFs**
![Markup tool](https://user-images.githubusercontent.com/19904513/126660626-3f93e660-c0f7-4ade-8f5a-ac30367c4a3b.gif)

**Comment by BDavydov** [comment]
Not sure how tidy this new issue title layout is looking! :/
![image](https://user-images.githubusercontent.com/19904513/126662018-0bbd55f7-8318-4317-8e0b-fdd5de6f00c4.png)

**Comment by BDavydov** [comment]
**Description**
When I create an Issue/SafetiBase Risks, sometimes I don't get a warning message when I go over the 660 characters limit on my description. As a result, I save the Issue/Risk and then half of the description disappears.

**Steps to replicate:**
- Open any model/federation
- Start creating a new Issue/SafetiBase Risk
- Write your own description >660 characters
- Click on the Save button
- Review the description (missing the end part)

**Images/GIFs**

**_Before Saving_**
![image](https://user-images.githubusercontent.com/19904513/126672896-ed1bb93b-3d12-4423-880d-6d495847c0e3.png)

**_After Saving_**
![image](https://user-images.githubusercontent.com/19904513/126672946-dd7b9186-61ca-46e4-90a3-746aca583a68.png)

**Comment by BDavydov** [comment]
**Description**
Can't update SafetiBase Viewpoint without taking a new model screenshot. Get a warning message as shown below.

**Steps to replicate:**
- Open any model
- Open an existing SafetiBase risk
- Click on the Update Viewpoint button
- Don't update the screenshot
- Get an error message

**Images/GIFs**
![image](https://user-images.githubusercontent.com/19904513/126674390-2549492e-51d2-46e9-9eb5-4fef99b38b96.png)

**Comment by BDavydov** [comment]
**Description**
If I update the SafetiBase Risk Screenshot without changing the viewpoint, it resets the original viewpoint.

**Steps to replicate:**
- Create a risk
- Open the new risk again
- Update the screenshot (don't update the viewpoint)
- Exit the risk
- Open it again (camera doesn't change to the original viewpoint)

**Images/GIFs**
![Update SafetiBase Screenshot](https://user-images.githubusercontent.com/19904513/126677103-937886cf-7a71-49b5-9254-cbb49d37137b.gif)

**Comment by mosment3DRepo** [comment]
### Smart Group filters can't be modified**
Once you create a smart group filter you can go back and edit it but you can't save the changes

### Steps to replicate
1. Create a new smart group
2. Add a rule
3. Save the group
4. Click the rule you created
5. Edit it
6. Hit "Update"
7. Notice the Save button is still disabled
8. Exit the group and go back in, it was not updated

### Expected behaviour
The save button should not be enabled after the "Update" button has been hit

## GIF
![Group change](https://user-images.githubusercontent.com/62879582/126677695-6ab70220-31b2-4931-841a-4bc60e5dc6a0.gif)

**Comment by carmenfan** [comment]
> **Description**
> If I update the SafetiBase Risk Screenshot without changing the viewpoint, it resets the original viewpoint.
> 
> **CORRECTION!!!!!!**
> It works after you refresh the page CTRL + R. Strange why it doesn't register the change in session. :/
> 
> **Steps to replicate:**
> 
> * Create a risk
> * Open the new risk again
> * Update the screenshot (don't update the viewpoint)
> * Exit the risk
> * Open it again (camera doesn't change to the original viewpoint)
> 
> **Images/GIFs**
> ![Update SafetiBase Screenshot](https://user-images.githubusercontent.com/19904513/126677103-937886cf-7a71-49b5-9254-cbb49d37137b.gif)

This was fixed last release, fyi reported here https://github.com/3drepo/3drepo.io/issues/2612#issuecomment-842450730

regression bugs!

@Charence

**Comment by BDavydov** [comment]
The clip plane flipped but the control arrows are still in the same place. Applies to a clip box.

![Clip Box Arrows](https://user-images.githubusercontent.com/19904513/126684646-1fa246af-41b0-4c80-8c06-65e86a052bc5.gif)

**Comment by mosment3DRepo** [comment]
> **Description**
> I can export the BCF from any model/federation. When I try and upload it to another model/federation I get an error message and it doesn't work.
> 
> **Steps to replicate:**
> 
> * Login to staging.dev.3drepo.io
> * Open any federation that contains issues
> * Download/Export BCF (issues)
> * Create another copy of the federation
> * Upload BCF and wait
> * Error message appears and no issues imported
> 
> **Images/GIFs**
> ![image](https://user-images.githubusercontent.com/19904513/126656029-4371be5e-e351-4c08-89a6-c04ae924e02e.png)

@BDavydov I think this might be model specific, do you have a link to the model as I can't replicate

**Comment by mosment3DRepo** [comment]
> The clip plane flipped but the control arrows are still in the same place. Applies to a clip box.
> 
> ![Clip Box Arrows](https://user-images.githubusercontent.com/19904513/126684646-1fa246af-41b0-4c80-8c06-65e86a052bc5.gif)

**Comment by BDavydov** [comment]
On Prod, when you create a new issue it says Unassigned. However, on staging the field is empty. Is that an update or an error in 3D Repo? 

**Prod**
![image](https://user-images.githubusercontent.com/19904513/126767383-9fbfd11d-b8ce-43fe-8651-9a9e7fc1b1ca.png)
![image](https://user-images.githubusercontent.com/19904513/126767460-4c44cc91-c94b-49fb-883c-bbf206b6d283.png)


**Staging**
![image](https://user-images.githubusercontent.com/19904513/126767251-83e61014-4577-48ab-9f20-d027ed3db9ff.png)
![image](https://user-images.githubusercontent.com/19904513/126767321-5c2f6721-45b9-4792-a5a7-018c28aa3a5f.png)

**Comment by Charence** [comment]
Sometimes getting a "Filter with this operation is already used" when editing a smart group.
