### ISSUE TITLE
Revamping - New container popup component

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2692]
### Description 
To create containers for a teamspace/project a  new container popup is needed. Take in consideration that 'container' is a renaming of 'model'.

### Goals
- [ ] Users should be able to open the new container popup 
- [ ] Users should be able to fill out the form and create a container

### Tasks
- [ ] Add button in containers page
- [ ] Create a form following the design
- [ ] Add form error handling
- [ ] Use the popup system for showing the popup
- [ ] Integrate with api 
- [ ] Add saga tests

### For consideration
This is a form popup, it shouldnt be dispatched by using `DialogActions.open` . Instead it should use `src\v5\ui\controls\modal\formModal\formDialog.component.tsx` embeded in the containersComponent. That's because is not a general modal that's being dispatched but just a form in a modal wrapping.

Let's use [react-hook-form](https://react-hook-form.com/) to manage the form 

The form should conform with [this schema](https://github.com/3drepo/3drepo.io/blob/1f43b5008ea84a58c8c50df9927bc1b96678701e/frontend/src/v4/routes/teamspaces/components/modelDialog/modelDialog.component.tsx#L36-L45) otherwise it should  show an error in the field.
![image](https://user-images.githubusercontent.com/42032433/146413117-63166d9e-8e0d-41b4-8682-9915aa4a65de.png)

The save button should be disabled until the form is valid.

### Related Resources
Look for the container popup form mockup from here:
https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3421%3A50924

[Create new container endpoint](https://github.com/3drepo/3drepo.io/issues/2769)
