### ISSUE TITLE
Revamping - New light theme

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2694]
### Description
A new theme for styling buttons, inputs, links and text

### Goals
- [x] To have a new theme that matches the design

### Tasks
- [x] Set styles for buttons in new theme
- [x] Set styles for inputs in new theme
- [x] Set styles for links in new theme
- [x] Set font styles for text, headings
- [x] Create a sample page to demonstrate the theme for testing

### Related Resources
MockUp : https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/UI-Kit?node-id=0%3A1

**Comment by m1chalkubiak** [comment]
Hi @sanmont3drepo 
I did not manage to complete inputs styling. What I managed to get to, is that probably the same as it is described in the documentation in custom input styling, we would have to break apart the `TextField` components and style them separately, so if we wanted to do it by overwriting material-ui theme, I'm afraid that we could spoil the styling of other elements that may be using those sub-elements.

Check the example below, the bootstrap one is mostly close to what we wanted to achieve.
https://material-ui.com/components/text-fields/#customized-inputs

By the way, I wanted to ask you what you think about importing colors or shadows separately in each style file, extracting them from the props provided by `ThemeProvider`. We have a global ThemeProvider for `styled-components` in which the same theme is provided that is used by the `material-ui`, thanks to the themes we have access to all defined colors, typography styles, shadows, etc.
With this approach, the use of color in styled-components would look like this: 
```js
color: ${({ theme }) => theme.pallete.primary.main};
```

**Comment by m1chalkubiak** [comment]
@sanmont3drepo one more thing, In the meantime, I realized that one of the things that I added within this Branch were shadows. There were four of them, but now on Figma I see George changed their name to Elevation and gave them 11 variants. 

It's normal for something to change and be improved in design. But when we start to implement it, it is important that everyone has up-to-date information about changes in order to be able to implement them. I do not associate any default notification functionality about changes in views on Figma, so @george-hadfield  please remember to stay in touch with us and inform us about these changes on a regular basis.

**Comment by george-hadfield** [comment]
Hi Michal,

This was me testing something out on Friday and the shadows you are talking
about aren't final. Once they are final, I will let you know as this would
be a change. The shadows you are seeing here, come directly from Material
UI, so I'm trying to make it an easier implementation/

Thanks,
George

**Comment by sanmont3drepo** [comment]
> Hi @sanmont3drepo
> I did not manage to complete inputs styling. What I managed to get to, is that probably the same as it is described in the documentation in custom input styling, we would have to break apart the `TextField` components and style them separately, so if we wanted to do it by overwriting material-ui theme, I'm afraid that we could spoil the styling of other elements that may be using those sub-elements.
> 
> Check the example below, the bootstrap one is mostly close to what we wanted to achieve.
> https://material-ui.com/components/text-fields/#customized-inputs
> 
> By the way, I wanted to ask you what you think about importing colors or shadows separately in each style file, extracting them from the props provided by `ThemeProvider`. We have a global ThemeProvider for `styled-components` in which the same theme is provided that is used by the `material-ui`, thanks to the themes we have access to all defined colors, typography styles, shadows, etc.
> With this approach, the use of color in styled-components would look like this:
> 
> ```js
> color: ${({ theme }) => theme.pallete.primary.main};
> ```

Hi MIchal, I was able to style the inputs. Right now is styling the general outline for inputs. I see no problem with that for now. If in the near future we want to style them in the scope of a textfield because of problems thy mught carry we can as I also tested to style them in the scope of textfield and it worked.
