### ISSUE TITLE
Revamping  - UI controls needed for basic layout

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2695]
### Description
Create necessary UI controls to code up #2690

### Goals
- [x] Have commonly used layouts controls with standardized spacing 
- [x] Have commonly used buttons

### Tasks
- [x] Circle buttons
- [x] Breadcrumbs (using theme)
- [x] Links (using theme)
- [x] AppBar
- [x] two level menu ( for navigation)

### Related Resources
MockUp : `link to mockup`
https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=0%3A1

**Comment by carmenfan** [comment]
@sanmont3drepo 
TODO:
- figure out which components we need for basic layout and list them here
- make sure have every we need for those components from george
