### ISSUE TITLE
Upload containers - Modal

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2698]
### Description
To upload files containers for a teamspace/project a  new upload popup dialog is needed. Take in consideration that 'container' is a renaming of 'model'.
This will integrate this issues: #2912 #2913 #2914 #2915

### Goals
- [x] Users should be able to open the upload container popup
- [ ] Users should be able to upload a new file to an existing container
- [ ] Users should be able to upload a new file to a new container
- [ ] Users can see the progress of the files being uploaded and their success/failed status

### Tasks
- [x] Add button in containers page
- [x] Use the popup system for showing the popup
- [ ] Create a form following the design
- [ ] Integrate the drag and drop component
- [ ] Integrate the edition item
- [ ] Integrate the edit settings control 
- [ ] integrate the upload progress component

### Related Resources
[Stages of uploading a model to a container:](https://www.figma.com/proto/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3096%3A48896&scaling=min-zoom&page-id=2856%3A52611&starting-point-node-id=3096%3A48896)
(use keyboard to navigate the stages using left or right arrows)
[The whole containers mockup](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2856%3A52611)
