### ISSUE TITLE
Address vulnerabilities

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2700]
### Description
Address alerts from Dependabot https://github.com/3drepo/3drepo.io/security/dependabot

### Goals

- [x] Address critical vulnerabilities
- [x] Address high severity vulnerabilities
- [x] Address moderate severity vulnerabilities

### Tasks

- ~html-pdf~
- [x] nodemailer
- [x] lodash
- [x] pug
- [x] socket.io
- [x] axios

### Related Resources

https://github.com/3drepo/3drepo.io/security/dependabot
