### ISSUE TITLE
Revamping - routing

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2706]
### Description
Create routes  for v5 pages. Routing should be as decoupled as possible to make it easy to tweak and see what's right. 

### Goals
- [ ] Create some sort of decoupled routing system
- [ ] Set containers/federations routes

### Tasks
- [ ] Create a service file that returns the route taking teamspace/project/ federationid, etc (depending on the route) as parameters 
- [ ] Group the functions in a logical maner (maybe separate the ones in dashboard and viewer)
- [ ] Use this service files also in the route paths when defining the paths in react router to avoid having outdated routes

**Comment by sanmont3drepo** [comment]
@m1chalkubiak I think I'll do this issue . Please address the comments in the other branches without the routing stuff and if you finish that move on to milestone 2 tasks.

**Comment by m1chalkubiak** [comment]
@sanmont3drepo of course, according to what we established at our last meeting,  I only pushed what was within #2690 directly related to routing.
