### ISSUE TITLE
Revamping - Container revision details

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2708]
### Description
When clicking an item in the containers list it should display a more detailed item providing a revision list and the options to add a new revision or to upload the file for the first time

### Goals
- [x] Users should be able to click on an item in the list and the details of the container will appear
- [x] If the container is empty the details will show an "upload file" button and be able to upload a new file
- [x] If the container is not empty, the list of revisions should appear with a "add new revision" button to upload a new file and create a new revision

### Tasks
- [x] Create a specific list control with the selected style (maybe using a "selected theme" where all the primary/secondary colors  are set as the specification of selected?)
- [x] Create a specific list item with the selected style
- [x] Create the trail on the left of the list, this should be prepare to for n revisions. ask @george-hadfield  for one or two revisions
- [x] Create a new saga/selectors/redux in v5 for fetching the revisions
- [x] Add tests for this saga

### Related Resources
revisions trail:
![image](https://user-images.githubusercontent.com/42032433/131731145-1c996b62-7203-40f6-b9e0-5998e77ca435.png)

mockup: https://www.figma.com/proto/djgxvRKOaMMyutswn5yywU/Teamspace?node-id=825%3A3916&scaling=min-zoom&page-id=821%3A1258

**Comment by m1chalkubiak** [comment]
@carmenfan For the `v5/teamspaces/${teamspace}/projects/${projectId}/containers/${containerId}/revisions` 
endpoint, the data that are missing in relation to designs is:
- description

I had doubts about the `void`, but from what I can see this property sometimes is sent and sometimes not, so it works, I just don't know if it's correct behavior.

I also would need to get from somewhere additional data regarding the author of the revision, 
<img width="261" alt="Zrzut ekranu 2021-10-14 o 16 42 13" src="https://user-images.githubusercontent.com/24941866/137340582-fb6ebfa7-63ff-4e39-b19d-9610bab351b3.png">
however, If it was too time-consuming, I think we could move this one feature into a separate issue.

So far I have used `${teamspace}/members` which seems to provide all the information I need.
