### ISSUE TITLE
Revamping - Realtime update (socketio)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2709]
### Description
A decoupled realtime service for managing socketio requests will be come in handy, this service can dispatch actions in order to affect the redux state and can be split out in different files that 

### Goals
- [ ] Realtime messages are being handled by the service
- [ ] No code regarding this service should appear in redux or saga (decoupled)
- [ ] Containers updated should be wired up using this service.

### Tasks
- [ ] Create a file that  provides utitlities for suscribing or unsubscribing to a message.
- [ ] Create an example file for one domain of messages (revision status updates)
- [ ] Use this service to dispatch the correct action to update the containers

**Comment by carmenfan** [comment]
TODO: 
also think (& ask product team) what kind of things expects an instant notification (add/remove containers, projects etc?) and scope out backend work accordingly

**Comment by carmenfan** [comment]
I think this is N/A - we've had other issues that superceded this 

@sanmont3drepo  just tagging you incase you disagree
