### ISSUE TITLE
Realtime events - Settings update for  containers/federations

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2716]
### Description
In order to get the user updated on changes we are using realtime events. This is for keeping the settings up to date.

### Goals
- [ ] As a user I want to know in realtime if someone else changed the federation settings
- [ ] As a user I want to know in realtime if someone else changed the containers settings

### Tasks
- [ ] Create methods for suscribing to federationSettingsUpdate, dispatch the update federation settings action
- [ ] Create methods for suscribing to containerSettingsUpdate, dispatch the update container settings action
- [ ] Enable **federationSettingsUpdate**  event in the  federation item
- [ ] Enable  **containerSettingsUpdate** event in the container item

### Related Resources
the data format of federationSettingsUpdate is 
````js
{
	"surveyPoints": [
		{
			"latLong": [ -34.459127, 0 ],
			"position": [ 0, 0, 0 ]
		}
	],
	"angleFromNorth": 0,
	"defaultView": "idOfView",
	"code": "dd",
	"unit": "mm",
	"desc": "ssd",
	"name": "Full Logo"
}
````

the data format of containerSettingsUpdate is 
````js
{
	"surveyPoints": [
		{
			"latLong": [ 0, 0 ],
			"position": [ 0, 0, 0 ]
		}
	],
	"type": "containerType",
	"angleFromNorth": 0,
	"defaultView": "idOfView",
	"code": "code",
	"unit": "unit",
	"desc": "description",
	"name": "containerName"
}
``

**Comment by m1chalkubiak** [comment]
Hi @sanmont3drepo Is there a chance to complete the requirements for this particular issue, or should we simply estimate use of the service that will be created under #2709 and assume a general implementation for events that at the moment we think that in containers will be needed?

**Comment by carmenfan** [comment]
this is on @mosment3DRepo to complete.


For the sake of the estimates just assume this doesn't exist and #2709 would be implemented using the chat events we currently have. 

This issue is about any extra events that we don't have yet (e.g. new model, delete model etc)

**Comment by m1chalkubiak** [comment]
Sure, thanks for the quick reply.

**Comment by mosment3DRepo** [comment]
@sanmont3drepo  is this what you were expecting?

**Comment by sanmont3drepo** [comment]
> @sanmont3drepo is this what you were expecting?

Yes, thank you!

**Comment by mosment3DRepo** [comment]
need Federation queued mockup @george-hadfield

**Comment by george-hadfield** [comment]
@sanmont3drepo I have created toast notification styles to cover the above, and will also help going forward for other notifications too.

Link to design
https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=137528%3A180576

Screenshot
<img width="896" alt="image" src="https://user-images.githubusercontent.com/78047794/172186169-8544fb64-565a-47b7-a7d7-5b84319077bb.png">

**Comment by carmenfan** [comment]
> @sanmont3drepo I have created toast notification styles to cover the above, and will also help going forward for other notifications too.
> 
> Link to design https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=137528%3A180576
> 
> Screenshot <img alt="image" width="896" src="https://user-images.githubusercontent.com/78047794/172186169-8544fb64-565a-47b7-a7d7-5b84319077bb.png">

Unless there's some private conversations involved, i don't think this is what we were after?

Originally we needed a mock up on how to show a federation is queued etc, which is similar to what we have for containers: 

![image](https://user-images.githubusercontent.com/11945337/172186855-05e381fd-e751-4b0b-849a-4eabec8be1ef.png)


If we're designing a whole range of toasts then i think that should go through design triage first. It's a bit big to add like this @mosment3DRepo

**Comment by sanmont3drepo** [comment]
> @sanmont3drepo can you clarify what are you after? I don't think we need to worry about toast notifications at this stage? We just want to see the the change of status at the row I think.

From the development side I just need to know what are the events (update a container? create a container?) and how I suscribe to them (suscribing to a container for update or to the project?).

From the UI standpoint I think that if it just updating the state of the container no other UI is needed because is just updating the state of the container and react will reflect that state.

**Comment by carmenfan** [comment]
> But if we want to enforce that someone changed it in realtime and we want to let the user know that I think toasts could work.

I don't think we want to do this at this stage - I think this doubles up with the notification centre stuff

> From the UI standpoint I think that if it just updating the state of the container no other UI is needed because is just updating the state of the container and react will reflect that state.

I think we still need the status on federations (again, federation has status) unless you already know what to do there? in which case it might worth altering the issue to specify.

> From the development side I just need to know what are the events (update a container? create a container?) and how I suscribe to them (suscribing to a container for update or to the project?).

Existing chat evets are documented here https://github.com/3drepo/3drepo.io/tree/staging/backend/src/v5/services/chat

There are some events still missing that requires some backend work, but they are planned and documented here: https://github.com/3drepo/3drepo.io/issues/3312

In essence as it stands we only have notifications to notify the UI the changes on model statuses

**Comment by sanmont3drepo** [comment]
> > But if we want to enforce that someone changed it in realtime and we want to let the user know that I think toasts could work.
> 
> I don't think we want to do this at this stage - I think this doubles up with the notification centre stuff
> 
> > From the UI standpoint I think that if it just updating the state of the container no other UI is needed because is just updating the state of the container and react will reflect that state.
> 
> I think we still need the status on federations (again, federation has status) unless you already know what to do there? in which case it might worth altering the issue to specify.
> 

In that case I agree. I've created the issue here: https://github.com/3drepo/3drepo.io/issues/3334
Which are the different status in federations? (you can comment on the other issue)

> > From the development side I just need to know what are the events (update a container? create a container?) and how I suscribe to them (suscribing to a container for update or to the project?).
> 
> Existing chat evets are documented here https://github.com/3drepo/3drepo.io/tree/staging/backend/src/v5/services/chat
> 
> There are some events still missing that requires some backend work, but they are planned and documented here: #3312
> 
> In essence as it stands we only have notifications to notify the UI the changes on model statuses

**Comment by carmenfan** [comment]
> Which are the different status in federations? (you can comment on the other issue)

@sanmont3drepo it just has queued/processing/ok/failed
