### ISSUE TITLE
Revamping - Backend endpoints for containers

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2719]
### Description
Here is a list of the backend endpoints needed for containers  based on the use cases of the page.

### Goals
- [ ] Fetch teamspaces with their projects for the logged user
- [ ] Fetch models by projectId
- [ ] Fetch revisions details by model
- [ ] Create a new container
- [ ] Upload a file to a container
- [ ] Delete a container

### Tasks
- [x] Teamspaces/projects endpoint  `HTTP  GET: /teamspaces` (#2722)
- [ ] Fetch models by projectId `HTTP  GET: /:teamspace/project/:projectId/models` (old api doesnt return all the necessary details)
- [ ] Fetch revisions details by model  `HTTP  GET: /:teamspace/:modelId/revisions.json?showVoid`
- [ ] Create a new container  `HTTP POST /:teamspace/model`
- [ ] Upload a file to a container `HTTP POST  /:teamspace/:modelId/upload`
- [ ] Delete a container `HTTP DELETE /:teamspace/:modelId`

**Comment by carmenfan** [comment]
@sanmont3drepo  i think it might be granular than this. Mostly for 2 reasons:

1. I think we should avoid designing endpoints for the convenience of a certain design - this will make it more reusable in the future without getting excessive data (this is also how we ended up with account.json 😆 )
2. More granular means quicker requests. So if there is a use case where we end up needing the same api endpoint, we're not stuck with a big ass database query to fetch data that we don't actually care about. For e..g model list may get a bit slow if the number of items gets big and if we also want to fetch all the stats around all the models.... so if we make them all separate then the webpage may have more loading icons logic, but it'll be more responsive

A couple of thoughts:

> Fetch teamspaces with their projects for the logged user
Is it worth splitting it in 2? I really think we should avoid grouping endpoints for the convenience of a certain design and do it where it makes sense (this is how we ended up with account.json. i.e.:
1. an endpoint where we fetch all the teamspaces that the user has access to
2. an endpoint where we fetch all the projects within the teamspaces has access to

> Fetch models by projectId HTTP GET: /:teamspace/project/:projectId/models (old api doesnt return all the necessary details)

By extra info do you mean these things? 
![image](https://user-images.githubusercontent.com/11945337/127196327-989d8262-e14c-403e-8720-a1c1e7765a7b.png)

I think i would prefer to leave this api. and have a `HTTP GET: /:teamspace/project/:projectId/models/:modelId/stats` that gives you this data. 

Also, is it worth prefixing teamspace as well? i.e.  `HTTP GET: /teamspace/:teamspace/project/:projectId/models` 

models, federations, containers.... Is it worth using containers and federations (even though the backend probably will end up merging the federation logic with containers...) - to get some consistency and clarity.

**Comment by sanmont3drepo** [comment]
> @sanmont3drepo i think it might be better to be more granular than this. Mostly for 2 reasons:
> 
> 1. I think we should avoid designing endpoints for the convenience of a certain design - this will make it more reusable in the future without getting excessive data (this is also how we ended up with account.json 😆 )
> 2. More granular means quicker requests. So if there is a use case where we end up needing the same api endpoint, we're not stuck with a big ass database query to fetch data that we don't actually care about. For e..g model list may get a bit slow if the number of items gets big and if we also want to fetch all the stats around all the models.... so if we make them all separate then the webpage may have more loading icons logic, but it'll be more responsive

I think you made two really good points here! I agree with this approach, but we need to see it case by case; for example in federations we will need the number of issues and risks and I dthink we dont want to fetch all issues and risks to get that number per item.

> 
> A couple of thoughts:
> 
> > Fetch teamspaces with their projects for the logged user
> 
> Is it worth splitting it in 2? i.e.:
> 
> 1. an endpoint where we fetch all the teamspaces that the user has access to

I think `HTTP GET: /teamspaces` could do it

> 2. an endpoint where we fetch all the projects within the teamspaces has access to

I would go for `HTTP GET: /teamspaces/:teamspace/projects`  (the singular /project was a typo )

> 
> > Fetch models by projectId HTTP GET: /:teamspace/project/:projectId/models (old api doesnt return all the necessary details)
> 
> By extra info do you mean these things?
> ![image](https://user-images.githubusercontent.com/11945337/127196327-989d8262-e14c-403e-8720-a1c1e7765a7b.png)
> 
> I think i would prefer to leave this api. and have a `HTTP GET: /:teamspace/project/:projectId/models/:modelId/info` that gives you this data.
> 
> Also, is it worth prefixing teamspace as well? i.e. `HTTP GET: /teamspace/:teamspace/project/:projectId/models`

Yes, it makes sense I think, but I would change it to be plural like this:  `HTTP GET: /teamspaces/:teamspace/projects/:projectId/models`

> 
> models, federations, containers.... Is it worth using containers and federations (even though the backend probably will end up merging the federation logic with containers...) - to get some consistency and clarity.

you mean two set of endpoints with `/containers/...` and `/federations/...` in their route?

**Comment by carmenfan** [comment]
closing this in favour of individual issues for groups of endpoints
