### ISSUE TITLE
backend v5 foundation

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2722]
### Description
For the v5 revamp (front end). we want to take the opportunity to also restructure the backend - at the very least, new endpoints should be added in a more desirable way so we are not adding extra technical debt for every extra logic going forward.

The aim is to have a place to code new features where we have a structure/frameworks that we wish to use going forward, whilst slowly migrate everything else during maintenance.

### Tasks
- [x] separate v4 and v5 similar to #2686
- [x] do one endpoint as an example
- [x] setup launch logic to tap into both so we run one server with endpoints supported from both versions
- [x] setup testing framework (properly)
- [x] setup coverall (again?)
- [x] setup better linting check
- [ ] swagger documentation ?
- [x] typescript - try it and see. 
- [x] allow launch from yarn run
- [x] response code revamp -> be able to send default error codes with customised message
- [ ] event listening to deal with things like emails and notifications (try it out)
- [ ] plugin js -> remove and see if it works?

### Proposed folder structure
- backend
  - tests
    - v4
    - v5
  - src
    - v4
    - v5
     - 3drepo.js
        - utils
          - config
          - logger
          - permissions (access rights check)          
          - helpers (essentially what was in utils but split up better, common helper functions etc)
        - middleware
          - auth
          - validator (input/output processing, so we stop doign things like UUID-to-string, ensure things are right type everywhere and can make assumptions)
        - routes
           - teamspace
             - project
               - containers
               - federation
               - common
                 - tickets
                   - issues
                   - risks
           - user
        - model (1 to 1 mapping to data models)
        - processors 
        - handlers (database, gridfs, fileshare, alluxio etc)
        - services (api server, sock.io server etc)
