### ISSUE TITLE
Create an endpoint for a list of projects the user can access

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2748]
### Description
Given a teamspace name, return a list of projects the user has access to. 

The proposed endpoint should have a similar format to the [ teamspace list](https://staging.dev.3drepo.io/docs/#/Teamspaces/get_teamspaces)

so for `GET /teamspaces/:teamspace/projects/`, It should return the following:

````
{
    projects: [
        {_id: <project id>, name: "project name", isAdmin: true }
        {_id: <project id>, name: "project name 2", isAdmin: false }
    ]
}
````

If the user does not have sufficient permission, or the teamspace does not exist, it should return 404 `TEAMSPACE_NOT_FOUND`

### Goals
- [ ] Create an endpoint that will return a list of projects within the teamspace the user has access to

### Tasks
- [ ] Create endpoint
- [ ] Create swagger docs
- [ ] Create e2e tests
- [ ] Create unit tests for each method created
