### ISSUE TITLE
Create an endpoint for a list of containers the user can access

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2749]
#### Containers
so for `GET /teamspaces/:teamspace/projects/:projectId/containers`, It should return the following:

````
{
    containers: [
        {_id: <container id>, name: "container name", role: "admin", isFavourite: true }
        {_id: <container id>, name: "container name 2", role: "collaborator", isFavourite: false }
    ]
}
````
If the user does not have sufficient permission, or the teamspace does not exist, it should return 404 `TEAMSPACE_NOT_FOUND`
If the user does not have sufficient permission, or the project does not exist, it should return 404 `PROJECT_NOT_FOUND`

### Goals
- [x] Create an endpoint that will return a list of containers within the project the user has access to

### Tasks
- [x] Create endpoint
- [x] Create swagger docs
- [x] Create e2e tests
- [x] Create unit tests for each method created
