### ISSUE TITLE
Favourites endpoint

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2754]
### Description
New v5 endpoints to show favourite containers/federations.

#### Add to favourites
- Containers `PUT /teamspace/:teamspace/project/:project/containers/favourites`
```` json
{
  containers: [idA, idB, idC,]
}
````
This should add any ids that were not in the array to the list of favourites.

- Containers `PUT /teamspace/:teamspace/project/:project/federations/favourites`
```` json
{
  federations: [idA, idB, idC,]
}
````
This should add any ids that were not in the array to the list of favourites

#### Remove from favourites
- Containers `DELETE /teamspace/:teamspace/project/:project/containers/favourites`
```` json
{
  containers: [idA, idB, idC,]
}
````
This should remove any ids that are in the favourites array

- Containers `DELETE /teamspace/:teamspace/project/:project/federations/favourites`
```` json
{
  federations: [idA, idB, idC,]
}
````
This should remove any ids that are in the favourites array

NOTE: There is no need to have a GET endpoint for now as we have this embedded in the GET fed/container list (https://github.com/3drepo/3drepo.io/issues/2749

### Goals
- [ ] The user should be able to:
  - [ ] Add multiple ids into the favourites array
  - [ ] Remove multiple ids from the favourites array

### Tasks
- [ ] Implement endpoint
- [ ] Add unit tests
- [ ] Add e2e tests
- [ ] Add swagger doc
