### ISSUE TITLE
container Revision endpoint 

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2756]
### Description
Have an endpoint to fetch the revision details of a given container

`GET /teamspaces/:teamspace/projects/:project/containers/:container/revisions?showVoid=true` 
payload:
````js
{
   revisions: [
       {
		"_id":"00000000-0000-0000-0000-000000000001",
		"author":"alice",
		"timestamp":12345567, //timestamp
		"name":"00000000-0000-0000-0000-000000000001",
	}
    ]
}
````
NOTES:
- `showVoid` is optional and should be false by default
- if `showVoid` is set to true, show void revisions as well as active revisions
- if container not found or if the user has no permissiosn to access the container, return `404 CONTAINER_NOT_FOUND`

### Goals
- [ ] The user should be able to get the list of revisions 
   - [ ]  Void revisions should only be visible when the user has specified showVoid to true

### Tasks
- [ ]  Implement endpoint
- [ ]  Add unit tests
- [ ]  Add e2e tests
- [ ]  Add swagger doc
