### ISSUE TITLE
Create an endpoint for a list of federations the user can access

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2763]
#### Federations
so for `GET /teamspaces/:teamspace/projects/:projectId/federations`, It should return the following:

````
{
    federations: [
        {_id: <fed id>, name: "fed name", role: "admin" , isFavourite: true}
        {_id: <fed id>, name: "fed name 2", role: "collaborator" , isFavourite: false}
    ]
}
````
If the user does not have sufficient permission, or the teamspace does not exist, it should return 404 `TEAMSPACE_NOT_FOUND`
If the project does not exist, it should return 404 `PROJECT_NOT_FOUND`

### Goals
- [x] Create an endpoint that will return a list of containers within the project the user has access to

### Tasks
- [x] Create endpoint
- [x] Create swagger docs
- [x] Create e2e tests
- [x] Create unit tests for each method created
