### ISSUE TITLE
Ability to add and delete containers

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2769]
#### Add a new container
v4 endpoint : https://3drepo.github.io/3drepo.io/#api-Model-createModel
`POST /teamspaces/:teamspace/projects/:project/containers`

payload (note: similar to v4 but not identical!)
````js
{
   name: "awesomeModel",
   unit: "ft",
   desc: "This is an awesome model!",
   code: "awe12",
   type: "Mechanical"
}
````
response (success) 
````js
{
    _id: <container id as a string>
}
````

NOTES:
- name, units and type is compulsory, if missing, return INVALID_ARGUMENTS with bespoke messages
- make sure we also do a type check, if failed, return INVALID_ARGUMENTS with bespoke messages
- units should be recognisible (ie. must be m, mm, cm, dm or ft... or whatever is the list)
- input validity should be done as a middleware inside dataConverter, use [yup](https://www.npmjs.com/package/yup)
- ensure we convert uuid back to string before we return the response (this should be done in routes file, not processor)
- you can only create a container if you are an admin (should be same as v4), NOT_AUTHORIZED otherwise

#### Remove a container
Corresponding v4 endpoint: https://3drepo.github.io/3drepo.io/#api-Model-deleteModel

`DELETE /teamspaces/:teamspace/projects/:project/containers/:container`

NOTES:
- only admins can do this.
- just return `templates.ok` upon success

### Goals
- The user should be able to create a new container if they have necessary permissions
- The user should be able to delete a container if they have necessary permissions

### Tasks
Add container
  - [x] Implement endpoint
  - [x] Add unit tests
  - [x] Add e2e tests
  - [x] Add swagger doc

Delete container
  - [x] Implement endpoint
  - [x] Add unit tests
  - [x] Add e2e tests
  - [x] Add swagger doc
