### ISSUE TITLE
Scripts for counting mesh faces

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2774]
### Description

Scripts for counting faces in meshes/models/federations

### Goals

- [x] Output faces_count for models/federations

### Tasks

- [x] Output faces_count for models
- [x] Output faces_count for federations

**Comment by carmenfan** [comment]
closing. see https://github.com/3drepo/3drepo.io/pull/2775#issuecomment-920203170
