### ISSUE TITLE
Revamping - Federations page

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2785]
### Description
Federations will be reimplemented with the new style. It will provide the functionality of viewing all the federations from a project. Be able to upload/edit/delete them. Provide some sort of search. 
It will also
The list will be based of the containers lists components as well as components specially needed for the federations.

### Goals
- [x] To have an all federations list based on the selected project
- [x] To have a favourites federations list based on the selected project
- [x] To add and remove federations from the the favourite list
- [x] To have blank states when the lists are empty
- [ ] Show revisions detailes when a row has been clicked

### Tasks
- [ ] Use lingui \<Trans id=".." /> tag for translations for the columns and blank state
- [ ] Use lingui i18n._('...') for translations when you can only pass strings 
- [ ] Create a reusable list item for federations using the components like \<dashboardlistitem ...> etc. 
- [ ] Use that list for all federations and favourites
- [ ] Use the columns for sorting the lists (if this bit goes into redux/selectors it depends on wether we want to keep the state when navigating throught the app) 
- [ ] Add a blankstate already created for containers when there are no items in the list (remember that no button for creating federations is needed at this point)
- [ ] Add api endpoint for fetching the federations to the api service ( I mean in the frontend)
- [ ] Add api endpoint for Adding/removing a federation as favourite the api service
- [ ] Add saga fetch actions and selectors for fetching and selecting the federations
- [ ] Add saga add/remove action for adding/removing the federation as favourite
- [ ] Use createHookSelectors for the the selectors as exemplified in **src\v5\services\selectorsHooks\currentUserSelectors.hooks.ts**
- [ ] Use actiondispatcher as exemplified in  **src\v5\services\actionsDispatchers\currentUsersActions.dispatchers.ts**

### Related Resources
MockUp : https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2427%3A36135

**Comment by george-hadfield** [comment]
Could someone please provide a URL for testing on this one?

**Comment by carmenfan** [comment]
@george-hadfield  it's at the top of the PR:
![image](https://user-images.githubusercontent.com/11945337/141147674-1e7b5a7d-d4ba-4a49-9ebb-addf5aa5c12a.png)
https://github.com/3drepo/3drepo.io/pull/2850
