### ISSUE TITLE
Revamping - Edit federations 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2786]
### Description
Edit federations from the v5 federations page. Its used to change which containers are included in the federation. It consists of a modal dialog for some buttons to trigger the modal dialog.

### Goals
- [ ] Have a modal dialog to edit a federation
- [ ] Have an Item in ellipsis menu of the particular federation to trigger the modal dialog

### Tasks
- [ ] Add an edit federation item in the ellipsis/hamburger menu in the federation item
- [ ] Create a modal dialog that will contain the two lists reusing the dashboard lists controls. This modal will take a federation as a prop
- [ ]  Use the data from the federation to fill the first list showing the containers that are included in that federation
- [ ] Use the rest of the containers for the next list to be able to add them to the  federation
- [ ] Add api endpoint to v5 to edit a federation
- [ ] Add action to edit a federation to redux/saga
- [ ] Add tests for these actions 
- [ ] The state of edit federation should be manage in the page until the save button has been clicked
- [ ] When clicking save, it will trigger the update federation action and close the dialog

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2608%3A56434)
