### ISSUE TITLE
Revamping - Create Federations

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2787]
### Description
Create new federations from the v5 federations page. It largely based on edit federations. It will have a section with data on which project and teamspace of the new federation as well as the federation name and the units its on.

### Goals
- [x] Have two buttons in the federations page  where you can trigger the create federations
- [x] Have a new modal dialog to enter the details of the new federation (similar to "Federation Settings")
- [x] After "Continue" on the first dialog box, the second dialog box contains the Edit Federations layout

### Tasks
- [x] Create a modal dialog that will reuse the layout from "Federation Settings"
- [x] Create a modal dialog that will reuse the lists from ""Edit Federation"
- [x] Add api endpoint to v5 to save a new federation
- [x] Add action to save a new federation to redux/saga
- [ ] Add tests for these actions 
- [ ] The state of the new federation should be managed in the page until the save button has been clicked
- [ ] when clicking save, it will  trigger the save new federation action

### User Stories

- [ ] As a user I can't click the continue button on the first modal until I have completed the required fields
- [ ] As a user I can't click "Create Federation" until I have assigned at least one model to the Federation
- [ ] As a user I can hit Cancel or the exit cross to close the modal at any time

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=5496%3A38730)

**Comment by sanmont3drepo** [comment]
The functionality of this was moved to 
#2786

**Comment by The-Daniel** [comment]
> @The-Daniel don't close issues (unless they're part of a bigger issue and got merged into main issue branch), it's part of a process and we close them when they're tagged.

Oops, sorry. I can undo the ones I closed now
