### ISSUE TITLE
Revamping - Share federation 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2788]
### Description
To share a federation there will be a modal dialog showing the link 

### Goals
- [ ] Have a modal dialog showing the link
- [ ] Have a way to trigger the modal
- [ ] Have a way to copy the link 
- [ ] Have a way for sending the link via email

### Tasks
- [ ] Create a modal dialog following the ui design
- [ ] Add a handler to open the modal from the federation item menu
- [ ] Use a service or helper to create the url based on the federation
- [ ] Add a copy to clipboard button that will copy the code
- [ ] Add a link 'send by email' using 'mailto:' as href

### Considerations
Reuse the control from https://github.com/3drepo/3drepo.io/issues/2887

### Related Resources
MockUp : https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2608%3A60696
![image](https://user-images.githubusercontent.com/42032433/144225071-0ef4084a-c14d-48ac-9922-b4bc76aec0be.png)
