### ISSUE TITLE
Revamping - Search federations

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2793]
### Description
In the federations page there will be a search field where the user can filter the federations based on on the keyword

### Goals
- [ ] Filter out  the federations list using the searchfield
- [ ] When there is a search remove both lists and leave just one with the search results
- [ ] Hve a blank state if no result was found

### Tasks
- [ ] Add a searchfield under the appbar
- [ ] Add a action for redux for sarching the list or do it in state of the the federations component (it depends if we want to keep the state when navigating the app)
- [ ] Remove both lists (all and favourites) and leave just one with the results

### Related Resources
MockUp :  https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=821%3A990
