### ISSUE TITLE
Revamping - hook up with containers

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2796]
### Description
We need to get real data for the containers.

### Goals
- [x] All containers will be filled with all the containers for that selected project
- [x] Favourite containers will be filled with the data from the real favourite containers for the selected project

### Tasks
- [x] Add api endpoint */teamspaces/:teamspace/projects/:projectId/containers* in service
- [x] Add redux/saga action for fetching the containers
- [x] Add tests for fetching the containers as depicted in *test\sagas.spec.ts*
- [x] Add selector for all containers
- [x] Add selector for favourites containers
- [x] Trigger the fetching of this data when loading containers. If there were already data loaded dont refetch it.
- [x] Use hook creators (as depicted in *src\v5\services\selectorsHooks\currentUserSelectors.hooks.ts*) and use those in the containers page.
- [x] Show loading feedback when loading the containers

### Related Resources
MockUp : `https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=821%3A1258

**Comment by EmilTheSadCat** [comment]
@carmenfan 
I have some trouble using GET `/teamspaces/{teamspace}/projects/{project}/containers` endpoint.
Unfortunately it doesn't work locally for any already existing projects and it returns 404 `PROJECT_NOT_FOUND`, even though the passed project id is correct. It does work for newly created projects, but I'm not able to add revisions locally.
Is it like this by design? Can you take a look if it works correctly?

**Comment by carmenfan** [comment]
@EmilTheSadCat  are you using the apptension database? give me an example of what you're doing (e.g. the url you're making the request to?)

**Comment by EmilTheSadCat** [comment]
@carmenfan 
I'm using db on host `35.177.108.64`. Example request: `api/v5/teamspaces/charence/projects/5d2de771-ee90-e63e-649d-9c0e00000000/containers`. It's a project with a title `BlackFriars`.

**Comment by EmilTheSadCat** [comment]
@carmenfan It's working now. Thank you :)

**Comment by carmenfan** [comment]
@m1chalkubiak why is it a problem?
