### ISSUE TITLE
Revamping - Add/remove to favourites hook-up

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2797]
### Description
We want to let the user to remove or add a container as a favourite

### Goals
- [x] Users should be able to click the star in the container item , if its fill the container should appear in the favourites list, if not it shouldnt. All should appear in the all containers list.
- [x] Users should be able to click the star in the favourite list as well and remove it from that list.

### Tasks
- [x] Add api endpoint  */teamspaces/:teamspace/projects/:project/containers/favourites*  in api service (take a look at https://github.com/3drepo/3drepo.io/issues/2754)
- [x] Add redux/saga action for adding/removing the containers
- [x] Add tests for adding/removing the containers as depicted in *test\sagas.spec.ts* and test that the favourite/all containters selectors works as intended
### Related Resources
MockUp : https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=821%3A1258
