### ISSUE TITLE
Revamping - Error message popup

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2800]
### Description
When there's an error in the frontend there should be a standard way to show an error message. The idea is to have an easy to trigger  popup message with a customisable error message and the origin of the error.

### Goals
- [x] Show the error popup when something goes wrong

### Tasks
- [x] Add a template popup message that matches the ui design
- [x] Add redux action to trigger the popup with the custom message and origin
- [ ] Add tests for the actions.

### Related Resources
MockUp : https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=1694%3A21238
