### ISSUE TITLE
Federation/model settings update endpoint

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2809]
### Description
We need a v5 endpoint that allows the user to edit the federation/container settings.

#### Update federation settings
v4 counterpart: https://3drepo.github.io/3drepo.io/#api-Model-updateSettings
v5 endpoint: `PATCH /teamspaces/:teamspace/projects/:project/federations/:federation`

**NOTES:**
- payload remains the same as v4 (the v4 doc does not contain every field that can be changed, check the code for full list)
- `Submodels` should not be something that can be updated via this endpoint
- Only admins can edit settings
- Ensure we validate the input (please use yup)
- The user should be able to update parts of the settings, so it's not necessary for the user to give the full settings everytime
- Should respond with 200 but no payload.

#### Update container settings
v4 counterpart: https://3drepo.github.io/3drepo.io/#api-Model-updateSettings
v5 endpoint: `PATCH /teamspaces/:teamspace/projects/:project/containers/:container`

**NOTES:**
- essentially identical to federations

### Goals
- [x] Create endpoint for editing federation settings
- [x] Create endpoint for editing container settings

### Tasks
- [x] Implement endpoint
- [x] Add unit tests
- [x] Add e2e tests
- [x] Add swagger doc
