### ISSUE TITLE
3drepo io v4.19.1 (Release Candidate) QA

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#2824]
### Bugs List
- [x] [Issue & Risks Report error](https://github.com/3drepo/3drepo.io/issues/2824#issuecomment-943541297) (Santiago)
- [x] [Model Upload action not updating in UI](https://github.com/3drepo/3drepo.io/issues/2824#issuecomment-944342311) (Santiago)
- [x] [Safetibase thumbnail not loading](https://github.com/3drepo/3drepo.io/issues/2824#issuecomment-944364374) (Santiago)
- [x] [Model UI update doubling models](https://github.com/3drepo/3drepo.io/issues/2824#issuecomment-944370577) (Santiago)
- <del> [Other teamspace profile pictures don't appear in the list](https://github.com/3drepo/3drepo.io/issues/2824#issuecomment-945806181) </del>  _Cannot reproduce._
- [x] [When you delete a group, there is a 5-10 seconds delay](https://github.com/3drepo/3drepo.io/issues/2824#issuecomment-945935822) (Santiago)

### UI Oddities
- [x] [increase blobs character limit:](https://github.com/3drepo/3drepo.io/issues/2836#issue-1030273815) (carmen)
  - [x] on frontend
  - [x] on backend v4
  - [x] on backend v5 (carmen)

**Comment by mosment3DRepo** [comment]
### Model Upload action not updating in UI
When you upload a new revision of a model, the UI does not update to say that the file is processing. You need to refresh the page to see it.

### Steps to replicate
- Create a new model
- Upload a model file
- Notice the model container still says 0 revisions
- Refresh the page
- Now model says processing

### GIF
![Model Upload](https://user-images.githubusercontent.com/62879582/137502839-506f6fb2-15ee-4fd0-bb2a-93213875f6ed.gif)

**Comment by mosment3DRepo** [comment]
### Federations being created as models in the UI
When a new federation is created, occasionally instead of creating a blue square in the UI it will create a model style white one

### Steps to replicate
- Open TeamSpace
- Create new Federation
- Notice the federation is represented as a white model square instead of a blue federation one (sometimes)

### GIF
This happens sporadically so currently no GIF available

**Comment by BDavydov** [comment]
**Description**
Other teamspace profile pictures don't appear in the list.
I can see my profile picture, but not other account images.


![image](https://user-images.githubusercontent.com/19904513/137746626-a2cb76b6-ffbe-474e-b4bc-2d23b6574055.png)

![image](https://user-images.githubusercontent.com/19904513/137746697-35e636ce-e334-4a12-87c7-1ed0a5dce9fa.png)

**Comment by BDavydov** [comment]
**Description**
No 120 character limit to model name when you update it in the settings menu.

**No warning message**
![image](https://user-images.githubusercontent.com/19904513/137751375-629f7f22-9f24-4128-a41d-5fd50c3143ab.png)

**What it looks like when you save the loooooooooong model name**
![image](https://user-images.githubusercontent.com/19904513/137751493-700a6b8a-09d8-41e8-8306-79e74254f09b.png)

**Comment by BDavydov** [comment]
**Description**
Model tree Select All function selects everything that's in the list. However, when you have isolated model elements and click Select All in the model tree, only visible model elements go in your selection set. Is that a hidden feature or a bug? :/ 

**GIF**
![Model Tree Select All](https://user-images.githubusercontent.com/19904513/137771175-1e82cf00-7ae7-4eaf-9933-29aeb2ee3c21.gif)

**Comment by mosment3DRepo** [comment]
@carmenfan Bugs list done, all relevant bugs included in the task list
