### ISSUE TITLE
Revamping - Containers v2 Layout

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2839]
### Description
Due to a slight change in the designs we will need to make a few visual tweaks to the containers page.

### Goals
Make the containers page easier to navigate and create a clearer hierarchy

### Tasks

- [x] [Increase the font size of the breadcrumb](https://github.com/3drepo/3drepo.io/issues/2839#issuecomment-946919902)
- [x] [Add Project Title Header](https://github.com/3drepo/3drepo.io/issues/2839#issuecomment-946922892)
- [x] [Move tabs below Project Title](https://github.com/3drepo/3drepo.io/issues/2839#issuecomment-946925721)
- [x] [Add Home icon to the start of the breadcrumb](https://github.com/3drepo/3drepo.io/issues/2839#issuecomment-946927319)
- [x] [Move search bar in line with accordion](https://github.com/3drepo/3drepo.io/issues/2839#issuecomment-946928214)
- [x] [Move create new containers & file upload button in line with the accordian](https://github.com/3drepo/3drepo.io/issues/2839#issuecomment-949684546)

### Related Resources

MockUp : https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2242%3A21959

**Comment by mosment3DRepo** [comment]
### Add Project Title Header

Add the project title header below the breadcrumb to make it clear which project the user is working in

![image](https://user-images.githubusercontent.com/62879582/137957799-5da9cf6f-1469-4618-810d-2fab70c363ee.png)

**Comment by mosment3DRepo** [comment]
### Move tabs below Project Title

In order to communicate the heirarchy of the UI better to users, we will move the tab list underneath the new Project Title

![image](https://user-images.githubusercontent.com/62879582/137958238-b1affeae-40a9-4037-b44f-e646c373ef80.png)

**Comment by mosment3DRepo** [comment]
### Move search bar above containers list

Now that the Project Title sits beneath the breadcrumb, there is less room for the search bar. In order to better communicate that you are searching the content of the page, we will move it above the containers list.

Image TBD
