### ISSUE TITLE
Federation/container settings get endpoint 

### ISSUE THREAD

**Issue by ChristosTsiotsias** [3drepo/3drepo.io#2843]
### Description
We need a v5 endpoint that allows the user to get the federation/container settings.

#### GET federation settings
v4 counterpart: https://3drepo.github.io/3drepo.io/#api-Model-getModelSetting
v5 endpoint: `GET/teamspaces/:teamspace/projects/:project/federations/:federation`

#### GET container settings
v4 counterpart: https://3drepo.github.io/3drepo.io/#api-Model-getModelSetting
v5 endpoint: `GET/teamspaces/:teamspace/projects/:project/containers/:container`

### Goals
- [x] Create endpoint for editing federation settings
- [x] Create endpoint for editing container settings

### Tasks
- [x] Implement endpoint
- [x] Add unit tests
- [x] Add e2e tests
- [x] Add swagger doc
