### ISSUE TITLE
Revamping - replace multi-language system

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2857]
### Description
Due to limitations with lingui (it only works on .tsx files), we need to replace the localization system.
The selected new system is formatJs https://formatjs.io/docs/getting-started/message-declaration

### Goals
- [x] Have an extract command that extracts the definitions also  
- [x] Have a compile command
- [ ] Replace \<Trans /\> tags with the proper new tag

### Tasks
- [x] Create extract script built on formatjs extract  (providing similar functionality as linguijs did)
- [x] Make the extract script remove unused entries (just keep the ones that are defined in the sourcecode)
- [x] Create catalogs only for non english (english version is already  being defined in the code) 
- [x] Create compile script that compiles the catalog to a format that formatjs can consume in the sourcecode
- [x] Create intl service file that provides an intl provider for react and non react environment
- [ ] Add simple locale switching as linguijs did.
- [x] Replace \<Trans /\> tag with \<FormattedMessage /\> tags

### Related Resources
https://formatjs.io/docs/getting-started/message-declaration
