### ISSUE TITLE
Authentication Endpoints

### ISSUE THREAD

**Issue by ChristosTsiotsias** [3drepo/3drepo.io#2865]
#### Get logged in user's username

v4 counterpart: https://3drepo.github.io/3drepo.io/#api-Authentication-checkLogin
v5 endpoint: `GET/login`

#### Log in
v4 counterpart: https://3drepo.github.io/3drepo.io/#api-Authentication-login
v5 endpoint: `POST/login`

payload
````js
{
   "username": "alice",
   "password": "AW96B6"
}
````

response
````js
{
   "username": "alice"
}
````

#### Log out
v4 counterpart: https://3drepo.github.io/3drepo.io/#api-Authentication-logout
v5 endpoint: `POST/logout`

### Goals
- [ ] Create endpoint for getting username
- [ ] Create endpoint for loggin in
- [ ] Create endpoint for loggin out

### Tasks

Get username
- [ ] Implement endpoint
- [ ] Add unit tests
- [ ] Add e2e tests

Log in
- [ ] Implement endpoint
- [ ] Add unit tests
- [ ] Add e2e tests
- [ ] Add swagger doc

Log out
- [ ] Implement endpoint
- [ ] Add unit tests
- [ ] Add e2e tests
- [ ] Add swagger doc
- [ ] Add swagger doc

**Comment by keifgwinn** [comment]
A personal request, if you do a GET /login and you're not logged in yet, please don't log that there's been a GET /login that isn't logged in

**Comment by carmenfan** [comment]
> A personal request, if you do a GET /login and you're not logged in yet, please don't log that there's been a GET /login that isn't logged in

I don't think we should start adding specific if conditions to purposely not log a response...

Can't you just filter it in your logging system? What is the issue?

**Comment by keifgwinn** [comment]
perhaps better solved in the frontend ui to not make a call unless it's actively logging in. It just seems inefficient to have a call we know will fail on every time the front page is loaded.

**Comment by carmenfan** [comment]
> perhaps better solved in the frontend ui to not make a unless it know's it'll be a success. currently it'll try and get /login and then fail because it isn't logged in.

It's used to check if a cookie is valid. i.e. this is the first call, if it failed -> it loads login page, if pass it goes straight to teamspace list

we could replace it with something else i guess, but just not entirely sure what the problem is

**Comment by carmenfan** [comment]
>{
   "username": "alice"
}


@ChristosTsiotsias Can we ditch this response? just return 200 like other v5 endpoints. It's one of those ones that I don't quite understand why we're sending data that already exists in the request payload 😆.
