### ISSUE TITLE
Discovering Safety (HSE) Phase 1 Safetibase Improvement

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2871]
### Description
Currently the Safetibase CSV file needs to be manually updated by the Admins on a teamspace, which means the latest risks and mitigations are not available until someone compiles a new CSV.

By creating an opt-in system we will allow all "Agreed (Fully)" and "Agreed (Partially)" risks to be added to the CSV automatically. Their Safetibase Ids would be stored on the CSV so changes to the Safetibase risk will automatically update the record in the CSV file

### Goals

- [x] Allow admins to opt-in to the process on the Teamspace admin page
- [x] When risks are set to "Agreed (Fully)" or "Agreed (Partially)" their data is added to the CSV
- [x] If a risk is subsequently set to void it is removed from the CSV
- [x] When you download the CSV the source risk IDs are maintained, but if they are removed the CSV risk becomes detached from the original
- [x] Add a column in the CSV to include which Project and Model the risk originated from
- [x] When an Agreed risk is updated, update the details in the CSV document

### Technical specification
At the moment, treatment suggestions works by relying on a teamspace admin importing a treatment suggestions csv, which looks something like the following:
![image](https://user-images.githubusercontent.com/11945337/149151835-e2404017-bdea-4fc0-9951-a4413ee2ee95.png)

Upon import, we translate each line of the CSV into individual entries within into a mitigations collection within the teamspace database. When a user of this teamspace creates a risk, they then can utilise the `suggest treatment` functionality, base on the values within the risk data (e.g. the `Risk Category`, `Risk Location` etc), we return a list of suggestions that matches those fields.

#### When risks are resolved
For this issue, if the user has opted into using the feature, we want to dynamically add new entries into the database when we have a resolved risk, if it doesn't exists (i.e. Treatment suggestion is set to `Agreed (Fully)` or `Agreed (Partially)`. So for e.g. if a risk with the following fields is marked as resolved:

We should first check if this rule already exists in the database.
#####  The rule currently does not exist in the database
We should add a new entry, with a reference to the `teamspace::modelId::riskId`, so there will be a new entry in the csv export/database that would look something like this:
![image](https://user-images.githubusercontent.com/11945337/149154160-0d0832a1-70b6-40d4-9588-4b71acaf07a9.png)

Notice that `Referenced Risks` should only be filled if the rule was originally created by us.

##### The rule already exists in the database
We should see if `Referenced Risks` is empty. If it is, this means it was a pre-existing rule that was determined by the user within the original CSV, thus we should just do nothing.

If the referenced risk is not empty, we should add the risk Id of this risk into the list, denoting the number of risks are using this rule.

#### When risks become unresolved
When the risks move from a resolved state (`Agreed (Fully)` or `Agreed (Partially)`), we will need to remove the reference from the database if the rule was inserted into the treatment database from this feature.

This should only happen if this risk id is the sole referee of the rule, otherwise we should remove the reference only.

#### When a resolved risk is updated
If the risk is resolved and the user updated some fields that are dependent upon by the treatment suggestion feature (i.e. fields that are within the CSV), we will need to update the rule.

We should only update the rule if the risk id is the sole referee of the rule, otherwise we should remove the reference, and create a new rule.

### Tasks
- [x] Modify teamspace settings to add a flag to enable/disable automatically add rules into the treatment database
    - [x] Backend changes (v4) to take in the extra flag
    - [x] Front end changes to add a check box `Create Treatment Suggestions from Agreed Risks`
- [x] Modify the wording on the teamspace setting UI for `treatment suggestion`:  from `Last Updated` to `Last Imported`
![image](https://user-images.githubusercontent.com/11945337/149138653-e581cc1d-ac06-4e82-a64c-925fa16ee4ed.png)
- [x] If teamspace has opted into adding the rules:
    1. When a risk has been set to be `Agreed (Fully)` or `Agreed (Partially)`:
        - [x] If this rule exists without any references (i.e. the risk is using a rule from CSV import): do nothing
        - [x] otherwise:
            - [x]  If the rule doesn't exist: Add it into the database with a reference to this risk
            - [x] if the rule already exists: Add this risk as an extra reference to the rule
    2. When a risk has been changed from `Agreed (Fully)` or `Agreed (Partially)` to something else:
        - [x] If the risk is a reference to a rule within the treatment database:
            - [x] if the risk is the only reference in the rule, remove the rule all together
            - [x] if the risk is one of many being referenced in the rule, remove the reference
        - [x] Otherwise: do nothing
    3. When a resolved risk is being updated where changes are made on treatment suggestion fields:
       - [x] apply instructions in rule 2 (i.e. remove the existing rule unless it is also used by some other risk)
       - [x] then apply instructons in rule 1 (i.e. add the new rule with the changed fields)
- [x] CSV management
   - [x] Upon importing a csv - there is no longer a need to store the original CSV
   - [x] On export - we will need to write a brand new CSV base on the data within the treatment database
   - [ ] Write a migration script to remove all records of existing CSVs

**Comment by mosment3DRepo** [comment]
@carmenfan this was the issue discussed earlier

**Comment by carmenfan** [comment]
@mosment3DRepo Some stuff to clarify:

> Allow admins to opt-in to the process on the Teamspace admin page

Can we have a quick mock up on how you want it to look?

>  When risks are set to "Agreed (Fully)" or "Agreed (Partially)" their data is added to the CSV

Presumably there should be 3 scenarios:
-  if the risk is set to `Agreed (X)` and the mitigation suggestion already exists in the database:
    - if the mitigation rule was created originally from a csv import (not created from a risk being mitigated), do nothing
    - if the mitigation rule was created by a different risk, add this risk ID as part of the dependency (i.e. the risk id dependency should be an array of [{project, model, risk Id}]
- If the mitigation suggestion does not exist, add it to the database with this risk ID as its dependency

> If a risk is subsequently set to void it is removed from the CSV

2 questions here:
1. Only remove if it's set to void? what if the user changed it from `agreed` back to `proposed`? or `Rejected` even?

2. As per the addition rules, we should only remove the suggestion if all the dependent risk IDs are removed?


>  Add a column in the CSV to include which Project and Model the risk originated from

If the user downloaded this csv from a different teamspace, and imported it to a separate teamspace, we should remove this new column?

**Comment by mosment3DRepo** [comment]
> > Allow admins to opt-in to the process on the Teamspace admin page
> 
> Can we have a quick mock up on how you want it to look?

![image](https://user-images.githubusercontent.com/62879582/146050223-76b23cda-37ad-46da-bdb9-874f59274e1b.png)

**Comment by mosment3DRepo** [comment]
> > When risks are set to "Agreed (Fully)" or "Agreed (Partially)" their data is added to the CSV
> 
> Presumably there should be 3 scenarios:
> 
> * if the risk is set to `Agreed (X)` and the mitigation suggestion already exists in the database:
>   
>   * if the mitigation rule was created originally from a csv import (not created from a risk being mitigated), do nothing
>   * if the mitigation rule was created by a different risk, add this risk ID as part of the dependency (i.e. the risk id dependency should be an array of `[{project, model, risk Id}]`
> * If the mitigation suggestion does not exist, add it to the database with this risk ID as its dependency

I think this could get confusing based on the potential to edit the risks, I think in all cases we should just add it as a new item. The aim is to allow the admin to clean it up. I think if we over complicate it we may get in a tangle when one risk is edited but another isn't even though they are both listed as a dependency on the same item

**Comment by mosment3DRepo** [comment]
> > If a risk is subsequently set to void it is removed from the CSV
> 
> 2 questions here:
> 
> 1. Only remove if it's set to void? what if the user changed it from `agreed` back to `proposed`? or `Rejected` even?
> 2. As per the addition rules, we should only remove the suggestion if all the dependent risk IDs are removed?

Could we add a column into the CSV to include current status and then filter out any which are proposed, rejected or void when using the treatment suggestion or autofill rules?

**Comment by mosment3DRepo** [comment]
> > Add a column in the CSV to include which Project and Model the risk originated from
> 
> If the user downloaded this csv from a different teamspace, and imported it to a separate teamspace, we should remove this new column?

We should keep it for reference but stop trying to link them together, so it is 'dumb' but the reference is still there in case it needs to be audited

**Comment by carmenfan** [comment]
> > > When risks are set to "Agreed (Fully)" or "Agreed (Partially)" their data is added to the CSV
> > 
> > 
> > Presumably there should be 3 scenarios:
> > 
> > * if the risk is set to `Agreed (X)` and the mitigation suggestion already exists in the database:
> >   
> >   * if the mitigation rule was created originally from a csv import (not created from a risk being mitigated), do nothing
> >   * if the mitigation rule was created by a different risk, add this risk ID as part of the dependency (i.e. the risk id dependency should be an array of `[{project, model, risk Id}]`
> > * If the mitigation suggestion does not exist, add it to the database with this risk ID as its dependency
> 
> I think this could get confusing based on the potential to edit the risks, I think in all cases we should just add it as a new item. The aim is to allow the admin to clean it up. I think if we over complicate it we may get in a tangle when one risk is edited but another isn't even though they are both listed as a dependency on the same item

@mosment3DRepo 

Really don't think this is a good idea, on both on a tech level and on a use case level. This will cause other problems:
- we're going to have duplicated suggestions on the risk suggestions endpoint, i.e. this list is going to be long with identical entries, which may be confusing and hard to navigate:
![image](https://user-images.githubusercontent.com/11945337/146351725-6242e51d-72e7-45be-86a0-5726bc043549.png)
- the CSV will get massive if the risk component is being used frequently, since we're essentially suggesting that every risk that we are recording as mitigated, in the whole teamspace (and in the case of a different teamspace taking in an existing csv, even more)  will get an entry.
- The database table will get clogged up as well - which will impact performance


> I think this could get confusing based on the potential to edit the risks, 

we can make it that if the user edited the risk it pulls the reference from the existing one and creates a new entry if the key fields have been changed, i don't think it's that much of an issue.

> Could we add a column into the CSV to include current status and then filter out any which are proposed, rejected or void when using the treatment suggestion or autofill rules?

What's the point of storing them? can't we just remove them?

**Comment by carmenfan** [comment]
> > > Allow admins to opt-in to the process on the Teamspace admin page
> > 
> > 
> > Can we have a quick mock up on how you want it to look?
> 
> ![image](https://user-images.githubusercontent.com/62879582/146050223-76b23cda-37ad-46da-bdb9-874f59274e1b.png)

I think the wording may be a bit too ambiguous, to me, this just means we turn on suggestions on risk.

**Comment by carmenfan** [comment]
also we may need to change the UI for the treatment suggestion - `last updated` no longer makes any sense as it's essentially updated everytime someone mitigated a risk.

**Comment by mosment3DRepo** [comment]
> > I think this could get confusing based on the potential to edit the risks,
> 
> we can make it that if the user edited the risk it pulls the reference from the existing one and creates a new entry if the key fields have been changed, i don't think it's that much of an issue.

Happy to go with this if it is easy enough to implement

**Comment by mosment3DRepo** [comment]
> > Could we add a column into the CSV to include current status and then filter out any which are proposed, rejected or void when using the treatment suggestion or autofill rules?
> 
> What's the point of storing them? can't we just remove them?

Fair point, ignore that suggestion then

**Comment by mosment3DRepo** [comment]
> also we may need to change the UI for the treatment suggestion csv label - `last updated` no longer makes any sense as it's essentially updated everytime someone mitigated a risk, maybe `last imported` or something

also agreed "last imported" is fine for the UI page

**Comment by mosment3DRepo** [comment]
> > > > Allow admins to opt-in to the process on the Teamspace admin page
> > > 
> > > 
> > > Can we have a quick mock up on how you want it to look?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/62879582/146050223-76b23cda-37ad-46da-bdb9-874f59274e1b.png)
> 
> I think the wording may be a bit too ambiguous, to me, this just means we turn on suggestions on risk.

"Create Treatment Suggestions from Agreed Risks" is probably more accurate but possibly a little verbose, do you know if we have any precedence for a linking to a support article for more details. I can't think of one, but it would be useful here
