### ISSUE TITLE
Create endpoints for assign/revoke/get admin privileges

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2872]
### Description
Admin API Overview

We would like to be able to present regular administrative tasks on the system through the API. This will require establishing a permissions structure for users to have additional permissions, and endpoints to manage those end user permissions, as well as endpoints for license administration and support tasks.

### Goals

- [x] Administrator can grant/revoke administrative permissions to another user
- [x] Administrator can grant/revoke support permissions to another user
- [x] Administrator can grant/revoke license permissions to another user

### Tasks

- [x] Test MongoDB Roles

Utilise MongoDB Roles to create an additional level of permissions for tasks that require higher privileges
Create a number of new endpoints to support administrative tasks

	 "role": "system_admin",
		[ canViewUserRoles, canEditUserRoles ]
	 "role": "support_admin",
		[ canViewUserRoles, canViewLicense  ]
	 "role": "licenseAdmin",
		[ canEditLicense , canViewLicense ]
	 
- [x] Establish final role / privilege configuration
- [x] Establish middleware configuration (present additional permissions in existing authentication structure)
- [x] Create endpoints as described below.
- [ ] Add unit tests
- [ ] Write e2e testing 
- [x] Ensure swagger docs complete 

#### Endpoints for user Addons
- [x] v5 endpoint: `GET /api/v5/admin/roles}`
	optional searches /api/v5/admin/roles?role=[system_admin,...]
	optional searches /api/v5/admin/roles?user=[abc,zyx]
- [x] v5 endpoint: `PUT /api/v5/admin/roles}`
- [ ] v5 endpoint: `PATCH /api/v5/admin/roles}`
- [x] v5 endpoint: `DELETE /api/v5/admin/roles}`

Requires [ systemroles_read ] permission to view
Requires [systemroles_write] permission to modify

Only works with an interactive log in for the session, doesn't work on API key alone. (Design Decision with Carmen 2022-01-21 meeting)

any valid permission acceptable in the call, doesn't have to list them all.
cannot remove own permissions

payload
````js
	{
	  users: [
		{user: "abc", role: "system_admin"},
		{user: "xyz", role: "support_admin"},
	  ]
	}
````
response GET 200

````js
	{
	  users: [
		{user: "abc", role: "system_admin"},
		{user: "xyz", role: "support_admin"},
	  ]
	}
````
response 400

````js
	{
	  "code": "invalidArguments",
	  "message": "The arguments provided are not valid",
	  "place": "PATCH /api/v5/admin/roles",
	  "status": 400
	}
````
response 401

````js
	{
	  "code": "notLoggedIn",
	  "message": "You are not logged in",
	  "place": "GET /api/v5/admin/roles",
	  "status": 401
	}
````
response 403

````js
	{
	  "code": "notAuthorized",
	  "message": "You do not have sufficient access rights for this action",
	  "place": "GET /api/v5/admin/roles}",
	  "status": 403
	}
````
response 404

````js
	{
	  "code": "userNotFound",
	  "message": "User not found.",
	  "place": "VERB /api/v5/admin/roles",
	  "status": 404
	}
````

**Comment by carmenfan** [comment]
>  "role": "io.systemAdmin",
 "role": "io.supportAdmin",
 "role": "io.licenseAdmin",

Any reason why we want to prepend it with `io.`? we don't really have this sort of notation used anywhere else within the system and i'm not sure if we'll ever have things like bouncer.admin, unity.admin. It's so fine grained it's unlikely to happen within our 3D Repo's life time.

**Comment by carmenfan** [comment]
>  Test MongoDB Roles
Utilise MongoDB Roles to create an additional level of permissions for tasks that require higher privileges
Create a number of new endpoints to support administrative tasks

I'm not sure whether there's a mis-understanding here. Because I don't feel like it's something we need to test -we're [already using it](https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/models/teamspaces.js#L46) the way I'm envisaging we use it here.

> Establish final role configuration (hierarchical required?)

I don't think so - it's only beneficial to do it this way if we are authenticating the user to do database operations (as mongo will be permission checking this base on the roles) - which we won't be doing.

**Comment by carmenfan** [comment]
> GET /api/v5/admin/users/{username}/addOns

Like I said in the earlier comment, i don't know if it's a confusion on how this should work, but I don't see them as addOns. They are the level of privilege the individual user has on the system. 

To fix https://github.com/3drepo/3drepo.io/issues/566, my intention is to add a basic `user` in the same manner. So in the future every one will have 1 role in the database. Coupled with the suggestion of grouping things in [feature actions](https://github.com/3drepo/3drepo.io/issues/2874#issuecomment-974625043), I think the endpoints should be more like `/api/v5/admin/roles/users/{username}`

**Comment by carmenfan** [comment]
>  v5 endpoint: POST /api/v5/admin/users/{username}/addOns
 v5 endpoint: PATCH /api/v5/admin/users/{username}/addOns

Following on from the above, we would just want a PATCH with a very similar payload to the response of GET request 

e.g a PATCH request with the payload:
````js 
{
  users: [
    {user: "abc", role: "systemAdmin"},
    {user: "xyz", role: "supportAdmin"},
  ]
}
````

would grant system admin role to abc and support admin role to xyz, and remove any pre-existing roles they may be assigned to

**Comment by carmenfan** [comment]
We may want to impose a restriction on the admin user to prevent them from relinquishing themselves from their privileges - to avoid the system having no admins - i.e. you can only update someone else's privileges, and if you want yours revoked, some other admin has to do it for you

**Comment by keifgwinn** [comment]
> > "role": "io.systemAdmin",
> > "role": "io.supportAdmin",
> > "role": "io.licenseAdmin",
> 
> Any reason why we want to prepend it with `io.`? we don't really have this sort of notation used anywhere else within the system and i'm not sure if we'll ever have things like` bouncer.admin`, `unity.admin`. It's so fine grained it's unlikely to happen within our 3D Repo's life time.

Habit as I am handling the other pieces of software on a regular basis. In environments where multiple pieces of software interact with the same resources I like to define which bit of the system owns those elements.

> I'm still not convinced we need `licenseAdmin`, if we want it more fine grained then it may make sense to think about this differently - orientate it around 3D Repo's teams - support needs support work, sales teams may want access to give pilot/enterprise license and see limited amount of business intelligence.

The reasoning for it here was that as license modification rights is something that could be granted to an individual and the end points were clustered together it made sense to say if you have license flag you can modify anything on the /admin/subscriptions/ section. We currently have quite blended roles/responsibilities so being able to pick and chose levels of permissions across individuals made sense. A sales person with more tech skills can be given support flags and automation can be given license flags only.

**Comment by keifgwinn** [comment]
> > Test MongoDB Roles
> > Establish final role configuration (hierarchical required?)
> I don't think so - it's only beneficial to do it this way if we are authenticating the user to do database operations (as mongo will be permission checking this base on the roles) - which we won't be doing.

'test' I meant is is working out the exact role structure to the point of code, same with hierarchical which I added because of our teams chat. I saw that the mongo roles/permissions/middleware was looking like we're actually doing the database activities as the named user so I wanted to investigate the roles a bit more.

> And i don't see it as an additional level of permissions for the tasks - I see it as a replacement to your whole userAddOn idea.

User addons came from the user/teamspace blend, the existing teamspace Addons configuration in the users customData, so I was aligning it all to closely match the existing use and add the user distinction. Underneath it's roles granted to mongo users so would just represent those under the endpoints. Changing the structure makes no odds to how it actually implements.

**Comment by carmenfan** [comment]
> Habit as I am handling the other pieces of software on a regular basis. In environments where multiple pieces of software interact with the same resources I like to define which bit of the system owns those elements.

I don't quite see it that way, the data we're manipulating is on the database level, some teamspace addOns are not utilised by io but by bouncer etc.

We want to make it extensible but not over engineered - and I think calling these io. admins might confuse anyone who is reading or editing the code. I'd suggest to ditch the prefix until we see a need - in which case the way middleware works should make it quite simple to alter.

> The reasoning for it here was that as license modification rights is something that could be granted to an individual and the end points were clustered together it made sense to say if you have license flag you can modify anything on the /admin/subscriptions/ section. We currently have quite blended roles/responsibilities so being able to pick and chose levels of permissions across individuals made sense. A sales person with more tech skills can be given support flags and automation can be given license flags only.

This is why I think we need input from @mosment3DRepo . This should be closely aligned to usecase instead of trying to engineer something that doesn't exist - for e.g. if licenseAdmin is never used then we're coding and maintaining an extra layer of logic for nothing.

Again I'm suggesting this for the principle of minimal but extensible - as long as our middleware checks for the privilege we're designing (e.g.`canEditLicense` `canViewLicense`) etc, instead of checking specific roles (e.g. `isLicenseAdmin`, `isSupprtAdmin`) then it's just a matter of changing the middleware check logic if we ever define new roles (any roles)

I feel quite strongly about this front, because 3drepo.io permissions system springs to mind and the way we made it so over engineered has become a nightmare to maintain/extend.

> User addons came from the user/teamspace blend, the existing teamspace Addons configuration in the users customData, so I was aligning it all to closely match the existing use and add the user distinction. Underneath it's roles granted to mongo users so would just represent those under the endpoints. Changing the structure makes no odds to how it actually implements.

Yea I figured this might be what you mean, but I don't think we should present this as an add On to accounts - The way I see it, this is more like the level of privilege the user has on the system. This is more inline with user permissions - we don't put teamspace admin as a addOn privilege, you're a teamspace admin of the teamspace, or you're a user (or project admins of speciifc projects) within the teamspace.

**Comment by carmenfan** [comment]
Establish time estimates for each tasks Start working on it
Testing MongoDB roles to make sure I understand it - 2 days 
Work out exact MongoDB Roles - 1 days
Establish middleware configuration (present additional permissions in existing authentication structure) - 3 days
Create endpoints as described below. - 1.5 weeks?
Add Unit Tests - 1 week?
e2e testing -1  week?
Swagger docs - 1 day

**Comment by keifgwinn** [comment]
Meeting today we decided to move the initialisation into a utility migration script based off #2352 scripts
