### ISSUE TITLE
Create endpoints for teamspace Addons

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2873]
### Description
teamspace addOn configuration

We would like to be able to present regular administrative tasks on the system through the API. This ticket describes endpoints for teamspace addOn configuration

### Goals

- [ ] licenseAdmin can modify teamspace addons on a specified teamspace

### Tasks

- [ ] Write endpoints 
- [ ] Add unit tests
- [ ] Write e2e testing 
- [ ] Ensure swagger docs complete 

#### Endpoints for Teamspace Addons

- [ ] v5 endpoint: `GET /api/v5/admin/addOns`
		?addOn=[] //PowerBI, srcEnabled
		?teamspace=[]
- [ ] v5 endpoint: `PUT /api/v5/admin/addOns`
- [ ] v5 endpoint: `PATCH /api/v5/admin/addOns`
- [ ] v5 endpoint: `DELETE /api/v5/admin/addOns`

Requires [ supportAdmin, licenseAdmin ] permission for GET
Requires [ supportAdmin, licenseAdmin ] permission, individual addOns are optional in the post/patch

payload
````js
	{
	   "teamspace": {
			"hereEnabled": true,  
			"vrEnabled": true,  
			"powerBIEnabled": true, 
			"srcEnabled": true, 
		}
	}
````
response GET 200

````js
	{
	   "a": {
			"hereEnabled": true,  
			"vrEnabled": true,  
			"powerBIEnabled": true, 
			"srcEnabled": true, 
		},	
	   "b": {
			"hereEnabled": true,  
			"vrEnabled": true,  
			"powerBIEnabled": true, 
			"srcEnabled": true, 
		},	
	}

````
response 400

````js
	{
	  "code": "invalidArguments",
	  "message": "The arguments provided are not valid",
	  "place": "PATCH /api/v5/admin/addOns",
	  "status": 400
	}
````
response 400

````js
	{
	  "code": "invalidArguments",
	  "message": "The arguments provided are not valid",
	  "place": "PUT /api/v5/admin/addOns",
	  "status": 400
	}
````
response 401

````js
	{
	  "code": "notLoggedIn",
	  "message": "You are not logged in",
	  "place": "GET /api/v5/admin/addOns",
	  "status": 401
	}
````
response 403

````js
	{
	  "code": "notAuthorized",
	  "message": "You do not have sufficient access rights for this action",
	  "place": "GET /api/v5/admin/addOns",
	  "status": 403
	}
````
response 404

````js
	{
	  "code": "teamspaceNotFound",
	  "message": "Teamspace not found.",
	  "place": "GET /api/v5/admin/addOns",
	  "status": 404
	}
````

**Comment by carmenfan** [comment]
Similar sentiment here to https://github.com/3drepo/3drepo.io/issues/2874#issuecomment-974625043

I think we should group things by `addOn` first on the routes.

**Comment by carmenfan** [comment]
> POST /api/v5/admin/teamspaces/{teamspace}/addOns

Similar question to this one https://github.com/3drepo/3drepo.io/issues/2874#issuecomment-974626491

**Comment by carmenfan** [comment]
@keifgwinn  to change:
- remove /teamspaces/:teamspace
- use query string to do GET with filter

**Comment by keifgwinn** [comment]
Made the suggested updates
