### ISSUE TITLE
Create endpoints for teamspace Licensing

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2874]
### Description
teamspace license configuration

We would like to be able to present regular administrative tasks on the system through the API. This ticket describes endpoints for teamspace subscription configuration

### Goals

- [ ] licenseAdmin can modify teamspace subscriptions on a specified teamspace

### Tasks

- [ ] Write endpoints 
- [ ] Write e2e testing 
- [ ] Ensure swagger docs complete 

#### Endpoints for Teamspace license

- [ ] v5 endpoint: `GET /api/v5/admin/subscriptions/teamspaces/:teamspace`
- [ ] v5 endpoint: `PUT /api/v5/admin/subscriptions/teamspaces/:teamspace/:subscriptionName`
- [ ] v5 endpoint: `DELETE /api/v5/admin/subscriptions/teamspaces/:teamspace/:subscriptionName`

Requires [ systemAdmin, licenseAdmin ] permission
subscriptionName one of [ "discretionary", "enterprise", "project", "internal" ]

payload optional one or both of these
````js

		{
			"collaborators" : int,
			"data" : int,
			"expiryDate" : ms,
		}
	

````
response GET /api/v5/admin/subscriptions/teamspaces/:teamspace 200

````js
	{
		"discretionary" : {
			"collaborators" : 10,
			"data" : 2000,
			"expiryDate" : 1234567890
		}
	}


````
response 400

````js
	{
	  "code": "invalidArguments",
	  "message": "The arguments provided are not valid",
	  "place": "PUT /api/v5/admin/subscriptions/teamspaces/:teamspace/:subscriptionName",
	  "status": 400
	}
````
response 401

````js
	{
	  "code": "notLoggedIn",
	  "message": "You are not logged in",
	  "place": "GET /api/v5/admin/subscriptions/teamspaces/:teamspace",
	  "status": 401
	}
````
response 403

````js
	{
	  "code": "notAuthorized",
	  "message": "You do not have sufficient access rights for this action",
	  "place": "GET /api/v5/admin/subscriptions/teamspaces/:teamspace",
	  "status": 403
	}
````
response 404

````js
	{
	  "code": "teamspaceNotFound",
	  "message": "Teamspace not found.",
	  "place": "GET /api/v5/admin/subscriptions/teamspaces/:teamspace",
	  "status": 404
	}
````

**Comment by keifgwinn** [comment]
changed from license to subscriptions to match the existing subscription naming on other calls

**Comment by carmenfan** [comment]
Thinking more about this. I feel like it might make more sense to group endpoints by feature actions instead of teamspaces.

Thinking about the future work use cases:
- We want to see a list of teamspaces with subscriptions
- We want to see a list of teamspaces with subscription of a certain type

By grouping the routes with teamspace first, these will follow a different pattern, and unless we want the admin api to effectively be an open door to the database (which personally, I don't see it being the best idea), i think we have very limited use to group things by teamspaces

so Perhaps it's better for end points to be this way round:
`/api/v5/admin/subscriptions/teamspaces/{teamspace}`

**Comment by carmenfan** [comment]
> payload optional one or both of these

		{
			"collaborators" : int,
			"data" : int,
			"expiryDate" : ms
		}
	

we also have a `pilot` flag, which was added in by request but not sure whether they still want it. check with @anorrie

**Comment by carmenfan** [comment]
> GET /api/v5/admin/teamspaces/{teamspace}/subscriptions/{subscriptionName}

I feel like we don't really need this

**Comment by carmenfan** [comment]
> POST /api/v5/admin/teamspaces/{teamspace}/subscriptions/{subscriptionName}

We may want to change this to a PUT. The question goes down to do we care if the teamspace already has a license? Because POST should error if it already has one (in which case we should add an expected response error to this issue)

If we say that most of the time when we use this call, we just want to add new or overwrite existing license to the one i'm updating to now, then PUT is more appropriate

**Comment by anorrie** [comment]
Happy to remove the pilot flag if it makes life easier and just use discretionary for pilots. We don't use it much as we now charge for pilots so they are effectively commercial anyway

**Comment by keifgwinn** [comment]
I've updated with the comments collected so far.

**Comment by keifgwinn** [comment]
[12:50] Andrew Norrie
ideally we would have Discretionary/ Project / Enterprise 

adding another license type at this stage wouldn't be too hard would it? just need to make sure the reporting understood it.

**Comment by carmenfan** [comment]
> [12:50] Andrew Norrie ideally we would have Discretionary/ Project / Enterprise
> 
> adding another license type at this stage wouldn't be too hard would it? just need to make sure the reporting understood it.

Yea, we don't look for particular license name in the code, we do however do it on reporting scripts

**Comment by carmenfan** [comment]
If we're going to extend this we may want to add staff/internal as a type, and only staff/internal can have unexpired license.
