### ISSUE TITLE
Create endpoints for support information

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2875]
### Description
We would like to be able to get additional information to assist in support queries.

### Goals

- [ ] support can access the requested information

### Tasks

- [ ] Write endpoints 
- [ ] Write e2e testing 
- [ ] Ensure swagger docs complete 
- [ ] v5 endpoint: `GET /api/v5/admin/users/{username}`

Requires [ systemAdmin, supportAdmin ] permission

payload
````js

````
response GET 200

````js
{
	"user": "johnPaul01",
	"firstName": "John",
	"lastName": "Paul",
	"company": "3D Repo Ltd",
	"email": "xample@email.com",
	"job": "Project Manager",
	"lastLoginAt" : ms,
	"createdAt" : ms,
	"loginInfo" : {
		"lastFailedLoginAt" : ms
	},
	"resetPasswordToken": {
		"token":"xxx",
		"expiredAt": ms,
	},
	"avatar": { "data": <base64> },
}
````

**Comment by carmenfan** [comment]
I'm once again struggling to understand why we need this. Majority of this info @3drepo/product-team has via intercom already. Perhaps something to discuss in the meeting?

**Comment by carmenfan** [comment]
- Would like to retrieve password token

**Comment by keifgwinn** [comment]
@3drepo/product-team can you confirm we're parking this for now
