### ISSUE TITLE
Revamping - Delete container modal

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2883]
### Description
For deleting containers there should be a popup acccesible through the menu in the item.

**Permissions for this?**

### Goals
- [ ] Users with permissions can trigger the popup for deleting the container
- [ ] A backend call should take place and delete the container

### Tasks
- [x] Create the popup using the popup system and follow the ui 
- [ ] Add delete endpoint to api service
- [x] Add redux/saga action for deleting the container
- [x] Add frontend test for the saga
- [ ] Show feedback after the container had been deleted?

###  Considerations 
Repurpose the components from `src\v5\ui\components\shared\modals\templates\alertModal\alertModal.component.tsx` to reuse on this popup. 

### Related Resources
![image](https://user-images.githubusercontent.com/42032433/144103719-0645cab3-ca7c-4f9f-aa3a-c2fff642a5fa.png)

MockUp : https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3329%3A49276
Delete container endpoint issue: https://github.com/3drepo/3drepo.io/issues/2769

**Comment by carmenfan** [comment]
> Permissions for this?

teamspace/project admin only

which reminds me, there's another thing we haven't done - adapt the containers/feds page for non admin views. we probably need to consider what they look like when some buttons are missing @mosment3DRepo  @george-hadfield

**Comment by sanmont3drepo** [comment]
> > Permissions for this?
> 
> teamspace/project admin only
> 
> which reminds me, there's another thing we haven't done - adapt the containers/feds page for non admin views. we probably need to consider what they look like when some buttons are missing @mosment3DRepo @george-hadfield

There's also the option of having them disabled with some tooltip explaining the permissions needed for that action.

**Comment by carmenfan** [comment]
> > > Permissions for this?
> > 
> > 
> > teamspace/project admin only
> > which reminds me, there's another thing we haven't done - adapt the containers/feds page for non admin views. we probably need to consider what they look like when some buttons are missing @mosment3DRepo @george-hadfield
> 
> There's also the option of having them disabled with some tooltip explaining the permissions needed for that action.

@mosment3DRepo  mentioned (maybe in another issue, maybe in a meeting, I forgot).

Basically we will aim to implement the whole thing with admins only in mind, and worry about the variations later

**Comment by The-Daniel** [comment]
Should something different happen when trying to delete a favourite container? Extra dialog, or inability to do so until you unfavourite it?

**Comment by carmenfan** [comment]
@The-Daniel Nope, just go ahead and delete it. What we need to make sure is that upon deletion it's removed from both lists
