### ISSUE TITLE
Revamping - Delete Federation modal

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2886]
### Description
For deleting federation there should be a popup acccesible through the menu in the item.

### Goals
- [ ] Users with permissions can trigger the popup for deleting the federation
- [ ] A backend call should take place and delete the federation

### Tasks
- [ ] Create the popup using the popup system and follow the ui 
- [ ] Add delete endpoint to api service
- [ ] Add redux/saga action for deleting the federation
- [ ] Add frontend test for the saga

###  Considerations 
Base this of https://github.com/3drepo/3drepo.io/issues/2883

### Related Resources
MockUp : https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3329%3A49276
Delete container endpoint issue: https://github.com/3drepo/3drepo.io/issues/2769
