### ISSUE TITLE
Revamp - Wrap up basic routing without design

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2894]
### Description
In order to be able to make it easier  test, tackle navigation issues that might arise and also as source of inspiration for ui design  basic routing starting with `/v5/dashboard` should be provided. 

### Goals
- [ ] `/v5/dashboard` is accessible
- [ ] Users can select a teamspace in `/v5/dashboard` and navigate to it
- [ ] Users can select a project in `/v5/dashboard/{teamspaceid}` , when  selected it should navigate to `/v5/dashboard/{teamspaceid}/{projectid}`
**definition in progress**

### Tasks
- [ ] Add content to  `/v5/dashboard` with a list of the user's teamspaces in whatever shape (combo box/links)
- [ ] After a selection navigate to  `/v5/dashboard/{teamspaceid}`
- [ ] Add content to  `/v5/dashboard/{teamspaceid}` with a list of the user's projectsin whatever shape (combo box/links)
- [ ] After a selection navigate to  `/v5/dashboard/{teamspaceid}/{projectid}`
- [ ] Users should be able to use the browser's back and foward buttons after navigation and should show the correct data

**Comment by mosment3DRepo** [comment]
@sanmont3drepo can I close this?

**Comment by carmenfan** [comment]
@mosment3DRepo  it's been in staging since 4.21.0, so yes closing.
