### ISSUE TITLE
Honeycomb integration tests

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2895]
### Description

Possible elastic replacement system is called Honeycomb, and requires a few packages to be installed as per the installation instructions.

### Goals
- [ ] Testing honeycomb behaviour as a suitable replacement for elastic
### Tasks
- [ ] Add required software
- [ ] Add temp configuration options suitable for testing.

### Related Resources

Documentation : [Honeycomb Docs](https://docs.honeycomb.io/getting-started/quickstart/#step-2-instrument-your-application-to-send-telemetry-data-to-honeycomb)
