### ISSUE TITLE
Ability to upload a new revision to a federation

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2901]
#### Upload a new revision in an existing federation
v4 counterpart: https://3drepo.github.io/3drepo.io/#api-Model-updateModel
payload:
```` json
{
   "submodels" : ["container ID 1", "container ID 2"]
}
````

### Goals
The user should be able to submit a new revision if they have sufficient permissions

### Tasks
- [ ] Middleware check
  - [ ] Schema of the payload is correct
  - [ ] User has sufficient permissions
  - [ ] Every submodel exists within the project
- [ ] Endpoint
- [ ] Event notification
- [ ] unit tests
- [ ] e2e tests
- [ ] swagger doc
