### ISSUE TITLE
Revamping - Container settings

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2902]
### Description
User should be able to update the settings for the containers like in v4. This will allow them to change the container name, description  code and units as well as the GIS survey point

### Goals
- [ ] Users can click on edit in the menu item list for the container
- [ ] Users can change the basic container properties as name, description, code, units
- [ ] Users can change the GIS survey point, that means latitude, longitude, angle , x, y and z.
- [ ] Users are able to select the default view for the container

### Tasks
- [ ] Create a modal reusing the new containers modal components
- [ ] Add API endpoint to the API service.
- [ ] Add a view selection component
- [ ] Add a save container settings saga function
- [ ] New database schema for groups (present it here)

### For consideration
The form should be treated as a more complex input, there shouldnt be anything related to redux until the settings are saved that it makes the request to save the container.

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3975%3A30433)
