### ISSUE TITLE
Try out refactoring search functionality (move to component)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2907]
### Description
The code for searching containers and federations seems a little to complex right now. Les try to find out if moving that from redux to the component can lead to generalization and simpler code.

### Goals
- [x] To see if there's a better way of searching dashboard lists

### Tasks
- [x] Move search code from redux to the component
- [x] Try other ideas that might ocurr
