### ISSUE TITLE
Refactor ellipsis menu containers/federations

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2909]
### Description
The ellipsismenu has been implemented by creating a `<EllipsisButtonWithMenu />` with a list as prop. I think that this is not a very good approach, the developer must have extra knowledge for the format of this list and is not very component oriented. Refactoring to a more react-like easy to use would enhance readability and componentization. 

### Goals
- [ ] Provide the same functionality as before but with a more  react approach
- [ ] Replace it in containers and federations

### Tasks
- [ ] separate `<EllipsisButtonWithMenu  >` into `<EllipsisMenu  />` and `<EllipsisMenuItem />`
- [ ]  implement the lists for containers
- [ ]  implement the lists for federations

### Details
Example of  reimplementation `<EllipsisContainerMenu />`:

-  In  `src\v5\ui\routes\dashboard\projects\containers\containersList\containerListItem\containerListItem.component.tsx` it should look this way:
```
...
			<DashboardListItemIcon selected={isSelected}>
				<EllipsisContainerMenu  container={container}/>
			</DashboardListItemIcon>
...
```
- `<EllipsisContainerMenu />` (this would be a new component) would look this way:
```
const ContainerEllipsisMenu =  (container:IContainer) => {
  <EllipsisMenu>
    <EllipsisMenuItem onClick="...">
      <FormattedMessage id="containers.ellipsisMenu.loadContainer" defaultMessage="Load Container in 3D Viewer" />
    <EllipsisMenuItem />
         ....  
  <EllipsisMenu>
...
```
