### ISSUE TITLE
Load federation with viewpoint

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2910]
### Description
Federation can hold multiple views. In order to load a federation in the 3d viewer with a selected view, we need some sort of menu for the user to select that view and enter the federation with the selected view

### Goals
- [ ] Users can see a list of all the available views for the federation
- [ ] Users can copy the link for that viewpoint to share it
- [ ] Users can enter the federation using a selected viewpoint 

### Tasks
- [ ] Create redux/saga for fetching the federation's viewpoints
- [ ] Create a modal with the list for selecting the views
- [ ] Add copy button/link for each item
- [ ] Enter the 3d viewer with the selected viewpoint

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3329%3A46998)

**Comment by AsiteZane** [comment]
Won't remove but very low prio given we haven't discussed this with any customers as a necessary feature.
