### ISSUE TITLE
Upload containers - Drag and drop uploader

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2912]
### Description
Have a reusable control for drag/drop files for uploading them.  It should also have a the possibility to browse files.

### Goals
- [ ] Have a control that adapts to the size of its container
- [ ] It should be easy to easy to use anywhere we want to upload files

### Tasks
- [ ] Create a mockup popup for testing out the component or use the one existing
- [ ] Create a component matching the style defined in figma
- [ ] Add support to drag and drop files
- [ ] Add asupport for browsing files
- [ ] Make sure is multilanguage

### For consideration
The component should act like an input (of file type) the actual uploading will be done by whichever component holds it.

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3096%3A48896)

**Comment by carmenfan** [comment]
now part of #2698
