### ISSUE TITLE
Upload containers - Edit container settings control (right panel)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2913]
### Description
This is part of the upload containers feature ( #2698 ) . For editing the data of a container before uploading the files. 

### Goals
- [ ] Users can see the basic properties of a container (it can be a new or an already existing container) in a form
- [ ] Users can edit the basic properties

### Tasks
- [ ] Create a mockup popup for testing out the component or use the one existing
- [ ] Make the collapsable sidebar showing the edit container settings  with a way to show/hide it
- [ ] Have a component that takes a container as props
- [ ] Make a form that shows the basic fields of the container (units, category, container code, container description, revision description)

### For consideration
The whole component can be thought as an input so it could be managed by a react-hook-forms. That means to replicate the input interface (onChange, value, etc)

### Scope
This issue is for the right panel in the the upload modal only. This means open/close the right panel (with its animation), and having editable fields for changing the container fields. also al the styling within that panel.

### Related Resources
[MockUp
](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3096%3A52458)

**Comment by carmenfan** [comment]
@ChristosTsiotsias check if we updated v5 endpoint to support timezone
