### ISSUE TITLE
Upload containers - Upload item (edition)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2914]
### Description
Is a visual representation of which files are going to be uploaded  and a fast way to create a container (or assign the file to an already existing container). It will be have a selected mode, providing feedback when this item is being selected for edition. It will also have  a delete icon and a edit icon.

This will be part of the modal in #2698.  

### Goals
- [ ] Users can see which files is being uploaded
- [ ] Can set a destination for the file.
- [ ] Users can see feedback when there are errors.
- [ ] Users can see when the item has been selected.

### Tasks
- [ ] Create a mockup popup for testing out the component or use the one existing
- [ ] Create a component item that shows the useravatar, the filename, the size of the file, the destination, revision name and  edit/delete icon buttons
- [ ] Try to reuse the list controls from containers/federations

### For consideration
For the autocomplete reasearch: 
https://mui.com/components/autocomplete/

The destination field is a bit complex, split it in another component.

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2919%3A44408)

**Comment by carmenfan** [comment]
Merged into https://github.com/3drepo/3drepo.io/issues/2698
