### ISSUE TITLE
Upload containers - Upload item (progress)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2915]
### Description
Is a visual representation of the files when they are  being uploaded. For readability is a different component than https://github.com/3drepo/3drepo.io/issues/2914.

This is part of #2698 

### Goals
- [ ] Users can see the files that are being uploaded, destination and revision name
- [ ] It shows the progress status of the file being uploaded
- [ ] It shows if the files was successfully uploaded or if it failed

### Tasks
- [ ] Use the mockup popup for setting the files and uploading them 
- [ ] Create an item reusing the components for #2914 following the ui design
- [ ] Create a upload progress component for showing the progress of the file and failed status 
- [ ] Add api/sagas for uploading the file
- [ ] If the api/sagas files for creating a container is not there create it 
- [ ] Add tests for sagas

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2874%3A69529) 
[Endpoint to upload a file to a container 
](https://github.com/3drepo/3drepo.io/issues/2770)
[Endpoint to create a container](https://github.com/3drepo/3drepo.io/issues/2769)

**Comment by carmenfan** [comment]
Merged in to https://github.com/3drepo/3drepo.io/issues/2698
