### ISSUE TITLE
Profile endpoints

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2924]
### Description
Create v5 endpoints to facilitate the[ profile page.](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3676%3A29600)

#### GET user profile
v4 endpoint: https://3drepo.github.io/3drepo.io/#api-User-getProfile

route: `GET /user` 
payload: none
response: same as v4. (note: the current v4 payload also generates an intercom hash - let's ignore for now, i feel like it should come from a different endpoint)

#### Update user details
v4 endpoint: https://3drepo.github.io/3drepo.io/#api-Account-updateUser
route: `PUT /user`
payload: same as v4 (note:  password update is also done via this endpoint, but it doesn't show on the documentation)
response: none (just http code is fine)

Notes:
- make sure we check character length, email validation, password strength etc on the data.
- this endpoint should **NOT** be accessible via API key authentication

#### Generate API Key
v4 endpoint : https://3drepo.github.io/3drepo.io/#api-User-generateApiKey

route: `POST /user/key`
payload: none
response: same as v4

NOTE: 
- this endpoint should **NOT** be accessible via API key authentication

#### Delete API key
v4 endpoint: https://3drepo.github.io/3drepo.io/#api-User-deleteApiKey_HTTP_1_1_200_OK___

route: `DELETE /user/key`
payload: none
response: none (http code only, unless errored)

NOTE: 
- this endpoint should **NOT** be accessible via API key authentication
- 
#### GET Avatar
v4 endpoint : https://3drepo.github.io/3drepo.io/#api-Account-getAvatar

route: `GET /user/avatar`
payload: none
response: same as v4.

#### Upload a new avatar
v4 endpoint: https://3drepo.github.io/3drepo.io/#api-Account-uploadAvatar 

route: `PUT /user/avatar` (Note this is a **PUT** when it used to be **POST**)
payload: same as v4 - apart from we don't need `user` field, just a file is fine.

- Make sure we are still imposing the file size limit
- check supported format

### Goals
- [x] The user should be able to get their profile information
  - [x] This endpoint should work with API keys authentication
- [x] The user should be able to update their profile information
  - [x] This endpoint should **not** work with API keys authentication
  - [x] Payload data should be validated, and relevant error input if it failed
- [x] The user should be able to generate/delete api keys
  - [x] This endpoint should **not** work with API keys authentication
- [x] The user should be able to view their current avatar
  - [x] returns 404 not found if there is no avatar
- [x] The user should be able to update their avatar
  - [x] validation check should be in place for supported format, file size.

### Tasks
_To be filled in by the developer_
