### ISSUE TITLE
The height of the empty favourites list should be the same as when it has just one item in containers and federations

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2928]
### Description
There is a minor height difference with the height of the empty favourite list and the favourite list with one item. They should be the same height

### Goals
- [ ] Have the same height in the  empty  favourite lists and the case when there is one item.

### Tasks
- [ ] Fix the style in the empty favourite favourite list in containers
- [ ] Fix the style in the empty favourite favourite list in federations.

### Related Resources
This:

![image](https://user-images.githubusercontent.com/42032433/148250324-02393c4c-bafe-4176-8a24-2ed29d2c6ce1.png)

And this:
![image](https://user-images.githubusercontent.com/42032433/148250370-82fd1509-feb5-452e-8e54-393d978044b3.png)

should have the same height
