### ISSUE TITLE
View revisions/hide revisions in container item menu

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2931]
### Description
In the containers item menu there is a 'View revisions' entry. When clicked it should select that container and show the revisions, if its already showing the revisions it should read 'Hide revisions' instead and deselect the container.

### Goals
- [ ] Users can show the revisions when clicking on  the 'View revisions' entry in the dropdown menu for the containers
- [ ] Users can hide the revisions when clicking on  the 'Hide revisions' entry in the dropdown menu for the containers

### Tasks
- [ ] show 'View revisions' in the menu entry for the container if the  revisions for that containers are not being shown
- [ ] show 'Hide revisions'  in the menu entry for the container if the revisions for that containers are being shown
- [ ] Show the revisions (select) the container if the user clicks in 'View revisions' 
- [ ] Hide the revisions (deselect) the container if the user clicks in 'Hid revisions' 

### Related Resources
![image](https://user-images.githubusercontent.com/42032433/148418874-e7e6963e-d9f1-4667-84ae-369ddce4481f.png)
