### ISSUE TITLE
Project user permissions

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2942]
### Description
To have project permissions in v5 we are going to reuse and re-style the component from v4. 

### Goals
- [x]  Reuse the functionality from v4

### Tasks
- [x] add a route 'user permissions' with a mockup component 
- [x] Try to embed the v4 project persmissions component in  the new route
- [x] Add some prop to pass on the selected project from v5 instead of selecting it from the select box
- [x] Remove the select box if the component is in the v5 environment
- [x] Change model to container (support v4 model naming still?)
- [x] Re-style thecomponent to match the changes

### Related Resources
[Ui Design](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3329%3A48228)
