### ISSUE TITLE
Upload containers - Destination input box

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2943]
### Description
The select box for creating a new container/select a container when uploading a new model has lots of states . It should consists of two components. An input  and a  select component linked up with an autocomplete component.

### Goals
- [ ] Provide the option to select an already existing container
- [ ] Provide the option to select a new container 
- [ ] Provide a way to show errors 
- [ ] Autocomplete the option

### Tasks
- [ ] make an unstyled version of the component to test that everything can work as intended using the autocomplet
- [ ] Create an input for an existing container following the styles defined in the mockup 
- [ ] Create ( or reuse, because it seems that it was already defined in the UI kit)  an input for new containers
- [ ] Add a tooltip for errors
- [ ] Create a select item for rendering the existing container that will populate the select box (bear in mind the styling)
- [ ] Update the select item for rendering the existing container that will populate the select box  with a disabled style
- [ ] Create a select item for new containers following the styling 

### Related Resources
[MockUp
](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2874%3A69529)Coda doc: `link to coda`

**Comment by carmenfan** [comment]
Merged into #2698
