### ISSUE TITLE
Move avatar into fileshare

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2944]
### Description
At the moment the avatar is embedded into the user document as a string (base64?), which is clogging up the database unnecessarily.

This should go to file handlers and store it like we store all other data resources.

### Goals
- Avatar functionality should be unaffected
- Avatar to be stored in file handler of choice (fileshare most likely)

### Tasks
- [ ] Alter the code to upload avatar into fileshare instead of the user document, replace avatar with a reference to the avatar.
- [ ] if avatar is updated, we need to make sure we remove the old one.
- [ ] Alter the code to delete the avatar in fileshare if it is being deleted
- [ ] Alter the code to fetch the avatar from fileshare
- [ ] database migration script to move existing avatar into fileshare.
