### ISSUE TITLE
Edit federation - Federation containers list

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2953]
### Description
This is a component to represent a list of available containers. It looks like a simplified list from the containers page. It should render a list of containers and provide a way to remove a particular container.  This will be included in the form described by 

### Goals
- [ ] Have a component with a list of containers 
- [ ] This list can render a plus or minus button for  using it in both 'containers included' and 'available containers' lists

### Tasks
- [ ] Create the columns, using our controls for the dashboard
- [ ] Create the basic `<FederationContainerItem />` with the button to add/remove and a prop to set which of those will be used
- [ ] Make sure that it looks ok at different resolutions

### Related Resources
[UI design](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2608%3A56434)
[UI design with  the minus button](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2608%3A58276)
