### ISSUE TITLE
Simplify the use of dashboard lists / search stuff

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2954]
### Description
Dashboard lists are a bit awkward to use. everytime they are used in a different context you  have to copy and paste the code.

### Goals
- [ ] As a dev I want to use a dashboard list in a simple fashion

### Tasks
- [ ] Try building on top of the existent components without modifying those.
- [ ] Try out changing the already stablished code for dashboard lists
