### ISSUE TITLE
Change topNavigation to projectNavigation

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2957]
### Description
I think the name 'topNavigation' with the links for navigating a project is confusing. projectNavigation is a better suited name

### Goals
- [ ]  To improve readability

### Tasks
- [ ]  rename topNavigation and its components to projectNavigation
- [ ] change it in the dependencies
