### ISSUE TITLE
Review the scrollbars in v5

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2958]
### Description
We are showing the scrollbars all the time in v5. I'm not sure that's a good look and feel.

### Goals
- [ ] Have the scrollbars replaced by the react scrollbards.

### Tasks
- [ ] Get rid of having default scrollbars showing when is not necessary 
- [ ] Use simplebar for the content of the modals (fixed header and footer)
- [ ] Use simple bar for revisions  (take in consideration minimum and maximum height)
- [ ] Use simple bar  in federations and containers
- [ ] In containers the revisions sublist  should have a fix height after 5 items. 
- [ ] In user permissions lets have the react scrollbar in the whole page.

### Related Resources
[Scrollbars in modals](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3160%3A51485)
