### ISSUE TITLE
Research: prevent components from using useParams

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2968]
### Description
Components are using 'useParams' for getting the selected teamspace or the project, etc. This couples routing and components in a way that might not be the best; it makes it hard to find out which component is fetching the data for that particular parameter. Also  it makes it hard to know which component is actually putting that parameter in redux, making it a bit prone to race conditions. 
Having one centralised component that handles the relation between url parameters and redux/requests might be a good way to know what each parameter does and also provide an standard way of dealing with these.

### Goals
- [ ] Make components dealing with routing parameters more readable
- [ ] Have a standard way to deal with routing parameters.
- [ ] Have a more

### Tasks
- [ ] Make a component that uses params;
- [ ] Make this component fetch the necesary data based on the params
- [ ] remove usparamas from the rest of the components: replace them with selectors.
