### ISSUE TITLE
Realtime system

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3003]
### Description
We need a clean system to hook up to chat events in v5. 

### Goals
- [ ] It's easy to setup 
- [ ] It's easy to add new events, shouldn't feel hacky.
- [ ] Should be transparent for sagas or redux

### Tasks
- [ ] Try out several designs
