### ISSUE TITLE
Users permissions navigation

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3007]
### Description
Right now user permissions contains two tabs; "Project permissions" and "Containers  & federations permissions". Instead of having those a subtabs of user permissions we want to have them as par of the project navigation tabs.
In addition to moving the tabs to the project navigation bar we want to be able to pass containers/federations as part of the query string and to be able to navigate from the containers/federations list to the permissions page.
That means put in the link from the ellipsis menu from a particular item (federation of container) in the "edit permissions" item, that will navigate to  "Containers  & federations permissions" tab and select the appropiate container or federation.

### Goals
- [ ] Have the tabs from user permissions in the project navigation bar
- [ ] Have a routing for selected container/federations permissions
- [ ] Being able to navigate from the container/federation to the user permissions of that container/federation

### Tasks
- [ ] Create a new route ':teamspace/:project/t/permissions' for the project permissions.
- [ ] Wire the project permissions component to the new route.
- [ ] Create new route ':teamspace/:project/t/container_federation_permissions' for the containers/federation permissions .
- [ ] Wire the container/federation permissions component to the new route.
- [ ] Modify the container/federation permissions component to receive a selectedContFed query param.
- [ ] Make the container/federation permissions component change the selection in response of the selectedContFed query param.
- [ ] Update the ellipsis menu from containers, edit permissions to link up to the new container/federation permissions passing the selected container as selectedContFed .
- [ ] Update the ellipsis menu from federations, edit permissions to link up to the new container/federation permissions passing the selected federation as selectedContFed .
