### ISSUE TITLE
Profile avatar

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3009]
### Description
On the top right we have an avatar pic that right now is hardcoded. We need to wire this with the proper profile pic and add a collapsible menu when clicking it.

### Goals
- [ ] The top right avatar pic should show the logged in user avatar image
- [ ] When clicking the avatar a menu should show up for logging out and accessing other pages.

### Tasks
- [ ] Make the profile list show the correct image
- [ ] Create the menu following the design
- [ ] Add the links to the menu

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=4163%3A33871)
