### ISSUE TITLE
Update the version of material ui

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3017]
### Description
We are using material ui version 4.11.2 and material ui is already in version 5.4.0 . We are missing out of some features, as for example the expandable color palette in the themes.

### Goals
- [ ]  Have the latest version of material UI

### Tasks
- [ ] Update the version of material UI
- [ ] Make sure it works in v4 dashboard
- [ ] Make sure it works in v4 viewer
- [ ] Make sure it works in v5
- [ ] Update the theme in v5 to use the new version

### Wait For 
Upgrading react to v17 is necessary to fulfill this task, so Issue #3057 shall be completed first.
