### ISSUE TITLE
Redux store refactoring/review

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3018]
### Description
Sometimes is a bit unclear what things should go in the redux store or where. I think reviewing/refactoring it a bit might bring a bit of clarity.

### Goals
- [x] Have a cleaner store

### Tasks
- [x] Define a criteria for which things should be kept in the redux store  and modify any saga function that fails to meet the criteria
- [x] Define a criteria for the saga functions (what type of params) and modify any saga function that fails to meet the criteria
- [x] Modify any selector that fails to meet the criteria of the thing that are being stored in the redux store
