### ISSUE TITLE
Groups of Groups

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3021]
### Description

Groups is currently a useful feature for checking models, but without being able to organise the groups in can limit the capabilities. 

### Goals

- [x] Groups named similarly to Meta Data (Category::GroupName) will be grouped into category
- [x] All uncategorised groups should come top of the list (similar to metadata)
- [x] Users can apply colour overrides to all groups in a category (by hitting the droplet)
- [x] When colour overrides are applied at the category level the icon should become completely filled and all fill icons in the category should go their respective colours.
- [x] Removing an individual fill after a category fill has been applied will remove the filled icon at the category level
- [x] Users can isolate all elements inside groups in a category (by hitting the eye icon)
- [x] Categories can be collapsed
- [x] Import/Export of groups and all API queries behave as usual, but with "::" in the group name

### Tasks 
- [x] Create a Selector that returns the groups tree
- [x] Create a GroupSet component that takes a group tree as prop
- [x] Create a GroupItem that takes a group as prop
- [x] Create the group list
- [x] Make sure that this plays nice both in v4 and v5.
- [x] Apply design to group items
- [x] Apply design to catagories

### Notes
We'll tackle the groups list as v5 component as a starting point for building the viewer in v5.
When going to the details then thats the v4 component.

### Related Resources
[Mockup](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=137716%3A180903) 

<img src="https://user-images.githubusercontent.com/62879582/174329870-4bd8960b-1ad8-421e-aed3-0c2161d14228.png" width="400" />

**Comment by sanmont3drepo** [comment]
@george-hadfield  I need the figma link for this issue
