### ISSUE TITLE
Custom Meta Data

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3022]
### Description

More customers are asking for ways to add data to elements inside 3D Repo. This can be for a multitude of reasons, including:
- Updating the status of offsite manufacture elements
- Identifying Installation or QA Dates
- Facilities Management information such as serial numbers or links to manuals

We should allow user to attach additional data to a metadata object via the API so that this data can be access inside 3D Repo's UI

### User Stories

- As an Integrator I want to add metadata so that it is visible in the BIM Card when I select an object
- As an integrator I would like to see what data has been added to an object when I query Get Metadata or Get All Metadata
- As an integrator I would like to batch upload metadata to multiple objects at a time
- As an integrator I would like to upload multiple metadata fields to objects at the same time
- As an integrator I would like to see all of the metadata associated with an element in the API response when I add custom metadata
- As a viewer I would like to see custom data n the BIM Card
- As a viewer I would like to use custom data in Smart Groups
- As a viewer I would like to favourite custom metadata fields

#### New endpoint
PATCH
route: `/teamspaces/{teamspace}/projects/{project}/containers/{container}/metadata/{metadata}`
payload: 
````js
{
 metadata: [
  { key: "abc", value: "xyz" },
  { key: "abcd", value: 12 },
  { key: "abcde", value: false },
  { key: "abcdef", value: null },
]
}
````
response: just return `200` on success

NOTES:
- metadata variable on the endpoint being metadata unique id (i.e. `_id` in the database )
- key provided must be new to the document, or an existing custom metadata (see below on how to check this)
- entries with `value: null` should be removed from the array in the database.

#### Metadata Schema update
for custom metadata, add an extra field on the the metadata entry to denote it is customised after processing, for e.g. : 
````js
{
    "_id" : LUUID("d2e93b3e-3b41-42bc-b93b-dfcc5ff94893"),
    "parents" : [ 
        LUUID("fe113f6d-d49f-4136-9ae7-9bded19406fc")
    ],
    "shared_id" : LUUID("5e6b18d1-bfd0-48f9-b6f7-aa60fb0d720b"),
    "type" : "meta",
    "name" : "ComponentName:409",
    "metadata" : [ 
        // This is a metadata from import and thus is read only
        { "key" : "IFC Type", "value" : "IfcBuildingElementProxy" }, 
        // This is a custom metadata that can be updated/removed
        { "key" : "Diameter (m)", "value" : 20, custom: true },        
    ]
}
````

### Goals

- [ ] Add custom data to to a metadata object via the API (PATCH)
- [ ] Upload multiple custom data values to a single metadata object in a single API request
- [ ] Upload to multiple metadata objects in a single API request
- [ ] Edit existing custom metadata with an overwriting PATCH request
- [ ] Remove metadata if a PATCH request has assigned a null value to a key
- [ ] Allow new metadata to be used in Smart Group requests (This should work naturally by the way it's stored)
- [ ] See custom metadata clearly defined when I use the [Get Meta by ID](https://3drepo.github.io/3drepo.io/#api-Meta-getMetadataById) request

**Comment by carmenfan** [comment]
@mosment3DRepo A few questions:

Since you're not after a UI, are we happy with only implementing this on v5 backend? (the data will be retrievable from v4 endpoints, just the edit endpoint will be a v5 one)

> As an integrator I would like to batch upload metadata to multiple objects at a time
> As an integrator I would like to upload multiple metadata fields to objects at the same time

To confirm on the definition of object here. Are we ok with the endpoint taking a metadata ID? From the discussions we had in the past, the plan is to append it to a metadata object, which is associated to one or more mesh/transformations)

> As an integrator I would like to batch upload metadata to multiple objects at a time

Do we have to support this on the backend? or can we expect one PATCH request per metadata ID? reason I ask this is, doing a batch edit complicates error handling, the user can send us a bunch of metadata ids where some doesn't exists, or give us a field to edit that is a custom field in one but not on another. Keeping this relationship 1 to 1 makes it a lot more manageable in terms of error handling + we avoid the situation of a partial error and ambiguous data states

> As an integrator I would like to see all of the metadata associated with an element in the API response when I add custom metadata

element being metadata ID? From what I remember we don't have a "give me all metadata associated with this mesh/transformation ID" endpoint, so I'm not sure if you're implying you want a new endpoint here or not.

**Comment by carmenfan** [comment]
@mosment3DRepo  another one:

Who has permissions to edit metadata? commenter+ ? collaborators+ ? admin only?

**Comment by mosment3DRepo** [comment]
> Since you're not after a UI, are we happy with only implementing this on v5 backend? (the data will be retrievable from v4 endpoints, just the edit endpoint will be a v5 one)

**Yes V5 only is fine**
> 
> > As an integrator I would like to batch upload metadata to multiple objects at a time
> > As an integrator I would like to upload multiple metadata fields to objects at the same time
> 
> To confirm on the definition of object here. Are we ok with the endpoint taking a metadata ID? From the discussions we had in the past, the plan is to append it to a metadata object, which is associated to one or more mesh/transformations

**Yes, in this instance we can read "object" as "metadata object", although it will require an extra API request from customers to get the metadata ids hopefully it should make any requests less ambiguous**
> > As an integrator I would like to batch upload metadata to multiple objects at a time
> 
> Do we have to support this on the backend? or can we expect one PATCH request per metadata ID? reason I ask this is that doing a batch edit complicates error handling. The user can send us a bunch of metadata ids where some doesn't exists, or give us a field to edit that is a custom field in one but not on another. Keeping this relationship 1 to 1 makes it a lot more manageable in terms of error handling + we avoid the situation of a partial error and ambiguous data states


**As discussed, for user simplicity I would prefer a batch upload, but for MVP since 3D Repo will be the ones delivering the integration we can operate on a 1 request per metadata object basis**
> > As an integrator I would like to see all of the metadata associated with an element in the API response when I add custom metadata
> 
> element being metadata ID? From what I remember we don't have a "give me all metadata associated with this mesh/transformation ID" endpoint, so I'm not sure if you're implying you want a new endpoint here or not.

**I think we can ignore this one**

> 
> 1. Who has permissions to edit metadata? commenter+ ? collaborators+ ? admin only?

**Admin + collaborators (I know I said admin on the phone but I think collaborators is needed too)**

> > See custom metadata clearly defined when I use the [Get Meta by ID](https://3drepo.github.io/3drepo.io/#api-Meta-getMetadataById) request
> 
> This could be difficult for v4 format as the format is `{ key: value }` , it doesn't give us any extra wiggle room to give any details per line.
>
> 2. Does it have to be that endpoint? or can we create a v5 version of the endpoint that will return the data in the new schema (thus we can just return whatever is in the database)

**Not necessary for v4 calls, but should be visible on v5 calls**
