### ISSUE TITLE
Endpoints to fetch views from containers

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3027]
### Description
endpoint to fetch view list from federations was adding in #2789

We need to do the same for containers.

NOTE: this issue will branch from #2789 for simplicity and to avoid conflicts

### Goals
- [ ] Fetching view list from containers should succeed

### Tasks
- [ ] Create endpoint to fetch views list
- [ ] refactor file-type to utils
