### ISSUE TITLE
Federation settings UI fixes

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3028]
## Description
There are some problems pointed out by George with the federation settings form

### Tasks
- [x] Remove arrows from Lat and Long inputs
![image](https://user-images.githubusercontent.com/78047794/154035434-d195a1cb-81ce-4402-a87e-a6f877963edc.png)

- [x] Incorrect font being used for input labels . Letter spacing and font weight seems incorrect.
![image](https://user-images.githubusercontent.com/78047794/154035610-7b297e9b-c755-49e2-be79-1979fd074de4.png)

- [x] Arrows for select inputs are incorrect.
![image](https://user-images.githubusercontent.com/78047794/154035862-570df663-ad53-45f6-b3de-1132204105b3.png)

- [ ] Border radius is incorrect for image on default view. Top right and bottom right border radius should be 0 once selected.
![image](https://user-images.githubusercontent.com/78047794/154036064-67568576-fdcd-4712-90a4-f8b3d3eb6a05.png)

**Comment by Amantini1997** [comment]
The mockup is not very clear, but the border has the same radius even after being selected. In the mockup, however, the thumbnail is overlapping the border itself and it seems the border-radius is set to 0, but a close up view shows it is in fact rounded <img width="491" alt="image" src="https://user-images.githubusercontent.com/43547703/154057199-dc75ef9f-faa6-442e-baad-76b252910f30.png">

**Comment by george-hadfield** [comment]
Yes please. Can you also love the image over 1px so you don't see the
border on the left?

**Comment by carmenfan** [comment]
![image](https://user-images.githubusercontent.com/11945337/154080657-370cb5de-d6e4-48db-9ba3-1c896f71c323.png)


@Amantini1997 `survey` is spelt wrong here

**Comment by Amantini1997** [comment]
> Yes please. Can you also love the image over 1px so you don't see the border on the left?

Should the thumbnail cover the actual border? @george-hadfield

**Comment by george-hadfield** [comment]
Yeah it should :)
