### ISSUE TITLE
Test redux-toolkit.js to improve code cleanliness

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3030]
Redux-toolkit (RTK) can be used to reduce the boilerplate inside redux *success methods

### Description
Try to introduce RTK to reduce the boilerplate for the redux *success methods and make it easier to read and maintain.

### Goals
Integrating RTK should:
- [ ] make the code easier to read and to maintain;
- [ ] make the code lighter;
- [ ] not break existing code;
- [ ] be easily extensible;

### Tasks
- [ ] Update the code to include RTK;
- [ ] Check goals are all met;
- [ ] Check the code does not break;
- [ ] Compare it to the integration of Immer.js ISSUE #3031 

### Related Resources
[Redux-toolkit migration guide](https://redux-toolkit.js.org/usage/immer-reducers)

**Comment by Amantini1997** [comment]
After researching and testing, RTK does not seem to bring significant benefits:
- Redux-sauce is accomplishing pretty similar results. Re-writing everything to move from redux-sauce to RTK is not worth it;
- A problem related to using RTK is the parameters passed to the single reducers 
  > e.g. `const fetchFederationsSuccess = (state, action: { payload: { <actual args> } }) => { ... }`. 
  
  Unwrapping the `action` object is an extra effort not needed. An helper function can be created to simplify that, but it had to be applied individually to each reducer (applying it in batch prevents intellisense from correcting the parameters passed to the reducers when the latter are called from the ActionDispatcher).

The main benefit that comes from RTK is how reducers can be re-written to use Immer.js syntax. As a result, RTK will be discarded, but Immer.js may be included. Refer to issue #3031
