### ISSUE TITLE
Test Immer.js to improve code cleanliness

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3031]
Immer.js can be used to reduce the boilerplate inside redux *success methods

### Description
Try to introduce Immer.js to reduce the boilerplate for the redux *success methods and make it easier to read and maintain.

### Goals
Integrating Immer.js should:
- [ ] make the code easier to read and to maintain;
- [ ] make the code lighter;
- [ ] not break existing code;
- [ ] be easily extensible;

### Tasks
- [ ] Update the code to include Immer.js;
- [ ] Check goals are all met;
- [ ] Check the code does not break;
- [ ] Compare it to the integration of RTK ISSUE #3030 

### Related Resources
[Redux + Immer](https://immerjs.github.io/immer/example-setstate#redux--immer)

**Comment by Amantini1997** [comment]
Using Immer.js seems to make the code more readable and easier to write/maintain. We will then proceed to include the library in our source code (https://github.com/3drepo/3drepo.io/issues/3524)
