### ISSUE TITLE
Add license key field to elastic records

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3041]
### Description

We'd like to add the field for the license key associated with the installation to all records submitted to elastic.

### Goals
- [x] New mapping
- [x] Roll over aliases
- [x] collect license key information

### Tasks
- [x] add field to mapping
- [x] add field to data collected
