### ISSUE TITLE
Rethink the button system

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3043]
### Description
There are several types of buttons (lets take out the `<CircleButton />` for now) with their different variants. We need to think a bit , taking in consideration the palettes and colourr (in particular the errorbutton variant) if it should be a variant or just the same variant with a different colour and the categories of buttons 

### Goals
- [ ] Have a more clear reusable button system

### Tasks
- [ ] Think about the best way to go
- [ ] Apply the changes
