### ISSUE TITLE
Use v5 endpoint for getting the profile

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3049]
### Description
We are using v4 endpoints for getting the profile. We need to change it to use the new endpoints.

### Goals
- [ ] There shouldnt be a difference regarding the user journey and the profile data should be accessible

### Tasks
- [ ] Get rid of the auth mockup saga.
- [ ] Implement a auth redux state for getting the profile
- [ ] Add API endpoints to the client for getting the profile from v5
- [ ] Add saga for getting the profile using the new endpoint

**Comment by The-Daniel** [comment]
@sanmont3drepo So is the the profile data to be stored in the auth2 redux state? In v4 it is stored in currentUser
