### ISSUE TITLE
Revisit textfields theming/colours

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3053]
### Description
Right now Textfields supports just one colour (it doesnt matter if it the prop color is 'primary' or 'secondary', it looks the same) . We need to do one of two things
1 - Fix it in the theme so we can have different colour schemas
2 - Create our own version of the textfield with differnt variants.

This might require @george-hadfield 's  input (which different kinds of textfields do we have?)

### Goals
- [ ] Stop having customised textfields around and have our uikits ones

### Tasks
- [ ] Research if it is possible to change the theme for support different ones
- [ ] If the first one fails extend material uis textfields to support our variants
