### ISSUE TITLE
Reestructure folders

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3054]
### Description
Since we added routing the structure of the folders in v5 have become a little muddled. We need to find a new cleaner structure that makes sense to the current code.

### Goals
- [ ] Make very clear where each file should go.

### Tasks
- [ ] Rethink the categories of files and derive a new folder structure that matches
- [ ] Create the folder structure.
- [ ] Move around files.
- [ ] Profit.
