### ISSUE TITLE
Try out storybook

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3055]
### Description
It seems that we need to showcase the components to be more aware of which components are already there and which new ones are needed. It would also makes things easier to see and approve for @george-hadfield .

### Goals
- [ ] Try storybook in a separate folder 

### Tasks
- [ ] Try to install and configure storybook in a separate folder
- [ ] Showcase the uikit
