### ISSUE TITLE
Split out types files

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3056]
### Description
Right now the types files (for example containers or federations) have all the types in the same file regarding that objects domain. I think splitting them out and moving the types to files which those types have more context (like the IProps in the components) can make the types files more managable and improve readbility.

### Goals
- [ ] Everything should work as before
- [ ] Types should be in the proper context

### Tasks
- [ ] move the payload types to the api files
- [ ] move the action types to the redux files
- [ ] leave the shared types in the same file
