### ISSUE TITLE
Update React version

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3057]
### Description
We are using react version 16.8.6 and we want to upgrade to MUI version 5.4.0, which needs react version 17^. 

### Goals
- [ ]  Upgrade to React v17;
- [ ]  Upgrade  to webpack v5

### Tasks
- [ ] Update the version of React
- [ ] Update the version of Webpack
- [ ] Update Webpack plugins
- [ ] Update Webpack loaders
- [ ] Make sure it works in v4
- [ ] Make sure it works in v5
