### ISSUE TITLE
Geometry Streaming Prototype

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#3065]
### Description
Create a version of the viewer running in the browser showing streaming working at the prototype stage

### Goals

- [ ] Web viewer streams geometry in and out on demand using the database/bouncer for model delivery

### Tasks

- [ ] Create a build of the streaming viewer with the lego house
- [ ] Check it has no memory leaks

**Comment by carmenfan** [comment]
Batch download JSON MPC endpoint:

route: `{teamspace}/{modelid}/{revision}/{revisionId (or master/head}/unity.json.mpc`

Returns:
````js
{
  supermeshes: [
      {
         id: "<super mesh id>",
         data: {
              //data in the file
          }
      }
 ]
}
````

**Comment by sebjf** [comment]
Hi @carmenfan, yes that should work!

**Comment by carmenfan** [comment]
@sebjf endpoint working, as usual if it's called from a federation it gets a bit complicated and everything hides inside a submodel array:

![image](https://user-images.githubusercontent.com/11945337/170479868-5c657efe-68f2-40ea-bdc8-009d941c3a93.png)


Only tested it very briefly, let me know if you run into problems.

Will also be making another commit for clean up after lunch (api docs, caching etc)

**Comment by sebjf** [comment]
@mosment3DRepo @carmenfan Thank you Carmen! The new API works. I updated the viewer to use it. 

On the LOR federation the viewer kept crashing in the however. I think this is because the response is too large for Unity's JSON parser. As a workaround I have used the API to load on a per-model basis (once ModelController has requested all the assets, and so has a list of models), rather than a per-container/federation basis, and that allows it to load.

I am not sure what the final fix should be. One option is to use a 3rd party JSON parser. Loading per-model seems like kicking the can down the road since if theres a limit, it isn't going away. On the other hand the likelihood of having such a large response (133 Mb) per model seems unlikely, and there are other responses as well that we'd have to consider if such a large model were to be created. The workaround now is not complete because it doesn't take into account the revision (unless the uid in the namespace loaded via a federation is implicitly a specific revision? Otherwise we may need a new API or some other way to get this in the right place).
