### ISSUE TITLE
Missing users redux tests

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3073]
### Description
We are missing test for users sagas and selectors

### Tasks
- [ ] Add tests for users sagas.
- [ ] Add tests for users redux.
- [ ] Add tests for users selectors.

**Comment by carmenfan** [comment]
@sanmont3drepo  might be good to think about setting some coverage restrictions on specific files so it auto files travis if someone didn't write tests
