### ISSUE TITLE
Write some tests for login/logout logic

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3086]
### Description
We had a bug during 4.22.0 RC testing where logging in [on the plugin is kicking a user out of a websession](https://github.com/3drepo/3drepo.io/pull/3074#issuecomment-1051082426)

We should ensure we have written adequate tests to prevent regression bugs.

The logic around this is:

- When a user login from a web session, we should be logging them out of any sessions that are established from the same referrer
- When a user log in from a non web session, no other sessions should be removed.

### Goals
Write tests to capture the force log out logic

### Tasks
Write a test for:
- [ ] When a user login from a web session
   - [ ] A event with session Ids with matching referrer should be triggered
   - [ ] This event should not include any sessions Ids that does not have the same referrer
   - [ ] No current session should also not trigger an event.
- [ ] When a user login from a non web session
  - [ ] No log out event should trigger.

**Comment by carmenfan** [comment]
Should be looked at after #3045  as there is a change in session handling there

**Comment by carmenfan** [comment]
addressed in https://github.com/3drepo/3drepo.io/pull/3116/files#diff-1eda2f30f13198567808b416261655ee76bcd0ac9c8841169ee2b7fad5abe1a6
