### ISSUE TITLE
Mailer V5

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3118]
### Description
At the moment, we're just bringing in the v4 mailer into v5. 

We want to rewrite it and only support functions that are currently needed.

#### Make a reusable template
In v4, we have full templates of every single email we send out as a [separate template](https://github.com/3drepo/3drepo.io/tree/master/backend/src/v4/mailer/templates). In reality, they share a lot of common components. Going forward, we want to ensure that we standardise the look and feel, and each context specific template should only contain the context specific components.

For e.g. we should have a general 3D Repo Email template:
![image](https://user-images.githubusercontent.com/11945337/159956113-b60d08f7-a642-4a7f-906b-ebfc828fc6c7.png)

and a Reset password email template:
![image](https://user-images.githubusercontent.com/11945337/159956179-534f87fb-f97f-4232-9c55-d5ce5c74c187.png)

The general template should be a full html, containing an area to insert the core email component, and the reset password email should only contain the text and reset password specific components.

#### Generalise function calls
In v4, we have [specific function calls](https://github.com/3drepo/3drepo.io/blob/master/backend/src/v4/mailer/mailer.js#L98) for each email to send 

In v5, we should generalise this so there is one function call to send email, and it takes in a constant to denote which email template to use. for e.g. to send an reset password email,  the caller should do something like this:

````js
mailer.send("recipient@mail.com", templates.RESET_PASSWORD, { username, token });
`````

In the mailer, we should only have a `send` function, and there should be a constants file that declare the list of templates available. So subsequent emails we create we just have to create new templates and utilise the same `send` function.

### Goals
- [ ] Create a v5 mailer service
- [ ] Support the following emails:
  - [ ] Email verification for sign up (for #3106) (mockup [here](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=5990%3A42695))
  - [ ] Forgot password email (for #3085) (mockup [here](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=6304%3A42192))

### Tasks
_to be filled in by the developer_
