### ISSUE TITLE
Embed a functional viewer in v5

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3125]
### Description
We are facelifting v4 viewer to match the style of v5, as a first step is necessary to have a viewer actually working in v5.

### Goals
- [x] As a user I want to navigate to the viewer in v5
- [ ] As a user I want to be able to do everything that is already working in v4

### Tasks
- [ ] Add basic route for v5 embeded-viewer 
- [ ] Add issue routtes for v5 embeded-viewer 
- [ ] Make sure every functionality work
- [ ] Provide a way to customise the components
- [ ] Make revisions switching work
