### ISSUE TITLE
Clean up customData in users

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3144]
# Teamspace Admin
### Description
who is a teamspace admin is currently stored inside the user bson of the teamspace

it should be instead stored in teamspace settings, inline with every other permissions settings.

We will also need to create a migration script to move existing admins to this format

### Tasks
- [x] Store in teamspace settings
- [x] Read teamspace settings
- [x] Migration script

# AddOns
### Description
The existing flags (`vrEnabled`, `hereEnabled` etc) are at the root level of `customData`. As we are introducing more and more flags this is getting a bit unmanagable. 

As of f9bd94c296de4befe392a821e6903d95a2b4a7cc in #2474 , we're also introducing an endpoint for users to probe what plugins are enabled for the teamspace. If we stick with the current approach, everytime we add a flag, we'd have to update this code so it fetches the flag in the query.

~~This is not really desirable and if we instead put them all into an embedded bson within `customData`, they will no longer clog up the root space level of `customData` and we won't need to explicity specify the flag on the projection.~~ Put in TS settings.

### Goals
- have all add on flags to be stored in inside an embedded object, `addOn: {}`
- store in TS settings
- ensure the system is probing the flag in the updated space

### Tasks
- [x] Read addOns settings
- [x] Migration script
- [x] addOns utility script

# Subscriptions
### Description
Move subscriptions from `customData` to TS settings.

### Tasks
- [x] Migration script
- [x] Update backend
- [ ] Licences utility script

**Comment by Charence** [comment]
Also address: #2481

**Comment by Charence** [comment]
- [ ] remove hack for broken TS
