### ISSUE TITLE
Teamspace selection

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3146]
### Description
As the user I want to have a place where I can see my teamspaces and navigate to the one I have selected.

### Goals
- [ ] As a user I want to see the teamspaces I'm member of.
- [ ] As a user I want to navigate to the content of the teamspace I want
- [ ] As a user I want to be able to create a new teamspace

### Tasks
- [ ] Create the teamspace card component 
- [ ] Make the teamspace card component a link to the teamspace (the projects list for that teamspace)
- [ ] List  your teamsapces
- [ ] New teamspace is a link for creating a mail ([mailto](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto)) . Check with @mosment3DRepo  for the content/subject of the email.

**Mailto for new Teamspace**
```
To: "support@3drepo.org"
Subject: "New 3D Repo Teamspace"
Body: "3D Repo Team, I would like to set up a new Teamspace"
```

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=6015%3A42627)

**Comment by carmenfan** [comment]
Note we currently do not have an endpoint for getting teamspace image.

Will probably add it in this issue for simplicity

**Comment by carmenfan** [comment]
@The-Daniel Endpoint for teamspace avatar up and working:
![image](https://user-images.githubusercontent.com/11945337/162729891-ebc255b2-ceeb-4208-9451-3a5f276b2dd1.png)


Will add tests for it later
