### ISSUE TITLE
Viewer facelift - Breadcrumbs in viewer

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3159]
### Description
The topbar is showing right now the dashboard breadcrumb. I should show an updated version.

### Goals
- [ ] Be able to navigate from within the viewer in v5

### Tasks
- [ ] Topbar  breadcrumb shoudl have the format `<teamspace>/<project>/<containerOrFederation>/<revision>`

**Revision select field**

Changes
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/78047794/163212295-2e4281a0-38f8-4eed-9673-539963c95cc3.png">

- [ ] Move the revision select field to the main breadcrumb 
- [ ] Should follow the new style breadcrumb
MockUp
