### ISSUE TITLE
Viewer facelift - Issues list (items and general ui)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3168]
### Description
We need to revamp issues, lets start by the list

### Goals
- [ ] As a user when opening the issues card I want to see a consistent v5 style

### Tasks
- [ ] Restyle the topbar menu in the issue list 
- [ ] Restyle the items  (take in consideration the different states, hover and styles the items can be in)
- [ ] Style the blank state

### Notes
For now we are not changing the button icons.

### Related Resources
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136544%3A176576)
