### ISSUE TITLE
Viewer facelift - Issues list (dropdown menu , filter and search)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3170]
### Description
In the issue list, there's the feature for filtering the issues , we need to style it in the v5 way. 

### Goals
- [ ] As a user I want to filter the issues and have a nice v5 style.

### Tasks
- [ ] Style the the dropdown menu
- [ ] Style the chips 

### Related Resources
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136544%3A176791)

**Comment by Amantini1997** [comment]
This was addressed as part of #3168
