### ISSUE TITLE
Viewer facelift - Issue details tab (properties)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3171]
### Description
For the issues we need to style every tab. This one is for properties 

### Goals
- [ ] As a user I want to edit the issues properties and have it styled in the v5 style

### Tasks
- [ ] Restyle in the theme the select box to match the style
- [ ] Restyle the 'edit pin', 'edit image' and 'update viewpoint' buttons
- [ ] Restyle the description   texbox

### Notes:
We are not changing the button icons for now

### Related Resources
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136526%3A174012)
