### ISSUE TITLE
Viewer facelift - Issue details (header and comments) 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3172]
### Description
For the issues we need to style every tab. This one is for the header and contents shared between every tab

### Goals
- [ ] As a user I want to edit the issues and have it styled in the v5 style

### Tasks
- [ ] Style the header 
- [ ] Style the comments
- [ ] Style the send comment section

### Notes:
We are not changing the button icons for now. If alignment is not easy to manage we wont change that.

### Related Resources
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136544%3A178700)

**Comment by Amantini1997** [comment]
This was addressed as part of #3168
