### ISSUE TITLE
Viewer facelift - Issue details tab (shapes)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3174]
### Description
For the issues we need to style every tab. This one is for shapes

### Goals
- [ ] As a user I want to add and remove shapes and have it styled in the v5 style

### Tasks
- [ ] Restyle the panel (font, background color)
- [ ] Restyle blank state
- [ ] Restyle the color picker (ask George before tackling this)
- [ ] Restyle the items 

### Notes:
We are not changing the button icons for now.

### Related Resources
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136544%3A177904)

**Comment by carmenfan** [comment]
Merged into #3168
