### ISSUE TITLE
Viewer facelift - Issue details tab (attachments) 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3175]
### Description
For the issues we need to style every tab. This one is for attachments.

### Goals
- [ ] As a user I want to add and remove attachments and have it styled in the v5 style

### Tasks
- [ ] Restyle blank state
- [ ] Restyle the attachment list
- [ ] Restyle the attachment popup dialog

### Notes:
We are not changing the button icons for now. If changing alignment is easy then we'll do it , otherwise we wont.

### Related Resources
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136544%3A178294)

**Comment by carmenfan** [comment]
Merged into #3168
