### ISSUE TITLE
Upload containers modal - cancel upload

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3179]
### Description

Clicking the cancel button in upload containers modal cancels any uploads

### Goals
- Can cancel uploads by clicking the cancel button
- This removes the upload from the list and closes the modal
- The user can still click the top right 'X' button to close the modal without cancelling/removing uploads

### Tasks
- [ ] add ability to cancel an API request
- [ ] change cancel button to use this new ability

### Related Resources
[Axios docs](https://axios-http.com/docs/cancellation)

**Comment by carmenfan** [comment]
> The user can still click the top right 'X' button to close the modal without cancelling/removing uploads

@mosment3DRepo @george-hadfield  do we want this? I thought we want to stick to the journey where the user have to sit on the pop up until the transfer has completed so they don't' accidentally close the window

**Comment by george-hadfield** [comment]
I agree @carmenfan. Remove the 'X' once the files are uploading.

**Comment by AsiteZane** [comment]
This is a good observation, thank you. Will need a new UI/UX to achieve the following:

- [ ] Ability to upload in the background
- [ ] Ability to know what is being uploaded when clicking Upload files (if one or more is happening in the background)
- [ ] Ability stop an upload of each individual file when on the upload modal
- [ ] Ability to stop all uploads on the upload modal with one button/action
- [ ] Stopping processing would be too difficult, can only stop the upload.

I will add a note in a new product ticket. @AsiteZane - get to it.
