### ISSUE TITLE
Viewer facelift - Fix left panel

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3196]
### Description
The top of the left panel should be aligned with the top first button at the top, and with the bottom of the bottom toolbar at the bottom

The height, however, should be responsive. When the viewport is squeezed and the panel approaches the bottom toolbar, the height of the former should reduce not to overlay the bottom toolbar.

### Goals
- [ ] As a user, I want to use the most of the spacing when playing around with the left panel;

### Tasks
- [ ] Fix the left panel position;
- [ ] Fix the left panel height;
- [ ] Make the left panel height responsive;

### Related Resources
Distance from the navigation bar
![image](https://user-images.githubusercontent.com/43547703/166692326-3229caa0-acd1-42eb-ab36-79211a358e7b.png)

Distance from the bottom of the screen when the viewport is large enough
![image](https://user-images.githubusercontent.com/43547703/166696143-b3dfad4c-c13e-484c-8fcb-e1ddcaadfd33.png)

Distance from the bottom toolbar when the viewport shrinks
![image](https://user-images.githubusercontent.com/43547703/166692985-dbf27a1f-b30d-4697-91e7-a796a6366682.png)
