### ISSUE TITLE
Viewer Facelift - UI fixes

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3206]
### Description
There is a few UI fixes to be done in v5 viewer.

### Goals
Fix the design to match the changes hereby mentioned.

### Tasks
- [x] Change arrow background colour for overdue issues
Instead of the teal background, can we change to below. Colour values can be found in figma here https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136292%3A177725
Updated design
<img width="449" alt="166712435-cd62d133-445a-4bb4-a210-385801ed7f84" src="https://user-images.githubusercontent.com/43547703/167377500-03c295ad-b27b-4d55-937e-36e1a0504400.png">

Current build
<img width="423" alt="166712021-7bcd6198-b4b7-49b7-8da7-3caacc761819" src="https://user-images.githubusercontent.com/43547703/167377543-1dbd2f2a-e461-47f7-b044-effcc9b0b06c.png">

- [x] Change dark border colour
Below the 'Issues' title and also above the create new issue button, the border colour looks too dark. Please change border colour to #E0E5F0
<img width="430" alt="166712875-635532ee-3aa3-4a98-aa09-f2c21ab09cc2" src="https://user-images.githubusercontent.com/43547703/167377605-99656a03-0db9-4251-ac66-00649ba60a24.png">

- [x] Change card title font size to 17px (currently 15px)
<img width="462" alt="166714082-23d96d6c-1408-4404-80dd-defb8edd52c9" src="https://user-images.githubusercontent.com/43547703/167377657-9edbbe8a-e223-4e82-9305-d3500ffb91cf.png">

- [x] Reduce the spacing between the icon and the text to match closer to the design

- [x] Change size of icons at the top of cards
The icons inside circles should be reduced to 1.2 rem as shown in screenshot.
<img width="168" alt="166714958-9e20e4f5-27b9-4bd1-9da3-1791ad79fc39" src="https://user-images.githubusercontent.com/43547703/167378202-203de915-746c-4deb-8bc4-7a66bf6eb60e.png">

- [ ] Change main icon to 1.4rem next to title
<img width="154" alt="166715152-2c18c502-c2e9-4111-84de-56e8ccd4a472" src="https://user-images.githubusercontent.com/43547703/167377897-b2f5b793-d417-4ce9-a92d-36ef97631a42.png">

<img width="470" alt="166715942-de388dc1-0c9a-4661-adaf-e47fd1c5afdb" src="https://user-images.githubusercontent.com/43547703/167377939-ab3b4ad5-431b-46e1-a725-e6f15d91504c.png">

- [ ] Change hover colour of issue items to #F7F8FA

**Comment by carmenfan** [comment]
Merged in #3168
