### ISSUE TITLE
Split the router files  into authenticated routes and unauth routes

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3220]
### Description
In v5 we have routes that are authenticated (needs the user to be logged in) and routes that aren't. In the case of the Unauth routes we need to redirect them to the login page, while the other ones needs to be accessible all the time.

### Goals
- [ ] As a dev I want to have a clear separation between auth and aunauth routes.

### Tasks
- [ ] Split `src\v5\ui\routes\dashboard\index.tsx` into auth and unauth routers files
- [ ] Manage login, forgot password, etc in auth router file  (maybe we can call these public?)
- [ ] Manage the rest of the routes in the private router.
