### ISSUE TITLE
Limit metadata fields in Meta requests

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3223]
### Description

There are 2 API requests which return long metadata lists: https://3drepo.github.io/3drepo.io/#api-Meta-queryMetadataByRules and https://3drepo.github.io/3drepo.io/#api-Meta-getAllMetadata

With some varied models & federations the number of Keys included across all elements can go into the thousands. This can make the request response take a long time and be very large (70MB seen on some models). Since a majority of the time the integrations are looking at specific Keys, we should give the users the option to add a filter to specify which keys should be returned.

### Goals

- [ ] As a user I want to query the latest model by default
- [ ] As a user I want to specify a revision of the model to query
- [ ] As a user I want to query Containers or Federations with the same endpoint
- [ ] As a user I want to include an array of Keys to filter by
- [ ] As a user I want to include hundreds of Keys in the filter array
- [ ] As a user some of my keys are long text fields
- [ ] As a user I still want to see the metadata _id and parents even if none of the keys matched so that I have a complete dataset
- 

### Related Resources

**Example**

Standard metadata response:
```
{
    "data": [
        {
            "_id": "005d7470-a66a-47a3-8c5a-cac53ac1b771",
            "parents": [
                "239cc6fb-4b07-4c22-90f5-d29b783ecb72"
            ],
            "metadata": {
                "IFC Type": "IfcBuildingElementProxy",
                "IFC GUID": "2wn9igZkDoJe6K_MZ5bAXW",
                "LayerName": "A-0233-M_Step33"
            }
        },
        {
            "_id": "0321aad0-1ca0-4ab2-88fb-be49b3400ce6",
            "parents": [
                "4817c549-c889-4929-8c08-eb748cc67e8d"
            ],
            "metadata": {
                "LayerName": "A-0120-M_Step20",
                "Floor": "Datum / Site Model",
                "RequiredForCOBieComponent": "True"
            }
        },
        {
            "_id": "0265184d-de0e-4405-8c19-c72fcbbc118b",
            "parents": [
                "8f20a60e-8f67-4421-93d9-b01a0accc36c"
            ],
            "metadata": {
                "Pen 1": "(do not use)",
                "Pen 2": "Black | 0.13",
                "Pen 3": "White Pen"
            }
        }
    ]
}
```

Query array:
`["IFC Type","LayerName"]`

Response:
```
{
    "data": [
        {
            "_id": "005d7470-a66a-47a3-8c5a-cac53ac1b771",
            "parents": [
                "239cc6fb-4b07-4c22-90f5-d29b783ecb72"
            ],
            "metadata": {
                "IFC Type": "IfcBuildingElementProxy",
                "LayerName": "A-0233-M_Step33"
            }
        },
        {
            "_id": "0321aad0-1ca0-4ab2-88fb-be49b3400ce6",
            "parents": [
                "4817c549-c889-4929-8c08-eb748cc67e8d"
            ],
            "metadata": {
                "LayerName": "A-0120-M_Step20"
            }
        },
        {
            "_id": "0265184d-de0e-4405-8c19-c72fcbbc118b",
            "parents": [
                "8f20a60e-8f67-4421-93d9-b01a0accc36c"
            ],
            "metadata": {
            }
        }
    ]
}
```
