### ISSUE TITLE
Issue 3206 - Viewer Facelift - small tweaks

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3236]
### Description
Just a bunch of small tweaks to enhance the look and feel of the viewer.

### Tasks

- [x] Issue images in list view have incorrect margin/padding
There seems to be a significant gap to the left of the images. The space be around 16px I believe
<img width="480" alt="image" src="https://user-images.githubusercontent.com/78047794/167901629-870cdbc0-65ad-448b-8a23-ee04a73db871.png">

- [x] Increase X in comments to 1rem

<img width="182" alt="image" src="https://user-images.githubusercontent.com/78047794/167902436-406b626f-2ca2-46a8-8f62-cfa1ecb06443.png">

- [x] Reduce icon size in issue title field
This should be for both the pencil and the icons shown in screenshot below. Also please change the colour to navy

Build
<img width="95" alt="image" src="https://user-images.githubusercontent.com/78047794/167902521-ecad847b-3ef5-4200-a698-a57d4a6586fa.png">

It should match the size of the icons when you edit the description box

<img width="131" alt="image" src="https://user-images.githubusercontent.com/78047794/167903008-545423a7-9dd4-4919-9783-0431df273eed.png">

Also, please align the pencil in the description box more towards the top of the field.

- [x] Change grey text in tabs to navy

<img width="354" alt="image" src="https://user-images.githubusercontent.com/78047794/167903321-65858849-5f4a-4002-8c92-b72addb88242.png">

- [x] Add 5px rounded corners to screenshot

<img width="426" alt="image" src="https://user-images.githubusercontent.com/78047794/167903396-1c42a5ae-e767-483a-9067-5d074a1371af.png">

- [x] Make all chevrons navy

<img width="178" alt="image" src="https://user-images.githubusercontent.com/78047794/167903480-bd521886-fbc6-47e5-8382-f5bd9d5d900c.png">

**Comment by carmenfan** [comment]
Merged into #3168
