### ISSUE TITLE
Redirects in logged out pages

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3240]
### Description
In v5 when the user gets logged out it doesn't redirect to login.   

### Goals
- [ ]  As a user I want to be able to sign in immediately if I've been logged out.
- [ ] As a user I want to go back automatically to the route I where before I got logged out.

### Tasks
- [ ] If a user got logged out redirect them to login (maye keep the route and just render the login?)
- [ ] If the user is in a a route that needs authentication and got redirected to login, redirect to that previous route after he signed in again.

**Comment by sanmont3drepo** [comment]
This one depends on #3220
