### ISSUE TITLE
Realtime event when the user gets kicked out by logging in in a different browser

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3288]
### Description
As policy we don't allow users to log in into the a different browser. For this we signoff the user in the other browser the user has already signed in as well as sending a realtime event to reflect that .  This is already implemented in v4, but we need to implement it in v5.

### Goals
- [ ] As a user I want to know if was automatically signed off the platform in realtime

### Tasks
- [ ] Add the logoff event in v5
- [ ] Suscribe to the logoff event in v5 and logoff the user
- [ ] Show a modal explaining why the user has been kicked out of the platform
