### ISSUE TITLE
Form Dialog refactor

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3302]
### Description
I'm not so sure that the form dialog should have the confirm/cancel thing . It feels very specific to a type of dialog (a confirm dialog)

### Goals
- [ ] As a developer I want to use from dialogs in an easy way

### Tasks
- [ ] Try and see how it feels to have a specific confirm dialog.
- [ ] Try creating a bunch of components for the lower part of the dialog and see how it feels to pass those
