### ISSUE TITLE
Layout system review

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3303]
### Description
I think we are using to many custom components for layout. We should check material ui components for layout again and if its not enough, create our own general ones.
 
### Goals
- [ ] As a dev I want to create layouts in a easy fashion

### Tasks
- [ ] Go page by page, form by form and list the different layout types (columns?) . Compare with George's notes.
- [ ] See if material ui is enough or that  with a bunch of components we can come up with a general layout system.
