### ISSUE TITLE
V5 Project select screen

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3307]
### Description
Adding Project Select screen to V5. This component will show the projects list for the current teamspace and give the user the ability to navigate to a project url, share that url and delete a project.

### Goals
- [ ] As a User I want to select a project from a project list.

### Tasks
- [x] Add a new component to show the projects list in the route `/v5/dashboard/:teamspace/` 
- [x] Add the layout to show a header component, a tab component and the projects list,  as shown in the mockup.
- [x] Create the header component 
- [x] Create the tabs
- [x] Add routing  for  `/v5/dashboard/:teamspace/t/projects` , `/v5/dashboard/:teamspace/t/settings`,`/v5/dashboard/:teamspace/t/users`  and  `/v5/dashboard/:teamspace/t/jobs`.
- [x] Create the projects list container with its search field and new project menu
- [x] Create the project list and the filtering mechanism
- [x] The individual project card must have an ellipsis menu with the share and delete button that will trigger nothing
- [x] Add the create new project card and button
- [x] Add tests if  some redux/saga files are added.

### Differences with the mockup
- The quota bit in the header component will not be addressed here. 

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=5323%3A35803)

**Comment by mosment3DRepo** [comment]
@george-hadfield to review hamburger vs options inside
