### ISSUE TITLE
V5 Legal Papers

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3311]
### Description

For legal reasons 3D Repo needs to have Terms & Conditions and Legal links available in the application

### Goals
- [ ] As a user I want to be able to see the legal terms for the use of 3drepo

### Tasks
- [ ] Update Page Design for Terms & Conditions
- [ ] Update Page Design for Cookies
- [ ] Update Page Design for Privacy
- [x] Add footer to dashboard pages with links

### Related Resources
[Footer mockup](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2427%3A36641)

![Image](https://user-images.githubusercontent.com/62879582/170514973-0b54ed48-1b23-49f0-8ebd-aa0cd239b070.png)

[Legal papers mockup](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=137475%3A180751)

**Comment by sanmont3drepo** [comment]
@george-hadfield  I think we might need a design for the footer in the teamspaces selection screen

**Comment by george-hadfield** [comment]
> @george-hadfield I think we might need a design for the footer in the teamspaces selection screen

One step ahead :)

<img width="603" alt="image" src="https://user-images.githubusercontent.com/78047794/176724023-dc7152b9-a1dc-48b5-b4a2-0ebb66c6cca0.png">

https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=6015%3A42897

**Comment by Amantini1997** [comment]
@george-hadfield will correct me if I'm wrong, but I think tables should take up the whole width
![image](https://user-images.githubusercontent.com/43547703/177114447-911ba80d-41b6-438a-ac60-78ddbbc5819e.png)

**Comment by Amantini1997** [comment]
I think the legal links should be added to all the dashboard pages
![image](https://user-images.githubusercontent.com/43547703/177118282-c4d352a7-2896-4b3f-9307-df6d99e1cf8f.png)

**Comment by george-hadfield** [comment]
> I think the legal links should be added to all the dashboard pages ![image](https://user-images.githubusercontent.com/43547703/177118282-c4d352a7-2896-4b3f-9307-df6d99e1cf8f.png)

Yep - that was the idea :)

**Comment by george-hadfield** [comment]
> @george-hadfield will correct me if I'm wrong, but I think tables should take up the whole width ![image](https://user-images.githubusercontent.com/43547703/177114447-911ba80d-41b6-438a-ac60-78ddbbc5819e.png)

Correct
