### ISSUE TITLE
Safeti base - Risk details

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3317]
### Description
Safeti base  in the viewer  has a broken ui in v5 - we need to update it to make it usable for users.

### Goals
- [ ] As a user I want to use safetibase in v5 with the ui that matches the rest of  v5

### Tasks
- [ ] Fix the layout
- [ ] Update the background colour
- [ ] Update the description field UI
- [ ] Update the Level of risk UI
- [ ] Match the files ui to the new one

### Related Resources

How it looks now:
<img src="https://user-images.githubusercontent.com/42032433/171160439-684d3d5a-4176-440b-b660-0a50a4cc631e.png" 
width="50%"
/>

How it should look:
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136550%3A176546)
