### ISSUE TITLE
Safeti base - Treatment

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3318]
### Description
Safeti base's UI is broken  in the viewer   in v5 - we need to update it to make it usable for users. This is for treatment

### Goals
- [ ]  As a user I want to use the treatment functionality from safetibase in v5

### Tasks
- [ ] Fix the inputs change to the new style
- [ ] The Suggest button is too close to the section above - move all fields down to create space.

### Related Resources
<img width="380" alt="image" src="https://user-images.githubusercontent.com/78047794/172366512-57444e6e-fb71-412c-9262-dea4e1dd1533.png">

[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136550%3A176546)

**Comment by mosment3DRepo** [comment]
> @george-hadfield Should these labels be displayed next to the respective input fields or on top of them? ![image](https://user-images.githubusercontent.com/43547703/174782937-cddc4c9f-684b-405a-8841-3d49630e1126.png)

I think next to the field makes more sense in this situation as vertical space is more valuable

**Comment by Amantini1997** [comment]
When I open the suggestion modal, I am not sure what the content should look like 
![image](https://user-images.githubusercontent.com/43547703/174835206-358feff8-f077-43c8-9842-79d56863b7a1.png)


@george-hadfield could you provide me with a mock up for this?

**Comment by carmenfan** [comment]
@Amantini1997 just make it look like V4 until someone from product team can answer 

![image](https://user-images.githubusercontent.com/11945337/174836522-6c1df705-fbe9-47fb-91ae-39e925ac3cd6.png)


tagging @mosment3DRepo incase you have anything to point out?

**Comment by mosment3DRepo** [comment]
> @Amantini1997 just make it look like V4 until someone from product team can answer
> 
> ![image](https://user-images.githubusercontent.com/11945337/174836522-6c1df705-fbe9-47fb-91ae-39e925ac3cd6.png)
> 
> tagging @mosment3DRepo incase you have anything to point out?

Agreed, @Amantini1997 until George is back I think it's best just to get it as close to V4 but with the new styles. Then George can update the design if needs be
