### ISSUE TITLE
Safeti base - Shapes

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3320]
### Description
Safeti base's UI is broken  in the viewer   in v5 - we need to update it to make it usable for users. This is for the shapes tab.

### Goals
- [ ]  As a user I want to use the shapes functionality from safetibase in v5

### Tasks
- [ ] Fix alignment of save and clear icons
<img width="384" alt="image" src="https://user-images.githubusercontent.com/78047794/172367156-7c940f36-a4a2-4ce1-9304-655362a39f95.png">

- [ ] Fix in colour picker not showing the complete colour in the textfield
<img width="200" alt="image" src="https://user-images.githubusercontent.com/42032433/172438624-de50db29-f795-450a-83b0-0cc2652219b6.png">

### Related Resources
<img src="https://user-images.githubusercontent.com/42032433/171161783-dcb764b8-1eff-4d98-b0c1-a303f8995070.png" 
width="50%"
/>

[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136550%3A176546) 

### Note
**This is broken also in issues, so this should fix both**

**Comment by sanmont3drepo** [comment]
@george-hadfield  I have a question regarding the textfield in the colour picker. Do we want that style? Is hard to figure out that's an input so some functionality might be a bit hidden

**Comment by george-hadfield** [comment]
> @george-hadfield I have a question regarding the textfield in the colour picker. Do we want that style? Is hard to figure out that's an input so some functionality might be a bit hidden

Sure - we can change it to the standard new input field style if thats doable?
