### ISSUE TITLE
Upload revision to a particular container from the containers list

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3322]
### Description
In the containers list there are several places from which a a user can upload a revision, but we are only  using one (from the collapsible menu). Also this way of triggering the modal is not specific for a particular container. 

### Proposal
For the particular revision triggers (ellipsis menu and empty revision list) I think it should directly trigger a file selection (if possible) and auto select the container from which the upload dialog was triggered

### Goals
- [ ] As a user I want the system file selection dialog to open when I select "Upload New Revision" so that I can find the local file I want to upload
- [ ] As a user I want to be limited to a single file selection because I have identified a single container to upload to
- [ ] As a user once the file has been selected I want it to populate the "Upload Files" modal
- [ ] As a user I want the "Destination" container to be pre-populated with the target container I selected in the first step
- [ ] As a user I want the remainder of the workflow to be consistent with bulk file upload
- [ ] As a user I want to see the option to add additional files during the upload process so that users that are unfamiliar with bulk upload (because it is a new feature) will see a hint that it is possible

### Tasks
- [ ] Add the props to the upload form so it can receive a container id and just select that from the start
- [ ] When opening the upload form trigger the browse files if there is a default container pass as a prop

### Related Resources
fig 1
![image](https://user-images.githubusercontent.com/62879582/173838269-23f56564-f9e0-40d5-8ec1-2d3903cf3e15.png)

fig 2
![image](https://user-images.githubusercontent.com/62879582/173838294-511a6406-f5e8-4a81-8461-3b8ad34256bc.png)

fig 3
![image](https://user-images.githubusercontent.com/62879582/173838612-13b8869e-a37a-4939-8c62-fdc6be4d1b72.png)

**Comment by mosment3DRepo** [comment]
@sanmont3drepo I take it this would need a new modal screen as well, or could we take users to the existing model upload modal with single select and then auto select the container?

**Comment by sanmont3drepo** [comment]
> @sanmont3drepo I take it this would need a new modal screen as well, or could we take users to the existing model upload modal with single select and then auto select the container?

I was thinking on using the same modal with preselected container, yep

**Comment by The-Daniel** [comment]
https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=137399%3A182874
The no revision overlay will need a link that includes this.
