### ISSUE TITLE
UI issues and improvements

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3drepo.io#3326]
### Description
We want to polish a bit of the ui for v5;

### Goals
- [ ] As a user I want o see a consistent clean ui 

### Tasks

- [x] The size of the Main nav bar is different when viewing Teamspace vs the viewer https://github.com/3drepo/3drepo.io/issues/3200 **Reduce height of main nav bar to 62px**
- [x] Remove Shadow around Modals (Note this is not the darkened background, but the faint shadow around the modal border)
- [x] Federations/Containers drop down circle button
	- Make hover state the same as on state
	- Clicked state same as on state
- [x] Elipses in Federations and Containers lists
	- Click and on state should inherit hover state colour (light grey)
- [x] Favourites star
	- Remove the surrounding circle in all state instances
	- on hover navy outline turns gold
	- on click fill star gold
- [x] Issue, risks, containers buttons in federation/containers list
	- on hover change button colour to tertiary lighter
	- remove click state
	- remove tooltip and use disabled colour until their actions are added (I think the tooltip and colour are done by just disabling the button)
	- change active background colour from blue to navy
- [ ] Search bar outlined [here](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=36658%3A140)
	- on hover outline turns to base light
- [ ] Text inputs follow Search bar style outline [here](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=36658%3A140)
	- Labels should not change colour on hover/click/active
- [x] User permissions list change Fed/Container name to navy
- [x] User profile circle
	- Change default bg colour to white
	- Change default text to navy
	- No other states (hover, click, active)
- [x] Remove click state from ? and bell circle buttons
- [x] Modal subheaders (Like in file upload. NOT the main modal header, but the smaller one below)
	- Opacity 0.6
- [x] Uploads modal
	- Ensure edit and delte buttons follow same logic as ellipsis
	- Match filename and filesize style to federation/container list items
	- Upload status use body1
	- Destination and rev name input fields changed to 35px height. Maintain the spacing above and below (so increase list item height)
- [x] Tabs on issues/risks reduce padding top by about 5px
- [x] Issues, risks, etc. Open when clicking the title and not just the teal arrow (Also add this to V4)
- [x] Reduce width of change password container to be consistent with login container
- [x] Fix the dashboard tabs bar shadow falling behind elements
- [x] Reduce height of steppers from 85px to 65px
- [x] Add drop shadow to tabs bar in edit profile modal

**Comment by george-hadfield** [comment]
**Fix font weights in File Upload modal**
Too heavy. Will fix with Daniel.

![Image](https://user-images.githubusercontent.com/78047794/177178507-df268c97-a2df-42c8-b2a1-d2c0ed709d17.png)

**Comment by The-Daniel** [comment]
- [ ] Remove Shadow around Modals (Note this is not the darkened background, but the faint shadow around the modal border)
- [ ] Federations/Containers drop down circle button
	- Make hover state the same as on state
	- Clicked state same as on state
- [ ] Elipses in Federations and Containers lists
	- Click and on state should inherit hover state colour (light grey)
- [ ] Favourites star
	- Remove the surrounding circle in all state instances
	- on hover navy outline turns gold
	- on click fill star gold
- [ ] Issue, risks, containers buttons in federation/containers list
	- on hover change button colour to tertiary lighter
	- remove click state
	- remove tooltip and use disabled colour until their actions are added (I think the tooltip and colour are done by just disabling the button)
	- change active background colour from blue to navy
- [ ] Search bar outlined [here]((https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=36658%3A140))
	- on hover outline turns to base light
- [ ] Text inputs follow Search bar style outline [here]((https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=36658%3A140))
	- Labels should not change colour on hover/click/active
- [ ] User permissions list change Fed/Container name to navy
- [ ] User profile circle
	- Change default bg colour to white
	- Change default text to navy
	- No other states (hover, click, active)
- [ ] Remove click state from ? and bell circle buttons
- [ ] Modal subheaders (Like in file upload. NOT the main modal header, but the smaller one below)
	- Opacity 0.6
- [ ] Uploads modal
	- Ensure edit and delte buttons follow same logic as ellipsis
	- Match filename and filesize style to federation/container list items
	- Upload status use body1
	- Destination and rev name input fields changed to 35px height. Maintain the spacing above and below (so increase list item height)
- [ ] Tabs on issues/risks reduce padding top by about 5px
- [ ] Issues, risks, etc. Open when clicking the title and not just the teal arrow (Also add this to V4)
