### ISSUE TITLE
Tweaks to 4.24 migration scripts

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3333]
### Description
A few extra tweaks to help running 4.24. migration scripts

### Tasks
- [x] Missing `[TEAMSPACE]` tag on addIndices logging
- [x] Run all indices in one go instead of wrapping it in Promise.all
- [x] Add option to alter what is returned from getTeamspaces()
