### ISSUE TITLE
Realtime events - New/delete container

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3342]
### Description
In order to get the user updated on changes we are using realtime events. In this case we keep the list of containers list updated with the new and deleted containers  

### Goals
- [ ] As a user I want to know in realtime if someone else added a container
- [ ] As a user I want to know in realtime if someone else deleted a container

### Tasks
- [x] Create a realtime  events file for container events
- [x] Create methods for suscribing to newContainer, dispatch the new container action to add it to the list
- [x] Create methods for suscribing to containerRemoved , dispatch the new container action to remove from the the list
- [x] Suscribe to the project room and the **newContainer**  event in the  the containers list
- [x] Suscribe to the project room and the **containerRemoved** event in the containers list

### Related Resources
Check the format of the data here #3312
