### ISSUE TITLE
Realtime events - New/delete federation

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3343]
### Description
In order to get the user updated on changes we are using realtime events. In this case we keep the list of federations list updated with the new and deleted federation

### Goals
- [ ] As a user I want to know in realtime if someone else added a federation
- [ ] As a user I want to know in realtime if someone else deleted a federation

### Tasks
- [ ] Create methods for suscribing to newFederation, dispatch the new federation action to add it to the list
- [ ] Create methods for suscribing to federationRemoved, dispatch the new federation action to remove from the the list
- [ ] Suscribe to the project room and the **newFederation**  event in the  the federations list
- [ ] Suscribe to the project room and the **federationRemoved** event in the federations list

### Related Resources
Check the format of the data here #3312
