### ISSUE TITLE
Include Drag and Drop to change user avatar

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3348]
### Description
Editing the user profile, the user may only change their avatar using a button (a standard html `<input />` component).
This feature may be improved using a Drag and Drop component instead.

### Goals
- [ ] Allow the user to change their avatar dragging a file instead of selecting it manually.

### Tasks
- [ ] Replace (or enhance) the functionality to change the user avatar to include a Drag and Drop component;
- [ ] Make sure the new Drag and Drop operates the same check on the file as the previous component (file format and image size). 

### Related Resources
![image](https://user-images.githubusercontent.com/43547703/173039675-7e709013-af7c-4ea3-9c28-8b9e9e4f45bd.png)

MockUp : waiting for a mockup
