### ISSUE TITLE
Delete project modal

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3357]
### Description
This issue depends on #3307.
For deleting a project's we are adding a delete project modal. Once the modal has been opened,  the user has to enter the project's name for confirming the project deletion.  This is for added security.

### Goals
- [ ] As a user I want a a way to delete old projects

### Tasks
- [ ] Create the delete project modal.
- [ ] Disable the 'delete project' button until then user enters the project name 
- [ ] Add trigger to open the delete project modal in the project selection component.
- [ ] Add [this endpoint](https://staging.dev.3drepo.io/docs/#/Projects/deleteProject) to the api service
- [ ] Add the pertinent sagas/redux actions
- [ ] Add  tests

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=7374%3A42459)
