### ISSUE TITLE
Share project modal

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3358]
### Description
This issue depends on #3307.
For sharing the project's url we are adding a modal. In the projects list page, in every  there is an ellipsis  menu that should trigger the share modal.

### Goals
- [ ] As a user I want a fast way to share the project's url

### Tasks
- [ ] Create the share project modal
- [ ] Add trigger to open the share project modal in the project selection component.

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=7378%3A42606)
