### ISSUE TITLE
Create new project modal

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3359]
### Description
This issue depends on #3307.
The create new project modal should be triggered from the projects list

### Goals
- [ ] As a user I want to able to create new projects

### Tasks
- [ ]  Create the modal as specified in the design
- [ ] Add [this endpoint](https://staging.dev.3drepo.io/docs/#/Projects/createProject) to the api service
- [ ] Add redux/saga actions for creating a project
- [ ] Add tests for redux/sagas

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=7378%3A43666)
