### ISSUE TITLE
More descriptive messages on teamspace/projects/model/resource not found. (prev: Handle invalid routes)

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3386]
### Description
Invalid routes are not properly handled. 
Trying to access an invalid routes trigger an error modal which is not very descriptive for the user.
![image](https://user-images.githubusercontent.com/43547703/177140089-b894fece-920d-4c87-839b-4723d1d6a3b3.png)

It would be nice to have something similar to what we have in the viewer.

### Goals
- [ ] Invalid routes to should lead to a landing page that correctly informs the user;
- [ ] Error modals should not be triggered

### Tasks
- [ ] Create an invalid-route landing page;
- [ ] Wire the routing so that whenever the user tries to reach an invalid route, they get redirected to that page instead.

**Comment by The-Daniel** [comment]
I understand that this is related to a bug that will probably change with https://github.com/3drepo/3drepo.io/issues/3386, but when the user navigates to an invalid teamspace they can open the modal and the default teamspace is blank. The problem however is that the submit button is enabled when a name is entered despite the teamspace field being empty and required. Just for sanity we should make sure that the teamspace field is actually required

**Comment by carmenfan** [comment]
@Amantini1997  correct me if i'm wrong here, the route format is technically valid right? just the teamspace is not valid/inaccessible to the user?

I think there's 2 situations here:

1. the above - The route is a recognised route but we are unable to fetch the required data due to no access (lack of permissions or non existent teamspace/project)
2. The route is invalid- like if i go to www.3drepo.io/v5/whatever, which we already have a landing page for 
![image](https://user-images.githubusercontent.com/11945337/222122701-05bd3326-d951-42f5-8fef-de2b8b3830e2.png)

**Comment by carmenfan** [comment]
I think for 1. what we are showing is correct, but maybe we we need to do is tweak the error message - the user can't see the content of that page because the teamspace is not found, or they don't have sufficient permissions.

I think the most likely situation of people running into this is when their privilege to the projects is revoked.

**Comment by Amantini1997** [comment]
> @Amantini1997 correct me if i'm wrong here, the route format is technically valid right? just the teamspace is not valid/inaccessible to the user?
> 
> I think there's 2 situations here:
> 
> 1. the above - The route is a recognised route but we are unable to fetch the required data due to no access (lack of permissions or non existent teamspace/project)
> 2. The route is invalid- like if i go to [www.3drepo.io/v5/whatever](http://www.3drepo.io/v5/whatever), which we already have a landing page for
>    ![image](https://user-images.githubusercontent.com/11945337/222122701-05bd3326-d951-42f5-8fef-de2b8b3830e2.png)

That's right, the path is valid, but the user is trying to access a teamspace he has no access to or that does not exist.

However, I think this problem was fixed. Given the path `homepage/{teamspace}/{project}/{model}/{revision}`, when the user tries to access something invalid, they get redirected to the rightmost valid segment in this path.
> e,g, the model is invalid, the user gets redirected to the project (if valid);
the project is invalid, the user gets redirected to the teamspace (if valid)

**Comment by carmenfan** [comment]
ok. Closing then since that's the case.

reopen with more details if we need further changes
