### ISSUE TITLE
Single Sign On: Login

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3396]
### Description
Add the ability to log in via single sign on through AAD

This issue depends on https://github.com/3drepo/3drepo.io/issues/3395

### Goals
- [x] User should be able to log in with a Microsoft account if their 3drepo is linked with one
- [x] User should not be able to login with username/password if their account is setup for SSO
- [x] If a user tries to log in via SSO with an email that is associated with an account not linked up with SSO, they should be given an apprioriate error
- [ ] Forgot password should not send an email to a SSO linked user 
- [x] Server should respond with apprioriate error if AAD is not configured

#### To login via SSO:
route: `GET /sso/aad/authenticate`
This route should redirect the user to Microsoft to authenticate, which then redirects the user to the redirect endpoint

#### Redirect endpoint
route: `GET /sso/aad/authenticate-post`
This route should determine whether the account is associated with a 3drepo account (by means of getting the id and see if there's a matching user)

- If there is a match, we should login as per typical user login (i.e. record the login record, establish the session etc) and redirect the user back to whereever the request specified.
- If the email matched but there is no SSO linkage on the account, apprioriate error should return
- If there is no match at all, it should redirect to sign up as per https://github.com/3drepo/3drepo.io/issues/3395

#### Alteration to existing login
- If an account is associated with an SSO account, normal login route should not work for that user

#### Forgot password
- If a user try to trigger the forgot password journey with an account associated with SSO account, no email should be sent

### Tasks
To be filled in by the developer
