### ISSUE TITLE
Single sign on: Edit profile

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3397]
### Description
Add support to allow a user to link/unlink SSO service to an account

Also impose some restrictions on what the users can edit on their profile

### Goals
- [ ] Users should be able to link their existing account with a microsoft account
- [ ] Users should be able to unlink their existing account from a microsoft account
- [ ] User should not be able to edit any fields associated with the SSO account (e.g. firstname, lastname, email)

#### Knowing if an account has SSO enabled
We need to add a field in [profile data API](https://staging.dev.3drepo.io/docs/#/User/getProfile) to tell the front end whether the account is associated with single sign on or not, this will affect what to display on the profile modal, suggested response (e.g. if the account is  linked to AAD:
````json
{
  "username": "Username1",
  "sso" : "aad",
  "firstName": "Jason",
  "lastName": "Voorhees",
  "email": "jason@vorhees.com",
  "company": "3D Repo",
  "countryCode": "GB",
  "hasAvatar": true,
  "apiKey": "23b61deadbba098fec517dc4fcc84d68"
}
`````

#### Edit profile endpoint change
a SSO linked account cannot change the following:
- Password
- firstname
- lastname
- email

#### Unlink SSO from an account
The user must provide a password along with the request to remove single sign on from the account
route: `POST /sso/aad/unlink`
example payload:
````js
{ 
  password: "abc"
}
````

- The user must be logged in (no API key auth)
- password must be strong enough
- Should throw appropriate error if the account isn't linked with aad

#### Link an account with SSO
route: ` /sso/aad/link`

redirect for Microsoft after authentication
route: `/sso/aad/link-post`

This procedure is very similar to sign up, we must check:
- User must have logged in
- Email isn't already in used by another user
- If the email does not match the one in the account, we overwrite the existing email with the one provided by SSO

### Tasks

- [x] Edit Get Profile endpoint to include isSSO property
- [x] Adjust Get Profile tests
- [x] Make the changes to Edit Profile endpoint to not allow the user to edit certain fields
- [x] Adjust Edit Profile tests 
- [x] Create Unlink endpoint
- [x] Add tests for Unlink endpoint
- [x] Create Link endpoint
- [x] Add tests for Link endpoint
