### ISSUE TITLE
Custom Tickets: Ability to create, edit, get templates

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3399]
### Description
Ability to create custom ticket templates and edit them, and fetch them

### Goals
- [ ] An endpoint to:
  - [ ] create templates
  - [ ] edit a template
  - [ ] get a list of templates
  - [ ] get the details of each template

#### Schema
- template schema
````js
{
  _id: uuid,
  name: string,
  code: string (length 3),
  config: {
     comments: bool, (default: false)
     issueProperties: bool, (default: false)
     defaultView: bool, (default: false),
     defaultImage: bool, (default: false),
     pin: bool (default: false),
     attachments: bool (default: false)
  } ,
  deprecated: bool,
  properties: [
    // additional properties to include in the template, optional
    <fieldObj>,
    <fieldObj>,
  ],
  modules: [
    <moduleObj>
  ]
}
````
- Module object
possible preset modules: https://github.com/3drepo/3drepo.io/blob/ISSUE_3429/backend/src/v5/schemas/tickets/templates.constants.js#L44
````js
// If using one of the default modules
{
  type: string,
  deprecated: bool,
  properties: [
    // any additional custom properties
    <fieldObj>,
    <fieldObj>
  ]
}
// If this is a custom module
{
  name: string,
  deprecated: bool,
  properties: [
    <fieldObj>,
    <fieldObj>
  ]
}

````

- Field object
- supported field types: https://github.com/3drepo/3drepo.io/blob/ISSUE_3429/backend/src/v5/schemas/tickets/templates.constants.js#L29
````js
{
  name: string,
  deprecated: bool,
  type:  string,
  required: bool, //default = false
  default: <type>, //optional, default undefined

  // if "one of" or "many of"
  values: [string]
}
````

#### Notes: 
- order in the array depicts the order to be displayed on the UI
- additional fields are assumed to go below default fields

### Endpoint: Create a template
Route: `POST /teamspaces/{teamspace}/settings/tickets/templates`
sample payload:
````js
{
  name: "Issue",
  code: "xyz",
  config:{
    comments: true,
    issueProperties: true,
    attachments: true,
    defaultView: true,
  }
  properties: [
    { 
      name: "type",
      type: "one of",
      values: [ "For Information", "Clash", "Constructability", "Design", "Diff" ],
      required: true,
      default: "For Information"
    }
  ],
  modules: [
     { type: "sequencing"},
     { type: "shapes"},

  ]
}
````
Response: returns the uuid of the newly created template
  - User must be a teamspace admin
  - Name must be unique
  - Property names cannot clash with defaults

#### Endpoint: Edit a template
Route: `PUT /teamspaces/{teamspace}/settings/tickets/templates/{templateId}`
sample payload:
````js
````js
{
  name: "Issue",
  code: "abc",
  config:{
    comments: true,
    issueProperties: true,
    attachments: true,
    defaultView: true,
  }
  properties: [
    { 
      name: "type",
      type: "one of",
      values: [ "For Information", "Clash", "Constructability", "Design", "Diff" ],
      required: true,
      default: "For Information"
    }
  ],
  modules: [
     { type: "sequencing"},
     { type: "shapes"},
     {
        name: "Custom module a" ,
        properties: [
            { name: "field A", type: "text", required: true}
         ]
     }
  ]
}
````

- User can change the name of a template
- User can turn on/off comments (?)
- User can add new properties/custom modules
- User cannot delete modules/properties, but they can marked deprecated
- the whole template can be deprecated
- User cannot change the type definition of a template
- User can change the order of properties/modules
- If the new schema provided does not contain a field/module it used to have, it will be marked as deprecated

#### Endpoint: List all templates
Route: `GET /teamspaces/{teamspace}/settings/tickets/templates`
response:
````js
{
  templates: [
    {
       _id: "uuid",
       name: "Issues",
      code: "ISE"
       deprecated: true
    },
    {
       _id: "uuid",
        code: "RSK"
       name: "Risk"
    }
  ]
}
````

#### Endpoint: Get template
Route: `GET /teamspaces/{teamspace}/settings/tickets/templates/{templateId}`
response:
````js
 {
  _id: "uuid",
  code: "ISE"
  name: "Issue",
  comments: true,
  properties: [
    { 
      name: "type",
      type: "one of",
      values: [ "For Information", "Clash", "Constructability", "Design", "Diff" ],
      required: true,
      default: "For Information"
    }
  ],
  modules: [
     { type: "sequencing"},
     { type: "shapes"},
     { type: "attachments"}

  ]
}
````

### Tasks
- [x] Write schema for template
- [x] Error checking for default fields
- [x] Error checking on duplicated fields/modules
- [x] make everything camelCase
- [x] Name can't be same as type in modules
- [x] change to issue presets?
- [x] accept jobs as a values option
- [x] Write middleware to validate data
  - [x] POST
  - [x] PUT
- [x] Write middleware to convert data (id, date etc)
  - [x]  GET
- [x] Add functions to save, edit, fetch
- [x] Add endpoints
- [x] write tests
- [x] Documentation on the schema
- [x] Add new config
- [x] Add read only fields
- [x] username + jobs
- [x] code
- [x] last updated

### Related Resources
https://github.com/3drepo/3D-Repo-Product-Team/issues/216
