### ISSUE TITLE
Handle Unexpected Errors Using Axios interceptor

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3416]
### Description
Right now, components that communicate with the backend also need to handle errors on their own.
Errors falls within 3 types:
- Network Errors;
- Expected Errors (the errors specific to the request and that the component should handle properly);
- Unexpected Errors (all the errors left).

In this branch #3359 we decoupled the `<NetworkError />` component such that it makes use of axios interceptors and deal with network errors on its own. It renders and unmount itself completly autonomously.

It would be nice to have something similar for unexpected errors as well. 

When there is an error, a component normally tries to handle it using a bunch of ifs, if the error is not caught by any of them (and it is not a network error), it is an unexpected error.
![image](https://user-images.githubusercontent.com/43547703/179491198-05981966-ea56-4475-9dab-58e2e15ee2f8.png)
> The above snippet is from _editProfilePersonalTab.component.tsx_

But if I pass those functions (emailAreadyExists, isFileFormatUnsupported, etc) to the <UnexpectedError /> component, the latter could be used in a more independent way.

This would be the result:
![image](https://user-images.githubusercontent.com/43547703/179491449-7dc845a1-7869-4832-87f8-d54dab0e96eb.png)

Then, in the `UnexpectedError` component, we would sniff the api response seeing if an error exists and does not match any of the ones passed (or the network error).

### Goals
- [ ] Make the unexpected Error a component that renders itself independently of the parent component, i.e. does not use a conditional rendering in the parent component;
- [ ] Make the sure the resulting code is cleaner and less coupled.

### Tasks
- [ ] Use axios interceptors;
- [ ] Check if the error is expected, if not render the `UnexpectedError` component;
- [ ] Make sure to test the error against network errors as well;

### Related Resources
Check the `NetworkError` component for a reference
