### ISSUE TITLE
v4.25.1 Bugs List

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#3427]
### Bugs
- [x] [Bug 1: GIS Card: Show/hide button cannot be clicket and cannot display/hide map tiles/information](https://github.com/3drepo/3drepo.io/issues/3427#issuecomment-1190418491) (Alessandro)
- [x] [Bug 2: Implementation error warning message appears after changing coordinates](https://github.com/3drepo/3drepo.io/issues/3427#issuecomment-1190426033) (Alessandro)
- [x] [Bug 3: Cannot select "Operation" in Smart Group creation/edit](https://github.com/3drepo/3drepo.io/issues/3427#issuecomment-1191326031) (Santiago)
- [x] [Bug 4: Compare card doesn't open and screen goes blank](https://github.com/3drepo/3drepo.io/issues/3427#issuecomment-1192378603) (Alessandro)
- [x] [Bug 5: Clone button doesn't work for issues and risks](https://github.com/3drepo/3drepo.io/issues/3427#issuecomment-1192649230) (Alessandro)
- [ ] [Bug 6: Import issue BCF fails](https://github.com/3drepo/3drepo.io/issues/3427#issuecomment-1192683760) (this is likely related to #3338)

### UI Oddities
- [x] [UI 1: Plus button dropdown far from button](https://github.com/3drepo/3drepo.io/issues/3427#issuecomment-1190355102) (Alessandro)
- [x] [UI 2: Expand/collapse arrow in Issues/Risks/Groups and BIM card not as expected](https://github.com/3drepo/3drepo.io/issues/3427#issuecomment-1192574252) (Daniel)
- [x] [UI 3: Groups titles exceed margin and shown on top of Show/box icons (for approx >42 characters)](https://github.com/3drepo/3drepo.io/issues/3427#issuecomment-1192583863) (Alessandro)
- [x] [UI 4: When issue status is set to Close, Pin/Edit Image and Update Viewpoint buttons change colour to another blue instead of grey](https://github.com/3drepo/3drepo.io/issues/3427#issuecomment-1192672247) (Santiago)

**Comment by miadibe** [comment]
### 1. Plus button dropdown far from button

**Comment by miadibe** [comment]
### Bug 1: GIS Card: Show/hide button cannot be clicket and cannot display/hide map tiles/information

**Comment by miadibe** [comment]
### Bug 2: Implementation error warning message appears after changing coordinates

###Description

###Steps to replicate 

###Current behaviour

###Expected behaviour

###Pictures/Gifs of the error

**Comment by mosment3DRepo** [comment]
### Cannot select "Operation" in Smart Group creation/edit

### Steps to replicate 
- Create a new Group
- Set Group to Smart group
- Type in "Field"
- Try to select an "Operation" from the dropdown, it does not let you select anything
- Open an existing Group, the same behavior exists when trying to edit


### Expected behaviour
I should be able to select an Operation from th edrop down so that I can create a smart group

### Pictures/Gifs of the error

![GroupOperation](https://user-images.githubusercontent.com/62879582/180194325-dd506ad5-f71d-4ba0-aee5-c68fa21eb295.gif)

**Comment by miadibe** [comment]
### Cannot open Compare card and screen goes blank on click 

### Steps to replicate
Click on the Compare icon, screen goes blank before card appears

### Expected behaviour
I should be able to click on the Compare icon to open the compare card and run my 3D Diff/Instant clash

### Pictures/Gifs of the error
![compare](https://user-images.githubusercontent.com/56918163/180410774-c2680403-37c6-4c69-abf3-52294e7703eb.gif)

**Comment by miadibe** [comment]
### Expand/collapse of filters in BIM card not showing as expected

### Steps to replicate
Add some filters then click on the expand/collapse arrow

### Current behaviour
Collapse is hiding the filters 
![ui 2](https://user-images.githubusercontent.com/56918163/180448858-d09bcc32-125b-440c-9932-e3b05f4a6b0e.gif)

### Expected behaviour
Filter names should be shown as expected
![expected](https://user-images.githubusercontent.com/56918163/180448503-7b5b3df6-2308-4b37-be6f-cc9b3d257521.gif)

**Comment by miadibe** [comment]
### Groups titles exceed margin and shown on top of Show/box icons (for approx >42 characters)
This happens in both the main groups card and when I try to edit an individual group title

### Steps to replicate
Create a group with approx > 40 characters in the title and save it. Notice the oddity in both the group card and the edit group

### Current behaviour
![UI3 3](https://user-images.githubusercontent.com/56918163/180450413-412bbc49-b003-4223-b5da-99e7ccc33baf.JPG)
![UI 3](https://user-images.githubusercontent.com/56918163/180450414-a35e46a0-1d36-4546-9eeb-d17ed9fc2085.JPG)

### Expected behaviour
![image](https://user-images.githubusercontent.com/56918163/180450667-a4c23f63-5f5d-4e66-bc3f-129c7a5c4b5a.png)

**Comment by miadibe** [comment]
### Clone button does not work for issues and risks then some buttons (like arrows cannot be clicked unless we refresh the page)

### Steps to replicate
Create a new issue or risk and save it. Click on the Clone button and notice how nothing happens.
Try going back to the issues or safetiBase card and notice how nothing happens. CTRL + R to be able to go back

### Expected behaviour
- Clone button should work
- As a result a new issue/risk should appear with an editable title 
- We should be able to click on any other arrow to go back buttons should not appear frozen

### Pictures /GIFs of the error
![clone](https://user-images.githubusercontent.com/56918163/180463976-a2781654-b085-46ba-9730-2ce062bd2ed4.gif)
![clone2](https://user-images.githubusercontent.com/56918163/180464386-d713974a-b8ed-4cb7-91ab-f7468dd8094f.gif)

**Comment by miadibe** [comment]
### When issue status is set to Close, Pin/Edit Image and Update Viewpoint buttons change colour to another blue

### Steps to replicate
Create an issue or edit an existing one. Change the status to Closed and notice how the 3 buttons change colours.
This only happens with 'Closed' 

### Expected behaviour
No colour change upon issue status change

### Picture / GIFs of the error
![blue buttons](https://user-images.githubusercontent.com/56918163/180469197-dbae215d-4549-4d32-bf7b-b8ccea3aac28.gif)

**Comment by miadibe** [comment]
### Import Issue BCF fails
This is likely related to #3338 

### Steps to replicate
- Export BCF from existing issues
- Create a federation that has the same model you used 
- Import BCF in this federation and notice the error 

### Picture / GIFs of the error
![image](https://user-images.githubusercontent.com/56918163/180471388-2ae75d86-6294-44bf-a123-b558c3a17998.png)

**Comment by carmenfan** [comment]
> ### Import Issue BCF fails
> This is likely related to #3338
> 
> ### Steps to replicate
> * Export BCF from existing issues
> * Create a federation that has the same model you used
> * Import BCF in this federation and notice the error
> 
> ### Expected behaviour
> For the same model, we should be able to import the list of issues in BCF into the federation or other model
> 
> ### Picture / GIFs of the error
> ![image](https://user-images.githubusercontent.com/56918163/180471388-2ae75d86-6294-44bf-a123-b558c3a17998.png)

@miadibe  can we make sure that we're trying a BCF that works in production to sanity check this?

QA bugs should be new feature/regression related and anything else  should only be considered release blocking if @mosment3DRepo says so

**Comment by miadibe** [comment]
@carmenfan yeah.. it's not working on prod either 
![image](https://user-images.githubusercontent.com/56918163/180473851-03e7df83-c4db-44bb-bcfb-c79015c5486c.png)

**Comment by carmenfan** [comment]
> @carmenfan yeah.. it's not working on prod either ![image](https://user-images.githubusercontent.com/56918163/180473851-03e7df83-c4db-44bb-bcfb-c79015c5486c.png)

@miadibe In that case I would suggest to try a bcf zip that works on production through this version just to make sure the BCF stuff isn't any more broken than before  (I would be surprised if it is, since we haven't touched it this release!)

**Comment by miadibe** [comment]
@mosment3DRepo I've concluded my testing on staging including the plugin uploads to io and confirm nothing else's been detected so far.
