### ISSUE TITLE
Custom Tickets: Endpoints to allow a user to create a custom ticket

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3429]
### Description
with #3399, we have the ability for teamspace admins to store /edit custom ticket templates

We now need a few of endpoints to allow the user to create custom tickets

####  Get a list of available custom templates
Depicts the list of custom templates available for this federation/container

route: `GET /teamspaces/{teamspace}/projects/{project}/containers/{container}/tickets/templates`
route: `GET /teamspaces/{teamspace}/projects/{project}/federations/{federation}/tickets/templates`

optional query: `showDeprecated=true` to show deprecated templates
response:
````js
{
  templates: [
    {
      _id: "uuid string",
      name: "template1",
      code: "abc",
    },
    {
      _id: "uuid string",
      name: "template2",
      code: "def",
    },
    {
      _id: "uuid string",
      name: "template3",
      deprecated: true
      code: "xvc",
    },

  ]
}
````

####  Get custom template
Get the details of a custom ticket template
route: `GET /teamspaces/{teamspace}/projects/{project}/containers/{container}/tickets/templates/{template}`
route: `GET /teamspaces/{teamspace}/projects/{project}/federations/{federation}/tickets/templates/{template}`

optional query: `showDeprecated=true` to include deprecated modules/properties

response: 
````js
{
  _id: "uuid string",
  name: "name of the template" ,
  code: "abc",
  properties: [
    { 
        name: "Created at", 
        type: "date",
        readOnly: true
    },
    {
       //...
    }

  ],
  modules: [
  ]
}
````

#### Create a ticket base on a custom template

route: `POST /teamspaces/{teamspace}/projects/{project}/containers/{container}/tickets/`
route: `POST /teamspaces/{teamspace}/projects/{project}/federations/{federation}/tickets/`
payload:
````js
{
  type: "template id",
  // ... fields that satisfies the template schema
  properties: {
    "Priority" : "Low"
  }, modules: {
    customModule1: {
      customField1: "abc"
    }
  }
}
````
response:
````js
{
  _id : "ticket id"
}
````

##### NOTE:
unlike the one in teamspace setting (#3399), this one should be the full schema, including the default properties.

### Goals
- [x] Users should be able to get a list of available templates
- [x] Users should be able to get the schema of a specific template
- [ ] Users should be able to create a ticket base on the schema

### Tasks
- [x] Mark read only fields (e.g. owner, created at)
- [x] end point to get a list of template names & ids
- [x] end point to get the details of a specific template
- [x] endpoint to create a ticket base on a template
  - [x] move attachments to configuration
  - [x] fledge out safetibase schema
  - [x] create validator
  - [x] write in read only values
  - [x] deal with preset modules
  - [x] add code to template list
  - [ ] remove tickets if the project/container gets removed
  - [ ] deal with groups
- [x] copy routes over to federations

### Related Resources
APIs to create custom ticket templates: #3399 
Original scope: https://github.com/3drepo/3D-Repo-Product-Team/issues/216
