### ISSUE TITLE
Additional utility/cron scripts

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3433]
### Description

Here is a list of some useful utility scripts that form part of a well run installation of io

#### Periodic share directory cleaner
_Scheduled?: daily_
To allow for time to investigate failed model processing, the current bouncer process leaves the uploaded models on the folder that is shared with bouncer. However for data retention and storage reasons, it's sensible to clear those down. We currently run a script externally to clear down the $SHARED_DIR/queue to maintain it at 14 days of age of file.

#### Remove Unverified Users
_Scheduled?: daily_
Exists currently as a [separate mongo js](https://github.com/3drepo/3drepo.io/blob/master/scripts/dbMaintenance/removeUnverifiedExpiredUsers.js) but could be rolled into a utility script for ease of management and implementation. It has also been copied into the helm chart for installation currently by using the contents of the script.

#### Reset processing flag
_Scheduled?: no_
Occasionally there may be an error with model processing that requires the flag to be reset on a particular model or teamspace, or the entire system. A script exists currently but it isn't possible to target a teamspace or particular model

#### license verification and information check
_Scheduled?: no_
Whilst io is open source and does not require a license to operate, 3D Repo does offer a licensed system for the 3drepobouncer/3drepounity system. It is possible to [add your license key to the config ](https://github.com/3drepo/3drepo.io/pull/3042) for better reporting, so if present it could be useful to check the expiry details and permissions set.

<details><summary>Belongs in an endpoint thus out of scope</summary>
-  Queue Monitor

We are exporting the queue stats to cloudwatch using an [external system](https://github.com/3drepo/DevOps/tree/master/docker/3drepoqueuemonitor) currently, and this could be rolled into IO.

</details>

<details><summary>Belongs to a devops script suite thus won't implement</summary>
- General Utility option to loop with a delay on long running tasks

Occasionally we wish to run batches of commands slowly over time as to not overload the system, so a configuration option to have loops operate at an interval could be useful.

- rabbitMQ initialisation

Currently we init the rabbitMQ queues externally to an IO installation but in the case of a local installation for development or small installations it could be useful to have the commands required to bootstrap a persistent rabbitmq installation.

- MongoDB initialisation

In the past there were mongo scripts created to create custom roles that give tight security for the minimal amount of operations required for IO to operate in a secure manner. In local deployments these steps are missed, so developed under accounts with higher permissions than required. We could revisit this to make it easier for new installations to be configured securely.
</details>

### Goals
- [x] Review suggestions and decide what to implement
- [x] Implement additional scripts
- [ ] Implement a way to run a scheduled script

### Tasks
- [x] Write new utility scripts
  - [x] Periodic share directory cleaner
  - [x] Remove Unverified Users
  - [x] Reset processing flag
  - [x] License verification and information check
- [x] Implement a way to run scheduled scripts
  - [x] Add email notification if scheduled scripts failed

**Comment by keifgwinn** [comment]
- Queue Monitor

Just had an idea that these could probably be published as Prometheus style stats endpoint

**Comment by carmenfan** [comment]
I think it's a no on these 3:

> General Utility option to loop with a delay on long running tasks
> Occasionally we wish to run batches of commands slowly over time as to not overload the system, so a configuration option to have loops operate at an interval could be useful.
> 
> rabbitMQ initialisation
> Currently we init the rabbitMQ queues externally to an IO installation but in the case of a local installation for development or small installations it could be useful to have the commands required to bootstrap a persistent rabbitmq installation.
> 
> MongoDB initialisation
> In the past there were mongo scripts created to create custom roles that give tight security for the minimal amount of operations required for IO to operate in a secure manner. In local deployments these steps are missed, so developed under accounts with higher permissions than required. We could revisit this to make it easier for new installations to be configured securely.

On the basis that the utility script here is a NodeJS application that piggy backs on the backend codebase. The above either can't be done (e.g. talking to rabbitmq without authentication) or all we're doing in the nodejs script is to call `process.spawn` to run some linux command (which could be difficult to make cross platform, and also difficult to write unit tests for)

I think there's a need for a more generic utility scripts suite in the devops/local repo where these things sit. We should keep this 3drepo.io more specific to business logic

**Comment by carmenfan** [comment]
> * Queue Monitor
> 
> Just had an idea that these could probably be published as Prometheus style stats endpoint

Is this more appropriate to add to #1883?
