### ISSUE TITLE
Updated style for text inputs/search bars

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3444]
### Description

Adding the Groups feature into 3D Repo, allowing the user to create/edit/delete groups
Initially described in #3326. The text inputs, search bars, and select fields need to follow updated spec outline [here](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=36658%3A140).

### Goals
- [ ]  As a user I want o see a consistent clean ui

### Tasks
- [ ] Search bar outlined [here](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=36658%3A140)
	- on hover outline turns to base light
- [ ] Text inputs follow Search bar style outline [here](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=36658%3A140)
	- Labels should not change colour on hover/click/active
