### ISSUE TITLE
Improve list render performance

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3450]
### Description
Currently every element of a list is rerendered if just one item needs rerendering. For instance just expanding a container in the containers list causes an entire list rerender. This is greatly inefficient, and is quite noticable when you have a lot of items in the containers, federations, and uploads lists.

One can observe this using the React Developer Tools extension for Chrome or Firefox. Open one of the React tabs in the Dev Tools and by clicking the settings cog you can turn on the setting "Highlight updates when components render". Now you can see when elements are unnecessarily rerendered.

These items are rerendered because React thinks their props are changing despite the fact they're not. This is because some of the props are anonymous functions, which will always get a new reference on every render. This problem can be avoided by memoising the functions using the [useCallback](https://reactjs.org/docs/hooks-reference.html#usecallback) hook.

### Things to ponder
- [ ] Which lists do we need this for? We probably only need it for lists that we expect to have many items and if the render function is performance heavy. 
- [ ] Is there a package to make memoised react lists simpler?
- [ ] Are there any helper functions we could create for this

#### Memoising list items
I did a test on the containers list. I memoised the component using React memo(). I memoised the functions passed to this component using useCallback(). I passed _.isEqual to the memo function otherwise the items will rerender because it thinks the container object has different (because comparing two objects with the same values, this the same for arrays)

Memoised vs Unmemoised: Expanding a list item in a container list of 40 containers.
Memoised
![image](https://user-images.githubusercontent.com/62481250/182417841-feaee816-3211-49dc-afd5-20406b3d5f19.png)
Unmemoised (what it is currently)
![image](https://user-images.githubusercontent.com/62481250/182417195-30f9d899-ee36-4bdb-8039-924f43952ea6.png)
The time it takes to expand a list item is almost halved in this case (Interaction to next paint). This difference will be greater the larger the list is.

I think this change will benefit the upload file modal most. Try adding 10+ files and then typing in the revision tag field. Each change rerenders the entire list and causes what you type to lag! Even opening the sidebar is slow when you add many files

---
#### Webpack
It appears that the app runs a lot slower locally. Using Chrome's Lighthouse Devtool I found the loading page for the exact same page locally vs on staging.3drepo.org
**Local:** 11.3s
**Staging:** 5.8s
The largest script the local test loaded was a 3,547.3 KiB Webpack file.

---
#### [Lazy load](https://reactjs.org/docs/code-splitting.html#reactlazy)
When a page is loaded in React everything is loaded at once. Lazy loading lets you defer the loading of certain modules that aren't critical to the initial page load. This could be modals or elements which require conditions to be met before they appear. It also lets you use a placeholder element for when the element is loading. (I don't think we can replace our current method of using skeleton elements with this.)

The Elements have to be exported as default unless you use the module **[react-lazily](https://www.npmjs.com/package/react-lazily)** which lets you deconstruct an import.

---
#### Remove unnecessary fetchContainers calls
If you are on the containers list page then move to another page before returning to the containers list the list appears briefly before it is reloaded. This unnecessary reload occurs in `containers.hooks.ts`. I was able to prevent this call by checking if the containers array is empty, but there is probably a better way with memoisation (edit. I found a better way using redux as described below). 

This may have the problem of if another user adds a container when you are not on the containers list the realtime event will not be heard and you won't see the new container until refresh. Would it be a good idea to run the fetchContainers/fetchFederations actions in the background when you are on any of the dashboard pages and have the event listeners on all these pages too? In other words if you were to load any of the dashboard pages (e.g. User Permissions) the fetchContainers and fetchFederations actions will be called and update the redux state (after everything else on that page has loaded). Then if the user navigates to the containers/federations list they will already be loaded. An entire reload of the fed/cont list can be avoided by returning the initial state in the fetchStats actions if the new stats object is the same as the one in the initial state. At the moment if the new stats object is the same as the old one it still updates the state because the objects dont have the same reference and are therefore perceived as different.

This might differ if we switch to Immer #3031, but there are definitely ways to improve the Redux efficiency.

There is also a fetchContainers action being called multiple times in the Federations list. This is because the containers are fetched when the EditFederation Modal is loaded (This might not be such a problem if the list items are memoised. In my tests I've only been focusing on the containers list. I think the modals get rerendered every time a new list item causes the list to rerender)

---

#### Other
We also have modal components in the list item components (e.g. ContainerSettingsForm). Would it be better to put these higher in the DOM so they aren't called everytime a list tiem renders? This could also be avoided if we switched the method we use for loading modals to using redux actions.

### Goals
- [ ] have more efficient lists

### Tasks
- [ ] Research how to improve list render times
- [ ] Research how to improve page load times
- [ ] Discuss the viability of these options
- [ ] Implement changes where deemed appropriate

### Related Resources
There are a lot of good guides. I think [this one](https://alexsidorenko.com/blog/react-list-rerender/) is straightforward
[React Dev Tools (Chrome)](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en)
[React Dev Tools (Firefox)](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/)
[useCallback](https://reactjs.org/docs/hooks-reference.html#usecallback)
[memo](https://reactjs.org/docs/react-api.html#reactmemo)
[Lazy load](https://reactjs.org/docs/code-splitting.html#reactlazy)

### Notes:
I have pushed some changes to this branch to give examples of adding these suggestions to the containers list. This isn't intended as a finished thing.
