### ISSUE TITLE
Enable automatic destroy on close of issue

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3460]
### Description

Automatically destroy a deployment when the pull request is closed.

### Goals

- [x] Automatically delete from the dev platform on closure.

### Tasks

- [x] Create a new DevOps pipeline
- [x] Add to .github/workflows/onPRClose.yml

**Comment by carmenfan** [comment]
@keifgwinn  while you're there can you rename `onStagingCommits` to `onPRClose`?

To more accurately reflect what we're capturing

**Comment by keifgwinn** [comment]
onPRClose change I'm moving to a new issue due to the github actions requirement

**Comment by keifgwinn** [comment]
#3471 fixes some bugs in this
