### ISSUE TITLE
  .github/workflows/onStagingCommits.yml → .github/workflows/onPRClose.yml

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3461]
### Description

Change the name of the workflow to more accurately reflect its purpose.

### Goals

- [x] Change work flow filename
- [x] update github action

### Tasks
- [x] Change work flow filename
- [x] update github action
