### ISSUE TITLE
Create container/fed with an existing name should not trigger modal

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3470]
### Description
Creating a container/fed with a name already taken triggers an error modal. This was the old behaviour. The new behaviour is to handle the error in the component itself and show up a form helper message right under the name input field.
This behaviour can be observed in the `create project modal`, where attempting to create a new project using an already taken name, results in such a behaviour.

### Goals
- [ ] Create container/federation modal should handle existing name itself and not close;
- [ ] An error modal should not be triggered;
- [ ] A form helper error should be displayed.

### Tasks
- [ ] Use standard RHF error to handle existing name error.

**Comment by carmenfan** [comment]
closing as duplicate of #3385
