### ISSUE TITLE
Rewrite Redux and Selector tests: Containers

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3481]
### Description
Right now, we have a unit test for each selector and for each redux method. This is too specific about the internal store structure, and future changes in the store structure, may lead to several tests to not pass.

What we should have instead, is a test file (one for each store object like containers, teamspaces, auth, etc.) which alters the state (using a reducer) and then checks the state is correct (using a selector).

### Goals
- [ ] The new tests should integrate both the redux and the selector tests;
- [ ] The new tests should not care about the internal store structure.

### Tasks
- [ ] Create a new test file for containers

### Related Resources
Example of how to write a container test:
```ts
describe('Containers: redux', () => {
	const projectId = 'projectId';
	const mockContainers = times(5, () => containerMockFactory({ isFavourite: false }));
	const defaultState:IContainersState = {
		...INITIAL_STATE,
	};

	it('should set the containers properly', () => {
		const resultState: IContainersState = containersReducer(
			defaultState,
			ContainersActions.fetchContainersSuccess(projectId, mockContainers),
		);
		const containers = selectContainers.resultFunc(resultState, projectId);
		expect(containers).toEqual(mockContainers);
	});
});
```
**Note** the use of a selector
```ts
...
);
const containers = selectContainers.resultFunc(resultState, projectId);
expect(containers).toEqual(mockContainers);
...
```

Also **Note** the difference with the older default state object (aware of the internal store structure)
```ts
...
const defaultState:IContainersState = {
	...INITIAL_STATE,
	containersByProject: {
		[projectId]: mockContainers
	}
};
...
```
