### ISSUE TITLE
Rewrite Redux and Selector tests: Teamspaces

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3490]
### Description
Right now, we have a unit test for each selector and for each redux method. This is too specific about the internal store structure, and future changes in the store structure, may lead to several tests to not pass.

What we should have instead, is a test file (one for each store object like containers, teamspaces, auth, etc.) which alters the state (using a reducer) and then checks the state is correct (using a selector).

### Goals
- [ ] The new tests should integrate both the redux and the selector tests;
- [ ] The new tests should not care about the internal store structure.

### Tasks
- [ ] Create a new test file for teamspaces

### Related Resources
Check this branch for reference https://github.com/3drepo/3drepo.io/issues/3481
