### ISSUE TITLE
Get icons into storybook

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3496]
### Description
Sometimes for finding icons is a bit of a hassle. Having a searchable sample list in storybook would help to dint them easily

### Goals
- [ ] As a developer/designer I want to be able to find icons easily to know which ones are available and which ones I need to add

### Tasks
- [ ] Research if there is a plugin for storybook
- [ ] In case there is not, or is not applyable to our case design a solution
