### ISSUE TITLE
Viewer canvas does not stretch behind navbar

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3504]
### Description
- Revert #3232
- This change caused problems. Reverting this will solve #3456 and #3457

### Goals
- [ ] Be able to access the viewer without elements being obscured by the navbar

### Tasks
- [ ] Revert opacity of navbar to 1
- [ ] Prevent canvas from extending behind navbar

**Comment by mosment3DRepo** [comment]
Closed https://github.com/3drepo/3drepo.io/issues/3456 and https://github.com/3drepo/3drepo.io/issues/3457 as no longer required
