### ISSUE TITLE
Add additional start up modes to the container

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3519]
### Description

To assist on local build and debugging I'd like to add some additional scripts to the container for starting up in debug mode.

### Goals

- [ ] Add a backend yarn watch start mode on linux
- [ ] Add a frontend yarn rebuild

### Tasks

- [ ] add some options to the init script

**Comment by keifgwinn** [comment]
solved this another way, with the internal local repo
