### ISSUE TITLE
Rewrite redux file to use Immer.js: Teamspaces

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3524]
### Description
Updating a redux state the standard way is a nuisance. Using Immer.js makes the code cleaner and more intuitive.

### Goals
- [ ] Make update redux states easier and cleaner;
- [ ] Avoid increases in code complexity/length;

### Tasks
- [ ] Use Immer produce-syntax to update redux states
- [ ] Finding a suitable single point modification to avoid using `produce` for every single reducer
- [ ] EXTRA, the first parameter of a reducer is the current state which has a default value `state = INITIAL_STATE`. The default value is not necessary as the state always falls back to that value because of redux-sauce's `createReducers`. Remove that assignment.
