### ISSUE TITLE
Custom Tickets: Thumbnail

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3540]
### Description
An endpoint to return the thumbnail of a custom ticket

route: `GET /teamspaces/{teamspace}/projects/{project}/containers/{container}/tickets/{ticket}/thumbnail`
Should return the image if available, 404 if not found.

Every time the default image is updated we need to remove the old thumbnail and update it with a new one.

### Technical Specification
- The thumbnail should be stored like all other files via filesManager service. The name should be `{ticket}_thumbnail`.
- The file ref should contain meta for teamspace, project, model information just like image properties implemented in #3429 
- The thumbnail should be a resized version of the default image just like v4

### Goals
- [ ] The user should be able to obtain a thumbnail for their ticket if it is available
- [ ] The thumbnail should be updated everytime the default image is updated
- [ ] There should be no zombie images, old thumbnails should be removed when we update to a new thumbnail

### Tasks
- [ ] Create thumbnail when default image is added/updated
- [ ] Remove old thumbnail if default image is removed/updated
- [ ] add endpoint to return thumbnail

### Related Resources
This issue depends on #3429 
Custom ticket scope: https://github.com/3drepo/3D-Repo-Product-Team/issues/216

**Comment by carmenfan** [comment]
@mosment3DRepo I removed the 4.28.0 label (again) as it was decided that you guys don't want thumbnails full stop.

If we've changed our minds then I think we need to schedule it in at a later release
