### ISSUE TITLE
Custom tickets: Get ticket by id

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3545]
### Description
Ability to get the ticket data given the id

route: `HTTP GET /teamspaces/{teamspace}/projects/{project}/federations/{federation}/tickets/{ticket}`
query string: 
  - showDeprecated: will include deprecated fields and their values, default = false
response: the ticket with any necessary fields serialised (e.g. UUIDs, dates)

route: `HTTP GET /teamspaces/{teamspace}/projects/{project}/federations/{federation}/tickets/{ticket}/resources/{resource}`
This is used to get blob resources such as images, files

### Goals
- [x] The user should be able to get the ticket details given a ticket id
- [x] the user should be able to fetch any documents/images given the resource id

### Tasks
- [x] endpoint to return resources
- [x] endpoint to return ticket detail
  - [x] middleware to cast
  - [x] ensure extra fields are not provided
- [x] finish off tests for resources/add ticket using get endpoint 
- [x] copy over to federation routes

### Related Resources
This issue depends on #3429 
Custom ticket scope: https://github.com/3drepo/3D-Repo-Product-Team/issues/216
