### ISSUE TITLE
Memoize list items (improve performance)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3566]
### Description
As a user I want a streamline experience and performance always imspact this. Because we have so many lists if we can improve on the performance of these we can deliver a bit of value to the ux
This is also detailed here: #3450 

### Goals
- [ ]  Navigate lists without feeling lag or anything of the sort

### Tasks
- [x] Memoize containers list
- [x] Memoize federations list
- [x] Memoize edit federations (containers list)
- [ ] Memoize upload containers list

### Notes
- Be aware that filtering (including highlighting of the results) should keep on working
- Take in consideration also that ordering by columns should work
