### ISSUE TITLE
Custom tickets - v5 Card

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3582]
### Description
We want to move on replacing the components inside the viewer to v5. One of the building blocks is the card.

### Goals
- [ ] As a user I want to navigate to the v5 viewer and have the the cards with the new ui 

### Tasks
- [ ] Test out a way to include a v5 card in the viewer.
- [ ] Create the card according to the design

### Notes
- This is only for the empty card without content and that can be shown in the viewer
- This card wont have the buttons from the top right
-  Figure a way to understand how this integrates in general with the viewer

### Related Resources
[MockUp](https://www.figma.com/file/VN7KvPD5hqDlTuqdIsm3vO/Custom-tickets?node-id=46%3A5533)
