### ISSUE TITLE
Custom tickets - Basic list for custom tickets (MAIN ISSUE FOR CUSTOM TICKETS)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3583]
### Description
We are starting to implement custom tickets. The first thing to have is to have a list with the ticikets.

### Goals
- [ ] As a user i want to be able to list all of my tickets in one place

### Tasks
- [ ] Create the list for custom tickets 
- [ ] Create the basic list item (ticket-id/ title)
- [ ] the title is clickable 
- [ ] Add filtering by ticket type
- [ ] Create redux/sagas bits for getting tickets
- [ ] Write tests
- [ ] Mock response for tickets

### Notes
-  Ticket types load with no types set and will display all tickets. Selecting a type will filter out all other types apart from selected. Can select multiple types. 

### Related Resources
[MockUp](https://www.figma.com/file/VN7KvPD5hqDlTuqdIsm3vO/Custom-tickets?node-id=86%3A5356)

[Api for tickets list](https://github.com/3drepo/3drepo.io/issues/3575)

[Api for template list](https://staging.dev.3drepo.io/docs/#/Teamspaces/ticketTemplateList)

**Comment by george-hadfield** [comment]
### Error modal needs a fixed width

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/78047794/204541078-4a4b48d6-0961-4691-9d27-904cf6f0a1b4.png">

**Comment by george-hadfield** [comment]
### Make Assignee list show ALL assignees

<img width="522" alt="image" src="https://user-images.githubusercontent.com/78047794/204541284-39b6dd13-5efc-4328-8861-56550d3c9467.png">

**Comment by george-hadfield** [comment]
### Reduce size of chevrons slightly and ensure they are centered

Reduce by 2 px

<img width="174" alt="image" src="https://user-images.githubusercontent.com/78047794/204541597-4e8ffccf-5736-49e0-908d-a5f3cbe0fa1b.png">

**Comment by george-hadfield** [comment]
### Reduce back arrow size

Reduce to 1.2rem from 1.5rem

<img width="275" alt="image" src="https://user-images.githubusercontent.com/78047794/204542012-bea2bcb8-e363-49b3-88aa-2f7ed02b968f.png">

**Comment by george-hadfield** [comment]
### When creating a new ticket, ensure the vertical padding around 'save tick' button is equal



<img width="311" alt="image" src="https://user-images.githubusercontent.com/78047794/204542565-92257f6c-3846-4482-ab15-67ce289d4f14.png">

**Comment by george-hadfield** [comment]
### Remove focus state after creating a ticket

Currently when creating a ticket, after clicking save, the ticket is created but the title input changes to a focused state. Please remove the focus state after saving

<img width="436" alt="image" src="https://user-images.githubusercontent.com/78047794/204543088-6a30c3fe-2ce6-4c26-a7c0-ae177ef5d5a6.png">

**Comment by george-hadfield** [comment]
### Change the border colour of disabled inputs

The border for disabled inputs looks to be the same as non-disabled ones. Disabled input should have a border colour of secondary.lightest (#E8EAED)

<img width="404" alt="image" src="https://user-images.githubusercontent.com/78047794/204543586-96619222-74bd-48fe-9e68-f400946afbb8.png">

**Comment by george-hadfield** [comment]
### Add a space after each comma on Assignee list

<img width="441" alt="image" src="https://user-images.githubusercontent.com/78047794/204549079-f841feb8-1210-4758-baa5-68c1617d843e.png">
