### ISSUE TITLE
Custom tickets - List with different tickets types

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3584]
### Description
Different types of tickets have different properties but we want to provide the user the basic useful information in the list.

### Goals
- [ ] As a user I want to get the basic gist of each ticket in the tickets list

### Tasks
- [ ] Create control for assigned people
- [ ] Create status controls 
- [ ] Update ticket item to reflect the actual ticket 

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=323%3A3)

**Comment by carmenfan** [comment]
Merged into base branch
