### ISSUE TITLE
Memoize Upload File List items (improve performance)

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3589]
### Description
Split off from #3566.
The upload file list is more complicated to memoise so this issue has been made

### Goals
- [ ] Use upload file list without feeling lag or anything of the sort

### Tasks
- [ ] start using FormContext (?)
- [ ] memoise functions being passed into list items
- [ ] memoise list item

### Related Resources

#3450
 #3566
