### ISSUE TITLE
Custom tickets - Realtime events 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3590]
### Description
When using  custom tickets we want to show the user the latest data, for this purpose we'll use realtime events to keep the user updated on any change

### Goals
- [ ] As a user I want to see the list of tickets always updated.

### Tasks
- [ ] Add realtime event subscription for tickets
- [ ] Add event for deletion
- [ ] Add event for new ticket
- [ ] Add event for update ticket.
- [ ] Subscribe I the proper file .
- [ ] What happens when the user is eding a tickit and a new update from the ticket gets received?

### Related Resources
[events](https://github.com/3drepo/3drepo.io/issues/3577)

**Comment by carmenfan** [comment]
Merged into the main branch
