### ISSUE TITLE
Fix/test for circular dependencies in v5

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3611]
### Description
Sometimes is very easy to creep in a circular dependency. These generate unexpected issues, with some circular dependencies the app can run as if there was no problem, but with other some objects can become undefined and break everything.  

### Goals
- [ ] As a dev I want to be sure that the code that I commit doesn't cause circular dependencies

### Tasks
- [ ] Check for circular dependencies (he have already this package installed https://www.npmjs.com/package/dpdm)
- [ ] Fix any circular dependency (primarily for v5, if we can get away with that one leave v4 alone)
- [ ] Add test in building process to check for circular dependencies when the code is pushed to github

### Related Resources
[DPDM](https://www.npmjs.com/package/dpdm)

**Comment by carmenfan** [comment]
this is done via #4321 ? @sanmont3drepo

**Comment by carmenfan** [comment]
This was done via #4321
