### ISSUE TITLE
Custom tickets - Assignees list

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3624]
### Description
Right now the assignees modal is very basic. In order to provide a bit more of information we are pushing a new design.
- The list is separated in two lists:  roles and users with a divider between them
- The list is ordered by first name
- The part with users have the avatar, fullname and role in the company
- On hover in the users the tooltip with more information for the user will appear (reuse the same tooltip we have) 
- The list should maintain the search capabilities (including highlighting)

### Goals
- [ ] As a user I want to have a friendlier way to search the users  

### Tasks
- [ ] Create the Roles item component
- [ ] Create the user item component
- [ ] Add hover to user item

### Related Resources
[Mock up](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=2724%3A22061&t=9fVWe6lH0lpqQNe9-0)

**Comment by george-hadfield** [comment]
### Updated link ready for approval

https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=2724%3A22061&t=apOADOloVmXENTe3-1
