### ISSUE TITLE
Custom tickets - basic comments module

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3626]
### Description
The initial implementation for comments in custom tickets. Designed to correct frustrating issues people have had in the past (low character limit) and include the most popular functionality.

Some features that are present in V4 (mentions and markdown) are not included in this scope as it was felt they would be better off waiting for an improved notification system.

Future scope included in https://github.com/3drepo/3drepo.io/issues/3631

### Goals
- Quote previous messages by selecting the quote icon on any previous message
- Limit length of message to LONG_TEXT_CHAR_LIM (1200)
- Hovering over the username presents more details of the user that typed the comment.
- Comments made should appear immediately in other user's browser if they have the same ticket open (chat server)

### Tasks
- [ ] Basic comments accordion (should be the accordion on custom tickets and only show if the comments setting in the template is on) 
- [ ] Writing area for comments component
- [ ] The written comments component (comments list)
- [ ] Comment bubble component 
- [ ] Reply message component (in writting area)

### Notes
The markdown for replies should follow this format

```
![CommentText](ee1aa9fa-5d17-464c-a8ba-f685203b911f)
![CommentImage]([...ids])
> This is the quoted comment text
I disagree with you because Im better.
```

### Related Resources
[Link to design](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=2443%3A17425&t=FJhl7Q2lhh416uTp-0)

#### backend 
[LInk to issue
](https://github.com/3drepo/3drepo.io/issues/3774)

**Comment by george-hadfield** [comment]
[Link to design](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1554%3A13803)

**Comment by george-hadfield** [comment]
[Link to design](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1591%3A13853&t=nTPe0G1h49KEHZSy-1)
