### ISSUE TITLE
Custom tickets - Tickets details - Pin modules component

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3630]
### Description
We need a component to have the pin property represented. This issue is for the visual component.

### Goals
- [ ] As a developer I want to have a component to use to represent pin property and edition 

### Tasks
- [ ] Create the empty state (if the pin prop is empty)
- [ ] Create the add pin state (if the pin prop is empty and the internal state is in edit mode)
- [ ] Create the change pin state (if the pin prop is not empty)
- [ ] Create the changing pin state (if the pin prop is not empty and the internal state is in edit mode)

### Related Resources
[Mockup](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=646%3A6011)

**Comment by george-hadfield** [comment]
Link to #3630 designs https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=520%3A9837

**Comment by sanmont3drepo** [comment]
Merged to the main branch
