### ISSUE TITLE
Update favicons

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3633]
### Description

We have refreshed branding, and can update the current favicon set.

### Goals
- [ ] Serve the new favicons

### Tasks

- [ ] Update base favicon.ico route
- [ ] add the larger sizes options to the html head prompt

### Related Resources
Favicon package: [favicon_io.zip](https://github.com/3drepo/3drepo.io/files/9549046/favicon_io.zip)
