### ISSUE TITLE
V5 Groups - List of UI oddities

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#3637]
### UI Oddities
- [x] [1. Group title ](https://github.com/3drepo/3drepo.io/issues/3637#issuecomment-1245273957)
- [x] [2. Group title in groups card](https://github.com/3drepo/3drepo.io/issues/3637#issuecomment-1245274838)
- [ ] [3. Field filter Scroll bar](https://github.com/3drepo/3drepo.io/issues/3637#issuecomment-1245275469) 
- [ ] [4. Measurements menu typo](https://github.com/3drepo/3drepo.io/issues/3637#issuecomment-1245276029)

**Comment by miadibe** [comment]
### 1. Group title
Highlighting objects on a federation node that would highlight multiple sub models is not functioning.

- This is happening in: prod/staging/both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- Open this model: `a link to the model`
- click on the root node of a federated tree

### Current Behaviour
- Only one of the models was highlighted.

### Expected Behaviour
- All models should be highlighted

### Pictures/ Gifs of the error
![Group title](https://user-images.githubusercontent.com/56918163/189889286-faf4e4c9-3687-4f98-b200-c8f26676042a.png)

**Comment by miadibe** [comment]
### Group title in groups card
Highlighting objects on a federation node that would highlight multiple sub models is not functioning.

- This is happening in: prod/staging/both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- Open this model: `a link to the model`
- click on the root node of a federated tree

### Current Behaviour
- Only one of the models was highlighted.

### Expected Behaviour
- All models should be highlighted

### Pictures/ Gifs of the error
![Group title groups card](https://user-images.githubusercontent.com/56918163/189889379-8990ce19-f344-4573-87c5-b6c202f4fbab.png)

**Comment by miadibe** [comment]
### 3. Field filter scroll bar

Highlighting objects on a federation node that would highlight multiple sub models is not functioning.

- This is happening in: prod/staging/both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- Open this model: `a link to the model`
- click on the root node of a federated tree

### Current Behaviour
- Only one of the models was highlighted.

### Expected Behaviour
- All models should be highlighted

### Pictures/ Gifs of the error
![scroll bar](https://user-images.githubusercontent.com/56918163/189889569-b8c48872-3517-4f21-990b-e783fcc2ce07.png)

**Comment by miadibe** [comment]
### Measurements menu typo
Highlighting objects on a federation node that would highlight multiple sub models is not functioning.

- This is happening in: prod/staging/both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- Open this model: `a link to the model`
- click on the root node of a federated tree

### Current Behaviour
- Only one of the models was highlighted.

### Expected Behaviour
- All models should be highlighted

### Pictures/ Gifs of the error
![typo (measurement)](https://user-images.githubusercontent.com/56918163/189889672-24cd4f73-788b-4763-b108-17933c16d411.png)
