### ISSUE TITLE
Improve DB delete performance

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3638]
### Description

Testing has shown that there is a significant performance hit in dropping collections with indices, the more indices the bigger the hit. The hit to drop the index prior to dropping the collection improves performance again.

### Goals
- [ ] db handler intelligently dropping indices before dropping the collection
- [ ] ability to provide index hint to the drop statement which side steps the issue.

### Tasks
- [ ] first goal probably the most flexible
- [ ] second goal nice to have / possibly ignored

### Related Resources

Mongo issue: [https://jira.mongodb.org/browse/SERVER-57221](https://jira.mongodb.org/browse/SERVER-57221)
