### ISSUE TITLE
Simplify themes in V5

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3646]
### Description
Sometimes we have very specficit targeting for applying styles in the V5 theme. I also think that there are some css targets in there which material ui already have a key for in the 

### Goals
- [ ] As a user I want to be able to read easily the v5 theme 

### Tasks
- [ ] Research for which css targets Material ui have already provided a key for
- [ ] Simplify and if possible get rid of duplicates styles.
