### ISSUE TITLE
Testing 4.28 migration script

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3647]
### Description

We are testing a large migration script, so spinning up seperate branch to avoid restarts. We'll also add an additional debug in one of the loops to ensure it's still moving.

### Goals

- [ ] branch not restarted by merges to staging
- [ ] monitor progress

### Tasks
- [ ] add additional logging
- [ ] azp run this
