### ISSUE TITLE
Custom tickets - Basic form functional prototype for custom ticket

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3650]
### Description
As a user I want to be able to show the content of a ticket 

### Goals
- [ ] As a user I want to  see the content of a ticket

### Tasks
- [ ] fetch the ticket/temlate details
- [ ] Generate a form dynamically from the ticket template
- [ ] Fill in the form using the ticekt data

**Comment by carmenfan** [comment]
closing as it's merged into #3583
