### ISSUE TITLE
V5 - Cannot tell what format a model was uploaded in

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#3652]
### Description
Currently in V5, there is no clear indication in the UI as to what file format a revision is uploaded in unless we download the revision to see the source filename. In V4, we are able to see the format within the revision information.
This was raised by the commercial team suggesting it should appear again. 

This requires #4375 for an updated endpoint.

### Goals
- As I user, I want to know which file format was the model uploaded in.

### Tasks
- [ ] Add `Format` column to the revision listing and display the file extension provided by the api
- [ ] Some aesthetic changes
  - [ ] background colour of each row
  - [ ] addition vertical strip on the left of each row
  - [ ] Void button style
  - [ ] `added by` is no longer in caps, and spacing between firstname and surname has changed
  - [ ] download icon update
  - [ ] no bold on revision code
  - [ ] new on hover behaviour (detailed in figma)

### Related Resources
Figma: https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=743%3A43993&mode=design&t=gm8B8UbEuif1hEin-1
**Currently in V4:** 
![image](https://user-images.githubusercontent.com/56918163/191726579-62f1e20e-c9e7-43c5-90ea-437d28dd3b86.png)
**Currently in V5:**
![image](https://user-images.githubusercontent.com/56918163/191726969-3cafa245-049c-495b-aec7-eb62c4fa4b9e.png)

**Comment by miadibe** [comment]
@mosment3DRepo needs triage

**Comment by george-hadfield** [comment]
[Link to design](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=743%3A43993&mode=design&t=gm8B8UbEuif1hEin-1)
