### ISSUE TITLE
Change to the custom login process

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3653]
### Description

To better support more custom logins in future, there's a change to the custom login process which requires the boot script to detect if we're running that and set up appropriate folder permissions for node to operate in the container

### Goals
- [ ] detect if we're configured for custom logins
- [ ] create and set permissions correctly.

### Tasks
- [ ] updated .azure/Docker/src/init.sh
