### ISSUE TITLE
Custom tickets - navigation in tickets card (list/details/new?)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3656]
### Description
As a user you want to be able navigate between the details of a ticket, the ticket list and the new ticket

### Goals
- [x] As a user I want to be able to navigate between the details and the ticket list

### Tasks
Try these:
- [x] Create a card context to be able to change the card content within the card content
- [x] Use the url to set the card content and just switch urls from within the card
- [x] Pass a function to change the card content (prop drilling?)
- [x] provide dummy component that would show the content of the ticket
- [x] provide dummy component that would show the new ticket form?

**Comment by carmenfan** [comment]
merged into #3608
