### ISSUE TITLE
Custom tickets - Tickets details - Save ticket changes

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3657]
### Description
As a user I want to be able to modify the content of the ticket.

### Goals
- [ ] As a user I want to be able to modify the content of the ticket.

### Tasks
- [x] Add the api bits to update the ticket
- [x] Add the saga bits to update the ticket
- [x] Create tests for testing that
- [ ] Ensure the form work as expected (validation schema)
- [ ] Whenever a user changes the value of a component update the ticket.

**Comment by sanmont3drepo** [comment]
Merged on main branch
