### ISSUE TITLE
Custom tickets - tickets api integration 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3666]
### Description
As we develop the frontend for custom tickets we need to access the data in the backend, we are missing the tickets details, templates details and insert / update ticket

### Goals
- [ ] As a developer I want to use the custom tickets api 
- [ ] As a developer I want to use the custom tickets template api 

### Tasks
- [ ] Add fetch ticket details api
- [ ] Add the update ticket api
- [ ] Add the insert ticket api
- [ ] Add fetch template details api
