### ISSUE TITLE
GitHub Actions - auto change status of issue if there's an update on the PR

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3672]
### Description
Add github action to change the status of an issue base on the status of the PR

### Goals
- [x]  if someone has been assigned a reviewer -> change issue status to "awaiting approval"
- [x]  if someone has came back with change requests -> change issue status to "address feedback"
- [x]  if it has been merged in, change issue status to "done"

### Tasks
- [x] review if we can do this in onPRReviews.yml
- [x] identify issue updating component in github actions
- [x] add the three tasks

**Comment by keifgwinn** [comment]
If someone has come back with change requests

<img width="1876" alt="image" src="https://user-images.githubusercontent.com/23369849/194536082-ed936bd4-a9e3-4f08-9b9e-98e0ecb8a9f4.png">

**Comment by keifgwinn** [comment]
If someone has merged in, set to done - I don't think this meets the requirement as it's not on merge it's just approved.

<img width="1891" alt="image" src="https://user-images.githubusercontent.com/23369849/194536227-87d654fb-c3ef-477d-81e8-ed8f1b241bf6.png">
