### ISSUE TITLE
GitHub Action - auto assign depicted teams for reviews when a PR is created

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3673]
### Description

GitHub Action (or CODEOWNERS) to auto assign depicted teams for reviews when a PR is created (if feature, include product team)

### Goals
- [ ] Sensible automatic assignment based on the area of the codebase being modified.

### Tasks

- [ ] Internal discussion to capture teams interests
- [ ] Test CODEOWNERS vs Action
- [ ] Build it

**Comment by carmenfan** [comment]
@keifgwinn  not sure if CODEOWNERS would be useful tagging the product team would be dependant on whether the `feature` label tag is on the issue.

By all means have a look, but I think you'd most likely want github action here.


Just to be clear:
- Automatically tag `3drepo/webdev` on all new PRs (You could use CODEOWNERS here and create sub teams for front/backend dev if you really want)
- Automatically tag `3drepo/product-team`  if `feature` label is on the associated issue

**Comment by carmenfan** [comment]
another thing to add: can we change the associated issue to "QA" for `feature progress` when a PR is created?

This is a field inside the project
![image](https://user-images.githubusercontent.com/11945337/195642903-4efde217-832e-4d76-a412-6ac48beae113.png)

**Comment by carmenfan** [comment]
Another another thing:

Can we take the sprint property of the associated issue and copy it to the PR

i.e. a PR for a `graphics` issue should also be categorised under `graphics` 
![image](https://user-images.githubusercontent.com/11945337/195643336-ca65179e-f738-4d64-af98-c3c9c0a60a03.png)
