### ISSUE TITLE
GitHub Actions - when a dev release is tagged, automate clean up and release notes

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3674]
### Description

When a dev tag is pushed, check the issues tagged 'in staging' and add them to a new milestone of the tag, close all the issues added to the milestone. Create a dev release with release notes.

### Goals

- [ ] new action on tagging
- [ ] check tag is dev semver
- [ ] create dev milestone
- [ ] add all issues tagged 'in staging' to milestone
- [ ] close all issues marked 'in staging' 

### Tasks

- [ ] look up github tag actions
- [ ] look up github milestone actions
- [ ] look up github issue actions
- [ ] put it all together

**Comment by carmenfan** [comment]
Just a clarification (probably obvious, but just incase)
>  check the issues tagged 'in staging'

check all **open** issues that are tagged `in staging`  - as you'll find closed issues labelled as in staging too and we wouldn't want to change their milestones :)
