### ISSUE TITLE
Custom tickets - New ticket - Functional

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3682]
### Description
We need to a way to create new tickets . This first approach (without everything in the design) should provide a way to select a template, create a ticket form with that and be able to save it 

### Goals
- [ ] Create a custom ticket

### Tasks
- [x] Add a select box with the list of templates in the ticket list
- [x] Add a new ticket button in the ticket list
- [x] Create a new ticket card that will render a template form based on the template previously selected in the ticket's list
- [ ] Create the schema based on the properties definition and the template modules
- [ ] Add a save button in the create new ticket card, when the form is valid, save the ticket

### Notes
- Do not implement the ui design as it is in the link this is a guide of the flow only 
- For an example of the validator of a property you can take a look at this 
https://github.com/3drepo/3drepo.io/blob/ISSUE_3657/frontend/src/v5/store/tickets/tickets.helpers.ts#L27

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=789%3A5282)

**Comment by sanmont3drepo** [comment]
Merged in main branch
