### ISSUE TITLE
Merge all login records into a single collection

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3694]
As part of the effort to reduce the amount of namespaces being used within the database, we will store loginRecords of all users within a single collection.

This collection will be called `loginRecords` and will live inside a new `internal` database, where notifications and other things like that will be stored

**Task**
- [x] Write a migration script to move all existing loginRecords into this setup
- [x] Add index to username and timestamp for fast retrieval
- [x] Alter codebase to write into this collection
- [x] Ensure all utility/reporting scripts reads data from this collection (if necessary?)
- [x] Deprecate `lastLogin` and extract this from the loginRecords instead
  - [x] rewrite failed attempts to record a failed login attempt
  - [x] create a new event for account locks triggering from loginRecords
  - [x] refactor `canLogIn` into an auth middleware
  - [x] update any references for lastLogin
