### ISSUE TITLE
Change styling of viewer controls

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3drepo.io#3695]
### Description
Changing the styling of the module controls (circles) in the viewer as well as the styling of the viewer controls.

### Tasks
- [ ] Change background colour of circles to secondary.main
- [ ] Change icon colour in circles to white
- [ ] Add select colour to circles to primary.main
- [ ] Change background of viewer controls to white
- [ ] Change icon colour of viewer controls to base.light
- [ ] Change icon select colour to viewer controls to base.main

### Related Resources
<img width="1585" alt="image" src="https://user-images.githubusercontent.com/78047794/196475762-4b5b95a0-73dd-4869-bdf7-f9339c6b4a2e.png">
