### ISSUE TITLE
Custom tickets - Details card header 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3697]
### Description
We are addresing the content of the card details in #3622 but we need to update the style for the header and add navigation between tickets

### Goals
- [ ] As a user I want to see an appropaite design in the card header for details
- [ ] As a user I want to navigate between tickets

### Tasks
- [x] Apply the header design
- [x] Add the navigation between cards

### Related Resources
[MockUp ](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=510%3A3503)
