### ISSUE TITLE
Custom tickets - Basic Image component

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3702]
### Description
For images/viewpoint we are going to use the same basic component, so it needs to be able to be composable for each particular case.

### Goals
- [ ] As a developer I want to have a component that I would be able to re-use for image/pin/viewpoints. 
- [ ] When I click "Add an Image" I get the option to either Create a Screenshot or Add an Image
- [ ]  I select "Create a Screenshot" it will take a screenshot of the Unity window (excluding all React UI) and save it as the image in the viewpoint
- [ ]  if I select "Upload Image" it will take me straight to my system file selection and allow me to select supported image types.

### Tasks
- [ ] Create an image component that suport haveing no image
- [ ] Update the image component that supports having an image
- [ ] Apply the design from figma
- [ ] Create a story in storybook for this

### Notes
For this component we want to have a list of available actions that will be taken care in each specific component (or composable so it can be reused) 
So the basic component would look like this:
```
<TicketImage src={imgSrc} onChange={handleOnchange}  title="Property Name"/>
```

For images:
```
<TicketImage src={imgSrc} onChange={handleOnchange} title="Property Name">
    <TicketImageActionList>
        <TicketImageActionListItem> <ImageEditionButton onChange={handleOnchange}/> </TicketImageActionListItem >
     <TicketImageActionList>
</TicketImage >
```

For Viewpoints:
```
<TicketImage src={imgSrc} onChange={handleOnchange}  title="Property Name">
    <TicketImageActionList>
        <TicketImageActionListItem onClick={goToViewpoint}> <CrossHairIcon> Edit image </TicketImageActionListItem >
        <TicketImageActionListItem > <ViewpointEditionButton onChange={handleOnchangeViewpoint}/></TicketImageActionListItem >
        <TicketImageActionListItem> <ImageEditionButton onChange={handleOnchangeImage}/> </TicketImageActionListItem >
     <TicketImageActionList>
</TicketImage >
```

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=732%3A7509)

**Comment by sanmont3drepo** [comment]
Issue will be addressed in #3703
