### ISSUE TITLE
Custom tickets - Image property

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3703]
### Description
Using #3702 implement the image property 

### Goals
- [ ] I want to be able to be able to see a property of type image
- [ ] I want to be able to add a property of type image
- [ ] I want to be able to change a property of type image
- [ ] I want to be able to delete a property of type image

### Tasks
- [ ] Using #3702 reflect the image property value
- [ ] Create an edit image button with a dropdown to create a screenshot/upload image/delete image
- [ ] Save changes when creating a screenshot /uploading an image
- [ ] Delete the image when clicking in delete image

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=788%3A5242)  (this is for viewpoint, but just ignore the edit viewpoint and go to viewpoint bits here)

**Comment by Amantini1997** [comment]
I may have gone a bit too far with #3702 and already implemented this

**Comment by sanmont3drepo** [comment]
Merged in main branch
