### ISSUE TITLE
Custom tickets - View property

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3705]
### Description
I want to be able to reflect the view and be able to set the view

### Goals
- [ ] As a Collaborator+ I can create a viewpoint when no viewpoint is currently available
- [ ] As a Collaborator+ I can change the viewpoint of an viewpoint which is already populated
- [ ] As a Collaborator+ if I select "Delete Viewpoint" I see a confirmation pop-up to confirm my choice
- [ ] As a Viewer+ if I select "Go to viewpoint" the Unity camera position will move to the stored position

### Tasks
- [ ] Create a button to create a viewpoint
- [ ] Use unity utils to get the current viewpoint to be able to save it
- [ ] Add button to go to a viewpoint
- [ ] Use unity utils to go to the viewpoint when clicking the go to a viewpoint button

### Notes
This is only to get view working, the design will be applied once #3703 is working

### Related Resources
[Mockup](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=520%3A9837)

**Comment by sanmont3drepo** [comment]
Merged in main branch
