### ISSUE TITLE
Custom tickets - go to a view from the ticket list

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3706]
### Description
When clicking tickets in the ticket list we want the view to position to the view (if any)  that the ticket is assigned to 

### Goals
- [ ] As a user I want to quickly see what the tickets view by clicking in the ticket and the camera positioning in that view

### Tasks
- [ ] Ensure that you have the view information in the tickets list view
- [ ] When clicking the ticket call a function in unity utils to position the camera
