### ISSUE TITLE
Custom tickets - View property with design and image managment

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3708]
### Description
Once #3705 and #3703 are done we want to have the view property complete with the image management

### Goals
- [ ] As a user I want to have a nice design in the view property
- [ ] As a user I want to be able to interact to change the image in the view
- [ ] As a Collaborator+ if I change a viewpoint the current camera details are saved and a pop-up in shown asking if I would like to save a screenshot. If I select "Save Screenshot" a screenshot of the current Unity window is taken and replaces the existing image. If I select cancel the viewpoint is set but the existing image is maintained.

### Tasks
- [ ] apply the design to the goto view button 
- [ ] apply the design to the edit viewpoint button
- [ ] make use of the edit image component and update the image in the view
- [ ] Add logic to ask for the screenshot if the user changes the viewpoint

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=732%3A7456)

**Comment by sanmont3drepo** [comment]
Closed because this will be addressed in here #3705
