### ISSUE TITLE
Custom tickets - Tickets details - Pin modules functional

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3710]
### Description
As a user of tickets I want to be able to associate a ticket with a pin and see that reflected in the viewer.

### Goals
- [ ] As a Collaborator+ I can add a pin when there is no pin currently uploaded
- [ ] As a Collaborator+ I can change the position of a pin which has already been placed
- [ ] As a Collaborator+ once I click "Add Pin" or "Change Pin Location" I will enter a _pin placement mode_. This will turn the stroke of the Pin module teal and enable the position selection tool in Unity. Once I select a position in the model it will update the location of the pin and exit _pin placement mode_.
- [ ]  As a Collaborator+ if I return to the list of tickets when I am in _pin placement mode_ it will cancel out of the mode and return back to the default model behaviour
- [ ]  As a Collaborator+ if I use the navigation arrows inside the ticket to navigate to a different ticket when I am in _pin placement mode_ it will cancel out of the mode and return back to the default model behaviour
- [ ]  As a Collaborator+ if I click the Custom Tickets bubble on the left of the page to close the Tickets card when I am in _pin placement mode_ it will cancel out of the mode and return back to the default model behaviour
- [ ]  As a Collaborator+ if I click the "X" button inside the module next to "Select new location on model" when I am in _pin placement mode_ it will cancel out of the mode and return back to the default model behaviour
- [ ] As a Collaborator+ if I select "Delete Pin" I see a confirmation pop-up to confirm my choice

### Tasks
- [ ] Render the filtered pins 
- [ ] When editing a ticket, only show that pin
- [ ] Add the add a pin feature
- [ ] Add delete a pin
- [ ] Add the change pin feature

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=646%3A6011)

**Comment by sanmont3drepo** [comment]
Merged in main branch
