### ISSUE TITLE
Custom tickets - show unset due dates and assignees in tickets list

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3721]
### Description
Right now we are showing the due dates and assignees in the ticket list only when they are set. We need to fetch the templates details and show the unset perroperties for templates that has these properties

### Goals
- [ ] As a user I want to know a first glance if a ticket should have an asignee or a due date.

### Tasks
- [ ] Fetch the templates details in the tickets list (maybe just add the fetch in the fetch templates saga)
- [ ] For tickets that are based on templates that hase due dates and asignees add the blank field.

**Comment by sanmont3drepo** [comment]
Merged in main branch
