### ISSUE TITLE
Custom tickets  - wire in set due date and assign users to tickets with issue like tickets

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3738]
### Description
With issue like tickets you can see due date and assignees in the main list of tickets. It seems to be a low hanging fruit to trigger those actions

### Goals
- [ ] As a user of tickets I want to set the due dates and assign people in the main ticket list .

### Tasks
- [ ] Add a date picker to due date that will be triggered by clicking in set due date
- [ ] Add a multiple select for the assignees and trigger that by clicking the assignees
- [ ] Save the changes

### Notes
Try not to use react hook forms as it will complicate things.

**Comment by sanmont3drepo** [comment]
Merged in main branch
