### ISSUE TITLE
custom tickets - reflect pins state in the viewer

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3739]
### Description
The pins from the custom tickets should be reflected in the viewer. When selecting a ticket the pin should show the selected feedback . Same when editing a ticket.

### Goals
- [ ] As a user I want to see the pins corresponding to the tickets in the viewer

### Tasks
- [ ] Move the ticket list filtering / status to redux
- [ ] Move the ticket selector / status to redux
- [ ] Create a pins selector to be consumed by the viewer
- [ ] Change the viewer to use the new pins

**Comment by carmenfan** [comment]
merged into main branch
