### ISSUE TITLE
Custom Ticket - Fix UI

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3760]
### Description
Ticket's UI need some fixing here and there.
These issues were first mentioned in https://github.com/3drepo/3drepo.io/pull/3608

### Tasks
- [x] Use the same empty state as we currently use for Issues but change wording to use Tickets
- [x] Use the new icon to display next to ticket title https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1624%3A13649&t=2lSOXBa8VyjskvSE-0
- [x] Title input should be focused when creating a new ticket
- [x] Clicking the title should open a ticket on first click
- [x] Decrease letter spacing in chips to match design
<img width="565" alt="200892356-03f513f4-a20b-44bc-9ad5-86e714b3d091" src="https://user-images.githubusercontent.com/43547703/201345912-69584d20-b0ae-45fd-86cb-4475a83d3b42.png">

- [x] "Unassigned" text in ticket list should be the same size as "Set due date" (10px)
- [ ] Update toast design (wating for design)
- [x] Reduce border radius on (template) chips to 5px to match design
- [x] Change chevron to new icon and use size 10
- [x] Avatars with no image should be consistent in background colour
- [x] Space out avatars and reduce the font size
> Font size change to: 10px
Change the margin to: -8px
- [x] Increase white border on avatars to 2px width
- [x] Move calendar icon to the right a few pixels to be centered above the chevron
- [x] Lack of templates should result in "new ticket" button disabled
- [x] Use new icons for properties https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1346%3A12333&t=wvnvRltwBWgTfWP4-0

**Comment by sanmont3drepo** [comment]
merged in base branch
