### ISSUE TITLE
Move all hookselectors and actiondispatchers to the same file

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3776]
### Description
Every hookselector has its own file but the actual content of the file is just one line. So I think it could be good if we just one file with all the hook selectors instead of having so many files . Same with the action dispatchers.

### Goals
- [ ] As a dev I want it to be easier to navigate files and to add hooksselectors and action dispatchers

### Tasks
- [ ] Move all hook selectors to one file 
- [ ] Move all action dispatchers to one file
