### ISSUE TITLE
clean up react hook form integration

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3777]
### Description
At the moment we are repeating code when doing react-hook-form integration. Instead of doing that, we can create just one adapter and make all the integrations to the input components in the same file.

### Goals
- [ ] As a dev I want a consistent clean way to integrate with react hook forms

### Tasks
- [ ] Create an adapter for hooking react-hook forms with the inputs components
- [ ] Move all hooked inputs to one file
