### ISSUE TITLE
Redux simplification

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3786]
### Description
Right now is a bit cumbersome to add an action to a redux file as you need to add the action function type, the action type, the reducer and a entry on an object. If the dev mistyped any of those thing the action wont work.
We can do a bit of an efffort if there's a less flakey way to do this.

### Goals
- [ ] As a dev I want to be able to add a redux action easily.

### Tasks
- [ ] Check what we have ATM
- [ ] Come up with a strategy to made it easier
