### ISSUE TITLE
Research alternatives for Webpack

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3791]
### Description
Webpack is complicated to configure and is slow (although I'm not sure if that's webpack's fault).  It would be good to take a look at other alternatives and see how the staand against webpack

### Goals
- [ ] As a dev I want a fast clean way to build the app

### Tasks
- [ ] Research Vite
- [ ] Research Parcel
- [ ] Look at other alternatives

### Tasks
I don't know if this has to do with  webpack but just to take in consideration  
- [ ] All of the scripts in `package.json` should work
