### ISSUE TITLE
Clean webpack

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3805]
### Description
The way webpack is implemented is in itself messy. Overtime, the code was changed across our codebase, but webpack was not always updated to reflect these changes. As a result, some code contained in webpack config files is not really used or not very efficient. That code should be improved where possible or deleted if no longer necessary.

### Goals
- [ ] Webpack code should be easier to read;
- [ ] Webpack should maintain the same functionality, possibly improving its speed

### Tasks
- [ ] Remove unused code;
- [ ] Refactor and clean up code where possible;
