### ISSUE TITLE
Bugs list v4.27.2

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#3808]
### Bugs
**V4 Regression**
- [x] ~~1. [Wrong link in log in/sign up form](https://github.com/3drepo/3drepo.io/issues/3808#issuecomment-1335868332)~~
- [x] [2. Settings button not working](https://github.com/3drepo/3drepo.io/issues/3808#issuecomment-1335877761) (Alessandro)
- [x] [3. Selecting object with BIM card/through BIM card opened takes measurement instead](https://github.com/3drepo/3drepo.io/issues/3808#issuecomment-1335943184) (Daniel)
- [x] [4. Sample_Project federation tree doesn't work and architectural model elements cannot be selected ](https://github.com/3drepo/3drepo.io/issues/3808#issuecomment-1337379034) (Santiago)
- [x] do not give new users toy project (carmen) 

**V5 UI**
- [x] [5. V5 Multiline Text Field scrollbars broken in Firefox](https://github.com/3drepo/3drepo.io/issues/3808#issuecomment-1337647547)  (This will not be fixed - Alessandro)
- [x] [6. Clicking 'Upload file to container' does not add the file to the uploads list](https://github.com/3drepo/3drepo.io/issues/3808#issuecomment-1337656630) (Alessandro)
- [x] [7. The error text is obscured on custom tickets properties](https://github.com/3drepo/3drepo.io/issues/3808#issuecomment-1339720476) (Daniel)
- [x] ~~[8. A required viewpoint should not require both viewpoint and screenshot](https://github.com/3drepo/3drepo.io/issues/3808#issuecomment-1339732552)~~
- [x] [9. Long property names are not truncated](https://github.com/3drepo/3drepo.io/issues/3808#issuecomment-1339774211) (Alessandro)
- [x] [10. App crashes when changing model with custom tickets open](https://github.com/3drepo/3drepo.io/issues/3808#issuecomment-1342555156) (Daniel)

**Comment by miadibe** [comment]
### 1. Wrong link in Log in/Sign up form
Support button opens Contact page and not support centre in Log in/sign up page. 

### Expected Behaviour
- Relink support button to Support Centre

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/56918163/205394019-6a2ab1e4-2157-4360-8ebe-03a5f138bff9.png)

**Comment by miadibe** [comment]
### 2. GIS - Settings button not working 
GIS Settings button does not open

###Expected Behaviour
Settings button should work and open when clicked for user to add or edit coordinates. 

###Pictures/ Gifs of the error
![ezgif com-gif-maker](https://user-images.githubusercontent.com/56918163/205396338-095d8f80-7418-4862-a019-aa8a8336df7e.gif)

**Comment by miadibe** [comment]
### 3. Selecting object with BIM card/through BIM card opened takes measurement instead
Clicking on an object after enabling the BIM card will not only highlight that object but also take measurements. 

### Steps to replicate 
1. Open any model
2. Open the BIM card
3. Select an object directly on the model **or** through the BIM card selection option
4. Click anywhere else on the model (perhaps to select another object) 

### Current behaviour
Measurements (point to point or custom polygonal area) appear, even after:
- Page refresh
- Log in/out 
- Change of model/federation
- Change of browser

### Expected behaviour 
No measurement should appear, and user should be able to select any other object 

### Pictures / GIF of the error
https://user-images.githubusercontent.com/56918163/205403454-161c4978-83c1-4944-bfbe-e86ea8135acc.mp4

**Comment by mosment3DRepo** [comment]
> ### 1. Wrong link in Log in/Sign up form
> Support button opens Contact page and not support centre in Log in/sign up page.
> 
> ### Expected Behaviour
> * Relink support button to Support Centre
> 
> ### Pictures/ Gifs of the error
> ![image](https://user-images.githubusercontent.com/56918163/205394019-6a2ab1e4-2157-4360-8ebe-03a5f138bff9.png)

Looks like this is a 3DRepo.com routing problem since it hasn't changed and the link still goes to http://3drepo.org/support/

**Comment by The-Daniel** [comment]
### 6. Clicking 'Upload file to container' does not add the file to the uploads list
On the containers dashboard using the 'Upload file' feature in either the revision list or ellipses menu doesn't work. The upload modal is opened and file select dialog is triggered, but the selected file does not appear in the list.

### Expected Behaviour
After selecting a file the upload modal appears with the file already in the uploads list

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62481250/205687714-b777a326-2c62-4b93-9930-2c037cc90032.png)
After selecting a file:
![image](https://user-images.githubusercontent.com/62481250/205687774-7b5f18bf-f066-4c49-914a-075db0bddcb6.png)

**Comment by Amantini1997** [comment]
> ### 5. V5 Multiline Text Field scrollbars broken in Firefox
> The custom scrollbars do not render in V5 multiline text fields when viewed in Firefox. The default scrollbar does not extend all the way to the bottom of the box. An example of one of these multiline text fields is the description box in a custom ticket.
> 
> ### Expected behaviour
> * The custom scrollbar works in firefox (might not actually be possible)
> * The scrollbar extends for the entire height of the text field box
> 
> ### Pictures/ Gifs of the error
> Firefox: ![image](https://user-images.githubusercontent.com/62481250/205683060-a8485306-2e9d-4c11-912a-6d284e55ef81.png) Chrome: ![image](https://user-images.githubusercontent.com/62481250/205683397-b66a4480-2927-415e-8440-7ced4dfb3034.png)

About this 

**The custom scrollbar works in firefox (might not actually be possible)**
It is indeed not possible. Firefox uses a floating scrollbar and the library cannot pick it. The team is currently working to fix it, but they haven't solve the issue yet


**The scrollbar extends for the entire height of the text field box**
This problem is not specific to Firefox. It is something that happens in Chromium as well and is due to the "resize" component. Textareas allow to be resized by dragging the bottom-right corner 
![image](https://user-images.githubusercontent.com/43547703/205908877-6aaa2d0f-db62-481f-a677-b205888f0b5b.png)

Using CSS, it is possible to prevent resizing (`resize: none`). This also hides that component, nonetheless, the scrollbar does not resize and maintains that height
![image](https://user-images.githubusercontent.com/43547703/205909057-6cdd83d2-d925-4487-9f41-57d5fe523e0f.png)

As such, I think this problem cannot be fixed right now, if not tweaking the textarea component in a bad way using CSS

May I tick that bug as complete?

**Comment by The-Daniel** [comment]
### 9.  Long property names are not truncated
Long property names can cause problems with the layout of some property components

### Expected Behaviour
Long property names should not affect the position/size of subcomponents. They should be truncated to limit the length shown

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62481250/205988067-68a06f1a-9522-46d7-acfc-ec2cc9f73f9b.png)

**Comment by sanmont3drepo** [comment]
> ### 8. A required viewpoint should not require _both_ viewpoint _and_ screenshot
> ### Current Behaviour
> A required viewpoint needs both viewpoint and an image to be set otherwise it errors.
> 
> ### Expected Behaviour
> It should be accepted as long as it has either a viewpoint _or_ an image (or both)
> 
> ### Pictures/ Gifs of the error
> ![image](https://user-images.githubusercontent.com/62481250/205980924-efc7190e-7786-4210-9c0c-ad085f6f5b7c.png)

It seems that it needs both once they are set. The backend will throw an error if you try to delete a viewpoint and send the screenshot.

**Comment by The-Daniel** [comment]
### 10. App crashes when changing model with custom tickets open

There is a redux state that stores the current ticket ID. This is not reset when changing model, so when you open custom tickets after changing model it tries to search for a ticket that doesn't exist on that model.

### Steps to replicate
- open a model
- open custom tickets
- enter ticket details for a ticket
- Change model (i.e. using the breadcrumb dropdown)
- Open up custom tickets
