### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3822]
### Tasks
- [ ]  Arrows on custom ticket detail are way too big

Build
<img width="397" alt="image" src="https://user-images.githubusercontent.com/78047794/207093640-b3432de3-3372-4aed-b5ed-2fa67aa2554b.png">

Design
<img width="469" alt="image" src="https://user-images.githubusercontent.com/78047794/207093756-6fb0ac61-41a3-425d-934f-256f6a648d4a.png">

- [ ] Missing Safetibase icon inside Safetibase cards

<img width="403" alt="image" src="https://user-images.githubusercontent.com/78047794/207094368-c9537f8c-4f63-4d8b-9fb1-31fd34e83f1c.png">

- [ ] Gaps between action buttons at the top of cards

<img width="155" alt="image" src="https://user-images.githubusercontent.com/78047794/207094646-13e43fdc-48e7-4449-bbd5-7a1c032bf36e.png">

- [ ]  Instant clash tab on compare tab should be on a single line

Build
<img width="391" alt="image" src="https://user-images.githubusercontent.com/78047794/207098452-cf97d39f-4672-47f1-8086-5972bba9d166.png">
