### ISSUE TITLE
Text being cutoff (missing ellipsis)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3827]
### Tasks
- [x]  Fix group names truncated but can overflow when nested
![image](https://user-images.githubusercontent.com/62481250/207037720-8d4e4298-5079-46a9-b61a-6dc6b6c4a385.png)
- [x] Edit profile modal 
![image](https://user-images.githubusercontent.com/43547703/207819360-47ed0131-97ab-4203-952e-5cbd738bbd14.png)
- [x] dashboard list item (includes edit federation)
![image](https://user-images.githubusercontent.com/43547703/207819598-594e1de2-6000-4369-8ed6-a189c61b4607.png)
- [x] Expanded container list item
![image](https://user-images.githubusercontent.com/43547703/207819937-2efeaed9-6476-44e1-b343-0021208f4b12.png)
- [x] Breadcrumbs trims only the last segment, which might be fine, but this means that the other segments break the line
![image](https://user-images.githubusercontent.com/43547703/207822211-c05293c8-f855-4bce-a408-85f5a460c701.png)
> Also, the overflowing may look pretty bad if that happens 
![image](https://user-images.githubusercontent.com/43547703/207823706-f37cef64-3793-4e9a-a7bd-73d74fdaf974.png)

- [x] Safetibase editable title 
![image](https://user-images.githubusercontent.com/43547703/207822865-85e05177-0869-4955-97a6-438b10b70778.png)
- [x] Compare Card 
![image](https://user-images.githubusercontent.com/43547703/207823268-713506ca-dd89-405b-8fc1-19cc62c00630.png)
- [ ] <del>Sequences (although we haven't really tackled this card yet)</del>
![image](https://user-images.githubusercontent.com/43547703/207823372-77398793-6fd1-4773-ada7-feb983af35a3.png)
- [x] Ticket title)
![image](https://user-images.githubusercontent.com/62481250/211305425-764b241d-9516-4c62-8c74-f7a4ba8306f4.png)
- [x] Latest Revision Title
![image](https://user-images.githubusercontent.com/62481250/211307176-5a9a05c6-dc18-4806-ad8b-c5b7a0cc4b2d.png)

**Comment by Amantini1997** [comment]
> Sequences (although we haven't really tackled this card yet)
![image](https://user-images.githubusercontent.com/43547703/207823372-77398793-6fd1-4773-ada7-feb983af35a3.png)

This is being tackled as part of #3690
