### ISSUE TITLE
Update nodejs to 18.12.1 LTS

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#3834]
### Description
Update nodejs to latest [18.12.1 LTS](https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.xz)

### Tasks
- [x] Update .io
- [x] Update GitHub Actions
- [x] Update Travis CI
- [x] Update containers https://github.com/3drepo/DevOps/issues/504
- [x] Update local https://github.com/3drepo/local/issues/64

**Comment by Charence** [comment]
After updating to nodejs 18.x.x. LTS, `yarn install` completes but `yarn test:v5` doesn't work.

`yarn test:v5` problem:
```
    Something went wrong installing the "sharp" module

    Cannot find module '../build/Release/sharp-linux-x64.node' from 'node_modules/sharp/lib/sharp.js'

    Possible solutions:
    - Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
    - Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
    - Consult the installation documentation: https://sharp.pixelplumbing.com/install

      19 | const _ = require("lodash");
      20 | const fs = require("fs").promises;
    > 21 | const sharp = require("sharp");
         |               ^
```

Running `npm install --ignore-scripts=false --verbose sharp` yields the following which seems to be related to https://github.com/3drepo/3drepo.io/issues/3441:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: connect-mongo@4.6.0
npm ERR! Found: mongodb@3.6.12
npm ERR! node_modules/mongodb
npm ERR!   peer mongodb@"3.x.x" from @shelf/jest-mongodb@2.0.1
npm ERR!   node_modules/@shelf/jest-mongodb
npm ERR!     dev @shelf/jest-mongodb@"2.0.1" from the root project
npm ERR!   mongodb@"3.6.12" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer mongodb@"^4.1.0" from connect-mongo@4.6.0
npm ERR! node_modules/connect-mongo
npm ERR!   connect-mongo@"4.6.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: mongodb@4.13.0
npm ERR! node_modules/mongodb
npm ERR!   peer mongodb@"^4.1.0" from connect-mongo@4.6.0
npm ERR!   node_modules/connect-mongo
npm ERR!     connect-mongo@"4.6.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by Charence** [comment]
Running sharp install with `--legacy-peer-deps` completes but doesn't seem to fix `yarn test:v5` problem:

![Screenshot from 2022-12-22 10-28-59](https://user-images.githubusercontent.com/1438332/209115059-21456aba-f5de-4bc6-bb47-b187fc4d2f90.png)

![Screenshot from 2022-12-22 10-29-10](https://user-images.githubusercontent.com/1438332/209115094-f6620e91-7eaf-4be3-be3f-e627a8682580.png)

**Comment by Charence** [comment]
Note: AAD unit and e2e tests seem to failing inconsistently.

- Unit test seems to pass most of the time, but sometimes will have 3 failures like this: https://github.com/3drepo/3drepo.io/actions/runs/3757158743/jobs/6384056098
- E2E test seems to fail most of the time, but with 2-3 failures like this: https://github.com/3drepo/3drepo.io/actions/runs/3757285923/jobs/6384319361
