### ISSUE TITLE
Chat notifications: Comments

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3859]
### Description
We need to add chat notifications when there is a new comment or a modifcation to a comment

#### New Comment (Container)
- Event name: `containerNewTicketComment`
- scope: Container/Federation event
- data: 
````
{  
  teamspace: "teamspace name", 
  project: "project id", 
  model: "container id", 
  data: { 
    ticket: "ticketId",
    _id: "commentId",
    comment: string,
    images: [string],
    author: string,
    createdAt number, //epoch timestamp 
  }
}
````

#### New Comment (federation)
- Event name: `federationNewTicketComment`
- scope: Federation event
- data: 
````
{  
  teamspace: "teamspace name", 
  project: "project id", 
  model: "federation id", 
  data: { 
    ticket: "ticketId",
    _id: "commentId",
    comment: string,
    images: [string],
    author: string,
    createdAt number, //epoch timestamp 
  }
}
````

#### Update Comment (Container)
- Event name: `containerUpdateTicketComment`
- scope: Container/Federation event
- data: 
````
{  
  teamspace: "teamspace name", 
  project: "project id", 
  model: "container id", 
  data: { 
    ticket: "ticketId",
    _id: "commentId",
    comment: string,
    images: [string],
    author: string,
    updatedAt: number, //epoch timestamp 
  }
}

// or

{  
  teamspace: "teamspace name", 
  project: "project id", 
  model: "container id", 
  data: { 
    ticket: "ticketId",
    _id: "commentId",
    deleted: true,
    updatedAt: number, //epoch timestamp 
  }
}
````

#### Update Comment (Federation)
- Event name: `federationUpdateTicketComment`
- scope: Container/Federation event
- data: 
````
{  
  teamspace: "teamspace name", 
  project: "project id", 
  model: "federation id", 
  data: { 
    ticket: "ticketId",
    _id: "commentId",
    comment: string,
    images: [string],
    author: string,
    updatedAt: number, //epoch timestamp 
  }
}

// or

{  
  teamspace: "teamspace name", 
  project: "project id", 
  model: "federation id", 
  data: { 
    ticket: "ticketId",
    _id: "commentId",
    deleted: true,
    updatedAt: number, //epoch timestamp 
  }
}
````

### Goals
- [ ] A chat message should be triggered if:
  - [ ] a user created a comment
  - [ ] a user updated their comment
  - [ ] a user deleted their comment
- [ ] chat notification documentation should also be updated 

### Tasks
TBC
