### ISSUE TITLE
Refactor upload form 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3877]
### Description
The code for upload form is too complex. In particular it's use of react-hook-forms.

### Suggested solution
- [ ] Test if not using react-hook-forms here would improve the code
- [ ] Test if there's another way of using react-hook-forms 
- [ ] Refactor side form component to think about it more like an input (same concept as in the custom tickets pin and image components)

### Goal
- [ ] Have more readable components
- [ ] If possible decrease the codebase

### Tasks
- [ ] Refactor the uploadFileForm
- [ ] Refactor uploadListComponent
- [ ] Refactor sidebarComponent

**Comment by sanmont3drepo** [comment]
duplicated issue #4047
