### ISSUE TITLE
Replace embeded dialog forms and use dialog dispatchers to have a more uniform way of using dialogs

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3878]
### Description
We are using two different ways for formdialogs. One is using an action and the other one is embedding the form dialog in the component that dispatches it. Over time we noticed that using just the dispatcher should cater for every case, providing a standard way of using dialogs.

### Suggested solution
Use dispatch dialogs. Ideally it shouldn't  decrease the readability of the code, each form dialog should be tackled on a case-by-case basis to guarantee that.

### Goal
- [ ] There's only one way of dispatching dialog forms.

### Tasks
- [ ] Take a look at each particular form dialog
- [ ] Replace the open/close logic on the component that dispatches the dialog to a DispatchDialog call
