### ISSUE TITLE
Split FormModal into many 

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3882]
### Description
At the moment, we have just one `FormModal` that is being used as a standard template.
To modify it (in particular, to adjust the Action Bar) the component accepts a lot of props.
It could be the case that having more than 1 modal could improve the readibility and the cleanliness of the code

### Goals
- [ ] Make the form modal easier to use and more readible;
- [ ] Reduce the number of props that the modal needs to handle

### Tasks
- [ ] Split the FormModal into a few modals. On top of my had I can think of a modal with no buttons (e.g. Share modal), one with canecl button only, and one with both a confirm and a cancel button
