### ISSUE TITLE
Create a simple SSO demo page

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3895]
### Description
Create a simple static html page to demonstrate how the backend API works for SSO.

### Goals
- [x] Front end developers will be able to look at the example page to understand how to implement the logic to interact with the SSO apis

### Tasks
- [x] Create sample journeys for:
  - [x] login
  - [x] sign up
  - [x] link
  - [x] unlink
- [x] Change redirect to just returning a link to microsoft to avoid CORS problem
