### ISSUE TITLE
SSO Sign-up Page

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3904]
### Description
Updated sign-up page to allow for log in with Microsoft SSO credentials.  In the main signup page there should be a link to sign up with Microsoft.
The steps are 
- Main signup page link to microsoft signup. [here](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1624%3A13680&t=X24Sdk65JXqdTBqA-0)
- Then fill in the  necessary data (username/company/country) [here](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1624%3A13822&t=X24Sdk65JXqdTBqA-0)
- After accepting terms and conditions [here](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1083%3A10009&t=X24Sdk65JXqdTBqA-0) redirect to the microsoft sso page [here](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1083%3A10059&t=X24Sdk65JXqdTBqA-0)
- If the user with sso already has an account redirect [here](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1624%3A14079&t=X24Sdk65JXqdTBqA-0)

### Goals
- [x] As a user I want to sign up using microsoft single sign on
- [x] As a user if I cancel the microsoft authentication I expect to be returned to the login page
- [x] As a user I need to populate some 3D Repo specific fields (eg. username) before I am prompted for the microsoft authentication
- [x] As a user I must accept the terms and conditions before my account is created

### Tasks
- [x] Add link for microsoft sso in main signup page
- [x] Add a route for the minimum necessary data form
- [x] Add the component for the min data form
- [x] Add a route when there were already an account  in 3drepo with SSO
- [x] Add the component for showing the message that the user has already a SSO account
- [x] Apply new design

### Related Resources
[Link to design](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1597%3A14060&t=aIZ6uRFkJnXtuwsP-1)

**Comment by george-hadfield** [comment]
[Link to design](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1597%3A14060&t=aIZ6uRFkJnXtuwsP-1)
