### ISSUE TITLE
V5 Jobs List (Facelift)

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3920]
### Description

In order to get a functional version of V5 up and running we must have a means to add and edit jobs.

### Goals

- [x] Replicate the functionality of https://www.3drepo.io/dashboard/user-management/{teamspace}/jobs
- [x] Allow admins to create new jobs
- [x] Allow admins to remove existing jobs
- [x] Prevent admins from removing an already assigned job
- [x] Allow admins to change the colour assigned to a job

### Related Resources
https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2128%3A27000&t=allLkjWNPPcVynts-0
