### ISSUE TITLE
Custom Tickets: Groups

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3933]
### Description
Add  full `state` support in views on 3drepo.io UI. When we display a custom ticket view, it should reset the object status on the viewer and apply what is saved inside the state object.

#### Data schema
See #3969 for the full schema of this object:
- `showDefaultHidden`: a boolean that depicts if hidden by default objects should be shown. This essentially affects if the `Show hidden geometry` option inside the tree: 
![image](https://user-images.githubusercontent.com/11945337/229100746-fdc27a88-4bba-4232-ae1a-71a2cb27c8ff.png)
- `colored`: specifies a list of groups that needs to have colour override applied (Note: it is possible where a single object is coloured by multiple groups - in that situation apply the same logic as v4 groups: apply the last applied override, if that is removed, apply the 2nd from last applied override). Unlike v4, it is possible to only apply a transparency override without applying a colour
- `hidden`: specifies a list of groups that needs to be hidden 
- `transformed`: This is a hidden list of groups (not shown to the UI) that specifies the list of objects with a 4x4 matrix that it is being applied. This is very specific to views saved when viewing a 4D Sequence and the user can only `edit` this by snapshotting the current view.

##### Prefix
The `prefix` specifies the hierachy of the group. This is a proper support of Group of groups in v4. e.g. in V4 you would define a hierachy of `Level 1` > `Kitchen` onto a group by prefixing the group name with `Level 1:: Kitchen`. In this implementation you should leave the group name as it is, and provide a prefix value of `["Level 1", "Kitchen"]`

##### View property
- The view property card has been updated to facilitate the groups support.
- Clicking on to the `groups` button will now lead you to the new groups UI

##### Groups list UI
- Groups should be collapsed by default
- When entering the groups card, we should reset the view to the selected view again to ensure the states are in sync
- Coloured groups:
  - Colour override should be on by default (i.e. check box ticked)
  - Colour override status is a temporary thing and does not get saved to the view - if the user wishes to no longer colour override a certain group they should just remove the group from the list.
  - Smart group should have a different icon to manual group, and the colour of the icon should match the colour/transparency override of that group (e.g. just like v4 groups)
  - Clicking on that group should highlight the objects in the specified colour (or default if only opacity is overriden)
  - Opacity cannot be set to 0 - they should be using hidden groups instead.
- Hidden groups
  - clicking on a group should unhide the group and highlight it with the default colour
  - The user can also show/hide the object by toggling the show/hide icon
    - This is a temporary viewer state that is not saved into the view - if the user wishes to show a certain hidden group, they should just remove the group
- Deleting a collection of groups should delete all groups within that collection 

##### Group edit/new view
- Smart group should be the default option
- Colour picker should only be available for coloured groups edit
- You can only save a group if it is a manual group with at least 1 object, or a smart group with at least 1 filter

### Goals
- [ ] As a ticket creator/editor (everyone but viewer):
  - [ ] I should be able to "snapshot" my current view into a saved view by a simple click of a button. It should preserve my camera settings, clipping planes and object states (hidden, colour override, transforms). Any highlighted objects should be grouped together by their highlighted colours
  - [ ] I should be able to specify what the view's state should be by creating groups (smart or manual), declaring them to be overridden by certain colour and/or opacity, or whether they should be hidden
  - [ ] I should NOT be able to declare a transformed group - these should only be possible by snapshotting my current view
  - [ ] I should be able to edit the group listings without affecting my camera/clipping point positions
  - [ ] I should be able to edit the group hierachy to introduce group collections the group should be under
  - [ ] I should be able to update the rules/objects of a group without changing anything else on the view
  - [ ] I should be able to delete the states without deleting the rest of the view
  - [ ] I should be able to delete the whole view - which would delete the states

- [ ] As a ticket viewer
  - [ ] When I'm being shown the viewpoint (e.g. clicking on it on the ticket list, entering the ticket, clicking on the show viewpoint option), it should reset my current object states and show me the object states that the view was saved with
  - [ ] I should be able to interact with the groups:
    - [ ] clicking on a colour overridden group should highlight the group with that colour
    - [ ] toggling the check box on a colour overridden group should toggle on/off colour override of that group
    - [ ] clicking on a hidden group should show the group and highlight the objects in default colour
    - [ ] I should be able to toggle the hidden group on or off
    - [ ] I should NOT be able to interact with hidden groups

<details> <summary> Original user journeys (outdated) </summary>

- [ ] As an admin I want to be able to add a groups module to a custom ticket template
- [ ] As a user I want to ignore any preexisting colour overrides in the 3D view when creating a custom ticket viewpoint
- [ ] As a user I want to automatically apply all the group colour overrides in order for a custom ticket when I enter the ticket details panel
- [ ] As a user I want all existing colour overrides to be removed when I open a custom ticket so that any groups within that ticket are applied exclusively
- [ ] As a user I want to changes to groups to be included in the activity log
- [ ] As a user I do not want all the groups to load when I load the model so that the initial loading time is shorter
- [ ] As a user I want to be able to create smart groups using multiple rule sets
- [ ] As a user I want to be able to create normal group using the selection method in v4
- [ ] As a user I want smart groups to be the default
- [ ] As a user I want to be able to edit the colour of the group and have the model update immediately with the new colours
- [ ] As a user I want the groups to stay active even after I have left the custom ticket details page
- [ ] As a user I want to be able to display a hierarchy of groups in the same way as v4
- [ ] As a user I want to be able to isolate the objects within a group or group collection
- [ ] As a user I want to be able to edit a group name
- [ ] As a user I want to be able to set a group opacity without a colour override so that all objects in that group retain their source colours
- [ ] As a user I want to be able to see the number of object included in a group
- [ ] As a user I want the number of objects in the group to update every time I make changes to the group
- [ ] As a user I want to see the number of groups displayed in the "Groups" accordion header
- [ ] As a user I would like to be able to use regular expressions on the field name as well as the value so that I be more flexible with my groups
- [ ] As a user I would like to have the count of objects to be included in the API response so that it is easier to display totals in external applications such as PowerBI (due to the complexity of the tree calculation)

</details>

### Related Resources
[Design](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3251-29959&t=UIQkeOgJ6s8RRcSO-0)

**Comment by mosment3DRepo** [comment]
@carmenfan @sanmont3drepo 

Ready for a brief lookover

**Comment by george-hadfield** [comment]
@carmenfan and @sanmont3drepo please see the link below for an updated groups design 

https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=2628%3A17653&t=Helfz5T9CzeLHgIR-1

If you could have a quick scan ahead of our call at 4pm and if you have any comments, feel free to leave them on Figma beforehand and I can tackle them before the meeting.

**Comment by george-hadfield** [comment]
@sanmont3drepo here's the link to the prototype for Groups that I presented on Friday. You can navigate using left/right keys or by clicking around.

**Prototype**
https://www.figma.com/proto/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?page-id=2628%3A17653&node-id=3251%3A30667&viewport=-7593%2C-1147%2C0.25&scaling=min-zoom&starting-point-node-id=3251%3A29959

**Figma design**
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=2628%3A17653&t=arbHQLSrxS8beu3c-1

@carmenfan said if you're happy to approve we can move this out of design and into dev.

**Comment by carmenfan** [comment]
UI changes needed:
- [ ] We're missing the updated view property UI
- [ ] Hidden groups should not have a check box - it should have a visibility toggle
- [ ] Number of groups on the hidden/coloured header should match the number of groups displayed
- [ ] Group edit card - `Add group to collection` should have a default option of `None` instead of `Please select`
