### ISSUE TITLE
Store all views in a single collection

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3968]
### Description
As part of the effort to reduce namespace, we are going to merge all views within a single teamspace into a single collection

At the moment, views are stored in `<model id>.views` of the user's teamspace

We want to create a `views` collection where all views from all models will be stored into the same collection, adding the `teamspace`, `project` and `model id` into the bson documents, similar to how we store custom tickets.

We should also ensure that the documents can be queried efficiently, i.e. index by teamspace > project > model Id > _id

We want to make sure that queries will run efficiently

### Goals
- [ ] All data should be migrated to `views` collection
- [ ] all functionality should function as before
- [ ] ensure queries will run efficiently

### Tasks
- [ ] Create a migration script to move all existing data into the new collection, and index the collection
- [ ] Create the view collection and index the collection at the point of initialising any future teamspaces
- [ ] Ensure the following functionality are reading/writing from the right place:
  - [ ] Create a view
  - [ ] Delete a view
  - [ ] Get view(s)
  - [ ] Deleting views triggered by deleting a model

**Comment by Charence** [comment]
@carmenfan We want to merge `<model_id>.views.ref` to `views.ref` too, right?

**Comment by carmenfan** [comment]
> @carmenfan We want to merge `<model_id>.views.ref` to `views.ref` too, right?

yes

**Comment by carmenfan** [comment]
severely out of date, we need to revisit and probably solve a lot of conflicts!
