### ISSUE TITLE
Custom tickets: Groups (endpoints)

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3969]
## Description
We want to add support of groups in custom tickets. For this version, we will only support groups within viewpoints.

Viewpoints will only support 2 types of  **(TBC: do we need to support transformed groups?)**: 
- color override
- hidden objects

**TBC: how to support group of groups**

Groups will be stored as data belonging to a ticket, therefore users will not be able to update a different ticket with an existing group from another ticket.

#### Groups schema
Groups will be stored inside `tickets.groups` collection

````js
{
  _id: UUID,
  teamspace: "teamspace name",
  project: UUID,
  modelId: "modelID",
   name: "Group name",
description: "Description of the group",
  rules: [/* see existing rules schema */], // can only have rules or objects, not both
  objects: [
    { container: "container id", _ids: [] } // or ifc guids
   ]
}
````

#### Group Schema (within the ticket)
````js
{
  /* ... */
  "Default View": {
      state: {
        showDefaultHidden: bool,
        colored: [
           // color and opacity are optional, only one of them needs to exist. Opacity cannot be 0
           // prefix depicts the section hierachy in the group list
           { prefix: ["section 1", "section 2"] , color: [0,0,0], opacity: 0.5, group: UUID}
        ],
        hidden: [ 
            // no prefix depicts it's a root level group
            { group: UUID  },
            {prefix: ["Floor 1"], group: UUID  }
         ],
        transformed: [
           { prefix: ["section 1", "section 2"] , transformation: [/*...*/], group: UUID}
        ]
      },
      camera: { /*...*/},
      image: /*...*/
   }
}
````

#### Creating a group
There is no new endpoint to create a group as it only exists within a ticket. like v4, the users should create the viewpoint with the group content, and the backend will create the group internally and returns a group id (a bit like image references)

eg:
````js
//when updating or creating a ticket
{
  "View Name": {
     state: {
       // Keep using UUID to reference existing groups. You can even reference groups from different state arrays (i.e. move a colour override group to hidden
       hidden: [ {group: UUID}, {group: UUID}, {prefix: ["a", "b"], group:  {
         name: "A new group to be hidden",
         rules: [/* see existing rules schema */],
        }}]
     }
   }
}
````

#### Editing a group
route `HTTP PATCH /teamspaces/:teamspace/projects/:project/:type/:model/tickets/:ticket/groups/:group`
payload:
````js
// only include fields that requires updating
{
  name: "New group name",
}
````

#### Getting group details
route `HTTP GET /teamspaces/:teamspace/projects/:project/:type/:model/tickets/:ticket/groups/:group`

returns group details similar to v4.

#### Deleting a group
There is no endpoint to delete a group. the user can "delete" a group by removing it from one of the state arrays. Groups will be automatically removed if they are no longer referenced

## Goals
- [x] The user should be able to include hidden and colored groups within views
- [x] The system log should should record a log if:
  - [x] groups array has been updated
  - [x] group details itself has been updated

## Tasks
- [x] Update schema to define groups
- [x] add model for db schema:
  - [x] ability to add a group
  - [x] ability to edit a group
  - [x] ability to remove a group
  - [x] ability to find a group by id
- [x] Add processor logic:
  - [x] convert group content to a UUID of the saved group
- [x] add changes to middleware to cast in/out the UUIDs
  - [x] in
  - [x] out
- [x] Ensure events are triggering correctly and history of group changes are recorded
  - [x] ticket level changes
  - [x] group details changes
- [x] add endpoints to
  - [x] edit groups
  - [x] get groups
- [x] Update swagger doc
- [x] Add description to group details

## clean ups
- [ ] Introduce constants to rules labels
- [x] use constants for state group names
- [x] document group update event
