### ISSUE TITLE
Improve performance on tickets comments

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4041]
### Description
When the list is too long the performance can drop, we need to research a solution for improving that

### Suggested solution
Research if we can virtualized the list or use memoization

### Goal
- [ ] Have a good performance with comments

### Tasks
- [ ] Research virtutalizatitoin options
- [ ] Research memoization options
- [ ] Apply the solution that works (oor both)
