### ISSUE TITLE
V5 viewer dev redesign

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4060]
### Description
In order to have a more stable product, easily updateable product we need to have a more thoughtout viewer design. It also would use v5 tech and fully localizable.

### Goals
- [ ] To have a more robust viewer design

### Tasks
- [ ] Make a list of conflicting issues with the current product
- [ ] Make a list of things that we like how works right now
- [ ] Make a list of things that we can improve
- [ ] Provide a basic design (as a prototype or as a diagram) with the ideas applied
