### ISSUE TITLE
Custom Ticket Loading States

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4073]
### Description
We need to add loading states to custom tickets. Some sections take longer to load than others, and there is no indication that the component has finished loading.

### Goals

- [ ] As a user I want to know whether the information has finished being fetched
- [ ] As a user I don't want to be accidentally click the wrong element due to components unexpectedly being rendered
- [ ] As a user I don't want to be misled into thinking data doesn't exist just because it hasn't loaded yet

### Tasks

- [ ] Add a loading state for the tickets list
- [ ] Add loading states for ticket details
- [ ] Fix the styling in the create ticket loading spinner

### Related Resources

There is currently an underutilised SpinnerLoader component in `@controls` perhaps this could be used?

The ticket list appears to show that you have no tickets before being fully loaded:
![loadingstate1](https://user-images.githubusercontent.com/62481250/224296147-b6280cf8-44bb-410b-b56a-e9e61c501017.png)

Upon opening ticket details it appears that there are no modules. Also some of the issue properties load in before others. This can cause the user to try to click one element (e.g. assignees) and end up clicking something else (e.g. the default view) as it loads
![loadingstate3](https://user-images.githubusercontent.com/62481250/224296073-6857ebf7-9035-45a7-8dfd-6da3af1ced73.png)

There _is_ a loading spinner when opening the new ticket screen but it is not centred
![image](https://user-images.githubusercontent.com/62481250/224297161-ab8d4313-0765-4bc4-9469-b9fd0b63e907.png)

MockUp : `link to mockup`

**Comment by AsiteZane** [comment]
Agreed, need a UI/UX mockup on how best to demonstrate this.

**Comment by AsiteZane** [comment]
https://github.com/3drepo/3drepo.io/issues/2285 should be considered here - if applicable. Only make it relevant to Custom Tickets. Issues and Risks do not need to be considered.
