### ISSUE TITLE
Refactor edit profile

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4077]
### Description
There are some props being passed around that wouldnt be necessary if we'd lean a bit more on react-hook-forms.

### Suggested solution
Try to get rid of the extra props being passed around for cleaner code.

### Goal
- [ ] have a more readable /maintanable code.

### Tasks
- [ ] Work on get rid of the  extra props being passed around
- [ ] Use the submit handler from rhf with a promise to let it handle the submitting status by itself
- [ ] See if having just onw form in edit profile with the schema dynamically changing would benefit the code
