### ISSUE TITLE
Review selectors

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4090]
### Description
Selectors might be recalculating more times than necessary, triggering unnecessary redraws

### Suggested solution
Check in the selectors, file by file if they are not being recalculated unecessary  

### Goal
- [ ] Have better performance

### Tasks
- [ ] Research in the internet is there's a way of debugging the perfomance of selectors 
- [ ] Console log the selectors?
