### ISSUE TITLE
Profile page bugs

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4099]
- [x] [Avatar reverts back to the old one upon save](https://github.com/3drepo/3drepo.io/issues/4099#issuecomment-1471811700)
- [x] [When you try to update the avatar with an image that is too big, it should not update the image](https://github.com/3drepo/3drepo.io/issues/4099#issuecomment-1471816112)
- [x] [email validation can be bypassed](https://github.com/3drepo/3drepo.io/issues/4099#issuecomment-1471854280)
- [x] [Update prompt needs to be shown on top](https://github.com/3drepo/3drepo.io/issues/4099#issuecomment-1471858598)

**Comment by carmenfan** [comment]
### Description
When a user updates their avatar, the image goes back to the old one upon save. Refreshing the page will update the avatar to the latest one

### Steps to replicate
- Update the avatar image
- click `update profile`

### Current Behaviour
The image goes back to the old one upon save

### Expected Behaviour
The image should stay as the newest one

### Pictures/ Gifs of the error
![img](https://user-images.githubusercontent.com/11945337/225606449-2eb66080-1437-4578-a04a-30535647351a.gif)

**Comment by carmenfan** [comment]
### Description
When you try to update the avatar with an image that is too big, it should not update the image

### Steps to replicate
Update avatar with this image: https://www.dropbox.com/s/l4cvetv6ly01w2j/bigPicture.jpg?dl=0

### Current Behaviour
We see the error message, but the avatar is still updated

### Expected Behaviour
We should not see the invalid avatar

### Pictures/ Gifs of the error
![img](https://user-images.githubusercontent.com/11945337/225608913-15a0f026-1f5e-45b6-ba32-fcc372977663.gif)

**Comment by carmenfan** [comment]
**Email validation can be bypassed**

It seems like the email validation breaks down if you try to update the email with an already taken email.

#### Steps to replicate
1. try to update email with an email that is already taken, gets an error
2. update the email with something valid and not in use
3. remove some parts of the email to make it invalid

#### Current behaviour
- At stage 2,  after updating, the `update profile` button remains enabled
- at Stage 3, the validation isn't triggering - the update profile button is enabled and it's letting me send jibberish

#### Expected behaviour
- Update profile should not be abled at stage 2
- Validations should show at stage 3 and update profile should disable 

#### Picture
![img](https://user-images.githubusercontent.com/11945337/225614739-f31179c2-9fd3-46c8-8c13-82534c541cfd.gif)

**Comment by carmenfan** [comment]
#### Modal needs to be longer

On a 1080 screen with a full size browser, the update/error prompt is hidden - so unless you know it's there you won't see it. We need the modal to be longer so we can see the whole thing (or we need to move the prompt)

![img](https://user-images.githubusercontent.com/11945337/225615590-4528baf9-d118-4c0a-8947-a6377470fca0.gif)
