### ISSUE TITLE
Project page improvements

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4104]
- [ ] [Remove the task tab on the projects page](https://github.com/3drepo/3drepo.io/issues/4104#issuecomment-1473757291)
- [ ] [Improve wording on selection message](https://github.com/3drepo/3drepo.io/issues/4104#issuecomment-1473759925)
- [ ] [Change wording on favourites](https://github.com/3drepo/3drepo.io/issues/4104#issuecomment-1473770002)

**Comment by carmenfan** [comment]
Improve wording on selection message
![image](https://user-images.githubusercontent.com/11945337/225904656-c6911353-84f6-4595-92a0-3f17e115fe51.png)

Can we change this to `Please select a federation or container to proceed`
