### ISSUE TITLE
Improve on saga testing

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4114]
### Description
redux-saga-test-plan has some limitations that doesnt allow the sagas to be tested properly. It works on a vacuum so you cant test it properly with other sagas, it also works on timeout, that means that the test files using redux-saga-test-plan have a minimum waiting time and it doesnt test for final states in the redux store.

### Suggested solution
Create a small framework to test it like we do with other redux functions

### Goal
- [ ] Have a more useful and reliable way to test saga functions

### Tasks
- [ ] Create a small framework to test sagas
- [ ] Add viewer testing
