### ISSUE TITLE
UI Tweaks and Issues

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3drepo.io#4123]
A list of UI tweaks to improve the look and feel of the application overall

### Goals
- [ ] Improve the look and feel of the UI
- [ ] Make the UI more consistent

### Tasks
Tasks to be posted as individual comments inside this Issue

**Comment by george-hadfield** [comment]
### Change border radius of bottom-toolbar to 25px
Currently set to 5px, this should round the left and right edges to appear circular

**Proposed design**
<img width="695" alt="image" src="https://user-images.githubusercontent.com/78047794/227186598-10aa1aea-762d-40c0-8aef-60414851f150.png">

**Existing design**
<img width="671" alt="image" src="https://user-images.githubusercontent.com/78047794/227186671-e9a35d4e-f623-47e9-8ff8-7c8e02d8b776.png">

**Comment by george-hadfield** [comment]
### Remove number count from notifications alert

**Existing design**
<img width="117" alt="image" src="https://user-images.githubusercontent.com/78047794/227186886-ed8655ad-83ad-4ddb-8e08-fdc483ceaa01.png">

**Proposed design**
<img width="103" alt="image" src="https://user-images.githubusercontent.com/78047794/227187606-90ea986a-9d56-454d-9079-e0e30c5efaf8.png">

**Comment by george-hadfield** [comment]
### Change border-radius from 5px to 10px on various elements

Apply to:

- [ ] Federations list
- [ ] Containers list
- [ ] Project permissions list
- [ ] User permissions list
- [ ] Project cards list
- [ ] Jobs list
- [ ] Users list

**Proposed design**
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/78047794/227188434-69ca02bd-d7b8-421a-b0b6-40a959784baf.png">

**Existing design**
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/78047794/227188529-6c6d7645-ff20-4077-b7ba-0993eab5cd3c.png">

**Comment by george-hadfield** [comment]
### Change modal border radius to 20px

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/78047794/227190935-fadf032e-42e8-428a-b76d-3103f7467fab.png">
