### ISSUE TITLE
Frontend automatic testing

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4133]
### Description
In the past we had frontend testing but it was to flimsy for use in the build process. We could try it again , but running it locally or try cypress

### Suggested solution
Try using selenium or cypress for automatic testing . 

### Goal
- [ ] To have automatic frontend tests (not running in the build process)

### Tasks
- [ ] Try again  selenium
- [ ] If selenium is still to flimsy to try it locally, try cypress
