### ISSUE TITLE
Minor UI issues (v4 face lifted)

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4145]
### Description
Minor UI issues that were found in #4137 

- [ ] [After entering and then deleting a date in the Start or End field of an Issue, the Cancel button returns the previous date.](https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1490063778)
- [ ] [Setting an End Date in an Issue that precedes the Start Date shows a modal error dialog](https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1490066719)
- [x] [Groups delete modal is too small and the close icon overlaps with the title](https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1490454431)
- [x] [Invalid comment in a group does not use the right colours](https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1490530060)
(there's more not linked up, check replies)
- [ ] [In the group card, the button to delete a smart filter value is not aligned with it](https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1490540671)
- [x] [When opening the compare card in a container the container is not selected in the list by default](https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1490545064)
- [ ] [When filtering a model, deselect action deselects all models instead of the selected one.](https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1490545737)
- [x] [Viewer shouldn't be able to try to create a shape on a risk](https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1494099145)
- [x] [The arrow in the GIS maps drop-down is insensitive](https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1494100551)
- [ ] [The 'Go to frame' button of the sequences field in kanban board issues/risks doesn't do anything.](https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1494100713)

**Comment by carmenfan** [comment]
#### Description
After entering and then deleting a date in the Start or End field of an Issue, the Cancel button returns the previous date.

#### Steps to replicate
1. Go into an issue (with the Start date deleted/unset)
2. Add a date
3. Delete the date
4. Click the field again
5. Click Cancel

#### Current Behaviour
The date that was originally set is still visible

#### Expected Behaviour
There should be no date

#### Pictures/ Gifs of the error

https://user-images.githubusercontent.com/5058369/227922326-a6113c39-e762-4ddf-8987-e71a3c566ebe.mp4

**Comment by carmenfan** [comment]
#### Description
Setting an End Date in an Issue that precedes the Start Date shows a modal error dialog

#### Steps to replicate
1. Go into any issue
2. Set the start date to the current day
3. Set the end date to a day before the start date

#### Current Behaviour
A modal dialog is displayed. The message is informative, but the dialog could be intimidating to some users (giant Error text, status codes they won't understand, message at the top saying "something has gone wrong").

#### Expected Behaviour
We should not allow the user to set an end date that precedes the start date (if start date is available)

#### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/5058369/227923690-883c76ed-72aa-4a1b-b28f-4c5baab4cd03.png)

**Comment by carmenfan** [comment]
#### Description
Groups delete modal is too small and the close icon overlaps with the title

#### Steps to replicate
In the viewer:
- open the groups card;
- click on the ellipsis;
- click on `Delete all`.

#### Current behaviour
The title and the close icon collide

#### Expected behaviour
The modal should be large enough to make the title and the close icon not overlap

#### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/43547703/227930613-7e722b02-7c1f-4234-8744-2cae0e62f132.png)

**Comment by carmenfan** [comment]
#### Description
In the group card, the button to delete a smart filter value is not aligned with it

#### Steps to replicate
In the viewer, open the group cards 
- open a smart group
- click on the + button to create add a new value for the smart filter

#### Current Behaviour
The button to delete a smart fileter value is not aligned with the former

#### Expected Behaviour
The button to delete a smart fileter value should be aligned with the former

#### Pics
![image](https://user-images.githubusercontent.com/43547703/227999079-130c2823-e5df-4a26-a3af-c35a0c87e406.png)

**Comment by carmenfan** [comment]
#### Description
When filtering a model, deselect action deselects all models instead of the selected one.
It happens in "3d diff" and in "instant clash"


#### Steps to replicate
 - Go to a federation
 - Filter one model
- Click on deselect

#### Current Behaviour
- Deselects all models

#### Expected Behaviour
- Deselects the selected model

#### Pictures/ Gifs of the error
![deselection error](https://user-images.githubusercontent.com/42032433/227944748-37160bd9-33c9-4bf7-b678-5df56f816a64.gif)

**Comment by carmenfan** [comment]
Viewer shouldn't be able to try to create a shape on a risk

![img](https://user-images.githubusercontent.com/11945337/227931430-5e846f8b-5428-47b1-941c-67310345d024.gif)

**Comment by carmenfan** [comment]
#### Description
The arrow in the GIS maps drop-down is insensitive

#### Steps to replicate
1. Open a container in a GIS enabled project with Here Maps enabled

#### Current Behaviour
Hovering the cursor over the arrow does not allow the user to click it

#### Expected Behaviour
The entire drop-down should allow the user to click it to select the map

#### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/5058369/227953292-ca0daebf-e7c8-4e2d-b12f-4f94ac85c8c3.png)

**Comment by carmenfan** [comment]
#### Description

The 'Go to frame' button of the sequences field in kanban board issues/risks doesn't do anything.

#### Current Behaviour
It does nothing

#### Expected Behaviour
Either it does something or it is removed
EDIT by CF: should be removed, but it should still be visible if the user is viewing the issue on the viewer

#### Pictures/ Gifs of the error

![image](https://user-images.githubusercontent.com/62481250/227963370-76d2488a-8d4e-450b-9bd3-9635cfe889f5.png)

**Comment by nkuberaf** [comment]
I dont see the container selected by default so considering this still failed: 

![image](https://github.com/user-attachments/assets/21746be4-d85f-4d6a-aece-820e0d460c3d)
