### ISSUE TITLE
Update saga tests (but Tickets)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4152]
### Description
Currently we are using redux-saga-test-plan (except for `viewer/viewer.sagas.spec.ts`) . The problem with redux-saga-test-plan is that they work in a vacuum and you cant test the saga thoroughly if it depends on another saga

### Suggested solution
Migrate the tests to the tech that is currently depicted in `viewer/viewer.sagas.spec.ts` and remove redux-saga-test-plan

### Goal
- [ ] To have more reliable saga tests

### Tasks
- [x] Migrate `auth.saga.specs.ts`
- [x] Migrate `containers.saga.specs.ts`
- [x] Migrate `currentUser.saga.specs.ts`
- [x] Migrate `federations.saga.specs.ts`
- [x] Migrate `projects.saga.specs.ts`
- [x] Migrate `revisions.saga.specs.ts`
- [x] Migrate `teamspaces.saga.specs.ts`
- [ ] <del>Migrate `tickets.saga.specs.ts`</del> (#4261)
- [ ] <del>Migrate `ticketsComments.saga.specs.ts`</del> (#4261)
- [x] Migrate `users.saga.specs.ts`
