### ISSUE TITLE
Custom Tickets: Groups - Colour picker control

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4153]
### Description
A new colour picker will be necessary for the groups feature in custom tickes

### Goals
- [ ] To have a more usefule/pretty colour picker

### Tasks
- [ ] Create the control (should be seen as an input for react-hook forms to pick up seamlessly)
- [ ] Create the predefined colours and hex editor panel
- [ ] Create the picking colour bit 

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3251-32180&t=CCepwuyWCdOc7GP7-0)

**Comment by carmenfan** [comment]
closeing as merged into main branch
