### ISSUE TITLE
Custom Tickets: Groups - Add/edit group panel

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4154]
### Description
We need  a panel for adding and editing a group

### Goals
- [ ] To be able to add and edit a group in custom tickets

### Tasks
- [ ] A new add/edit panel
- [ ] Support a disabled mode for users that dont have permissions

### Notes
Don't code in the filters for smart groups or the colour picker. Those will be addressed in a different issue.
**This panel is only accessible if you are not a viewer**

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3251-32693&t=CCepwuyWCdOc7GP7-0)

**Comment by carmenfan** [comment]
merged into #3933
