### ISSUE TITLE
Custom Tickets: Groups - smart groups filter control

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4155]
### Description
For finishing up the smart groups we need to be able to set up the rules this control is for doing that.

### Goals
- [ ] Users can create and edit smart groups rules in tickets

### Tasks
- [ ] A new control for creating the several rules
- [ ] It should end up being an input that can manage complex data so react hook forms can pick it up seamlessly 

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3251-33759&t=CCepwuyWCdOc7GP7-0)

**Comment by carmenfan** [comment]
merged into #3933
