### ISSUE TITLE
Custom Tickets: Groups - Views update state/reflect state

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4156]
### Description
When updating/creating a viewpoint as a user I need that the the state of the viewpoint stores the state of the viewer. To achieve this we are storing the data in groups within the ticket view 

### Goals
- [ ] As a ticket creator/editor (everyone but viewer):
   - [ ] Create groups for the view based on the current state of the viewer
   - [ ] Delete the whole groups field
   - [ ] Save the camera as before
   - [ ] Update image as before

### Tasks
- [ ] As a ticket creator/editor (everyone but viewer):
    - [ ] When updating the current view it creates groups and save it in the view
    - [ ] When updating the image it saves it (deletion or new image)
    - [ ] When updating the camera(look at and clipping planes)  it saves it (deletion or new camera)

**Comment by carmenfan** [comment]
merged into #3933
