### ISSUE TITLE
UI Tweaks and Issues - Batch 2

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4169]
### Description

This is a follow on from #4123 to prevent that PR getting too large and unwieldy. 
- [x] [Remove white backgrounds from projects list, users, jobs, teamspace settings (look at link for full details!)](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1502906643)
- [x] [Remove 'New project' card from project selection](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1502907937)
- [x] [Change number on accordion titles to be inside a circle](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1502912299)
- [x] [Update font size below Teamspace title on Project selection screen](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1502917890)
- [x] [Change h1 and h2 font weights to 700](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1502920808)
- [x] [Set minimum width for Teamspace menu to 200px](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1502924891)
- [x] [Change accordion buttons to rounded squares rather than circles](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1502926304)
- [x] [Change viewer bottom toolbar to new design](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1502945104) (WILL NOT BE ADDRESSED HERE, look at https://github.com/3drepo/3drepo.io/issues/4325)
- [x] [Make sure all the padding around the dashed empty states in the viewer are consistent (problem areas listed in link)](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1502939149)
- [x] [Increase height of viewer inputs to 30px - currently 26px](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1507079881) (temporarily suspended)
- [x] [Remove outer border of project permissions/user permissions tables so they resemble container federations lists](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1506540543)
- [x] [In uploads modal table border radius and drag and drop border radius should be the same (10px)](https://github.com/3drepo/3drepo.io/pull/4151#issuecomment-1520076481)

### Suggested solution
- [ ] fix the ui

### Goal

- [ ] Have clear consistent design

### Tasks
- [ ] fix the ui
