### ISSUE TITLE
Custom Tickets: Groups - selecting a ticket with groups in the list should affect the view

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4176]
### Description
When selecting a ticket that contains a view with groups the viewer should be set with the state of that view

### Goals
- [ ] As any user when I click on a ticket that contains a view with groups I want the viewer to reflect the whole view state

### Tasks
- [ ] When selecting an issue with a view with groups fetch the groups
- [ ] After the groups were fetch update the viewer to reflect that state

### Notes
The camera should be reflected as before
