### ISSUE TITLE
Custom tickets - ability to filter closed tickets

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4189]
### Description
We need a quick work around for filtering closed tickets. This is the same behaviour we have with issues and risks in v4.

### Goals
- [ ] For risks if mitigation_status is **agreed_fully** or **void** , they  should not be shown in the list by default.
- [ ] For issues if status is **closed** or **void** , they  should not be shown in the list by default.
- [ ] we need to add a filter (possibly a toggle) to show/hide resolved/voided tickets

### Tasks
- [ ] Dont show clse/void/tratead risk or issue tickets
- [ ] Add "completed" filtering pill. When is toggled on closed/void/trated risks and issues should be shown 

### Related Resources
[Design](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=23%3A30556&t=K2zTrLPH7ksEz4nm-1)

**Comment by george-hadfield** [comment]
**Link to design**
https://www.figma.com/proto/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?page-id=3457%3A29998&node-id=23-32372&viewport=-27649%2C1861%2C1&scaling=min-zoom&starting-point-node-id=23%3A32597
