### ISSUE TITLE
Make extents button use the default view 

### ISSUE THREAD

**Issue by anorrie** [3drepo/3drepo.io#4207]
### Description

Change the behaviour of the extents button to take the user to the default view. 

### Goals

- [ ] when a user clicks the home button it should take them to the default view (Home View)

### Tasks

- [ ] Make the extents button go to the default view 
- [ ] If not default view set then go to extents 
- [ ] Rename extents to "Home" 
- [ ] Rename defualt view to "Home View"
