### ISSUE TITLE
Custom Tickets: Groups - Views input upgrade UI

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4214]
### Description
For accessing the new groups the view input will be updated to accomodate the groups. 
**Important** : when updating the view now it creates groups with the whole state of the viewer (overrides and hidden groups), the camera and clipping planes are still saved in the camera prop

### Goals
- [ ] To have a new cleaner ui for views
- [ ] To have a way to access and change groups

### Tasks
- [ ] Update the ui with the new design
- [ ] Add a way to navigate to the groups card inside of the ticket card 

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3042-23547&t=wExZ71I9NEiTL5BX-0)

**Comment by carmenfan** [comment]
merged into #3933
