### ISSUE TITLE
Custom Tickets: Groups - Wire in logic for groups tab

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4224]
### Description
Right now the groups tab only reflect the groups and has a mockup modal to delete groups. Wire in the logic for overrides, selecting a group, adding a group , deleting a group

### Goals
- [ ] To have all the functionality for groups wired in 

### Tasks
- [ ] Overrides in the groups tab
- [x] Delete groups in the groups tab
- [ ] Hide a group in the groups tab
- [x] Create a group (hardcoded)
- [x] Update a group (hardcoded)
- [x] When clicking a group highlight the selected meshes

**Comment by carmenfan** [comment]
Merged into #3933
