### ISSUE TITLE
Remove  avatarurl and hasurl 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4232]
### Description
Avatarurl and hasAvatar in members and current user doesnt seem to originate from the backend and having that in the currentuser and member creates some confusion. It also created a performance issue  by recalculating the members in the selector without reason

### Suggested solution
Get rid of avatarul and hasUrl from the redux store for users and members.

### Goal
- [ ] Decouple a field that only concerns the avatar components
- [ ] Simplify the code a bit more

### Tasks
- [ ] Calculate the avatar url in the avatar components
- [ ] Remove hasavatar and avatarul from the store
