### ISSUE TITLE
ticket sagas testing refactor + missing tests

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4261]
### Description
TIckets sagas test are using an old framework  we should update them and add the missing groups tests

### Goal
- [ ] Have updated and complete tests

### Tasks
- [ ] Change the existing tests to use redux-sagas style 
- [ ] Add group tests
