### ISSUE TITLE
Custom Tickets: Groups - Create Collection

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4272]
### Description
When creating/editing a new group, a user should be able to create a new collection to add the group to.
Right now, we are missing that functionality.

### Goals
- [ ] when creating/editing a group, the "create collection" button should be available

### Tasks
- [ ] create a "create collection" button
- [ ] create a panel that opens on "create collection" click
- [ ] the new group should not clash with an existing group in the same level
- [ ] the new group should be selected in the main form

### Related Resources
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?type=design&node-id=3251-33110&t=sExM20hbwxmMD8bA-0

**Comment by carmenfan** [comment]
Merged into #3933
