### ISSUE TITLE
Polish save groups

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4275]
### Description
Adding the Groups feature into 3D Repo, allowing the user to create/edit/delete groups

### Goals
- [ ] To have edit working correctly

### Tasks
- [x] Feedback in the list when clicking the group
- [x] When I save the group it should re-highilght the group
- [x] Dehighlight when clicking outside the group
- [x] Dehighlight when leaving the groups tab
- [x] Fix group form schema
- [x] Add smart group saving
- [x] Make cancel button work

**Comment by carmenfan** [comment]
Merged into #3933
