### ISSUE TITLE
Custom tickets - groups objects count

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4286]
### Description
Right now the the mesh count is not correctly calculated in groups in from the ticket

### Goals
- [ ] As a user I want to know how many objects does the group have.

### Tasks
- [ ] Calculate the group object count
- [ ] Show the object count in the groups list

**Comment by sanmont3drepo** [comment]
fixed in #3933
