### ISSUE TITLE
Custom Ticket:Groups - performance issue

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4294]
### Description
There's a re-rendering problem with the group items. When a new one gets created it is added to the list. Then all the list items refresh. This refresh seems unnecessary.

The image below shows 'group' being logged for a new group. As you can see it successfully reads as an object before it is updated to be a string before again returning as an object
![248812086-57ff242f-e7a3-4b0d-b6a3-ef44787ee863](https://github.com/3drepo/3drepo.io/assets/43547703/31426ffd-158e-4429-9d43-0d9a449d84f4)

### Goals
- [ ] Improve rendering time required for custom ticket groups

### Tasks
- [ ] Find the problem causing the refreshing
- [ ] Fix the amount of times the list gets re-rendered
- [ ] Make sure the same problem will not happen when deleting/editing/editing and changing prefix for a group

**Comment by carmenfan** [comment]
merged into main branch ISSUE #4299
