### ISSUE TITLE
Custom Tickets - Pin coloring

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4340]
### Description
This is the main issue for pin colouring.  At the moment tickets pin colours of tickets are hardcoded. To provide more flexibility we want to allow the users to be able to odefine their own colours in the the templates

backend changes were made in https://github.com/3drepo/3drepo.io/issues/4338 (To be merged into this branch)

### Goals
- [ ] As an admin user, I should be able to:
  - [x] not specify a pin colour and the pin will be coloured according to the default behaviour
  - [x] specify a pin colour and the pin will always be coloured to that colouring.
  - [x] specify a logic of how the pin should be coloured based on the values of a property
- [ ] As a Custom ticket user, I should be able to:
  - [x] See a pin with no specified colouring to be coloured by default behaviour
  - [x] See a pin with a colour specified to always be coloured as the specified colour
  - [x] See a pin colour changes according to another property if it is specified that way.
  - [x] Click on the the select pin button and see the pin rendered in a different way so it stands out

### Tasks
- [x] Add new method in unity util  "DropTicketPin"
- [x] Update **pinDetails.compone**nt with the new UI
- [x] Update **pinDetails.component** to be able to select a pin
- [x] Update **selectTicketPins** in  `src\v5\store\tickets\card\ticketsCard.selectors.ts`  to use the new pin type 'ticket'
- [x] Update **showPin** in `src\v4\services\viewer\viewer.tsx` to manage the new pin type ticket and call dropticketpin in unity util
- [x] Update **selectTicketPins** in  `src\v5\store\tickets\card\ticketsCard.selectors.ts`  to use the new pin colours schema
- [x] Move **pinDetails.component** to `src\v5\ui\routes\viewer\tickets\ticketsForm\properties as` the rest of the properties
- [ ] Test ALL 5 cases of pin colouring.

### Notes
New colouring schema in templates: 

<details>

#### Colouring not specified
The way the pin is coloured is not specified. This is the current situation. (should have the default hardcoded colour)

#### A single colour is specified
Template instructs that the pin should be coloured in a specific colour

````js
// Default pin
{
   config: {
       pin: {
           color: [r, g, b]
       }
   }
}

// Custom pin
{
   properties: [{
       name: "Custom pin",
       type: "coords",
       color: [ r, g, b]
   }]
}
````

#### Colouring of the pin is based on the value of a certain field
````js
// default pin
{
   config: {
       pin: {
           color: {
                property: {
                  name: "priority"
                },
                mapping: [
                    {
                        default: [r, g, b]
                    },
                    {
                        value:  "low",
                        color: [r, g, b]
                    },
                    {
                        value:  "medium",
                        color: [r, g, b]
                    }
                ]
           }
       }
   }
}
// Custom pin 
{
   properties: [{
       name: "Custom pin",
       type: "coords",
       color: {                
                property: {
                  "module": "safetibase",
                  "name": "Level of Risk"
                },
                mapping: [
                    {
                        default: [r, g, b]
                    },
                    {
                        value:  "low",
                        color: [r, g, b]
                    },
                    {
                        value:  "medium",
                        color: [r, g, b]
                    }
                ]
           }
   }]
}
````
</details>

UI design summary (check figma for more [details](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=482-37509&mode=design&t=qTjqf6CRjuPRy4Pv-0)):
<details>
<img width="782" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/8879da60-da76-4e71-9991-090db7465285">
</details>

### Related Resources
[Feature scope](https://github.com/3drepo/3D-Repo-Product-Team/issues/293) 
[UI design](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=482-37509&mode=design&t=qTjqf6CRjuPRy4Pv-0)
