### ISSUE TITLE
SSO - restricting access to only SSO users and/or from approved domain

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4342]
### Description
Create the ability to restrict access to users who are logged in using SSO, and/or from specific AAD domains

See details in https://github.com/3drepo/3D-Repo-Product-Team/issues/262

#### Schemas
In the teamspace settings, we will add a configuration to deduce if the teamspace is restricted
````js
// The teamspace is restricted to only allow SSO users
{
  security: {
    ssoRestricted: true,
    allowedDomains: ["3drepo.org", "asite.com"]
  }
  // ...other teamspace settings
}

````

### Goals
- [x] As an admin user, I should be able to
  - [x] Request 3drepo support to enforce/cancel SSO restriction on my teamspace
  - [x] Request 3drepo support to enforce/cancel a domain restriction on my teamspace
  - [x] Request 3drepo support to enforce/cancel both SSO only and a domain restriction on my teamspace 
- [x] As a team member of a SSO restricted teamspace, I should be able to 
  - [x] log in and access the teamspace as normal if I am logged in via SSO from a sanctioned domain
- [x] As a team member of a SSO restricted teamspace, I should not be able to
  - [x] access the teamspace if I have unlinked my account from AAD
  - [x] access the teamspace if I am linked to a AAD directory that is not sanctioned in the teamspace
- [x] As a team member of a domain restricted teamspace, I should be able to
  - [x] access the teamspace only if my email is from an accepted domain
- [x] As a team member of a normal unrestricted teamspace, I should be able to
  - [x] access the teamspace as normal regardless how I am authenticated

### Tasks
- [x] Add a script to configure whether a teamspace should be restricted by SSO users only
- [x] Add restriction on middleware to enforce the check

### Related Resources
scope: https://github.com/3drepo/3D-Repo-Product-Team/issues/262
