### ISSUE TITLE
Custom tickets - Tabular view

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4347]
### Description
Users needs to be able to view tickets outside the viewer and group them by the relevant criteria, so we figured that a table view with groups by is the best to approach this.

### Goals
- [ ] Have a useful view for users to manage tickets in the dashboard.

### Tasks
- [ ] Blank state
- [ ] Templates select
- [ ] Groupby select
- [ ] Logic for grouping by
- [ ] Add the new ticket button (consult with Carmen and George about it)

Nice to have:
- [ ] Routing; a link that selects all the appropiate filters
- [ ] Endpoint for getting the tickets by modelid and template
- [ ] Endpoint for getting the templates by project

### Notes
The initial code for this branch is scaffolding intended to provide the spaces for the final components, change any code as needed.

### Related Resources
[MockUp](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=410-41485&mode=design)
