### ISSUE TITLE
Tabular view - Federations and containers multiple select

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4357]
### Description
For tabular view we need a federations/containers multiple select that complies with the design 

### Goals
- [ ] To be able to select federations and containers from the same searchable select

### Tasks
- [ ] Add the default selection mode (consult with Carmen)
- [ ] Apply the design

### Notes
Branch from #4347 .  Change the logic as needed

### Related Resources
[MockUp](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=464-43276&mode=design&t=qSsF1vfLNlAAPyFD-0)

**Comment by carmenfan** [comment]
done in #4347
