### ISSUE TITLE
Tabular view - Ticket form

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4358]
### Description
In the tabular view there's a ticket form that get displayed when selecting a ticket or creating a new one.  This should reuse the same forms for ticket details and new tickets as in the viewer. But adapt them to the context of not having a viewer. For example dropping a pin or taking a screenshot from the viewer is impossible in this CONTEXT (**wink** **wink**)

- The new ticket form have select the template type from the tabular view
- The new  ticket form will have preselected the groupBy value eg and wich 'new ticket button was clicked'
   eg.: if you click on new ticket in the tabular view that is inside the 'medium' group when grouping by priority, then the from will have 
the value 'medium' in the priority field.

- Be aware of the properties that depends on the viewer that is no longer there

### Goals
- [ ] Users can edit and create new tickets in the tabular view

### Tasks
- [ ] Adapt the new ticket component for tabular view
- [ ] Adapt the ticket details component for tabular view
- [ ] Add the link for the ticket when editing an existing ticket (issue #4190)

### Notes
- This will branch from #4347

### Related Resources
[MockUp](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=410-41485&mode=design&t=qSsF1vfLNlAAPyFD-0)

**Comment by carmenfan** [comment]
merged into https://github.com/3drepo/3drepo.io/issues/4347
