### ISSUE TITLE
Tabular view - Collapsible table

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4359]
### Description
For tabular view we need a table of tickets that presents the information in a sensible manner for the context.
Use the same criteria for showing the extended properties as we do in the ticket list inside the viewer.

### Goals
- [ ] To have a reusable table for the results in tabular view

### Tasks
- [ ] Create a collapsible table with the information that is shown in the  design
- [ ] Add the different  columns depending if the template has enabled the appropiate properties (like risk or issue properties)
- [ ] Try to reuse or adapt the special components like asignees or status level of risk or status, etc

### Notes
This will be a branch from #4347 

### Related Resources
[MockUp](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=342-37215&mode=design&t=qSsF1vfLNlAAPyFD-0)

**Comment by carmenfan** [comment]
merged into the main branch
