### ISSUE TITLE
Refactor Ticket sagas tests

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4361]
### Description
Currently we are using redux-saga-test-plan in the ticket sagas tests. The problem with redux-saga-test-plan is that they work in a vacuum and you cant test the saga thoroughly if it depends on another saga (Refer to #4152)

### Suggested solution
Migrate the tests to the tech that is currently depicted in the other sagas tests and remove redux-saga-test-plan

### Goal
- [ ] To have more reliable saga tests

### Tasks
- [ ] Migrate `tickets.saga.specs.ts`
- [ ] Migrate `ticketsComments.saga.specs.ts`

**Comment by sanmont3drepo** [comment]
duplicated from #4312
