### ISSUE TITLE
Supporting more options on field name variations on smart rules

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4383]
### Description
See [scoping document](https://github.com/3drepo/3D-Repo-Product-Team/issues/308) for full context.

**This is a sub task of #4386. Please branch/merge with that branch instead of staging.**

We need to augment the [rules schema](https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/schemas/rules.js) to support varied field names, similar to values.

The following operators need to be supported:
- `IS` : field name is an exact match to the string
- `CONTAINS`: the string is a substring within the field name i.e `/{string}/i`
- `STARTS_WITH`: field name begins with the string i.e. `/^{string}/i`
- `ENDS_WITH`: field name ends with the string i.e. `/{string}$/i`
- `REGEX`: user provides a regex to specify what they would like.

#### Schema changes
We would expect the rule to look something like this

````js
{
  field: "fruits",
  operator: "EQUALS",
  values: ["apples", "oranges"]
}
````

````js
{
  name: "rule name"
  field: { operator: "IS", values: ["fruits", "items"]},
  operator: "EQUALS",
  values: ["apples", "oranges"]
}
````
##### Notes
- All operators support 1 or more values, with the exception of regex.
- We need to ensure we still support the old schema to ensure compatibility for any incoming requests, we need a migration for existing data
- name is a new field and is required. for existing data, we need a database migration to add a name based on the logic from the front end.

### Goals
- [ ] To be able to specify rules with variation on field names
- [ ] Old schema should still function correctly.
- [ ] Ensure this function is supported in both v5 ticket groups and v4 groups

### Tasks
- Schema updates
  - [ ] Update [rules schema](https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/schemas/rules.js#L79) to support the new data structure
  - [ ] Ensure old schema is still understood (I would do this in rules schema and have a cast function)
    - [ ] we should only output the rules under new schema (i.e. convert it to new schema if we're returning a smart group with old data
    - [ ] old schema coming in from a network request will be understood and converted
    - [ ] old schema in existing groups will be understood and converted
- [ ] [Translates](https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/models/metadata.rules.js#L32 ) the new operators to mongo database queries 
- [ ] Ensure same logic is applied for v4 groups (make v4 codebase use v5 functions if appropriate)
- Unit Tests
  - [ ] Ensure all operators have tests
  - [ ] Ensure old schema have tests
- e2e Tests
  - [ ] Ensure all operators have tests
  - [ ] Ensure old schema have tests
- [ ] Data migration
  - [ ] Add a name to all rules, based on the logic currently on the front end
  - [ ] Change all `{ field: string }` to `{ field: {operator: "IS", value: [string]}}` (make it separate, we will run it one release later)

### Related Resources
Figma: https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=715-17375&mode=design&t=QUnvuU28wOnbtypc-0
Scope: https://github.com/3drepo/3D-Repo-Product-Team/issues/308

**Comment by ChristosTsiotsias** [comment]
Range rules seem to accept any even number of values ie. 4, 6 etc. Is that correct ? Cause you cant do that through the UI

Also all there operators seem to accept more than one value even though you cant do it through the UI. Should we keep it like that ?

![image](https://github.com/3drepo/3drepo.io/assets/71635617/ceb8054a-2b97-458f-b98e-5d731d417ce6)

**Comment by carmenfan** [comment]
closing as it's been merged into #4385
