### ISSUE TITLE
Adding rules to support a variation of field names

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4386]
### Description
This is a parent issue for many sub tasks around supporting regexed field names within smart rules.

See scoping issue for details https://github.com/3drepo/3D-Repo-Product-Team/issues/308

### Goals
- As a user I want to be able to create smart group rules for a certain field regardless of the parent category the field belongs in
- As a user I want to be able to create a smart group rule where for multiple fields, and consider an object a match if it contains matching data for any of those fields
- As a user I want to be able to create smart group rules for multiple fields regardless of the parent category (i.e. the combination of the top 2 stories)
- As a power user that understands how to create a regex, I want to be able to just provide a regex to explain the field name I want to match so I can maximise the flexibility.
### Tasks
- [x] https://github.com/3drepo/3drepo.io/issues/4383
- [x] https://github.com/3drepo/3drepo.io/issues/4385
- [x] https://github.com/3drepo/3drepo.io/issues/4384
