### ISSUE TITLE
Image UI changed due to viewpoint UI changed

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4398]
### Description
Image UI now looks like this:
![image](https://github.com/3drepo/3drepo.io/assets/11945337/098803b6-5689-4a1c-9caa-8e6534686f42)

This was a consequence of the property share the same code as the view UI. This was not intentional

We probably want to rework this.

### Goals
- [ ] A better UI for image property. The user should be able to
  - [ ] Upload an image (or screenshot the current image) 
  - [ ] Remove an existing image (if available)

### Tasks
TBD

**Comment by carmenfan** [comment]
closing in favour of a bigger scoping exercise in https://github.com/3drepo/3D-Repo-Product-Team/issues/243
