### ISSUE TITLE
A utility script to gather plugin usage stats

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4417]
### Description
We want to gather usage info around plugin usage to better understand plugin usage activity. This will help us to determine which version of plugins we can drop, and which version of Autodesk software we no longer need to support.

We record this as part of the login records, it tells us if the user is logging in from the plugin and if so, what version of the plugin and which autodesk software:

![image](https://github.com/3drepo/3drepo.io/assets/11945337/41b2ce7a-9a5f-46e3-83f0-c3ebdb3ed1cc)

We'd like a utility script that, given a time range (e.g. within the past 6 months, or past year etc) how many users have logged in using which version of which application, and using what version of the plugin. So something like this:

````csv
Application,Version,Plugin Version,#logins
Revit, 2021,5.4.0,10
Navis, 2024,5.2.0,5
````

### Goals
- [ ] As an administrator I want to be able to find out the usage stats around plugins so I can make a decision on which version of the software/plugin to support.

### Tasks
- [ ] A utility script to process login records to find out the data
- [ ] test for the new script
