### ISSUE TITLE
Update the frontend to understand the new federation settings/ federation stats schema

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4428]
### Description
We need to update the front end to understand the new schema, which is being returned by federation settings and federation stats.
We also need to update the edit federation panel to allow users to define groupings for their federations.

See scoping document for details: https://github.com/3drepo/3D-Repo-Product-Team/issues/304

#### READ ME
- Please branch from https://github.com/3drepo/3drepo.io/issues/4391
- This will also require https://github.com/3drepo/3drepobouncer/issues/639 for the full experience (though not necessary for the frontend work)

### Goals
- [x] The user should be able to view federations as before (currently broken on v5 viewer due to it not understanding the new containers array)
- [x] The user should be able to edit federations and optionally add grouping should they wish to
  - [x] existing groups should appear as a suggestion to minimise chance of typo errors

### Tasks
- [ ] Adapt the `IFederation` interface to work with the new `containers` prop;
- [ ] Use new edit federation design (do not worry about the new modal design just yet);
- [ ] Add a autosuggest in the included containers to manipulate the group

### Related Resources
Scoping document: https://github.com/3drepo/3D-Repo-Product-Team/issues/304
Federation edit mockup: https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=605%3A38114&mode=design&t=1PFl8RzEZtGnLqX2-1
