### ISSUE TITLE
New Modal styling

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4435]
### Description
Use the new styling for modals

### Goals
- [ ] replace the old modal styling with the new one

### Tasks

- [ ] Check the viewer uses the new styling everywhere
- [ ] Check v5 uses the new styling everywhere

### Related Resources
[link](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=605-38114&mode=design&t=1wF7IkcDT6QROuZV-0)
