### ISSUE TITLE
Auto-import does not detect react-router/react-router-dom

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4449]
### Description
It seems that VSCode is not able to detect react-router[-dom] exports and does not suggests them.
The problem causing might also be responsible for lack of type checking with regards to these libraries.

### Suggested solution
Adding the @types dependency for react-router-dom may fix the problem
`yarn add @types/react-router-dom --save-dev`

### Goal
- [ ] simplify react-router-dom usage and add type checking support

### Tasks
- [ ] VSCode auto import should suggest methods and component that can be exported from react-router-dom;
- [ ] react-router-dom exports should suggest type errors
