### ISSUE TITLE
Tabular View - fixes

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4467]
### Description
(This should be a  subbranch of #4347)
Tabular view has the major features in place, but comes with some minor issues.

### Goals
This branch should address the following:
- [ ] When a user tries to create a ticket that requires the viewer, they shouldn't get stuck;
- [ ] Properties disabled because they required the viewer should state that more clearly;
- [ ] There should be an indication about which ticket is currently being edited

### Tasks
- [ ] When a user tries to create a ticket that requires the viewer, the "go to viewer" button should be enabled;
- [ ] Properties disabled because they required the viewer should state that in the name;
- [ ] TBD

**Comment by Amantini1997** [comment]
Merged into #4390
