### ISSUE TITLE
Optimise sequence frame hidden instructions

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4486]
### Description
In sequences we are currently showing all nodes and then we hide the ones that we need to hide . That means that if in the sequence we have the same state defined in two consecutive frames I'm sending extra commands to show and hide the same meshes.

### Suggested solution
We should do the same thing we are doing with colour overrides. Show just sending the difference between frames.

### Goal
- [ ] We should only send the necessary commands

### Tasks
- [ ] Calculate the difference between frames
- [ ]  Send those hide/show commands
