### ISSUE TITLE
Improve Skeletons components

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4500]
### Description
To indicate a loading status, a common approach is to use skeleton components. We often use them across v5, but they are inconsistent or missing in some scenario

### Goals
- [ ] Make sure skeletons are correctly used where required
- [ ] Make sure skeletons are consistent

### Tasks
- [ ] Add skeletons to projects
- [ ] Fix federations/containers skeletons to match the final structure
- [ ] (?)Add skeletons for LinkCards (teamspaces and projects)
