### ISSUE TITLE
Keep teamspace and project updates in a single file

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4508]
### Description
Right now we have multiple files responsible to listen for changes in the current teamspace or project.
They then make the necessary calls to redux/sagas method.

This is not the right approach as the same logic is repeated across multiple files, making the code harder to maintain and more prone to errors.

### Suggested solution
We should try to keep this kind of logic in the same file.

### Goal
- [ ] Avoid repeating redux/sagas logic for projects and teamspace;
- [ ] Find an approach valid both in the viewer and the dashboard

### Tasks
- [ ] Create a single file to handle teamspace (redux/sagas logic) when it changes;
- [ ] Do the same for projects
- [ ] Consider the option to create a component to place higher up in the virtualDOM to listen to these changes both in the viewer and in the dashboard

### Resources
Following in example of where we repeat the same logic to update the currentProject in redux
![image](https://github.com/3drepo/3drepo.io/assets/43547703/c979752b-0203-4e38-9df4-c0d20e8a9b08)
