### ISSUE TITLE
Allow projects to have images

### ISSUE THREAD

**Issue by ChristosTsiotsias** [3drepo/3drepo.io#4524]
### Description
We should allow projects to have images as described in [here](https://github.com/3drepo/3D-Repo-Product-Team/issues/292). 

Changes:

####  Get a project image:

GET v5/teamspaces/{teamspace}/projects/{project}/image

response: binary stream of the image
permission: anyone who has access to the project

#### Update a project image:

PUT v5/teamspaces/{teamspace}/projects/{project}/image

payload: multi-part form with the key palue pair: "file" : file in binary form
response: OK for success or an error code if it fails
permission: Project admin (or teamspace admin)

![image](https://github.com/3drepo/3drepo.io/assets/71635617/39ccba4a-8eb4-4d6a-ac6b-7c8ad01238bb)

#### Delete a project image:

DELETE v5/teamspaces/{teamspace}/projects/{project}/image

response: OK for success or an error code if it fails
permission: Project admin (or teamspace admin)

### Goals
- [ ] User should be able to add a project image.
- [ ] User should be able to edit a project image.
- [ ] User should be able to delete a project image.
- [ ] User should be able to retrieve project image.

### Tasks
GET endpoint
- [ ] Should retrieve the image of the project and return a binary stream
- [ ] Should return fileNotFound if there is no image

PUT endpoint
- [ ] Should accept the binary stream of the image and validate the data
- [ ] Should store the image in fileshare as well as the ref projects.ref
- [ ] If there is an existing image it should be removed from fileshare as well as its ref should be removed from projects.ref

DELETE endpoint
- [ ] Should remove the image from filestream
- [ ] Should remove the ref from projects.ref

**Comment by carmenfan** [comment]
@ChristosTsiotsias 

see comment here: https://github.com/3drepo/3D-Repo-Product-Team/issues/292#issuecomment-1770949214
