### ISSUE TITLE
Update 3drepo logo

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4525]
### Description
Because we are part of asite now we need to update the logo in all the places where they are to reflect the state of the company

### Goals
- [ ] Get users to know that we are now part of asite

### Tasks
- [ ] Update the logo in the login/signup pages
- [ ] Update the logo in the footer of the dashboard pages

### Related Resources
[
Images](https://asitesol.sharepoint.com/sites/3DRepoTeamFolder/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2F3DRepoTeamFolder%2FShared%20Documents%2FMarketing%2FLogos%2FAsite%203D%20Repo%20Logos%2FPNG&p=true&ct=1697545608534&or=Teams%2DHL&ga=1&LOF=1)
