### ISSUE TITLE
Tabular View: Remove "Unset" group when default exists

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4549]
### Description
In Tickets Tabular view (#4347), some grouping options have the "Unset" group batch at the bottom.
This should only be displayed if the template does not have a default value for the respective property

e.g. The user groups by `priority`. If the property in the template come with a default value (`default`), then the group batch "Unset" should not exist as it is "unreachable". 

### Goals
- [ ] The UI should better reflect the reachable states
- [ ] An unreachable (and always empty) state should not have its own group

### Tasks
- [ ] If the group is one of [priority, status, level of risk, treatment status] and the respective property has a default value, don't show the "Unset" group
