### ISSUE TITLE
Add placeholder in Edit federation settings for inaccessible containers

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4560]
### Description
When a user tries to edit a federation with more than 1 container, but they don't have sufficient permissions for some of them (e.g. they have viewer permissions for one of them), the latter are automatically removed from the federation.

So doing, the user see the "save changes" button already enabled, without having a clear idea of what they would be doing by saving the form.

### Goals
- [ ] The user should be provided with a better knowledge about the federation
- [ ] Some information about the inaccessible containers should be provided
- [ ] The form should not allow to be saved without interactions

### Tasks

- [ ] Add a placeholder for inaccessible containers
- [ ] When the user edits some containers (add/remove/edit group), the inaccessible containers should be kept as part of the federation

**Comment by AsiteZane** [comment]
To discuss as part of permissions revamp.
