### ISSUE TITLE
Only filtered ticket pins should be visible 

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4563]
### Description

This was initially found in 5.6 QA https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1783156043
The ticket pins should reflect what is shown in the ticket list. If tickets are filtered out of that list their pins should not be visible. If the ticket card is closed the pins should remain as if the card had been left open.
If a user goes into ticket details only the ticket pins for that ticket should be visible

### Goals

- [ ] The visible pins reflect the filtering on tickets
- [ ] Default pins are added/removed when tickets list filtering changes
- [ ] When the user first opens a model all the uncompleted ticket pins should be visible (As in it should match the ticket list when opened)
- [ ] The visible ticket pins should remain constant when the ticket card is closed. Only upon opening it again and the list is reset should the pins also reset

### Tasks

- [ ] Move ticket pin logic out of v4 (`viewerCanvas.component.tsx`)
- [ ] Have ticket pin logic depend on items in the ticket list

### Related Resources
I had an attempt by adding a useEffect to TicketItem
![image](https://github.com/3drepo/3drepo.io/assets/62481250/c2534f86-0871-43e7-a59c-6397cc7cdb6d)
But could not find a way of not removing the pin when closing the card (the ticketsCardOpen technique doesn't work )
