### ISSUE TITLE
Add placeholder for failed revisions

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4564]
### Description
At the moment failed revisions goes into the void and it's not clear that it has happened. We should add a record in the revision history to indicate it existed (and link to the file) so it doesn't look like the operation never happened.

### Goals
- [ ] As a collaborator I would like to know the aftermath of my revision if it has failed (and have a record of why it has failed)

### Tasks

- [ ] A new Group panel
- [ ] List group component
- [ ] edit group component
- [ ] new API end point to remove groups
- [ ] New database schema for groups (present it here)

### Related Resources

MockUp : `link to mockup`
Coda doc: `link to coda`

**Comment by AsiteZane** [comment]
@carmenfan - could we discuss this please and how long it might take?
