### ISSUE TITLE
Project images

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4566]
### Description
We want users to be able to have custom project images to identify the project much faster. Also improves the sense of ownership for the users.

### Goals
- [ ] Admins should be able to create a project and upload a project image
- [ ] Admins should be change  a project image  in the project settings
- [ ] All users with access to the project should see the project image in the project list 

### Tasks
- [ ] Modify the api files to be able to upload an image (update and new)
- [ ] Update project settings to be able to upload an image for the project
- [ ] Update projectCard to use the new image if there's one or to use the default one
- [ ] Update new project modal to be able to upload a project image 

### Notes
For uploading the image in the new project modal we could use two api calls: one for creating the project and the second one patching with the new project image. 

### Related Resources
<img width="551" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/bcbb235f-87d7-4c84-aa81-163d62c8de41">

[MockUp ](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=855-18588&mode=design&t=wHOMQ4O77s5FiSe6-0)

[Issue for the api](https://github.com/3drepo/3drepo.io/issues/4524)

**Comment by carmenfan** [comment]
@sanmont3drepo  yes admin only. see #4524 
![image](https://github.com/3drepo/3drepo.io/assets/11945337/13e0689e-2678-4498-95a0-a269ac504117)


Note: George also requested to add the default image for a project with no image ( the blue ones in the mockup)
