### ISSUE TITLE
Automatic tests for authentication

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4572]
### Description
We want to be able to test the app at any given time without using a lot of man power. For this reason using automatic tests would help. 
As a first step we want to have all tests from the authentication tab in the test spreadsheet.

### Suggested solution
Use the regression tests framework to translate all authentication tests in the test spreadsheet. Use mailhog to test the verification emails.

### Goal
- [x] All authentication tests should be working automatically

### Tasks
- [x] Test Mailhog
- [x] Create Login feature test
- [x] Create Login SSO feature tes
- [x] Create Logout test
- [x] Create Signup test
- [x] Create Signup SSO test
- [x] Create Sign up (links) test
- [x] Create Reset Password test
