### ISSUE TITLE
1.13 bugs v2

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#458]
Actual Bugs:
- [x] [Billings page hangs forever unless you load the license page first](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322132218)
- [x] [Being a Teamspace admin no longer automatically make you a project admin](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322135909)
- [x] [Only teamspace owner is being automatically assigned as model admins](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322136866)
- [x] [Paypal button is missing on the billings page](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322138369)
- [x] [Permissions still need cleaning up](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322140534)
- [x] [As a project admin I'm not getting permission on the side menu for models](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322162363)
- [x] [Pin should take precedence over measuring tool](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322168604)
- [x] [Bugs around multi-select](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322170209)
- [x] [Bugs when you load an earlier revision](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322171410)
- [x] [Page doesn't hook up to the chat server upon refresh](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322173680)
- [x] [Forgot password page still doesn't work](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322777755)
- [x] [Occasionally components + viewer doesn't load](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322779428)
- [x] [Invalid Revision name when it looks valid](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-323020142)
- [x] [Import failure message is stopping user from viewing the previous revision of the model](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-325682728)
- [x] [Can't delete model. Error: Internal Error](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-326245921)
- [x] [Can't deselect multi-selected objects or select other objects when created new issue](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-326248876)
- [x] [3D Viewer jerks when one card is opened and opening or closing the second card](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-326249118)
- [x] [Users deleted with GUI appear in Teamspace Permissions](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-326246674)
- [X] [Upload dialog doesn't go away when I hit UPLOAD button](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-326620144)
- [x] [Missing reset password page](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-327185258)
- [x] [Selected objects not saved with issue](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-328050925)
- [x] [Issues filter reset doesn't show all issues](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-328105499)
- [x] [Jobs list multiplied in issues menu in federation](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-328127738)
- [X] [Revisions fail to load in the viewer](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-328160809)
- [x] [Partial failures are being shown as Failed to import once refreshed](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-328213959)
- [x] [Show resolved issues doesn't work](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-328494835)
- [x] [Unassigned Models message is not true](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-328535295)
- [x] [Print issues not working](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-329232157)
- [x] [Can't select some objects](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-329430733)
- [x] [Issues: Pins of closed issues don't disappear](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-330165214)
- [x] [Pins of submodel issues are being shown when the issue themselves are not shown](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-331846650)
- [x] [URL not changing upon verifying new account](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-331922557)
- [x] [Freshly created project doesn't show up on "Add Model"](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-332261810)

Logic weirdness:
- [x] [multiple API calls before upload](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-323027566)

UI Oddities:

- [x] [Error message doesn't disappear when error is rectified on fed create tab](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322142307)
- [x] [Default units are not consistent between models and federations](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322145787)
- [x] [Please Check Input???](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322146632)
- [x] [2 letter model names are invalid but it's not obvious](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-322174689)
- [x] [Allow taking screenshot in an issue before typing comment](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-326247960)
- [x] [User Teamspace expanded by default](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-326331497)
- [x] [Deactivate measuring tool when leaving model](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-326338502)
- [x] [Make "New Comment" in issue clickable](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-327162052)
- [x] [Loading wheel never goes away from the Licences page](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-328503129)
- [x] [Select Models/Federation pop up too short](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-328593128)
- [x] [Make Admin radio buttons in models/federations permissions gray](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-329513898)
- [x] [Sort model/federation list alphabetically](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-329531027)
- [x] [Profile shows model owner not who is logged in](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-329550747)
- [x] [Issues: Allow only deleting the last comment, no editing](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-329822135)
- [x] [Issues: Add None to assign list](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-329823543)
- [x] [Rename model not working in settings](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-330182198)
- [x] [Issues: Disable screenshot button if issue closed or viewer permission only](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-330183561)
- [x] Cancelling Edit federation dialog updates UI
- [x] [The prompt re submodel permissions shows up when you are trying to unassign a user](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-332259122)
- [x] [On Model Permissions page, if the project is empty, it is waiting for models forever](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-332259830)
- [x] Typos on signUp and Teamspace page

** Jozef's Bugs **
- [x] [Helicopter icon slow to load](https://github.com/3drepo/3drepo.io/issues/479)
- [x] [New comment field should be sticky at the bottom](https://github.com/3drepo/3drepo.io/issues/473)
- [x] [Search icon should not be inside an issue](https://github.com/3drepo/3drepo.io/issues/483)

** Not Fixing **
- [ ] [User list order is non deterministic](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-332260720)
- [ ] [Show user's job next to username in Permissions page](https://github.com/3drepo/3drepo.io/issues/458#issuecomment-329515483)

**Comment by carmenfan** [comment]
**Billings page hangs forever unless you load the license page first**
- Log in , go to billings page, it will hang forever:
![image](https://user-images.githubusercontent.com/11945337/29264368-b9157974-80d4-11e7-8036-4360757226ce.png)
- You can only get it to load if you go to license page first then go back to billings page:
![image](https://user-images.githubusercontent.com/11945337/29264410-e0d59f52-80d4-11e7-80a7-67ae8fb73100.png)

**Comment by carmenfan** [comment]
**Being a Teamspace admin no longer automatically make you a project admin**
Carmen and James are teamspace admins:
![image](https://user-images.githubusercontent.com/11945337/29264630-be9f5c2e-80d5-11e7-8a05-e7120f7b5020.png)

They should be project admins for every projects as well, with every check box disabled so user cannot alter them.

Should also make sure that:
* someone is assigned an admin, these boxes should populate themselves without refreshing
* when someone is revoked from the admin permission, all those disabled check boxes should be unchecked without refreshing

**Comment by carmenfan** [comment]
**Only teamspace owner is being automatically assigned as model admins**
James is also a teamspace admin, but he's not defaulted as a model admin
![image](https://user-images.githubusercontent.com/11945337/29265132-baa941a0-80d7-11e7-8308-b34a49612e8f.png)

Also, while the line for carmen looks disabled, the user can actually change the permission (even though the changes are not reflected upon refreshing):
![image](https://user-images.githubusercontent.com/11945337/29265200-ffe707ac-80d7-11e7-8773-a4b6904283ce.png)

We should also make sure that project admins are auto model admins.

**Comment by carmenfan** [comment]
What it looks like in production:
![image](https://user-images.githubusercontent.com/11945337/29265466-0857b458-80d9-11e7-8308-65e5cb985d26.png)


What it looks like on dev:
![image](https://user-images.githubusercontent.com/11945337/29265438-ef7aebee-80d8-11e7-9b71-458cfd949b8d.png)

**Comment by carmenfan** [comment]
**Permissions still need cleaning up**
![image](https://user-images.githubusercontent.com/11945337/29265753-1a767628-80da-11e7-82cb-16709b40dcae.png)

There is Create/Delete federation, but only Create model.
At the very least these should match, either have both Create/Delete Federation and Create/Delete Model, or just have "Manage Federation" and "Manage Model". Pavol is in favour of just having Manage *.

We can remove the edit Project from selection really, that only lets you change the name of the project.

**Comment by carmenfan** [comment]
**Error message doesn't disappear when error is rectified**
Trying to create federation with same name, gives error message which is good- 
![image](https://user-images.githubusercontent.com/11945337/29266107-67581e64-80db-11e7-9304-b787f82c8961.png)

When I changed it to a valid name, the save button is enabled, but message doesn't disappear:
![image](https://user-images.githubusercontent.com/11945337/29266123-77a9fb20-80db-11e7-9a3d-076f3f91962b.png)

**Comment by carmenfan** [comment]
**Default units are not consistent between models and federations**
For new model it currently has cm as default units
![image](https://user-images.githubusercontent.com/11945337/29266567-35f091b0-80dd-11e7-9e75-33e6896767a7.png)
But federation has milimetres
![image](https://user-images.githubusercontent.com/11945337/29266585-48fb1000-80dd-11e7-96e0-a9cee7b49ff3.png)

cm isn't really widely used as a units for AEC models, and pavol thinks it's best if we default to mm.

**Comment by carmenfan** [comment]
**Please Check Input???**
![image](https://user-images.githubusercontent.com/11945337/29266692-a7072454-80dd-11e7-9347-08c1728feefa.png)

This stays there until the user has completed every compulsary field. I can see what you're saying is that the user hasn't completed all required fields, but it doesn't really make much sense to the user. There is probably a better way to do this

**Comment by JamesMilnerUK** [comment]
Fixed the PayPal / Billings page issue. Will take a look at the others when I have a moment :smiley_cat:

**Comment by carmenfan** [comment]
Thanks James, I haven't found anything that is really breaking (apart from unable to pay i guess) so it's probably in a good enough state for user testings.

You're on holiday! take it easy!

**Comment by carmenfan** [comment]
**As a project admin I'm not getting permission on the side menu for models**
I'm a project admin of henry's, I can change model permissions through the assign permissions tab, but I can't go straight to that tab with the side menu on the model lines
![image](https://user-images.githubusercontent.com/11945337/29269247-69a39b1e-80e8-11e7-8bcc-d29c641072fa.png)

**Comment by carmenfan** [comment]
**Metadata is no longer switched on by default**
![image](https://user-images.githubusercontent.com/11945337/29270129-21d6f4f2-80ed-11e7-8be5-8b25591956c2.png)

**Comment by carmenfan** [comment]
**Pin should take precedence over measuring tool** 
With both pin and measuring tool enabled, measuring tool functionality is on but pin is off. It should be the other way round.

**Comment by carmenfan** [comment]
**Bugs around multi-select**
* When in multi-select mode, clicking on an already highlighted object should only un-highlight that specific object, it is currently un-highlighting everything.
* highlight several objects -> click on the + to create new issue -> all the highlighting is reset (doesnt' happen if it's single object highlighted)

**Comment by carmenfan** [comment]
**Viewer is borked when you load an earlier revision**
Load a model, then load an earlier revision of the model:
![image](https://user-images.githubusercontent.com/11945337/29270685-d7b157d4-80ef-11e7-819a-6fab76f4cc1b.png)
The older revision looks like this:
![image](https://user-images.githubusercontent.com/11945337/29270707-e8c564c0-80ef-11e7-9592-1650fcc5ab24.png)
* Model settings aren't loaded/hidden as the IFC spaces are showing
* cannot highlight the object/fetch metadata

**Comment by carmenfan** [comment]
**Page doesn't hook up to the chat server upon refresh**
* Load a medium size model
* refresh the page once it's reached the processing page
* You can no longer see the processing icon, but upload has not finished. (i.e. it's not hooking back up to the chat server, or at least not acting like it has

**Comment by carmenfan** [comment]
**2 letter model names are invalid but it's not obvious**
If you name your model with only 2 letters, it's not immediately obvious as to why it's highlighting it as invalid
![image](https://user-images.githubusercontent.com/11945337/29271258-7627335a-80f2-11e7-9104-d12c8df65f64.png)

In fact I never understood why Pinakin decided it has to have a min. of 3 letters. and why it's restricted to hyphen/underscores only. Esp with the new model ID change the user can pretty much have whatever they want as model name.

**Comment by carmenfan** [comment]
**Forgot password page still doesn't work**
Shows the login page if you click into forgot password:
![image](https://user-images.githubusercontent.com/11945337/29366625-6f467acc-8292-11e7-9641-51fe22d87a12.png)

If you hit refresh it shows up below the login tab:
![image](https://user-images.githubusercontent.com/11945337/29366651-7d7409c0-8292-11e7-845b-36bfd56bea51.png)

**Comment by carmenfan** [comment]
**Occasionally components + viewer doesn't load**
Go into a model:
![image](https://user-images.githubusercontent.com/11945337/29366869-15105f54-8293-11e7-81bf-ee30dd0b9307.png)

Keep refreshing, occasionally, the left buttons and viewer doesn't load:
![image](https://user-images.githubusercontent.com/11945337/29366928-350bdc3e-8293-11e7-945f-26544a0b00ee.png)

**Comment by carmenfan** [comment]
**Invalid Revision name when it looks valid**
![image](https://user-images.githubusercontent.com/11945337/29406093-eba0b678-8337-11e7-8bf2-3678b1c433d9.png)
Removing a few characters worked, so there is probably an implicit character limit. 

1. we should give a different error message when it is because of that
2. There's no reason why it has to be so short. we need to extend the length as the user needs it quite a bit longer (maybe 50-100 characters)

**Comment by carmenfan** [comment]
**multiple API calls before upload**
This is not a bug as such but I'm not really understanding what it is doing or why does it need to do that.

When you upload to an existing model, it does an http get on revisions.json and account.json. And I don't see why they need any of that.

The full API is as follows:
* `https://dev.3drepo.io/api/carmen/[object%20Object]/revisions.json` -> returns an empty array
* `https://dev.3drepo.io/api/carmen.json` -> which we have the info already

It then eventually calls upload.

**Comment by carmenfan** [comment]
**Import failure message is stopping user from viewing the previous revision of the model**

![image](https://user-images.githubusercontent.com/11945337/29826305-d4df5264-8cce-11e7-81a7-9f366005e358.png)

The error message doesn't go away and even though there's a working revision for the project, I can't view it.

It makes sense to be there to notify the user that the last error failed, but we need a way for it to go away and let you get on with things. Alternatively, stick to the way it is working in production - the error message flashes up for a few seconds then it disappear.

**Comment by JamesMilnerUK** [comment]
@carmenfan that issue is to do with the frontend checking for a Timestamp which is null on that model for one reason or another. I improved the UX a little around the uploads now though

**Comment by paloknapo** [comment]
Can't delete model. Error: Internal Error
![image](https://user-images.githubusercontent.com/760452/29917289-6c154a2e-8e39-11e7-82b9-3fdf7944d9d1.png)

**Comment by paloknapo** [comment]
**Users deleted with GUI appear in Teamspace Permissions**

![image](https://user-images.githubusercontent.com/760452/29917406-d551f8ca-8e39-11e7-9e0e-b64e30d437da.png)

**Comment by paloknapo** [comment]
**Allow taking screenshot in an issue before typing comment**

The button is disabled until a comment is added. User should be able to take screenshot first and then comment. Or vice versa. 
![image](https://user-images.githubusercontent.com/760452/29917529-2704c3be-8e3a-11e7-9bc6-78fb089f54b8.png)
Display message in bottom toolbar to type something if user hasn't done so before submitting comment

**Comment by paloknapo** [comment]
**Can't deselect multi-selected objects or select other objects when created new issue**

Deselect works once back in list view. Also, sometimes object selection saved with issue doesn't work when issue is opened (ie. https://dev.3drepo.io/pavol/e7fe9e98-7120-4c03-aa6b-fbcfde4c27ef/issues/1594df40-8e2d-11e7-895e-9fc113649c02 )

**Comment by paloknapo** [comment]
**3D Viewer jerks when one card is opened and opening or closing the second card**

**Comment by paloknapo** [comment]
**User Teamspace expanded by default**

Expand user's own Teamspace - Models and Federation. Shared Teamspaces are collapsed. 
This is what users sees when logs in:
![image](https://user-images.githubusercontent.com/760452/29931405-17e6f710-8e69-11e7-86af-5c30e0abdb5b.png)

**Comment by paloknapo** [comment]
**Deactivate measuring tool when leaving model**

Measuring tool is still active even though I left model and I'm back to Teamspace:
![image](https://user-images.githubusercontent.com/760452/29932408-1dc2c530-8e6c-11e7-8963-5ba43008f41b.png)

**Comment by paloknapo** [comment]
**Upload dialog doesn't go away when I hit UPLOAD button**

Upload starts but I have to click X to get rid of the dialog
![image](https://user-images.githubusercontent.com/760452/29978163-e8434408-8f37-11e7-9f9d-00ed37e8e150.png)

**Comment by paloknapo** [comment]
**Make "New Comment" in issue clickable**

Same as "Description" when creating issue.
![image](https://user-images.githubusercontent.com/760452/30061417-2de12048-923f-11e7-9542-2fa0200faff5.png)

**Comment by paloknapo** [comment]
**Missing reset password page**

Reset password email link goes to login instead of reset password page

**Comment by paloknapo** [comment]
**Selected objects not saved with issue**

Selection is cleared once hit + issue button. When object is selected after issue was created it is still not saved with issue.
![image](https://user-images.githubusercontent.com/760452/30204942-29098014-947f-11e7-9608-f3e309670ab2.png)

**Comment by paloknapo** [comment]
**Issues filter reset doesn't show all issues**

When the filter field is empty or reset with the X button list of all issues should appear in the card. This is not happening.
![image](https://user-images.githubusercontent.com/760452/30214160-48912e2c-94a3-11e7-97e5-cc3f1a4066b6.png)

**Comment by paloknapo** [comment]
**Jobs list multiplied in issues menu in federation**

Jobs list is taken from each model which is wrong. Jobs list is on teamspace level and it is the same for any model or federation within.
![image](https://user-images.githubusercontent.com/760452/30217739-fe5bcc7a-94ae-11e7-8331-31dedc3d328a.png)

**Comment by JamesMilnerUK** [comment]
**Revisions sometimes fail to load**

**Comment by carmenfan** [comment]
Partial failures are being shown as Failed to import once refreshed

Import something with a partial failure (missing nodes, missing textures etc). Once it's imported it's showing the right message:
![image](https://user-images.githubusercontent.com/11945337/30231199-b3374fac-94e1-11e7-8419-3edb7afb3007.png)

But if you refresh the page, it shows Failed to import model:
![image](https://user-images.githubusercontent.com/11945337/30231215-ca1da34c-94e1-11e7-81b3-e4a7a884dc7f.png)

Which isn't true , as it's technically a success with warning scenario (there is a new viewable revision in the model).  Ideally we should display the original error message, or just no message at all. As it stands it's pretty misleading to users, especially if they closed the browser and have never seen the original message just thinks the upload failed.

**Comment by paloknapo** [comment]
**Show resolved issues doesn't work**

Issues menu option Show resolved issues doesn't show closed issues.
![image](https://user-images.githubusercontent.com/760452/30271416-16d8b4ee-96e8-11e7-9199-a0b595245287.png)

**Comment by paloknapo** [comment]
**Loading wheel never goes away from the Licences page**

![image](https://user-images.githubusercontent.com/760452/30272764-fcaec116-96ed-11e7-8c0c-d5aeca707c09.png)

**Comment by paloknapo** [comment]
**Unassigned Models notification is not true**

For example, user andrew is assigned as collaborator or commenter on all sub-models but this message still pops up:

![image](https://user-images.githubusercontent.com/760452/30277741-9cf2e35c-9700-11e7-80ef-dda4093f51cd.png)

**Comment by paloknapo** [comment]
**Select Models/Federation pop up too short**

Make the pop up as large as possible if the list of models, federations is long
![image](https://user-images.githubusercontent.com/760452/30286889-16bb6b5e-971b-11e7-911f-dba7b96a68d5.png)

**Comment by paloknapo** [comment]
**Print issues not working**

I get this error:
{"path":"/home/node/3drepo.io/pug/issues.pug","place":"GET /CWCL/04d9ee15-a2af-4ca8-984c-43077c1b42de/issues.html","status":500,"message":"Internal Error","value":4000}

![image](https://user-images.githubusercontent.com/760452/30390264-6f5d6ab2-98ad-11e7-96e8-dc1a5a6dae0a.png)

**Comment by paloknapo** [comment]
**Can't select some objects**

There are objects in model I can't select in 3D viewer, I can select them in tree though and rest of the model is fine. Here are few examples:

https://dev.3drepo.io/pavol/e7fe9e98-7120-4c03-aa6b-fbcfde4c27ef/issues/5dce5c80-992e-11e7-87da-afdd3d0877da

https://dev.3drepo.io/Laika0901/2c773a5e-04cf-4723-af76-c49862ed4a55/issues/475c5170-9869-11e7-973a-574dcd3c7296

**Comment by paloknapo** [comment]
**Make Admin radio buttons in models/federations permissions gray**

Inactive radio buttons should be gray, RGB = 140, 140, 140
![image](https://user-images.githubusercontent.com/760452/30437850-94c849ba-9967-11e7-931a-61d8a24cc450.png)

**Comment by paloknapo** [comment]
**Show user's job next to username in Permissions page**

![image](https://user-images.githubusercontent.com/760452/30438116-4b1f7850-9968-11e7-980a-84379a83fe12.png)

**Comment by paloknapo** [comment]
**Sort model/federation list alphabetically**

![image](https://user-images.githubusercontent.com/760452/30440710-4989eab4-996f-11e7-9460-567d8455eb31.png)

**Comment by paloknapo** [comment]
**Profile shows model owner not who is logged in**

![image](https://user-images.githubusercontent.com/760452/30444002-69c04346-9979-11e7-81f5-673418a78e88.png)

**Comment by paloknapo** [comment]
**Issues: Allow only deleting the last comment, no editing**

Allow user to delete comment made just now. If someone commented after deleting is not possible. Should work as undo when sending email. 

![image](https://user-images.githubusercontent.com/760452/30491675-ec6dd63e-9a35-11e7-897d-6725a2b8a682.png)

**Comment by paloknapo** [comment]
**Issues: Add None to assign list**

For case when user selects a job and decides to un-assign the issue.

**Comment by paloknapo** [comment]
**Issues: Pins of closed issues don't disappear**

Pin should disappear from the model if the issue is closed. Pin appears if "Show resolved issues" from issues menu is active.

**Comment by paloknapo** [comment]
**Rename model not working in settings**

Name field is not active and can't be changed by user.

**Comment by paloknapo** [comment]
**Issues: Disable screenshot button if issue closed or viewer permission only**

**Comment by paloknapo** [comment]
**Cancelling Edit federation dialog updates UI** 

Open edit federation, remove model and hit cancel. Fed list is updated but it shouldn't. Federation doesn't change when opened.

**Comment by carmenfan** [comment]
Pins of submodel issues are being shown when the issue themselves are not shown.

If you open a federation, by default, sub model issues are hidden. At the moment the pins are being shown even though the issues are hidden:
![image](https://user-images.githubusercontent.com/11945337/30805210-5dc24c98-a1e8-11e7-93df-5e4af0e497b4.png)

Those pins should only be shown if sub model issues are shown, which is an option that's within the issues tab:
![image](https://user-images.githubusercontent.com/11945337/30805233-6f466efe-a1e8-11e7-80a8-01e66301e050.png)

**Comment by carmenfan** [comment]
**URL not changing upon verifying new account:**

- Creating a new account and following through with the email verification etc.
- The URL is stuck on registerRequest when you're on the teamspace page. If you go into a model it will get updated with the correct name 

![image](https://user-images.githubusercontent.com/11945337/30817294-697a1f48-a210-11e7-80b9-e097c7e44e6a.png)

**Comment by carmenfan** [comment]
**The prompt re submodel permissions shows up when you are trying to unassign a user**
When you try to set someone to `Unassigned`:
![image](https://user-images.githubusercontent.com/11945337/30872234-49323442-a2e1-11e7-9fb6-12dcc74b4c72.png)

The prompt about needing to add permissions on sub model shows up:
![image](https://user-images.githubusercontent.com/11945337/30872245-51d3ee06-a2e1-11e7-88c8-fa894dbb4abb.png)

Incredibly minor thing: there's a comma at the end of the last model.

**Comment by carmenfan** [comment]
**On Model Permissions page, if the project is empty, it is waiting for models forever**
Select an empty project on the `models and federations` tab in permissions page:

![image](https://user-images.githubusercontent.com/11945337/30872339-a17d1220-a2e1-11e7-9a79-b4b59269ba19.png)
Instead of hanging on "awaiting models/federations", it should just show an empty drop down or a message to say there are no models within this project.

**Comment by carmenfan** [comment]
**User list order is non deterministic**
Seems like for every model the user list can be at a completely random order. Might worth having just a quick sort on the lines:

![image](https://user-images.githubusercontent.com/11945337/30872461-0f5c31fe-a2e2-11e7-8a92-ea6d98bc1283.png)

![image](https://user-images.githubusercontent.com/11945337/30872471-174f6c64-a2e2-11e7-95a5-ea3283e25c85.png)

**Comment by carmenfan** [comment]
**Freshly created project doesn't show up on "Add Model":**
* Create a project:
![image](https://user-images.githubusercontent.com/11945337/30872585-7cf4c4a6-a2e2-11e7-90db-9670feb61dc7.png)

* Try to add a new model, the new project isn't shown:
![image](https://user-images.githubusercontent.com/11945337/30872604-8cb2528c-a2e2-11e7-88f4-ccabd9d9ed42.png)

* It is not visible on add federation either:
![image](https://user-images.githubusercontent.com/11945337/30872612-970fb882-a2e2-11e7-9ddf-307b804f047e.png)
