### ISSUE TITLE
Select the next ticket/issue/risk if the user closed the ticket/issue/risk.

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4585]
### Description
At the moment, if you have a long list of risks/issue/ticket, and you have changed a property that makes it so your currently selected ticket is filtered out, you lose your place in the list when you go back to the details, for e.g:
![img-10-28-23-05-28](https://github.com/3drepo/3drepo.io/assets/11945337/9ea66486-c7d6-4d04-bc4c-53ebf94aa124)

It would be ideal if the next item (or previous if it's easier) is selected in this situation so the user doesn't lose track of where they got to.

### Goals
- [ ] As a user who is going through a list of tickets/issues/risks, I want to be able to close an item out and go back to the item listing without losing my place

### Tasks
- [ ] Modify the ticket list to remember the position
- [ ] When going back keep the position
