### ISSUE TITLE
Show time on dates

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4587]
### Description
In many places (due dates, revision upload time, latest updated time etc), we are not showing the time of the date.

It would be useful if we show the time part of the date in all places where we show the time, for e.g:

![image](https://github.com/3drepo/3drepo.io/assets/11945337/dee232ff-bd47-41bf-91e0-b72b229fb7cd)
![image](https://github.com/3drepo/3drepo.io/assets/11945337/e3a81e12-5337-4d35-ac4a-089f479b4707)
![image](https://github.com/3drepo/3drepo.io/assets/11945337/0a1d32b4-9083-412b-91fb-14c2f16ba9c2)

Naturally we also want to be able to specify the time for a certain due date (i.e. use the date time selector from sequence for any date properties)

### Goals
- [ ] As a user i want to be able to easily identify the exact time of when something has happened/needs to happen
- [ ] As a user I want to be able specify the exact time for a due date within a risk/issue/ticket.

### Tasks
- [ ]  Increase column width to show the time
- [ ] Change the date picker to let user select time also
