### ISSUE TITLE
New clipping box

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4623]
### Description
Because of several complaints by clients we decided to overhaul the clipping box functionality . For doing so we are adding a user interface with buttons to set the differents modes of the clipping tool.

NOTE: this will need to branch off https://github.com/3drepo/3drepo.io/issues/4477 to get the gizmo. Make sure you are using the 2GB viewer to see the latest clipping plane functionality from unity.
 
### Goals
- [ ] Users can create clipping boxes through the toolbar
- [ ] Users can change the mode of the clipping box to resize, move, or rotate through buttons in the toolbar **(scale shouldn't be available in plane mode**)
- [ ] Users can select between box or plane through a button in the toolbar
- [ ] Users can cancel the clipping creation through a button in the toolbar
- [ ] Users can shrink/expand the clipping box/plane based on what objects have been highlighted through a button in the toolbar
- [ ] Users can shrink/expand the clipping box/plane based on what objects have been highlighted through a button in the toolbar
- [ ] Users can flip the clipping plane. (**this shouldn't be available on cube mode**)

### Tasks
- [ ] Add callbacks to unity to set the mode

### Related Resources

- Fixed buttons in the toolbar:
<img width="144" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/d4b1f240-7af8-41f7-aed6-9733d4e100b0">

- Contextual buttons that appears when in clipping mode
<img width="496" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/510622bf-7b3a-4642-b497-d87361b40cc5">

**IMPORTANT** 
- when is in plane mode the rotate gizmo shouldnt appear.
- when is in cube mode the flip button shouldnt appear

General design:
<img width="1055" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/e2fc8f66-f118-413e-96c7-359497c0b986">

[MockUp](https://www.figma.com/proto/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=1900-51556&t=1kPdVdpeEHrt2P06-0&scaling=min-zoom&page-id=182%3A30991&starting-point-node-id=2210%3A51164&show-proto-sidebar=1)
