### ISSUE TITLE
Ability to go to the sequence to today's date as a default behaviour

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4635]
### Description
2 features required on top of #4568 

#### Ability to go to today's date directly without additional clicks
Customers have requested that there should be a default behaviour to be to go to today's date when someone enters a sequence, but to avoid confusing users with change of default behaviour, we want to add toggle on the sequence card list (something like this, consult troy for thoughts on exact placement and look & feel):
![image](https://github.com/3drepo/3drepo.io/assets/11945337/580d107f-c1f2-409d-9ebc-5254972526e4)

It should be clearly visible on the list so the user is aware of it existence, by default it should be on. If it is toggled off, it should behave like now.

#### Display a pop up modal when the today's date falls outside of the sequence range
The behaviour should stay as is, but we should show a pop up to indicate to the user that `Today's date falls outside of the range of the sequence. The nearest date is selected`. This should show if I enter a sequence with `go to today's date` toggled on, or I click on `Go to todays' date` button on the sequence details card.

### Goals
- [ ] As a user I want to be able to go to the sequence and see today's date immediately without needing to perform extra clicks
- [ ] As a user I want to be able to be able to view the sequence from the beginning without it jumping to today's date immediately
- [ ] As a user I want to be notified if today's date falls outside the range of the sequenece

### Tasks
TBC

### Related Resources

MockUp : `link to mockup`
Coda doc: `link to coda`
