### ISSUE TITLE
Toolbar: ability to clear overrides from sequences

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4640]
### Description
Sequences have the faculty of hiding/override geometry.

When a sequence is affecting geometry, the new toolbar is capable of telling when some geometry is hidden and display the relative icons. However, it is not able to tell if some overrides are taking place because of a sequence. Clicking on "clear overrides" does clear them either.

### Goals
- [ ] As a user, I want to be able to clear the overrides no matter what is generating them

### Tasks
- [ ] Find a way to determine if the sequence is overriding geometry and
- [ ] Show the clear overrides button if so
- [ ] Enhance the "clear overrides" button to also clear the overrides generated by a sequence
