### ISSUE TITLE
ModelCacher should manage the web requests

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#4659]
### Description

This is the .io counterpart of https://github.com/3drepo/3drepounity/issues/463

The plan is that in the browser, web requests will be handled entirely in JavaScript, and the responses passed to unity as close to complete as possible (i.e. byte[] arrays for AssetBundle requests, and strings for Json requests).

To do this, the ModelCacher will be re-written to offload more functionality into JavaScript. A class in addition to the IndexedDbCache should be added to interface with the ModelCacher, which will turn into a general request manager.

### Goals

- [x] The viewer issues all web requests through our own web request handler
- [x] The handler can use IndexedDb as a cache
- [x] The cache is configurable

### Tasks

- [x] Write a counterpart to the Unity WebRequestHandler2 that can return fetch responses to Unity
- [x] Update IndexedDbCache to use a Promise-based API
- [x] Update WebRequestHandler2 to use the cache 
- [x] Create all the endpoints to configure the request manager properly
- [x] Add logic to control which calls are cached
- [x] Make sure that ArrayBuffers are moved to the cache worker as [Transferable Objects](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects)

**Comment by sebjf** [comment]
> For 2, we could still cache `supermeshes.json` right? The caller should know if we're fetching a specific revision or not?

Hi @carmenfan, yes I will had the overload to the method used in the place the URL is built, where the viewer needs to figure out what revision or none to add!
