### ISSUE TITLE
Refactor overrides (colored and hidden)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4690]
### Description
It seems that the override system is too complex and hard to extend .If there is something new that supports groups seems to be prone to error. We got to find t a way to simplify it maybe have just one viewpoint. 
After this we can apply the same philosophy to pins/shapes/camera. 

### Suggested solution
We need to stablish clear rules of how overrides works with views, groups and sequences. Then try to find an api that is easy to use throughout all the components.

### Goal
- [ ] Have a unified way of showing the overrides which doesnt require to have special selectors each time
- [ ] Have a simple way to clear overrides for that particular component
- [ ] Have a way to clear all overrides

### Tasks
- [ ] Stablish the rules for overrides
- [ ] Define a simple set of functions for overrides (maybe `setOverride(...args) => override_id` and `clearOverride(override_id)` )
