### ISSUE TITLE
Change sequences to use viewpoints

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4721]
### Description
At the current time we use  selectors to reflect the sequence's  frame state. This causes that we have to manually clear the viewpoint from other components. This is prone to errors and it will make it more consistent to use a viewpoint instead of the selectors. Also we already do this for custom sequences so it will make the code in sequences easier to read. 

### Suggested solution
Get rid of the sequences selectors for reflecting the sequence's frame state and replace it with a conversion of the frame into a viewpoint.

### Goal
- [ ] Have a more consistent code regarding view reflection.
- [ ] Have a more robust code in sequences

### Tasks
 - [ ] Get rid of the selectors for reflecting the frame state
 - [ ] Convert the frame into a viewpoint 
 - [ ] Show the viewpoint when a frame is selected
