### ISSUE TITLE
Status should be shown at all times

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4731]
### Description
With https://github.com/3drepo/3drepo.io/issues/4713, status is now a default property of all custom tickets.

However, it seems like the front end is relying on issue properties to render it instead of taking it from the property list. Therefore currently they are not showing:
![image](https://github.com/3drepo/3drepo.io/assets/11945337/2a967746-6c72-4032-9344-d3c75840eccd)

We need all tickets to show status in accordance to the template. We would also like status to be moved to the left of the issue property strip so it's consistent across all tickets (with and without other issue properties). 

For details see scoping issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/331

### Goals
- [ ] As a user I want to status value of all tickets
- [ ] As a user I want to be able to set an ticket as closed or voided

### Tasks
- [ ] Change ui and move the status to the left in tickets in the details form
- [ ] Show the status in the list regardless that the ticket has issuproperties in config or not
- [ ] Make all tickets use the default property for status 

### Note
Ensure that the tickets uses the same status UI. Atm its probably checking that it has issue properties to render the pill in the list and the the details. so just make every ticket use that ui.

### Images
![image](https://github.com/3drepo/3drepo.io/assets/42032433/0709e6bb-cd8a-4184-870a-b7111c264d3f)
