### ISSUE TITLE
Custom tickets: Customisable status configuration

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4733]
### Description
We want the ability for a user who's creating a template to be able to customise their status.

See details and schema proposal in https://github.com/3drepo/3D-Repo-Product-Team/issues/370

### Goals
- [ ] As an admin of a project, I want to be able to freely define what are my custom ticket status for each ticket template
- [ ] As an admin of a project, I want to be able to define what the custom status means so it can be integrated to existing filters

### Tasks
- [x] Create a statusTypes list that contains the possible status types (0.1 hrs)
- [x] Modify  addTicketTemplate endpoint /teamspaces/{teamspace}/settings/tickets/templates/{template}: payload should accept and validate status property (2 hrs)
- [x] Swagger update for addTicketTemplate (0.1 hrs)
- [x] Modify  updateTicketTemplate endpoint /teamspaces/{teamspace}/settings/tickets/templates/{template}: payload should accept and validate status property (1 hrs)
- [x] Swagger update for updateTicketTemplate (0.1 hrs)
- [x] Modify  getModelTemplates endpoint /teamspaces/{teamspace}/projects/{project}/{type}/{model}/tickets/templates: should include status property in the response in case getDetails query is set to true (3 hrs)
- [x] Swagger update for getModelTemplates (0.1 hrs)
- [x] Modify  getTemplateDetails endpoint /teamspaces/{teamspace}/projects/{project}/{type}/{model}/tickets/templates/{template}: should include status property in the response (1 hrs)
- [x] Swagger update for getTemplateDetails  (0.1 hrs)
- [x] Modify  addTicket endpoint /teamspaces/{teamspace}/projects/{project}/{type}/{model}/tickets: payload validation should ensure status type is valid (3 hrs)
- [x] Modify  updateTicket endpoint /teamspaces/{teamspace}/projects/{project}/{type}/{model}/tickets: payload validation should ensure status type is valid (1)
- [x] Add unit tests (4 hrs)
- [x] Add e2e tests (4 hrs)
