### ISSUE TITLE
Enhance images carrousel

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4735]
### Description
ATM the images carrousel for comment images (and potentially other images) doesn't give you a lot of context to which image you have select what other images are there or give you a quick access to see other images.
To improve this we are changing a bit the image carrousel to show in the lower part a preview of the images and be able to click them and show the full image.

### Goals
- [ ] Users can access the the images easier
- [ ] Users can see how many images and in which image number they are viewing 

### Tasks
- [ ] Update the image carrousel to show the preview on the bottom
- [ ] Add the add `imagenumber of totalimagecount` indicator on the top
- [ ] Add the buttons
- [ ] Add click on the image to show the full image
- [ ] Add actions to delete an image from the comment

### Notes
- For now dont attach any actio to edit markup. That will be address in a separate issue
- The actions for download and delete the image should be somwhat dettached from the component. Through a bunch of buttons passed as props or as `ondownload` `ondelete` props

### Api Notes
In order to delete an image from a comment send the array with the image ids and without the one you want to delete

Example:
Let's say you have image **[ref1, ref2, ref3, ref4]**
 if you want to remove **ref2**, then send **[ref1, ref3, ref4]**

[Reference
](https://www.3drepo.io/docs/#/Tickets/updateComment)

### Related Resources
[MockUp ](https://www.figma.com/file/wIFHoRuWpJtJv9fMDYrdh7/Enhanced-Image-Support?type=design&node-id=32-1786&mode=design&t=aoKkf1MdAxADjuIq-0)

<img width="758" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/9ff857f7-a901-4435-a346-20a17ee96f23">

**Comment by sanmont3drepo** [comment]
@apeitup I think we need to add some mockups for when the images are too many for the preview area and form images with different aspect ratios.
