### ISSUE TITLE
Markup for v5

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4736]
### Description
To continue our task of getting into feature parity with v4 we need the ability to draw in images. 

### Goals
- [ ] Be able to draw in an image 
- [ ] Integrate markdown on ticket images
- [ ] Integrate markdown on ticket comments

### Tasks
- [ ] Reuse the v4 component for image edition without the toolbar
- [ ] Reuse the bottom toolbar with new colours to reflect the ui design and use it to call the v4 component functions 
- [ ] Integrate the component with ticket images
- [ ] Integrate the component with comment images 

### API Notes
For updating the comment images the images array should be sent with all the image ids and with the image the will be replaced in bas64 format using the comment update API.

For example:
Let's say you have image **[ref1, ref2, ref3, ref4]**
if you want to replace **ref2** (markup edit or outright upload)**, [ref1, \<base64 blob\>, ref3, ref4]**

[reference](https://www.3drepo.io/docs/#/Tickets/updateComment)

For updating a ticket just use the normal image ticket api

[reference](https://www.3drepo.io/docs/#/Tickets/updateTicket)

### Related Resources
<img width="364" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/3c0fa5cc-2336-4217-87cb-47ba15c9eda0">

[MockUp](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=1304-2045&mode=design&t=80LUHo6802PgcYvF-0)
