### ISSUE TITLE
Ticket items in list revamp

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4737]
### Description
For making it simpler for users to identify the tickets  (as well as bringing feature parity closer)  we want to show the default image in the ticket list. We also believe that showing the description would be of help. This image comes from the default view property.
Also want to change the selection ui.

### Goals
- [ ] Improve identification of tickets at first glance
- [ ] Improve on the look and feel

### Tasks
- [ ] Apply new selection design
- [ ] Make the item show the default image (from the default viewpoint)
- [ ] Make the item show the description

### Related Resources
[MockUp](https://www.figma.com/proto/yzsLESycxJwhzw4bqLOS0C/3D-Repo-UI-Components?page-id=1%3A38&type=design&node-id=217-12126&viewport=330%2C-2523%2C0.33&t=qXXzgWQmwMN28vDR-1&scaling=min-zoom&starting-point-node-id=217%3A12126)

[Mock up (dev mode)](https://www.figma.com/file/yzsLESycxJwhzw4bqLOS0C/3D-Repo-UI-Components?type=design&node-id=217-11312&mode=dev)

**Comment by sanmont3drepo** [comment]
@carmenfan you think we you are going to add a thumbnail version of the image for the list? Or should we use just the regular image?

**Comment by carmenfan** [comment]
> @carmenfan you think we you are going to add a thumbnail version of the image for the list? Or should we use just the regular image?

considering we limit the image to like 2mb, let's just show the original image (for now)

If it becomes a problem let me know, we can always do something on the backend.
