### ISSUE TITLE
Custom tickets: show customisable status in frontend

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4739]
### Description
For extra flexibility we want to provide the users with the ability for setting up their own status in tickets.
For showing the icons and setting behaviour we will have type of status.

### Goals
- [ ] As an admin of a project, I want to be able to freely define what are my custom ticket status for each ticket template
- [ ] As a user, I want to be able to filter completed tickets on custom ticket statuses.
- [ ] As a user, I want to see the custom status to show a matching symbols

### Tasks
- [ ] Update ui for taking the data from the config
- [ ] Not customizable status should work as before

### Notes
Sample of how the data will come
![image](https://github.com/3drepo/3drepo.io/assets/42032433/041515fd-9923-4342-aae8-94d4a677bdc1)
