### ISSUE TITLE
Custom tickets: Add ability to declare a property as immutable

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4744]
### Description
To add the ability to define a property as immutable.

For details, see https://github.com/3drepo/3D-Repo-Product-Team/issues/375

### Goals
- [ ] As a template creator, I want to ensure that a field that can only be written once cannot be altered
- [ ] As a template creator, I want to be notified if the property field I create is not viable, for example, I should not be able to declare something as both `read only` and `immutable`

### Tasks
Template endpoints
- [x] Amend template create / edit endpoints (teamspaces/{teamspace}/settings/tickets/templates) so that immutable field is supported on properties
- [x] Amend get endpoint  (teamspaces/{teamspace}/settings/tickets/templates/{template}) and make sure it returns immutable fields 
- [x] Amend unit and e2e tests to cover the new cases
- [x] Update swagger on all endpoints

Ticket endpoints
- [x] Amend ticket create / edit endpoints (/teamspaces/{teamspace}/projects/{project}/{type}/{model}/tickets/{ticket}) so that immutable properties can only be set once
- [x] Amend unit and e2e tests to cover the new cases
