### ISSUE TITLE
Date format should be standard

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4761]
### Description
At the moment of writing this issue, we have different dates across the app that use different formatting. For example, the ticket "date" property uses its own formatting system, sequences use something similar, etc.

### Suggested solution
Everything should use the same formatting function to ensure the same output everywhere

### Goal
- [ ] Achieve a standard date display approach

### Tasks
- [ ] Find all the date occurrences across the app;
- [ ] Make sure they all use the same date format
