### ISSUE TITLE
Automatic tests  - Initial configuration 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4763]
### Description
The automatic test ATM can't be run automatically because we dont have an initial dataset. Also mailhog is not running automatically so it has to run manually. 
We need a way to set up a dataset  and run mailhog in order to be able to be run without intervention.

### Suggested solution
Set up a test database that can be reset each time the tests are run. Set local to use mailhog.

### Goal
- [ ] Be able to run automatic tests without intervention

### Tasks
- [ ] Set a database in local for testing and that can have the data reset each time.
- [ ] Set microsoft users for testing.
- [ ] Make local use mailhog
