### ISSUE TITLE
[2D MVP] Milestone 1: Drawings list 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4779]
### Description
As part of milestone 1 we need to show the list of uploaded drawings and provide access to upload and delete more. This page is very similar to containers as it will provide the interface to show the list of files. In another issue it will also provide the list of drawing revisions and the ability to upload  and create new drawings

### Goals
- [ ] As a user, I want to be able to see a list of 100s-1000s of files without performance issues
- [ ] As a user I want to be able to add the drawing to my favourite list 
- [ ] As an admin I want to be able to delete a drawing

### Tasks
- [ ] Add route for the drawings from that project: `/dashboard/{teamspace}/{projectid}/t/drawings`
- [ ] Reusing the components from federations and lists create the lists matching the ui
- [ ] Add the ability to set a drawing as favourite

### Notes
If the backend is not ready for the actions we can mock it in the api files. Just return 

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=5-5981&mode=design&t=pFMWJ4p6AncfMfQy-0)
