### ISSUE TITLE
[2D MVP] Milestone 1: Upload drawings

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4780]
### Description
As part of milestone 1 the user needs to be able to create new drawings and to upload new revisions.
The upload drawing revisions modal consist of a list of files to be uploaded and a dropzone area.
Also there is a form for editing the drawing properties when clicking on "edit button" that will slide from the right.
The items in the file lists consists of:  **Filename** (in icon of file type and the name of the file), **Drawing destination** ( an autocomplete select box with all the drawings and an option to create a new drawing like in containers), **status code**,  **revision code** , **description**, an **edit button** and a **delete button**

- clicking on upload file or droping files will create file entries in the list
- Clicking on the **edit button** in a file entry will display the drawing edition form on the  right. In case of existing drawings it will be all readonly and in case of new drawings it will be editable
- If the user (as **admin**) is creating a new **Drawing destination** after entering the name , clicking enter on "add new drawing",  taking focus of the field or pressing enter will open (if its not open already) the edit drawing form on the right. The form will be filled with the new drawing name and validate all necessary values, 
- Validation on the edit drawing form will be the same as in #4782
- If the user fails to fill in valid values on the edit drawing form then the value on the select box will be invalidated making the whole file list invalid and the upload button disabled.
- If the user is a **collaborator** the new drawing destination option will not be available
- Once the user have filled the upload form with valid data the **upload files** button will be enabled. After clicking the **upload files** button the form will change into a progress list of files being uploaded (like in containers) 

### Goals
- As a admin/collaborator I want to be able to upload a new revision to a drawing

### Tasks
- [ ] Create upload revision dialog
- [ ] Ensure the file upload dialog supports +100 files with acceptable performance
- [ ] If #4779 is done wire in the onclick to the upload button. If not just add the buttons without any type of design just to trigger the modal.
- [ ] Validate that the combination of revision code and status code is unique

### Notes on permissions:
- **Admin** is project admin
-  **collaborator** is a **drawing collaborator** (which you can grant using the users permissions page after #4789 )

### Notes
- Refactor the components of upload containers to be reusable for this feature and for upload containers to keep on working as it does today.
- If the backend is not ready for the actions we can mock it in the api files. 
Just return hardcoded data and put in a little delay to mimic  the backend delay.

### Related Resources
[MockUp upload](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=2-1833&mode=design&t=pFMWJ4p6AncfMfQy-0)
