### ISSUE TITLE
[2D MVP] Milestone 1: Drawings route & redux state

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4781]
### Description
For supporting #4780 and #4779 we need a route in which we can build the drawings management feature

### Goals
- [ ] As a user I want to access drawings management

### Tasks
- [ ] Add route for the drawings from that project: `/dashboard/{teamspace}/{projectid}/t/drawings`
- [ ] Add a empty component which will be replaced by the drawing list afterwards
- [ ] Add a redux state for selecting the drawings. **(schema TBD)**
- [ ] If the backend is not ready yet you can hardcode a bunch of drawings
