### ISSUE TITLE
[2D MVP] Milestone 1: New drawings/Drawings settings

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4782]
### Description
As part of milestone 1 the user needs to be able to create new drawings. 
It consists of a modal only accessed by the admin that will be trigger by a button in the drawings management page. 
- The fields of the modal are **Name**, **Drawing Number**, **Category** and **Description** .
- **Name**, **Category**  and **Drawing Number** are required fields.
- **Category** select box is filled with the categories from an API endpoint **(TBD)**
- **Drawing number** is a unique string throughout the project, it will trigger an error if entered an already existing **Drawing number**. The format is alphanumberic + '_' + '-' without spaces.

Once the user filled a valid  form `create drawing` button is enabled , and api request is posted and the new empty drawing appears in the list.

With an existing drawing the user can see the properties of the drawing. If the user is an admin these properties will be editable if not everything in the form is read only and no **save changes** button is shown.

### Goals
- As an admin, I want to be able to create drawing entries so collaborators and admins can upload their files.
- As an admin I want to specify properties of the drawing so they can be easily identified.
- As an admin, I want to be able to edit these properties

### Tasks
- [ ] if #4779 is done wire it there else create a button without styles to trigger a **new drawing modal**
- [ ] if #4779 is done wire it there else create a button without styles to trigger a **drawing settings modal**
- [ ] Create redux actions for creating a new drawing
- [ ] Create the api for creating a new drawing **(TBD)**
- [ ] Create the modal.
- [ ] Create validators for the modal
- [ ] Dispatch the appropiate action to create the drawing, the drawing should appear on the list

### Notes
- If the backend is not ready for the actions we can mock it in the api files. 
Just return hardcoded data and put in a little delay to mimick  the backend delay.
### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=8-43844&mode=design&t=pFMWJ4p6AncfMfQy-0)

**Comment by carmenfan** [comment]
Merged into #4781
