### ISSUE TITLE
Custom tickets - Readonly for UI & unique property in templates

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4784]
### Description
For supporting new features (#4777) we need to add `readOnlyOnUI` and `unique` configuration for properties in custom tickets. 
- `readOnlyOnUI` from the frontend standpoint is identical to `readOnly`. Both configs applies.
- `unique` will add a validation to ensure that the value from that property is not repeated throughout all the tickets of that type that belongs to the container (or federation).

### Goals
- [ ] Users see `readOnlyOnUI` properties as readOnly
- [ ] Users can interact with `unique` properties and have them validated 

### Tasks
- [ ] In template selector replace `readOnly` with the value `readOnlyOnUI || readOnly`
- [ ] In the ticket form add a validation for testing the uniqueness of `unique` properties and provide an error message when that happens.

### Template schema
```` js
{
  properties: [
    // This property will be read only on the UI, but editable via the API
    {
        name: "my property",
        type: "text",
        readOnlyOnUI: true
    }
    // This property will be validated against existing tickets of the same template and ensure the value is unique
    // If value is undefined, the check will not happen.
    {
        name: "my property",
        type: "text",
        unique: true
    }
    // This property wll not be editable on the UI, and it has to be unique.
    {
        name: "my property",
        type: "text",
        unique: true,
        readOnlyOnUI: true
    }
    
  ]
//other ticket template values
}

````
