### ISSUE TITLE
Custom tickets: Additional traits for properties

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4785]
### Description
For https://github.com/3drepo/3D-Repo-Product-Team/issues/301, we need a few additional traits to be defined for properties.

- `readOnlyOnUI:<boolean>` - the front end, plugins ticket view will treat this property the same as any readOnly: true property
- `unique:<boolean>` - if true, the value has to be unique across all tickets.

Read https://github.com/3drepo/3D-Repo-Product-Team/issues/389 for details.

#### ReadOnlyOnUI
This is a "guidance" configuration and the responsibility of making it read only will lie completely on the front end. There is no validation on this property trait when we are validating new ticket/ ticket updates.

The role of the backend is just to ensure we understand this when the user create/edit a ticket schema.

#### Unique
If a property is unique, then we should be validating any value within the property to ensure that, any other ticket under the same template does not already contain this value.

e.g. If I have 2 tickets, with a property `prop` declared is unique on both `template 1` and `template 2`:

- This should not happen:
````
Ticket 1: { template: "template 1", property: { prop: 1 } }
Ticket 2: { template: "template 1", property: { prop: 1 } }
````

- But this can happen
````
Ticket 1: { template: "template 1", property: { prop: 1 } }
Ticket 2: { template: "template 2", property: { prop: 1 } }
````

Unique configuration **cannot** be applied to the following property types: 
- longText
- boolean
- image
- measurements
- coords

### Goals
- [ ] As a ticket template creator I want to ensure some properties cannot be edited by end users when they are managed by integration scripts
- [ ] As a ticket template creator I want to ensure some fields are unique across all tickets of the same template.
- [ ] As a commenter I want to be told if I am putting in a duplicated value on a unique field
- [ ] As a commenter I should be able to put a duplicated value in a unique field if they are from 2 different templates.

### Tasks
- [x] Modify Add, Edit Template endpoints to allow the creation of readOnlyOnUI and unique properties (1 hr)
- [x] Edit Get Template endpoint to allow the fetching of readOnlyOnUI and unique properties (0.5 hr)
- [x] Update swagger docmentation for template endpoints (0.5 hr)
- [x] Add unit tests for all template endpoint changes (1 hr)
- [x] Add e2e tests for all template endpoint changes (1 hr)
- [x] Modify Add, Edit ticket endpoints to ensure there are no duplicate values in a unique property (3 hrs)
- [ ] Add unit tests for all ticket endpoint changes (1 hr)
- [x] Add e2e tests for all ticket endpoint changes (1 hr)
