### ISSUE TITLE
[2D MVP] Milestone 1: Drawing revisions list

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4788]
### Description
Milestone 1 of the drawing features will have to provide the ability of managing revisions. Copying the same functionality as from containers, users will be able to see the list of revisions and users with permissions will be able to void/un-void revisions.
This issue depends on #4779 

The list of revisions will be displayed after clicking on an item in the drawing list. 

- If the user is not a collaborator or admin **active/void** button will not be displayed

### Goals
- As a collaborator, I want to be able to declare a revision as void if I have made a mistake
- As a collaborator, I want to be able to un-void a revision if I mis-clicked.

### Tasks
- [ ] Modify drawing list to add the revisions list following the UI in the mockup
- [ ] Add void/unvoid API files
- [ ] Add fetch revisions API files

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=38-13027&mode=design&t=tuv30jdyJ3MIH6Vm-0)
