### ISSUE TITLE
[2D MVP] Milestone 1: Drawing permissions

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4789]
### Description
For milestone 1 we want to re-use the permissions from federations/containers. This means we have to add the drawing list in the list together with containers and federations

### Goals
- As an admin, I want to specify who has the right to upload new drawings (collaborators)
- As an admin, I want to specify who has the right to view a drawing. (viewers)

### Tasks
- [ ] Modify the user permissions to have drawings also
- [ ] Add API to get the users permissions for drawings
- [ ] Add API to modify the user permissions for drawings
- [ ] Modify user permissions to post the changes for drawings

### Related Resources
<img width="1124" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/9073472f-3b95-4e71-9c0d-b22f48fcf605">
