### ISSUE TITLE
Custom ticket: New preset module - Clash

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4804]
### Description
As part of https://github.com/3drepo/3D-Repo-Product-Team/issues/301, we need 2 things:
- A preset module for clash
- A default ticket template for storing clash detection

Details of the schema is recorded in As part of https://github.com/3drepo/3D-Repo-Product-Team/issues/301

#### Note:
The following features are required for this template to fully function:
- https://github.com/3drepo/3D-Repo-Product-Team/issues/370
- https://github.com/3drepo/3D-Repo-Product-Team/issues/375
- https://github.com/3drepo/3D-Repo-Product-Team/issues/389

### Goals
- As a user of an existing teamspace, I want to be able to utilise the Sync clash facility straight away without creating a ticket template
- As a user of a bew teamspace, I want to be able to utilise the Sync clash facility straight away without creating a ticket template
- As a administrator of a teamspace, I want to be able to define my own template with the ability to sync clash results

### Tasks
- [x] Add Preset module `clash` into the template schema
  - [x] Update swagger
- [x] Add a default template when a teamspace is initialised
- [x] Write a migration script to add default template to existing teamspaces
- [x] Add tests
  - [x] Ensure we have a test that default template being added is a valid schema
