### ISSUE TITLE
Keep props up to date when dispatching a modal

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4823]
### Description
When dispatching a modal using an action you pass the props, but this props are "static". Which means the value never gets updated. In some cases we want those props to be updated. 

### Suggested solution
Create a hook to keep the props up to date

### Goal
- [ ] have a unique and practical way to dispatch the modals and to keep the props up to date

### Tasks
- [ ] create the hooks
- [ ] integrate it with the modal
