### ISSUE TITLE
[2D MVP] Milestone 1: Backend integration

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4826]
### Description
We need to integrate the api calls with the actual backend. 

### Goals
- [x] Users will see realtime updates when navigating the page
- [x] Users will see the changes after refreshing the page

### Tasks
 - [x] Add realtime suscriptions 
 - [x] Replace mocked api calls with the actual calls
 - [x] Update schemas if necessary
 - [x] Add saga/redux tests
