### ISSUE TITLE
[2D MVP] Milestone 2: Basic 2d viewer

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4827]
### Description
The first version should support the basic stuff to be functional.  Load an image, zoom and pan.
If the 

### Goals
- [ ] Users are able to see a 2d drawing
- [ ] Users are able to pan/zoom a 2d drawing 

### Tasks
- [ ] Create a component `DrawingViewer` which would have the prop drawing passed to it
- [ ] Create the toolbar with the zoom+/zoom- buttons
- [ ] Make the component pan / zoom

### Notes
- Create a test route for showing DrawingViewer 
- In the mock up there is a (+) button, that's for calibration. Dont add that to the toolbar.

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=143-28437&mode=design&t=GuDzXNJlxwU9N18x-0)

**Comment by carmenfan** [comment]
Merged into Main issue #4833
