### ISSUE TITLE
[2D MVP] Milestone 2: Split viewer

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4828]
### Description
The viewer should be split when showing the 2d view on the right and the 3d view on the left. 
When is open there is a way to change the ratio between the 3d and 2d view.

- A handle will appear when you hover over the division line .
- The division line changes colour when hovering over it , it will also show the handle in the height position matching the hover. When dragging the colour changes to a dark blue

### Goals
- [ ] Users can split the view into 2 
- [ ] Users can change the ratio between the 3d and 2d view.
- [ ] Users can can close the 2d view 

### Tasks
- [ ] Create ViewerSplit and Split component with the 3d view on the left  
- [ ] Create ViewerSplitContext  that will be inside viewersplit, will provide the context to open or close the side view (this could also be a redux state thing)

### Notes
The code will end up something like this
```
<ViewerSplit>
    <Split name="3d"><3dviewer..></Split>
    <Split name="2d"><2dViewer ..></Split>
</ViewerSplit>
```
### Related Resources

- The division line matches the colours here (inactive/hover/dragging):
[Handle states](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=491-14545&mode=design&t=GuDzXNJlxwU9N18x-0)

 
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=11-65520&mode=design&t=GuDzXNJlxwU9N18x-0)
