### ISSUE TITLE
[2D MVP] Milestone 2: Drawings card

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4829]
### Description
For selecting a drawing and showing it in the 2d viewer we need a list of all the drawings in a new drawings card. When clicking an item the 2d viewer is triggered and loads the selected viewing. 

### Goals
- [x] Users can see all the viewings for the project within the viewer
- [x] Users can see a list of 100s-1000s of files without performance issues
- [x] Users can select a drawing for viewing 

### Tasks
- [x] Create a new card and new button for accessing it on the viewer
- [x] Show all the projects drawings following the design 

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=38-14984&mode=design&t=OqGPJ7jNoNPrxtzW-0)
