### ISSUE TITLE
[2D MVP] Milestone 1

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4830]
### Description
This is the base branch for 2d milestone 1 
dependencies:
- [x] https://github.com/3drepo/3drepo.io/issues/4781
- [x] https://github.com/3drepo/3drepo.io/issues/4779
- [x] https://github.com/3drepo/3drepo.io/issues/4780
- [x] https://github.com/3drepo/3drepo.io/issues/4788
- [x] https://github.com/3drepo/3drepo.io/issues/4789
- [x] https://github.com/3drepo/3drepo.io/issues/4782
- [x] https://github.com/3drepo/3drepo.io/issues/5023
- [x] https://github.com/3drepo/3drepo.io/issues/5024
- [x] https://github.com/3drepo/3drepo.io/issues/4985
- [x] https://github.com/3drepo/3drepo.io/issues/5080
- [x] https://github.com/3drepo/3drepo.io/issues/4826
- [x] https://github.com/3drepo/3drepo.io/issues/4898
- [x] https://github.com/3drepo/3drepo.io/issues/4901
- [x] https://github.com/3drepo/3drepo.io/issues/4983
- [x] https://github.com/3drepo/3drepo.io/issues/5126
- [x] https://github.com/3drepo/3drepo.io/issues/5127
- [x] https://github.com/3drepo/3drepo.io/issues/5128
- [x] https://github.com/3drepo/3drepo.io/issues/5129

### Goals
- [x] As an Admin I want to Upload/delete their Drawings
- [x] As a user with access to the drawing I want to view the revision history of the drawings
- [x] As an admin I want to manage permissions on each drawing.

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=5-5981&mode=design&t=ATm59VQXYC23fw9g-0)

**Comment by The-Daniel** [comment]
The search highlight in dashboard list item titles is now broken up by gaps

![image](https://github.com/user-attachments/assets/4835a0a4-bc44-4035-8376-73151517797c)


![image](https://github.com/user-attachments/assets/85ea6ded-8f61-435c-81b6-60a4334dff8d)

From the Title styling in `dashboardListItemTitle.styles.ts`. In #5024 this section was changed from `a { (...) }` to `* { (...) }` so now it applies to the broken up sections. The `padding-right: 10px;` is responsible for the gap
![image](https://github.com/user-attachments/assets/4c3a1e3c-f126-4113-a3ad-5f76e6b3bb31)
