### ISSUE TITLE
Custom Tickets Icons to use 'SHEW' Symbols

### ISSUE THREAD

**Issue by jamie-iskander** [3drepo/3drepo.io#4831]
### Description
 Custom ticket icons to include the 'SHEW' (Safety, Health, Environment and Wellbeing) symbols used by the Environment Agency on their jobs. 

### Goals
 
- [ ] As a user, I want to create a new Custom Ticket and have the icon correspond to the type of risk. 
- [ ] As a user, when I choose the the _type_ of ticket the icon changes to match the corresponding symbol and make it clear to all users what type of hazard / risk is in that area. 
- [ ] As an Admin, I want to be able to control which symbols appear in the tickets and set this up at a global level. 

### Tasks

- [ ] TBC

### Related Resources

Link to Environment Agency SHEW guidance chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.ada.org.uk/wp-content/uploads/2023/02/LIT-16559-Safety-Health-Environment-and-Wellbeing-SHEW-Code-of-Practice.pdf
Hazard pictograms: https://www.hse.gov.uk/chemical-classification/labelling-packaging/hazard-symbols-hazard-pictograms.htm
