### ISSUE TITLE
[2D MVP] Milestone 2: 2D screenshot 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4832]
### Description
We want to be able to create tickets with screenshots of the 2d viewer. For that we need to be create a component that can take a screenshot of the svg using canvas2d. 
- In custom tickets there will be a new take 2d screenshot and take screenshot renamed to take 3d screenshot
  - If the the 2d view is opened then take 2d screenshot will be available. After taking the screenshot markup will open to change it as needed
  - If the 2d view is closed take 2d screenshot is disabled and a tooltip will appear explaining to the user that user needs to open a drawing first to take a 2d screenshot
- The screenshot will take in consideration zoom/pan of the 2d view.

### Goals
- [ ] As a commenter+ (of the model), I want to be able to choose whether I am taking a screenshot of the 2D or 3D viewer when I'm filling in a custom ticket

### Tasks
- [ ] Using  canvas2d create a function for passing a url of a svg/png , size and zoom/rect to create a screenshot 
- [ ] In images in tickets add the 2d screenshot option 

### Related Resources
<img width="408" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/4e6dd2cc-abb6-433a-84d4-da1235661293">
