### ISSUE TITLE
Measurement - Angles and Polylines

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#4835]
### Description

This is for the frontend changes for https://github.com/3drepo/3D-Repo-Product-Team/issues/394 - support for PolyLine and Angle measurements.

### Goals

- [ ] As a user, I should be able to snap against two lines and create an angular measurement between them (regardless of angle)
- [ ] As a user, I should be able to draw multiple points as a polyline (without bends) and determine the straight distance along the entire line.
- [ ] Angle measurements should show up in the measurements list

### Tasks
- [x] update icons
- [x] Create polyline listitem
- [x] Wire up polyline to unity
- [x] Add polyline to measurements
- [x] Add polyline to measurements in issues
- [x] Add polyline to measurements in risks
- [x] Create angle listitem
- [x] Wire up angle to unity
- [x] Add angle to measurements
- [x] Add angle to measurements in issues
- [x] Add angle to measurements in risks

### Related Resources

Product Team Ticket: https://github.com/3drepo/3D-Repo-Product-Team/issues/394
Unity Ticket: https://github.com/3drepo/3drepounity/issues/516

[Angle Mockup](https://www.figma.com/file/tmkgqJQlhjV8oUdhQwkHzr/Measurements?type=design&node-id=30-102&mode=design&t=Mt3AX4q4kL6rKi5j-0)
[Polyline Mockup](https://www.figma.com/file/tmkgqJQlhjV8oUdhQwkHzr/Measurements?type=design&node-id=30-139&mode=design&t=wZiFEV7SU6Q0XIpx-0)
