### ISSUE TITLE
[2D MVP] Milestone 2: backend integration

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4841]
### Description
We need to integrate the api calls with the actual backend. 

### Goals
- [ ] Users will see realtime updates when navigating the page
- [ ] Users will see the changes after refreshing the page

### Tasks
 - [ ] Add realtime suscriptions 
 - [ ] Replace mocked api calls with the actual calls
 - [ ] Update schemas if necessary

**Comment by sanmont3drepo** [comment]
Merged into base branch
