### ISSUE TITLE
[2D MVP] Milestone 3

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4897]
### Description
Base issue for milestone 3
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/379

dependencies:

- [x] https://github.com/3drepo/3drepo.io/issues/4857
- [x] https://github.com/3drepo/3drepo.io/issues/4906
- [x] https://github.com/3drepo/3drepo.io/issues/4907
- [x] https://github.com/3drepo/3drepo.io/issues/4908
- [x] https://github.com/3drepo/3drepo.io/issues/4909
- [x] https://github.com/3drepo/3drepo.io/issues/4942
- [x] https://github.com/3drepo/3drepo.io/issues/4910
- [x] https://github.com/3drepo/3drepo.io/issues/4993
- [x] https://github.com/3drepo/3drepo.io/issues/4941
- [x] https://github.com/3drepo/3drepo.io/issues/4911
- [x] https://github.com/3drepo/3drepo.io/issues/5044
- [x] https://github.com/3drepo/3drepo.io/issues/5064

### Goals
- [ ] As a collaborator, I want to be able to easily see which drawing requires calibration
- [ ] As a collaborator, I want to calibrate a drawing against any model I have access to
- [ ] As a collaborator, I want to be able to re-calibrate a drawing if I feel it is out of synced
- [ ] As a collaborator, If a new revision of the drawing has been uploaded, it should take the calibration from the previous revision of the drawing
- [ ] As a collaborator, I want to know if the drawing is calibrated with an older revision so I can verify if the calibration values are still correct
- [ ] As a collaborator, I am able to manually calibrate my drawings which is simplified by snapping to objects in the model to enhance accuracy.
- [ ] As a collaborator, I want to be able to only tweak the necessary values when I'm trying to recalibrate. i.e. do not make do a calibration from scratch, show me the values and I can adjust them accordingly.
- [ ] As a collaborator, I want to be able to recalibrate a drawing from the drawing list in the 3D Viewer
- [ ] As a collaborator, I want to be able to confirm a drawing's calibration from the drawing list in the 3D Viewer

### Related Resources
[Mockup](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=2%3A39&mode=design&t=NsRszpgyRNsSIoIw-1)

**Comment by The-Daniel** [comment]
At the moment the 3D calibration start and end point cannot be the same for obvious reasons, however there is nothing stopping a user from using a perfectly vertical vector. Since the x and y coordinates are the same you run into a divide by zero problem when trying to transform the 2D vector into the 3D one.
![image](https://github.com/user-attachments/assets/2a76c8b7-bb15-469e-9012-4dca6cbee568)
![image](https://github.com/user-attachments/assets/b358337b-a3ef-4c02-9864-79af7f6b5261)

**Comment by sebjf** [comment]
Hi @sanmont3drepo, a random suggestion (sure you appreciate these coming in now 😄 ) but in the 2d viewer, right clicking brings up the context menu. 
I notice it because the 3d viewer uses the right mouse button to navigate, so we train the user to use the right mouse button on the left, but when they instinctively do the same thing on the right, the menu interrupts them. 
Not sure if there's an easy way to turn it off.
