### ISSUE TITLE
[2D MVP] Milestone 1: Ensure permissions in drawings are being enforced

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4898]
### Description
We need to ensure that the permissions are being applied correctly and getting the data from the right source (check the selectors).

### Goals
- [ ] As an admin, I want to be able to create drawing entries 
- [ ] As a collaborator or admin, I want to upload files.
- [ ] As an admin, I want to be able to edit drawing properties
- [ ] As an admin, I want to be able to remove a drawing that is no longer applicable
- [ ] As a collaborator or admin, I want to change the void status of revisions
- [ ] As an admin, I want to change the permissions of a user to a drawing

### Tasks
- [ ] Ensure that the **new drawing** button is only available for project or teamspace admins
- [ ] Ensure that **upload files** button is only available for project or teamspac eadmins and drawing collaborators
- [ ] Ensure that **upload files** item  in hamburger menu  is only available for project or teamspace admins and drawing collaborators
- [ ] In the upload form, for collaborators, the **destination** field doesnt allow for creating a new drawing
- [ ] In the upload form, for collaborators, the **destination** field should only be populated with the drawings in which that user has collaborator permissions
- [ ] Ensure that **settings item** in hamburger menu is only available for project or teamspace admins 
- [ ] Ensure that **delete** item in hamburger menu is only available for project or teamspace admins 
- [ ] Ensure that **void** button in the revision item is only available for project or teamspace admins and drawing collaborators
- [ ] Ensure that **void** button in the revision item is read-only for for viewer and commenters (not admins and not collaborators)
