### ISSUE TITLE
[2D MVP] Milestone 3: Calibration steps skeleton+routing

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4906]
### Description
As groundwork we need a way to access the calibration pages so we can implement the functionality. This issue doesnt concern with design; just the route, showing a step progress (can be very crude) and a space in which the different steps of calibration are shown.

### Goals
- [ ] Users can access a route to calibrate their drawings.

### Tasks
- [x] For selecting the container/federation show a modal dialog displaying
- [x] Add a frontend route   ``v5/viewer/{teamspace}/{projectid}}/{containerId}/{revisionId}/calibration?drawing={drawingid}``
- [x] Add link from the drawing list to calibrate it.
- [x] Add mechanism (for now lets use context) for changing steps
- [x] Add Back/Cancel/Next buttons
- [x] The next button should only be enabled if the data in the content is valid
- [x] The back button should be enabled if it's not the first step
- [x] Cancel should always be enabled and go back to the page that triggered  the calibration wizard
- [x] Add select container/federation page skeleton
- [x] Add 3d point step page skeleton
- [x] Add 2d point step page skeleton
- [x] Add vertical spatial boundaries page skeleton page 
- [x] Add confirmation page skeleton page 

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=202-14332&mode=design&t=V5ZeaWfoqHoeg4bS-0)
