### ISSUE TITLE
[2D MVP] Milestone 3: Calibration steps apply design

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4907]
### Description
#4906 addresses  functional skeleton of the steps, while in this issue is about making it nice to look at.

### Goals
- [ ] As a collaborator/admin I want to follow the calibration steps with a nice ui  a drawing with a nice UI

### Tasks
- [ ]  Apply the design from the mockup
- [ ] Add a confirmation message when clicking "Cancel"

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=202-14332&mode=design&t=q47f98fNuLWkluFj-0)

**Comment by carmenfan** [comment]
merged into #4897
