### ISSUE TITLE
[2D MVP] Milestone 3: Federation/container selection for calibration

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4908]
### Description
Before starting calibration the user needs to select a container or federation to use for calibration.
- If the user is calibrating from within a container/federation then the selected container/federation is the one from which the calibration action is triggered
- If calibration is triggered from the drawing list, it shows this modal

The selection is a modal with a form that consists
of two fields
- The selected drawing
- The container/federation list (we should reuse the component from tickets table)

### Goals
- [ ] As a user calibrating a drawing I want to select a container/federation as a calibrating entry

### Tasks
- [ ] Show the selected drawing
- [ ] Reuse the tickets table container/federation list but make it single select
- [ ] Make the next button enabled once the user has selected a container/federation

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=202-14332&mode=design&t=Enls6PK3bsy73fO6-0)
