### ISSUE TITLE
[2D MVP] Milestone 3: Step 1 - 3D calibration points

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4909]
### Description
For calibrating the 2d drawing with the 3d drawing we need to find a way to transform 3d points into 2d points (and vice versa). 
- In this step we are creating a 3d vector in the viewer to be mapped to a 2d vector in next step. 
What we see here is a split view between the 3d and the 2d viewer.
- In the 3d side we have a limited version of the sidebar and a special version of the toolbar.
- Mesh selection should be disabled in this viewer.
- If this is a re-calibration we'll use the data from the previous calibration

<details>
  <summary> Sidebar</summary>
 
 Though in the mockup we can see different icons (**don't implement them**)  the  icons showing are
  **Groups**,  **Views** and **Tree**. So these are the cards that should be working on this 3d vector step. 
  If the sidebar code is too complicated we should aim to refactor it and make it simple.

</details>

<details>
  <summary> Tool bar</summary>

  The toolbar is somewhat simplified also,  consisting of  **Home**, **Perspective/Ortographic view**, **Turntable/Helicopter view**,  **sectioning**, **attribute data**. All of these should work as the are working currently in the viewer. We should create a new toolbar, reusing the buttons that we already have.

  There are also a new button  
###   (note: the vertical boundaries button shouldn't be there, it's wrong in figma):
  
  <img width="232" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/bce6466e-b9d0-477f-afdf-60ffe2d7e20d">
  
  - **Calibration vector** : when activated this button sets the viewer in a Vector mode. there also a couple of buttons that appears in the _subtoolbar_ to manage the  start and end points of the vector. 
  They are disabled while there is no vector defined.  When the user defines the start point the "clear start" button gets enabled and when the end point is the defined the "clear end" buttons is enabled. 
  Clicking on each of this buttons will delete its corresponding point from the vector
  
  Once its activated the user will define a vector in the 3d viewer. If the vector has been defined then the "Continue" button is enabled in the steps bar.
    
</details>

<details>
  <summary> 2d view </summary>
  
  It should only have *zoom in* and *zoom out* buttons

</details>

<details>
  <summary> Unity integration </summary>
  
  When clicking the "calibration vector" button  two things must happen
  
  1. Enable snapping by calling  _UnityUtil._**enableSnapping()** . 
  2. Set the calibration mode by calling _UnityUtil._**setCalibrationToolMode('Vector')** .
  3. If this is a recalibration use  _UnityUtil_.**setCalibrationToolVector(startPoint, endPoint)**  with **startPoint** and **endPoint** from the saved calibration. So the continue button will be available.

  
  The user is then abled to click on the model, create the start point and then click again and create the end point.
  
  When the user places either end of the vector, the viewer will call `UnityUtil.calibrationVectorChanged`. This method will be passed an object containing the start and end points of the vector, like so:
  
  ```
  {
      "start": [
          -0.18804311752319336,
          0.999995231628418,
          0.25510096549987793
      ],
      "end": []
  }
  ```
  The arrays will be the 3D positions of that end in Project coordinates, or empty, depending on whether that end has been specified yet.
  
  - For clearing the start point  _UnityUtil_.**setCalibrationToolVector(null, endPoint)**
  - For clearing the end point  _UnityUtil_.**setCalibrationToolVector(startPoint, null)**
</details>

<details>
  <summary> Calibration format  </summary>

```js
  {
    // this will most likely live in the drawing history
    calibration: {
        horizontal: {
            model: [[0,0,0], [1,1,1]],
            drawing: [[0,0], [1,1]]
        },
        verticalRange: [ 0, 10],
        // considering different container can be in different units we'd need to make sure we know how to scale it when viewing on a different model.
       units: "m"
     }
}

When showing the calibration take in consideration that the units might be different from the units in the container. Calculate to compensate if necessary.

```

</details>

### Goals
- [ ]  As a calibration user I want to be able to create a 3d vector for calibration

### Tasks
- [x] Make this component appear when in the "3d calibration points" step
- [x] Create/update sidebar with the allowed functionality for this step.
- [x] Create a toolbar for calibration
- [x] Update the viewer with the new unity functions
- [x] If this is a recalibration call _UnityUtil_.**setCalibrationToolVector(startPoint, endPoint)** with the previous calibration data 
- [x] Trigger UnityUtil.setCalibrationToolMode('Vector') when clicking in the calibration vector button and enable snapping
- [x] "Save" somewhere the created vector 
- [x] Enable/disable the continue button in the steps bar matching the vector state.
- [x] Add help box on top (look at design)

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=143-28437&mode=design&t=7bXLKF16hA7XqUeP-0)

**Comment by sanmont3drepo** [comment]
Merged into #4897
