### ISSUE TITLE
[2D MVP] Milestone 3: Step 2 - 2D calibration points

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4910]
### Description
This issue is to address step 2 in calibration wizard.  This defines the 2D vector in the viewer,
based on #4909, it should show a split screen.  The sidebar in the 3d view is the same as the step before.
The toolbar  consists of  **Home**, **Perspective/Ortographic view**, **Turntable/Helicopter view**,  **sectioning**, **attribute data**. 

Depends on #4941 and #4942.

<details>
   <summary> 2d viewer </summary>
 
 In the toolbar there is now a calibration button
<img width="47" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/acdf5ddf-ba1a-4175-b0a5-f0cae072a57b">

When clicked it gets activated and two buttons appear in the sub toolbar
<img width="287" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/4627c5d7-ff0f-44b7-900b-9e19ac5ccf50">

  - **Calibration vector** : when activated this button sets the viewer in a Vector mode. there also a couple of buttons that appears in the _subtoolbar_ to manage the  start and end points of the vector. 
  They are disabled while there is no vector defined.  When the user defines the start point the "clear start" button gets enabled and when the end point is the defined the "clear end" buttons is enabled. 
  Clicking on each of this buttons will delete its corresponding point from the vector
  
  Once its activated the user will define a vector in the 2d viewer. If the vector has been defined then the "Continue" button is enabled in the steps bar.
</details>

<details>
  <summary> Calibration format  </summary>

```js
  {
    // this will most likely live in the drawing history
    calibration: {
        horizontal: {
            model: [[0,0,0], [1,1,1]],
            drawing: [[0,0], [1,1]]
        },
        verticalRange: [ 0, 10],
        // considering different container can be in different units we'd need to make sure we know how to scale it when viewing on a different model.
       units: "m"
     }
}
```

</details>

### Goals
- [ ] As a calibration user I want to define a 2d vector to calibrate with 3d

### Tasks
- [x] If this is a re-calibration show the vector with the previous calibration data.
- [ ] Make the viewer react to step 3 of the calibration wizard
- [x] Add a 2d vector component using the ui layer: copy the look and feel from unity viewer
- [ ] Add support for snapping.
- [x] Add the buttons in the toolbar following the behaviour from the description of the issue
- [x] Add help box on top (look at design)
- [x] Make sure vector start and end coordinates do not overlap

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=7-34655&mode=design&t=lugkcNhj94mlP2AS-0)

**Comment by sanmont3drepo** [comment]
merged in the branch
