### ISSUE TITLE
[2D MVP] Milestone 3: 2D Vector drawing

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4942]
### Description
For calibrating and for future features we need a way to add UI elements to the drawing that respond to panning/zooming. In this issue we provide that ui layer and vector drawing.

### Goals
- [ ] As a user I want to be able to draw a vector in the 2d viewer and that it responds appropriately to pan/zoom

### Tasks
- [ ] Create a component ``<2DViewerLayer {..props}/>`` that sits on top of the 2d viewer
- [ ]  props of 2DViewerLayer  are children (svg ui elements), **viewbox** (a rect that will represent the pan/zoom position of the drawing

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=7-35530&mode=design&t=013L82bg5wfSjJMa-0)

**Comment by carmenfan** [comment]
Merged into #4897
