### ISSUE TITLE
[2D MVP] Milestone 2:  Select a drawing opens right side panel 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4948]
### Description
In order to complete the loop for milestone 2 we need to open the side panel with an actual drawing.
for doing so lets hardcode a couple of drawings with actual urls that has images and make the 2dviewer show them

### Goals
- [ ] As a user I want to click on a drawing in the viewer and see the drawing on the split view

### Tasks
- [x] Mockup some  drawings with urls pointing to svg and png images that can be accessde (maybe put them in public? in that case we should remember to delete them before mergeing milestone 2)
- [x] When clicking in the image close the drawing list and  show the split view with the actual image.

### Related Resources
[MockUp](https://www.figma.com/file/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?type=design&node-id=38-14984&mode=design&t=C9aRDghVfTLzNf5q-0)
