### ISSUE TITLE
Get rid of all ticketCard Selectors/actions references in ticketsform

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4966]
### Description
Using ticketsForm outside the tickets card can be a bit of a pain because it uses references to ticketscard redux state 

### Suggested solution
Replace the ticketcards selectors/action  within the context of ticketform with a context. Link tickets cards selectors with that context only in ticketscards. In other context we can use what makes sense. 

### Goal
- [ ] Improve the reusability of ticketform
- [ ] Avoid possible bugs because of missues of ticketcards redux states.

### Tasks
- [ ] Replace ticketscard selectors in ticketsform with a context  or maybe hidden inputs (like ticketId, which could be accesed using useform)
- [ ] link ticketscard selectors with the new context in the ticket cards
