### ISSUE TITLE
Re-renders: Review render in dashboard layout 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4971]
### Description
We havent really taken a look at how many renders we are are using in general but Ive noticed that a blank content in the dashboard layout gets rendered 15 times

<img width="625" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/5a2c6317-605d-4460-98a8-95a6953386ef">

### Suggested solution
Evaluate if its necessary for the app to re-render so many times by blanking one of the pages and see what triggers the re-renders.
Maybe we have a problem with redux store that keeps creating a new state while holding the same data.

### Goal
- [ ] Improve performance of dashboard

### Tasks
- [ ] try blanking a  page
- [ ] research whats causing the re-renders.
