### ISSUE TITLE
[2D MVP] Milestone 1: Ability to add/remove drawing containers

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4972]
### Description
This is part of https://github.com/3drepo/3D-Repo-Product-Team/issues/377.

Create endpoints to provide general drawing container management (note: permissions will be a separate issue). This issue aims to allow the user to create a drawing container, edit its properties and delete them.

##### Drawing categories
  
endpoint: `GET /teamspaces/{teamspace}/projects/{project}/settings/drawingCategories`
Description: Returns the list of drawing categories available within the project
Permissions required: Teamspace/project admin
Response: 
````js
{
  drawingCategories: [
    "a",
    "b"
  ]
}
````

NOTE:
At this stage we're not storing a user editable list of drawing categories. so make it return the hard coded list of model categories (from container)

##### Create a drawing container
endpoint: `POST /teamspaces/{teamspace}/projects/{project}/drawings`
Description: Creates a new drawing container
Permissions required: Teamspace/project admin
Payload:
````js
{
  name: "Level 2 Floor plan", //Name of the drawing, unique within project (strings.title)
  number: "SC1-SFT-V1-01-M3-ST-30_10_30-0001", //Some sort of unique identifier for the drawing (string.title - alphanumeric with underscores and hyphens)
  type: "Architecture",
  desc: "This is the level 2 floor plan for a building in xyz" // strings.shortDescription
}
````

Respsonse:
HTTP 200
````js
{ 
  _id: "3f6eeebd-6f2a-443d-91c1-ef208265771b"  //ID of the drawing that was created
}

````

NOTES:
- In general we want to treat drawings like a different type of container
- This should create an entry in `settings` collection, specifying the type of the model to be `drawing`
- A socket io event should trigger for the new container

##### Edit a drawing container's settings
endpoint: `PATCH /teamspaces/{teamspace}/projects/{project}/drawings/{drawing id}`
Description: Edits a drawing settings
Permissions required: Teamspace/project admin
Payload: Any of the fields that are filled in when the drawing is created

NOTE: 
- A socket io event should trigger for settings being updated

##### Delete a drawing container
endpoint: `DELETE /teamspaces/{teamspace}/projects/{project}/drawings/{drawing id}`
Description: Deletes a drawing container
Permissions required: Teamspace/project admin

NOTE: 
- A socket io event should trigger for container removed

##### Adding favourate drawings
endpoint: `PATCH /teamspaces/{teamspace}/projects/{project}/drawings/favourites`
Description: Adds to the list of favourite drawings within the project
Payload:
````js
{
  models: [
    "3f6eeebd-6f2a-443d-91c1-ef208265771b",
    "ee7e2c5c-a9f0-4a50-9a49-c6daec0d6f7e"
  ]
}
````

##### Removing favourate drawings
endpoint: `DELETE/teamspaces/{teamspace}/projects/{project}/drawings/favourites?ids={drawing id}`
Description: remove from the list of favourite drawings within the project

### Goals
- As an admin, I want to be able to create drawing entries so collaborators and upload their files.
- As an admin I want to specify properties of the drawing so they can be easily identified.
- As an admin, I want to be able to edit these properties
- As an admin, I want to be able to remove a drawing that is no longer applicable
- As an admin, I want to be told if I am trying to create a new drawing container with an existing drawing name
- As an admin, I want to be told if I am trying to create a new drawing container with an existing drawing number
- As a user, I want to be able, to declare a drawing as a favourite/unfavourite

### Tasks
Get Drawing Categories 
- [x] Create route method and swagger doc
- [x] Create processor method
- [ ] Create unit and e2e tests

Create Drawing Container
- [x] Create route method and swagger doc
- [x] Create yup validation method
- [x] Create processor method
- [x] Create model method
- [ ] Create unit and e2e tests

Edit Drawing Container
- [x] Create route method and swagger doc
- [x] Create yup validation method
- [x] Create processor method
- [x] Create model method
- [ ] Create unit and e2e tests

Delete Drawing Container
- [x] Create route method and swagger doc
- [x] Create yup validation method
- [x] Create processor method
- [x] Create model method
- [ ] Create unit and e2e tests

Add Favourite Drawing
- [x] Create route method and swagger doc
- [x] Create yup validation method
- [x] Create processor method
- [x] Create model method
- [ ] Create unit and e2e tests

Remove Favourite Drawing
- [x] Create route method and swagger doc
- [x] Create yup validation method
- [x] Create processor method
- [x] Create model method
- [ ] Create unit and e2e tests

### Related Resources
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/377

**Comment by carmenfan** [comment]
Merged into #4830
