### ISSUE TITLE
[2D MVP] Milestone 1: Endpoints for revision management

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4983]
### Description
This is part of https://github.com/3drepo/3D-Repo-Product-Team/issues/377.

Create endpoints to process drawings revisions.

##### New revision of drawings
endpoint: `POST /teamspaces/{teamspace}/projects/{project}/drawings/{drawing}/revisions`
description: Post a new file (pdf or dwg) as a new revision to the drawing
permissions: collaborator+
payload: 
````js
// Multipart form with:
statusCode: Should be one of the known status codes in the get status code endpoint, required
revCode: string, max length 10, alphanumeric ,fullstop,hypens and underscores
desc: string (shortDescription)
file: <dwg or pdf file via multipart>
````

NOTE:
- maximum file size supported should be 500MB
- The combination of StatusCode + RevCode needs to be unique (This is the equivalent of `tag` in container)
- Processing of the drawing should follow the same process as 3d models (i.e. we don't immediately denote the processing is complete, it goes through the processing status that gets stored and send back by socket.io.
  - for the purpose of this issue - **processing is out of scope** - so just pretend it's completed as soon as we've stored the file.
- This should contribute to the quota calculation (just like containers)
- This should send notification of the status through socket.io just like 3D model processing

##### Get revision list
endpoint: `GET /teamspaces/{teamspace}/projects/{project}/drawings/{drawing}/revisions`
description: provide the full list of revisions uploaded within this drawing container
permissions: viewer+
sample response:
````js
{
  "revisions": [
    {
      "_id": "ef0855b6-4cc7-4be1-b2d6-c032dce7806a",
      "author": "someUser",
      "timestamp": 12345678,
      "format": ".dwg",
      "statusCode": "s1",
      "revCode": "P01,
      "description": "Level 2 floor plan",
      "void": true //omitted when false
    }
  ]
}
````

##### Update revision
endpoint: `PATCH /teamspaces/{teamspace}/projects/{project}/drawings/{drawing}/revisions/{revision}`
description: Update a revision - just like containers, you should only be able to void or unvoid a revision.
permissions: collaborator+
payload:
````js
{
  "void": true
}
````

##### Get original files
endpoint: `GET /teamspaces/{teamspace}/projects/{project}/drawings/{drawing}/revisions/{revision}/files/original`
description: Get the original file (the PDF/DWG) for that particular revision
permissions: collaborator+
response:  binary of the original file

##### Get status codes list
see https://github.com/3drepo/3drepo.io/issues/5023

###### Revision records
Revision records should be stored in `drawings.history`:
````js
// Example drawing revision
{
    "_id" : LUUID("cad0c3fe-dd1d-4844-ad04-cfb75df26a63"),
    "project": LUUID("bfe0c3fe-dd1d-4844-ad04-cfb75df26a63"),
    "model": LUUID("aeb0c3fe-dd1d-4844-ad04-cfb75df26a63"),
    "author" : "carmen",
    "statusCode" : "S1",
    "revCode": "abc,
    "timestamp" : ISODate("2023-11-28T19:11:55.000Z"),
    "format": "dwg",
    "rFile" : [ 
        LUUID("0ac71fb2-a18d-4ef8-b5a8-b87879326300")
    ]
}
````
NOTE:
- Unlike containers, every drawing within a teamspace will be stored in the same collection, with project/model properties to denote which project/model they belong to.
- Ensure we add to the delete drawing function to remove revisions
- `rFile` should be links to original files, which should be a reference to a file. The reference should be stored in `drawings.history.ref`
  - the original filename should be a metadata within the reference, instead of the `<UUID>_original_file_name` approach taken in containers.
  - We will record the file extension in the object instead of having to regex it out of the rFile string like in containers.
  - This will also contain the `incomplete` and `void` property like container to denote the state of the model processing.

###### Original file
As stated above, the original file will be stored in `drawings.history.ref` with the original file name as part of the metadata:
````
// drawings.history.ref
{
    "_id" : LUUID("0ac71fb2-a18d-4ef8-b5a8-b87879326300"),
    "type" : "fs",
    "link" : "197/204/f959eda6-3fde-436a-ba0e-b1aa777a413d",
    "size" : 2419670,
    "name": "Floor1.dwg",
    "project": LUUID("bfe0c3fe-dd1d-4844-ad04-cfb75df26a63"),
    "model": LUUID("aeb0c3fe-dd1d-4844-ad04-cfb75df26a63"),
    "rid" : LUUID("cad0c3fe-dd1d-4844-ad04-cfb75df26a63"),
}
````

### Goals
-  As a collaborator, I want to be able to declare a revision as void if I have made a mistake
-  As a collaborator, I want to be able to un-void a revision if I mis-clicked.
-  As an admin, I want to quickly create a drawing container whilst I am uploading a drawing
-  As a collaborator, I want to be able import a 2D drawing (PDFs, DWGs) into 3D Repo
-  As a collaborator, I want to be stopped from uploading the drawing if there is already an existing revision with the same status code and revision code
- As a collaborator, I want to be able to download the original drawing file

##### New revision

- [x] Add validation
- [x] Create route method
- [x] Create processor method
- [x] Create model method
- [x] Update quota to include drawings
- [x]  Create unit & e2e tests
- [x] Update swagger doc

##### Update revision

- [x] Add validation
- [x] Create route method
- [x] Create processor method
- [x] Create model method
- [x]  Create unit & e2e tests
- [x] Update swagger doc

##### Get revision list

- [x] Create route method
- [x] Create processor method
- [x] Create model method
- [x]  Create unit & e2e tests
- [x] Update swagger doc

##### Get original files

- [x] Create route method
- [x] Create processor method
- [x] Create model method
- [x]  Create unit & e2e tests
- [x] Update swagger doc

**Comment by carmenfan** [comment]
Merged into #4830
