### ISSUE TITLE
Send io-activity from 3drepo.io instead of determining from logs

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#4991]
### Description
Send io-activity from 3drepo.io instead of determining from logs

### Goals
- [x] Create new index `io-activity` in Elastic
- [x] Send network logs to Elastic

### Tasks
- [x] Send network logs to Elastic

### Related Resources

MockUp : `link to mockup`
Coda doc: `link to coda`

**Comment by Charence** [comment]
Sample output:
![image](https://github.com/3drepo/3drepo.io/assets/1438332/7089fe27-cb43-4bd6-8381-ca07d5fd71b2)

**Comment by Charence** [comment]
Add `host`:
![image](https://github.com/3drepo/3drepo.io/assets/1438332/2b105077-258c-491c-b775-dab21ae6e1ed)

**Comment by Charence** [comment]
@carmenfan Existing script here: https://github.com/3drepo/3D-Repo-Product-Team/blob/master/Tools/Elastic%20Index%20Mover/main.py
