### ISSUE TITLE
Make tickets table use generateFullPath instead of getSearchParams

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5004]
### Description
In `src\v5\ui\routes\dashboard\projects\tickets\ticketsTable\ticketsTable.component.tsx` we are using  getSearchParams from useSearchParams for generating some urls. Using generateFullPath (#4906) would make the code clearer  in its intentions.

### Goal
- [ ] Improve readbility in ticketsTable  

### Tasks
- [ ] Replace getSearchParams use with generateFullPath
- [ ] Delete getSearchParams  from useSearchParams
