### ISSUE TITLE
Pin events are not correctly handled

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#5021]
### Description
There is some code for pin clicks (I spotted 2 files, but there may be more) that could use refactoring:
- In Viewer.tsx, we have a function called `handlePinClick`. This function is registered a few lines below and triggered when the user clicks on a ticket pin. The same behaviour exists also for issues and risks, but the logic is store in a different file, ViewerGui.sagas.tsx. I the same logic for pins should be moved there. Also, this causes the selectedTicketPin value store in the ticketsCard.redux to be set to a issue/risk pin when clicking on the latter, which is incorrect
- in ViewerGui.sagas.tsx there are 2 functions called `stop/startListenOnClickPin`. They were probably copy pasted as their code references model stuff

### Goal
- [ ] The logic for handling pin click should be consistent
- [ ] *ListenOnClickPin code should be correct

### Tasks
- [ ] Move handlePinClick logic in viewerGui.sagas.tsx
- [ ] Adjust the error text for startListenOnClickPin
- [ ] Adjust the event action on stopListenOnClickPin
