### ISSUE TITLE
[2D MVP] Milestone 1 - Status Code preset list

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5023]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/377

We'd like to make some changes to Status code:
- This should be a pre-determined list, determined by a backend API (which will be configurable via project settings in the future)
- The preset list should be as follows (without S5), with Published codes going up to 9
![image](https://github.com/3drepo/3drepo.io/assets/11945337/418cd96e-a74a-4cd4-82f1-fdc1cbc9eaee)
- Status code should be compulsory, with no default values
- Only the code should be stored in the data, but on the drop down menu, we should also provide the description for the users to understand what each option means

#### Front end change
Status code should now be a required field and a drop down providing the options provided by the Drawign configuration endpoint.
![image](https://github.com/3drepo/3drepo.io/assets/11945337/9a04c0aa-4567-48fa-a5a3-03a856af4566)

If we can reuse the design for destination to provide the `code` and `description` of each status code:
![image](https://github.com/3drepo/3drepo.io/assets/11945337/77dbdf4d-82d0-4d86-b116-37bbf24be147)

##### Drawing configurations
endpoint: GET /teamspaces/{teamspace}/projects/{project}/settings/statusCodes
Description: Returns the configurations for available within the project
Permissions required: everyone
Response:
````js
{
  statusCodes: [
     { code: "S1", description: "Suitable for coordination" },
     { code: "S2", description: "Suitable for information" },
     // etc
  ]
}
````

NOTES: 
- The list will be hard coded for now.

### Goals
- [ ] As a project admin I want to make sure that all drawing revisions are submitted with a recognised status code

### Tasks
 - [ ] Status code should be mandatory
 - [ ] Status code should use an autosuggest dropdown as opposed to a text input
 - [ ] Status code options should come from the new endpoint (mock the response for now)
 - [ ] Status code options should use the same design as destination autosuggest

**Comment by sanmont3drepo** [comment]
Merged in #4830
