### ISSUE TITLE
Migrate  3dviewer from class component to function component

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5036]
### Description
3dviewer is a v4 component and is using the old way of creating a component, that means its awkward to use because you cant use hooks and is harder to read. 

### Suggested solution
Refactor 3dviewer to functional form

### Goal
- [ ] Have a consistent code style throught the app
- [ ] be able to use hooks in 3dviewer
- [ ] tidy up a bit of the 3dviewer

### Tasks
- [ ] Refactor 3dviewer
