### ISSUE TITLE
[2D MVP] Milestone 4

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5038]
### Description
Base issue for milestone 4
dependencies:

- [x] https://github.com/3drepo/3drepo.io/issues/5084
- [x] https://github.com/3drepo/3drepo.io/issues/5039
- [x] https://github.com/3drepo/3drepo.io/issues/5040
- [x] https://github.com/3drepo/3drepo.io/issues/5043
- [x] https://github.com/3drepo/3drepo.io/issues/5103

### Product issue
https://github.com/3drepo/3D-Repo-Product-Team/issues/380

### Related Resources
[Navigation
](https://www.figma.com/design/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?node-id=11-9027&t=Z3TmeDiRW11yggwo-0)

[Show 2d Pins](https://www.figma.com/design/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?node-id=11-11332&t=Z3TmeDiRW11yggwo-0)
