### ISSUE TITLE
[2D MVP] Milestone 4: Camera handling

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5039]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/380
For the user to be able to use 3d+2d they should be able to move the camera in the 2d space and see it reflected in the 3d space, as well as for the camera in 3d to change and see it reflected in 2d.

To do so we are adding a camera widget in the 2d viewer:

<img width="76" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/7857d66b-6c71-41db-bc4d-78f5009e365a">

- If the user clicks and drags the camera, it will be reflected on 3d and move the camera  using _ViewerService.setCamera_ and the transformation provided by the calibration.
- By checking the position of the 3d camera using _ViewerService.getCurrentViewpointInfo_  (maybe using requestAnimationFrame for polling? ) then the 2d camera will be updated. 
- The cone represents the direction in which the camera is looking. If the 3d camera is looking top down , then the cone disappears and it becomes just a circle. 

When the camera is off sight, either by panning/zooming  the icon will change and be just off the borders like it's been shown here:
<img width="160" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/e90abaac-d0f3-4545-b4c1-d1ad887c5cf0">
 
 The flap in the box with the camera icon should be pointing to the actual position of the camera.

### Goals
- [ ] As a viewer+, I want to be able to identify where I am on the 2D drawing base on my 3D Camera position
- [ ] As a viewer+, I want to know if I am outside of my current view of the drawing, and on which direction
- [ ] As a viewer+, I should be able to move my camera in the 3D pane and it should update the placement of the 2D icon and its orientation.

### Tasks
- [ ] Add a camera widget
- [ ] Synchronize position of 2d camera when moving the camera in 3d (see #5041 and ViewerService.getCurrentViewpointInfo) 
- [ ] Synchronize position of 3d camera when moving the camera in 2d (see #5041 and ViewerService.setCamera)

### Related Resources

[Camera in sight](https://www.figma.com/design/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?node-id=11-9345&t=artmM8q9Qc8Zz01g-0)

[Camera out of sight
](https://www.figma.com/design/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?node-id=478-14406&t=artmM8q9Qc8Zz01g-0)

**Comment by carmenfan** [comment]
Merged into #5038
