### ISSUE TITLE
[2D MVP] Milestone 4: Show 2D Pins

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5040]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/380
We are providing a way for the users to show and drop pins in the 2d area. 

- The pins shown are only from tickets.
- The pins that are shown in the 2d drawing are only the ones that are inside the limits of the 2d drawing.

### Goals
- [ ] As a viewer+, I want to be able see all the pins of the custom tickets that are relevant to the drawing
- [ ] As a viewer+, I want to be able to click on the pin on 2D and it will show me the ticket information on the Tickets panel 

### Tasks
- [ ] When clicking a pin in 2d open the ticket as we do with the 3d pin.
- [ ] Reflect the pins from custom tickets taking in consideration only those are are inside the volume of the drawing

### Related Resources
[MockUp](https://www.figma.com/design/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?node-id=11-11332&t=j1A2qZU5bKmgEQil-0)

**Comment by sanmont3drepo** [comment]
merged into base branch
