### ISSUE TITLE
[2D MVP] Milestone 4: Transformations utils

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5041]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/380
For being able to render the camera and the pins we need a way to transform a 3d vector to a  2d point and vice versa.  Using the calibration vectors + planes we should be able to have a function to transform the points. 

### Goals
- [ ] As a dev I want to be able to transform a 3d vector to 2d point to affect the drawing.
- [ ] As a dev I want to be able to transform a 3d vector to 2d point to manage 3d from the drawing.

### Tasks
- [ ]  Add a function that creates a matrix to transform 3d points to 2d points based of the calibration
- [ ]  Add a function that creates a matrix to transform 2d points to 3d points based of the calibration

**Comment by sanmont3drepo** [comment]
This  is already addressed in other milestone 4 issues.
