### ISSUE TITLE
[2D MVP] Milestone 4: Drop 2D Pins

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5043]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/380
We are providing a way for the users to drop pins in the 2d area. 

- When dropping a pin in  the 2d area, the plane that its being dropped to is the lower plane.

### Goals
- [ ] As a collaborator+, I want to be able to drop a pin in the 2D drawing.
- [ ] As a collaborator+, I want to be able to edit a pin in the 2D drawing.

### Tasks
- [ ] Add pin drop from 2d area.
- [ ] Add the ability to edit the pins like with 3d

### Related Resources
[MockUp](https://www.figma.com/design/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?node-id=11-11332&t=j1A2qZU5bKmgEQil-0)

**Comment by carmenfan** [comment]
Merged into #5038
