### ISSUE TITLE
[2D MVP] Milestone 3: Integration with backend

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5044]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/379
For fetching and saving the calibration we need to integrate with backend.

<details>
  <summary> Calibration format  </summary>

```js
  {
    // this will most likely live in the drawing history
    calibration: {
        horizontal: {
            model: [[0,0,0], [1,1,1]],
            drawing: [[0,0], [1,1]]
        },
        verticalRange: [ 0, 10],
        // considering different container can be in different units we'd need to make sure we know how to scale it when viewing on a different model.
       units: "m"
     }
}
```

</details>

### Goals
- [ ] As a calibration user I want to be able to save the changes
- [ ] As a calibration user I want to be able to get the calibration I saved beforhand

### Tasks
- [ ] Add api endpoints for saving calibration
- [ ] Add api endpoints for fetching calibration
- [ ] Update code to use those instead of the hardcoded data

**Comment by sanmont3drepo** [comment]
merged in the base branch
