### ISSUE TITLE
Extend addOn schema to support optional modules

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5046]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/530

Create v5 version fo the addOns endpoint and add support for modules, which specify which optional feature the teamspace has enabled.

#### Endpoint
Route: `HTTP GET /v5/teamspaces/{teamspace}/addOns`
Permissions: member of teamspace
description: Returns information about what addons are available within this teamspace
response:
````js
{
    "vrEnabled" : true,
    "hereEnabled" : true,
    "modules": ["issues", "risks"]
}
````

- NOTES:
see product issue on how the add ons should be configured, and what is the consequences of it being enabled/disabled.

### Goals
- [ ] As a system admin, I should be able to turn off Issues and Risks from the teamspace settings for both existing teamspaces and new teamspaces.
- [ ] As a system admin, I want to ensure existing teamspaces will have issues/risks enabled unless we're told otherwise
- [ ]  As a teamspace/project admin/user, when a system admin turns off Issues or Risks in the teamspace settings I should not see this on the 3D Repo.io UI.
- [ ]  As a teamspace/project admin/user, when a system admin turns off Issues or Risks in the teamspace settings I should not be able to interact with these elements on any of the plugins.

### Tasks
- [x] Update add ons script
- [x] Create new endpoint for fetching add ons
- [x] Create middleware to stop reaching issues/risks endpoint if they are not enabled

**Comment by carmenfan** [comment]
merged into #5048
