### ISSUE TITLE
Detect optional features and disable risks/issues if they are not available in the TeamSpace 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5048]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/530
We are providing an option to enable/disabled issues and risks based on the TeamSpace.
This depends on #5046

 
- If issues is not enabled frontend will hide issues in the viewer.
- If risks is not enabled frontend will hide risks in the viewer.
- If issues is not enabled kanban will hide the issues options in the select box
- If risks is not enabled kanban will hide the risks options in the select box
- if issues and risks are not enable the whole kanban route will not be enabled

<details>
   <summary> Backend endpoints </summary>

Route: `HTTP GET /v5/teamspaces/{teamspace}/addOns`

```json
{
    "vrEnabled" : true,
    "hereEnabled" : true,
    "modules": ["issues", "risks"]
}
```
</details>

### Goals
- [ ] As a teamspace/project admin/user, when a system admin turns off Issues or Risks in the teamspace settings I should not see this on the 3D Repo.io UI.

### Tasks
- [x] Add API functions for getting the addons
- [x] Add redux states/sagas for getting the addons
- [x] Fetch the addons state
- [x] Remove issues from the viewer if they are not enabled
- [x] Remove risks from the viewer if they are not enabled
- [x] Remove issues from the kanban select box if they are not enabled
- [x] Remove risks from the kanban select box if they are not enabled
- [x] Change title of issues & risks tab based on the state of addons
- [x] Remove kanban route if risks and issues are not enabled
