### ISSUE TITLE
Swagger docs - Incorrect output type on get revision list timestamp

### ISSUE THREAD

**Issue by zaneulhaq** [3drepo/3drepo.io#5050]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/467

Change swagger so that timestamp refers to the correct epoch timestamp.

### Goals

- [x] The user should see an epoch timestamp as an example
- [x] The user should see an epoch timestamp as an integer, not a string in the schema.

### Tasks

- [x] Go here https://github.com/3drepo/3drepo.io/blob/b5215adce21d8b7124ed2c85aa27bbb20dc43f6e/backend/src/v5/routes/teamspaces/projects/models/containers/revisions.js#L134
- [x] edit type to integer
- [x] edit example to "1644925152000"

### Related Resources

MockUp : `link to mockup`
