### ISSUE TITLE
Simplify columns definition in dashboard list

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5063]
### Description
The dashboard lists have an awkward way of setting the width of the columns, simplifying that would make them easier to change and more reliable

### Suggested solution
Use css grid or flex

### Goal
- [ ] Have more readable and maleable lists

### Tasks
- [ ] Try using css grid
- [ ] if css grid doesnt work try with flexboxes
- [ ] verify that elipssis still works
