### ISSUE TITLE
[2D MVP] Milestone 3 - endpoint to store and fetch calibration 

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5064]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/379

We need an endpoint for the front end to talk to in order to store the calibration values against a drawing.

Calibration needs to be stored against a revision, and a drawing can be calibrated many times, but each calibration we will store as a record so it is clear who calibrated/recalibrated at what time. When the user requests a calibration against a revision, they will be provided with the latest calibration values.

##### Add calibration
endpoint: `POST /teamspaces/{teamspace}/projects/{project}/drawings/{drawing}/revisions/{revision}/calibrations`
permissions: collaborator+
description: Add a calibration against the drawing
payload:
````js
{
    horizontal: {
        model: [[0,0,0], [1,1,1]], //2 3d points to make a vector
        drawing: [[0,0], [1,1]] //2 2d points to make a vector
    },
    verticalRange: [ 0, 10],
    units: "m"
}
````

NOTES:
Calibrations should be stored in `drawings.revisions.calibrations` and a record should look something like this:
````js
{
    _id: LUUID(xxx),
   project: LUUID(xxx),
   drawing: LUUID(xxx),
   rev_id: LUUID(xxx),
   createdAt: ISODATE(),
   createdBy: "username",
   horizontal: {
      model: [[0,0,0], [1,1,1]], //2 3d points to make a vector
      drawing: [[0,0], [1,1]] //2 2d points to make a vector
  },
  verticalRange: [ 0, 10],
  units: "m" 
}
````

##### Stats endpoint
Update to the drawing stats endpoint created in https://github.com/3drepo/3drepo.io/issues/4985 , to add the calibration state of a drawing
````js
{
   calibration: "calibrated"; // Can be calibrated, uncalibrated or unconfirmed
  
 //... other drawing stats as before
}
````
NOTES:
- Calibration status is defined as follows:
  - `Uncalibrated`: there is no calibration associated with the drawing at all
  - `Unconfirmed`: There are calibration associated with the drawing, but not to the latest revision of the drawing
  - `Calibrated`: There is a calibration assoicated with the latest revision of the drawing

##### Get a calibration
endpoint: `GET /teamspaces/{teamspace}/projects/{project}/drawings/{drawing}/revisions/{revision}/calibrations`
permissions: viewer+
description: Get a calibration against the drawing
payload:
````js
{
    horizontal: {
        model: [[0,0,0], [1,1,1]], //2 3d points to make a vector
        drawing: [[0,0], [1,1]] //2 2d points to make a vector
    },
    verticalRange: [ 0, 10],
    units: "m"
}
````

NOTES:
This should pull the latest calibration against the latest revision of the drawing. If there is no calibration against hte latest revision, pull the next available (i.e. latest calibration of the previous revision

##### Confirm a calibration
endpoint: `POST /teamspaces/{teamspace}/projects/{project}/drawings/{drawing}/revisions/{revision}/calibrations?usePrevious=true`
permissions: collaborator+
description: Confirm a calibration against the drawing revision by copying a previous revisions' calibration
payload: none

NOTES:
- This is only responsive if the revision of the drawing is in unconfirmed state (i.e. it has no recorded calibration but there are previous calibration revisions.
- On this request, we take a copy of the latest calibration from the previous revision and copy it in as our own.
- This in affect is the same as posting a calibration, without sending the data (i.e. we should record the time and user who did the confirmation)
- If the revision is not in `unconfirmed` state, it should return with an error.

### Goals
- [ ] As a collaborator+, I should be able to post a calibration against a drawing revision
- [ ] As a viewer+ I should be able to fetch the calibration information of a drawing
- [ ] As a viewer+ I should be able to see the calibration status of the latest revision of the drawing
- [ ] As a collaborator+, I should be able to confirm a calibration of a drawing

### Tasks
- TBC
