### ISSUE TITLE
[2D MVP] Milestone 2: Integrate backend on drawings card

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5066]
### Description
The drawings card is not showing the actual backend data.

### Goals
- [ ] Users has access to their backend drawing data though the drawings card.

### Tasks
- [ ] Add fetch drawing data when opening the drawings card if necessary
- [ ] Update the data structures to use the real data
- [ ] Show the thumbnail and rest of the data from the drawings

**Comment by carmenfan** [comment]
merged into #4833
