### ISSUE TITLE
Session validation is missing unit tests

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5072]
### Description
Currently [session validation logic](https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/utils/sessions.js#L32) does not have its own unit tests and is being tested by [the middleware](https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/middleware/sessions.js) that is calling it. 

### Suggested solution
To make them truly unit tests, utils/sessions should have its own unit tests and the middleware should be mocking the results of the function.

### Goal
- [ ] The 2 functions involved should have true unit tests

### Tasks
- [ ] Add unit tests for utils/sessions
- [ ] make sessions middleware mock the results of `isSessionValid `
