### ISSUE TITLE
[2D MVP] Milestone 4 - Basic search

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5084]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/380
In order to let users search the drawings we are implementing a basic search by string by reusing the component in custom tickets.

### Goals
- [ ] The user can search the tickets by a string

### Tasks
- [ ]  Add the search from tickets
- [ ] Modify the items to highlight the search word like in tickets
- [ ]  Search by description, status code, revision code, name, drawing number

### Related Resources
<img width="428" alt="image" src="https://github.com/user-attachments/assets/31c732dc-7b36-488e-99ed-3bc2dc031143">

**Comment by sanmont3drepo** [comment]
merged into base branch
