### ISSUE TITLE
[2D/3D] Milestone 2 Reading 2D DWG plans

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5090]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/378

With https://github.com/3drepo/3drepobouncer/pull/688 pretty much done, we can start hooking up the process to process DWG plans

This also depends on https://github.com/3drepo/3drepo.io/pull/5032

### Goals
- [ ] As a collaborator I want to be able to upload a 2D DWG and get a SVG to view once it has been processed
- [ ] As a collaborator I want to be told if the process failed
- [ ] As a system admin I want to be known if a DWG has failed to process unexpectedly

### Tasks
- [x] push 2D DWG task to processing
  - [x] Ensure bouncer understands and is processing the file
- [x] Ensure processing status are updated
- [x] Ensure success/failure of processing is recorded correctly
 - [x] Ensure failure triggers an email
 - [x] Ensure failed revisions are being filtered out on revision list (?)
- [x] NEW_REVISION event seems redundant, model import finished can be used instead.
- [x] Ensure 3D model is also using UUID everywhere until it hits events (e.g. on model processed it is passing a string for revId)

**Comment by carmenfan** [comment]
Merged into #4830
