### ISSUE TITLE
Introduce a new property to custom tickets: Image List

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5091]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/382

We want the ability to store multiple images (`imageList`) in a single property(`image`). On an existing property the user should be able to add/remove images.

It should conform to the same mechanics as all properties (i.e. readOnly, immutable etc)

These images should contribute to the quota calculation, and respects the maximum image file size that is configured (basically same middleware checks as single image.

Like other complex properties, `default` does not need to be supported

#### Schema

This will work very similarly to images in comments, image list property will take in an array of images in base64 format:
````js
{
  //... other properties
  imageListProp: ["<base 64 image 1>", "<base 64 image 2>", "<base 64 image 3>"]
}
````

If it is an edit, it will accept a combination of recognised reference ids and base64 images
````js
{
  //... other properties
  imageListProp: ["<base 64 image 1>", "<UUID of existing image>", "<base 64 image 3>"]
}
````

#### NOTES:
- Images should be removed if it is no longer referenced
- There should be a entry in the tickets log to show if someone has added/removed images to this field
- If the array is empty, unset the property.

### Goals
- [x] As a user I want to add multiple images into a single property
- [x] As a user I want to add additional images to an existing `imageList` property
- [x] As a user I want to remove existing images to an existing `imageList` property
- [x] As a user I want to be able to clear all images from the property.

### Tasks
- [x] Modify the schema to accept multiple images and set null to empty array
- [x] Modify the proc / models to store multiple images
- [x] Remove multiple images if prop is null
- [x] Add the log for adding / removing images
- [x] Edit quota code to take into consideration all images
- [x] Edit unit and e2e tests
