### ISSUE TITLE
Multiple images property in custom tickets

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5099]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/382
We want to provide users with the ability to upload several images to a ticket. in a similar way the user should be able to take multiple screenshots. when clicking on the image it shows the gallery and the user can delete or edit each image individually.

It should conform to the same mechanics as all properties (i.e. readOnly, immutable etc)

### Goals
- [ ] As a user I want to add multiple images into a single property
- [ ] As a user I want to add additional images to an existing `imageList` property
- [ ] As a user I want to remove existing images to an existing `imageList` property
- [ ] As a user I want to be able to clear all images from the property.

### Tasks
- [ ] Read and handle new template property "imageList";
- [ ] `imageList` should allow to delete images one by one or all together;
- [ ] `imageList` should display multiple images the same way as comments;
- [ ] `imageList` should allow new images upload on top of the existing one(s) if any;
- [ ] If `imageList` is readonly, none of the functions above should be available;
- [ ] if `imageList` is immutable, the functions above should be disabled right after closing the carousel

### Related Resources
<img width="333" alt="image" src="https://github.com/user-attachments/assets/0369f33e-5ce1-4749-91bf-c220337522c9">

[Backend issue
](https://github.com/3drepo/3drepo.io/issues/5091)
[MockUp](https://www.figma.com/design/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?node-id=11-42720&t=1Mn53p50sqWOx2vA-0)
