### ISSUE TITLE
[2D MVP] Milestone 4: Show/hide all pins ticket

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5103]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/380
We want to let the users show or hide the ticket pins to grant them a bit more control when the 3d view seems more cluttered.

This is only for the ticket listing 

### Goals
- [ ] As a user I want to be able hide all tickets pins
- [ ] As a user I want to be able to show all ticket pins

### Tasks
- [ ] - To be completed - 

### Related Resources
<img width="519" alt="image" src="https://github.com/user-attachments/assets/678d810c-9733-4e98-b344-fd2fb4e97517">

**Comment by sanmont3drepo** [comment]
merged into base branch
