### ISSUE TITLE
[2D/3D MVP] Milestone 2 - Create thumbnail

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5107]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/378

When a dwg/pdf has finished processing successfully, we want to create a png thumbnail of the SVG/Raster image that has been stored.

This thumbnail should be a much smaller version of the drawing and the aspect ratio should match what we intend to display on the drawing list (best to consult the front end team for the numbers)

This thumbnail should be stored per revision, but (for now at least) only the latest non void version of the image can be fetched by the following endpoint:

endpoint: GET /teamspaces/{teamspace}/projects/{project}/drawings/{drawing}/thumbnail
description: Fetches the thumbnail of the latest processed, non void drawing
permissions: viewer+

The thumbnail should be stored in a similar way as the image, with a reference in the revision.

### Goals
- [ ] As a viewer+, I want to be able to see a thumbnail of the drawing on the list of drawings

### Tasks
- [x] Construct thumbnail when revision is processed
- [ ] Create endpoint for reading thumbnail
  - [ ] middleware to check permissions and drawing exists
- [ ] Processor to find the reference to the latest processed revision
  - [ ] fetch image
    - [ ] Ensure mimetype is respected

**Comment by carmenfan** [comment]
Merged into #5090
