### ISSUE TITLE
BCF and report is not working (issue & risks) 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5121]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/575https://github.com/3drepo/3D-Repo-Product-Team/issues/575

When trying to export BCF or showing the issues report there is an error showing (not logged in)
For report we are going to hide the item

### Goals
- [ ] The user can download BCF 
- [ ] There is no way to access the reports

### Tasks
- [ ] Hide reports
- [ ] Use CSRF token to download BCF

### Related Resources
![image](https://github.com/user-attachments/assets/7ce885ae-02ea-40f5-8c98-cae44cbca68e)
