### ISSUE TITLE
[2D MVP] Milestone 2: Show the stored drawing when clicking on the drawings card

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5124]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/378
Until this issue the drawings on the drawings viewer are mocked up. After #5066 we need to show the actual drawings.

### Goals
- [ ] As a user I want to see the drawing that I uploaded when clicking on the drawings card

### Tasks
- [ ] When clicking on the drawing item in the drawing card fetch the actual drawing (take in consideration the crossite token)
- [ ] Delete image files from #4948
