### ISSUE TITLE
Update Intercom contact creation

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#5134]
### Description
Update Intercom contact creation to include default attributes e.g. `unsubscribed_from_emails`

### Goal
- Should make use of fields Asite team also uses

### Tasks
- [x] `unsubscribed_from_emails`
- [x] `signed_up_at`
- [x] Check with team what to do with `company_entered`
  - [x] Team uses custom attribute `company` so it is preferred to copy value into this custom attribute
