### ISSUE TITLE
Providing an archived activity log as an endpoint

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5145]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/546

We want to build the foundations of capturing an audit trail of activities that are happening within a teamspace. To begin with, we would like to record the following activities:

- Whenever a user has been assigned/revoked from a seat
- When an invitation has been sent/revoked
- Permission changes:
  - When a user has been assigned/revoked from teamspace admin privileges
  - When a user has been assigned/revoked from project admin privileges
  - When a user has been assigned/changed/revoked from container level permissions privileges

#### Journaling service
We'll implement an journaling service that will run when the server is launched. It will hook up to the [events manager](https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/services/eventsManager/eventsManager.js) to listen into events it needs and records the journals as appropriate.

We will have to introduce [new events](https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/services/eventsManager/eventsManager.constants.js) that will be triggered in the 4 actions described above.

#### Data storage
Data should be stored in te teamspace database inside an `activities` collection. The following should be the base schema for all activities, with variations on what the data part contains:
````js
{
    _id: UUID(/* ... */),
    action: "type of action"; // an enum to denote the activity
    timestamp: ISODATE(yyyy-mm--dd); // Date/Time when it happened
    executor:  "user1"; // username of user who triggered this action
    data: {
        /*
             This schema will vary depending on the action, e.g. if a user has been added or 
              removed it should only contain a user name
              If this is permissions it should contain the list of users and their permissions before/after.
       */
    }  
}
````

#### Actions
| Enum | Description | Data Schema |
|--------|--------|--------|
| `USER_ADDED` | When a user has been added into the teamspace| <pre>{<br>&emsp;&emsp;user: "username"<br>}<br></pre>|
| `USER_REMOVED` | When a user has been removed from the teamspace | Same as above|
| `PERMISSIONS_UPDATED` | When a user's permissions have changed  | see `Permissions updated data examples`|
| `INVITATION_ADDED` | When a user is invited to a teamspace | TBD |
| `INVITATION_REVOKED` | When a user's invitation is revoked | TBD |

##### Permissions updated data examples
Teamspace level permissions:
````js
// user has been revoked from teamspace admin privileges
{
  users: ["username"],
  permissions: [
    {
      from:  ["teamspace_admin"],
      to: null
    }
  ]
}
// user has been granted from teamspace admin privileges
{
  users: ["username"],
  permissions: [
    {
      from: null,
      to: ["teamspace_admin"]
    }
  ]
}
````

Project level permissions:
````js
// The following user has been removed from project admin access from project A and granted admin access to project B
{
  users: ["username"],
  permissions: [
    {
      project: UUID(/* project A */),
      from:  ["project_admin"],
      to: null
    }
    {
      project: UUID(/* project B */),
      from: null,
      to: ["project_admin"]
    }
  ]
}
````

many level permissions:
````js
// The following users has been removed from project admin access from project A and granted some model privileges 
{
  users: ["username", "username2", "username3"],
  permissions: [
    {
      project: UUID(/* project A */),
      from: ["project_admin"],
      to: null
    },
    {
      project: UUID(/* project A */),
      model: UUID(/* container 1 */)
      from:  null,
      to: ["viewer"]
    },
    {
      project: UUID(/* project A */),
      model: UUID(/* container 2 */)
      from:  null,
      to: ["collaborator"]
    }

  ]
}
````

#### Endpoint to retrieve activity log
We will also need an endpoint to retrieve the list of activities:
**Endpoint** `GET /teamspaces/{teamspace}/settings/activities/archive`
**Permissions**: Teamspace admins
**Optional query string options**:
  - `from` : timestamp (epoch ms) of the earliest activity the user wishes to include
  - `to`: timestamp (epoch ms) of the last activity the user wishes to include
**Response**: A encrypted archive of the log within the stated time period

NOTE: 
This will also need to send an email to the user with the password to the encrypted archive. A draft of the email can be found in [figma](https://www.figma.com/design/eI1KkbqCaxI7AeMeXnPE1V/Permissions?node-id=100-1550&node-type=FRAME&t=iA6995NZXUmb5qk8-0)

### Goals
- [ ] As a teamspace admin I want to be able to retrieve a list of access related activities as an archive

### Tasks
- [x] create the activities events file with the subscribes
- [x] create the activities model 
- [x] and the publishes in all the necessary files
- [x] modify unit and e2e tests
- [x] modify the documentation to include the new events
- [x] Create the endpoint for fetching activities
- [x] Send the email to the user
- [x] Add tests for the endpoint
