### ISSUE TITLE
User Permissions - Warning modal when making a change

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5149]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/537
Be warned when any user permissions are changed.

### Goals
- [ ] As a teamspace/project admin, show me a modal that requires confirmation before changing a single or multiple users permissions with information regarding the change.
- [ ] As a teamspace/project admin, allow me to suppress this modal on each session by adjusting the toggle option in the user permissions UI.

### Tasks
- [ ] Add a boolean switch in users permissions page (design is just a guide for this)
- [ ] Use local storage to save the switch permission settings ( like with visual settings)
- [ ] Dispatch a warning message like in the design whenever the user is changing something)  

### Related Resources
[MockUp](https://www.figma.com/design/eI1KkbqCaxI7AeMeXnPE1V/Permissions?node-id=1-38)
