### ISSUE TITLE
Download activity log for teamspace

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5151]
### Description
Product issue:  https://github.com/3drepo/3D-Repo-Product-Team/issues/546
For teamspace admins we are providing a way to check on the activity of the teamspace. So there will be a download activity log in the teamspace settings along wiith a date filter

### Goals
- [ ] As a teamspace admin, I am able to download an encrypted and zipped JSON log of permission changes that occur on the teamspace and all the projects in the teamspace from the teamspace settings.
- [ ] As a teamspace admin, I can select a date range for user permission changes in the teamspace settings to filter what information I download.
- [ ] As a teamspace admin, I am notified of a password being sent to my email to open the encrypted file.
- [ ] As a teamspace admin, I am sent a password to my email for use in opening the encrypted file.
- [ ] As a teamspace admin, I should only be able to Download the logs if I provide a Start Date OR End Date.

### Tasks
- [x] Add the section for downloading the .zip file in the teamspace settings
- [x] Download button is enabled only if the user have selected start or end date
- [x] MAke the call to thebackend to download the file using the start/end date as param

### Related Resources
[MockUp](https://www.figma.com/design/eI1KkbqCaxI7AeMeXnPE1V/Permissions?node-id=71-361&node-type=canvas&t=neDerpLMNi80ZZXF-0)
Backend Issue: #5145
