### ISSUE TITLE
Remove v4 getstate/dispatch in favour of v5  getstate/dispatch 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5156]
### Description
because in v4 the helper functions getstate/dispatch  are also in the same place the store is being created is easy to create circular dependencies. In v5 this dependency is inverted so  getstate and dispatch can be safer to use. 

### Goal
- [ ] have all the references to getstate and dispatch using the v5 version

### Tasks
- [x] Remove getstate and dispatch from store
- [x] REplace the refereces with v5
