### ISSUE TITLE
[2D MVP] Milestone 5: set vertical limits on new drawing

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5173]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/594
Autocalibration works by using GIS coordinates to set the calibration vectors only in the ground plane. For managing the vertical boundary the user must enter it. For providing a framework so autocalibration can work we'll let the user set the 

### Goals
- [ ] As a user I want to be able to calibrate a drawing with the least amount of data provided from my end

### Tasks
- [ ] Add "bottom extent" and "top extent" fields to the new drawing form
- [ ] Add "bottom extent" and "top extent" fields to the settings form
- [ ] Add "bottom extent" and "top extent" fields to the sidebar form when uploading a file (should it be readonly  @carmenfan when is an already existing drawing?)

### Related Resources
- Branch from #5163
- [Create drawing design](https://www.figma.com/design/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?node-id=8-43844&t=Zf6MeI4K4IChNu9Q-1)
- [Drawing settings design](https://www.figma.com/design/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?node-id=1834-38618&t=Zf6MeI4K4IChNu9Q-1)
- For the upload sidebar use your criteria on design

**Comment by carmenfan** [comment]
>  Add "bottom extent" and "top extent" fields to the sidebar form when uploading a file (should it be readonly @carmenfan when is an already existing drawing?)

Should behave the same way as other values within drawing settings, if they're read only then it should be read only

**Comment by carmenfan** [comment]
merged into #5038
