### ISSUE TITLE
Ticket filters (base branch)

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5188]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/521
We want to provide more powerful filters for tickets (also reusable for drawings). For this we need a a filters bar in which you can add filters and show the applied filters. 
This filters bar can collapse or expand. When is collapsed the user can see one line of filters (represented as pills) but if the filters go beyond that, a button with "show more" shows up and when clicking that, the filters bar expands to show everything. The user can click "clear all" to clear the whole filters section. 

- The idea is to provide a general component that will take in a value of filters (like an input) and be able to delete individual filters/all collapse and expand. 
- So at this stage the filters are not added through the actual  bar with filter button  but as a prop value
- The filter pills should be a different component that would somehow make the bar be aware that you want to delete them? (maybe a filters context?) 

<details>
<summary>Pills/chips specification</summary>
A property can contain one or more search values.

With a single search values it looks like this, showing the search value:
<img width="162" alt="Screenshot 2024-11-05 120143" src="https://github.com/user-attachments/assets/e80b6a69-7e52-4110-a07d-011746de2833">

With multiple search values it looks like this, where the search value has been replaced with the amount of search values for that filter  ( in this case with the phrase "2 filters"). It also has a minor ui change by being underlined :
<img width="176" alt="image" src="https://github.com/user-attachments/assets/92d169d0-5b7e-4121-8fd2-9e0a213453fa">

There's a selected state for the chip. It will look like this on hover or on selected:
<img width="200" alt="image" src="https://github.com/user-attachments/assets/aec0b21d-019e-473f-a650-7203b5792445">

There should be a way to subscribe to the onclick of the chip so it can be selected in a following issue.

There's a width limit on the chip, if the contents of the chip surpasses that it should cut it off and show ellipsis like in here:
<img width="200" alt="image" src="https://github.com/user-attachments/assets/aec0b21d-019e-473f-a650-7203b5792445">

There are several search criterias: 
Here's the list with their respective icons:
<img width="215" alt="image" src="https://github.com/user-attachments/assets/6e090cca-74f2-422a-9b1c-c4a06a0acff8">
<img width="215" alt="image" src="https://github.com/user-attachments/assets/827c81b1-a200-4cd2-91c3-0641cc46815d">

</details>

<details>
<summary>filters bar layout</summary>

- The filters bar have a **clear all (x)** button on the top right   that will delete the whole filter criteria. **(note: clear all(x) position TBD as from the moment is inconsistent with another state)** 

- When the chips goes over one line it shows a division line with a "Show less" to collapse to one line like here:

<img width="515" alt="image" src="https://github.com/user-attachments/assets/cb975ab1-2dbc-41b7-a95b-86ddf65b811a">

**(note: clear all(x)  position TBD as from the moment is inconsistent with another state)** 

- The properties filters by module will be grouped inside the filters by with  the module title on top like this:
<img width="364" alt="image" src="https://github.com/user-attachments/assets/c0bdfd4f-a8e4-4604-b083-ce14d2eef8e7">

</details>

### Goals
- [ ] I want to have a general search component to reuse 

### Tasks
- [ ] Create a Filter Bar component which contains the filter pills
- [ ] Make the Filter Bar collapsible/expandible based on the amount and length of filter pills
- [ ] Create the filters pills
- [ ] Detect filter pills deletion (single pill or clear all)
- [ ] Provide a mean to create new pills (this is can be a temporary hack)

### Suggestion 
- Provide an input interface like value/onChange, etc so we can use it in the same manner as other inputs
- Create its own context (filtersContext?)

### Related Resources
[MockUp](https://www.figma.com/design/nboKoEopFrXIrOAYTJQHru/Filters?node-id=681-73193&node-type=canvas&t=Pw4J21JOdy9CnhZz-0)
