### ISSUE TITLE
Improve global styles

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#5194]
### Description
Everytime we create a button from scratch, we need to set `cursor: pointer`, which should be implicit in the button component.
Also, changing the padding for something affects the box size as opposed to its content because, by default, `box-sizing` is set to `content-box`.

### Suggested solution
In the global css file, set 
```css
button {
    border: none;
    cursor: pointer;
}
* {
    box-sizing: border-box;
}
```

### Goal
- [ ] Make css writing less tedious

### Tasks
- [ ] Apply those CSS styles to all the components
- [ ] Make sure components UI does not change after those changes
