### ISSUE TITLE
Only allow users/jobs to be assigned to a ticket if they have commenter+ access.

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5209]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/590

We want to do 3 things here:

- Add an endpoint to fetch users with container/federation access 
- Add an endpoint to fetch jobs with container/federation access 
- add middleware validation for:
  - Custom ticket assignee property: Can only assign job/user who has commenter+ access to the container/federation
  - Custom ticket general oneOf/ManyOf propery: Can only assign job/user who has viewer+ access to the container/federation

#### Endpoints
route: `GET /teamspaces/{teamspace}/projects/{project}/{type}/{model}/members`
description: Returns all users who have access to this model (including teamspace admins, project admins)
permissions: viewer+
query string: Option query string `exludeViewers`, if set to true, do not include any users who only have viewer access.
response:
````js
{
  users: [
    "username-1",
    "username-2",
     //...
   ]
}
````

route: `GET /teamspaces/{teamspace}/projects/{project}/{type}/{model}/jobs`
description: Returns all jobs who have users that have access to this container/federation
permissions: viewer+
query string: Option query string `exludeViewers`, if set to true, do not include any job who only have users with viewer access.
response:
````js
{
  jobs: [
    "job1",
    "job2",
     //...
   ]
}
````

### Goals
- [ ] As a project admin I want to make sure that only users who have access to the container/federation will be communicated to within the container/federation so no messages will be lost due to lack of access
- [ ] As  a project admin I want to make sure that users who have sufficient privilege can be assigned to a ticket so that they can respond accordingly.

### Tasks
Endpoint 1
- [x] Create route, processor and model methods
- [x] Add unit and e2e tests
- [x] Add documentation

Endpoint 2
- [x] Create route, processor and model methods
- [x] Add unit and e2e tests
- [x] Add documentation

Other Tasks
- [x] Amend Assignees property funcionaliy
- [x] Amend oneOf and manyOf properties functionality
