### ISSUE TITLE
Email notifications for custom tickets

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5211]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/419

We want to implement a basic implementation of email notifications around custom tickets. This should be a daily email digest (triggered by the [scheduler](https://github.com/3drepo/3drepo.io/tree/master/backend/src/scripts/utility)), to send email to relevant members of a teamspace.

A flag on the teamspace should determine whether an email should be sent.

#### Teamspace AddOn flag
Add a new teamspace addOn flag to denote whether daily digest email notifications should be sent. This should operate like existing addOn flags, where it is configured by a utility script.

#### V5 notification service
Add a notification service that hooks onto the following activities
- New Ticket
- Ticket Updated
- Ticket comment added

Then create a notification if the following situation occurs:
##### Ticket assigned/assignment changed
If ticket assignment has changed (or has been first assigned), generate notification messages for the relevant user/users. If a Job has been assigned, then only users within a job with access to the model should be notified.

A Notifcation record should be generated in `internal` database `notifications` with the following schema

````js
{
  _id: <UUID>,
  user: "username",
  type: "TICKET_ASSIGNED",
  timestamp: <date>,
  data: { 
    teamspace: "<teamspace>",
    project: <project id>,
    model: "<model id>"
    ticket: <ticket id>    
  }    
}
````

##### Ticket updated
On any situation where the ticket is updated (properties updated, new comments), generate a notification message for the assigned users as well as the owner. If a Job has been assigned, then only users within a job with access to the model should be notified.

````js
{
  _id: <UUID>,
  user: "username",
  type: "TICKET_UPDATED",
  timestamp: <date>,
  data: { 
    teamspace: "<teamspace>",
    project: <project id>,
    model: "<model id>"
    ticket: <ticket id>,
    author: "user who changed the ticket",
    changes: { 
      // similar to change log schema
    }    
  }    
}
````
Or if a comment is added

````js
{
  _id: <UUID>,
  user: "username",
  type: "TICKET_UPDATED",
  timestamp: <date>,
  data: { 
    teamspace: "<teamspace>",
    project: <project id>,
    model: "<model id>"
    ticket: <ticket id>,
    author: "user who changed the ticket",
    comment: { 
      // comment id and message
    }    
  }    
}
````

##### Ticket resolved/closed/voided
When a ticket is resolved/voided,  generate a notification message for the assigned users as well as the owner.

````js
{
  _id: <UUID>,
  user: "username",
  type: "TICKET_CLOSED",
  timestamp: <date>,
  data: { 
    teamspace: "<teamspace>",
    project: <project id>,
    model: "<model id>"
    ticket: <ticket id>,
    author: "<person who closed it>",
    status: "<status value>"
  }    
}
````

#### Email notification script
Create a utility script that will trigger email notification to all users with notification, within a teamspace that has notifications enabled. The script is designed to be executed once a day thus it should be a daily digest of activities within the last 24 hours.

Mock up of the email can be found here: https://www.figma.com/design/pKGmv8qhbtuh4vRJLLi7kO/3D-Repo-Notifications-%26-Tasks?node-id=798-15088&node-type=frame&t=6pwtUztRtOccFxgE-0

Note: The link should be a URL to the viewer with the tickets filtered. consult frontend to confirm what that url should look like.

### Goals
- As a customer account, when I request email notifications, all my users will receive the below template.
- As a commentor+, I cannot opt out when my organisation has chosen for users to receive notifications.
- As a commentor+, I will receive a daily digest of all custom tickets assigned to me or a "job" that I am assigned to provided I have access to that federation/container.
- As a commentor+, I will only receive an email if there is something to be notified for - if I receive no notifications, there will be no email.
- As a commentor+, I will be able to click a link against " of tickets assigned to you", this will open the custom ticket list in the viewer with a filter against the relevant custom tickets.
- As a commentor+, I will be able to click a link against " of tickets have changed", this will open the custom ticket list in the viewer with a filter against the relevant custom tickets.
- As a commentor+, I will be able to click a link against " of tickets resolved, closed or voided", this will open the custom ticket list in the viewer with a filter against the relevant custom tickets.

### Tasks
- [x] Teamspace flag
  - [x] Add a flag for emailDigest
  - [x] Add to the AddOn script to allow it to be enabled/disabled
  - [x] Add tests
- [x] Notification service
  - [x] Create notification service
    - [x] Inits at launch
    - [x] Listens to relevant events and create notifications
        - [x] On new ticket
        - [x] On batch create
        - [x] on ticket updated
            - [x] Create ticket updated notification
            - [x] Create ticket assigned notification
            - [x] Create ticket resolved notification  
        - [x] on new comment
  - [x] Create model file for notifications
    - [x] Add functions to add notifications
  - [x] Check compatibiltiy with v4 
- [x] Email script
  - [x] Create script to trigger email
  - [x] Construct email template
    - [x] mock up the structure
    - [x] inject css to header
    - [x] loop through template to generate table per container
    - [x] construct data and email links
- [x] Wrap up
  - [x] think about indexing the notifications
  - [x] Jobs to users - permissions in model
  - [x] Move tickets notifications to a tickets file
  - [x] Ensure unique recipients
  - [x] Check remove user deletes notifications
  - [x] Check remove teamspace deletes notifications
  - [x] Check user still in teamspace
  - [x] Check if initialiser still makes sense
    - [x] Notification model shouldn't have an init call
  - [x] Error handling
  - [x] Figure out why emails come truncated
