### ISSUE TITLE
Email Notifications - Tickets url

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5213]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/419
For email notifications we need a way to link some tickets to the email, for this we are adding a url param with the tickets:
`<viewerURL>??tickets=ISS:1,ISS2,RSK:1..`
The filter will show in the search box.

### Goals
- [ ] As a user I want to be able to click a link and show the viewer with a filtered list of tickets

### Tasks
- [ ] Add URL to show the filtered tickets
- [ ] Show the Selected filters in the search box

### Related Resources
![image](https://github.com/user-attachments/assets/5edce3a9-2a16-49e9-a09d-04c59bfc487a)

**Comment by sanmont3drepo** [comment]
@carmenfan shouldnt we have a way to clear the filters for the tickets?
