### ISSUE TITLE
Custom tickets show only allowed users/jobs in the assignee list 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5235]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/590
ATM the list of users/jobs in a custom issue shows all teamspace/jobs. This means that you can assign users/jobs to a ticket while the user/job doesnt have permissions for that federation/container.  For fixing this we are adding some endpoints to fetch the right data.
would recommend to branch from #5209

### Goals
- [ ] As a admin/collab I want to be able to assign tickets to users that have permissions to access the ticket.
- [ ] As a user I only want to be assigned to  tickets that I have permissions to .

### Tasks
- [ ] Add endpoints to api for fetching the assignee list (mock them if backend is not ready)
- [ ] Add fetchs and integration in the ticket card

### Related Resources
[endpoint specs](https://github.com/3drepo/3drepo.io/issues/5209)
