### ISSUE TITLE
Slope measurements

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5243]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/392
Currently is not possible to measure slopes, to  fix this we want to be able to make slope measurements.
This will be shown in the measurements card and in measurements in issues and risks.
It will follow the same workflow as the reset of the measurements:
- Click on slope measurement -> changes the viewer into slope measurement mode
- Add the measurement in unity -> appears in the measurement list
- Edit the measurement on the list -> reflects in unity

_(note: this needs the unity viewer to be updated)_

### Goals
- [ ] As a collaborator I want to able to manage slope measurments in the measurement card
- [ ] As a collaborator I want to able to manage slope measurments in issues and risks

### Tasks
- [ ] Create the slope type in measurements
- [ ] Create the slope type in issues
- [ ] Create the slope type in risks

### Related Resources
[MockUp](https://www.figma.com/design/tmkgqJQlhjV8oUdhQwkHzr/Measurements?node-id=167-30342&node-type=frame&t=cxyhIinxqKfxpubL-0)

**Comment by FJThiel** [comment]
Changes done by me on the side of the viewer and UnityUtil:
- There is a new mode accepted by the method setMeasureToolMode in UnityUtil. Calling it with the parameter "Slope" will switch to the new measurement tool in the viewer
- There is a new method named setMeasureToolSlopeUnit() in UnityUtil. It takes a single parameter that can be either "Degrees" or "Percentage". It changes how the value of the slope is displayed since it can be expressed as degree or as %.
- The viewer is now able to commit slope measurements to the frontend. They have the same format as the other measurements. The meaning of their fields is as follows:
```
uuid -> uuid
value -> slope gradient in degrees
type -> 3
positions -> array of three positions (location the user selected, normal direction, slope direction)
color -> color
```

**Comment by FJThiel** [comment]
@Amantini1997 
Just FYI, I put an updated build here. Most important change is that it exposes control over the cursor to the frontend. Sebastian thinks that it is best in the long run for the frontend to control the cursor and not the viewer (see our conversation [here](https://github.com/3drepo/3drepounity/pull/558#discussion_r1846887807)).

**Comment by sebjf** [comment]
fyi the viewer side is in staging now, but has not been rebuilt yet

**Comment by carmenfan** [comment]
@sebjf  can you/felix rebuild this now since you have access to a pro license? I can do it if needed, just wondering 😆

**Comment by sebjf** [comment]
Hi @carmenfan, yes I can rebuild this now! just given it a go on the PR for this issue...

**Comment by sebjf** [comment]
@carmenfan I have successfully rebuilt the viewer without the splash screen, so the one on this branch can be merged when the units menu is added!
