### ISSUE TITLE
Add the ability to add query ticket list API

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5244]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/521

We want to be able to do the query server side to better serve large amount of tickets with custom property filtering.

#### Endpoint changes

Endpoint: https://www.3drepo.io/docs/#/Tickets/GetTicketList
additional query string: `query`, `limit`, `skip`

##### Query
see https://github.com/3drepo/3drepo.io/wiki/Custom-Ticket-Query-Filters

##### Limit
Limit should be supported to restrict the number of results returned by the endpoint.

e.g. `limit=10` denotes we should only return 10 results

If undefined, we will return all tickets as appropriate

##### Skip
Skip should be supported to allow the user to skip the first n entries for pageination purposes

e.g. `skip=100` denotes we should skip the first 100 results returned.

by default, skip is 0.

### Goals
- [x] As 3D Repo admin, I want to ensure modules and properties cannot start with `$` to ensure queries are not ambiguous.
- [ ] As a 3D Repo user, I want to be able to filter for tickets that matches a specific condition
- [ ] As a 3D Repo API user, I want to be able to pageinate my results to better handle the size of data.

### Tasks
- [x] Add limit and skip to the existing params
- [x] Create a query schema to validate query param
- [x] Dissallow module names / properties to start with dollar sign
- [ ] Amend the processor to convert all these to a mongo query
- [ ] Add extra unit tests
- [ ] Add extra e2e tests
- [ ] Amend documentation
