### ISSUE TITLE
We should avoid using UnityUtil outside the `ViewerService` 

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#5254]
### Description
Right now, there are a few places where we call `UnityUtils` methods, mainly calibration components.
It is preferable to use ViewerService (which wraps those methods and then provides an API to call them) instead.

### Suggested solution
Invoke the equivalent UnityUtils methods from ViewerService instead. If missing, create them.

### Goal
- [ ] Avoid using UnityUtils directly from components outside the Viewer

### Tasks
- [ ] Identify the places (outside the ViewerService) where UnityUtils methods are invoked
- [ ] If missing, create the wrapper for those methods in ViewerService (note: I use the word "wrapper", but they might be more than mere wrapper. For instance, instead of just awaiting for the viewer to be ready and then call the UnityUtils method, they may contain more logic to provide a more concise API that better reflects the frontend needs. Use discretion)
- [ ] Replace those UnityUtils methods with ViewerService methods
