### ISSUE TITLE
Ticket filters: string filter form

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5264]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/521
Properties depicted as string will use this filter form. Also the basic fields for tickets which are not defined as "property"; title, description and id.

String properties have the following criterias  for filtering 
<img width="242" alt="image" src="https://github.com/user-attachments/assets/77feab78-26cf-401e-93cf-dc2c2bb656b1">

When selecting 'equals', 'does not equals', 'contains', 'does not contains'  a text field will appear with a + symbol will appear to the right of the field. Clicking on + will create another field so the user can search any string that matches several strings. If there is more than one field  - will be enabled to let the user get rid of fields if they change their mind.
<img width="446" alt="image" src="https://github.com/user-attachments/assets/454d158f-ae0f-48c0-b1d4-59c140bf91c1">
Once the user filled these fields apply will be enabled and if clicked here it will add the filter to the list.

If the user selected 'Exists' or 'Does not exists' the no other field will be presented and the apply button will be enabled.

### Goals
- [ ] As a user I want to filter by strings in the tickets list

### Tasks
- [ ] Create filter form specific to string (operators and input type)
- [ ] Add string validation
- [ ] The structure is very similar to group filters, see if that can be re-used

### Related Resources
[MockUp](https://www.figma.com/design/nboKoEopFrXIrOAYTJQHru/Filters?node-id=823-43606&node-type=section&t=5P2O7r9RqRYKLdbp-0)

**Comment by carmenfan** [comment]
Merged into #5188
