### ISSUE TITLE
Ticket filters: select filter form

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5266]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/521
Properties typed as `oneOf` or `manyOf` has several fixed options. For filtering these the filter form has to show a multiple selections (like with `manyOf`). Apart from the properties that are typed as oneof and manyof this is the form that also matches templates. 
Properties of type `manyOf` with values `jobsAndUsers` are tackled in a different issue.

Select filter form has "equals" ,  "not equals", "contains",   "does not contains", "exists" and "does not exists" criteria:
<img width="263" alt="image" src="https://github.com/user-attachments/assets/8d99bd45-0e60-4bba-9310-6adbfdc25719">

And for values a multiselect input with all the possible values
<img width="284" alt="image" src="https://github.com/user-attachments/assets/d4bb0f4e-1831-48af-8f40-b0080b958da9">

After selecting one or more  values apply button is enabled and after clicking it the  filter is added/updated in the filters bars

### Goals
- [ ] As a user I want to be able to filter tickets by the properties that has limited amount of options
- [ ] As a user I want to be able to filter tickets by the template type

### Tasks
- [ ] Make values accept array
- [ ] Many 'template' and 'oneOf' properties with 'equals' or 'not equals' operators use single select
- [ ] Make 'template' and 'oneOf' properties with 'contains' or 'not contains' operators use multi select
- [ ] Make 'manyOf' properties use multiselect

### Related Resources
[MockUp](https://www.figma.com/design/nboKoEopFrXIrOAYTJQHru/Filters?node-id=823-43806&node-type=section&t=25jy2lyTqa9Z96ir-0)

**Comment by sanmont3drepo** [comment]
Merged into main branch
