### ISSUE TITLE
Ticket filters: date filter form 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5267]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/521
For filtering tickets by date type properties we need to add a date type filter form. 
"Created at" has "pastDate" type but should be treated as date.

<details>
<summary> The criterias supported by  this form are "equals", "On or before", "On or after", "In Range" , "Not in range",   "Exists" or "Does not exists" </summary>
<img width="309" alt="image" src="https://github.com/user-attachments/assets/252c8517-8f51-46bf-8f5c-4fa25fbf2bbe">
<br />
<img width="309" alt="image" src="https://github.com/user-attachments/assets/b38c4170-a42e-426f-8dfc-4984a2d9e951">
<br />(the design in figma might be a bit outdated)
</details>

- If the criteria chosen is "Exists" or "Does not exists" the form becomes valid and the filter can be added to the list.
<details>
<summary> If the criteria selected is "Equals", "On or before" or "On or after" then the form shows a single datepicker field with a (+) button to add more values. 
</summary>
<img width="250" alt="image" src="https://github.com/user-attachments/assets/72533e26-4a67-4f5d-ab94-b321835a9e01">
</details>
 
<details>
<summary> If the criteria selected is "In Range"  or "Not in range" then the form shows two datepickers fields with a (+) button to add more values. </summary>
<img width="389" alt="image" src="https://github.com/user-attachments/assets/2c06e5c5-9399-48d1-809a-cda5426b2b72">
</details>

 

### Goals
- [ ] As a user I want to be able to filter the tickets list by date type properties

### Tasks
- [ ] Create date type
- [ ] Show only valid operators (beware, some operators have the same icon, but different label)
- [ ] Add validation (for range, disable old dates according to existing value, e.g. if 'from' is set, 'to' should not allow earlier dates)

### Related Resources
[MockUp  "On or after" ](https://www.figma.com/design/nboKoEopFrXIrOAYTJQHru/Filters?node-id=823-43956&node-type=section&t=TWYpz9ckGbvN57su-0)

[MockUp "date range"](https://www.figma.com/design/nboKoEopFrXIrOAYTJQHru/Filters?node-id=681-73193&node-type=canvas&t=TWYpz9ckGbvN57su-0)

[MockUp "multi date range"](https://www.figma.com/design/nboKoEopFrXIrOAYTJQHru/Filters?node-id=823-44957&node-type=section&t=TWYpz9ckGbvN57su-0)
