### ISSUE TITLE
Ticket filters: number filter form

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5268]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/521
Parent issue: https://github.com/3drepo/3drepo.io/issues/5267
We need to be able to provide users with a way of filtering tickets by number typed properties. 

<details>
<summary>The criterias available for number properties are "Equals", "Does not Equals", "Greater than", "Greater than or equal to", "Less than", "Less than or equal to", "In range", "Not in range", "Exists" or "Does not exists" </summary>
<img width="389" alt="image" src="https://github.com/user-attachments/assets/7a826280-8355-4fc7-99e9-42a4b8ffeb48">
</details>

- If the criteria chosen is "Exists" or "Does not exists" the form becomes valid and the filter can be added to the list.

<details>
<summary> If the criteria selected is "Equals", "Does not Equals", "Greater than", "Greater than or equal to", "Less than" or "Less than or equal to" then the form shows a single textfield with a (+) button to add more values. 
</summary>
<img width="377" alt="image" src="https://github.com/user-attachments/assets/4d7b639f-d634-4acc-b962-b6b775249612">
</details>

- If the criteria selected is "In Range"  or "Not in range" then the form shows two textfields with a (+) button to add more values. 

### Goals
- [ ] As a user I want to be able to filter tickets by number typed fields.

### Tasks
- [ ] Create filter form specific to numbers (operators and input type)
- [ ] Add input validation

### Related Resources
[MockUp ](https://www.figma.com/design/nboKoEopFrXIrOAYTJQHru/Filters?node-id=823-44241&node-type=section&t=Abr4f9cZ2vBp6Zzq-0)

**Comment by sanmont3drepo** [comment]
Merged into  main ticket filters branch #5188
