### ISSUE TITLE
Ticket filters: integration with backend.

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5270]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/521
We are going to use the filtering from the backend in order to not fetch all the tickets data. Based on https://github.com/3drepo/3drepo.io/issues/5244 we should  

### Goals
- [ ] As a user I want to be able to filter tickets

### Tasks
- [ ] Add fetch endpoints in API files 
- [ ] Modify sagas to use the endpoints
- [ ] Modify selectors to show the filtered tickets
- [ ] Wire up ticket card to use these 

### Related Resources
[Endpoint specification](https://github.com/3drepo/3drepo.io/issues/5244)

**Comment by sanmont3drepo** [comment]
Merged into the base branch
