### ISSUE TITLE
Viewpoints in comments

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5272]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/583
to match issues and safetibase functionality we need the comments in tickets to be able to contain viewpoint information.

<details>
<summary> Creating a new comment </summary>
When creating a new comment the comment form has now a checkbox that indicates if the comment will be saved with viewpoint information.
<br />
<br />
<img width="474" alt="image" src="https://github.com/user-attachments/assets/59f7cfa9-96e0-4771-b8c1-1b581f8c678d">
</details>

<details>
<summary> Comments written by the user </summary>

On hover 

</details>

### Goals
- [ ] As a commentor+, I want to be able to automatically create a viewpoint as part of my comment.
- [ ] As a commentor+, I want to be able to have a checkbox that I can opt out of if I do not want a viewpoint on my comment.
- [ ] As a commentor+, I want to be able to only have a viewpoint as my comment.
- [ ] As a commentor+, I want to be able to modify a viewpoint when I edit my comment
- [ ] As a commentor+, I want to be able to delete the viewpoint from my comment
- [ ] As a commentor+, I want to be able to have an indication/icon on my comment which shows that there is a viewpoint there.

### Tasks
- [ ] Update comment form to add a checkbox for saving the viewpoint
- [ ] 

### Related Resources
[MockUp](https://www.figma.com/design/wY9fEOmo2qBxikmCelAZwr/Custom-Tickets?node-id=154-12208&node-type=section&t=5uddy0c38AgnzyuH-0)

**Comment by sanmont3drepo** [comment]
Closed in favour of https://github.com/3drepo/3drepo.io/issues/5309
