### ISSUE TITLE
Custom Tickets: Tabular View Filter

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5299]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/311
We want to provide users with the freedom to filter tickets in the tabular view in the same way they can filter in the tickets card. For this we want to reuse the UI from tickets cards. 

- In this case the template option won't be in the filters list when showing the filters select list options,  the reason for this is that there's already a way for filtering the template via the select box in the top left part of the page
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/8d21e533-45b0-4190-a299-ff1c4e58008a">

The functionality is the same as with the tickets card.

### Goals
- [ ] As a user I want to filter by any searchable property (no images or viewpoints etc)

### Tasks
- [ ] Integrate filter ui from tickets card
- [ ] Integrate with backend ticket filtering

### Related Resources
[MockUp](https://www.figma.com/design/wLMpbhvZJsPpm2A7MyLdCG/Tabular-View-Filter?node-id=1-45&node-type=canvas&t=eG5sC85Tt7Vyw1b2-0)

**Comment by Didi-Kwan** [comment]
### Acceptance criteria


- [ ] Make sure the properties selection list includes all available options from all ticket template, regardless of status (active or deprecated), except this property: ticket template.
- [ ] Once the filter is applied, that property option is not available in the properties selection list anymore.
- [ ] If the filter is removed, that property option should reappear in the properties selection list.
- [ ] Make sure user can add/remove/update filters.
- [ ] Applied filter should appear on the filter bar as a pill.
- [ ] Make sure the filtering display on the pill is correct.
- [ ] If the pills goes over the length limit of the filter bar, user should be able to view all pills using scrollbar.
- [ ] The filter bar is collapsible.
- [ ] Update the table or all tables if grouping applied when applying/removing/updating filters.
- [ ] Make sure the filtering work as intended such that the filtered tickets inside the tables match with the result.
- [ ] Make sure the "Clear all" button can remove all pills and update the table or all tables if grouping applied.
- [ ] Existing functions such as add/remove models, group by, filter completed tickets, add tickets must continue to work as before.
