### ISSUE TITLE
Views in ticket comments

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5309]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/583
We want the ability for the users to create a views in comments.  This will also advance the pairing of features with issues & risks.
For doing so there's an update in the create comment form:
- Now there's a checkbox indicating that it will save the current viewpoint (by default is checked)
- If the checkbox is checked then when saving the comment the viewpoint will be saved also.
The create comment form will be reused for edition. So when you edit your comment it will look like creating a new comment with values preloaded (the images/text/viewpoint set) . Also the send comment icon is replaced by a (✖️) and a (✔️) icon indicating "cancel edition" and "save edition". 
When a comment is not being edited but it has view information there will be a small camera icon which the user can click to apply the comment's view.

### Goals
- [ ] As a commentor+, I want to be able to automatically create a viewpoint as part of my comment.
- [ ] As a commentor+, I want to be able to have a checkbox that I can opt out of if I do not want a viewpoint on my comment.
- [ ] As a commentor+, I want to be able to only have a viewpoint as my comment.
- [ ] As a commentor+, I want to be able to modify a viewpoint when I edit my comment
- [ ] As a commentor+, I want to be able to delete the viewpoint from my comment
- [ ] As a commentor+, I want to be able to have an indication/icon on my comment which shows that there is a viewpoint there.

### Tasks
- [ ] Add the view checkbox to the comment form
- [ ] Update the new comment redux bit to save the view if the checkbox is checked (@carmenfan I guess we need a backend issue to update the endpoint?)
- [ ] Update the save edited comment redux bit to save the view if the checkbox is checked (@carmenfan same as before)
- [ ] Modify the comment form to be reused in the edition mode
- [ ] Add the view icon on the comment if the comment have view information
- [ ] Apply the view when the user clicks on the view icon 

### Related Resources
[Mockup](https://www.figma.com/design/wY9fEOmo2qBxikmCelAZwr/Custom-Tickets?node-id=154-12208&t=LfsIppqOyfEYJoua-0)

**Comment by Didi-Kwan** [comment]
### Acceptance criteria / Additional goals


- [ ] As a commentor+, I want to be able to delete the comment and only have a viewpoint on my comment.
- [ ] As a viewer+, I want to be able to apply the comment's view when i click on the camera icon on the comment.
- [ ] As a viewer+, I want other's comment viewpoint update instantly when they modify the comment so that i can apply the updated comment's view.
