### ISSUE TITLE
Custom Tickets - Adjustable width columns

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5310]
### Description
Product issue:  https://github.com/3drepo/3D-Repo-Product-Team/issues/443
The ability to adjust the width of the columns in tabular view for a more comfortable experience.

Users are able to adjust the size of the columns by clicking and dragging the limits in between columns. When the users drags the column in any place the column in each table will change size. (beware of performance here)

When the user resizes an inner column  that makes the column on the right to move outwards(enlarging the column) or inwards (shrinking the column) . If resizing makes the columns on the right to expand beyond the page's viewport a scrollbar will show up down.  When the user scrolls this bar the tables collapse buttons stay fixed:

<img width="1078" alt="Screenshot 2024-12-17 164708" src="https://github.com/user-attachments/assets/ab1196ae-3b20-4109-8889-200a6d248680" />

### Goals
- [ ] As a viewer+, allow me to take a column and resize it.

### Tasks
- [ ] Refactor the column system to be able to set the width of a column.
- [ ] Update the ui to match the design

### Related Resources
[MockUp](https://www.figma.com/design/wLMpbhvZJsPpm2A7MyLdCG/Tabular-View-Filter?node-id=21-24447&t=v0azNyLcunmfRDa4-0)
