### ISSUE TITLE
Ensure properties are unique when tickets are being imported

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5319]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/466

We want to make sure that when multiple tickets are being [imported/updated](https://github.com/3drepo/3drepo.io/issues/4777), on properties that are defined as [unique](https://github.com/3drepo/3drepo.io/issues/4785), we want to ensure that tickets that are being updated/imported at the same time does not have the same value.

#### Example
consider this template:
````json
{
  "name": "Unique Prop Test",
  "code": "UNQ",
  "properties": [
    {
      "name": "Some unique value",
      "type": "text",
      "unique": true
   
    }
  ]

}
````
If we import tickets:

````json
{
  "tickets": [
    {
      "properties": {
        "Some unique value": "b",
        "Status": "Open"
      },
      "title": "test"
    },
    {
      "properties": {
        "Some unique value": "b",
        "Status": "Open"
      },
      "title": "test 2"
    }
  ]
}
````

Currently succeeds and we end up with `Some unique value` having the same value for the 2 tickets, when it shouldn't. Instead we should have checked this in the data validation middleware and rejected the request.

### Goals
- [ ] As a 3drepo project admin I want to ensure all the properties within my tickets marked as unique are truly unique

### Tasks
- [x] Build tests to check that the if a duplicate exists it gets rejected
- [x] Update the middleware logic to check for duplicates

### Resource
- Info around custom ticketS:  https://3drepo-help.asite.com/en/?q=custom+ticket
