### ISSUE TITLE
Add view support in ticket comments

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#5326]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/583

We want to allow the user to add a viewpoint along with their comment within a ticket, so their comment can be associated to a viewer state to better describe what they want to explain.

#### About the comment
This field is not mandatory, but a comment should only be considered valid if it contains **at least** one of the following:
- A text comment
- image(s)
- viewpoint

i.e. a comment can be completely blank and only contains a viewpoint.

The viewpoint can also be added/edited/removed when the user edits their comment. naturally if the entire comment is removed, the viewpoint should also be removed.

The viewpoint should be stored as part of the comment history if it has been edited (just like the comment string).

#### Affected routes
- New comment https://staging.dev.3drepo.io/docs/#/Tickets/createComment
- Updating a comment https://staging.dev.3drepo.io/docs/#/Tickets/updateComment
- Importing tickets (which may have comments) https://staging.dev.3drepo.io/docs/#/Tickets/importTickets
- Updating multiple tickets (which may have comments) https://staging.dev.3drepo.io/docs/#/Tickets/updateManyTickets

#### Viewpoint schema
The viewpoint schema should be pretty much the same as the [`view` property type](https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/schemas/tickets/validators.js#L30) in custom tickets, with the exception that we will not be taking in a screenshot along the view.

### Goals
- [ ] As a commenter+, I want to be able to save the viewer state along side my comment so the reader can see what I'm describing.
- [ ] As a commenter+, I want to be able to change the viewer state when I edit the comment so I can correct it if I have made a mistake.
- [ ] As a commenter+ I want to be able to remove a viewer state with my comment if I have decided that it is not necessary.
- [ ] As a project admin, I want to make sure there is an audit trial on what is the viewer state that is being saved along with comments
- [ ] As a system integrator, I want to be able to import viewpoints alongside comments when I import/update tickets.

### Tasks
TBD by the developer

### Related Resources
UI mockup: https://www.figma.com/design/wY9fEOmo2qBxikmCelAZwr/Custom-Tickets?node-id=154-12208&t=jfMpUCpoqVmi0QtU-1
About comments: https://github.com/3drepo/3drepo.io/issues/3774
