### ISSUE TITLE
[2.1.3] Bug List

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#564]
**Actual Bugs:**
- [x] [Edit federation tab's X doesn't do anything](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340401779)
- [x] [The user can change units on Federation edit even though it's not allowed (and won't be updated)](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340402683)
- [x] [Model name restriction is unnecessarily strict](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340404474)
- [x] [Model tab doesn't go away when the model is uploading](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340405496)
- [ ] [Selected objects not saved with issue](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340408647)
- [x] [Tree highlighting it's a acting a bit weird](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340408712) `carmen`
- [ ] [Zoom out occasionally not working](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340410193) `carmen`
- [x] [The system is very confused when you try to access a model you dont' have permissions to](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340411174)
- [x] [Fed Tree doesn't display when one of the model is empty](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340417252)
- [x] [The client thinks my session has expired when it hasn't when I am accessing some permissions](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340418324)
- [x] [Profile update errors aren't displayed to the user](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340420059)
- [x] [Collapsing root and model nodes in tree not working properly](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340422904) `carmen`
- [x] [Issues list view doesn't update](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340426796)
- [x] [Show sub-models issues disappeared from issues menu](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340431456)
- [x] [Can't delete some jobs](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340432778)
- [x] Very occasionally the new issue button doesn't become enabled after load
- [ ] [Saved object group is not always highlighted when issue is selected](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340714584)
- [x] [VR flag is wiped when user info is updated](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340452268)
- [x] Expired session doesn't reset the model (#562 - closed)

**UI Oddities:**
- [x] [Generic error message when you try to change password with an invalid token](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340400147)
- [x] [UI is displaying the Error JSON object when upload failed](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340405941)
- [x] [Create federation dialog too wide](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340406189)

**Backend:**
- [ ] [Cleanup unhandled promises](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340479689)
- [x] [Cleanup console output](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340492394)

**Comment by carmenfan** [comment]
**Generic error message when you try to change password with an invalid token**
1. Trigger reset password
2. Go and reset the password
3. Use the same url again to try to reset password :+1: 
Token has expired (because it's used) which is good, but error displayed is generic:
![image](https://user-images.githubusercontent.com/11945337/32165447-bb356f12-bd5a-11e7-8b37-eff3470bf7bf.png)

@JamesMilnerUK  Not that important, If you want to just move it into a separate issue and put it in the backlog instead of fixing it in this release is fine with me

**Comment by carmenfan** [comment]
** Edit federation tab's X doesn't do anything**

1. Try to edit a federation
2. Press the "X" on the federation tab - it does nothing
![image](https://user-images.githubusercontent.com/11945337/32165771-ce0b6db6-bd5b-11e7-8cf4-c82e3aca718a.png)

**Comment by carmenfan** [comment]
**The user can change units on Federation edit even though it's not allowed (and won't be updated)**
If the user is editing a federation, units should be disabled (just like model settings)
![image](https://user-images.githubusercontent.com/11945337/32165949-446f40a4-bd5c-11e7-9eea-38b2c10ed2e4.png)

**Comment by carmenfan** [comment]
**Model name restriction is unnecessarily strict**

Model name (and federation name) are restricted to letters numbers underscores and hyphens only, when it should be anything in ASCII.

**Comment by carmenfan** [comment]
**Model tab doesn't go away when the model is uploading**
I Pressed `upload`, I can see on the teamspace that the model status is changed to `uploading`, but the tab is still there until the status is changed to `queued`.
![image](https://user-images.githubusercontent.com/11945337/32166489-e96179a0-bd5d-11e7-9570-73f5a78abcd5.png)

**Comment by carmenfan** [comment]
**UI is displaying the Error JSON object when upload failed**
This model upload failed with "SIZE_LIMIT_PAY" error (aka user ran out of quota), and this is what is displayed on the UI:
![image](https://user-images.githubusercontent.com/11945337/32166578-3218fad8-bd5e-11e7-8f81-42097517a70a.png)

**Comment by paloknapo** [comment]
**Create federation dialog too wide**

![image](https://user-images.githubusercontent.com/760452/32166663-7a0cb366-bd5e-11e7-831a-42aa7d97c14b.png)

**Comment by paloknapo** [comment]
**Selected objects not saved with issue**
Multi-select works as expected but selection is not saved.
https://dev.3drepo.io/Laika1030/2f4f31cb-1bca-43f2-a534-b316f3f6d2dd

**Comment by carmenfan** [comment]
Tree highlighting it's a acting a bit weird
2 things:
* Highlight an object in tree, the object doesn't look highlighted until you move the mouse to elsewhere: 
Mouse hovering on the node looked like this:
![image](https://user-images.githubusercontent.com/11945337/32167088-c6f4091c-bd5f-11e7-84cf-e1b83717aa47.png)
Mouse on something else looks like this:
![image](https://user-images.githubusercontent.com/11945337/32167112-dbcbdca2-bd5f-11e7-8895-a0c5371b3e02.png)


* Highlight something else on the tree, the first node doesn't get unhighlighted:
Clicked on first floor, the first floor is highlighted but the root node is still displayed as highlighted:
![image](https://user-images.githubusercontent.com/11945337/32167147-f4d9a5da-bd5f-11e7-9be9-e1eddd7beeda.png)

Works fine if the highlight came from clicking on model...

**Comment by paloknapo** [comment]
**Zoom out occasionally not working**
When camera goes through a wall zoom out stops working for both scroll wheel and right-click and drag. Try here:
https://dev.3drepo.io/Laika1030/2f4f31cb-1bca-43f2-a534-b316f3f6d2dd

**Comment by carmenfan** [comment]
The system is very confused when you try to access a model you dont' have permissions to:
* Go to pavol's link without logging into Laika (link [here](https://dev.3drepo.io/Laika1030/2f4f31cb-1bca-43f2-a534-b316f3f6d2dd)):
It first thinks your session is invalid (it's not):
![image](https://user-images.githubusercontent.com/11945337/32167648-73a09a4e-bd61-11e7-85e6-79adbc23f060.png)

Then tells you the model failed to load or it doesn't exist (technically neither, as it's more to do with you were not authorised)!
![image](https://user-images.githubusercontent.com/11945337/32167681-8bbb16cc-bd61-11e7-8b9a-dd295ee0f487.png)

**Comment by paloknapo** [comment]
**Highlighting in tree doesn't reset**
Highlighting objects in tree stays.  
![image](https://user-images.githubusercontent.com/760452/32168648-6133fe60-bd65-11e7-8283-96e8ae554b99.png)

**Comment by carmenfan** [comment]
**Fed Tree doesn't display when one of the model is empty**
* Create a federation with 2 submodels, one with actual model and the other empty. The model loads and everything, but the tree is stuck:
![image](https://user-images.githubusercontent.com/11945337/32168638-5811eb9e-bd65-11e7-8045-855cb9f1b4ca.png)

**Comment by carmenfan** [comment]
The client thinks my session has expired when it hasn't when I am accessing some permissions:
Select Andrew's teamspace in the model permissions tab:
![image](https://user-images.githubusercontent.com/11945337/32168851-0aee6440-bd66-11e7-8c44-487db00eddbc.png)

The system thinks my session has expired (it hasn't):
![image](https://user-images.githubusercontent.com/11945337/32168867-14baf57e-bd66-11e7-9504-ea3c9e935c66.png)

Redirects me to login page, and complains that' i'm already logged in when i try to log in:
![image](https://user-images.githubusercontent.com/11945337/32168900-31b1dbd4-bd66-11e7-9347-4f0d6e123301.png)

I don't think I have any permission changing rights on any of andrew's model, so that teamspace probably should not have been on the list.

**Comment by carmenfan** [comment]
**Profile update errors aren't displayed to the user**

Try to change my email address to another address that is being used by another account, it failed (which is good), but it doesn't tell me:
![image](https://user-images.githubusercontent.com/11945337/32169219-75d5862a-bd67-11e7-9a9b-83db6ffe6215.png)

**Comment by paloknapo** [comment]
**Collapsing root and model nodes in tree not working properly**
It doesn't collapse all sub nodes as expected.
![image](https://user-images.githubusercontent.com/760452/32169662-6401a71a-bd69-11e7-90f3-15eca76217fd.png)

**Comment by paloknapo** [comment]
**Chat server not working**
New issue doesn't show up if collaborator created it. I get this error:
![image](https://user-images.githubusercontent.com/760452/32170306-f1890fa4-bd6b-11e7-849a-027eb8eaef27.png)

**Comment by paloknapo** [comment]
**Show sub-models issues disappeared**
I can't show sub-model issues in federation.
![image](https://user-images.githubusercontent.com/760452/32171135-149ca4f8-bd6f-11e7-9aac-336543894fb4.png)

**Comment by paloknapo** [comment]
**Can't delete some jobs**
Some jobs can be deleted, some not.
![image](https://user-images.githubusercontent.com/760452/32171416-e6db9bfe-bd6f-11e7-8bea-f43e553a763d.png)

**Comment by carmenfan** [comment]
**VR flag is wiped when user info is updated**
We introduced a secret `vrEnabled` flag in the user profile to determine if VR bundles should be generated in this release. This flag is being cleared when someone updates their info on 3drepo.io

**Comment by Charence** [comment]
Cleanup unhandled promises

**Comment by Charence** [comment]
**Cleanup console output**

**Comment by JamesMilnerUK** [comment]
Very occasionally the new issue button doesn't become enabled after load

**Comment by paloknapo** [comment]
**Saved object group is not always highlighted when issue is selected**
Object saved with an issue are sometimes not highlighted, I can't really reproduce when. It all works fine after reload.

**Comment by carmenfan** [comment]
Merged in as 2.1.4. Any further updates should be in [here](https://github.com/3drepo/3drepo.io/issues/565).
