### ISSUE TITLE
[2.1.4] Bug List

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#565]
**Reproducible bugs**
- [x] [Symbols are not displaying correctly in model name](https://github.com/3drepo/3drepo.io/issues/565#issuecomment-340800855)
- [x] [Model tab doesn't go away when the model is uploading](https://github.com/3drepo/3drepo.io/issues/565#issuecomment-340802365)
- [x] [The status of the model is stuck on "uploading" until you refresh the page if import model failed during upload](https://github.com/3drepo/3drepo.io/issues/565#issuecomment-340803184) `charence`
- [x] [Caching error everytime we upgrade or switch to/from maintenance](https://github.com/3drepo/3drepo.io/issues/565#issuecomment-341050856)
- [x] [Can't select units when creating federation](https://github.com/3drepo/3drepo.io/issues/565#issuecomment-341364729)
- [x] [Can't save project with selected model](https://github.com/3drepo/3drepo.io/issues/565#issuecomment-341377901)
- [x] [Can't change status of issue assigned to my job](https://github.com/3drepo/3drepo.io/issues/565#issuecomment-341386412)
- [ ] [Dialog errors for API requests that fail override session expired timeout](https://github.com/3drepo/3drepo.io/issues/565#issuecomment-341392497)
- [ ] Token validation fails if token is invalid, but doesn't show error (unhandled promise)

**Unreproducible bugs:**
- [x] [Saved object group is not always highlighted when issue is selected](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340714584)
- [x] [Zoom out occasionally not working](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340410193)

**Clean up**
- [x] [Cleanup unhandled promises](https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340479689) `charence`

**Comment by JamesMilnerUK** [comment]
Still some issues with add issue button not triggering correctly

**Comment by carmenfan** [comment]
Symbols are not displaying correctly in model name
* Created a model with a strange looking name:
![image](https://user-images.githubusercontent.com/11945337/32232709-91c3504e-be50-11e7-87e3-1aa462f7e5a5.png)
* On teamspace listing it's displayed as this:
![image](https://user-images.githubusercontent.com/11945337/32232756-ac4d15e4-be50-11e7-8361-24c3d6a9904c.png)
* and Model setting:
![image](https://user-images.githubusercontent.com/11945337/32232766-b431be40-be50-11e7-8c35-d7acf56bb851.png)
* Inside the model: (It's different model but you get the idea)
![image](https://user-images.githubusercontent.com/11945337/32232795-c4cde152-be50-11e7-8566-ccce93b53cd8.png)

**Comment by carmenfan** [comment]
**Model tab doesn't go away when the model is uploading**
Still happening:
[Model tab doesn't go away when the model is uploading] (https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340405496)

**Comment by carmenfan** [comment]
**The status of the model is stuck on "uploading" until you refresh the page if import model failed during upload**
Still happening (2nd part of this): https://github.com/3drepo/3drepo.io/issues/564#issuecomment-340405941

**Comment by carmenfan** [comment]
**Caching error everytime we upgrade or switch to/from maintenance**
We gotta solve this, we can't ask every user to clear the cache everytime we update.

**Comment by paloknapo** [comment]
**Can't select units when creating federation**
![image](https://user-images.githubusercontent.com/760452/32318664-cf402c48-bfaf-11e7-8832-40facb9a5364.png)

**Comment by paloknapo** [comment]
**Can't save project with selected model**
Created fresh new project, created fresh new model.
![image](https://user-images.githubusercontent.com/760452/32321075-d1952496-bfb7-11e7-8ca4-d6d5c0bb8e43.png)

**Comment by paloknapo** [comment]
**Can't change status of issue assigned to my job**
![image](https://user-images.githubusercontent.com/760452/32322454-7578656a-bfbc-11e7-8126-944e6e6e08c0.png)

**Comment by JamesMilnerUK** [comment]
Dialog errors for API requests that fail override session expired timeout

**Comment by paloknapo** [comment]
**Highlighting not working on old models**
Try here:
https://dev.3drepo.io/pavol/fd19b76f-e935-4c7c-8b26-02d6fa98575c

**Comment by JamesMilnerUK** [comment]
@carmenfan can you confirm that the old models wouldn't appear in production? Thanks

**Comment by carmenfan** [comment]
We had to regenerate trees for the last release (2.0) and I made sure the trees generated in production was 2.2 compatible so yes, should work.

**Comment by JamesMilnerUK** [comment]
Token validation fails if token is invalid, but doesn't show error (unhandled promise)
![screenshot_20171103_143217](https://user-images.githubusercontent.com/8822075/32378890-cec7cca4-c0a3-11e7-983b-c822d002a41c.png)
