### ISSUE TITLE
Bug List [2.1.5]

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#571]
- [x] Error with session expiration logic on the client, causing not to log out on expiration
- [x] [Error message when you edit description of an issue](https://github.com/3drepo/3drepo.io/issues/571#issuecomment-342133172)
 - <s> [Cannot edit a comment](https://github.com/3drepo/3drepo.io/issues/571#issuecomment-342133374) </s> (Pavol wanted it gone)
- [x] [I can change the priority of the issue even though the issue is closed](https://dev.3drepo.io/testingMe/c480fb00-000f-4be3-bc0c-d23e22c97dbd/issues/faf46300-c2ec-11e7-9bfc-e10cb99d5374)
-  [x] [You can enter an empty federation](https://github.com/3drepo/3drepo.io/issues/571#issuecomment-342139104)
- [x] [Changing of units are enabled again for edit federation](https://github.com/3drepo/3drepo.io/issues/571#issuecomment-342139791)
- [x] [Inconsistency with Add * tabs]()
- [x] [I am teamspace admin but apparently I do not have permissions to add an issue](https://github.com/3drepo/3drepo.io/issues/571#issuecomment-342143701)

**Comment by carmenfan** [comment]
**Error message when you edit description of an issue**

Create an issue:
![image](https://user-images.githubusercontent.com/11945337/32440877-020055f0-c2ed-11e7-991f-ae1c40be57f3.png)

Edit the description:
![image](https://user-images.githubusercontent.com/11945337/32440891-13109fe4-c2ed-11e7-9df4-4bdf5327f298.png)

Gets an error (though I don't see any error on the network console)

Refresh the page - the issue description has changed:
![image](https://user-images.githubusercontent.com/11945337/32440920-301e7a52-c2ed-11e7-8d86-eeb572154aa6.png)



(note: this user has no job)

**Comment by carmenfan** [comment]
**Cannot edit a comment**
Posted a new comment:
![image](https://user-images.githubusercontent.com/11945337/32440970-5a5383da-c2ed-11e7-905f-398b2704de3c.png)


There is no edit button anymore?

**Comment by carmenfan** [comment]
**I can change the priority of the issue even though the issue is closed**
Priority should also be disabled when the issue is closed

**Comment by carmenfan** [comment]
**Occasionally highlight is not being displayed bug is still here:**

Just triggered it:
![image](https://user-images.githubusercontent.com/11945337/32441495-dabcc14c-c2ef-11e7-8eb5-bac3801c5313.png)

**Comment by carmenfan** [comment]
** You can enter a federation of no models **

If you click on an empty model, it prompts you to upload.

If you click on an empty federation, it just goes straight inside (which has nothing). This should spawn the edit federation dialog, similar to what empty model is doing

**Comment by carmenfan** [comment]
**Changing of units are enabled again for edit federation**

![image](https://user-images.githubusercontent.com/11945337/32441933-650a5e44-c2f1-11e7-91a8-ef0d65447721.png)

Just to be clear - you can change units when you CREATE a federation, but not when you are EDITING.

**Comment by carmenfan** [comment]
**Inconsistency with Add * tabs**
New model has a title that says "new model":
![image](https://user-images.githubusercontent.com/11945337/32442158-4b96f20a-c2f2-11e7-84b7-06f817cab6e0.png)

New Federation has a title says "federation":
![image](https://user-images.githubusercontent.com/11945337/32442179-59b3a5d6-c2f2-11e7-81cc-80000883d7d6.png)

New Project has a title that says "edit project"
![image](https://user-images.githubusercontent.com/11945337/32442188-6577be70-c2f2-11e7-91c9-851e9d5973ab.png)


New project tab should def not be called "edit project".

**Comment by carmenfan** [comment]
**I am teamspace admin but apparently I do not have permissions to add an issue**
![image](https://user-images.githubusercontent.com/11945337/32442442-5ca5bd1e-c2f3-11e7-9257-8fc7030ab3d0.png)
sometimes I am allowed after the model has loaded. seems to happen more often on [this model ](https://dev.3drepo.io/carmen/b91d2192-aa0e-4e2b-9457-2693e1d624cc)than others for some reason
