### ISSUE TITLE
2.3.2 Bug list

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#594]
- [x] [Can't type in clipping plane box](https://github.com/3drepo/3drepo.io/issues/594#issuecomment-344270723)
- [x] [Issue component bug](https://github.com/3drepo/3drepo.io/issues/594#issuecomment-344271361)
<del> - [Use powered by 3D Repo in Bryden Wood custom environment](https://github.com/3drepo/3drepo.io/issues/594#issuecomment-344284570) </del> (this is 2.2 prod environment changes)

---NOT BUGS---
- [x] [Clipping plane arrows step by  unit](https://github.com/3drepo/3drepo.io/issues/594#issuecomment-344278066)

**Comment by paloknapo** [comment]
**Can't type in clipping plane text box**

**Comment by paloknapo** [comment]
**Issue component bug**
![image](https://user-images.githubusercontent.com/760452/32784214-1f5d1228-c946-11e7-8607-8bdda4143d3a.png)

**Comment by paloknapo** [comment]
**Clipping plane arrows step by unit**
![image](https://user-images.githubusercontent.com/760452/32785377-4950e782-c949-11e7-9c43-0ef08a34491a.png)

**Comment by paloknapo** [comment]
**Use powered by 3D Repo in Bryden Wood custom environment**
Logo saved here
3D Repo Team Folder\UI\BrydenWood\BWpoweredBy.png

**Comment by JamesMilnerUK** [comment]
Can't type in clipping plane box is semi fixed. Still a problem with Unity. Will attempt https://github.com/3drepo/3drepounity/issues/69 to fix

**Comment by JamesMilnerUK** [comment]
Can confirm #595 fixes this but requires more work
