### ISSUE TITLE
[v2.3.3] Bug List

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#597]
- [x] [Clipping plane jumps when you control it using multiple ways](https://github.com/3drepo/3drepo.io/issues/597#issuecomment-344680398)
- [x] [Clipping plane not at the right place when you load an issue](https://github.com/3drepo/3drepo.io/issues/597#issuecomment-344682960)
-  [x] [Direction toggle does not change when you load an issue viewpoint](https://github.com/3drepo/3drepo.io/issues/597#issuecomment-344683950)
- [x] [Comments are not being saved](https://github.com/3drepo/3drepo.io/issues/597#issuecomment-345218780)

**Comment by carmenfan** [comment]
**Clipping plane jumps when you control it using multiple ways**
* Alter the value by typing
![image](https://user-images.githubusercontent.com/11945337/32852652-8fc42bd8-ca30-11e7-8653-09ac94ceef30.png)

* Press once on the down arrow key (Or press down on keyboard):
![image](https://user-images.githubusercontent.com/11945337/32852693-ab25fc80-ca30-11e7-9daf-47406b75ecc5.png)

It makes a massive jump to the the end of the slider

**Comment by carmenfan** [comment]
**Clipping plane not at the right place when you load an issue**

* Create an issue with a clipping plane that is not the model units:
![image](https://user-images.githubusercontent.com/11945337/32853025-d5379d84-ca31-11e7-9e93-860aa701d8a3.png)

* Load it , it's not clipping at the right place:
![image](https://user-images.githubusercontent.com/11945337/32853051-f1f05326-ca31-11e7-8e52-1171befdcd78.png)

* If you set it to original model units, the clipping plane is correct:
![image](https://user-images.githubusercontent.com/11945337/32853076-0c7b4dfe-ca32-11e7-98e3-51ab34f14ccc.png)

**Comment by carmenfan** [comment]
**Direction toggle does not change when you load an issue viewpoint**
* Enable toggle then click on a viewpoint:
![image](https://user-images.githubusercontent.com/11945337/32853228-82ffda3a-ca32-11e7-99dc-c7bef3a956aa.png)
* Disable toggle then click on a viewpoint that has a clip that goes the other way also doesn't update:
![image](https://user-images.githubusercontent.com/11945337/32853259-9ac36038-ca32-11e7-8b7d-603aee1acd81.png)

**Comment by carmenfan** [comment]
**Comments are not being added.**
 API returns 200 but comments are gone when you refresh
