### ISSUE TITLE
Bugs and features for 3D Diff/Clash

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#637]
- [x] [Target model tab doesn't highlight when clicked](https://github.com/3drepo/3drepo.io/issues/637#issuecomment-351027216)
- [x] [Enable Diff still activated when new model loaded](https://github.com/3drepo/3drepo.io/issues/637#issuecomment-351027726)
- [x] [Clipping plane slider updating broken](https://github.com/3drepo/3drepo.io/issues/637#issuecomment-351061031)

**Comment by paloknapo** [comment]
**Target model tab doesn't highlight when clicked.**

It is selected but the green bar on top stays at Base tab. 
![image](https://user-images.githubusercontent.com/760452/33882796-4bab6ae0-df31-11e7-81f3-581fe18ccdc6.png)

**Comment by paloknapo** [comment]
**Enable Diff still activated when new model loaded**

Button keeps hanging. I diffed on one model, went to teamspace, opened other model, button still yellow.

![image](https://user-images.githubusercontent.com/760452/33882922-b73ec3ec-df31-11e7-9ee2-51c24fbd1ffe.png)

**Comment by paloknapo** [comment]
**Clipping plane slider updating broken**

I created an issue with clipping plane activated, moved slider & spinned the model, went back to freshly created issue, clipping plane updated to saved position but slider stayed.
![image](https://user-images.githubusercontent.com/760452/33888659-a0df8488-df45-11e7-8bb0-fe36f9799901.png)
