### ISSUE TITLE
Dev 2.5.5 bugs

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#666]
- [x] [Can't create a new account](https://github.com/3drepo/3drepo.io/issues/666#issuecomment-354994786) (maybe fixed by https://github.com/3drepo/3drepo.io/commit/8471b974670fa3e9d15b0b69567669f540b86b77)
- [x] [Remove license sometimes doesn't work and gives error](https://github.com/3drepo/3drepo.io/issues/666#issuecomment-354995464) (maybe fixed by https://github.com/3drepo/3drepo.io/commit/8471b974670fa3e9d15b0b69567669f540b86b77)
- [x] [Can't remove Job](https://github.com/3drepo/3drepo.io/issues/666#issuecomment-354996253) (maybe fixed by https://github.com/3drepo/3drepo.io/commit/8471b974670fa3e9d15b0b69567669f540b86b77)
- [ ] [IFC spaces appear even if the Hide IFC spaces is active](https://github.com/3drepo/3drepo.io/issues/666#issuecomment-355001481)
- [ ] [Ghosted geometry in Diff](https://github.com/3drepo/3drepo.io/issues/666#issuecomment-355004309)
- [x] [PayPal error crashes server](https://github.com/3drepo/3drepo.io/issues/666#issuecomment-355005289)
- [ ] [DIFF - Latest revision as Base model even if the previous one is loaded in Viewer](https://github.com/3drepo/3drepo.io/issues/666#issuecomment-355005322)
- [x] [Getting "Cannot remove assigned jobs" on jobs that aren't assigned](https://github.com/3drepo/3drepo.io/issues/666#issuecomment-355044379)
- [x] Editing federation takes a while, Processing message sticks

Oddities:
- [x] Decimeters as default units, make it millimeters

**Comment by paloknapo** [comment]
**Can't create a new account**
Says: System error. Please try again later.

![image](https://user-images.githubusercontent.com/760452/34519565-893f6be8-f07c-11e7-9ff6-1aacb72c4216.png)

**Comment by paloknapo** [comment]
**Remove license sometimes doesn't work and gives error **

![image](https://user-images.githubusercontent.com/760452/34519660-fa111c5e-f07c-11e7-8a43-a6e8f136913a.png)

**Comment by paloknapo** [comment]
**Can't remove Job**

The job is not assigned to any user, yet I can't get rid of it.

![image](https://user-images.githubusercontent.com/760452/34519801-c84f5252-f07d-11e7-9743-c61d3a1c09f9.png)

**Comment by paloknapo** [comment]
**IFC spaces appear even if the Hide IFC spaces is active**

1. Isolate few objects and create issue
2. Show All
3. IFC spaces appear even if the Hide IFC spaces is active

**Comment by paloknapo** [comment]
**Ghosted geometry in Diff**
Diff gives funny results, it looks like geometry behind an object is Xrayed ???
![image](https://user-images.githubusercontent.com/760452/34521196-674c9df0-f084-11e7-88be-36a0e0c5fd4c.png)

**Comment by JamesMilnerUK** [comment]
**PayPal Error crashes server**

Trying to access undefined property

**Comment by paloknapo** [comment]
**DIFF - Latest revision as Base model even if the previous one is loaded in Viewer**

![image](https://user-images.githubusercontent.com/760452/34521343-318c3710-f085-11e7-818c-2326ba6c9d67.png)

**Comment by carmenfan** [comment]
**Getting "Cannot remove assigned jobs" on jobs that aren't assigned**

there are 3 license holders in my teamspace:
![image](https://user-images.githubusercontent.com/11945337/34527241-d9d796e6-f09c-11e7-9fd8-f55852ffab50.png)

But when I try to delete client, it's giving me the error message:
![image](https://user-images.githubusercontent.com/11945337/34527278-f87b02ae-f09c-11e7-8a59-e0b7fdea3c7d.png)

**Comment by carmenfan** [comment]
deploying what we have right now, all remaining bug fixes please put it in https://github.com/3drepo/3drepo.io/issues/670
