### ISSUE TITLE
Dev 2.5.6 bugs

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#670]
- [x] [Valid username (that is too long?) is getting an erroneous error message](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355246924)
- [x] [Poor handling of lack of permission on model in federation in compare tool](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355256660)
- [x] [allNodes has no length which throws error](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355269080)
- [x] [Dodgy clipping plane appears on issues without clipping plane saved](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355307525)
- [x] [Zooming with scroll wheel doesn't work when measuring](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355331713)
- [x] [ISSUE URLs don't work](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355343567)
- [ ] [Issues in federation: saved object selection forgotten if one model removed from fed](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355347087)
- [ ] [objectsPromise problem if no objects are hidden](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355358474)
- [x] [Tree: nodes gone missing when a node expanded](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355532266)
- [ ] [Unity error which is not Unity error](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355540529)
- [ ] [Console error when opening existing issue](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355541669)
- [ ] [Issues menu: Created by list multiplied](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355543858)
- [ ] [Highlighting doesn't occasionally work](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355580971)
- [x] [Lots of errors regarding could not find pin with name](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355585243)
- [ ] [I don't know what happened there, I just switched to helicopter mode](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355624470)

**Comment by carmenfan** [comment]
**Valid username (that is too long?) is getting an erroneous error message**
![image](https://user-images.githubusercontent.com/11945337/34559184-cfcfd25c-f138-11e7-87b5-783f8ed63fbe.png)

**Comment by JamesMilnerUK** [comment]
Poor handling of lack of permission on model in federation in compare tool

**Comment by JamesMilnerUK** [comment]
**allNodes has no length which throws error**

**Comment by paloknapo** [comment]
**Dodgy clipping plane appears on issues without clipping plane saved**

1. Go to issue with clipping plane saved
2. Go to issue without clipping plane - plane appears at slider position 0 or sometimes in the middle of model
Test on Sample_House

**Comment by paloknapo** [comment]
**Zooming with scroll wheel doesn't work when measuring**

**Comment by carmenfan** [comment]
**ISSUE URLs don't work**
- Open an issue (URL should change)
- refresh the page

URL gets shorted to the default model URL, Issue does not open

**Comment by paloknapo** [comment]
**Issues in federation: saved object selection forgotten if one model removed from fed**

**Comment by Charence** [comment]
objectsPromise problem if no objects are hidden

![2018-01-04](https://user-images.githubusercontent.com/1438332/34578175-dbb85c04-f17b-11e7-8b22-ad1d22e8989e.png)

**Comment by paloknapo** [comment]
**Tree: nodes gone missing when a node expanded**

There is excessive white space when a node is expanded and rest of the tree is not visible. This sorts itself out when working with the tree for a bit.  

1. load this model
https://dev.3drepo.io/Laika0104/fde1cff8-fffc-48cc-bed0-04b0409739be
2. open tree and expand/collapse "text - moved"
3. double-click on any object in Viewer, tree works fine now

![image](https://user-images.githubusercontent.com/760452/34607093-e879e7c6-f209-11e7-8868-ce548debab3a.png)

**Comment by paloknapo** [comment]
**Unity error which is not Unity error**

This is a mystery message which pops up occasionally but I can't reproduce it. After dismissing it, I can still navigate the model, create issues ... without difficulties, it's not memory related. 

![image](https://user-images.githubusercontent.com/760452/34608482-71e57ff6-f210-11e7-829a-6127272ee078.png)

**Comment by paloknapo** [comment]
**Console error when opening existing issue**

It doesn't affect issue, I can change flags and comment. Error appears every time I open an issue though.

![image](https://user-images.githubusercontent.com/760452/34608802-fd666efe-f211-11e7-8967-c5f969654ead.png)

**Comment by paloknapo** [comment]
**Issues menu: Created by list multiplied**

![image](https://user-images.githubusercontent.com/760452/34609273-f5a15b50-f213-11e7-878f-cfad3da058d7.png)

**Comment by paloknapo** [comment]
**Highlighting doesn't occasionally work**

Double-click on objects zooms to it, metadata also works, just highlighting is not always there. Tested on multiple machines with same problem.

1. Load this model
https://dev.3drepo.io/Laika0104/65619358-b8b9-4f57-a2c2-7343da2c34b4
2. Select an object

**Comment by carmenfan** [comment]
**Lots of errors regarding could not find pin with name**
- Open a model with pins in
- Exit the model, open another model
- Loads of errors pop up regarding not finding a pin.
![image](https://user-images.githubusercontent.com/11945337/34616022-b7a7150e-f22e-11e7-8e2d-054f3501362e.png)


If you've called clearCanvas, unity wipes the model , including pins. It's a bit weird that it's trying to address the pins of the old model when you enter the new model?

**Comment by paloknapo** [comment]
**I don't know what happened there, I just switched to helicopter mode**

![image](https://user-images.githubusercontent.com/760452/34622069-8fce84da-f243-11e7-8063-6a8e71e68026.png)

**Comment by carmenfan** [comment]
Closing for dev deployment, all existing issues please fix in https://github.com/3drepo/3drepo.io/issues/674
