### ISSUE TITLE
Dev Bugs 2.5.7

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#674]
- [x] [objectsPromise problem if no objects are hidden](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355358474)
- [x] [Issues menu: Created by list multiplied](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355543858)
- [ ] [Highlighting doesn't occasionally work](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355580971)
- [x] [I don't know what happened there, I just switched to helicopter mode](https://github.com/3drepo/3drepo.io/issues/670#issuecomment-355624470)  
- [x] [TypeScript compilation error on tree component](https://github.com/3drepo/3drepo.io/issues/674#issuecomment-355951300)
- [x] [Tree multiplication of content](https://github.com/3drepo/3drepo.io/issues/674#issuecomment-355972059)
- [x] [Clip appears on issues with no clipping set](https://github.com/3drepo/3drepo.io/issues/674#issuecomment-355977581)
- [x] [Navgiation control buttons don't go away once a navgiation control type has been selected](https://github.com/3drepo/3drepo.io/issues/674#issuecomment-355993352)
- [x] [Issues & Compare cards don't reset when exiting model](https://github.com/3drepo/3drepo.io/issues/674#issuecomment-356013488)
- [x] [Diff: Revision name not updated in Base model if different revision loaded in Viewer](https://github.com/3drepo/3drepo.io/issues/674#issuecomment-356248560)
- [x] [Eye on diff tool and eye on tree can go out of sync](https://github.com/3drepo/3drepo.io/issues/674#issuecomment-356254786)
- [x] [Adaptive diff threshold](https://github.com/3drepo/3drepo.io/issues/674#issuecomment-356616966)

**Comment by carmenfan** [comment]
@Charence @JamesMilnerUK  please confirm those are fixed/not fixed, just copied it from #670

**Comment by carmenfan** [comment]
**TypeScript compilation error on tree component**
![image](https://user-images.githubusercontent.com/11945337/34670288-830ba03a-f46d-11e7-9eea-060f382da8d1.png)

**Comment by paloknapo** [comment]
**Tree cancer**

Nodes in tree multiply if an issue with saved visibility is loaded before:
1. Open this:
https://dev.3drepo.io/andrew/85c38d1a-d787-4ed2-a4fd-96a155c558e7
2. Open tree
3. Open any issue with visibility status
4. Check tree, nodes multiply each time you open an issue

**Comment by Charence** [comment]
@carmenfan I have already removed 'public' from my version of tree.component in #673 to address **TypeScript compilation error on tree component**

**Comment by JamesMilnerUK** [comment]
***Clip appears on issues with no clipping set***

**Comment by carmenfan** [comment]
**Navgiation control buttons doesn't go away once a navgiation control type has been selected**
* Change "turnable" to "helicopter"
* you can see the position of helicopter and turntable has been swapped around, but the unselected one should go away, but currently it doesn't: 
![image](https://user-images.githubusercontent.com/11945337/34676939-6c9880ac-f486-11e7-8a2a-090705935e32.png)

**Comment by paloknapo** [comment]
**Issues & Compare cards don't reset when exiting model**

Content of previous model visible for a while when loading a new model.

**Comment by paloknapo** [comment]
**Diff: Revision name not updated in Base model if different revision loaded in Viewer**

Diff loads correct revisions, just wrong revision name is displayed
![image](https://user-images.githubusercontent.com/760452/34717180-0a982002-f52a-11e7-9744-e491f74d7738.png)

**Comment by carmenfan** [comment]
**Eye on diff tool and eye on tree can go  out of sync**
* load this https://dev.3drepo.io/carmen/6cb7debf-3b10-4941-87b3-2b6dc531f1b6
* hide clinic A from tree
* show clinic A from tree, the eye on diff tool is still shown as invisible
* if you try to toggle clinic A from the compare tool, it won't ever get shown as visible
(this may be related to to hidden IFC spaces. I think if tree eye is showing as partially visible diff tool should show as visible ?) 
![image](https://user-images.githubusercontent.com/11945337/34718263-f3a97676-f52d-11e7-89eb-6efc2d71744c.png)

**Comment by paloknapo** [comment]
**Adaptive diff threshold**

Canary Wharf project optimal threshold:
Threshold 10 is too much, ghosting artefacts appear when looking directly at a straight wall from short distance. 5 works fine with flat surfaces. With smaller than 5 flickering artefacts appear at pipes (round objects).
Threshold for other sizes varies, see examples below.
Extra large bounding box is about 20x20x20km - infrastructure
Large bounding box is about 100x100x100m - construction, Canary Wharf size
Medium bounding box is about 20x20x20m - small construction projects or components 

A3_CT_STRUCT
https://dev.3drepo.io/CWCL/cc0ffdd8-9938-49da-8b50-4eaa0f39db3f
NWD import
Threshold: 5
Units: mm 
Large bounding box 

A3_CT_ARCH
https://dev.3drepo.io/CWCL/4adf8419-11e6-4822-a123-e140622b9878
IFC import
Threshold: 5
Units: mm
Large bounding box

A3_CT_MEP_NGB
https://dev.3drepo.io/CWCL/67f42680-f41a-42f6-9115-509db8d2febb
NWD import
Threshold: 5
Units: mm
Medium bounding box

G3_MEP
https://dev.3drepo.io/CWCL/1851607b-8852-4e76-8132-ff8c4dce448c
NWD import
Threshold: 5
Units: mm
Large bounding box

roads
https://dev.3drepo.io/Laika0104/e15f478e-32f0-412d-8861-6ff0e593a136
FBX import
Threshold: 5
Units: m
Extra large bounding box

Revit House
https://dev.3drepo.io/Laika0104/1445e89a-3cd4-4f96-b0c7-58150b3fae3e
IFC import
Units: mm
Threshold: default
Large bounding box

Light Tower 1
https://dev.3drepo.io/Laika0104/daf8e34a-0b56-412e-9e4e-2d2237418f34
FBX & NWD imports 
Compare rev 2 with rev3
Units: m
Threshold: 0.1
Medium bounding box

Lights m
https://dev.3drepo.io/Laika0104/dcec2bdb-df91-46d1-aa46-2f8493f2abec
OBJ import
Units: m
Threshold: default
Large bounding box

A14
https://dev.3drepo.io/Laika0104/e338efbd-043a-4e00-a7f6-be074e83c0b2
NWD import
Units: m
Threshold: default
Extra large bounding box
