### ISSUE TITLE
Dev Bugs 2.5.8

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#681]
- [x] [Timestamp error](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357652812)
- [x] [Tree nodes multiply](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357653989)
- [x] [Viewer tries to highlight objects after canvas is cleared](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357654969)
- [x] [idToMeshes is sometimes undefined](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357658096)
- [x] [Errors in console when typing illegal characters in model name](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357658957)
- [x] [Meta card X button not working](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357669221)
- [x] [Issues: Can't delete latest comment](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357669221)
- [x] [Compare: Base & Target models tab scrolls with models](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357693955)
- [x] [Compare card doesn't reset when leaving viewer](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357709059)
- [x] [Unity error, even error is not to do with Unity](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357737727)

**Comment by paloknapo** [comment]
**Timestamp error**

![image](https://user-images.githubusercontent.com/760452/34939693-b17a0516-f9e4-11e7-960d-4d49266683e9.png)

**Comment by paloknapo** [comment]
**Tree multiplies**

Tree nodes multiply if an issue with saved selection is opened before.

https://dev.3drepo.io/Laika0115/e0e2b45b-5c60-4238-a5c6-35df9683f0c2

![image](https://user-images.githubusercontent.com/760452/34939862-4c35dc56-f9e5-11e7-9734-188c9ee4aaba.png)

**Comment by paloknapo** [comment]
**Viewer tries to highlight objects after canvas is cleared**

![image](https://user-images.githubusercontent.com/760452/34940061-11c88bc6-f9e6-11e7-82c2-bb773132b330.png)

**Comment by JamesMilnerUK** [comment]
idToMeshes is sometimes undefined 
![spectacle m19475](https://user-images.githubusercontent.com/8822075/34940621-24d68068-f9e8-11e7-8f53-504f9b34ddcb.png)

**Comment by paloknapo** [comment]
**Errors in console when typing illegal characters in model name**

It doesn't allow illegal characters and works fine, just gives lots of errors in console. 

![image](https://user-images.githubusercontent.com/760452/34940709-851c9e8a-f9e8-11e7-933c-141a2128d80d.png)

**Comment by paloknapo** [comment]
**Meta card X button not working**

Remove it and the card can be switched on/off with Meta button, same as the other cards.

https://dev.3drepo.io/Laika0115/9bff3e87-b184-4a1c-8b70-bd5f7117d87d

![image](https://user-images.githubusercontent.com/760452/34942342-38bdf38e-f9ef-11e7-835f-0c53286db58f.png)

**Comment by paloknapo** [comment]
**Issues: Can't delete latest comment**

https://dev.3drepo.io/Laika0115/e0e2b45b-5c60-4238-a5c6-35df9683f0c2/issues/90110460-f9e9-11e7-b506-ff9f75e9b2a5

![image](https://user-images.githubusercontent.com/760452/34942648-510a9270-f9f0-11e7-88b8-894bdd0b0cab.png)

**Comment by paloknapo** [comment]
**Compare: Base & Target models tab scrolls with models**

![image](https://user-images.githubusercontent.com/760452/34946331-5d44a5d6-f9fe-11e7-8105-883a2e203dfe.png)

**Comment by paloknapo** [comment]
**Compare card doesn't reset when leaving viewer**

1. open federation
2. clash
3. go to teamsapce and open a model
4. check clash target models tab

![image](https://user-images.githubusercontent.com/760452/34948791-1060e358-fa06-11e7-8f07-64bcc1f555f3.png)

**Comment by JamesMilnerUK** [comment]
Unity error, even error is not to do with Unity

**Comment by Charence** [comment]
I'm not able to reproduce [idToMeshes error](https://github.com/3drepo/3drepo.io/issues/681#issuecomment-357658096). Please let me know the next time it is seen.
