### ISSUE TITLE
Dev Bugs 2.5.11

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#685]
- [x] CompareService.diffToolDisableAndClear should be ViewerService.diffToolDisableAndClear
- [x] [Travis front end e2e is broken as of 2.5.11](https://github.com/3drepo/3drepo.io/issues/685#issuecomment-359374404)
- [x] [Visibility not reset by issue if hiddenNodes null](https://github.com/3drepo/3drepo.io/issues/685#issuecomment-359813785)
- [x] [Add IFC space hidden flag to issue](https://github.com/3drepo/3drepo.io/issues/685#issuecomment-359876596)
- [x] <del>Backend sometimes brings back incorrect toggleState for top level models</del>(fixed in https://github.com/3drepo/3drepobouncer/issues/231)
- [x] Hide Import BCF
- [x] [Cannot highlight windows](https://github.com/3drepo/3drepo.io/issues/685#issuecomment-360433564)
- [x] Visibility states in tree (downward propagation)
- [x] <del> Sync Hide IFC UI menu button and TreeService state</del> (fixed in #677)
- [x] Fix mainTree when subTree is retrieved

**Comment by carmenfan** [comment]
**Travis front end e2e is broken as of 2.5.11**

See https://travis-ci.org/3drepo/3drepo.io/builds/329930337

**Comment by Charence** [comment]
**Visibility of all nodes not reset if hiddenNodes is null in issue**

Check if this is resolved in #686. If not, ensure ShowAllNodes (or equiv.) called when showing issue.

**Comment by Charence** [comment]
**Add IFC space hidden flag to issue**

Save IFC space hidden state in issue

**Comment by Charence** [comment]
**Cannot highlight windows**

![screenshot 2018-01-25 10 59 00](https://user-images.githubusercontent.com/1438332/35384968-d1f96b92-01be-11e8-86bd-b4a7c29736de.png)

**Comment by Charence** [comment]
Message for 97620dc is wrong. Should be #677.
