### ISSUE TITLE
The big list of backend refactoring TODOs

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#726]
- [x] modelhelper has a function called createAndAssigneRole that not only does that, but it also creates the model settings itself...  (#1223)
- [ ] modelhelper shouldn't even exist. Everything in there has a theme that should map to a separate file
- [ ] helper folder in the model directory doesn't make any sense. model is suppose to be direct mapping of database schemas.
- [x] We should get rid of mongoose in favour of a thin self made interface to mongo. It has been more of a hindrance than help.
- [x] Subscription schema is ridiculous, it can be immensely simplified (#763)
- [ ] model settings should not have a list of submodels, this can easily go out of sync with the real list of sub models.
- [ ] endpoints in model.js should proabbly be split into multiple different files. currently model settings, unity, json trees, x3d are all residing in model.js
- [x] UnityAsset.json should probably just be a bson object instead of being in gridFS (#1223)
- [ ] Model User and teamspace differently (even though they come from the same bson)
-  Account.json API:
     - [x] quota information is sent there when it's only ever used in the accounts billing page... (in #763)
- [ ] Account.json API is in the auth routes file when it has nothing to do with auth.
- [ ] There is a free space calculation (`_calSpace`) in model folder and there's another one within middleware(`freeSpace`)
- [ ] Updating billing information and updating subscriptions should be 2 different end points.
- [ ] Reorganise the route folder to reflect the hierarchy within the end points
- [ ] split `model/user.js` into `user` and `teamspace`
- [ ] Response codes is a mess. Should categorise things.
- [x] BCF import/export should live in its own file. (#1359)
- [ ] Not all end points are logged
- [ ] log username to end point logs
- [x] I don't think  models/repo is used anymore . Same for the entire repo folder
- [x] There is a comment count in issue schema which basically equates to comments.length (#1359)
- [ ] Functions for metadata endpoints should probably be moved from ModelHelper to Meta
- [x] Groups endpoints defy convention e.g. /groups/revision/... instead of /revision/:rid/groups

**Comment by carmenfan** [comment]
* Account should be renamed to teamspace or user 
* User endpoints/handling should be split into teamspace/user
* Enforce same linter as 3drepobouncer/bouncer_worker
* Support swagger documentation instead
* Response code error , allow additional of details
* Maybe all the routes with /revision/master/head should really just be a query string?
* Should just have a default responder that responds with whatever the promise returns, we have this we copy and paste this everywhere
![image](https://user-images.githubusercontent.com/11945337/106915524-01089c80-66fe-11eb-9e43-0cc0f131c95f.png)
* Also, for some reason we call APIInfo to get the place on these functions, but it's only ever used by responseCodes.respond, which has access to req....

**Comment by sanmont3drepo** [comment]
#### Proposal for creating containers 

Route: `HTTP POST /api/:teamspace/:projectid/`

Payload:
````js
{
  code: string,
  containerName: string,
  type: string,
  unit: string,
}
````

Which is a refactoring of  `HTTP POST /api/:teamspace/models/`

**Comment by carmenfan** [comment]
this is all a bit N/A due to v5.
