### ISSUE TITLE
Dev bugs 2.7.4

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#735]
- [x] [GIS Settings: Can't change Angle from North](https://github.com/3drepo/3drepo.io/issues/735#issuecomment-365245509)
- [x] <del>[GIS Settings: Can't select text with dragging mouse](https://github.com/3drepo/3drepo.io/issues/735#issuecomment-365245909)</del> _(CF: #737 should fix this)_
- [x] <del> [Console errors when in 3D viewer and maps activated](https://github.com/3drepo/3drepo.io/issues/735#issuecomment-365246561) </del> _(CF: OSM is choking - will be addressed in #739)_
- [x] [Current model map settings uses previous model settings](https://github.com/3drepo/3drepo.io/issues/735#issuecomment-365273770)
- [x] [Project point settings - negate Z](https://github.com/3drepo/3drepo.io/issues/735#issuecomment-365296022)
- [x] [Should make email compulsory and regex check it](https://github.com/3drepo/3drepo.io/issues/735#issuecomment-365590987)
- [x] [Navigation list doesn't go away after you've selected your new navigation style](https://github.com/3drepo/3drepo.io/issues/735#issuecomment-365603036)
- [x] [Helicopter mode doesn't travel well on gamepad](https://github.com/3drepo/3drepo.io/issues/735#issuecomment-365701051) _(Fixed in #737)_

**Comment by paloknapo** [comment]
**GIS Settings: Can't change Angle from North**

New value isn't saved when changed.

![image](https://user-images.githubusercontent.com/760452/36148682-c7a2ff46-10b4-11e8-89ee-c62925e2ec2d.png)

**Comment by paloknapo** [comment]
**GIS Settings: Can't select text with dragging mouse**

Double click or ctrl+A works

**Comment by paloknapo** [comment]
**Console errors when in 3D viewer and maps activated**

![image](https://user-images.githubusercontent.com/760452/36148883-761ebc68-10b5-11e8-99e1-a3cdd14b9959.png)

**Comment by paloknapo** [comment]
**Current model map settings uses previous model settings**

Loads map context from previous model, doesn't reset survey point after leaving viewer. All good after reload.

**Comment by paloknapo** [comment]
**Project point settings - negate Z**

Positive Z values move model below maps and vice versa which might be correct programming-wise but is confusing for user.

**Comment by carmenfan** [comment]
**Navigation list doesn't go away after you've selected your new navigation style**

I swear we fixed this in the last or the one before last release. (maybe worth putting a e2e test on this?)

clicking on the turnable button shows the list of navigations to check to/from (which is good):
![image](https://user-images.githubusercontent.com/11945337/36205996-b50791e2-1188-11e8-90a8-62c08f2e4502.png)

but clicking on helicopter button should make the list disappear (which it doesn't):
![image](https://user-images.githubusercontent.com/11945337/36206017-c3f519ea-1188-11e8-92a7-1a6bdecd2967.png)

**Comment by JamesMilnerUK** [comment]
@carmenfan I removed it because the way we were doing this was a massive hack. I can bring it back if you want, but you can just close it by hitting the helicopter again.

**Comment by carmenfan** [comment]
@JamesMilnerUK the expected behaviour is that it closes it so it is kina annoying. Is it time consuming/difficult/ugly?

**Comment by JamesMilnerUK** [comment]
@carmenfan not particularly for changing modes discretely, yes for clicking on the viewer to cancel mode changing.

**Comment by JamesMilnerUK** [comment]
@paloknapo I can't replicate 'GIS Settings: Can't change Angle from North'

**Comment by carmenfan** [comment]
Helicopter mode doesn't travel well on gamepad
