### ISSUE TITLE
2.7.5 buglist

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#750]
**Bugs:**
- [x] [Editing a federation and cancelling it still updates the submodel list](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366757162)
- [x] [API server is still actively listening to requests in maintenance mode](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366959062)
- [x] [Password policy is only enforced on signups](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366959820)
- [x] [List of issues to print is in random order](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366964810)
- [x] [Isolate doesn't work when it's done on a object selected by searched list](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366968714)
- [x] [Search is showing objects belonging to the previous commits](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366969786) ( _CF: James made a fix by filtering on the front end, but we should be filtering it on the backend on the db query instead_)
- [x] [Clip tool bug when coupled with issues](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366971974)
- [x] [Double check issue loading in Firefox](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366996572)
- [x] [Clear card if content fails to load](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-367023946)
- [x] [Show All highlights whole model if multi-mesh object was selected and isolated in Issue](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-367032247)
- [x] [Hidden object is selected](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-367032694)
- [x] [Action notification text in issues have a strange behaviour](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-368090816)

**UI Oddities:**
- [x] [Clearer error message on invalid email address](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366961279)
- [x] [Shorten the wording to "Creating a 3D Repo account is free"](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366950608)
- [x] [password prompt should not say "OK" until it is actually going to be accepted](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366949701)
- [x] [Font on Licenses & Jobs aren't consistent](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366962744)
- [x] [Unknown behaviour when the user changes teamspace during edit a project](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366963698)
- [x] [Screenshot tab misaligns when the screenshot size is nto the same as the user screen size](https://github.com/3drepo/3drepo.io/issues/750#issuecomment-366967342)

**Comment by carmenfan** [comment]
Editing a federation and cancelling it still updates the submodel list:

I have a federation:
![image](https://user-images.githubusercontent.com/11945337/36390036-6654f764-1599-11e8-9760-bcf36f6326ef.png)


I edit the sub model list:
![image](https://user-images.githubusercontent.com/11945337/36390046-6ff6261c-1599-11e8-8848-6e6021a1eb1c.png)


If I press the "X" on top right instead of cancel, the submodel list gets updated:
![image](https://user-images.githubusercontent.com/11945337/36390055-795e3190-1599-11e8-9f78-3ba1a98a1786.png)


Cancel works as intended though!

(this is probably e2e test worthy)

**Comment by carmenfan** [comment]
password prompt should not say "OK" until it is actually going to be accepted

Also maybe we should just set min. characters to be 8 instead of 9 

(Can we make the prompt to say "at least 8 characters instead of of more than 7? human instinct is to just glance through the prompt and pick up the most important info i.e. 7 and assume we need 7 characters.)

**Comment by carmenfan** [comment]
**Shorten the wording to "Creating a 3D Repo account is free"**
![image](https://user-images.githubusercontent.com/11945337/36421809-d0865c34-1631-11e8-9267-f9975a4f8ae9.png)

**Comment by carmenfan** [comment]
**API server is still actively listening to requests in maintenance mode**

**Comment by carmenfan** [comment]
**Password policy is only enforced on signups**

I can do whatever I want on this page
![image](https://user-images.githubusercontent.com/11945337/36423479-0238e070-1638-11e8-84de-4eca1a0ce10c.png)

**Comment by carmenfan** [comment]
**Clearer error message on invalid email address**

On sign up page - technically I filled in everything. 
![image](https://user-images.githubusercontent.com/11945337/36423590-7f178b1e-1638-11e8-8dd2-f8799bee694a.png)


Absolutely no prompt when I make changes here:
![image](https://user-images.githubusercontent.com/11945337/36423698-d4ebb3f8-1638-11e8-84cc-e638a9b7a45b.png)

**Comment by carmenfan** [comment]
**Font on Licenses & Jobs aren't consistent:**
![image](https://user-images.githubusercontent.com/11945337/36423975-b458c8a0-1639-11e8-8a6b-fa576054959f.png)
![image](https://user-images.githubusercontent.com/11945337/36423988-c04e7e52-1639-11e8-8c5b-9b02c7bb7e4a.png)

**Comment by carmenfan** [comment]
**Unknown behaviour when the user changes teamspace during edit a project**

The user currently can change the teamspace when he/she tries to edit a project name:
![image](https://user-images.githubusercontent.com/11945337/36424142-388b0ac0-163a-11e8-9f7e-92231e8d44d3.png)

If you change the name then hit save, that launches an erroneous API call. We should probably disable the drop down menu in edit mode.

**Comment by carmenfan** [comment]
**List of issues to print is in random order**

This is my issue list: 
![image](https://user-images.githubusercontent.com/11945337/36424336-d9002030-163a-11e8-994d-d0e6ab53826e.png)


This is the order on the print page:
![image](https://user-images.githubusercontent.com/11945337/36424344-df3a4f2a-163a-11e8-8ea2-6e79a1cbfbcb.png)

**Comment by carmenfan** [comment]
Screenshot tab misaligns when the screenshot size is nto the same as the user screen size

When it is the right dimension it looks perfect:
![image](https://user-images.githubusercontent.com/11945337/36424636-f24b1490-163b-11e8-970a-87f0bef56dc5.png)

When I have my console on the right , the tab has a lot of empty spaces:
![image](https://user-images.githubusercontent.com/11945337/36424712-3565c70c-163c-11e8-8104-0c6dc151661a.png)

Also notice how stretched my screenshot looks on that thumbnail....

And this is a screenshot that was done when I had the console up:
![image](https://user-images.githubusercontent.com/11945337/36424752-54ec89da-163c-11e8-96ca-ded19ab0b729.png)

Gets worse when the screenshot was done in significantly smaller screen dimension:
![image](https://user-images.githubusercontent.com/11945337/36424779-7180929e-163c-11e8-849a-bf6fb7f7b1c1.png)

**Comment by carmenfan** [comment]
Isolate doesn't work when it's done on a object selected by searched list:

I searched for walls and Highlighted one of the objects here:
![image](https://user-images.githubusercontent.com/11945337/36424950-083adcb2-163d-11e8-9a20-08bbea6f0480.png)

Clicked Isolate, see nothing:
![image](https://user-images.githubusercontent.com/11945337/36424982-2879d0b4-163d-11e8-940a-b6f84e1f36de.png)

**Comment by carmenfan** [comment]
**Search is showing objects belonging to the previous commits**
2 different entries, one I suspect belongs to an older commit (hence highlighting sometimes does not work.
![image](https://user-images.githubusercontent.com/11945337/36425146-d28ec9a6-163d-11e8-8414-5bb798d33f30.png)

**Comment by carmenfan** [comment]
**Clip tool bug when coupled with issues** 

Click on an issue with a clip plane defined:
![image](https://user-images.githubusercontent.com/11945337/36425530-1219d84e-163f-11e8-82c7-1cfd115ba082.png)

Change the units on the clip tool:
![image](https://user-images.githubusercontent.com/11945337/36425552-1a583afa-163f-11e8-860b-d16d17f16a70.png)


Click on an issue without clip plane, the model is clipped in weird place:
![image](https://user-images.githubusercontent.com/11945337/36425573-2aaff2ee-163f-11e8-9244-d97377ebf65e.png)

**Comment by Charence** [comment]
**Double check issue loading in Firefox**

Tree appears to update, but viewer doesn't update. Errors point to TraverseAndPushIds.

![treevisibility2](https://user-images.githubusercontent.com/1438332/36429794-80296d16-164b-11e8-911d-265a631e50b7.PNG)

**Comment by paloknapo** [comment]
**Clear card if content fails to load**

This is for any card. In example below, tree card loaded previous model tree when fulltree.json failed to load:
![image](https://user-images.githubusercontent.com/760452/36434377-cc7276a8-1656-11e8-9cdb-5b1eece5e5df.png)

**Comment by paloknapo** [comment]
**Show All highlights whole model if multi-mesh object was selected and isolated in Issue**

1. Create issue with multi-mesh object selected and isloated
2. Show All

**Comment by paloknapo** [comment]
**Hidden object is selected**

Hidden means hidden! 
Please follow "Out of sight out of mind" principle and deselect when hiding objects.

**Comment by Charence** [comment]
**Action notification text in issues have a strange behaviour**

When you change certain properties, such as Type, it will add a notification to the issue comments. This is fine for the new notification.

However, it seems to also affect the appearance of existing comments. The text of some notifications will disappear or change, e.g. for types, it reverts back to the internal value of "for_information" rather than "For Information". Sometimes screenshots disappear too from other comments.

Everything goes back to normal after a refresh of the issue.

![screenshot 2018-02-23 18 00 15](https://user-images.githubusercontent.com/1438332/36609001-776d9d08-18c3-11e8-920b-ea4dfef8d1ef.png)

**Comment by JamesMilnerUK** [comment]
Fixed #758 here

**Comment by JamesMilnerUK** [comment]
@Charence I can't reproduce the Firefox issue, any ideas?
