### ISSUE TITLE
2.7.6 buglist

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#760]
- [x] ~~Full~~ Better Solibri import support
- [ ] ~~[Issues: More than saved isolated selection shown in federation](https://github.com/3drepo/3drepo.io/issues/760#issuecomment-368842970)~~ Deferred to ISSUE #764 
- [x] [Issues: Changing any flag throws error](https://github.com/3drepo/3drepo.io/issues/760#issuecomment-368852158)
- [x] Save issue_id to groups
- [x] [Maps: Always keep the closest tiles even if they are partially out of the screen](https://github.com/3drepo/3drepo.io/issues/760#issuecomment-368898412)
- [x] [Error loading some issues](https://github.com/3drepo/3drepo.io/issues/760#issuecomment-369189107)
- [x] [Remove console logs](https://github.com/3drepo/3drepo.io/issues/760#issuecomment-369191470)
- [x] Use correct username for BCF import notification

UI oddities
- [x] [No Due Date icon](https://github.com/3drepo/3drepo.io/issues/760#issuecomment-368841569)
- [x] [Federation menu: Move Delete to the bottom](https://github.com/3drepo/3drepo.io/issues/760#issuecomment-368859038)
- [x] [Tree: Node expands one row below](https://github.com/3drepo/3drepo.io/issues/760#issuecomment-368909696)
- [x] Improve UX of import IFC

**Comment by paloknapo** [comment]
**No Due Date icon**

Keep it simple and aligned

![image](https://user-images.githubusercontent.com/760452/36725974-0289f122-1bb0-11e8-88cd-6fc8704b09eb.png)

**Comment by paloknapo** [comment]
**Issues: More than saved isolated selection shown n federation**

This issue should only show the footing object but trees are also visible:
https://dev.3drepo.io/pavol/d6f913ad-1432-47c3-bc46-8f551869dce6/issues/5dc86b90-1bb0-11e8-bd7c-c38b3b093976
![image](https://user-images.githubusercontent.com/760452/36726180-d1d266ee-1bb0-11e8-9c74-47562cca959f.png)

**Comment by paloknapo** [comment]
**Issues: Changing any flag throws error**
https://dev.3drepo.io/pavol/d6f913ad-1432-47c3-bc46-8f551869dce6/issues/8b47760e-ea3b-4c0e-afdf-500ac812034e
![image](https://user-images.githubusercontent.com/760452/36727733-42a6b33e-1bb6-11e8-8714-778b86c48a90.png)

**Comment by paloknapo** [comment]
**Federation menu: Move Delete to the bottom**
![image](https://user-images.githubusercontent.com/760452/36728942-64112a96-1bba-11e8-9825-b882b461b36c.png)

**Comment by paloknapo** [comment]
**Maps: Always keep the closest tiles even if they are partially out of the screen**
![image](https://user-images.githubusercontent.com/760452/36734519-9abac302-1bcb-11e8-9e0b-e0e515a3d326.png)

**Comment by paloknapo** [comment]
**Tree: Node expands one row below**
Open this issue and expand selected in tree
https://dev.3drepo.io/Laika0227/8725a694-1e3c-45ee-8a97-b42dd82b99e8/issues/d15fd920-1bcf-11e8-90da-7b64ac773596
![image](https://user-images.githubusercontent.com/760452/36736269-1774905e-1bd0-11e8-866c-6c55300ab4d7.png)

**Comment by carmenfan** [comment]
**Error loading some issues**
issue no. 13 on [this model](https://dev.3drepo.io/pavol/d6f913ad-1432-47c3-bc46-8f551869dce6/issues/ce4ffdb1-cd99-4165-bf02-2e6c070d4993)

![image](https://user-images.githubusercontent.com/11945337/36781664-6f9a888a-1c6e-11e8-98e1-8d568d0a6532.png)


server return error 500 with the following stack trace:
![image](https://user-images.githubusercontent.com/11945337/36781647-60862f66-1c6e-11e8-9a58-edb1084016f5.png)

**Comment by carmenfan** [comment]
**Removing console logs:**

![image](https://user-images.githubusercontent.com/11945337/36782091-b4d69d70-1c6f-11e8-9b61-62f3d8c89190.png)
![image](https://user-images.githubusercontent.com/11945337/36782107-c40f125e-1c6f-11e8-983e-746a73326ccd.png)

**Comment by Solidu** [comment]
Unable to create a comment with a photo in Solibri. Using another tool like BCFier to add a photo and bringing it back to Solibri does not work!

**Comment by carmenfan** [comment]
Hi @Solidu,

We don't work on Solibri so I believe you are posting on the wrong place?

If you would like to report a bug on 3drepo.io then please create a new issue detailing on how to replicate it.

**Comment by Charence** [comment]
> Unable to create a comment with a photo in Solibri. Using another tool like BCFier to add a photo and bringing it back to Solibri does not work!

@Solidu Are you importing or exporting BCF from 3D Repo? If you are continuing to have problems with 3D Repo, please provide more details in a new issue: https://github.com/3drepo/3drepo.io/issues/new
