### ISSUE TITLE
2.7.8 Bugs

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#774]
- [x] [Issues: visibility not saved](https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370391750)
- [x] [Issues: can't close imported issue](https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370392206)
- [x] [Issues: can't import BCF 2.1 (Solibri)](https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370393251)
- [x] [Issues: can't export BCF](https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370395002)
- [x] [Issues: doesn't highlight selected objects in imported BCF](https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370400728)
- [x] [No limit on Project name](https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370404487)
- [x] [No limit on Federation name](https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370407073)
- [x] [Metadata stopped working on this branch](https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370470289)
- [x] [BCF type and priority flags not imported](https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370721576)
- [x] [Deleting a project doesn't seem to remove the models within the project](https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370832135)

**Comment by paloknapo** [comment]
**Issues: visibility not saved**

Visibility status not saved in freshly created issue

**Comment by paloknapo** [comment]
**Issues: can't closed imported issue**

Try closing this one:
https://dev.3drepo.io/Laika0220/ea4afd9f-b4cd-4ce8-a8bb-5f9f266a01d0/issues/94ff63f5-5905-4610-9922-41fca8fde2fd

![image](https://user-images.githubusercontent.com/760452/36972990-259ec256-2069-11e8-965e-0ccd5b3de3f1.png)

**Comment by paloknapo** [comment]
**Issues: can't import BCF 2.1**

Test with this file:
https://www.dropbox.com/s/b9srtm64ku1pqqu/cube2_1_solibri2.bcf?dl=0

Shows "Uploading BCF" but nothing happens, just this in console:
![image](https://user-images.githubusercontent.com/760452/36973134-9b3206a4-2069-11e8-82ab-aa7fc3475257.png)

**Comment by paloknapo** [comment]
**Issues: can't export BCF**

{"place":"GET /issues.bcfzip","status":500,"message":"Internal Error","value":4000}

**Comment by paloknapo** [comment]
**Issues: doesn't highlight selected objects in imported BCF **

Try this:
https://dev.3drepo.io/Laika0220/4e37b3f0-e0ff-4f08-adcd-9bfab15b32b7/issues/8f4f6f0d-6fd7-461e-9e7d-e3ef3dd10aae

**Comment by paloknapo** [comment]
**No limit on Project name**

Please limit to 120 characters only as in models

**Comment by paloknapo** [comment]
**No limit on Federation name**

It allows more that 120 characters but pops up error when saving. Please limit to 120 characters as in models. 
![image](https://user-images.githubusercontent.com/760452/36975577-6cfe3312-2072-11e8-80e7-b525697bb000.png)
![image](https://user-images.githubusercontent.com/760452/36975586-73c93354-2072-11e8-8ecc-b23855ff89d7.png)

**Comment by Charence** [comment]
**Metadata stopped working on this branch**

![screenshot 2018-03-05 16 08 52](https://user-images.githubusercontent.com/1438332/36985592-9d047fe0-208f-11e8-934a-bc63732e5970.png)

**Comment by paloknapo** [comment]
**BCF type and priority flags not imported**

Import following flags please.
![image](https://user-images.githubusercontent.com/760452/37024945-3e27dea2-2122-11e8-9d27-6ac82d5a63c9.png)

**Comment by carmenfan** [comment]
**Deleting a project doesn't seem to remove the models within the project**

removing a project on the front end -> models still exist within the database. Everything to do with the project should be removed.

**Comment by carmenfan** [comment]
Merged into master. merge into staging work will be done in #789
