### ISSUE TITLE
Groups 

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#803]
- [ ] UI for groups
- [ ] Any backend changes
- [ ] DB migration script to add issue_id to groups belonging to issues
- [ ] [Colour Override toggle changes colour when active](https://github.com/3drepo/3drepo.io/issues/803#issuecomment-376463907)
- [ ] [Select group objects when entering edit mode](https://github.com/3drepo/3drepo.io/issues/803#issuecomment-376464287)
- [ ] [Focus to group in list view when leaving edit mode](https://github.com/3drepo/3drepo.io/issues/803#issuecomment-376464638)
- [ ] [Scale up card to get rid of scroll bar](https://github.com/3drepo/3drepo.io/issues/803#issuecomment-376465281)
- [ ] [Show number of objects in group and selected](https://github.com/3drepo/3drepo.io/issues/803#issuecomment-376465954)
- [ ] [Add Select Objects button in edit mode](https://github.com/3drepo/3drepo.io/issues/803#issuecomment-376466349)
- [ ] [Display group colour bar next to the group name and make Colour Picker button gray](https://github.com/3drepo/3drepo.io/issues/803#issuecomment-376467175)
- [ ] [Clever pop up when user wants to overwrite large group with small selection](https://github.com/3drepo/3drepo.io/issues/803#issuecomment-376467606)

Not implementing:
- [ ] [Make Isolate/Show All toggle button](https://github.com/3drepo/3drepo.io/issues/803#issuecomment-376463159)
Not really a togglable state

**Comment by carmenfan** [comment]
New functions to control colour override in unity-utils:
````js
	 /**
	 * Override the diffuse colour of the given meshes
	 * @param {string} account - teamspace the meshes resides in
	 * @param {string} model - model ID the meshes resides in
	 * @param {string[]} meshIDs - unique IDs of the meshes to operate on
	 * @param {number[]} color - RGB value of the override color (note: alpha will be ignored)
	 */
	public static overrideMeshColor(account, model, meshIDs, color) {
		const param: any = {};
		if (account && model) {
			param.nameSpace = account + "."  + model;
		}
		param.ids = meshIDs;
		param.color = color;
		UnityUtil.toUnity("OverrideMeshColor", UnityUtil.LoadingState.MODEL_LOADED, JSON.stringify(param));
	}

	/**
	 * Restore the meshes to its original color values
	 * @param {string} account - teamspace the meshes resides in
	 * @param {string} model - model ID the meshes resides in
	 * @param {string[]} meshIDs - unique IDs of the meshes to operate on
	 */
	public static resetMeshColor(account, model, meshIDs) {
		const param: any = {};
		if (account && model) {
			param.nameSpace = account + "."  + model;
		}
		param.ids = meshIDs;
		UnityUtil.toUnity("ResetMeshColor", UnityUtil.LoadingState.MODEL_LOADED, JSON.stringify(param));
	}
````

usage:
![override](https://user-images.githubusercontent.com/11945337/37904624-4dc4c2ee-30f4-11e8-994b-d2af40d6b9a2.gif)

**Comment by paloknapo** [comment]
Make Isolate/Show All toggle button

**Comment by paloknapo** [comment]
**Colour Override toggle changes colour when active**

**Comment by paloknapo** [comment]
**Select group objects when entering edit mode**

**Comment by paloknapo** [comment]
**Focus to group in list view when leaving edit mode**

Same as in Issues

**Comment by paloknapo** [comment]
**Scale up card to get rid of scroll bar**

![untitled-1](https://user-images.githubusercontent.com/760452/37960161-cf17da94-31ac-11e8-9f2a-c5a0cceecdbb.png)

**Comment by paloknapo** [comment]
**Show number of objects in group and selected**
![untitled-1](https://user-images.githubusercontent.com/760452/37960256-1c36e978-31ad-11e8-95c9-9446e4cd6cdd.png)

**Comment by paloknapo** [comment]
**Add Select Objects button in edit mode**
![untitled-1](https://user-images.githubusercontent.com/760452/37960315-449a9194-31ad-11e8-9982-83393fba3f96.png)

**Comment by paloknapo** [comment]
**Display group colour bar next to the group name and make Colour Picker button gray**

Same as in Issues
![untitled-1](https://user-images.githubusercontent.com/760452/37960473-a435c97a-31ad-11e8-8e7d-19f4527e78c0.png)

**Comment by paloknapo** [comment]
**Clever pop up when user wants to overwrite large group with small selection**

**Comment by carmenfan** [comment]
The function now has an extra boolean to determine if things are forced to be highlighted
![image](https://user-images.githubusercontent.com/11945337/38358846-569bb5d6-38be-11e8-8e8a-091859000517.png)
usage:
![hl](https://user-images.githubusercontent.com/11945337/38358986-d97665a0-38be-11e8-9321-c326943a6922.gif)
