### ISSUE TITLE
v2.9.1 bug list

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#839]
- [x] [Status icon + assignment colour strip doesn't change until the issue is saved](https://github.com/3drepo/3drepo.io/issues/839#issuecomment-376473139)
- [x] [Issue search doesn't work correctly](https://github.com/3drepo/3drepo.io/issues/839#issuecomment-376474910)
- [x] [Screenshot on comments is broken](https://github.com/3drepo/3drepo.io/issues/839#issuecomment-376477906)
- [x] [Export BCF is broken](https://github.com/3drepo/3drepo.io/issues/839#issuecomment-377174086)
- [x] [BCF Imports with no description should should say `(No Description)`](https://github.com/3drepo/3drepo.io/issues/839#issuecomment-377175392)

**Comment by carmenfan** [comment]
**Status icon + assignment colour strip doesn't change until the issue is saved**
![issuebug](https://user-images.githubusercontent.com/11945337/37961533-7213fea0-31b0-11e8-9343-98a64c5f487f.gif)

**Comment by carmenfan** [comment]
**Issue search doesn't work correctly**
2 problems:
- searching type doesn't work.
- searching other values doesn't gives back all available results

This is my list of issues, I have 2 issue of type RFI:
![image](https://user-images.githubusercontent.com/11945337/37961762-0bed2434-31b1-11e8-99af-e2b7c388cf2b.png)

Searching "RFI" gives no results:
![image](https://user-images.githubusercontent.com/11945337/37961836-4108f2a6-31b1-11e8-8ddb-56d37291875c.png)


Searching test returns 1 result (when pretty much all of them are named "test")
![image](https://user-images.githubusercontent.com/11945337/37961863-50e4c862-31b1-11e8-8072-5b73c506acaf.png)

**Comment by carmenfan** [comment]
**Screenshot on comments is broken**
Screenshots are not created when you try to make one for comments
![screenshotbug](https://user-images.githubusercontent.com/11945337/37962440-0155c254-31b3-11e8-844a-060dbc94dd65.gif)

**Comment by carmenfan** [comment]
**Export BCF is broken**
![image](https://user-images.githubusercontent.com/11945337/38080569-befcfe12-3339-11e8-81f2-630cd5e2f034.png)

**Comment by carmenfan** [comment]
**BCF Imports with no description should should say `(No Description)`**

This is so that it's clear there is no description and the user has something to click on to change viewpoint.
