### ISSUE TITLE
Bug list 2.9.3

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#880]
- [x] [Double click background no longer goes back to extent (this should be a unity issue)](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-380065826)
- [x] [Double click on tree panel is broken with multi select](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-380067491) _(fixed in #830)_
- [x] [Groups panel is using the show all icon instead of isolate icon to represent isolate](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-380135917)
- [x] Typos on lite-dialog
- [x] Show objects when going into an issue if they're hidden
- [x] [Highlight selected group/groups in list](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-380748478)
- [x] [When entering group edit mode, ensure group objects are shown (if they were hidden before)](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-380873055)
- [x] [Create Issue should fail if create group fails](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-381097441)
- [x] [Remove console.log()](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-381101400)
- [x] [Some groups are saved without a model ID](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-381112144)
- [x] ifc_guid and shared_id both appear in DB entry for groups

UI Oddities:
- [x] [Delete button disappears when group is deleted](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-380478756)
- [x] [Focus on group name field when group is created](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-380480656)

Not fixing:
- [ ] [List of empty groups in some older models](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-380499916) - Artifacts from development / old issues
- [ ] [Groups: Colour override toggles off when entering edit mode](https://github.com/3drepo/3drepo.io/issues/880#issuecomment-380485438) - This could be problematic

**Comment by carmenfan** [comment]
**Double click background no longer goes back to extent (this should be unity issue)**
double clicking on background should go back to extent.

**Comment by carmenfan** [comment]
**Double click on tree panel is broken with multi select**
This is broken again.
![brokenmulti](https://user-images.githubusercontent.com/11945337/38554733-a6468894-3cbb-11e8-8b53-214eebc7e558.gif)

**Comment by carmenfan** [comment]
**Groups panel is using the show all icon instead of isolate icon to represent isolate**
![image](https://user-images.githubusercontent.com/11945337/38565485-5831411c-3cd9-11e8-803d-56bec19de91d.png)

**Comment by paloknapo** [comment]
**Delete button disappears when group is deleted**

![image](https://user-images.githubusercontent.com/760452/38624137-4483efb8-3d9f-11e8-85c1-1587ba7411fd.png)

Desired behaviour:
1. Select group
2. Delete group
3. Next group below (or above if none below) is selected
4. Delete group, keep deleting all groups if you like

**Comment by paloknapo** [comment]
**Focus on group name field when group is created**

So I can type name immediately for workflow like this:
1. Select objects
2. Hit + button on Groups card
3. Type name
4. Hit Save

**Comment by paloknapo** [comment]
**Use Isolate icon for isolating group**

![image](https://user-images.githubusercontent.com/760452/38624618-703f41f6-3da0-11e8-8431-de2d0dd8bfb3.png)

**Comment by paloknapo** [comment]
**Groups: Colour override toggles off when entering edit mode**

1. Turn on colour override
2. Go to edit mode
3. Colour override toggles off - should be on
4. Go back to groups list, colour override is off - should be on

Only user can toggle colour override on/off

**Comment by JamesMilnerUK** [comment]
@carmenfan @Charence not sure what we want to do about the icon as it's a hard coded SVG

**Comment by paloknapo** [comment]
**List of empty groups in some older models**

![image](https://user-images.githubusercontent.com/760452/38627725-8a35330c-3da7-11e8-9f37-34da8b12c9a4.png)

I suspect they are from BCF imports. For example:
https://dev.3drepo.io/CWCL/2133a7ee-8132-4b54-9c48-f040a7c859fe
https://dev.3drepo.io/Laika0302/d14731f9-4a9c-45d1-9dba-de9f6d3d57e9

**Comment by carmenfan** [comment]
I think it's likely that the issue was deleted thus the group was orphaned + untagged (esp on the models we tested BCF with, I manually deleted the issues very often). I wouldn't worry too much about it.

**Comment by Charence** [comment]
@carmenfan This shouldn't happen on production. I deleted issues on dev DB without deleting groups for testing on a number of models.

**Comment by paloknapo** [comment]
**Highlight selected group/groups in list**

In same fashion as in tree

![image](https://user-images.githubusercontent.com/760452/38670560-fee18590-3e40-11e8-92ab-8915fa2b99e7.png)

**Comment by carmenfan** [comment]
**When entering group edit mode, ensure group objects are shown (if they were hidden before)**
Putting this here so we don't forget.

**Comment by Charence** [comment]
**Issue saving should fail/provide user feedback if createGroups fails**

Check: IssueController.prototype.createGroup

**Comment by carmenfan** [comment]
Remove console.log()
![image](https://user-images.githubusercontent.com/11945337/38731462-345bd03c-3f12-11e8-9c3f-bef48016e21b.png)

**Comment by carmenfan** [comment]
**Some groups are saved without a model ID**
- Multi selected 2 sub models within a federation and the entries being sent to the back end contains no model ID
![image](https://user-images.githubusercontent.com/11945337/38732989-2c655488-3f18-11e8-9768-1620c431534c.png)
