### ISSUE TITLE
Bug list 2.9.4

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#903]
- [x] [Wrong units in Sample Project](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-381544770)
- [x] [TypeError: this[0].focus is not a function](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-381547261)
- [x] [Group error message says issue not group](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-381553763)
- [x] [Issues with visibility state isn't being displayed properly](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-381570066)
- [x] [Viewpoint doesn't go to the right place on issue link](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-381649656)
- [x] [TypeError: Cannot read property 'permissions' of undefined when loading issue](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-381921693)
- [x] [Delete multiple selected groups in one go](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-381971614)
- [x] [Select top group upon group deletion](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-382343494)
- [X] [Errors when you delete the last group](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-382758119)
- [x] [Objects stay highlgihted in group colour when the group has been deleted](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-382762997)

Not fixing:
- [ ] [Some windows don't change colour when you save the group](https://github.com/3drepo/3drepo.io/issues/903#issuecomment-382761978)

@Charence may have a fix for this on his branch

**Comment by paloknapo** [comment]
**Wrong units in Sample Project**

All models in the project are in MM not M.

![image](https://user-images.githubusercontent.com/760452/38802409-44d55f1a-4164-11e8-9962-20b0254f46bf.png)

**Comment by Charence** [comment]
**TypeError: this[0].focus is not a function**

I think this is something I caused by adding a dialog box for new T&Cs.

![screenshot 2018-04-16 11 00 23](https://user-images.githubusercontent.com/1438332/38802867-69964dc2-4165-11e8-868c-3633d7e9fe63.png)

**Comment by carmenfan** [comment]
**Group error message says issue not group**
![image](https://user-images.githubusercontent.com/11945337/38804092-187deb4e-4169-11e8-9445-6f5bb8f95b3a.png)

**Comment by carmenfan** [comment]
**Issues with visibility state isn't being displayed properly**
Less objects hidden than anticipated when issues are saved with isolate.
See the comments in https://dev.3drepo.io/carmen/6cb7debf-3b10-4941-87b3-2b6dc531f1b6/issues/349ff5b0-4169-11e8-994e-8b36a657c12c

**Comment by carmenfan** [comment]
**Viewpoint doesn't go to the right place on issue link**

for e.g.:
https://dev.3drepo.io/T_E_S_T/9197b38e-e1a5-4972-ae25-8be0756151b8/issues/9e348050-3f29-11e8-b73f-4dc2dfc55c0c

Loaded via issue link looks like this:
![image](https://user-images.githubusercontent.com/11945337/38820004-c6cad452-4194-11e8-9564-d5f08cd07ba6.png)


When the viewpoint should look like this:
![image](https://user-images.githubusercontent.com/11945337/38820018-cd140252-4194-11e8-9ec9-39843d3d5d0d.png)

**Comment by JamesMilnerUK** [comment]
```TypeError: Cannot read property 'permissions' of undefined``` when loading issue

**Comment by paloknapo** [comment]
**Delete multiple selected groups in one go**
Delete button deletes only one group at the time even if more selected. It should delete all selected groups.

**Comment by JamesMilnerUK** [comment]
@paloknapo asked we also select the top group upon deletion of groups

**Comment by carmenfan** [comment]
**Errors when you delete the last group**
![lastgroup](https://user-images.githubusercontent.com/11945337/38997927-71f8e064-43e6-11e8-992d-b723bc1c541d.gif)
x

**Comment by carmenfan** [comment]
**For some windows the window doesn't change colour when you save the group**
This only happens if the objects were windows (oddly) and if they are selected during edit mode.
![recolour](https://user-images.githubusercontent.com/11945337/38998670-f9720128-43e7-11e8-80dc-bd3d9692e99f.gif)

**Comment by carmenfan** [comment]
**Objects stay highlighted in group colour when the group has been deleted**
When you delete the last group, the color highlight remains (Maybe related to https://github.com/3drepo/3drepo.io/issues/903#issuecomment-382758119)
![image](https://user-images.githubusercontent.com/11945337/38998825-57fd515c-43e8-11e8-8d9f-da6f638f08d2.png)

**Comment by Charence** [comment]
I may have inadvertently fixed https://github.com/3drepo/3drepo.io/issues/903#issuecomment-382758119 and https://github.com/3drepo/3drepo.io/issues/903#issuecomment-382761978 on #895
