### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#975]
### Description
Adding views to 3D repo to allow people to have specific view points of a model

### Goals
- [x] Allow the user to save views 
- [x] Allow the user to go back to a saved view
- [x] Allow user to update a saved view

### Tasks
- [x] Frontend interface for saving and viewing views
- [x] Backend endpoints for saving and viewing views
- [x] Remove Mongoose from backend code
