### ISSUE TITLE
Check All API requests

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#976]
### Description
All parameters coming from API end points should be type checked. We should also reject any request that doesn't come in the right format (e.g. missing required parameters)

### Goals
- API requests missing required fields should fail (e.g. issue with no name)
- API requests with parameters with wrong type should fail (e.g. login username is a boolean, colour is not an array)

### Tasks

- Go through all end points and ensure parameters are type checked, throw error otherwise
- Go through all end points and enforce required parameters are provided, throw error otherwise
- Ensure there are backend tests for these scenarios.

### Files to go through
- [x] accountPermission.js (CF)
- [x] auth.js (CF)
- [x] config.js
- [x] group.js (CF)
- [ ] history.js
- [ ] invoice.js
- [ ] issue.js
- [ ] issueAnalytic.js
- [ ] job.js
- [x] maps.js (CW)
- [x] meta.js (CW)
- [x] model.js (CW)
- [ ] payment.js
- [ ] permissionTemplate.js
- [ ] plan.js
- [ ] project.js
- [ ] subscriptions.js
- [ ] teamspace.js
- [x] viewpoints.js (CW)

**Comment by carmenfan** [comment]
@Charence  I added an error code: 
```` js
	INVALID_ARGUMENTS: { message: "Missing or invalid arguments", status: 400 },
````

I guess we'll just claim one file at a time (when you're done with other stuff and hopefully can churn through it without too much pain!
